classdef ProjectionAlignmentSafeSolvePolicyTest < matlab.unittest.TestCase
    %ProjectionAlignmentSafeSolvePolicyTest Tests RD-7 actionability policy.

    properties (Constant)
        Tol = 1e-10
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src")));
        end
    end

    methods (Test)
        function testPassedReviewAndRejectedKeepSolverTruth(testCase)
            passing = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                12, false, 10, 4);
            review = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                3, false, 10, 1);
            rejected = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                2, false, 10, 1);

            testCase.verifyEqual(passing.Diagnostics.SafeSolvePolicy.Status, ...
                "passed");
            testCase.verifyTrue( ...
                passing.Diagnostics.SafeSolvePolicy.PreviewAllowed);
            testCase.verifyTrue( ...
                passing.Diagnostics.SafeSolvePolicy.ApplyAllowed);
            testCase.verifyFalse( ...
                passing.Diagnostics.SafeSolvePolicy.ConfirmationRequired);

            testCase.verifyEqual(review.Diagnostics.SafeSolvePolicy.Status, ...
                "review");
            testCase.verifyTrue( ...
                review.Diagnostics.SafeSolvePolicy.ApplyAllowed);
            testCase.verifyTrue( ...
                review.Diagnostics.SafeSolvePolicy.ConfirmationRequired);

            testCase.verifyEqual(rejected.Status, "solved");
            testCase.verifyTrue(rejected.Convergence.Success);
            testCase.verifyEqual( ...
                rejected.Diagnostics.SafeSolvePolicy.Status, "rejected");
            testCase.verifyTrue( ...
                rejected.Diagnostics.SafeSolvePolicy.PreviewAllowed);
            testCase.verifyFalse( ...
                rejected.Diagnostics.SafeSolvePolicy.ApplyAllowed);
            testCase.verifyTrue(any(contains( ...
                rejected.Diagnostics.SafeSolvePolicy.HardRejectionReasons, ...
                "hard minimum")));
        end

        function testMarginalAndNoOpCorrectionsRequireReview(testCase)
            marginal = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                12, false, 10, 9.5);
            noOpInput = ProjectionAlignmentSafeSolvePolicyTest. ...
                makeSolvedResult(12, false, 10, 10);
            noOpInput.SolvedCorrections. ...
                ViewVectorAngularOffsetsDegrees = [0 0 0];
            noOp = ProjectionAlignmentSafeSolvePolicy.apply( ...
                noOpInput, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual( ...
                marginal.Diagnostics.SafeSolvePolicy.Status, "review");
            testCase.verifyEqual( ...
                marginal.Diagnostics.SafeSolvePolicy. ...
                ResidualImprovementFraction, 0.05, ...
                AbsTol=ProjectionAlignmentSafeSolvePolicyTest.Tol);
            testCase.verifyEqual( ...
                marginal.Diagnostics.SafeSolvePolicy.ActiveObjectiveBefore, ...
                100);
            testCase.verifyEqual( ...
                marginal.Diagnostics.SafeSolvePolicy.ActiveObjectiveAfter, 1);
            testCase.verifyEqual( ...
                marginal.Diagnostics.SafeSolvePolicy.ActiveObjectiveChange, ...
                -99);
            testCase.verifyTrue(ProjectionAlignmentSafeSolvePolicy. ...
                isActionable(marginal));
            testCase.verifyEqual(noOp.Diagnostics.SafeSolvePolicy.Status, ...
                "review");
            testCase.verifyTrue(noOp.Diagnostics.SafeSolvePolicy.IsNoOp);
        end

        function testHardFailuresRejectWithoutRewritingConvergence(testCase)
            bound = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                12, true, 10, 1);
            degraded = ProjectionAlignmentSafeSolvePolicyTest.classify( ...
                12, false, 10, 10.5);
            unobservableInput = ProjectionAlignmentSafeSolvePolicyTest. ...
                makeSolvedResult(12, false, 10, 1);
            unobservableInput.Diagnostics.Observability.Solution. ...
                HasUnsupportedUnobservableMode = true;
            unobservable = ProjectionAlignmentSafeSolvePolicy.apply( ...
                unobservableInput, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                ProjectionAlignmentOptions.defaults());

            decisions = [bound.Diagnostics.SafeSolvePolicy ...
                degraded.Diagnostics.SafeSolvePolicy ...
                unobservable.Diagnostics.SafeSolvePolicy];
            testCase.verifyTrue(all(string({decisions.Status}) == ...
                "rejected"));
            testCase.verifyEqual([bound.Status degraded.Status ...
                unobservable.Status], ["solved" "solved" "solved"]);
            testCase.verifyTrue(all([bound.Convergence.Success ...
                degraded.Convergence.Success ...
                unobservable.Convergence.Success]));
            testCase.verifyTrue(any(contains( ...
                degraded.Diagnostics.SafeSolvePolicy. ...
                HardRejectionReasons, "degraded")));
        end

        function testForwardRayMetricAndUncertaintyAreReported(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 4, 0.1);
            result.Diagnostics.Comparison = struct( ...
                ForwardRay3D=struct(RmsBefore=4, RmsAfter=3.9));
            result.SolvedCorrections. ...
                ViewVectorAngularOffsetsDegrees = [1e-4 1e-4 1e-4];
            result.Diagnostics.Observability.Solution. ...
                EffectiveAttitudeCovariance = 0.01 * eye(3);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                ProjectionAlignmentOptions.defaults());

            decision = result.Diagnostics.SafeSolvePolicy;
            testCase.verifyEqual(decision.Status, "review");
            testCase.verifyEqual(decision.RmsAfter, 3.9, ...
                AbsTol=ProjectionAlignmentSafeSolvePolicyTest.Tol);
            testCase.verifyEqual(decision.ResidualMetric, "forwardRay3D");
            testCase.verifyTrue( ...
                decision.CorrectionSmallRelativeToUncertainty);
        end

        function testNonconvergenceAndConfiguredUncertaintyLimitsReject(testCase)
            nonconvergedInput = ProjectionAlignmentSafeSolvePolicyTest. ...
                makeSolvedResult(12, false, 10, 1);
            nonconvergedInput.Status = "failed";
            nonconvergedInput.Convergence.Status = "failed";
            nonconvergedInput.Convergence.Success = false;
            nonconverged = ProjectionAlignmentSafeSolvePolicy.apply( ...
                nonconvergedInput, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                ProjectionAlignmentOptions.defaults());

            conditionInput = ProjectionAlignmentSafeSolvePolicyTest. ...
                makeSolvedResult(12, false, 10, 1);
            limitedOptions = struct(SafeSolvePolicy=struct( ...
                MaximumConditionNumber=5, ...
                MaximumAttitudeStandardDeviationDegrees=5e-4));
            uncertaintyLimited = ProjectionAlignmentSafeSolvePolicy.apply( ...
                conditionInput, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                limitedOptions);

            testCase.verifyEqual( ...
                nonconverged.Diagnostics.SafeSolvePolicy.Status, "rejected");
            testCase.verifyFalse(nonconverged.Convergence.Success);
            testCase.verifyFalse(nonconverged.Diagnostics. ...
                SafeSolvePolicy.ApplyAllowed);
            testCase.verifyEqual(uncertaintyLimited.Diagnostics. ...
                SafeSolvePolicy.Status, "rejected");
            testCase.verifyTrue(any(contains(uncertaintyLimited.Diagnostics. ...
                SafeSolvePolicy.HardRejectionReasons, "Condition number")));
            testCase.verifyTrue(any(contains(uncertaintyLimited.Diagnostics. ...
                SafeSolvePolicy.HardRejectionReasons, ...
                "Attitude standard deviation")));
        end

        function testLegacyPreferenceOptionMigratesAndCanBeDisabled(testCase)
            legacy = ProjectionAlignmentOptions.validate(struct( ...
                SafeSolvePolicy=struct( ...
                MinResidualImprovementFraction=[])));
            current = ProjectionAlignmentOptions.validate(struct( ...
                SafeSolvePolicy=struct( ...
                MinResidualImprovementFraction=0.2, ...
                PreferredResidualImprovementFraction=0.3)));
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 10, 10);
            result.SolvedCorrections. ...
                ViewVectorAngularOffsetsDegrees = [0.01 0.02 0.03];
            result = ProjectionAlignmentSafeSolvePolicy.apply(result, ...
                ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12), ...
                legacy);

            testCase.verifyFalse(isfield(legacy.SafeSolvePolicy, ...
                "MinResidualImprovementFraction"));
            testCase.verifyEmpty(legacy.SafeSolvePolicy. ...
                PreferredResidualImprovementFraction);
            testCase.verifyEqual(current.SafeSolvePolicy. ...
                PreferredResidualImprovementFraction, 0.3);
            testCase.verifyEqual(result.Diagnostics.SafeSolvePolicy.Status, ...
                "passed");
        end
    end

    methods (Static, Access = private)
        function result = classify(matchCount, boundHit, rmsBefore, rmsAfter)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                matchCount, boundHit, rmsBefore, rmsAfter);
            result = ProjectionAlignmentSafeSolvePolicy.apply(result, ...
                ProjectionAlignmentSafeSolvePolicyTest. ...
                makeMatchResult(matchCount), ...
                ProjectionAlignmentOptions.defaults());
        end

        function result = makeSolvedResult( ...
                matchCount, boundHit, rmsBefore, rmsAfter)
            result = struct();
            result.Status = "solved";
            result.Matches = struct( ...
                Pair=[1 2], MovingPoints=zeros(matchCount, 2), ...
                ReferencePoints=zeros(matchCount, 2), ...
                MovingProjectionPoints=zeros(matchCount, 2), ...
                ReferenceProjectionPoints=zeros(matchCount, 2), ...
                Scores=ones(matchCount, 1), ...
                DescriptorIndices=[(1:matchCount).' (1:matchCount).'], ...
                Count=matchCount);
            result.Residuals = struct( ...
                LossMode="projectionPlane2D", Unit="planeMeters", ...
                Before=rmsBefore * ones(1, matchCount), ...
                After=rmsAfter * ones(1, matchCount), ...
                PerPair=struct(Pair=[1 2], ...
                Before=rmsBefore * ones(1, matchCount), ...
                After=rmsAfter * ones(1, matchCount), Count=matchCount));
            result.SolvedCorrections = struct( ...
                LayerIndex=2, ...
                ViewVectorAngularOffsetsDegrees=[0.01 0.02 0.03], ...
                ProjectionOffsetMeters=[0 0], SharedScale=1);
            result.Convergence = struct( ...
                Status="converged", Success=true, Iterations=3, ...
                FunctionEvaluations=8, ExitFlag=1, Objective=1, ...
                FirstOrderOptimality=1e-6, Message="done");
            result.Warnings = strings(1, 0);
            result.Diagnostics = struct(AnyBoundHit=boundHit, ...
                RmsBefore=rmsBefore, RmsAfter=rmsAfter, ...
                ActiveObjective=struct(Before=100, After=1, Change=-99), ...
                Observability=struct(Solution=struct( ...
                ConditionNumber=10, ...
                HasUnsupportedUnobservableMode=false, ...
                EffectiveAttitudeCovariance=1e-6 * eye(3))));
            result = ProjectionAlignmentResult.validate(result);
        end

        function matchResult = makeMatchResult(matchCount)
            matchResult = struct(Matches=struct( ...
                Pair=[1 2], Count=matchCount));
        end
    end
end
