classdef ProjectionDenseSurfaceSyntheticTestSupport
    %ProjectionDenseSurfaceSyntheticTestSupport Small public synthetic fixtures.

    methods (Static)
        function config = config()
            %config Return independently selected public test configuration.
            config = struct();
            config.schema_version = 1;
            config.fixture = struct( ...
                source_image_path="test_data/public_texture.tif", ...
                reserved_source_image_paths="test_data/reserved_texture.tif", ...
                random_seed=17);
            config.image = struct(rows=101, columns=301, view_count=3, ...
                instantaneous_line_axis="rows", scan_axis="columns", ...
                scan_rate_lines_per_second=200, cross_track_fov_degrees=2, ...
                focal_length_meters=0.2, source_band_sequence=[1 2 3]);
            config.world_frame = struct( ...
                x_axis_definition="nominal-flight-forward", ...
                y_axis_definition="right-of-flight", z_axis_definition="up", ...
                platform_x_axis_definition="nose-forward", ...
                platform_y_axis_definition="right-wing", ...
                platform_z_axis_definition="down");
            config.platform = struct(height_above_ground_meters=1000, ...
                forward_velocity_meters_per_second=50, ...
                nominal_off_nadir_degrees=60, target_side="right");
            config.gimbal = struct(zero_boresight_axis="platform-positive-z", ...
                rotation_order=["roll" "pitch"], ...
                roll_axis="platform-positive-x", ...
                pitch_axis="roll-gimbal-positive-y", ...
                positive_rotation_convention="right-hand", ...
                pitch_field_of_regard_degrees=[-30 30], ...
                maximum_initial_forward_pitch_degrees=20, ...
                ideal_encoder_and_mounting=true);
            config.collection_planner = struct( ...
                desired_scene_center_separation_degrees=1, ...
                allow_separation_expansion=true, constant_inter_image_gap=true, ...
                retrace_time_seconds=0.1, minimum_slant_range_meters=100, ...
                maximum_slant_range_meters=4800, ...
                stop_for_user_on_infeasible_geometry=true);
            config.sampling = struct(maximum_oversampling_per_axis=4, ...
                derive_range=true, minimum_reflection_tiles_rows=3, ...
                minimum_reflection_tiles_columns=3, ...
                maximum_reflection_tiles_rows=31, ...
                maximum_reflection_tiles_columns=31, ...
                prefer_odd_tile_counts=true, logical_reflection_addressing=true);
            config.terrain = struct( ...
                model="asymmetric-windowed-radial-sinc-composite", ...
                minimum_height_meters=-10, maximum_height_meters=20, ...
                characteristic_lengths_meters=[40 90], ...
                asymmetry_weights=[1 0.2], require_occlusion=true);
            config.truth_turbulence = struct( ...
                model="deterministic-gauss-markov", ...
                position_rms_meters_per_axis=0.1, ...
                attitude_rms_degrees_per_axis=0.001, ...
                correlation_time_seconds=1);
            gnss = struct(class="public-nominal-code-solution", update_rate_hz=2, ...
                horizontal_position_sigma_meters=1, ...
                vertical_position_sigma_meters=2, ...
                velocity_sigma_meters_per_second=0.1, ...
                correlation_time_seconds=1);
            tactical = struct(gyro_bias_sigma_degrees_per_hour=2, ...
                gyro_angle_random_walk_degrees_per_sqrt_hour=0.2, ...
                accelerometer_bias_sigma_mg=0.2, ...
                accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour=0.1);
            navigation = struct(gyro_bias_sigma_degrees_per_hour=0.2, ...
                gyro_angle_random_walk_degrees_per_sqrt_hour=0.05, ...
                accelerometer_bias_sigma_mg=0.05, ...
                accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour=0.02);
            config.navigation = struct(aiding_mode="nominal-non-rtk-gnss", ...
                gnss=gnss, bias_draw_scope="one-sortie", ...
                presets=struct(tactical_grade_imu=tactical, ...
                navigation_grade_imu=navigation));
            config.acceptance = struct( ...
                modes=["pointing-only" "combined-navigation-error"], ...
                establish_thresholds_after_first_full_scale_baseline=true, ...
                record_metrics=["coverage" "repeatability"]);
            config.output = struct(directory="artifacts/public_synthetic", ...
                default_image_format="tiff", ...
                supported_image_formats=["tiff" "png"], ...
                preserve_source_integer_class=true, ...
                write_compact_mat_truth=true, write_json_run_summary=true);
            config.future = struct( ...
                reserve_maximum_images_within_for_mode=true, ...
                reserve_degraded_gps_mode=true, ...
                reserve_independent_passes_mode=true, ...
                reserve_piecewise_linear_orbit_mode=true, ...
                reserve_curved_orbit_mode=true, ...
                reserve_time_varying_opk_posts=true);
        end

        function [config, plan] = plan(sourceImageSize)
            %plan Return the public config and its feasible collection plan.
            if nargin < 1
                sourceImageSize = [128 136 3];
            end
            config = ProjectionDenseSurfaceSyntheticTestSupport.config();
            plan = ProjectionDenseSurfaceSyntheticPlanner.plan( ...
                config, sourceImageSize);
        end

        function [config, plan, sourceImage] = generatorFixture()
            %generatorFixture Return a small full-render public fixture.
            config = ProjectionDenseSurfaceSyntheticTestSupport.config();
            config.image.rows = 33;
            config.image.columns = 49;
            config.image.scan_rate_lines_per_second = 100;
            [x, y] = meshgrid(1:36, 1:32);
            sourceImage = cat(3, uint8(mod(x + 3 * y, 251)), ...
                uint8(mod(2 * x + 5 * y, 251)), ...
                uint8(mod(7 * x + y, 251)));
            plan = ProjectionDenseSurfaceSyntheticPlanner.plan( ...
                config, size(sourceImage));
        end

        function [config, run, navigation] = acceptanceFixture()
            %acceptanceFixture Return a textured public alignment fixture.
            config = ProjectionDenseSurfaceSyntheticTestSupport.config();
            config.image.rows = 160;
            config.image.columns = 224;
            config.image.scan_rate_lines_per_second = 200;
            config.image.source_band_sequence = [1 1 1];
            stream = RandStream("mt19937ar", Seed=91);
            texture = imgaussfilt(rand(stream, 192, 208), 0.7);
            texture = uint8(round(255 * mat2gray(texture)));
            sourceImage = cat(3, texture, uint8(255 - texture), texture);
            plan = ProjectionDenseSurfaceSyntheticPlanner.plan( ...
                config, size(sourceImage));
            run = ProjectionDenseSurfaceSyntheticGenerator.generate( ...
                config, plan, sourceImage, struct(WriteFiles=false, ...
                RowChunkSize=80, ColumnChunkSize=112));
            navigation = ...
                ProjectionDenseSurfaceSyntheticNavigation.createFromResult( ...
                config, run);
        end
    end
end
