classdef ProjectionDenseSurfaceExtractorTest < matlab.unittest.TestCase
    %ProjectionDenseSurfaceExtractorTest Tests dense SGM ray triangulation.

    properties (Constant)
        HeightToleranceMeters = 3
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src")));
        end
    end

    methods (TestMethodSetup)
        function closeDenseSurfaceWindows(testCase)
            testCase.addTeardown(@() ...
                ProjectionDenseSurfaceExtractorTest.closeFigures());
            ProjectionDenseSurfaceExtractorTest.closeFigures();
        end
    end

    methods (Test)
        function testExtractsKnownElevatedPlane(testCase)
            testCase.assumeTrue(exist("disparitySGM", "file") == 2);
            [scene, working, matches, expectedHeight] = ...
                ProjectionDenseSurfaceExtractorTest.stereoFixture();
            options = struct(DisparityRange=[0 16], ...
                UniquenessThreshold=0, MaximumSurfacePoints=20000);

            result = ProjectionDenseSurfaceExtractor.extract( ...
                scene, working, matches, options);

            disparities = result.Disparity(result.ValidDisparityMask);
            heights = result.Surface.HeightMeters(result.Surface.ValidMask);
            testCase.verifyEqual(result.Status, "succeeded");
            testCase.verifyEqual(result.Diagnostics.Execution, "cpu");
            testCase.verifyGreaterThan(numel(disparities), 500);
            testCase.verifyEqual(double(median(disparities)), 4, AbsTol=0.75);
            testCase.verifyGreaterThan(numel(heights), 100);
            testCase.verifyEqual(median(heights), expectedHeight, ...
                AbsTol=ProjectionDenseSurfaceExtractorTest. ...
                HeightToleranceMeters);
            testCase.verifyFalse( ...
                result.Diagnostics.ProjectionOffsetsAppliedToRays);
            testCase.verifyFalse(result.Diagnostics.GpuInfo.Requested);
        end

        function testGpuRequestUsesCapabilityCheckedCpuEquivalentPath(testCase)
            testCase.assumeTrue(exist("disparitySGM", "file") == 2);
            [scene, working, matches] = ...
                ProjectionDenseSurfaceExtractorTest.stereoFixture();
            baseOptions = struct(DisparityRange=[0 16], ...
                UniquenessThreshold=0, MaximumSurfacePoints=20000);
            gpuOptions = baseOptions;
            gpuOptions.UseGPU = true;
            cpu = ProjectionDenseSurfaceExtractor.extract( ...
                scene, working, matches, baseOptions);
            gpuRequested = ProjectionDenseSurfaceExtractor.extract( ...
                scene, working, matches, gpuOptions);
            expectedGpuInfo = ProjectionGpuSupport.resolve(true);
            expectedExecution = ...
                ProjectionDenseSurfaceExtractorTest.expectedExecution( ...
                expectedGpuInfo);
            commonFinite = isfinite(cpu.Disparity) & ...
                isfinite(gpuRequested.Disparity);

            testCase.verifyEqual(gpuRequested.Diagnostics.GpuInfo, ...
                expectedGpuInfo);
            testCase.verifyEqual(gpuRequested.Diagnostics.Execution, ...
                expectedExecution);
            testCase.verifyEqual(gpuRequested.ValidDisparityMask, ...
                cpu.ValidDisparityMask);
            testCase.verifyEqual(gpuRequested.Disparity(commonFinite), ...
                cpu.Disparity(commonFinite), AbsTol=1e-5);
        end

        function testRejectsTooFewAcceptedMatches(testCase)
            [scene, working, matches] = ...
                ProjectionDenseSurfaceExtractorTest.stereoFixture();
            matches.Count = 2;
            matches.MovingSourceRows = matches.MovingSourceRows(1:2);
            matches.MovingSourceColumns = matches.MovingSourceColumns(1:2);
            matches.ReferenceSourceRows = matches.ReferenceSourceRows(1:2);
            matches.ReferenceSourceColumns = ...
                matches.ReferenceSourceColumns(1:2);

            testCase.verifyError(@() ...
                ProjectionDenseSurfaceExtractor.extract( ...
                scene, working, matches), ...
                "ProjectionDenseSurfaceExtractor:insufficientMatches");
        end

        function testViewerShowsIntensityAndSurfaceWindows(testCase)
            testCase.assumeTrue(exist("disparitySGM", "file") == 2);
            testCase.assumeTrue(exist("imageshow", "file") == 2);
            [scene, working, matches] = ...
                ProjectionDenseSurfaceExtractorTest.stereoFixture();
            result = ProjectionDenseSurfaceExtractor.extract( ...
                scene, working, matches, struct(DisparityRange=[0 16], ...
                UniquenessThreshold=0, MaximumSurfacePoints=20000));

            handles = ProjectionDenseSurfaceViewer.show(result);
            drawnow

            testCase.verifyTrue(isvalid(handles.IntensityViewer));
            testCase.verifyEqual(string(handles.IntensityViewer.Tag), ...
                "ProjectionViewerDenseSurfaceIntensityViewer");
            testCase.verifyTrue(isvalid(handles.SurfaceFigure));
            testCase.verifyEqual(string(handles.SurfaceFigure.Tag), ...
                "ProjectionViewerDenseSurfaceFigure");
            testCase.verifyTrue(isvalid(handles.SurfaceObject));
        end
    end

    methods (Static, Access = private)
        function [scene, pairWorking, pairMatch, surfaceHeight] = ...
                stereoFixture()
            imageSize = [72 128];
            disparityPixels = 4;
            surfaceHeight = 50;
            cameraHeight = 100;
            focalLength = 100;
            baseline = 4;
            center = ([imageSize(2), imageSize(1)] + 1) / 2;
            originalRng = rng;
            cleanup = onCleanup(@() rng(originalRng));
            rng(18, "twister");
            movingImage = imgaussfilt(rand(imageSize), 0.7);
            referenceImage = zeros(imageSize);
            referenceImage(:, 1:end-disparityPixels) = ...
                movingImage(:, 1+disparityPixels:end);
            clear cleanup

            scene = ProjectionViewerHarness.createSceneFromImages( ...
                {movingImage, referenceImage}, ["moving.tif", "reference.tif"], ...
                struct(RowStride=4, ColumnStride=4, ...
                DisplayTextureMaxPixels=Inf));
            plane = PlanarProjection.definePlaneFromBasis( ...
                zeros(3, 1), [1; 0; 0], [0; 1; 0]);
            origins = [-baseline / 2, baseline / 2];
            for layerIndex = 1:2
                layer = scene.layers(layerIndex);
                origin = [origins(layerIndex); 0; cameraHeight];
                layer.BaseProjectionPlane = plane;
                layer.CurrentProjectionPlane = plane;
                layer.SourceGeometry.ImageSize = imageSize;
                layer.SourceGeometry.SampleRayFcn = @(rows, columns) ...
                    ProjectionDenseSurfaceExtractorTest.pinholeRays( ...
                    origin, rows, columns, center, focalLength);
                scene.layers(layerIndex) = layer;
            end
            scene.layers = ProjectionLayerIdentity.ensureLayers(scene.layers);

            [columnGrid, rowGrid] = meshgrid(1:imageSize(2), 1:imageSize(1));
            planeX = columnGrid - center(1);
            planeY = rowGrid - center(2);
            movingSourceColumns = center(1) + ...
                (planeX - origins(1)) * focalLength / cameraHeight;
            referenceSourceColumns = center(1) + ...
                (planeX - origins(2)) * focalLength / cameraHeight;
            sourceRows = center(2) + planeY * focalLength / cameraHeight;
            movingMask = movingSourceColumns >= 1 & ...
                movingSourceColumns <= imageSize(2);
            referenceMask = referenceSourceColumns >= 1 & ...
                referenceSourceColumns <= imageSize(2);
            movingLayer = struct(LayerIndex=1, ...
                LayerId=string(scene.layers(1).LayerId), AnalysisBand=1, ...
                Image=movingImage, ValidMask=movingMask, ...
                PlaneCoordinates=[planeX(:).'; planeY(:).'], ...
                SourceRows=sourceRows, SourceColumns=movingSourceColumns, ...
                SourceObservationMask=movingMask, MeshSummary=struct());
            referenceLayer = struct(LayerIndex=2, ...
                LayerId=string(scene.layers(2).LayerId), AnalysisBand=1, ...
                Image=referenceImage, ValidMask=referenceMask, ...
                PlaneCoordinates=[planeX(:).'; planeY(:).'], ...
                SourceRows=sourceRows, SourceColumns=referenceSourceColumns, ...
                SourceObservationMask=referenceMask, MeshSummary=struct());
            ids = string([scene.layers.LayerId]);
            pairWorking = struct(Pair=[1 2], PairLayerIds=ids, ...
                MovingLayerId=ids(1), ReferenceLayerId=ids(2), ...
                PairDirection="movingToReference", OutputSize=imageSize, ...
                NumericalMode="fullSourceInverseWarp", ...
                ProjectionPlane=plane, OutputGrid=struct(), ...
                PixelToPlane=struct(X=planeX, Y=planeY, ...
                Coordinates=[planeX(:).'; planeY(:).']), ...
                LayerImages=[movingLayer referenceLayer], ...
                LayerMasks=cat(3, movingMask, referenceMask), ...
                OverlapMask=struct(Mask=movingMask & referenceMask), ...
                GridKey="dense-surface-test", RenderPlanSummary=struct());

            movingX = [28; 44; 60; 76; 92; 108];
            movingY = [20; 28; 36; 44; 52; 60];
            referenceX = movingX - disparityPixels;
            worldX = (movingX - center(1)) * ...
                (cameraHeight - surfaceHeight) / cameraHeight + origins(1);
            worldY = (movingY - center(2)) * ...
                (cameraHeight - surfaceHeight) / cameraHeight;
            movingColumns = center(1) + ...
                (worldX - origins(1)) * focalLength / ...
                (cameraHeight - surfaceHeight);
            referenceColumns = center(1) + ...
                (worldX - origins(2)) * focalLength / ...
                (cameraHeight - surfaceHeight);
            sourceMatchRows = center(2) + worldY * focalLength / ...
                (cameraHeight - surfaceHeight);
            pairMatch = struct(Pair=[1 2], PairLayerIds=ids, ...
                Count=numel(movingX), MovingSourceRows=sourceMatchRows, ...
                MovingSourceColumns=movingColumns, ...
                ReferenceSourceRows=sourceMatchRows, ...
                ReferenceSourceColumns=referenceColumns, ...
                MovingFeatureLocations=[movingX movingY], ...
                ReferenceFeatureLocations=[referenceX movingY]);
        end

        function [origins, vectors] = pinholeRays( ...
                origin, rows, columns, center, focalLength)
            count = numel(rows);
            origins = repmat(origin, 1, count);
            vectors = [(double(columns(:)).' - center(1)) / focalLength; ...
                (double(rows(:)).' - center(2)) / focalLength; ...
                -ones(1, count)];
        end

        function closeFigures()
            delete(findall(groot, "Tag", ...
                "ProjectionViewerDenseSurfaceIntensityViewer"));
            delete(findall(groot, "Tag", ...
                "ProjectionViewerDenseSurfaceFigure"));
        end

        function execution = expectedExecution(gpuInfo)
            execution = "cpu";
            if gpuInfo.Enabled
                execution = "gpu";
            end
        end
    end
end
