classdef ProjectionProceduralAnaglyphTest < matlab.unittest.TestCase
    %ProjectionProceduralAnaglyphTest C2 production golden-parity oracle.

    methods (TestClassSetup)
        function addPaths(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(root));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(root, "src")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(root, "tests")));
        end
    end

    methods (Test)
        function testOutputGridReconstructsThePhysicalPlane(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            expected = PlanarProjection.reconstruct3d( ...
                result.OutputGrid.PlaneCoordinates, fixture.Plane);
            productionCoordinates = PlanarProjection.worldToPlane( ...
                result.OutputGrid.WorldPoints, fixture.Plane);

            testCase.verifyEqual(result.OutputGrid.WorldPoints, expected, ...
                AbsTol=1e-12);
            testCase.verifyEqual(result.OutputGrid.PlaneCoordinates, ...
                productionCoordinates, AbsTol=1e-12);
            testCase.verifyEqual(size(result.OutputGrid.X), ...
                fixture.Options.OutputSize);
            testCase.verifyEqual(result.Precision, "double");
            testCase.verifyFalse( ...
                result.Presentation.PhysicalGeometryChanged);
        end

        function testInverseCoordinatesValuesAndMasksMatchProduction(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);

            for index = 1:2
                layer = fixture.Scene.layers(index);
                mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                    layer, fixture.Plane, fixture.Scene.renderOrigin);
                model = ProjectionFullSourceInverseWarp.prepare( ...
                    mesh, fixture.Plane, size(fixture.Images{index}));
                query = result.CoordinateMaps(index). ...
                    DisplayQueryPlaneCoordinates;
                mapping = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                    model, query, fixture.Options.OutputSize);
                [image, mask] = ProjectionFullSourceInverseWarp.sampleImage( ...
                    fixture.Images{index}, mapping, ...
                    fixture.Options.Interpolation, ...
                    fixture.Options.InvalidFillValue);

                testCase.verifyEqual( ...
                    result.CoordinateMaps(index).RowCoordinates, ...
                    mapping.RowCoordinates, AbsTol=1e-10);
                testCase.verifyEqual( ...
                    result.CoordinateMaps(index).ColumnCoordinates, ...
                    mapping.ColumnCoordinates, AbsTol=1e-10);
                testCase.verifyEqual(result.Masks{index}, mask);
                testCase.verifyEqual(result.Images{index}, image, ...
                    AbsTol=1e-10);
            end
        end

        function testPhysicalEyeAssignmentMatchesProductionController(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            viewIds = string({fixture.Sources.ViewId});
            identity = ProjectionViewMetadata.pairIdentity( ...
                viewIds(1), viewIds(2));
            controller = ProjectionStereoEyeController();
            production = controller.resolve(identity.PairId, viewIds, ...
                horzcat(fixture.Sources.ViewOrigin), ...
                result.Presentation.CameraRightVector);

            testCase.verifyEqual(result.EyeAssignment.LeftViewId, ...
                production.LeftViewId);
            testCase.verifyEqual(result.EyeAssignment.RightViewId, ...
                production.RightViewId);
            testCase.verifyEqual(result.EyeAssignment.ProjectionRatio, ...
                production.ProjectionRatio, AbsTol=1e-12);
            testCase.verifyEqual(result.EyeAssignment.IsDegenerate, ...
                production.IsDegenerate);
        end

        function testLayerOrderDoesNotChangePhysicalRedCyanResult(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            forward = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            reverse = proceduralTwoImageAnaglyph( ...
                fixture.Images([2 1]), fixture.Plane, fixture.Camera, ...
                fixture.Sources([2 1]), fixture.Options);

            testCase.verifyEqual(reverse.EyeAssignment.LeftViewId, ...
                forward.EyeAssignment.LeftViewId);
            testCase.verifyEqual(reverse.EyeAssignment.RightViewId, ...
                forward.EyeAssignment.RightViewId);
            testCase.verifyEqual(reverse.Anaglyph, forward.Anaglyph, ...
                AbsTol=1e-12);
            testCase.verifyEqual(reverse.ValidMask, forward.ValidMask);
        end

        function testDisplayOffsetsMatchProductionAndLeaveGridFixed(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            fixture.Options.StereoExaggeration = 1.75;
            fixture.Options.ScreenDepthOffsetMeters = 0.025;
            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            viewIds = string({fixture.Sources.ViewId});
            before = fixture.Plane.P0 + fixture.Plane.basis * ...
                result.OutputGrid.PlaneCoordinates;

            for index = 1:2
                if viewIds(index) == result.EyeAssignment.LeftViewId
                    channel = 1;
                else
                    channel = 3;
                end
                expected = ProjectionAnaglyphModel.presentationOffset( ...
                    result.Presentation.CameraRightVector, channel, ...
                    fixture.Camera.ViewWidthMeters, ...
                    fixture.Options.StereoExaggeration, ...
                    fixture.Options.ScreenDepthOffsetMeters, ...
                    fixture.Options.BaseSeparationFraction);
                testCase.verifyEqual( ...
                    result.Presentation.DisplayOffsetsWorld(:, index), ...
                    expected, AbsTol=1e-12);
            end
            testCase.verifyEqual(result.OutputGrid.WorldPoints, before, ...
                AbsTol=1e-12);
            testCase.verifyEqual(sum( ...
                result.Presentation.DisplayOffsetsWorld, 2), zeros(3, 1), ...
                AbsTol=1e-12);
        end

        function testCanonicalRedCyanCompositionMatchesProduction(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            viewIds = string({fixture.Sources.ViewId});
            left = find(viewIds == result.EyeAssignment.LeftViewId, 1);
            right = find(viewIds == result.EyeAssignment.RightViewId, 1);
            [production, mask] = ProjectionAnaglyphModel.composeRedCyan( ...
                result.Images{left}, result.Images{right}, ...
                result.Masks{left}, result.Masks{right}, ...
                fixture.Options.InvalidFillValue);

            testCase.verifyEqual(result.Anaglyph, production, AbsTol=1e-12);
            testCase.verifyEqual(result.ValidMask, mask);
            testCase.verifyEqual(result.Anaglyph(:, :, 2), ...
                result.Anaglyph(:, :, 3), AbsTol=1e-12);
        end

        function testViewerTextureHelperPreservesEstablishedContract(testCase)
            image = uint8(cat(3, [0 30; 60 90], ...
                [0 60; 120 180], [0 90; 180 255]));
            expectedGray = single(uint8(round(mean(double(image), 3)))) / 255;
            red = ProjectionAnaglyphModel.channelTexture(image, 1, 1.25, 0.08);
            blue = ProjectionAnaglyphModel.channelTexture(image, 3, 1.25, 0.08);

            testCase.verifyEqual(red(:, :, 1), ...
                min(single(1), single(0.08) + single(1.25) * expectedGray));
            testCase.verifyEqual(red(:, :, 2), ...
                single(0.08) * ones(2), AbsTol=eps("single"));
            testCase.verifyEqual(blue(:, :, 3), red(:, :, 1));
        end

        function testStrictInputsResourceLimitsAndPortableOutput(testCase)
            fixture = ProjectionProceduralAnaglyphTest.fixture();
            oversized = fixture.Options;
            oversized.MaxOutputPixels = 4;
            unknown = fixture.Options;
            unknown.HiddenState = true;
            invalid = fixture.Sources;
            invalid(1).ViewOrigin(1) = NaN;

            testCase.verifyError(@() proceduralTwoImageAnaglyph( ...
                fixture.Images, fixture.Plane, fixture.Camera, ...
                fixture.Sources, oversized), ...
                "proceduralTwoImageAnaglyph:resourceLimit");
            testCase.verifyError(@() proceduralTwoImageAnaglyph( ...
                fixture.Images, fixture.Plane, fixture.Camera, ...
                fixture.Sources, unknown), ...
                "proceduralTwoImageAnaglyph:invalidOptions");
            testCase.verifyError(@() proceduralTwoImageAnaglyph( ...
                fixture.Images, fixture.Plane, fixture.Camera, ...
                invalid, fixture.Options), ...
                "proceduralTwoImageAnaglyph:invalidSources");

            result = proceduralTwoImageAnaglyph(fixture.Images, ...
                fixture.Plane, fixture.Camera, fixture.Sources, ...
                fixture.Options);
            encoded = jsonencode(result);
            testCase.verifyNotEmpty(encoded);
            testCase.verifyFalse(contains(encoded, "function_handle"));
            testCase.verifyFalse(result.Provenance.RuntimeStateRetained);
            testCase.verifyFalse(result.Provenance.GuiUsed);
            testCase.verifyFalse(result.Provenance.CacheUsed);
        end
    end

    methods (Static, Access = private)
        function fixture = fixture()
            [rowGrid, columnGrid] = ndgrid(1:8, 1:10);
            first = 0.1 + 0.7 * (rowGrid - 1) / 7 + ...
                0.2 * (columnGrid - 1) / 9;
            second = 0.8 - 0.5 * (rowGrid - 1) / 7 + ...
                0.1 * (columnGrid - 1) / 9;
            images = {first, second};
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                images, ["oracle-a.tif" "oracle-b.tif"], ...
                struct(RowStride=1, ColumnStride=1));
            plane = scene.layers(1).CurrentProjectionPlane;
            sources = repmat(struct(ViewId="", ViewOrigin=zeros(3, 1), ...
                RowIndices=[], ColumnIndices=[], SampleFcn=[], ...
                ProjectionOffsetMeters=zeros(2, 1)), 1, 2);
            boundsByView = zeros(2, 2, 2);
            for index = 1:2
                layer = scene.layers(index);
                sources(index) = struct(ViewId="oracle-view-" + index, ...
                    ViewOrigin=layer.SourceGeometry.ReferenceOrigin, ...
                    RowIndices=layer.MeshSampling.RowIndices, ...
                    ColumnIndices=layer.MeshSampling.ColumnIndices, ...
                    SampleFcn=layer.SourceGeometry.SampleFcn, ...
                    ProjectionOffsetMeters=layer.ProjectionOffsetMeters);
                mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                    layer, plane, scene.renderOrigin);
                coordinates = PlanarProjection.worldToPlane( ...
                    reshape(mesh.WorldPoints, 3, []), plane);
                boundsByView(:, :, index) = [ ...
                    min(coordinates, [], 2) max(coordinates, [], 2)];
            end
            xBounds = [max(boundsByView(1, 1, :), [], "all") ...
                min(boundsByView(1, 2, :), [], "all")];
            yBounds = [max(boundsByView(2, 1, :), [], "all") ...
                min(boundsByView(2, 2, :), [], "all")];
            camera = struct(Position=scene.frameCamera.G0, ...
                Target=scene.frameCamera.G0 + scene.frameCamera.V0, ...
                UpVector=scene.frameCamera.focalPlane.basis(:, 2), ...
                ViewWidthMeters=xBounds(2) - xBounds(1));
            options = struct(OutputSize=[7 9], ...
                Bounds=struct(X=xBounds, Y=yBounds), ...
                Interpolation="bilinear", InvalidFillValue=0, ...
                StereoExaggeration=1, ScreenDepthOffsetMeters=0, ...
                BaseSeparationFraction=0.01);
            fixture = struct(Images={images}, Scene=scene, Plane=plane, ...
                Sources=sources, Camera=camera, Options=options);
        end
    end
end
