classdef ProjectionFailingDenseMatcherFixture < ProjectionDenseMatcher
    %ProjectionFailingDenseMatcherFixture Fail one pair after earlier evidence.

    properties (SetAccess = immutable)
        FailedPairId (1, 1) string
    end

    methods
        function matcher = ProjectionFailingDenseMatcherFixture(failedPairId)
            matcher.FailedPairId = string(failedPairId);
        end

        function metadata = metadata(~)
            metadata = struct(AlgorithmId="test.failure-capture", ...
                Name="Failure capture fixture", SemanticVersion="1.0.0", ...
                Capabilities=struct(Geometry="mappedGrid"), ...
                RequiredProducts=strings(1, 0), Deterministic=true, ...
                Precision="double", MemoryEstimate="constant", ...
                CpuSupported=true, GpuSupported=false);
        end

        function options = defaultOptions(~)
            options = struct(Count=4);
        end

        function options = validateOptions(~, options)
            if isempty(options)
                options = struct(Count=4);
            end
            if ~isstruct(options) || ~isscalar(options) || ...
                    ~isequal(string(fieldnames(options)), "Count") || ...
                    ~isnumeric(options.Count) || ~isscalar(options.Count) || ...
                    ~isfinite(options.Count) || options.Count < 1 || ...
                    fix(options.Count) ~= options.Count
                error("ProjectionFailingDenseMatcherFixture:invalidOptions", ...
                    "Options require one positive integer Count field.");
            end
            options.Count = double(options.Count);
        end
    end

    methods (Access = protected)
        function result = matchImpl(matcher, request, options, ~)
            if request.PairId == matcher.FailedPairId
                error("ProjectionFailingDenseMatcherFixture:injectedFailure", ...
                    "Injected pair failure for exportable evidence testing.");
            end
            indices = find(request.OverlapMask, options.Count, "first");
            result = struct( ...
                MovingSourceRows=request.SourceRows{1}(indices), ...
                MovingSourceColumns=request.SourceColumns{1}(indices), ...
                ReferenceSourceRows=request.SourceRows{2}(indices), ...
                ReferenceSourceColumns=request.SourceColumns{2}(indices), ...
                States=repmat("valid", numel(indices), 1), ...
                Score=zeros(numel(indices), 1), ...
                Confidence=ones(numel(indices), 1), ...
                Diagnostics=struct(Fixture=true), ...
                Execution=struct(Device="cpu"));
        end
    end
end
