classdef ProjectionAlignmentSafeSolvePolicyTest < matlab.unittest.TestCase
    %ProjectionAlignmentSafeSolvePolicyTest Tests safe solve result gating.

    properties (Constant)
        Tol = 1e-10
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            srcFolder = fullfile(projectRoot, "src");
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(srcFolder));
        end
    end

    methods (Test)
        function testPassingSolveRemainsActionable(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 10, 4);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "solved");
            testCase.verifyTrue(result.Convergence.Success);
            testCase.verifyEqual(result.Diagnostics.SafeSolvePolicy.Status, ...
                "passed");
            testCase.verifyTrue( ...
                ProjectionAlignmentSafeSolvePolicy.isActionable(result));
        end

        function testThreeToNineMatchesWarnButRemainActionable(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                3, false, 10, 1);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(3);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "solved");
            testCase.verifyTrue(result.Convergence.Success);
            testCase.verifyEqual( ...
                result.Diagnostics.SafeSolvePolicy.MinMatchCount, 3, ...
                AbsTol=ProjectionAlignmentSafeSolvePolicyTest.Tol);
            testCase.verifyEqual( ...
                result.Diagnostics.SafeSolvePolicy.Status, "warning");
            testCase.verifyTrue(any(contains(result.Warnings, ...
                "Low-confidence")));
            testCase.verifyTrue( ...
                ProjectionAlignmentSafeSolvePolicy.isActionable(result));
            testCase.verifyNotEmpty(result.SolvedCorrections);
        end

        function testFewerThanThreeMatchesFailsPolicy(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                2, false, 10, 1);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(2);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "failed");
            testCase.verifyFalse(result.Convergence.Success);
            testCase.verifyTrue(any(contains(result.Warnings, ...
                "hard minimum")));
            testCase.verifyFalse( ...
                ProjectionAlignmentSafeSolvePolicy.isActionable(result));
        end

        function testBoundHitFailsPolicy(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, true, 10, 1);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "failed");
            testCase.verifyEqual(result.Diagnostics.SafeSolvePolicy.Status, ...
                "failed");
            testCase.verifyTrue(any(contains(result.Warnings, ...
                "bound-limited")));
            testCase.verifyFalse( ...
                ProjectionAlignmentSafeSolvePolicy.isActionable(result));
        end

        function testResidualLimitedSolveFailsPolicy(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 10, 9.5);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "failed");
            testCase.verifyEqual( ...
                result.Diagnostics.SafeSolvePolicy.ResidualImprovementFraction, ...
                0.05, AbsTol=ProjectionAlignmentSafeSolvePolicyTest.Tol);
            testCase.verifyTrue(any(contains(result.Warnings, ...
                "residual-limited")));
        end

        function testPolicyUsesForwardRayDiagnosticsForEveryLoss(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 4, 0.1);
            result.Diagnostics.Comparison = struct( ...
                ForwardRay3D=struct(RmsBefore=4, RmsAfter=3.9));
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12);

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, ProjectionAlignmentOptions.defaults());

            testCase.verifyEqual(result.Status, "failed");
            testCase.verifyEqual(result.Diagnostics.SafeSolvePolicy.RmsAfter, ...
                3.9, AbsTol=ProjectionAlignmentSafeSolvePolicyTest.Tol);
            testCase.verifyEqual( ...
                result.Diagnostics.SafeSolvePolicy.ResidualMetric, ...
                "forwardRay3D");
            testCase.verifyTrue(any(contains(result.Warnings, ...
                "residual-limited")));
        end

        function testResidualImprovementThresholdCanBeDisabled(testCase)
            result = ProjectionAlignmentSafeSolvePolicyTest.makeSolvedResult( ...
                12, false, 10, 10);
            matchResult = ProjectionAlignmentSafeSolvePolicyTest.makeMatchResult(12);
            options = struct(SafeSolvePolicy=struct( ...
                MinResidualImprovementFraction=[]));

            result = ProjectionAlignmentSafeSolvePolicy.apply( ...
                result, matchResult, options);

            testCase.verifyEqual(result.Status, "solved");
            testCase.verifyEqual(result.Diagnostics.SafeSolvePolicy.Status, ...
                "passed");
        end
    end

    methods (Static, Access = private)
        function result = makeSolvedResult(matchCount, boundHit, rmsBefore, rmsAfter)
            result = struct();
            result.Status = "solved";
            result.Matches = struct( ...
                Pair=[1 2], ...
                MovingPoints=zeros(matchCount, 2), ...
                ReferencePoints=zeros(matchCount, 2), ...
                MovingProjectionPoints=zeros(matchCount, 2), ...
                ReferenceProjectionPoints=zeros(matchCount, 2), ...
                Scores=ones(matchCount, 1), ...
                DescriptorIndices=[(1:matchCount).' (1:matchCount).'], ...
                Count=matchCount);
            result.Residuals = struct( ...
                LossMode="projectionPlane2D", ...
                Unit="planeMeters", ...
                Before=rmsBefore * ones(1, matchCount), ...
                After=rmsAfter * ones(1, matchCount), ...
                PerPair=struct(Pair=[1 2], ...
                Before=rmsBefore * ones(1, matchCount), ...
                After=rmsAfter * ones(1, matchCount), Count=matchCount));
            result.SolvedCorrections = struct( ...
                LayerIndex=2, ...
                ViewVectorAngularOffsetsDegrees=[0.01 0.02 0.03], ...
                ProjectionOffsetMeters=[0 0], ...
                SharedScale=1);
            result.Convergence = struct( ...
                Status="converged", Success=true, Iterations=3, ...
                FunctionEvaluations=8, ExitFlag=1, Objective=1, ...
                FirstOrderOptimality=1e-6, Message="done");
            result.Warnings = strings(1, 0);
            result.Diagnostics = struct( ...
                AnyBoundHit=boundHit, ...
                RmsBefore=rmsBefore, ...
                RmsAfter=rmsAfter);
            result = ProjectionAlignmentResult.validate(result);
        end

        function matchResult = makeMatchResult(matchCount)
            matchResult = struct();
            matchResult.Matches = struct(Pair=[1 2], Count=matchCount);
        end
    end
end
