classdef ProjectionDenseAssociationFixture
    %ProjectionDenseAssociationFixture Privacy-safe scalable association data.

    methods (Static)
        function request = benchmarkRequest(recordsPerPair, viewCount)
            arguments
                recordsPerPair (1, 1) double {mustBeInteger, mustBePositive}
                viewCount (1, 1) double {mustBeInteger, mustBeGreaterThanOrEqual(viewCount, 2)} = 5
            end
            pairs = nchoosek(1:viewCount, 2);
            recordCount = size(pairs, 1) * recordsPerPair;
            records = repmat(ProjectionDenseAssociationFixture.emptyRecord(), ...
                1, recordCount);
            viewIds = "view-" + (1:viewCount);
            passIds = "pass-" + ceil((1:viewCount) / 2);
            viewOffset = (1:viewCount) - (viewCount + 1) / 2;
            origins = [12 * viewOffset; 4 * (-1) .^ (1:viewCount); ...
                zeros(1, viewCount)];
            cursor = 0;
            for pairIndex = 1:size(pairs, 1)
                pair = pairs(pairIndex, :);
                for featureIndex = 1:recordsPerPair
                    cursor = cursor + 1;
                    point = [0.02 * featureIndex; ...
                        0.01 * mod(featureIndex, 17); ...
                        100 + 0.005 * featureIndex];
                    source = [100 + 0.25 * featureIndex + pair; ...
                        200 + 0.125 * featureIndex + 0.5 * pair].';
                    records(cursor) = struct( ...
                        RecordId=sprintf("record-%02d-%06d", ...
                        pairIndex, featureIndex), ...
                        PairId=sprintf("pair:%d-%d", pair(1), pair(2)), ...
                        ViewIds=viewIds(pair), PassIds=passIds(pair), ...
                        ObservationIds=repmat(sprintf( ...
                        "feature-%06d", featureIndex), 1, 2), ...
                        SourceObservationsPixels=source, ...
                        RayOriginsWorld=origins(:, pair), ...
                        RayVectorsWorld=point - origins(:, pair), ...
                        MatchState="valid", Score=0, Confidence=0.9, ...
                        TextureScore=0.8, NavigationWeights=[0.9 0.9], ...
                        RadiometricValues=[featureIndex featureIndex], ...
                        RadiometricConsistency=0.95, ...
                        VisibilityStates=["visible" "visible"], ...
                        ProvisionalPointWorld=point, ...
                        PairwiseCovarianceWorldMetersSquared=eye(3), ...
                        ModeId="");
                end
            end
            request = struct( ...
                Format=ProjectionDenseObservationAssociator.RequestFormat, ...
                Version=ProjectionDenseObservationAssociator.RequestVersion, ...
                WorldFrame="fixtureWorld", Records=records);
        end

        function request = semanticRequest()
            request = ProjectionDenseAssociationFixture.benchmarkRequest(4, 5);
            rejected = request.Records(1);
            rejected.RecordId = "record-rejected-texture";
            rejected.ObservationIds = ["rejected-a" "rejected-b"];
            rejected.MatchState = "insufficientTexture";
            rejected.TextureScore = 0;
            disconnected = request.Records(1);
            disconnected.RecordId = "record-disconnected";
            disconnected.PairId = "pair:disconnected";
            disconnected.ObservationIds = ["isolated-a" "isolated-b"];
            conflict = request.Records(2);
            conflict.RecordId = "record-duplicate-view-conflict";
            conflict.PairId = "pair:conflict";
            conflict.ViewIds = [request.Records(2).ViewIds(1) ...
                request.Records(2).ViewIds(2)];
            conflict.PassIds = [request.Records(2).PassIds(1) ...
                request.Records(2).PassIds(2)];
            conflict.ObservationIds = ["alternate-same-view" ...
                request.Records(2).ObservationIds(2)];
            conflict.SourceObservationsPixels(1, :) = ...
                conflict.SourceObservationsPixels(1, :) + 3;
            conflict.Confidence = 0.1;
            conflict.TextureScore = 0.1;
            request.Records = [request.Records rejected disconnected conflict];
        end

        function record = emptyRecord()
            record = struct(RecordId="", PairId="", ...
                ViewIds=strings(1, 2), PassIds=strings(1, 2), ...
                ObservationIds=strings(1, 2), ...
                SourceObservationsPixels=nan(2), ...
                RayOriginsWorld=nan(3, 2), RayVectorsWorld=nan(3, 2), ...
                MatchState="valid", Score=NaN, Confidence=1, ...
                TextureScore=1, NavigationWeights=ones(1, 2), ...
                RadiometricValues=nan(1, 2), ...
                RadiometricConsistency=1, ...
                VisibilityStates=["visible" "visible"], ...
                ProvisionalPointWorld=zeros(3, 0), ...
                PairwiseCovarianceWorldMetersSquared=[], ModeId="");
        end
    end
end
