classdef ProjectionDenseSurfaceSyntheticPlannerTest < matlab.unittest.TestCase
    %ProjectionDenseSurfaceSyntheticPlannerTest Tests synthetic collection planning.

    properties (Constant)
        Tol = 1e-9
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src")));
        end
    end

    methods (Test)
        function testLoadValidatesSchemaAndResolvesRuntimePaths(testCase)
            root = ProjectionDenseSurfaceSyntheticPlannerTest.makeTemporaryRoot( ...
                testCase);
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();
            configPath = ProjectionDenseSurfaceSyntheticPlannerTest.writeConfig( ...
                root, config);

            [loaded, context] = ProjectionDenseSurfaceSyntheticConfig.load(configPath);

            testCase.verifyEqual(loaded.schema_version, 1);
            testCase.verifyTrue(isfile(context.SourceImagePath));
            testCase.verifyEqual(context.ProjectRoot, string(root));
            testCase.verifyTrue(startsWith(context.OutputDirectory, string(root)));
        end

        function testValidationRejectsSchemaDrift(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();
            config.image.unapproved_field = true;

            testCase.verifyError( ...
                @() ProjectionDenseSurfaceSyntheticConfig.validate(config), ...
                "ProjectionDenseSurfaceSyntheticConfig:schemaMismatch");
        end

        function testFrameTransformAndGimbalOrderAreExplicit(testCase)
            transform = ...
                ProjectionDenseSurfaceSyntheticPlanner.bodyToWorldMatrix();
            pitchRay = ProjectionDenseSurfaceSyntheticPlanner.boresightRay(0, 5);
            rightRay = ProjectionDenseSurfaceSyntheticPlanner.boresightRay(-30, 0);
            composed = ProjectionDenseSurfaceSyntheticPlanner.gimbalRotation(-30, 5);

            testCase.verifyEqual(transform, diag([1 1 -1]));
            testCase.verifyGreaterThan(pitchRay(1), 0);
            testCase.verifyGreaterThan(rightRay(2), 0);
            testCase.verifyEqual(composed * [0; 0; 1], ...
                ProjectionDenseSurfaceSyntheticPlanner.gimbalRotation(-30, 0) * ...
                ProjectionDenseSurfaceSyntheticPlanner.gimbalRotation(0, 5) * ...
                [0; 0; 1], ...
                AbsTol=ProjectionDenseSurfaceSyntheticPlannerTest.Tol);
        end

        function testFeasiblePlanReportsDerivedRelationships(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();

            report = ProjectionDenseSurfaceSyntheticPlanner.plan( ...
                config, [128 136 3]);
            projectedGsd = reshape([report.Views.ProjectedGsdMeters], 2, []).';
            contributions = [report.Views.PlatformAdvanceMetersPerColumn].' + ...
                [report.Views.GimbalAdvanceMetersPerColumn].';

            testCase.verifyTrue(report.Feasible, report.Explanation);
            testCase.verifyEqual(numel(report.Views), config.image.view_count);
            testCase.verifyEqual(contributions, projectedGsd(:, 2), ...
                AbsTol=ProjectionDenseSurfaceSyntheticPlannerTest.Tol);
            testCase.verifyGreaterThan([report.Views.PitchFieldOfRegardMarginDegrees], 0);
            testCase.verifyGreaterThanOrEqual( ...
                min(report.AchievedSceneCenterSeparationsDegrees), ...
                config.collection_planner.desired_scene_center_separation_degrees);
            testCase.verifyEqual(report.AcquisitionDurationSeconds, ...
                config.image.columns / config.image.scan_rate_lines_per_second, ...
                AbsTol=ProjectionDenseSurfaceSyntheticPlannerTest.Tol);
        end

        function testPitchInfeasibilityIsExplainable(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();
            config.gimbal.pitch_field_of_regard_degrees = [-2 2];
            config.gimbal.maximum_initial_forward_pitch_degrees = 1;

            report = ProjectionDenseSurfaceSyntheticPlanner.plan(config, [128 136 3]);

            testCase.verifyFalse(report.Feasible);
            testCase.verifyEqual(report.FirstViolation, "pitchFieldOfRegard");
            testCase.verifyNotEmpty(report.Explanation);
            testCase.verifyTrue(isfield(report.NearestCandidate, ...
                "MinimumPitchMarginDegrees"));
        end

        function testTextureGrowthInfeasibilityIsExplainable(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();
            config.sampling.minimum_reflection_tiles_rows = 1;
            config.sampling.minimum_reflection_tiles_columns = 1;
            config.sampling.maximum_reflection_tiles_rows = 1;
            config.sampling.maximum_reflection_tiles_columns = 1;

            report = ProjectionDenseSurfaceSyntheticPlanner.plan(config, [12 14 3]);

            testCase.verifyFalse(report.Feasible);
            testCase.verifyEqual(report.FirstViolation, "textureGridGrowth");
            testCase.verifyGreaterThan(max(report.RequiredReflectionTileCount), 1);
        end

        function testDisallowedScheduleExpansionFailsExplicitly(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();
            config.collection_planner.allow_separation_expansion = false;

            report = ProjectionDenseSurfaceSyntheticPlanner.plan(config, [128 136 3]);

            testCase.verifyFalse(report.Feasible);
            testCase.verifyEqual(report.FirstViolation, "constantGapSchedule");
            testCase.verifyTrue(report.SeparationExpanded);
        end

        function testMissingSourceBandIsRejected(testCase)
            config = ProjectionDenseSurfaceSyntheticPlannerTest.publicConfig();

            testCase.verifyError( ...
                @() ProjectionDenseSurfaceSyntheticPlanner.plan(config, [128 136 2]), ...
                "ProjectionDenseSurfaceSyntheticPlanner:missingSourceBand");
        end
    end

    methods (Static, Access = private)
        function root = makeTemporaryRoot(testCase)
            root = tempname;
            mkdir(root);
            mkdir(fullfile(root, "config"));
            mkdir(fullfile(root, "test_data"));
            testCase.addTeardown(@() rmdir(root, "s"));
            source = uint8(mod(reshape(0:(16 * 18 * 3 - 1), 16, 18, 3), 251));
            imwrite(source, fullfile(root, "test_data", "public_texture.tif"));
        end

        function configPath = writeConfig(root, config)
            configPath = fullfile(root, "config", "public_config.json");
            fileId = fopen(configPath, "w");
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(config, PrettyPrint=true));
            clear cleanup
        end

        function config = publicConfig()
            config = struct();
            config.schema_version = 1;
            config.fixture = struct( ...
                source_image_path="test_data/public_texture.tif", ...
                reserved_source_image_paths="test_data/reserved_texture.tif", ...
                random_seed=17);
            config.image = struct(rows=101, columns=301, view_count=3, ...
                instantaneous_line_axis="rows", scan_axis="columns", ...
                scan_rate_lines_per_second=200, cross_track_fov_degrees=2, ...
                focal_length_meters=0.2, source_band_sequence=[1 2 3]);
            config.world_frame = struct( ...
                x_axis_definition="nominal-flight-forward", ...
                y_axis_definition="right-of-flight", z_axis_definition="up", ...
                platform_x_axis_definition="nose-forward", ...
                platform_y_axis_definition="right-wing", ...
                platform_z_axis_definition="down");
            config.platform = struct(height_above_ground_meters=1000, ...
                forward_velocity_meters_per_second=50, ...
                nominal_off_nadir_degrees=45, target_side="right");
            config.gimbal = struct(zero_boresight_axis="platform-positive-z", ...
                rotation_order=["roll" "pitch"], ...
                roll_axis="platform-positive-x", ...
                pitch_axis="roll-gimbal-positive-y", ...
                positive_rotation_convention="right-hand", ...
                pitch_field_of_regard_degrees=[-30 30], ...
                maximum_initial_forward_pitch_degrees=20, ...
                ideal_encoder_and_mounting=true);
            config.collection_planner = struct( ...
                desired_scene_center_separation_degrees=1, ...
                allow_separation_expansion=true, constant_inter_image_gap=true, ...
                retrace_time_seconds=0.1, minimum_slant_range_meters=100, ...
                maximum_slant_range_meters=4800, ...
                stop_for_user_on_infeasible_geometry=true);
            config.sampling = struct(maximum_oversampling_per_axis=4, ...
                derive_range=true, minimum_reflection_tiles_rows=3, ...
                minimum_reflection_tiles_columns=3, ...
                maximum_reflection_tiles_rows=31, ...
                maximum_reflection_tiles_columns=31, ...
                prefer_odd_tile_counts=true, logical_reflection_addressing=true);
            config.terrain = struct( ...
                model="asymmetric-windowed-radial-sinc-composite", ...
                minimum_height_meters=-10, maximum_height_meters=20, ...
                characteristic_lengths_meters=[40 90], ...
                asymmetry_weights=[1 0.2], require_occlusion=true);
            config.truth_turbulence = struct( ...
                model="deterministic-gauss-markov", ...
                position_rms_meters_per_axis=0.1, ...
                attitude_rms_degrees_per_axis=0.001, ...
                correlation_time_seconds=1);
            gnss = struct(class="public-nominal-code-solution", update_rate_hz=2, ...
                horizontal_position_sigma_meters=1, ...
                vertical_position_sigma_meters=2, ...
                velocity_sigma_meters_per_second=0.1, ...
                correlation_time_seconds=1);
            tactical = struct(gyro_bias_sigma_degrees_per_hour=2, ...
                gyro_angle_random_walk_degrees_per_sqrt_hour=0.2, ...
                accelerometer_bias_sigma_mg=0.2, ...
                accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour=0.1);
            navigation = struct(gyro_bias_sigma_degrees_per_hour=0.2, ...
                gyro_angle_random_walk_degrees_per_sqrt_hour=0.05, ...
                accelerometer_bias_sigma_mg=0.05, ...
                accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour=0.02);
            config.navigation = struct(aiding_mode="nominal-non-rtk-gnss", ...
                gnss=gnss, bias_draw_scope="one-sortie", ...
                presets=struct(tactical_grade_imu=tactical, ...
                navigation_grade_imu=navigation));
            config.acceptance = struct( ...
                modes=["pointing-only" "combined-navigation-error"], ...
                establish_thresholds_after_first_full_scale_baseline=true, ...
                record_metrics=["coverage" "repeatability"]);
            config.output = struct(directory="artifacts/public_synthetic", ...
                default_image_format="tiff", ...
                supported_image_formats=["tiff" "png"], ...
                preserve_source_integer_class=true, ...
                write_compact_mat_truth=true, write_json_run_summary=true);
            config.future = struct( ...
                reserve_maximum_images_within_for_mode=true, ...
                reserve_degraded_gps_mode=true, ...
                reserve_independent_passes_mode=true, ...
                reserve_piecewise_linear_orbit_mode=true, ...
                reserve_curved_orbit_mode=true, ...
                reserve_time_varying_opk_posts=true);
        end
    end
end
