classdef ProjectionViewerPrecisionValidation
    %ProjectionViewerPrecisionValidation Validate long-range display precision.

    properties (Constant)
        Format = "ProjectionViewerPrecisionValidation"
        Version = 1
        Wgs84SemimajorAxisMeters = 6378137
    end

    methods (Static)
        function report = run(options)
            %run Compare safe local single display geometry with double truth.
            if nargin < 1
                options = struct();
            end
            options = ProjectionViewerPrecisionValidation.validateOptions(options);
            horizon = ProjectionViewerPrecisionValidation.geometricHorizon( ...
                options.ObserverHaeMeters);
            if horizon < options.RequiredRangeMeters
                error("ProjectionViewerPrecisionValidation:infeasibleRequiredRange", ...
                    "Observer HAE must place the unrefracted horizon at or beyond the required range.");
            end
            stretch = min(options.MaximumStretchRangeMeters, horizon);
            ranges = unique([options.NearRangeMeters ...
                options.NominalRangeMeters options.RequiredRangeMeters stretch], ...
                "stable");
            origins = [ ...
                struct(Name="local", TranslationMeters=zeros(3, 1)), ...
                struct(Name="largeTranslated", ...
                TranslationMeters=[6378137.125; -2700000.375; 1300000.625])];
            records = repmat( ...
                ProjectionViewerPrecisionValidation.emptyRecord(), ...
                1, numel(ranges) * numel(origins));
            cursor = 0;
            for origin = origins
                for range = ranges
                    cursor = cursor + 1;
                    records(cursor) = ...
                        ProjectionViewerPrecisionValidation.evaluateCase( ...
                        origin, range, options);
                end
            end
            localErrors = [records.LocalSingleMaximumScreenErrorPixels];
            safeEyeOrdering = [records.LocalSingleEyeOrderingPreserved];
            finite = [records.LocalSingleFinite];
            passes = all(localErrors < options.DisplayGatePixels) && ...
                all(safeEyeOrdering) && all(finite);
            report = struct( ...
                Format=ProjectionViewerPrecisionValidation.Format, ...
                Version=ProjectionViewerPrecisionValidation.Version, ...
                Status=ProjectionViewerPrecisionValidation.status(passes), ...
                ObserverHaeMeters=options.ObserverHaeMeters, ...
                EarthRadiusMeters=ProjectionViewerPrecisionValidation. ...
                Wgs84SemimajorAxisMeters, ...
                HorizonModel="unrefractedWgs84SemimajorSphere", ...
                GeometricHorizonMeters=horizon, ...
                RequiredRangeMeters=options.RequiredRangeMeters, ...
                StretchRangeMeters=stretch, RangesMeters=ranges, ...
                DisplayGatePixels=options.DisplayGatePixels, ...
                SafeBoundary="subtract double render origin before single cast", ...
                Records=records, MaximumLocalSingleScreenErrorPixels= ...
                max(localErrors), LocalSingleEyeOrderingPreserved= ...
                all(safeEyeOrdering), LocalSingleFinite=all(finite), ...
                UnsafeAbsoluteSingleWorse=any( ...
                [records.AbsoluteSingleMaximumScreenErrorPixels] > ...
                localErrors), ThresholdsEstablished=false, ...
                P1Complete=passes);
        end

        function distance = geometricHorizon(observerHaeMeters)
            %geometricHorizon Return unrefracted spherical WGS84 horizon range.
            observerHaeMeters = ...
                ProjectionViewerPrecisionValidation.validatePositiveScalar( ...
                observerHaeMeters, "observerHaeMeters");
            radius = ProjectionViewerPrecisionValidation.Wgs84SemimajorAxisMeters;
            distance = sqrt((radius + observerHaeMeters)^2 - radius^2);
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionViewerPrecisionValidation:invalidOptions", ...
                    "Options must be a scalar struct.");
            end
            defaults = struct(ObserverHaeMeters=4000, ...
                NearRangeMeters=1000, NominalRangeMeters=25000, ...
                RequiredRangeMeters=100000, ...
                MaximumStretchRangeMeters=200000, ...
                ScreenPixelsPerMeter=2, DisplayGatePixels=0.1, ...
                StereoBaselineMeters=0.02);
            names = fieldnames(options);
            unknown = setdiff(string(names), string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionViewerPrecisionValidation:invalidOptions", ...
                    "Unknown option: %s.", unknown(1));
            end
            for index = 1:numel(names)
                defaults.(names{index}) = options.(names{index});
            end
            fields = string(fieldnames(defaults));
            for field = fields.'
                defaults.(field) = ...
                    ProjectionViewerPrecisionValidation.validatePositiveScalar( ...
                    defaults.(field), field);
            end
            if defaults.NearRangeMeters >= defaults.NominalRangeMeters || ...
                    defaults.NominalRangeMeters >= defaults.RequiredRangeMeters || ...
                    defaults.MaximumStretchRangeMeters < ...
                    defaults.RequiredRangeMeters
                error("ProjectionViewerPrecisionValidation:invalidOptions", ...
                    "Ranges must increase from near through required and stretch.");
            end
            options = defaults;
        end

        function value = validatePositiveScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value <= 0
                error("ProjectionViewerPrecisionValidation:invalidOptions", ...
                    "%s must be a finite positive numeric scalar.", name);
            end
            value = double(value);
        end

        function record = evaluateCase(origin, rangeMeters, options)
            sceneCenter = origin.TranslationMeters + [0; 0; -rangeMeters];
            offsets = [ ...
                -512.123 511.877 -255.371 256.629; ...
                -384.377 -383.623 384.129 383.871; ...
                0.127 -0.253 0.379 -0.503];
            worldPoints = sceneCenter + offsets;
            doubleRelative = worldPoints - sceneCenter;
            localSingleRelative = double(single(doubleRelative));
            absoluteSingleRelative = double( ...
                single(worldPoints) - single(sceneCenter));
            doubleScreen = options.ScreenPixelsPerMeter * ...
                doubleRelative(1:2, :);
            localScreen = options.ScreenPixelsPerMeter * ...
                localSingleRelative(1:2, :);
            absoluteScreen = options.ScreenPixelsPerMeter * ...
                absoluteSingleRelative(1:2, :);
            localScreenError = vecnorm(localScreen - doubleScreen, 2, 1);
            absoluteScreenError = vecnorm(absoluteScreen - doubleScreen, 2, 1);

            eyeOffsets = [-0.5 0.5] * options.StereoBaselineMeters;
            eyeWorld = sceneCenter + [eyeOffsets; zeros(2, 2)];
            doubleBaseline = eyeWorld(:, 2) - eyeWorld(:, 1);
            localSingleBaseline = double(single(eyeWorld - sceneCenter));
            localSingleBaseline = ...
                localSingleBaseline(:, 2) - localSingleBaseline(:, 1);
            absoluteSingleEyes = single(eyeWorld);
            absoluteSingleBaseline = double( ...
                absoluteSingleEyes(:, 2) - absoluteSingleEyes(:, 1));

            record = ProjectionViewerPrecisionValidation.emptyRecord();
            record.OriginRegime = origin.Name;
            record.RangeMeters = rangeMeters;
            record.WorldTranslationMeters = origin.TranslationMeters.';
            record.LocalSingleMaximumWorldErrorMeters = max(vecnorm( ...
                localSingleRelative - doubleRelative, 2, 1));
            record.AbsoluteSingleMaximumWorldErrorMeters = max(vecnorm( ...
                absoluteSingleRelative - doubleRelative, 2, 1));
            record.LocalSingleMaximumScreenErrorPixels = max(localScreenError);
            record.AbsoluteSingleMaximumScreenErrorPixels = ...
                max(absoluteScreenError);
            record.LocalSingleFinite = all(isfinite(localSingleRelative), "all");
            record.LocalSingleEyeOrderingPreserved = ...
                sign(localSingleBaseline(1)) == sign(doubleBaseline(1));
            record.AbsoluteSingleEyeOrderingPreserved = ...
                sign(absoluteSingleBaseline(1)) == sign(doubleBaseline(1));
        end

        function value = status(passes)
            value = "failed";
            if passes
                value = "passed";
            end
        end

        function record = emptyRecord()
            record = struct(OriginRegime="", RangeMeters=NaN, ...
                WorldTranslationMeters=nan(1, 3), ...
                LocalSingleMaximumWorldErrorMeters=NaN, ...
                AbsoluteSingleMaximumWorldErrorMeters=NaN, ...
                LocalSingleMaximumScreenErrorPixels=NaN, ...
                AbsoluteSingleMaximumScreenErrorPixels=NaN, ...
                LocalSingleFinite=false, ...
                LocalSingleEyeOrderingPreserved=false, ...
                AbsoluteSingleEyeOrderingPreserved=false);
        end
    end
end
