classdef ProjectionTimeVaryingOpkTruthAudit
    %ProjectionTimeVaryingOpkTruthAudit Held-out A7 recovery/support audit.

    methods (Static)
        function report = run()
            %run Exercise dense, sparse, and per-column research cases.
            [denseRequest, truth] = ...
                ProjectionTimeVaryingOpkTruthAudit.denseFixture();
            options = struct(SmoothnessWeight=1e-10, GaugeWeight=1e6, ...
                MaximumDataConditionNumber=1e12);
            dense = ProjectionTimeVaryingOpkResearch.analyze( ...
                denseRequest, options);
            heldOutError = ProjectionTimeVaryingOpkTruthAudit. ...
                heldOutError(dense, truth);

            sparseRequest = ProjectionTimeVaryingOpkTruthAudit. ...
                requestForColumns([1 128 256 384 512]);
            sparse = ProjectionTimeVaryingOpkResearch.analyze( ...
                sparseRequest);

            perColumnRequest = ProjectionTimeVaryingOpkTruthAudit. ...
                requestForColumns(1:16, 16, 2);
            perColumn = ProjectionTimeVaryingOpkResearch.analyze( ...
                perColumnRequest, struct(Mode="perColumnAnalysis"));

            report = struct(Format= ...
                "ProjectionTimeVaryingOpkTruthAudit", Version=1, ...
                OperationalTruthSeparated=true, ...
                Dense=struct(Status=dense.Status, ...
                LocallyObservable=dense.Observability.LocallyObservable, ...
                SelectedPostSpacingPixels= ...
                dense.Model.SelectedPostSpacingPixels, ...
                MaximumHeldOutRotationErrorRadians=max(heldOutError), ...
                RmsHeldOutRotationErrorRadians= ...
                sqrt(mean(heldOutError .^ 2)), ...
                AutoApplied=dense.AutoApplied), ...
                Sparse=struct(Status=sparse.Status, ...
                LocallyObservable=sparse.Observability.LocallyObservable, ...
                SelectedPostSpacingPixels= ...
                sparse.Model.SelectedPostSpacingPixels, ...
                Coarsened=sparse.Observability.Coarsened, ...
                History=sparse.Observability.History), ...
                PerColumn=struct(Status=perColumn.Status, ...
                AnalysisOnly=perColumn.Model.PerColumnAnalysisOnly, ...
                ApplicationSupported=perColumn.ApplicationSupported, ...
                ParameterCount= ...
                perColumn.Observability.Final.ParameterCount), ...
                Decision=dense.Decision, ApplicationSupported=false, ...
                AuditFingerprint=ProjectionGeometryFingerprint.hash(struct( ...
                DenseError=heldOutError, ...
                SparseHistory=sparse.Observability.History, ...
                PerColumnParameters= ...
                perColumn.Observability.Final.ParameterCount)));
        end
    end

    methods (Static, Access = private)
        function [request, truth] = denseFixture()
            columns = 1:8:512;
            request = ProjectionTimeVaryingOpkTruthAudit. ...
                requestForColumns(columns);
            heldOutColumns = 5:16:509;
            truth = ProjectionTimeVaryingOpkTruthAudit. ...
                truthForViews(request.Views, heldOutColumns, 128);
        end

        function request = requestForColumns(columns, width, viewCount)
            if nargin < 2
                width = 512;
            end
            if nargin < 3
                viewCount = 4;
            end
            columns = reshape(double(columns), 1, []);
            if viewCount == 4
                passIds = ["pass-a" "pass-a" "pass-b" "pass-b"];
            else
                passIds = repmat("pass-a", 1, viewCount);
            end
            template = struct(ViewId="", PassId="", ...
                ImageWidthPixels=0, SourceColumnsPixels=zeros(0, 1), ...
                RotationJacobians=zeros(0, 3), Residuals=zeros(0, 1), ...
                Weights=zeros(0, 1), EvidenceKind="dense");
            views = repmat(template, 1, viewCount);
            for index = 1:viewCount
                [common, coefficients] = ...
                    ProjectionTimeVaryingOpkTruthAudit.coefficients( ...
                    index, viewCount, width, 128);
                basis = ProjectionTimeVaryingOpkResearch.basis( ...
                    width, columns, 128);
                effective = common + basis * coefficients;
                views(index) = struct(ViewId="view-" + index, ...
                    PassId=passIds(index), ImageWidthPixels=width, ...
                    SourceColumnsPixels=repelem(columns(:), 3), ...
                    RotationJacobians=repmat(eye(3), numel(columns), 1), ...
                    Residuals=reshape(effective.', [], 1), ...
                    Weights=ones(3 * numel(columns), 1), ...
                    EvidenceKind="dense");
            end
            request = struct(SourceGenerationId="a7-held-out-fixture", ...
                Views=views);
        end

        function truth = truthForViews(views, columns, spacing)
            template = struct(ViewId="", PassId="", ...
                SourceColumnsPixels=zeros(1, 0), ...
                EffectiveRotationVectorsRadians=zeros(0, 3));
            truth = repmat(template, 1, numel(views));
            for index = 1:numel(views)
                [common, coefficients] = ...
                    ProjectionTimeVaryingOpkTruthAudit.coefficients( ...
                    index, numel(views), ...
                    views(index).ImageWidthPixels, spacing);
                basis = ProjectionTimeVaryingOpkResearch.basis( ...
                    views(index).ImageWidthPixels, columns, spacing);
                truth(index) = struct(ViewId=views(index).ViewId, ...
                    PassId=views(index).PassId, ...
                    SourceColumnsPixels=columns, ...
                    EffectiveRotationVectorsRadians= ...
                    common + basis * coefficients);
            end
        end

        function [common, coefficients] = coefficients( ...
                viewIndex, viewCount, width, spacing)
            [~, definition] = ProjectionTimeVaryingOpkResearch.basis( ...
                width, [1 width], spacing);
            control = linspace(-1, 1, definition.ControlCount).';
            if viewCount == 4
                passIndex = ceil(viewIndex / 2);
                signValue = 1 - 2 * mod(viewIndex, 2);
            else
                passIndex = 1;
                signs = ones(1, viewCount);
                signs(2:2:end) = -1;
                signs(end) = signs(end) - sum(signs);
                signValue = signs(viewIndex);
            end
            commonTable = [2.0e-3 -1.0e-3 0.5e-3; ...
                -1.5e-3 0.8e-3 -0.4e-3];
            common = commonTable(passIndex, :);
            shape = [sin(pi * control) ...
                control .^ 2 - mean(control .^ 2) ...
                cos(0.5 * pi * control) - ...
                mean(cos(0.5 * pi * control))];
            coefficients = signValue * shape .* [4e-4 3e-4 2e-4];
        end

        function errors = heldOutError(result, truth)
            errors = zeros(0, 1);
            for index = 1:numel(truth)
                resultIndex = find(string({result.Views.ViewId}) == ...
                    truth(index).ViewId, 1);
                view = result.Views(resultIndex);
                passIndex = find(string({result.Passes.PassId}) == ...
                    truth(index).PassId, 1);
                common = result.Passes(passIndex).CommonAttitudeRadians;
                basis = ProjectionTimeVaryingOpkResearch.basis( ...
                    view.ImageWidthPixels, ...
                    truth(index).SourceColumnsPixels, ...
                    view.PostSpacingPixels);
                estimated = common + basis * ...
                    view.DifferentialControlRotationVectorsRadians;
                difference = estimated - ...
                    truth(index).EffectiveRotationVectorsRadians;
                errors = [errors; sqrt(sum(difference .^ 2, 2))]; %#ok<AGROW>
            end
        end
    end
end
