classdef ProjectionDenseSgmMatcher < ProjectionDenseMatcher
    %ProjectionDenseSgmMatcher Adapt the current SGM surface extractor.

    methods
        function metadata = metadata(~)
            %metadata Describe the built-in SGM adapter.
            gpu = ProjectionGpuSupport.capability();
            metadata = struct( ...
                AlgorithmId="sightline.sgm", Name="Built-in SGM", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct( ...
                InputGeometry="correctedRayPair", ...
                Radiometry="singleBand2D", ...
                SearchGeometry="globalRectifiedDisparity", ...
                ObservationSpace="continuousFullSource", ...
                SupportsOcclusionState=false, ...
                SupportsCovariance=false, Gpu=gpu), ...
                RequiredProducts="Computer Vision Toolbox", ...
                Deterministic=true, Precision="single cost/disparity; double rays", ...
                MemoryEstimate="bounded by analysis grid and disparity range", ...
                CpuSupported=true, GpuSupported=gpu.Available);
        end

        function options = defaultOptions(~)
            %defaultOptions Return current extractor options.
            options = ProjectionDenseSurfaceExtractor.defaults();
        end

        function options = validateOptions(~, options)
            %validateOptions Reuse the established SGM option contract.
            options = ProjectionDenseSurfaceExtractor.validateOptions(options);
        end
    end

    methods (Static)
        function request = requestFromLegacy(scene, pairWorking, pairMatch, options)
            %requestFromLegacy Build a matcher request from current dense inputs.
            if nargin < 4
                options = struct();
            end
            if ~isstruct(scene) || ~isscalar(scene) || ...
                    ~isfield(scene, "layers") || ...
                    ~isstruct(pairWorking) || ~isscalar(pairWorking) || ...
                    ~isfield(pairWorking, "Pair") || ...
                    ~isfield(pairWorking, "PairLayerIds") || ...
                    ~isfield(pairWorking, "LayerImages") || ...
                    ~isstruct(pairMatch) || ~isscalar(pairMatch)
                error("ProjectionDenseSgmMatcher:invalidLegacyContext", ...
                    "Scene, pair working images, and pair match are required.");
            end
            scene = ProjectionViewMetadata.ensureScene(scene);
            pair = double(pairWorking.Pair(:).');
            if numel(pair) ~= 2 || any(pair < 1) || ...
                    any(pair > numel(scene.layers))
                error("ProjectionDenseSgmMatcher:invalidLegacyContext", ...
                    "PairWorking.Pair must select two scene layers.");
            end
            layerIds = string(pairWorking.PairLayerIds);
            layerImages = pairWorking.LayerImages;
            first = ProjectionDenseSgmMatcher.layerImage(layerImages, layerIds(1));
            second = ProjectionDenseSgmMatcher.layerImage(layerImages, layerIds(2));
            viewIds = string({scene.layers(pair).ViewId});
            identity = ProjectionViewMetadata.pairIdentity(viewIds(1), viewIds(2));
            overlap = first.ValidMask & second.ValidMask;
            if isfield(pairWorking, "OverlapMask") && ...
                    isstruct(pairWorking.OverlapMask) && ...
                    isfield(pairWorking.OverlapMask, "Mask")
                overlap = logical(pairWorking.OverlapMask.Mask);
            end
            seed = 0;
            if isfield(options, "Seed")
                seed = options.Seed;
                options = rmfield(options, "Seed");
            end
            request = ProjectionDenseMatchRequest.validate(struct( ...
                PairId=identity.PairId, ViewIds=viewIds, ...
                AnalysisImages={{ ...
                ProjectionDenseSgmMatcher.finiteAnalysisImage(first.Image), ...
                ProjectionDenseSgmMatcher.finiteAnalysisImage(second.Image)}}, ...
                ValidityMasks={{logical(first.ValidMask), ...
                logical(second.ValidMask)}}, ...
                SourceRows={{first.SourceRows, second.SourceRows}}, ...
                SourceColumns={{first.SourceColumns, second.SourceColumns}}, ...
                CorrectedGeometry=[scene.layers(pair).SourceGeometry], ...
                OverlapMask=overlap, SearchPrediction=struct( ...
                SparsePairMatch=pairMatch), PrecisionPolicy=struct( ...
                Geometry="double", WorkingRadiometry="single", ...
                Disparity="single"), Seed=seed, Context=struct( ...
                Scene=scene, PairWorking=pairWorking, PairMatch=pairMatch, ...
                ExtractorOptions=options)));
        end

        function result = resultFromLegacy(request, legacy)
            %resultFromLegacy Convert current extractor output to SDK matches.
            request = ProjectionDenseMatchRequest.validate(request);
            if ~isstruct(legacy) || ~isscalar(legacy) || ...
                    ~isfield(legacy, "Surface") || ...
                    ~isfield(legacy, "Diagnostics") || ...
                    ~isfield(legacy, "Format") || ~isfield(legacy, "Version")
                error("ProjectionDenseSgmMatcher:invalidLegacyResult", ...
                    "Legacy result must contain surface, diagnostics, format, and version.");
            end
            surface = legacy.Surface;
            required = ["ValidMask" "MovingSourceRows" ...
                "MovingSourceColumns" "ReferenceSourceRows" ...
                "ReferenceSourceColumns" "RaySeparationMeters"];
            if ~isstruct(surface) || ~isscalar(surface) || ...
                    any(~isfield(surface, required))
                error("ProjectionDenseSgmMatcher:invalidLegacyResult", ...
                    "Legacy surface does not contain full-source observations.");
            end
            count = numel(surface.ValidMask);
            states = repmat("geometrySearchFailure", count, 1);
            valid = logical(surface.ValidMask(:));
            states(valid) = "valid";
            score = double(surface.RaySeparationMeters(:));
            confidence = zeros(count, 1);
            confidence(valid) = 1 ./ (1 + max(0, score(valid)));
            info = whos("legacy");
            execution = ProjectionDenseSgmMatcher.executionFromLegacy(legacy);
            result = struct( ...
                PairId=request.PairId, ViewIds=request.ViewIds, ...
                MovingSourceRows=surface.MovingSourceRows(:), ...
                MovingSourceColumns=surface.MovingSourceColumns(:), ...
                ReferenceSourceRows=surface.ReferenceSourceRows(:), ...
                ReferenceSourceColumns=surface.ReferenceSourceColumns(:), ...
                States=states, Score=score, Confidence=confidence, ...
                CovariancePixelsSquared=[], Diagnostics=struct( ...
                LegacyFormat=string(legacy.Format), ...
                LegacyVersion=double(legacy.Version), ...
                ValidCount=nnz(valid), ObservationCount=count, ...
                RectifiedMovingImage=ProjectionDenseSgmMatcher. ...
                fieldOrDefault(legacy, "RectifiedMovingImage", []), ...
                RectifiedReferenceImage=ProjectionDenseSgmMatcher. ...
                fieldOrDefault(legacy, "RectifiedReferenceImage", []), ...
                DisparityMap=ProjectionDenseSgmMatcher. ...
                fieldOrDefault(legacy, "Disparity", []), ...
                ValidDisparityMask=ProjectionDenseSgmMatcher. ...
                fieldOrDefault(legacy, "ValidDisparityMask", []), ...
                DisparityRangeUsed=ProjectionDenseSgmMatcher.fieldOrDefault( ...
                legacy.Diagnostics, "DisparityRangeUsed", []), ...
                ConfidenceCalibrated=false), ...
                Memory=struct(Bytes=double(info.bytes)), ...
                Execution=execution, Provenance=struct( ...
                Adapter="ProjectionDenseSgmMatcher"));
            result = ProjectionDenseMatchResult.validate(result, request);
        end
    end

    methods (Access = protected)
        function result = matchImpl(~, request, options, ~)
            context = request.Context;
            required = ["Scene" "PairWorking" "PairMatch"];
            if any(~isfield(context, required))
                error("ProjectionDenseSgmMatcher:missingLegacyContext", ...
                    "SGM adapter requests require the validated legacy context.");
            end
            legacy = ProjectionDenseSurfaceExtractor.extract( ...
                context.Scene, context.PairWorking, context.PairMatch, options);
            result = ProjectionDenseSgmMatcher.resultFromLegacy(request, legacy);
        end
    end

    methods (Static, Access = private)
        function layer = layerImage(layers, layerId)
            ids = string({layers.LayerId});
            index = find(ids == layerId, 1, "first");
            if isempty(index)
                error("ProjectionDenseSgmMatcher:invalidLegacyContext", ...
                    "Pair layer image '%s' is unavailable.", layerId);
            end
            layer = layers(index);
            required = ["Image" "ValidMask" "SourceRows" "SourceColumns"];
            if any(~isfield(layer, required))
                error("ProjectionDenseSgmMatcher:invalidLegacyContext", ...
                    "Pair layer images require analysis arrays, masks, and source maps.");
            end
        end

        function execution = executionFromLegacy(legacy)
            device = string(ProjectionDenseSgmMatcher.fieldOrDefault( ...
                legacy.Diagnostics, "Execution", "cpu"));
            gpuInfo = ProjectionDenseSgmMatcher.fieldOrDefault( ...
                legacy.Diagnostics, "GpuInfo", struct( ...
                Requested=false, Enabled=false, Reason="notReported"));
            fallbackReason = "";
            if isfield(gpuInfo, "Requested") && gpuInfo.Requested && ...
                    isfield(gpuInfo, "Enabled") && ~gpuInfo.Enabled
                fallbackReason = string(ProjectionDenseSgmMatcher. ...
                    fieldOrDefault(gpuInfo, "Reason", "unavailable"));
            end
            execution = struct(Device=device, ...
                FallbackReason=fallbackReason, GpuInfo=gpuInfo);
        end

        function image = finiteAnalysisImage(image)
            image = double(image);
            image(~isfinite(image)) = 0;
        end

        function value = fieldOrDefault(container, fieldName, default)
            value = default;
            if isstruct(container) && isscalar(container) && ...
                    isfield(container, fieldName)
                value = container.(fieldName);
            end
        end
    end
end
