classdef ProjectionDenseSurfaceExtractor
    %ProjectionDenseSurfaceExtractor Build a dense ray-triangulated surface.

    properties (Constant)
        Format = "ProjectionDenseSurfaceResult"
        Version = 1
    end

    methods (Static)
        function capabilities = capabilities()
            gpu = ProjectionGpuSupport.capability();
            capabilities = struct( ...
                HasDisparitySgm=exist("disparitySGM", "file") == 2, ...
                RequiredProduct="Computer Vision Toolbox", ...
                Execution="cpuWithOptionalGpuArray", RequiresGpu=false, ...
                DisparitySgmSupportsGpuArray=true, Gpu=gpu);
        end

        function options = defaults()
            options = ProjectionDenseSurfaceExtractor.validateOptions(struct());
        end

        function result = extract(scene, pairWorking, pairMatch, options)
            %extract Rectify, match, and triangulate one aligned stereo pair.
            if nargin < 4
                options = struct();
            end
            capabilities = ProjectionDenseSurfaceExtractor.capabilities();
            if ~capabilities.HasDisparitySgm
                error("ProjectionDenseSurfaceExtractor:missingDisparitySgm", ...
                    "disparitySGM is required. Install Computer Vision Toolbox.");
            end
            options = ProjectionDenseSurfaceExtractor.validateOptions(options);
            gpuInfo = ProjectionGpuSupport.resolve(options.UseGPU);
            scene = ProjectionLayerIdentity.ensureScene(scene);
            [pairWorking, pairMatch, pair] = ...
                ProjectionDenseSurfaceExtractor.validateInputs( ...
                scene, pairWorking, pairMatch, options);
            timer = tic;

            [movingPoints, referencePoints, sparseDiagnostics] = ...
                ProjectionDenseSurfaceExtractor.sparseWorkingPoints( ...
                scene, pairWorking, pairMatch, pair, ...
                options.MinimumSparseMatches);
            [angleRadians, parallaxDirection] = ...
                ProjectionDenseSurfaceExtractor.rectificationAngle( ...
                movingPoints, referencePoints, options);
            imageSize = double(pairWorking.OutputSize);
            imageCenter = ([imageSize(2), imageSize(1)] + 1) / 2;
            movingRectifiedPoints = ...
                ProjectionDenseSurfaceExtractor.rotatePoints( ...
                movingPoints, imageCenter, angleRadians);
            referenceRectifiedPoints = ...
                ProjectionDenseSurfaceExtractor.rotatePoints( ...
                referencePoints, imageCenter, angleRadians);
            sparseDisparities = movingRectifiedPoints(:, 1) - ...
                referenceRectifiedPoints(:, 1);
            verticalResiduals = movingRectifiedPoints(:, 2) - ...
                referenceRectifiedPoints(:, 2);
            disparityRange = ProjectionDenseSurfaceExtractor.disparityRange( ...
                sparseDisparities, imageSize(2), options);

            movingLayerImage = ...
                ProjectionDenseSurfaceExtractor.layerImageForId( ...
                pairWorking, pairWorking.PairLayerIds(1));
            referenceLayerImage = ...
                ProjectionDenseSurfaceExtractor.layerImageForId( ...
                pairWorking, pairWorking.PairLayerIds(2));
            movingRectified = ProjectionDenseSurfaceExtractor.rectifyLayer( ...
                movingLayerImage, imageCenter, angleRadians);
            referenceRectified = ProjectionDenseSurfaceExtractor.rectifyLayer( ...
                referenceLayerImage, imageCenter, angleRadians);

            [disparity, disparityRangeUsed, execution] = ...
                ProjectionDenseSurfaceExtractor.computeDisparity( ...
                movingRectified.ImageUint8, referenceRectified.ImageUint8, ...
                disparityRange, options.UniquenessThreshold, gpuInfo);
            disparity = single(disparity);
            [referenceX, referenceY] = ...
                ProjectionDenseSurfaceExtractor.referenceMatchGrid(disparity);
            matchedReferenceMask = ProjectionDenseSurfaceExtractor.sampleMap( ...
                double(referenceRectified.ValidMask), referenceX, ...
                referenceY, "nearest", 0) > 0.5;
            validDisparity = isfinite(disparity) & ...
                movingRectified.ValidMask & matchedReferenceMask;

            surface = ProjectionDenseSurfaceExtractor.triangulateSurface( ...
                scene, pair, pairWorking.ProjectionPlane, movingRectified, ...
                referenceRectified, disparity, validDisparity, options);
            intensity = movingRectified.Intensity;
            displayIntensity = intensity;
            displayIntensity(~validDisparity) = NaN;

            diagnostics = struct( ...
                Method="semiGlobalMatching", Execution=execution, ...
                GpuInfo=gpuInfo, ...
                Pair=pair, PairLayerIds=pairWorking.PairLayerIds, ...
                SparseMatchCount=size(movingPoints, 1), ...
                SparseProjection=sparseDiagnostics, ...
                RectificationAngleDegrees=rad2deg(angleRadians), ...
                DominantParallaxDirection=parallaxDirection, ...
                SparseDisparityMedianPixels=median(sparseDisparities), ...
                SparseDisparityRangePixels=[min(sparseDisparities), ...
                max(sparseDisparities)], ...
                SparseVerticalRmsPixels=rms(verticalResiduals), ...
                RequestedDisparityRange=disparityRange, ...
                DisparityRangeUsed=double(disparityRangeUsed), ...
                DenseDisparityCount=nnz(isfinite(disparity)), ...
                ValidTriangulationCount=nnz(surface.ValidMask), ...
                ValidTriangulationFraction=nnz(surface.ValidMask) / ...
                numel(surface.ValidMask), ...
                SurfaceSampleCount=numel(surface.ValidMask), ...
                SurfaceStride=surface.Stride, ...
                ProjectionOffsetsMeters=reshape( ...
                [surface.LayerCorrections.ProjectionOffsetMeters], 2, []).', ...
                ProjectionOffsetsAppliedToRays=false, ...
                TotalSeconds=toc(timer));
            diagnostics = ProjectionDenseSurfaceExtractor.addSurfaceSummary( ...
                diagnostics, surface);

            result = struct(Format=ProjectionDenseSurfaceExtractor.Format, ...
                Version=ProjectionDenseSurfaceExtractor.Version, ...
                Status="succeeded", Pair=pair, ...
                PairLayerIds=pairWorking.PairLayerIds, ...
                Intensity=displayIntensity, ...
                RectifiedMovingImage=movingRectified.Intensity, ...
                RectifiedReferenceImage=referenceRectified.Intensity, ...
                Disparity=disparity, ...
                ValidDisparityMask=validDisparity, Surface=surface, ...
                Diagnostics=diagnostics, Options=options);
        end

        function options = validateOptions(options)
            if nargin < 1 || isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "Dense-surface options must be a scalar struct.");
            end
            defaults = struct(DisparityRange=[], ...
                DisparityPaddingPixels=16, MaximumDisparitySpanPixels=128, ...
                UniquenessThreshold=15, MinimumSparseMatches=3, ...
                MinimumSparseParallaxPixels=0.1, ...
                MaximumSurfacePoints=250000, ...
                MaximumRaySeparationMeters=Inf, UseGPU=false);
            names = string(fieldnames(options));
            unexpected = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unexpected)
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "Unexpected dense-surface option: %s.", unexpected(1));
            end
            for name = string(fieldnames(defaults)).'
                if isfield(options, name)
                    defaults.(name) = options.(name);
                end
            end
            defaults.DisparityRange = ...
                ProjectionDenseSurfaceExtractor.optionalRange( ...
                defaults.DisparityRange, "DisparityRange");
            defaults.DisparityPaddingPixels = ...
                ProjectionDenseSurfaceExtractor.nonnegativeScalar( ...
                defaults.DisparityPaddingPixels, "DisparityPaddingPixels");
            defaults.MaximumDisparitySpanPixels = ...
                ProjectionDenseSurfaceExtractor.positiveScalar( ...
                defaults.MaximumDisparitySpanPixels, ...
                "MaximumDisparitySpanPixels");
            defaults.UniquenessThreshold = ...
                ProjectionDenseSurfaceExtractor.nonnegativeInteger( ...
                defaults.UniquenessThreshold, "UniquenessThreshold");
            defaults.MinimumSparseMatches = ...
                ProjectionDenseSurfaceExtractor.positiveInteger( ...
                defaults.MinimumSparseMatches, "MinimumSparseMatches");
            defaults.MinimumSparseParallaxPixels = ...
                ProjectionDenseSurfaceExtractor.nonnegativeScalar( ...
                defaults.MinimumSparseParallaxPixels, ...
                "MinimumSparseParallaxPixels");
            defaults.MaximumSurfacePoints = ...
                ProjectionDenseSurfaceExtractor.positiveInteger( ...
                defaults.MaximumSurfacePoints, "MaximumSurfacePoints");
            defaults.MaximumRaySeparationMeters = ...
                ProjectionDenseSurfaceExtractor.positiveScalarOrInf( ...
                defaults.MaximumRaySeparationMeters, ...
                "MaximumRaySeparationMeters");
            defaults.UseGPU = ProjectionDenseSurfaceExtractor.logicalScalar( ...
                defaults.UseGPU, "UseGPU");
            options = defaults;
        end
    end

    methods (Static, Access = private)
        function [disparity, disparityRangeUsed, execution] = ...
                computeDisparity(movingImage, referenceImage, ...
                disparityRange, uniquenessThreshold, gpuInfo)
            if gpuInfo.Enabled
                [disparity, disparityRangeUsed] = disparitySGM( ...
                    gpuArray(movingImage), gpuArray(referenceImage), ...
                    DisparityRange=disparityRange, ...
                    UniquenessThreshold=uniquenessThreshold);
                disparity = gather(disparity);
                disparityRangeUsed = gather(disparityRangeUsed);
                execution = "gpu";
            else
                [disparity, disparityRangeUsed] = disparitySGM( ...
                    movingImage, referenceImage, ...
                    DisparityRange=disparityRange, ...
                    UniquenessThreshold=uniquenessThreshold);
                execution = "cpu";
            end
        end

        function [pairWorking, pairMatch, pair] = validateInputs( ...
                scene, pairWorking, pairMatch, options)
            requiredWorking = ["Pair", "PairLayerIds", "OutputSize", ...
                "ProjectionPlane", "PixelToPlane", "LayerImages"];
            if ~isstruct(pairWorking) || ~isscalar(pairWorking) || ...
                    any(~isfield(pairWorking, requiredWorking))
                error("ProjectionDenseSurfaceExtractor:invalidWorkingImages", ...
                    "Pair working images are incomplete. Render the aligned pair again.");
            end
            pair = ProjectionAlignmentLayerResolver.pairIndices( ...
                scene, pairWorking);
            if numel(pairWorking.PairLayerIds) ~= 2 || ...
                    ~isequal(pairWorking.PairLayerIds, ...
                    ProjectionLayerIdentity.idsForIndices(scene, pair))
                error("ProjectionDenseSurfaceExtractor:pairIdentityMismatch", ...
                    "Working-image stable layer IDs do not match the current scene.");
            end
            requiredMatch = ["MovingSourceRows", "MovingSourceColumns", ...
                "ReferenceSourceRows", "ReferenceSourceColumns", "Count"];
            if ~isstruct(pairMatch) || ~isscalar(pairMatch) || ...
                    any(~isfield(pairMatch, requiredMatch)) || ...
                    pairMatch.Count < options.MinimumSparseMatches
                error("ProjectionDenseSurfaceExtractor:insufficientMatches", ...
                    "Dense surface extraction needs at least %d accepted matches.", ...
                    options.MinimumSparseMatches);
            end
            outputSize = double(pairWorking.OutputSize(:).');
            if numel(outputSize) ~= 2 || any(outputSize < 8) || ...
                    any(outputSize ~= round(outputSize))
                error("ProjectionDenseSurfaceExtractor:invalidWorkingImages", ...
                    "Pair working images must have a common size of at least 8x8.");
            end
            PlanarProjection.validatePlane(pairWorking.ProjectionPlane);
        end

        function [movingPoints, referencePoints, diagnostics] = ...
                sparseWorkingPoints(scene, pairWorking, pairMatch, pair, ...
                minimumMatches)
            movingProjection = ProjectionAlignmentObservationProjector.project( ...
                scene, pair(1), pairMatch.MovingSourceRows, ...
                pairMatch.MovingSourceColumns, pairWorking.ProjectionPlane);
            referenceProjection = ...
                ProjectionAlignmentObservationProjector.project( ...
                scene, pair(2), pairMatch.ReferenceSourceRows, ...
                pairMatch.ReferenceSourceColumns, ...
                pairWorking.ProjectionPlane);
            valid = movingProjection.ValidMask & referenceProjection.ValidMask;
            movingPoints = ProjectionDenseSurfaceExtractor.planeToPixel( ...
                pairWorking.PixelToPlane, ...
                movingProjection.PlaneCoordinates(valid, :));
            referencePoints = ProjectionDenseSurfaceExtractor.planeToPixel( ...
                pairWorking.PixelToPlane, ...
                referenceProjection.PlaneCoordinates(valid, :));
            finite = all(isfinite(movingPoints), 2) & ...
                all(isfinite(referencePoints), 2);
            movingPoints = movingPoints(finite, :);
            referencePoints = referencePoints(finite, :);
            diagnostics = struct(InputCount=pairMatch.Count, ...
                CurrentProjectionValidCount=nnz(valid), ...
                WorkingPixelValidCount=nnz(finite));
            if size(movingPoints, 1) < minimumMatches
                error("ProjectionDenseSurfaceExtractor:insufficientMatches", ...
                    ["Fewer than %d accepted matches project into the " ...
                    "current working grid."], minimumMatches);
            end
        end

        function pixels = planeToPixel(pixelMap, planePoints)
            required = ["X", "Y"];
            if ~isstruct(pixelMap) || any(~isfield(pixelMap, required)) || ...
                    min(size(pixelMap.X)) < 2 || ...
                    ~isequal(size(pixelMap.X), size(pixelMap.Y))
                error("ProjectionDenseSurfaceExtractor:invalidPixelMap", ...
                    "PixelToPlane must contain compatible X and Y grids.");
            end
            origin = [pixelMap.X(1, 1); pixelMap.Y(1, 1)];
            columnStep = [pixelMap.X(1, 2); pixelMap.Y(1, 2)] - origin;
            rowStep = [pixelMap.X(2, 1); pixelMap.Y(2, 1)] - origin;
            transform = [columnStep rowStep];
            if rcond(transform) <= 1e-12
                error("ProjectionDenseSurfaceExtractor:invalidPixelMap", ...
                    "Pixel-to-plane grid is singular.");
            end
            offsets = transform \ (planePoints.' - origin);
            pixels = [offsets(1, :).' + 1, offsets(2, :).' + 1];
        end

        function [angle, direction] = rectificationAngle( ...
                movingPoints, referencePoints, options)
            displacements = movingPoints - referencePoints;
            center = median(displacements, 1);
            if norm(center) > options.MinimumSparseParallaxPixels
                direction = center / norm(center);
            else
                [~, singularValues, vectors] = svd(displacements, "econ");
                if isempty(singularValues) || singularValues(1, 1) <= ...
                        options.MinimumSparseParallaxPixels
                    error("ProjectionDenseSurfaceExtractor:insufficientParallax", ...
                        "Accepted matches do not define a usable parallax direction.");
                end
                direction = vectors(:, 1).';
                if median(displacements * direction.') < 0
                    direction = -direction;
                end
            end
            angle = -atan2(direction(2), direction(1));
        end

        function points = rotatePoints(points, center, angle)
            rotation = [cos(angle) -sin(angle); sin(angle) cos(angle)];
            points = (rotation * (points - center).').'+ center;
        end

        function rectified = rectifyLayer(layerImage, center, angle)
            required = ["Image", "ValidMask", "SourceRows", "SourceColumns"];
            if any(~isfield(layerImage, required))
                error("ProjectionDenseSurfaceExtractor:invalidWorkingImages", ...
                    "Layer working image lacks image, mask, or source maps.");
            end
            imageSize = size(layerImage.Image);
            imageSize = imageSize(1:2);
            [x, y] = meshgrid(1:imageSize(2), 1:imageSize(1));
            inverseRotation = [cos(angle) sin(angle); -sin(angle) cos(angle)];
            original = inverseRotation * ...
                ([x(:).'; y(:).'] - center.') + center.';
            originalX = reshape(original(1, :), imageSize);
            originalY = reshape(original(2, :), imageSize);
            validMask = ProjectionDenseSurfaceExtractor.sampleMap( ...
                double(layerImage.ValidMask), originalX, originalY, ...
                "nearest", 0) > 0.5;
            intensity = ProjectionDenseSurfaceExtractor.sampleMap( ...
                double(layerImage.Image), originalX, originalY, "linear", 0);
            intensity = ProjectionDenseSurfaceExtractor.normalizeIntensity( ...
                intensity, validMask);
            sourceRows = ProjectionDenseSurfaceExtractor.sampleMap( ...
                double(layerImage.SourceRows), originalX, originalY, ...
                "linear", NaN);
            sourceColumns = ProjectionDenseSurfaceExtractor.sampleMap( ...
                double(layerImage.SourceColumns), originalX, originalY, ...
                "linear", NaN);
            validMask = validMask & isfinite(sourceRows) & ...
                isfinite(sourceColumns);
            imageUint8 = im2uint8(intensity);
            imageUint8(~validMask) = 0;
            rectified = struct(Intensity=single(intensity), ...
                ImageUint8=imageUint8, ValidMask=validMask, ...
                SourceRows=sourceRows, SourceColumns=sourceColumns, ...
                OriginalX=originalX, OriginalY=originalY);
        end

        function normalized = normalizeIntensity(image, mask)
            normalized = zeros(size(image), "single");
            values = image(mask & isfinite(image));
            if isempty(values)
                return
            end
            lower = min(values);
            upper = max(values);
            if upper > lower
                normalized(mask) = single((image(mask) - lower) / ...
                    (upper - lower));
            else
                normalized(mask) = 0.5;
            end
        end

        function range = disparityRange(sparseDisparities, width, options)
            if ~isempty(options.DisparityRange)
                range = options.DisparityRange;
            else
                lower = floor(min(sparseDisparities) - ...
                    options.DisparityPaddingPixels);
                upper = ceil(max(sparseDisparities) + ...
                    options.DisparityPaddingPixels);
                span = upper - lower;
                if span > options.MaximumDisparitySpanPixels
                    center = median(sparseDisparities);
                    halfSpan = options.MaximumDisparitySpanPixels / 2;
                    lower = floor(center - halfSpan);
                    upper = ceil(center + halfSpan);
                end
                range = [lower upper];
            end
            limit = max(width - 1, 1);
            range = min(max(double(range), -limit), limit);
            if range(2) - range(1) < 16
                center = mean(range);
                range = [floor(center - 8), ceil(center + 8)];
                range = min(max(range, -limit), limit);
            end
            if range(2) <= range(1)
                error("ProjectionDenseSurfaceExtractor:invalidDisparityRange", ...
                    "The disparity range is empty after clipping to image width.");
            end
        end

        function [referenceX, referenceY] = referenceMatchGrid(disparity)
            [x, y] = meshgrid(1:size(disparity, 2), 1:size(disparity, 1));
            referenceX = x - double(disparity);
            referenceY = y;
        end

        function surface = triangulateSurface(scene, pair, plane, ...
                movingRectified, referenceRectified, disparity, ...
                validDisparity, options)
            count = nnz(validDisparity);
            stride = max(1, ceil(sqrt(count / options.MaximumSurfacePoints)));
            rowIndices = 1:stride:size(disparity, 1);
            columnIndices = 1:stride:size(disparity, 2);
            disparitySample = double(disparity(rowIndices, columnIndices));
            valid = validDisparity(rowIndices, columnIndices);
            [x, y] = meshgrid(columnIndices, rowIndices);
            referenceX = x - disparitySample;
            referenceY = y;

            movingRows = movingRectified.SourceRows(rowIndices, columnIndices);
            movingColumns = ...
                movingRectified.SourceColumns(rowIndices, columnIndices);
            referenceRows = ProjectionDenseSurfaceExtractor.sampleMap( ...
                referenceRectified.SourceRows, referenceX, referenceY, ...
                "linear", NaN);
            referenceColumns = ProjectionDenseSurfaceExtractor.sampleMap( ...
                referenceRectified.SourceColumns, referenceX, referenceY, ...
                "linear", NaN);
            valid = valid & isfinite(movingRows) & isfinite(movingColumns) & ...
                isfinite(referenceRows) & isfinite(referenceColumns);

            [movingOrigins, movingVectors, movingValid] = ...
                ProjectionDenseSurfaceExtractor.sampleRays( ...
                scene.layers(pair(1)), movingRows(:), movingColumns(:), plane);
            [referenceOrigins, referenceVectors, referenceValid] = ...
                ProjectionDenseSurfaceExtractor.sampleRays( ...
                scene.layers(pair(2)), referenceRows(:), ...
                referenceColumns(:), plane);
            rayValid = movingValid & referenceValid & valid(:);
            [midpoints, separations, forwardValid] = ...
                ProjectionDenseSurfaceExtractor.closestRayMidpoints( ...
                movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors);
            rayValid = rayValid & forwardValid & ...
                separations <= options.MaximumRaySeparationMeters;
            midpoints(:, ~rayValid) = NaN;
            planeCoordinates = nan(2, numel(rayValid));
            heights = nan(1, numel(rayValid));
            if any(rayValid)
                planeCoordinates(:, rayValid) = ...
                    PlanarProjection.worldToPlane( ...
                    midpoints(:, rayValid), plane);
                heights(rayValid) = plane.VN.' * ...
                    (midpoints(:, rayValid) - plane.P0);
            end

            outputSize = size(disparity);
            fullValid = false(outputSize);
            sampledLinear = sub2ind(outputSize, y(:), x(:));
            fullValid(sampledLinear(rayValid)) = true;
            layerCorrections = ...
                ProjectionDenseSurfaceExtractor.layerCorrections(scene, pair);
            surface = struct( ...
                X=reshape(planeCoordinates(1, :), size(x)), ...
                Y=reshape(planeCoordinates(2, :), size(x)), ...
                HeightMeters=reshape(heights, size(x)), ...
                Intensity=movingRectified.Intensity(rowIndices, columnIndices), ...
                RaySeparationMeters=reshape(separations, size(x)), ...
                ValidMask=reshape(rayValid, size(x)), ...
                FullResolutionValidMask=fullValid, Stride=stride, ...
                RowIndices=rowIndices, ColumnIndices=columnIndices, ...
                MovingSourceRows=reshape(movingRows, size(x)), ...
                MovingSourceColumns=reshape(movingColumns, size(x)), ...
                ReferenceSourceRows=reshape(referenceRows, size(x)), ...
                ReferenceSourceColumns=reshape(referenceColumns, size(x)), ...
                LayerCorrections=layerCorrections);
        end

        function [origins, vectors, valid] = sampleRays( ...
                layer, rows, columns, plane)
            rows = double(rows(:));
            columns = double(columns(:));
            count = numel(rows);
            origins = nan(3, count);
            vectors = nan(3, count);
            imageSize = double(layer.SourceGeometry.ImageSize(:).');
            candidate = isfinite(rows) & isfinite(columns) & ...
                rows >= 1 & rows <= imageSize(1) & ...
                columns >= 1 & columns <= imageSize(2);
            rotation = ProjectionMeshBuilder.viewVectorRotationMatrix( ...
                layer, plane);
            sourceGeometry = layer.SourceGeometry;
            if isfield(sourceGeometry, "SampleRayFcn") && ...
                    isa(sourceGeometry.SampleRayFcn, "function_handle")
                [origins, vectors] = ProjectionDenseSurfaceExtractor. ...
                    sampleExactRays(sourceGeometry.SampleRayFcn, rows, ...
                    columns, candidate, origins, vectors);
            else
                [origins, vectors] = ProjectionDenseSurfaceExtractor. ...
                    sampleMeshRays(layer, rows, columns, candidate, ...
                    origins, vectors);
            end
            vectors = rotation * vectors;
            valid = all(isfinite(origins), 1).' & ...
                all(isfinite(vectors), 1).' & ...
                sqrt(sum(vectors.^2, 1)).' > 1e-12;
        end

        function [origins, vectors] = sampleExactRays(sampleFcn, rows, ...
                columns, candidate, origins, vectors)
            indices = reshape(find(candidate), 1, []);
            if isempty(indices)
                return
            end
            try
                [sampledOrigins, sampledVectors] = sampleFcn( ...
                    rows(indices), columns(indices));
                if ~isequal(size(sampledOrigins), [3 numel(indices)]) || ...
                        ~isequal(size(sampledVectors), [3 numel(indices)])
                    error("ProjectionDenseSurfaceExtractor:invalidRaySampler", ...
                        "SampleRayFcn returned incompatible arrays.");
                end
                origins(:, indices) = double(sampledOrigins);
                vectors(:, indices) = double(sampledVectors);
                return
            catch
                % Custom samplers may support only scalar observations.
            end
            for index = indices
                try
                    [origin, vector] = sampleFcn(rows(index), columns(index));
                    if isequal(size(origin), [3 1]) && ...
                            isequal(size(vector), [3 1])
                        origins(:, index) = double(origin);
                        vectors(:, index) = double(vector);
                    end
                catch
                    % Leave this individual sample invalid.
                end
            end
        end

        function [origins, vectors] = sampleMeshRays(layer, rows, ...
                columns, candidate, origins, vectors)
            sampled = ProjectionMeshBuilder.sampleLayerGeometry(layer);
            for component = 1:3
                origins(component, candidate) = interp1( ...
                    sampled.ColumnIndices, ...
                    sampled.SampledOrigins(component, :), ...
                    columns(candidate), "linear", NaN);
                vectorGrid = squeeze( ...
                    sampled.SampledVectors(component, :, :));
                vectors(component, candidate) = interp2( ...
                    sampled.ColumnIndices, sampled.RowIndices, vectorGrid, ...
                    columns(candidate), rows(candidate), "linear", NaN);
            end
        end

        function [midpoints, separations, valid] = closestRayMidpoints( ...
                firstOrigins, firstVectors, secondOrigins, secondVectors)
            firstNorms = sqrt(sum(firstVectors.^2, 1));
            secondNorms = sqrt(sum(secondVectors.^2, 1));
            firstVectors = firstVectors ./ firstNorms;
            secondVectors = secondVectors ./ secondNorms;
            delta = firstOrigins - secondOrigins;
            b = sum(firstVectors .* secondVectors, 1);
            d = sum(firstVectors .* delta, 1);
            e = sum(secondVectors .* delta, 1);
            denominator = 1 - b.^2;
            valid = all(isfinite(delta), 1) & isfinite(denominator) & ...
                abs(denominator) > 1e-10 & firstNorms > 1e-12 & ...
                secondNorms > 1e-12;
            firstRange = nan(size(denominator));
            secondRange = nan(size(denominator));
            firstRange(valid) = (b(valid).*e(valid) - d(valid)) ./ ...
                denominator(valid);
            secondRange(valid) = (e(valid) - b(valid).*d(valid)) ./ ...
                denominator(valid);
            valid = valid & firstRange > 0 & secondRange > 0;
            firstPoints = firstOrigins + firstVectors .* firstRange;
            secondPoints = secondOrigins + secondVectors .* secondRange;
            midpoints = 0.5 * (firstPoints + secondPoints);
            separations = sqrt(sum((firstPoints - secondPoints).^2, 1));
            midpoints(:, ~valid) = NaN;
            separations(~valid) = Inf;
            valid = valid(:);
            separations = separations(:);
        end

        function layerImage = layerImageForId(pairWorking, layerId)
            ids = string([pairWorking.LayerImages.LayerId]);
            index = find(ids == string(layerId), 1, "first");
            if isempty(index)
                error("ProjectionDenseSurfaceExtractor:missingLayerImage", ...
                    "Pair working images do not contain layer %s.", layerId);
            end
            layerImage = pairWorking.LayerImages(index);
        end

        function values = sampleMap(map, x, y, method, fillValue)
            values = interp2(double(map), double(x), double(y), ...
                method, fillValue);
        end

        function corrections = layerCorrections(scene, pair)
            corrections = repmat(struct(LayerIndex=0, LayerId="", ...
                ViewVectorAngularOffsetsDegrees=zeros(1, 3), ...
                ProjectionOffsetMeters=zeros(1, 2)), 1, 2);
            for k = 1:2
                layer = scene.layers(pair(k));
                corrections(k).LayerIndex = pair(k);
                corrections(k).LayerId = string(layer.LayerId);
                if isfield(layer, "ViewVectorAngularOffsetsDegrees")
                    corrections(k).ViewVectorAngularOffsetsDegrees = ...
                        reshape(double( ...
                        layer.ViewVectorAngularOffsetsDegrees), 1, 3);
                end
                if isfield(layer, "ProjectionOffsetMeters")
                    corrections(k).ProjectionOffsetMeters = ...
                        reshape(double(layer.ProjectionOffsetMeters), 1, 2);
                end
            end
        end

        function diagnostics = addSurfaceSummary(diagnostics, surface)
            heights = surface.HeightMeters(surface.ValidMask);
            separations = ...
                surface.RaySeparationMeters(surface.ValidMask);
            diagnostics.SurfacePointCount = nnz(surface.ValidMask);
            diagnostics.HeightRangeMeters = [NaN NaN];
            diagnostics.HeightMedianMeters = NaN;
            diagnostics.RaySeparationMedianMeters = NaN;
            diagnostics.RaySeparationP95Meters = NaN;
            if ~isempty(heights)
                diagnostics.HeightRangeMeters = [min(heights) max(heights)];
                diagnostics.HeightMedianMeters = median(heights);
                diagnostics.RaySeparationMedianMeters = median(separations);
                diagnostics.RaySeparationP95Meters = ...
                    ProjectionDenseSurfaceExtractor.percentile( ...
                    separations, 95);
            end
        end

        function value = percentile(values, percentage)
            values = sort(double(values(:)));
            if isempty(values)
                value = NaN;
                return
            end
            position = 1 + (numel(values) - 1) * percentage / 100;
            lower = floor(position);
            upper = ceil(position);
            fraction = position - lower;
            value = values(lower) * (1 - fraction) + ...
                values(upper) * fraction;
        end

        function value = optionalRange(value, name)
            if isempty(value)
                value = [];
                return
            end
            if ~isnumeric(value) || numel(value) ~= 2 || ...
                    any(~isfinite(value)) || value(2) <= value(1)
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be empty or an increasing finite two-vector.", name);
            end
            value = reshape(double(value), 1, []);
        end

        function value = positiveScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value <= 0
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be a positive finite scalar.", name);
            end
            value = double(value);
        end

        function value = positiveScalarOrInf(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    isnan(value) || value <= 0
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be positive or Inf.", name);
            end
            value = double(value);
        end

        function value = logicalScalar(value, name)
            if ~(islogical(value) || isnumeric(value)) || ~isscalar(value) || ...
                    (isnumeric(value) && (~isfinite(value) || ...
                    ~any(value == [0 1])))
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be a logical scalar.", name);
            end
            value = logical(value);
        end

        function value = nonnegativeScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value < 0
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be a nonnegative finite scalar.", name);
            end
            value = double(value);
        end

        function value = positiveInteger(value, name)
            value = ProjectionDenseSurfaceExtractor.positiveScalar(value, name);
            if value ~= round(value)
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be an integer.", name);
            end
        end

        function value = nonnegativeInteger(value, name)
            value = ProjectionDenseSurfaceExtractor.nonnegativeScalar( ...
                value, name);
            if value ~= round(value)
                error("ProjectionDenseSurfaceExtractor:invalidOptions", ...
                    "%s must be an integer.", name);
            end
        end
    end
end
