classdef ProjectionRobustMultiRayFusion < ProjectionSurfaceFusionAlgorithm
    %ProjectionRobustMultiRayFusion SDK adapter for authoritative B5 points.

    methods
        function metadata = metadata(~)
            metadata = struct( ...
                AlgorithmId="sightline.fusion.robust-multi-ray", ...
                Name="Robust multi-ray point-set adapter", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct(FusedPoints=true, VoxelEvidence=false, ...
                CompetingModes=true, Covariance=true), ...
                RequiredProducts="ProjectionMultiRayPointSet", ...
                Deterministic=true, Precision="double", ...
                MemoryEstimate="linearInPointCount", ...
                CpuSupported=true, GpuSupported=false, ...
                ProductRole="authoritativeReference");
        end

        function options = defaultOptions(~)
            options = struct();
        end

        function options = validateOptions(~, options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options) || ...
                    ~isempty(fieldnames(options))
                error("ProjectionRobustMultiRayFusion:invalidOptions", ...
                    "Robust multi-ray adapter has no algorithm options.");
            end
        end
    end

    methods (Access = protected)
        function result = fuseImpl(~, request, ~, ~)
            [inputPoints, rejections] = ...
                ProjectionSurfaceFusionSupport.selectPoints(request);
            fusedPoints = ProjectionSurfaceFusionSupport.standardPoints( ...
                inputPoints, request.PointSet.WorldFrame);
            result = struct(FusedPoints=fusedPoints, ...
                SparseVoxelEvidence=struct(), ...
                CompetingModes=ProjectionSurfaceFusionSupport. ...
                modeSummary(inputPoints), ...
                Uncertainty=struct(Policy= ...
                "retainAuthoritativeMultiRayCovariance", ...
                AvailableCount=nnz(string({fusedPoints.CovarianceStatus}) ~= ...
                "unavailable")), ...
                Contributors=ProjectionSurfaceFusionSupport. ...
                contributorSummary(inputPoints, fusedPoints), ...
                Rejections=rejections, ...
                Diagnostics=struct( ...
                InputStage="robustMultiView", PointSetRecomputed=false, ...
                Explanation="B5 robust multi-ray points are already authoritative."), ...
                Memory=struct(Bytes= ...
                ProjectionSurfaceFusionSupport.bytes(fusedPoints)), ...
                Execution=struct(Device="cpu"));
        end
    end
end
