classdef ProjectionPairwisePointCovariance
    %ProjectionPairwisePointCovariance Pair triangulation and linear covariance.

    properties (Constant)
        Format = "ProjectionPairwisePointCovariance"
        Version = 1
    end

    methods (Static)
        function result = reconstruct(request)
            %reconstruct Triangulate ray pairs and propagate pixel covariance.
            request = ProjectionPairwisePointCovariance.validate(request);
            count = size(request.FirstOrigins, 2);
            records = repmat(ProjectionPairwisePointCovariance.emptyRecord(), ...
                count, 1);
            for index = 1:count
                records(index) = ProjectionPairwisePointCovariance.one( ...
                    request, index);
            end
            result = struct(Format=ProjectionPairwisePointCovariance.Format, ...
                Version=ProjectionPairwisePointCovariance.Version, ...
                Status="complete", CoordinateFrame=request.WorldFrame, ...
                CovarianceUnits="metersSquared", ...
                ObservationOrdering="[firstColumn firstRow secondColumn secondRow]", ...
                Records=records, Count=count, ...
                ValidCount=nnz([records.Valid]), ...
                CovarianceAvailableCount=nnz( ...
                string({records.CovarianceStatus}) == "available"));
        end
    end

    methods (Static, Access = private)
        function request = validate(request)
            required = ["PairIds" "ViewIds" "FirstOrigins" ...
                "FirstVectors" "SecondOrigins" "SecondVectors"];
            if ~isstruct(request) || ~isscalar(request) || ...
                    any(~isfield(request, required))
                error("ProjectionPairwisePointCovariance:invalidRequest", ...
                    "Pair IDs, view IDs, origins, and vectors are required.");
            end
            count = size(request.FirstOrigins, 2);
            arrays = ["FirstOrigins" "FirstVectors" ...
                "SecondOrigins" "SecondVectors"];
            for field = arrays
                if ~isnumeric(request.(field)) || ...
                        ~isequal(size(request.(field)), [3 count]) || ...
                        any(~isfinite(request.(field)), "all")
                    error("ProjectionPairwisePointCovariance:invalidRequest", ...
                        "%s must be a finite 3xN array.", field);
                end
                request.(field) = double(request.(field));
            end
            request.PairIds = string(request.PairIds(:));
            request.ViewIds = string(request.ViewIds);
            if numel(request.PairIds) ~= count || ...
                    ~isequal(size(request.ViewIds), [count 2])
                error("ProjectionPairwisePointCovariance:invalidRequest", ...
                    "Identity arrays must match the ray-pair count.");
            end
            defaults = struct(ObservationCovariancePixelsSquared=[], ...
                RayStateCovarianceWorld=[], ...
                FirstDirectionJacobian=zeros(3, 2, count), ...
                SecondDirectionJacobian=zeros(3, 2, count), ...
                WorldFrame="sceneWorld", CovarianceStatus="assumed", ...
                LinearizationStepPixels=1e-3, ...
                LinearizationStepRayState=1e-6, ...
                MaximumConditionNumber=1e8);
            names = fieldnames(defaults);
            for index = 1:numel(names)
                if ~isfield(request, names{index})
                    request.(names{index}) = defaults.(names{index});
                end
            end
            if ~isempty(request.ObservationCovariancePixelsSquared) && ...
                    (~isnumeric(request.ObservationCovariancePixelsSquared) || ...
                    size(request.ObservationCovariancePixelsSquared, 1) ~= 4 || ...
                    size(request.ObservationCovariancePixelsSquared, 2) ~= 4 || ...
                    numel(request.ObservationCovariancePixelsSquared) ~= ...
                    16 * count || any(~isfinite( ...
                    request.ObservationCovariancePixelsSquared), "all"))
                error("ProjectionPairwisePointCovariance:invalidCovariance", ...
                    "Observation covariance must be empty or finite 4x4xN.");
            end
            if ~isempty(request.ObservationCovariancePixelsSquared)
                request.ObservationCovariancePixelsSquared = reshape( ...
                    double(request.ObservationCovariancePixelsSquared), ...
                    4, 4, count);
            end
            if ~isempty(request.RayStateCovarianceWorld) && ...
                    (~isnumeric(request.RayStateCovarianceWorld) || ...
                    size(request.RayStateCovarianceWorld, 1) ~= 12 || ...
                    size(request.RayStateCovarianceWorld, 2) ~= 12 || ...
                    numel(request.RayStateCovarianceWorld) ~= 144 * count || ...
                    any(~isfinite(request.RayStateCovarianceWorld), "all"))
                error("ProjectionPairwisePointCovariance:invalidCovariance", ...
                    "Ray-state covariance must be empty or finite 12x12xN.");
            end
            if ~isempty(request.RayStateCovarianceWorld)
                request.RayStateCovarianceWorld = reshape( ...
                    double(request.RayStateCovarianceWorld), 12, 12, count);
            end
            jacobians = ["FirstDirectionJacobian" ...
                "SecondDirectionJacobian"];
            for field = jacobians
                if ~isnumeric(request.(field)) || ...
                        size(request.(field), 1) ~= 3 || ...
                        size(request.(field), 2) ~= 2 || ...
                        numel(request.(field)) ~= 6 * count || ...
                        any(~isfinite(request.(field)), "all")
                    error("ProjectionPairwisePointCovariance:invalidRequest", ...
                        "%s must be a finite 3x2xN array.", field);
                end
                request.(field) = reshape(double(request.(field)), 3, 2, count);
            end
            request.WorldFrame = string(request.WorldFrame);
            request.CovarianceStatus = string(request.CovarianceStatus);
            if ~isscalar(request.WorldFrame) || strlength(request.WorldFrame) == 0 || ...
                    ~isscalar(request.CovarianceStatus) || ...
                    ~ismember(request.CovarianceStatus, ...
                    ["prior" "posterior" "calibrated" "assumed"])
                error("ProjectionPairwisePointCovariance:invalidRequest", ...
                    "Covariance frame and status must be explicit.");
            end
            scalarFields = ["LinearizationStepPixels" ...
                "LinearizationStepRayState" "MaximumConditionNumber"];
            for field = scalarFields
                if ~isnumeric(request.(field)) || ...
                        ~isscalar(request.(field)) || ...
                        ~isfinite(request.(field)) || request.(field) <= 0
                    error("ProjectionPairwisePointCovariance:invalidRequest", ...
                        "%s must be a finite positive scalar.", field);
                end
                request.(field) = double(request.(field));
            end
        end

        function record = one(request, index)
            firstOrigin = request.FirstOrigins(:, index);
            secondOrigin = request.SecondOrigins(:, index);
            firstVector = request.FirstVectors(:, index);
            secondVector = request.SecondVectors(:, index);
            [point, separation, ranges, valid, condition] = ...
                ProjectionPairwisePointCovariance.triangulate( ...
                firstOrigin, firstVector, secondOrigin, secondVector);
            covariance = zeros(3);
            covarianceStatus = "unavailable";
            covarianceReason = "observationAndGeometryCovarianceMissing";
            reliable = false;
            available = false;
            if valid && ~isempty(request.ObservationCovariancePixelsSquared)
                inputCovariance = request.ObservationCovariancePixelsSquared(:, :, index);
                firstJacobian = request.FirstDirectionJacobian(:, :, index);
                secondJacobian = request.SecondDirectionJacobian(:, :, index);
                pointJacobian = ProjectionPairwisePointCovariance.pointJacobian( ...
                    firstOrigin, firstVector, firstJacobian, secondOrigin, ...
                    secondVector, secondJacobian, ...
                    request.LinearizationStepPixels);
                covariance = covariance + ...
                    pointJacobian * inputCovariance * pointJacobian.';
                available = true;
            end
            if valid && ~isempty(request.RayStateCovarianceWorld)
                rayJacobian = ProjectionPairwisePointCovariance.rayStateJacobian( ...
                    firstOrigin, firstVector, secondOrigin, secondVector, ...
                    request.LinearizationStepRayState);
                covariance = covariance + rayJacobian * ...
                    request.RayStateCovarianceWorld(:, :, index) * rayJacobian.';
                available = true;
            end
            if available
                covariance = 0.5 * (covariance + covariance.');
                covarianceStatus = "available";
                covarianceReason = "";
                reliable = all(eig(covariance) >= -1e-10) && ...
                    condition <= request.MaximumConditionNumber;
                if ~reliable
                    covarianceStatus = "unreliable";
                    covarianceReason = "weakGeometryOrNonPsdLinearization";
                end
            else
                covariance(:) = NaN;
            end
            axes = nan(3, 1);
            if all(isfinite(covariance), "all")
                axes = sqrt(max(sort(eig(covariance), "descend"), 0));
            end
            record = struct(PairId=request.PairIds(index), ...
                ViewIds=request.ViewIds(index, :), PointWorld=point, ...
                Valid=valid, RayParameters=ranges, ...
                RaySeparationMeters=separation, ...
                IntersectionAngleDegrees=rad2deg(acos(min(1, max(-1, ...
                abs(dot(firstVector / norm(firstVector), ...
                secondVector / norm(secondVector))))))), ...
                ConditionNumber=condition, CovarianceWorldMetersSquared=covariance, ...
                PrincipalAxisSigmasMeters=axes, ...
                CovarianceStatus=covarianceStatus, ...
                CovarianceReason=covarianceReason, ...
                CovarianceFrame=request.WorldFrame, ...
                ObservationCovarianceStatus=request.CovarianceStatus, ...
                ReliableLinearization=reliable);
        end

        function jacobian = pointJacobian(o1, v1, j1, o2, v2, j2, step)
            jacobian = zeros(3, 4);
            for component = 1:4
                delta1 = zeros(3, 1);
                delta2 = zeros(3, 1);
                if component <= 2
                    delta1 = j1(:, component) * step;
                else
                    delta2 = j2(:, component - 2) * step;
                end
                plus = ProjectionPairwisePointCovariance.triangulate( ...
                    o1, v1 + delta1, o2, v2 + delta2);
                minus = ProjectionPairwisePointCovariance.triangulate( ...
                    o1, v1 - delta1, o2, v2 - delta2);
                jacobian(:, component) = (plus - minus) / (2 * step);
            end
        end

        function jacobian = rayStateJacobian(o1, v1, o2, v2, step)
            jacobian = zeros(3, 12);
            for component = 1:12
                delta = zeros(12, 1);
                delta(component) = step;
                plus = ProjectionPairwisePointCovariance.triangulate( ...
                    o1 + delta(1:3), v1 + delta(4:6), ...
                    o2 + delta(7:9), v2 + delta(10:12));
                minus = ProjectionPairwisePointCovariance.triangulate( ...
                    o1 - delta(1:3), v1 - delta(4:6), ...
                    o2 - delta(7:9), v2 - delta(10:12));
                jacobian(:, component) = (plus - minus) / (2 * step);
            end
        end

        function [point, separation, ranges, valid, condition] = ...
                triangulate(firstOrigin, firstVector, secondOrigin, secondVector)
            firstVector = firstVector / norm(firstVector);
            secondVector = secondVector / norm(secondVector);
            matrix = [firstVector -secondVector];
            singularValues = svd(matrix, "econ");
            condition = singularValues(1) / max(singularValues(end), eps);
            ranges = matrix \ (secondOrigin - firstOrigin);
            firstPoint = firstOrigin + firstVector * ranges(1);
            secondPoint = secondOrigin + secondVector * ranges(2);
            point = 0.5 * (firstPoint + secondPoint);
            separation = norm(firstPoint - secondPoint);
            valid = all(isfinite(point)) && all(ranges > 0) && ...
                singularValues(end) > 1e-10;
            if ~valid
                point(:) = NaN;
            end
        end

        function record = emptyRecord()
            record = struct(PairId="", ViewIds=strings(1, 2), ...
                PointWorld=nan(3, 1), Valid=false, RayParameters=nan(2, 1), ...
                RaySeparationMeters=Inf, IntersectionAngleDegrees=NaN, ...
                ConditionNumber=Inf, CovarianceWorldMetersSquared=nan(3), ...
                PrincipalAxisSigmasMeters=nan(3, 1), ...
                CovarianceStatus="unavailable", CovarianceReason="notRun", ...
                CovarianceFrame="", ObservationCovarianceStatus="", ...
                ReliableLinearization=false);
        end
    end
end
