classdef ProjectionDenseMatchRequest
    %ProjectionDenseMatchRequest Validate graphics-independent matcher input.

    properties (Constant)
        Format = "ProjectionDenseMatchRequest"
        Version = 1
    end

    methods (Static)
        function request = validate(request)
            %validate Normalize one dense-correspondence request.
            if ~isstruct(request) || ~isscalar(request)
                error("ProjectionDenseMatchRequest:invalidRequest", ...
                    "Dense matcher request must be a scalar struct.");
            end
            required = ["PairId" "ViewIds" "AnalysisImages" ...
                "ValidityMasks" "SourceRows" "SourceColumns"];
            if any(~isfield(request, required))
                error("ProjectionDenseMatchRequest:invalidRequest", ...
                    "Request must contain pair/view identity, images, masks, and source maps.");
            end
            forbidden = ["DisplayPyramid" "PreviewCoordinates" "Surface"];
            if any(isfield(request, forbidden))
                error("ProjectionDenseMatchRequest:forbiddenPresentationData", ...
                    "Requests cannot contain preview, pyramid, or surface products.");
            end
            defaults = struct(Format=ProjectionDenseMatchRequest.Format, ...
                Version=ProjectionDenseMatchRequest.Version, ...
                PairId="", ViewIds=strings(1, 0), AnalysisImages={{}}, ...
                ValidityMasks={{}}, SourceRows={{}}, SourceColumns={{}}, ...
                CorrectedGeometry=repmat(struct(), 1, 2), ...
                OverlapMask=[], Roi=[], SearchPrediction=struct(), ...
                PrecisionPolicy=struct(Geometry="double", ...
                WorkingRadiometry="preserve"), Seed=0, Context=struct());
            names = fieldnames(request);
            unknown = setdiff(string(names), string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDenseMatchRequest:invalidRequest", ...
                    "Unexpected request field: %s.", unknown(1));
            end
            for index = 1:numel(names)
                defaults.(names{index}) = request.(names{index});
            end
            defaults.PairId = ProjectionDenseMatchRequest.nonemptyString( ...
                defaults.PairId, "PairId");
            defaults.ViewIds = reshape(string(defaults.ViewIds), 1, []);
            if numel(defaults.ViewIds) ~= 2 || ...
                    any(ismissing(defaults.ViewIds)) || ...
                    any(strlength(defaults.ViewIds) == 0) || ...
                    defaults.ViewIds(1) == defaults.ViewIds(2)
                error("ProjectionDenseMatchRequest:invalidIdentity", ...
                    "ViewIds must contain two distinct nonempty strings.");
            end
            fields = ["AnalysisImages" "ValidityMasks" ...
                "SourceRows" "SourceColumns"];
            for field = fields
                if ~iscell(defaults.(field)) || ...
                        ~isequal(size(defaults.(field)), [1 2])
                    error("ProjectionDenseMatchRequest:invalidArrays", ...
                        "%s must be a 1x2 cell array.", field);
                end
            end
            for viewIndex = 1:2
                image = defaults.AnalysisImages{viewIndex};
                mask = defaults.ValidityMasks{viewIndex};
                rows = defaults.SourceRows{viewIndex};
                columns = defaults.SourceColumns{viewIndex};
                if ~isnumeric(image) || isempty(image) || ~ismatrix(image) || ...
                        any(~isfinite(image), "all")
                    error("ProjectionDenseMatchRequest:invalidArrays", ...
                        "Analysis images must be nonempty finite 2-D numeric arrays.");
                end
                if ~islogical(mask) || ~isequal(size(mask), size(image)) || ...
                        ~isnumeric(rows) || ~isequal(size(rows), size(image)) || ...
                        ~isnumeric(columns) || ...
                        ~isequal(size(columns), size(image))
                    error("ProjectionDenseMatchRequest:invalidArrays", ...
                        "Masks and source maps must match each analysis image.");
                end
                if any(~isfinite(rows(mask)), "all") || ...
                        any(~isfinite(columns(mask)), "all")
                    error("ProjectionDenseMatchRequest:invalidArrays", ...
                        "Valid analysis pixels require finite source coordinates.");
                end
            end
            imageSize = size(defaults.AnalysisImages{1});
            if ~isequal(size(defaults.AnalysisImages{2}), imageSize)
                error("ProjectionDenseMatchRequest:invalidArrays", ...
                    "Both analysis images must share one working-grid size.");
            end
            if isempty(defaults.OverlapMask)
                defaults.OverlapMask = defaults.ValidityMasks{1} & ...
                    defaults.ValidityMasks{2};
            elseif ~islogical(defaults.OverlapMask) || ...
                    ~isequal(size(defaults.OverlapMask), imageSize)
                error("ProjectionDenseMatchRequest:invalidArrays", ...
                    "OverlapMask must be logical and match the analysis images.");
            end
            if isempty(defaults.Roi)
                defaults.Roi = [1 imageSize(2) 1 imageSize(1)];
            elseif ~isnumeric(defaults.Roi) || ...
                    ~isequal(size(defaults.Roi), [1 4]) || ...
                    any(~isfinite(defaults.Roi)) || ...
                    defaults.Roi(1) > defaults.Roi(2) || ...
                    defaults.Roi(3) > defaults.Roi(4)
                error("ProjectionDenseMatchRequest:invalidRoi", ...
                    "Roi must be finite [columnMin columnMax rowMin rowMax].");
            end
            structFields = ["SearchPrediction" "PrecisionPolicy" "Context"];
            for field = structFields
                if ~isstruct(defaults.(field)) || ~isscalar(defaults.(field))
                    error("ProjectionDenseMatchRequest:invalidRequest", ...
                        "%s must be a scalar struct.", field);
                end
            end
            if ~isstruct(defaults.CorrectedGeometry) || ...
                    numel(defaults.CorrectedGeometry) ~= 2
                error("ProjectionDenseMatchRequest:invalidGeometry", ...
                    "CorrectedGeometry must contain two struct values.");
            end
            if ~isnumeric(defaults.Seed) || ~isscalar(defaults.Seed) || ...
                    ~isfinite(defaults.Seed) || defaults.Seed < 0 || ...
                    fix(defaults.Seed) ~= defaults.Seed
                error("ProjectionDenseMatchRequest:invalidSeed", ...
                    "Seed must be a finite nonnegative integer scalar.");
            end
            defaults.Seed = double(defaults.Seed);
            request = defaults;
        end
    end

    methods (Static, Access = private)
        function value = nonemptyString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || strlength(value) == 0
                error("ProjectionDenseMatchRequest:invalidIdentity", ...
                    "%s must be a nonempty string scalar.", name);
            end
        end
    end
end
