classdef ProjectionSurfaceFusionRequest
    %ProjectionSurfaceFusionRequest Validate bounded surface-fusion input.

    properties (Constant)
        Format = "ProjectionSurfaceFusionRequest"
        Version = 1
    end

    methods (Static)
        function request = validate(request)
            %validate Normalize one graphics-independent fusion request.
            if ~isstruct(request) || ~isscalar(request)
                error("ProjectionSurfaceFusionRequest:invalidRequest", ...
                    "Surface-fusion request must be a scalar struct.");
            end
            forbidden = ["Truth" "DisplayPyramid" "PreviewCoordinates" ...
                "Graphics" "ProgressFcn" "CancellationFcn"];
            if any(isfield(request, forbidden))
                error("ProjectionSurfaceFusionRequest:forbiddenData", ...
                    "Truth, presentation state, and runtime callbacks are not portable fusion inputs.");
            end
            defaults = struct( ...
                Format=ProjectionSurfaceFusionRequest.Format, ...
                Version=ProjectionSurfaceFusionRequest.Version, ...
                PointSet=struct(), RoiWorld=[], VoxelScalesMeters=[], ...
                GsdMeters=[], VoxelScaleMultipliers=[0.5 1 2], ...
                BaseVoxelScaleMeters=NaN, VoxelScaleSource="", ...
                PrecisionPolicy=struct(Geometry="double", ...
                Evidence="double", Final="double"), ...
                Seed=0, Context=struct());
            names = string(fieldnames(request));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionSurfaceFusionRequest:invalidRequest", ...
                    "Unexpected fusion-request field: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = request.(name);
            end
            defaults.Format = string(defaults.Format);
            if ~isscalar(defaults.Format) || ismissing(defaults.Format) || ...
                    defaults.Format ~= ProjectionSurfaceFusionRequest.Format || ...
                    ~isequal(defaults.Version, ...
                    ProjectionSurfaceFusionRequest.Version)
                error("ProjectionSurfaceFusionRequest:unsupportedSchema", ...
                    "Fusion request Format and Version must be supported.");
            end
            defaults.PointSet = ProjectionSurfaceFusionRequest. ...
                validatePointSet(defaults.PointSet);
            defaults.RoiWorld = ProjectionSurfaceFusionRequest. ...
                validateRoi(defaults.RoiWorld);
            defaults.GsdMeters = ProjectionSurfaceFusionRequest. ...
                optionalPositiveScalar(defaults.GsdMeters, "GsdMeters");
            defaults.VoxelScaleMultipliers = ...
                ProjectionSurfaceFusionRequest.positiveVector( ...
                defaults.VoxelScaleMultipliers, "VoxelScaleMultipliers");
            explicitScales = ProjectionSurfaceFusionRequest.positiveVector( ...
                defaults.VoxelScalesMeters, "VoxelScalesMeters", true);
            if isempty(explicitScales)
                [baseScale, source] = ProjectionSurfaceFusionRequest. ...
                    derivedScale(defaults.PointSet, defaults.GsdMeters);
                defaults.VoxelScalesMeters = unique( ...
                    baseScale * defaults.VoxelScaleMultipliers, "sorted");
                defaults.BaseVoxelScaleMeters = baseScale;
                defaults.VoxelScaleSource = source;
            else
                defaults.VoxelScalesMeters = unique(explicitScales, "sorted");
                defaults.BaseVoxelScaleMeters = median(explicitScales);
                defaults.VoxelScaleSource = "explicit";
            end
            defaults.PrecisionPolicy = ProjectionSurfaceFusionRequest. ...
                validatePrecision(defaults.PrecisionPolicy);
            defaults.Seed = ProjectionSurfaceFusionRequest.seed(defaults.Seed);
            if ~isstruct(defaults.Context) || ~isscalar(defaults.Context) || ...
                    ProjectionSurfaceFusionRequest.hasRuntimeValue( ...
                    defaults.Context)
                error("ProjectionSurfaceFusionRequest:invalidContext", ...
                    "Context must be a scalar portable value struct.");
            end
            request = defaults;
        end
    end

    methods (Static, Access = private)
        function pointSet = validatePointSet(pointSet)
            required = ["Format" "Version" "WorldFrame" "GenerationId" ...
                "Points" "RawPairwiseRecords" "AssociationTracks"];
            if ~isstruct(pointSet) || ~isscalar(pointSet) || ...
                    any(~isfield(pointSet, required))
                error("ProjectionSurfaceFusionRequest:invalidPointSet", ...
                    "A complete robust multi-view point set is required.");
            end
            format = string(pointSet.Format);
            if ~isscalar(format) || ismissing(format) || ...
                    format ~= ProjectionMultiRayReconstructor.Format || ...
                    ~isequal(pointSet.Version, ...
                    ProjectionMultiRayReconstructor.Version)
                error("ProjectionSurfaceFusionRequest:unsupportedPointSet", ...
                    "Point-set Format or Version is unsupported.");
            end
            pointSet.WorldFrame = string(pointSet.WorldFrame);
            pointSet.GenerationId = string(pointSet.GenerationId);
            if ~isscalar(pointSet.WorldFrame) || ...
                    strlength(pointSet.WorldFrame) == 0 || ...
                    ~isscalar(pointSet.GenerationId) || ...
                    strlength(pointSet.GenerationId) == 0 || ...
                    ~isstruct(pointSet.Points) || ...
                    ~isstruct(pointSet.RawPairwiseRecords) || ...
                    ~isstruct(pointSet.AssociationTracks)
                error("ProjectionSurfaceFusionRequest:invalidPointSet", ...
                    "Point-set identity and value arrays must be explicit.");
            end
            requiredPoint = ["PointId" "ModeId" "CompetingMode" "Valid" ...
                "PointWorld" "ContributingViewIds" "ContributingPassIds" ...
                "IndependentViewCount" "IndependentPassCount" ...
                "PairRecordCount" "RayDiagnostics" ...
                "CovarianceWorldMetersSquared" "CovarianceStatus" ...
                "CovarianceReason" "CovarianceFrame" ...
                "PrincipalAxisSigmasMeters" "VisibilityState"];
            pointIds = strings(1, numel(pointSet.Points));
            for index = 1:numel(pointSet.Points)
                point = pointSet.Points(index);
                if any(~isfield(point, requiredPoint))
                    error("ProjectionSurfaceFusionRequest:invalidPointSet", ...
                        "Every point must retain fusion identity, evidence, and uncertainty.");
                end
                pointId = string(point.PointId);
                stringValues = {pointId string(point.ModeId) ...
                    string(point.CovarianceStatus) ...
                    string(point.CovarianceReason) ...
                    string(point.CovarianceFrame) ...
                    string(point.VisibilityState)};
                invalidString = cellfun(@(value) ~isscalar(value) || ...
                    ismissing(value), stringValues);
                viewIds = reshape(string(point.ContributingViewIds), 1, []);
                passIds = reshape(string(point.ContributingPassIds), 1, []);
                covarianceInput = point.CovarianceWorldMetersSquared;
                covarianceShape = isnumeric(covarianceInput) && ...
                    isequal(size(covarianceInput), [3 3]);
                if covarianceShape
                    covariance = double(covarianceInput);
                else
                    covariance = zeros(0);
                end
                covarianceValid = ProjectionSurfaceFusionRequest. ...
                    covarianceValid(covariance);
                sigmaInput = point.PrincipalAxisSigmasMeters;
                sigmaShape = isnumeric(sigmaInput) && numel(sigmaInput) == 3;
                if sigmaShape
                    sigmas = double(sigmaInput(:));
                else
                    sigmas = zeros(0, 1);
                end
                sigmasValid = sigmaShape && ...
                    (all(isfinite(sigmas) & sigmas >= 0) || all(isnan(sigmas)));
                countValues = {point.IndependentViewCount ...
                    point.IndependentPassCount point.PairRecordCount};
                countsValid = all(cellfun(@(value) isnumeric(value) && ...
                    isscalar(value) && isfinite(value) && value >= 0 && ...
                    fix(value) == value, countValues));
                if ~isscalar(pointId) || ismissing(pointId) || ...
                        strlength(pointId) == 0 || ...
                        any(invalidString) || ...
                        ~islogical(point.Valid) || ~isscalar(point.Valid) || ...
                        ~islogical(point.CompetingMode) || ...
                        ~isscalar(point.CompetingMode) || ...
                        ~isnumeric(point.PointWorld) || ...
                        ~isequal(size(point.PointWorld), [3 1]) || ...
                        ~covarianceShape || ...
                        ~covarianceValid || ...
                        ~sigmasValid || ~isstruct(point.RayDiagnostics) || ...
                        ~countsValid || any(ismissing(viewIds)) || ...
                        any(strlength(viewIds) == 0) || any(ismissing(passIds)) || ...
                        any(strlength(passIds) == 0) || ...
                        point.IndependentViewCount ~= numel(unique(viewIds)) || ...
                        point.IndependentPassCount ~= numel(unique(passIds)) || ...
                        string(point.CovarianceFrame) ~= pointSet.WorldFrame
                    error("ProjectionSurfaceFusionRequest:invalidPointSet", ...
                        "Point geometry, covariance, or ray evidence is malformed.");
                end
                pointIds(index) = pointId;
                if point.Valid && any(~isfinite(point.PointWorld))
                    error("ProjectionSurfaceFusionRequest:invalidPointSet", ...
                        "Valid points require finite world coordinates.");
                end
            end
            if numel(unique(pointIds)) ~= numel(pointIds)
                error("ProjectionSurfaceFusionRequest:duplicatePointId", ...
                    "Every fusion input point requires a unique PointId.");
            end
        end

        function roi = validateRoi(roi)
            if ~isnumeric(roi) || ~isequal(size(roi), [3 2]) || ...
                    any(~isfinite(roi), "all") || any(roi(:, 1) >= roi(:, 2))
                error("ProjectionSurfaceFusionRequest:invalidRoi", ...
                    "RoiWorld must be finite 3x2 [minimum maximum] bounds.");
            end
            roi = double(roi);
        end

        function value = optionalPositiveScalar(value, name)
            if isempty(value)
                value = [];
                return
            end
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value <= 0
                error("ProjectionSurfaceFusionRequest:invalidScale", ...
                    "%s must be empty or a finite positive scalar.", name);
            end
            value = double(value);
        end

        function values = positiveVector(values, name, allowEmpty)
            if nargin < 3
                allowEmpty = false;
            end
            if isempty(values) && allowEmpty
                values = zeros(1, 0);
                return
            end
            if ~isnumeric(values) || ~isvector(values) || isempty(values) || ...
                    any(~isfinite(values)) || any(values <= 0)
                error("ProjectionSurfaceFusionRequest:invalidScale", ...
                    "%s must be a finite positive vector.", name);
            end
            values = reshape(double(values), 1, []);
        end

        function [scale, source] = derivedScale(pointSet, gsd)
            if ~isempty(gsd)
                scale = gsd;
                source = "gsd";
                return
            end
            sigmas = zeros(1, 0);
            for point = pointSet.Points
                values = double(point.PrincipalAxisSigmasMeters(:));
                values = values(isfinite(values) & values > 0);
                if ~isempty(values)
                    sigmas(end + 1) = max(values); %#ok<AGROW>
                end
            end
            if isempty(sigmas)
                error("ProjectionSurfaceFusionRequest:scaleUnavailable", ...
                    "Voxel scale needs explicit values, GSD, or point uncertainty.");
            end
            scale = median(sigmas);
            source = "pointUncertainty";
        end

        function policy = validatePrecision(policy)
            defaults = struct(Geometry="double", Evidence="double", ...
                Final="double");
            if ~isstruct(policy) || ~isscalar(policy) || ...
                    ~isequal(sort(string(fieldnames(policy))), ...
                    sort(string(fieldnames(defaults))))
                error("ProjectionSurfaceFusionRequest:invalidPrecision", ...
                    "PrecisionPolicy must declare Geometry, Evidence, and Final.");
            end
            policy.Geometry = string(policy.Geometry);
            policy.Evidence = string(policy.Evidence);
            policy.Final = string(policy.Final);
            if ~isscalar(policy.Geometry) || ~isscalar(policy.Evidence) || ...
                    ~isscalar(policy.Final) || ismissing(policy.Geometry) || ...
                    ismissing(policy.Evidence) || ismissing(policy.Final) || ...
                    policy.Geometry ~= "double" || policy.Final ~= "double" || ...
                    ~ismember(policy.Evidence, ["double" "single"])
                error("ProjectionSurfaceFusionRequest:invalidPrecision", ...
                    "Geometry/final precision must be double; evidence may be double or single.");
            end
        end

        function value = seed(value)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 0 || fix(value) ~= value
                error("ProjectionSurfaceFusionRequest:invalidSeed", ...
                    "Seed must be a finite nonnegative integer.");
            end
            value = double(value);
        end

        function tf = hasRuntimeValue(value)
            if isa(value, "function_handle") || ...
                    (isobject(value) && isa(value, "handle")) || isjava(value)
                tf = true;
            elseif isstruct(value)
                tf = false;
                names = fieldnames(value);
                for elementIndex = 1:numel(value)
                    for nameIndex = 1:numel(names)
                        if ProjectionSurfaceFusionRequest.hasRuntimeValue( ...
                                value(elementIndex).(names{nameIndex}))
                            tf = true;
                            return
                        end
                    end
                end
            elseif iscell(value)
                tf = false;
                for index = 1:numel(value)
                    if ProjectionSurfaceFusionRequest.hasRuntimeValue(value{index})
                        tf = true;
                        return
                    end
                end
            else
                tf = false;
            end
        end

        function tf = covarianceValid(covariance)
            if all(isnan(covariance), "all")
                tf = true;
                return
            end
            if any(~isfinite(covariance), "all")
                tf = false;
                return
            end
            scale = max(1, norm(covariance, "fro"));
            symmetric = norm(covariance - covariance.', "fro") <= ...
                1e-10 * scale;
            tf = symmetric && all(eig(0.5 * ...
                (covariance + covariance.')) >= -1e-10 * scale);
        end
    end
end
