classdef ProjectionExampleSurfaceRegistration < ...
        ProjectionSurfaceRegistrationAlgorithm
    %ProjectionExampleSurfaceRegistration Minimal external-style composition.

    methods
        function metadata = metadata(~)
            metadata = struct(AlgorithmId="example.robust-dem-adapter", ...
                Name="Example composed DEM registration adapter", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct(DelegatesToTrustedBuiltIn=true, ...
                ProposedCorrection=true), ...
                AllowedTransform="globalTranslation", Deterministic=true, ...
                Precision="double", CpuSupported=true, GpuSupported=false);
        end

        function options = defaultOptions(~)
            options = ProjectionRobustDemTranslation().defaultOptions();
        end

        function options = validateOptions(~, options)
            options = ProjectionRobustDemTranslation().validateOptions(options);
        end
    end

    methods (Access = protected)
        function result = registerImpl(~, request, options, runtimeControl)
            delegated = ProjectionRobustDemTranslation().register( ...
                request, options, runtimeControl);
            correction = delegated.CorrectionSetData;
            correction.GenerationId = "example-dem-registration-" + ...
                extractBefore(ProjectionGeometryFingerprint.hash(struct( ...
                Source=correction.GenerationId, ...
                Adapter="example.robust-dem-adapter")), 17);
            correction.Provenance.AlgorithmId = ...
                "example.robust-dem-adapter";
            correction.Provenance.DelegatedAlgorithmId = ...
                delegated.AlgorithmId;
            correction = ProjectionCorrectionSet.create(correction).toStruct();
            result = rmfield(delegated, ["Format" "Version" "Stage" ...
                "WorldFrame" "AlgorithmId" "Timing" "Execution" ...
                "Provenance" "Precision"]);
            result.CorrectionSetData = correction;
            result.Diagnostics.DelegatedAlgorithmId = delegated.AlgorithmId;
        end
    end
end
