classdef ProjectionDenseObservationAssociator
    %ProjectionDenseObservationAssociator Form provenance-rich dense tracks.

    properties (Constant)
        Format = "ProjectionDenseObservationAssociation"
        Version = 1
        RequestFormat = "ProjectionDensePairObservationRecords"
        RequestVersion = 1
    end

    methods (Static)
        function options = defaults()
            %defaults Return deterministic association and quality gates.
            options = struct( ...
                MinimumPairAngleDegrees=0.1, ...
                MinimumTextureScore=0.05, ...
                MinimumNavigationWeight=0.05, ...
                MinimumRadiometricConsistency=0.05, ...
                SourceObservationTolerancePixels=0.25, ...
                RayOriginToleranceMeters=1e-6, ...
                RayDirectionToleranceDegrees=1e-5, ...
                ModeSeparationMeters=Inf);
        end

        function result = associate(request, options, runtimeControl)
            %associate Reconcile dense pair observations into stable tracks.
            if nargin < 2
                options = struct();
            end
            if nargin < 3
                runtimeControl = struct();
            end
            runtimeControl = ProjectionDenseObservationAssociator. ...
                validateRuntimeControl(runtimeControl);
            started = tic;
            options = ProjectionDenseObservationAssociator.validateOptions( ...
                options);
            request = ProjectionDenseObservationAssociator.validateRequest( ...
                request);
            ProjectionDenseObservationAssociator.publishProgress( ...
                runtimeControl, 0, "normalize", 0, numel(request.Records), ...
                started);
            ProjectionDenseObservationAssociator.checkCancelled(runtimeControl);
            records = ProjectionDenseObservationAssociator.normalizeRecords( ...
                request.Records, runtimeControl, started);
            [observations, records, groupingWork] = ...
                ProjectionDenseObservationAssociator.collectObservations( ...
                records, options, runtimeControl, started);
            records = ProjectionDenseObservationAssociator.precheckRecords( ...
                records, observations, options, runtimeControl, started);
            [records, tracks, associationWork] = ...
                ProjectionDenseObservationAssociator.associateTracks( ...
                records, observations, options, runtimeControl, started);

            ProjectionDenseObservationAssociator.checkCancelled(runtimeControl);
            ProjectionDenseObservationAssociator.publishProgress( ...
                runtimeControl, 0.95, "finalizeProvenance", 0, 1, started);
            generationPayload = struct(WorldFrame=request.WorldFrame, ...
                Options=options, RecordIds=string({records.RecordId}), ...
                RecordStates=string({records.AssociationState}), ...
                RecordReasons=string({records.AssociationReason}), ...
                TrackIds=string({tracks.TrackId}));
            generationId = "dense-association-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(generationPayload), 17);
            result = struct( ...
                Format=ProjectionDenseObservationAssociator.Format, ...
                Version=ProjectionDenseObservationAssociator.Version, ...
                Status="complete", Stage="denseObservationAssociation", ...
                WorldFrame=request.WorldFrame, GenerationId=generationId, ...
                Options=options, RawPairwiseRecords=records, ...
                Observations=observations, Tracks=tracks, ...
                Diagnostics=ProjectionDenseObservationAssociator.diagnostics( ...
                records, observations, tracks, groupingWork, ...
                associationWork));
            ProjectionDenseObservationAssociator.publishProgress( ...
                runtimeControl, 1, "finalizeProvenance", 1, 1, started);
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            defaults = ProjectionDenseObservationAssociator.defaults();
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "Association options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "Unknown association option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            bounded = ["MinimumTextureScore" ...
                "MinimumNavigationWeight" ...
                "MinimumRadiometricConsistency"];
            for name = bounded
                defaults.(name) = ...
                    ProjectionDenseObservationAssociator.boundedScalar( ...
                    defaults.(name), name);
            end
            positive = ["SourceObservationTolerancePixels" ...
                "RayOriginToleranceMeters" ...
                "RayDirectionToleranceDegrees"];
            for name = positive
                defaults.(name) = ...
                    ProjectionDenseObservationAssociator.positiveScalar( ...
                    defaults.(name), name, false);
            end
            defaults.MinimumPairAngleDegrees = ...
                ProjectionDenseObservationAssociator.boundedAngle( ...
                defaults.MinimumPairAngleDegrees, "MinimumPairAngleDegrees");
            defaults.ModeSeparationMeters = ...
                ProjectionDenseObservationAssociator.positiveScalar( ...
                defaults.ModeSeparationMeters, "ModeSeparationMeters", true);
            options = defaults;
        end

        function request = validateRequest(request)
            if ~isstruct(request) || ~isscalar(request)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Dense pair-observation request must be a scalar struct.");
            end
            allowed = ["Format" "Version" "WorldFrame" "Records"];
            unknown = setdiff(string(fieldnames(request)), allowed);
            if ~isempty(unknown)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Unexpected request field: %s.", unknown(1));
            end
            required = ["WorldFrame" "Records"];
            if any(~isfield(request, required))
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "WorldFrame and Records are required.");
            end
            if ~isfield(request, "Format")
                request.Format = ...
                    ProjectionDenseObservationAssociator.RequestFormat;
            end
            if ~isfield(request, "Version")
                request.Version = ...
                    ProjectionDenseObservationAssociator.RequestVersion;
            end
            request.Format = string(request.Format);
            if ~isscalar(request.Format) || ismissing(request.Format) || ...
                    request.Format ~= ...
                    ProjectionDenseObservationAssociator.RequestFormat || ...
                    ~isequal(request.Version, ...
                    ProjectionDenseObservationAssociator.RequestVersion)
                error("ProjectionDenseObservationAssociator:unsupportedSchema", ...
                    "Dense pair-observation Format and Version must be supported.");
            end
            request.WorldFrame = string(request.WorldFrame);
            if ~isscalar(request.WorldFrame) || ismissing(request.WorldFrame) || ...
                    strlength(request.WorldFrame) == 0
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "WorldFrame must be a nonempty string scalar.");
            end
            if ~isstruct(request.Records)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Records must be a struct array.");
            end
        end

        function records = normalizeRecords( ...
                inputRecords, runtimeControl, started)
            records = repmat( ...
                ProjectionDenseObservationAssociator.emptyRecord(), ...
                1, numel(inputRecords));
            if isempty(inputRecords)
                return
            end
            allowed = string(fieldnames( ...
                ProjectionDenseObservationAssociator.emptyRecord()));
            inputFields = string(fieldnames(inputRecords));
            internal = ["NodeIndices" "PairRayParametersMeters" ...
                "PairRaySeparationMeters" "PairConditionNumber" ...
                "PairAngleDegrees" "PairForwardValid" "AssociationState" ...
                "AssociationReason" "ModeKey" "TrackId"];
            allowedInput = setdiff(allowed, internal);
            unknown = setdiff(inputFields, allowedInput);
            required = ["RecordId" "PairId" "ViewIds" "PassIds" ...
                "ObservationIds" "SourceObservationsPixels" ...
                "RayOriginsWorld" "RayVectorsWorld"];
            if ~isempty(unknown) || any(~isfield(inputRecords, required))
                error("ProjectionDenseObservationAssociator:invalidRecords", ...
                    "Records have missing required or unexpected fields.");
            end
            for index = 1:numel(inputRecords)
                record = ProjectionDenseObservationAssociator.emptyRecord();
                for field = inputFields.'
                    record.(field) = inputRecords(index).(field);
                end
                records(index) = ...
                    ProjectionDenseObservationAssociator.validateRecord(record);
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, index, numel(inputRecords), ...
                    "normalize", 0, 0.15, started);
            end
            keys = string({records.RecordId});
            if numel(unique(keys)) ~= numel(keys)
                error("ProjectionDenseObservationAssociator:duplicateRecordId", ...
                    "Every dense pair record requires a unique RecordId.");
            end
            [~, order] = sort(keys);
            records = records(order);
        end

        function record = validateRecord(record)
            record.RecordId = ProjectionDenseObservationAssociator. ...
                nonemptyString(record.RecordId, "RecordId");
            record.PairId = ProjectionDenseObservationAssociator. ...
                nonemptyString(record.PairId, "PairId");
            record.ViewIds = reshape(string(record.ViewIds), 1, []);
            record.PassIds = reshape(string(record.PassIds), 1, []);
            record.ObservationIds = reshape(string(record.ObservationIds), 1, []);
            identity = [record.ViewIds record.PassIds record.ObservationIds];
            if numel(record.ViewIds) ~= 2 || ...
                    numel(record.PassIds) ~= 2 || ...
                    numel(record.ObservationIds) ~= 2 || ...
                    any(ismissing(identity)) || any(strlength(identity) == 0) || ...
                    record.ViewIds(1) == record.ViewIds(2)
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "Each record requires two distinct views and stable pass/observation IDs.");
            end
            finiteArrays = ["SourceObservationsPixels" ...
                "RayOriginsWorld" "RayVectorsWorld"];
            expectedSizes = {[2 2], [3 2], [3 2]};
            for index = 1:numel(finiteArrays)
                field = finiteArrays(index);
                value = record.(field);
                if ~isnumeric(value) || ...
                        ~isequal(size(value), expectedSizes{index}) || ...
                        any(~isfinite(value), "all")
                    error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                        "%s has invalid size or nonfinite values.", field);
                end
                record.(field) = double(value);
            end
            if any(vecnorm(record.RayVectorsWorld, 2, 1) <= eps)
                error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                    "Ray vectors must be nonzero.");
            end
            record.MatchState = string(record.MatchState);
            supportedStates = ["valid" "noMatch" "occluded" ...
                "ambiguousRepetitive" "insufficientTexture" ...
                "outsideOverlap" "geometrySearchFailure" "masked" ...
                "algorithmFailure"];
            if ~isscalar(record.MatchState) || ...
                    ~ismember(record.MatchState, supportedStates)
                error("ProjectionDenseObservationAssociator:invalidState", ...
                    "MatchState is unsupported.");
            end
            record.VisibilityStates = reshape( ...
                string(record.VisibilityStates), 1, []);
            if numel(record.VisibilityStates) ~= 2 || ...
                    any(~ismember(record.VisibilityStates, ...
                    ["visible" "occluded" "unknown" "unobservable"]))
                error("ProjectionDenseObservationAssociator:invalidVisibility", ...
                    "VisibilityStates must contain two supported states.");
            end
            record.Score = ProjectionDenseObservationAssociator. ...
                finiteOrNanScalar(record.Score, "Score");
            bounded = ["Confidence" "TextureScore" ...
                "RadiometricConsistency"];
            for field = bounded
                record.(field) = ProjectionDenseObservationAssociator. ...
                    boundedScalar(record.(field), field);
            end
            if ~isnumeric(record.NavigationWeights) || ...
                    numel(record.NavigationWeights) ~= 2 || ...
                    any(~isfinite(record.NavigationWeights)) || ...
                    any(record.NavigationWeights < 0 | ...
                    record.NavigationWeights > 1)
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "NavigationWeights must contain two values in [0,1].");
            end
            record.NavigationWeights = ...
                reshape(double(record.NavigationWeights), 1, 2);
            if ~isnumeric(record.RadiometricValues) || ...
                    numel(record.RadiometricValues) ~= 2
                error("ProjectionDenseObservationAssociator:invalidRadiometry", ...
                    "RadiometricValues must contain two numeric values.");
            end
            record.RadiometricValues = ...
                reshape(double(record.RadiometricValues), 1, 2);
            record.ProvisionalPointWorld = ...
                ProjectionDenseObservationAssociator.optionalVector( ...
                record.ProvisionalPointWorld, 3, "ProvisionalPointWorld");
            covariance = record.PairwiseCovarianceWorldMetersSquared;
            if ~isempty(covariance) && (~isnumeric(covariance) || ...
                    ~isequal(size(covariance), [3 3]) || ...
                    any(~isfinite(covariance), "all"))
                error("ProjectionDenseObservationAssociator:invalidCovariance", ...
                    "Pairwise covariance must be empty or finite 3x3.");
            end
            record.PairwiseCovarianceWorldMetersSquared = double(covariance);
            record.ModeId = string(record.ModeId);
            if ~isscalar(record.ModeId) || ismissing(record.ModeId)
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "ModeId must be a string scalar, possibly empty.");
            end
            [point, ranges, separation, condition, angle, valid] = ...
                ProjectionDenseObservationAssociator.triangulate( ...
                record.RayOriginsWorld, record.RayVectorsWorld);
            if isempty(record.ProvisionalPointWorld)
                record.ProvisionalPointWorld = point;
            end
            record.PairRayParametersMeters = ranges;
            record.PairRaySeparationMeters = separation;
            record.PairConditionNumber = condition;
            record.PairAngleDegrees = angle;
            record.PairForwardValid = valid;
        end

        function [observations, records, work] = collectObservations( ...
                records, options, runtimeControl, started)
            observations = ...
                ProjectionDenseObservationAssociator.emptyObservations();
            work = struct(CandidateCount=0, GroupCount=0, ...
                CandidateAssignments=0);
            if isempty(records)
                ProjectionDenseObservationAssociator.publishProgress( ...
                    runtimeControl, 0.35, "groupObservations", 0, 0, started);
                return
            end
            candidateCount = 2 * numel(records);
            candidates = repmat( ...
                ProjectionDenseObservationAssociator.emptyCandidate(), ...
                1, candidateCount);
            cursor = 0;
            for recordIndex = 1:numel(records)
                for side = 1:2
                    cursor = cursor + 1;
                    candidates(cursor) = ...
                        ProjectionDenseObservationAssociator.candidate( ...
                        records(recordIndex), recordIndex, side);
                end
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, recordIndex, numel(records), ...
                    "groupObservations", 0.15, 0.05, started);
            end
            keys = string({candidates.NodeKey});
            [sortedKeys, order] = sort(keys);
            groupStart = find([true sortedKeys(2:end) ~= sortedKeys(1:end - 1)]);
            groupEnd = [groupStart(2:end) - 1 candidateCount];
            groupCount = numel(groupStart);
            observations = repmat( ...
                ProjectionDenseObservationAssociator.emptyObservation(), ...
                1, groupCount);
            for groupIndex = 1:groupCount
                memberIndices = order(groupStart(groupIndex):groupEnd(groupIndex));
                members = candidates(memberIndices);
                observations(groupIndex) = ...
                    ProjectionDenseObservationAssociator.observation( ...
                    members, options);
                for candidateIndex = memberIndices
                    records(candidates(candidateIndex).RecordIndex). ...
                        NodeIndices(candidates(candidateIndex).Side) = ...
                        groupIndex;
                end
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, groupIndex, groupCount, ...
                    "groupObservations", 0.2, 0.15, started);
            end
            work = struct(CandidateCount=candidateCount, ...
                GroupCount=groupCount, CandidateAssignments=candidateCount);
        end

        function candidate = candidate(record, recordIndex, side)
            candidate = ProjectionDenseObservationAssociator.emptyCandidate();
            candidate.NodeKey = record.ViewIds(side) + "|" + ...
                record.ObservationIds(side);
            candidate.RecordIndex = recordIndex;
            candidate.Side = side;
            candidate.RecordId = record.RecordId;
            candidate.PairId = record.PairId;
            candidate.ViewId = record.ViewIds(side);
            candidate.PassId = record.PassIds(side);
            candidate.ObservationId = record.ObservationIds(side);
            candidate.SourceObservationPixels = ...
                record.SourceObservationsPixels(side, :);
            candidate.RayOriginWorld = record.RayOriginsWorld(:, side);
            candidate.RayVectorWorld = record.RayVectorsWorld(:, side);
            candidate.Confidence = record.Confidence;
            candidate.NavigationWeight = record.NavigationWeights(side);
            candidate.RadiometricValue = record.RadiometricValues(side);
            candidate.VisibilityState = record.VisibilityStates(side);
        end

        function observation = observation(members, options)
            viewIds = unique(string({members.ViewId}));
            passIds = unique(string({members.PassId}));
            source = vertcat(members.SourceObservationPixels);
            origins = horzcat(members.RayOriginWorld);
            vectors = horzcat(members.RayVectorWorld);
            unitVectors = vectors ./ vecnorm(vectors, 2, 1);
            meanVector = mean(unitVectors, 2);
            meanVector = meanVector / norm(meanVector);
            angular = acosd(min(1, max(-1, meanVector.' * unitVectors)));
            visibility = unique(string({members.VisibilityState}), "stable");
            consistent = isscalar(viewIds) && isscalar(passIds) && ...
                max(vecnorm(source - mean(source, 1), 2, 2)) <= ...
                options.SourceObservationTolerancePixels && ...
                max(vecnorm(origins - mean(origins, 2), 2, 1)) <= ...
                options.RayOriginToleranceMeters && ...
                max(angular) <= options.RayDirectionToleranceDegrees && ...
                ~all(ismember(["visible" "occluded"], visibility));
            reason = "";
            if ~consistent
                reason = "observationIdentityConflict";
            end
            values = [members.RadiometricValue];
            finiteValues = values(isfinite(values));
            radiometricValue = NaN;
            if ~isempty(finiteValues)
                radiometricValue = median(finiteValues);
            end
            visibilityState = "unknown";
            if isscalar(visibility)
                visibilityState = visibility;
            elseif any(visibility == "occluded")
                visibilityState = "conflicting";
            elseif any(visibility == "visible")
                visibilityState = "visible";
            end
            observation = struct( ...
                ObservationKey=members(1).NodeKey, ...
                ObservationId=members(1).ObservationId, ...
                ViewId=members(1).ViewId, PassId=members(1).PassId, ...
                SourceRowPixels=mean(source(:, 1)), ...
                SourceColumnPixels=mean(source(:, 2)), ...
                RayOriginWorld=mean(origins, 2), ...
                RayVectorWorld=meanVector, ...
                Confidence=max([members.Confidence]), ...
                NavigationWeight=min([members.NavigationWeight]), ...
                RadiometricValue=radiometricValue, ...
                VisibilityState=visibilityState, ...
                Consistent=consistent, ConflictReason=reason, ...
                OccurrenceCount=numel(members), ...
                RecordIds=sort(unique(string({members.RecordId}))), ...
                PairIds=sort(unique(string({members.PairId}))));
        end

        function records = precheckRecords( ...
                records, observations, options, runtimeControl, started)
            for index = 1:numel(records)
                record = records(index);
                reason = "";
                if record.MatchState ~= "valid"
                    reason = "matchState:" + record.MatchState;
                elseif any(~[observations(record.NodeIndices).Consistent])
                    reason = "observationIdentityConflict";
                elseif ~record.PairForwardValid
                    reason = "pairForwardInvalid";
                elseif record.PairAngleDegrees < options.MinimumPairAngleDegrees
                    reason = "nearlyParallel";
                elseif record.TextureScore < options.MinimumTextureScore
                    reason = "insufficientTexture";
                elseif min(record.NavigationWeights) < ...
                        options.MinimumNavigationWeight
                    reason = "weakNavigation";
                elseif record.RadiometricConsistency < ...
                        options.MinimumRadiometricConsistency
                    reason = "radiometricInconsistent";
                elseif any(record.VisibilityStates == "occluded")
                    reason = "visibilityConflict";
                end
                if strlength(reason) > 0
                    records(index).AssociationState = "rejected";
                    records(index).AssociationReason = reason;
                end
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, index, numel(records), ...
                    "precheckRecords", 0.35, 0.1, started);
            end
        end

        function [records, tracks, work] = associateTracks( ...
                records, observations, options, runtimeControl, started)
            tracks = ProjectionDenseObservationAssociator.emptyTracks();
            work = struct(EligibleEdgeCount=0, ComponentCount=0, ...
                ReconciledEdgeCount=0, TrackFinalizationCount=0, ...
                BaseDisjointSet=struct(), ReconcileFindCalls=0, ...
                ReconcileFindSteps=0, ReconcileJoinCalls=0);
            eligible = find(string({records.AssociationState}) == "candidate");
            if isempty(eligible)
                ProjectionDenseObservationAssociator.publishProgress( ...
                    runtimeControl, 0.9, "reconcileTracks", 0, 0, started);
                return
            end
            baseSet = ProjectionDisjointSet(numel(observations));
            for eligibleIndex = 1:numel(eligible)
                edgeIndex = eligible(eligibleIndex);
                nodes = records(edgeIndex).NodeIndices;
                baseSet.join(nodes(1), nodes(2));
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, eligibleIndex, numel(eligible), ...
                    "unionComponents", 0.45, 0.15, started);
            end
            edgeRoots = zeros(1, numel(eligible));
            for eligibleIndex = 1:numel(eligible)
                edgeRoots(eligibleIndex) = baseSet.find( ...
                    records(eligible(eligibleIndex)).NodeIndices(1));
            end
            [sortedRoots, rootOrder] = sort(edgeRoots);
            componentStart = find([true ...
                sortedRoots(2:end) ~= sortedRoots(1:end - 1)]);
            componentEnd = [componentStart(2:end) - 1 numel(eligible)];
            componentCount = numel(componentStart);
            trackBuffer = repmat( ...
                ProjectionDenseObservationAssociator.emptyTrack(), ...
                1, numel(eligible));
            trackCursor = 0;
            reconciledBefore = 0;
            reconcileWork = struct(FindCalls=0, FindSteps=0, JoinCalls=0);
            for componentIndex = 1:componentCount
                edgeIndices = eligible(rootOrder( ...
                    componentStart(componentIndex):componentEnd(componentIndex)));
                modeGroups = ProjectionDenseObservationAssociator.modeGroups( ...
                    records, edgeIndices, options.ModeSeparationMeters);
                competing = numel(modeGroups) > 1;
                modeProcessedBefore = 0;
                for modeIndex = 1:numel(modeGroups)
                    modeEdges = modeGroups(modeIndex).EdgeIndices;
                    [records, modeTracks, modeWork] = ...
                        ProjectionDenseObservationAssociator.reconcileMode( ...
                        records, observations, modeEdges, ...
                        modeGroups(modeIndex).ModeKey, competing, ...
                        runtimeControl, started, ...
                        reconciledBefore + modeProcessedBefore, ...
                        numel(eligible));
                    count = numel(modeTracks);
                    if count > 0
                        trackBuffer(trackCursor + (1:count)) = modeTracks;
                        trackCursor = trackCursor + count;
                    end
                    reconcileWork.FindCalls = reconcileWork.FindCalls + ...
                        modeWork.FindCalls;
                    reconcileWork.FindSteps = reconcileWork.FindSteps + ...
                        modeWork.FindSteps;
                    reconcileWork.JoinCalls = reconcileWork.JoinCalls + ...
                        modeWork.JoinCalls;
                    modeProcessedBefore = modeProcessedBefore + numel(modeEdges);
                end
                reconciledBefore = reconciledBefore + numel(edgeIndices);
            end
            tracks = trackBuffer(1:trackCursor);
            if ~isempty(tracks)
                [~, order] = sort(string({tracks.TrackId}));
                tracks = tracks(order);
            end
            baseWork = baseSet.diagnostics();
            work = struct(EligibleEdgeCount=numel(eligible), ...
                ComponentCount=componentCount, ...
                ReconciledEdgeCount=reconciledBefore, ...
                TrackFinalizationCount=numel(tracks), ...
                BaseDisjointSet=baseWork, ...
                ReconcileFindCalls=reconcileWork.FindCalls, ...
                ReconcileFindSteps=reconcileWork.FindSteps, ...
                ReconcileJoinCalls=reconcileWork.JoinCalls);
        end

        function groups = modeGroups(records, edgeIndices, separation)
            groupTemplate = struct(ModeKey="", EdgeIndices=zeros(1, 0));
            buffer = repmat(groupTemplate, 1, max(1, numel(edgeIndices)));
            cursor = 0;
            explicit = string({records(edgeIndices).ModeId});
            explicitIds = sort(unique(explicit(strlength(explicit) > 0)));
            for modeId = explicitIds
                cursor = cursor + 1;
                buffer(cursor) = struct( ...
                    ModeKey="hint:" + modeId, ...
                    EdgeIndices=edgeIndices(explicit == modeId));
            end
            autoEdges = edgeIndices(strlength(explicit) == 0);
            if isempty(autoEdges)
                groups = buffer(1:cursor);
                return
            end
            if isinf(separation)
                cursor = cursor + 1;
                buffer(cursor) = struct( ...
                    ModeKey="auto:1", EdgeIndices=autoEdges);
                groups = buffer(1:cursor);
                return
            end
            points = horzcat(records(autoEdges).ProvisionalPointWorld).';
            keys = string({records(autoEdges).RecordId}).';
            orderTable = table(points(:, 1), points(:, 2), points(:, 3), ...
                keys, (1:numel(autoEdges)).', VariableNames= ...
                ["X" "Y" "Z" "RecordId" "LocalIndex"]);
            orderTable = sortrows(orderTable, ["X" "Y" "Z" "RecordId"]);
            centers = zeros(0, 3);
            members = cell(1, 0);
            for orderIndex = 1:height(orderTable)
                localIndex = orderTable.LocalIndex(orderIndex);
                point = points(localIndex, :);
                distances = vecnorm(centers - point, 2, 2);
                [distance, cluster] = min(distances);
                if isempty(cluster) || distance > separation
                    centers(end + 1, :) = point; %#ok<AGROW>
                    members{end + 1} = localIndex; %#ok<AGROW>
                else
                    members{cluster}(end + 1) = localIndex;
                    centers(cluster, :) = mean(points(members{cluster}, :), 1);
                end
            end
            for cluster = 1:numel(members)
                cursor = cursor + 1;
                buffer(cursor) = struct( ...
                    ModeKey="auto:" + cluster, ...
                    EdgeIndices=autoEdges(members{cluster}));
            end
            groups = buffer(1:cursor);
        end

        function [records, tracks, work] = reconcileMode( ...
                records, observations, edgeIndices, modeKey, competing, ...
                runtimeControl, started, processedBefore, totalEdges)
            tracks = ProjectionDenseObservationAssociator.emptyTracks();
            edgeIndices = reshape(edgeIndices, [], 1);
            quality = reshape([records(edgeIndices).Confidence], [], 1) .* ...
                reshape([records(edgeIndices).TextureScore], [], 1) .* ...
                reshape([records(edgeIndices).RadiometricConsistency], [], 1) .* ...
                reshape(arrayfun(@(record) min(record.NavigationWeights), ...
                records(edgeIndices)), [], 1);
            pairIds = reshape(string({records(edgeIndices).PairId}), [], 1);
            recordIds = reshape(string({records(edgeIndices).RecordId}), [], 1);
            localIndices = (1:numel(edgeIndices)).';
            ordering = table(-quality, pairIds, recordIds, edgeIndices, ...
                localIndices, VariableNames=["NegativeQuality" "PairId" ...
                "RecordId" "EdgeIndex" "LocalIndex"]);
            ordering = sortrows(ordering, ...
                ["NegativeQuality" "PairId" "RecordId"]);
            globalNodes = sort(unique([records(edgeIndices).NodeIndices]));
            [~, localEdgeNodes] = ismember( ...
                vertcat(records(edgeIndices).NodeIndices), globalNodes);
            viewIds = string({observations(globalNodes).ViewId});
            [~, ~, viewOrdinals] = unique(viewIds, "sorted");
            viewMembership = cell(1, numel(globalNodes));
            for nodeIndex = 1:numel(globalNodes)
                viewMembership{nodeIndex} = viewOrdinals(nodeIndex);
            end
            set = ProjectionDisjointSet(numel(globalNodes));
            for orderIndex = 1:height(ordering)
                edgeIndex = ordering.EdgeIndex(orderIndex);
                localIndex = ordering.LocalIndex(orderIndex);
                nodes = localEdgeNodes(localIndex, :);
                firstRoot = set.find(nodes(1));
                secondRoot = set.find(nodes(2));
                if firstRoot ~= secondRoot
                    if any(ismember(viewMembership{firstRoot}, ...
                            viewMembership{secondRoot}))
                        records(edgeIndex).AssociationState = "rejected";
                        records(edgeIndex).AssociationReason = ...
                            "duplicateViewConflict";
                        ProjectionDenseObservationAssociator.checkpoint( ...
                            runtimeControl, processedBefore + orderIndex, ...
                            totalEdges, "reconcileTracks", 0.6, 0.3, started);
                        continue
                    end
                    combinedViews = [viewMembership{firstRoot} ...
                        viewMembership{secondRoot}];
                    [newRoot, ~, retiredRoot] = set.join( ...
                        firstRoot, secondRoot);
                    viewMembership{newRoot} = combinedViews;
                    viewMembership{retiredRoot} = zeros(1, 0);
                end
                records(edgeIndex).AssociationState = "accepted";
                records(edgeIndex).AssociationReason = "";
                records(edgeIndex).ModeKey = modeKey;
                ProjectionDenseObservationAssociator.checkpoint( ...
                    runtimeControl, processedBefore + orderIndex, totalEdges, ...
                    "reconcileTracks", 0.6, 0.3, started);
            end
            acceptedEdges = edgeIndices(string( ...
                {records(edgeIndices).AssociationState}) == "accepted");
            if isempty(acceptedEdges)
                work = set.diagnostics();
                return
            end
            [~, acceptedLocalRows] = ismember(acceptedEdges, edgeIndices);
            acceptedLocalNodes = localEdgeNodes(acceptedLocalRows, :);
            acceptedRoots = zeros(1, numel(acceptedEdges));
            for acceptedIndex = 1:numel(acceptedEdges)
                acceptedRoots(acceptedIndex) = ...
                    set.find(acceptedLocalNodes(acceptedIndex, 1));
            end
            [sortedRoots, rootOrder] = sort(acceptedRoots);
            trackStart = find([true ...
                sortedRoots(2:end) ~= sortedRoots(1:end - 1)]);
            trackEnd = [trackStart(2:end) - 1 numel(acceptedEdges)];
            tracks = repmat(ProjectionDenseObservationAssociator.emptyTrack(), ...
                1, numel(trackStart));
            for trackIndex = 1:numel(trackStart)
                ProjectionDenseObservationAssociator.checkCancelled( ...
                    runtimeControl);
                span = rootOrder(trackStart(trackIndex):trackEnd(trackIndex));
                modeRecordIndices = reshape(acceptedEdges(span), 1, []);
                nodeIndices = sort(unique([records( ...
                    modeRecordIndices).NodeIndices]));
                viewIds = string({observations(nodeIndices).ViewId});
                [~, order] = sort(viewIds);
                nodeIndices = nodeIndices(order);
                observationKeys = string( ...
                    {observations(nodeIndices).ObservationKey});
                observationIds = string( ...
                    {observations(nodeIndices).ObservationId});
                recordIds = sort(string({records(modeRecordIndices).RecordId}));
                pairIds = sort(unique(string( ...
                    {records(modeRecordIndices).PairId})));
                trackPayload = struct(ModeKey=modeKey, ...
                    ObservationKeys=observationKeys, RecordIds=recordIds);
                trackId = "dense-track-" + extractBefore( ...
                    ProjectionGeometryFingerprint.hash(trackPayload), 17);
                for recordIndex = 1:numel(modeRecordIndices)
                    edgeIndex = modeRecordIndices(recordIndex);
                    records(edgeIndex).TrackId = trackId;
                end
                tracks(trackIndex) = struct( ...
                    TrackId=trackId, ModeId=modeKey, ...
                    CompetingMode=competing, ...
                    ObservationIndices=nodeIndices, ...
                    ObservationKeys=observationKeys, ...
                    ObservationIds=observationIds, ...
                    ViewIds=string({observations(nodeIndices).ViewId}), ...
                    PassIds=string({observations(nodeIndices).PassId}), ...
                    RecordIds=recordIds, PairIds=pairIds, ...
                    ViewCount=numel(nodeIndices), ...
                    IndependentPassCount=numel(unique(string( ...
                    {observations(nodeIndices).PassId}))), ...
                    PairRecordCount=numel(modeRecordIndices), ...
                    State="associated");
            end
            work = set.diagnostics();
        end

        function value = diagnostics(records, observations, tracks, ...
                groupingWork, associationWork)
            states = string({records.AssociationState});
            reasons = string({records.AssociationReason});
            baseWork = associationWork.BaseDisjointSet;
            if isempty(fieldnames(baseWork))
                baseWork = struct(FindCalls=0, FindSteps=0, JoinCalls=0);
            end
            stageWork = struct(NormalizedRecordCount=numel(records), ...
                ObservationCandidateCount=groupingWork.CandidateCount, ...
                ObservationGroupCount=groupingWork.GroupCount, ...
                CandidateAssignmentCount=groupingWork.CandidateAssignments, ...
                PrecheckedRecordCount=numel(records), ...
                EligibleEdgeCount=associationWork.EligibleEdgeCount, ...
                ComponentCount=associationWork.ComponentCount, ...
                ReconciledEdgeCount=associationWork.ReconciledEdgeCount, ...
                TrackFinalizationCount= ...
                associationWork.TrackFinalizationCount, ...
                DisjointSetFindCalls=baseWork.FindCalls + ...
                associationWork.ReconcileFindCalls, ...
                DisjointSetFindSteps=baseWork.FindSteps + ...
                associationWork.ReconcileFindSteps, ...
                DisjointSetJoinCalls=baseWork.JoinCalls + ...
                associationWork.ReconcileJoinCalls);
            numericWork = cell2mat(struct2cell(stageWork));
            value = struct(InputPairRecordCount=numel(records), ...
                ObservationCount=numel(observations), ...
                ConsistentObservationCount=nnz([observations.Consistent]), ...
                TrackCount=numel(tracks), ...
                AcceptedPairRecordCount=nnz(states == "accepted"), ...
                RejectedPairRecordCount=nnz(states == "rejected"), ...
                DuplicateViewConflictCount=nnz( ...
                reasons == "duplicateViewConflict"), ...
                CompetingModeTrackCount=nnz([tracks.CompetingMode]), ...
                TwoViewTrackCount=nnz([tracks.ViewCount] == 2), ...
                StageWorkCounts=stageWork, ...
                TotalIndexedWorkCount=sum(numericWork), ...
                DenseRecordObservationMatrixAllocated=false);
        end

        function runtime = validateRuntimeControl(runtime)
            defaults = struct(ProgressFcn=[], CancellationFcn=[], ...
                ChunkSize=256);
            if isempty(runtime)
                runtime = defaults;
                return
            end
            if ~isstruct(runtime) || ~isscalar(runtime) || ...
                    any(~ismember(string(fieldnames(runtime)), ...
                    string(fieldnames(defaults))))
                error("ProjectionDenseObservationAssociator:invalidRuntimeControl", ...
                    "Runtime control supports progress, cancellation, and chunk size.");
            end
            names = fieldnames(runtime);
            for index = 1:numel(names)
                defaults.(names{index}) = runtime.(names{index});
            end
            for field = ["ProgressFcn" "CancellationFcn"]
                if ~(isempty(defaults.(field)) || ...
                        isa(defaults.(field), "function_handle"))
                    error("ProjectionDenseObservationAssociator:invalidRuntimeControl", ...
                        "%s must be empty or a function handle.", field);
                end
            end
            if ~isnumeric(defaults.ChunkSize) || ...
                    ~isscalar(defaults.ChunkSize) || ...
                    ~isfinite(defaults.ChunkSize) || ...
                    defaults.ChunkSize < 1 || fix(defaults.ChunkSize) ~= ...
                    defaults.ChunkSize
                error("ProjectionDenseObservationAssociator:invalidRuntimeControl", ...
                    "ChunkSize must be a positive integer.");
            end
            defaults.ChunkSize = double(defaults.ChunkSize);
            runtime = defaults;
        end

        function checkpoint(runtime, completed, total, stage, ...
                fractionBase, fractionSpan, started)
            if completed == total || mod(completed, runtime.ChunkSize) == 0
                ProjectionDenseObservationAssociator.checkCancelled(runtime);
                fraction = fractionBase + fractionSpan * ...
                    double(completed) / max(double(total), 1);
                ProjectionDenseObservationAssociator.publishProgress( ...
                    runtime, fraction, stage, completed, total, started);
            end
        end

        function checkCancelled(runtime)
            if isempty(runtime.CancellationFcn)
                return
            end
            cancelled = runtime.CancellationFcn();
            if ~islogical(cancelled) || ~isscalar(cancelled)
                error("ProjectionDenseObservationAssociator:invalidRuntimeControl", ...
                    "CancellationFcn must return a logical scalar.");
            end
            if cancelled
                error("ProjectionDenseObservationAssociator:cancelled", ...
                    "Dense observation association was cancelled cooperatively.");
            end
        end

        function publishProgress(runtime, fraction, stage, completed, ...
                total, started)
            if isempty(runtime.ProgressFcn)
                return
            end
            elapsed = toc(started);
            runtime.ProgressFcn(struct(Fraction=double(fraction), ...
                Stage=string(stage), Completed=double(completed), ...
                Total=double(total), ElapsedSeconds=elapsed, ...
                Message=sprintf("%s: %d/%d (%.2f s)", stage, ...
                completed, total, elapsed)));
        end

        function [point, ranges, separation, condition, angle, valid] = ...
                triangulate(origins, vectors)
            directions = vectors ./ vecnorm(vectors, 2, 1);
            matrix = [directions(:, 1) -directions(:, 2)];
            singularValues = svd(matrix, "econ");
            condition = singularValues(1) / max(singularValues(end), eps);
            ranges = matrix \ (origins(:, 2) - origins(:, 1));
            firstPoint = origins(:, 1) + directions(:, 1) * ranges(1);
            secondPoint = origins(:, 2) + directions(:, 2) * ranges(2);
            point = 0.5 * (firstPoint + secondPoint);
            separation = norm(firstPoint - secondPoint);
            angle = acosd(min(1, max(-1, abs(dot( ...
                directions(:, 1), directions(:, 2))))));
            valid = all(isfinite(point)) && all(ranges > 0) && ...
                singularValues(end) > 1e-10;
            if ~valid
                point(:) = NaN;
            end
        end

        function value = nonemptyString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || ...
                    strlength(strip(value)) == 0
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "%s must be a nonempty string scalar.", name);
            end
            value = strip(value);
        end

        function value = boundedScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 0 || value > 1
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "%s must be a finite scalar in [0,1].", name);
            end
            value = double(value);
        end

        function value = finiteOrNanScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~(isfinite(value) || isnan(value))
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "%s must be a finite scalar or NaN.", name);
            end
            value = double(value);
        end

        function value = positiveScalar(value, name, allowInf)
            if ~isnumeric(value) || ~isscalar(value) || isnan(value) || ...
                    value <= 0 || (~allowInf && ~isfinite(value))
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "%s must be a positive scalar%s.", name, ...
                    ProjectionDenseObservationAssociator.infSuffix(allowInf));
            end
            value = double(value);
        end

        function value = boundedAngle(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 0 || value >= 90
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "%s must be in [0,90) degrees.", name);
            end
            value = double(value);
        end

        function suffix = infSuffix(allowInf)
            suffix = "";
            if allowInf
                suffix = " or Inf";
            end
        end

        function value = optionalVector(value, count, name)
            if isempty(value)
                value = zeros(count, 0);
                return
            end
            if ~isnumeric(value) || numel(value) ~= count || ...
                    any(~isfinite(value))
                error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                    "%s must be empty or a finite %d-vector.", name, count);
            end
            value = reshape(double(value), count, 1);
        end

        function record = emptyRecord()
            record = struct(RecordId="", PairId="", ...
                ViewIds=strings(1, 2), PassIds=strings(1, 2), ...
                ObservationIds=strings(1, 2), ...
                SourceObservationsPixels=nan(2), ...
                RayOriginsWorld=nan(3, 2), RayVectorsWorld=nan(3, 2), ...
                MatchState="valid", Score=NaN, Confidence=1, ...
                TextureScore=1, NavigationWeights=ones(1, 2), ...
                RadiometricValues=nan(1, 2), ...
                RadiometricConsistency=1, ...
                VisibilityStates=["visible" "visible"], ...
                ProvisionalPointWorld=zeros(3, 0), ...
                PairwiseCovarianceWorldMetersSquared=[], ModeId="", ...
                NodeIndices=zeros(1, 2), ...
                PairRayParametersMeters=nan(2, 1), ...
                PairRaySeparationMeters=Inf, PairConditionNumber=Inf, ...
                PairAngleDegrees=NaN, PairForwardValid=false, ...
                AssociationState="candidate", AssociationReason="", ...
                ModeKey="", TrackId="");
        end

        function candidate = emptyCandidate()
            candidate = struct(NodeKey="", RecordIndex=0, Side=0, ...
                RecordId="", PairId="", ViewId="", PassId="", ...
                ObservationId="", SourceObservationPixels=nan(1, 2), ...
                RayOriginWorld=nan(3, 1), RayVectorWorld=nan(3, 1), ...
                Confidence=0, NavigationWeight=0, RadiometricValue=NaN, ...
                VisibilityState="unknown");
        end

        function observation = emptyObservation()
            observation = struct(ObservationKey="", ObservationId="", ...
                ViewId="", PassId="", SourceRowPixels=NaN, ...
                SourceColumnPixels=NaN, RayOriginWorld=nan(3, 1), ...
                RayVectorWorld=nan(3, 1), Confidence=0, ...
                NavigationWeight=0, RadiometricValue=NaN, ...
                VisibilityState="unknown", Consistent=false, ...
                ConflictReason="", OccurrenceCount=0, ...
                RecordIds=strings(1, 0), PairIds=strings(1, 0));
        end

        function observations = emptyObservations()
            observations = struct("ObservationKey", {}, ...
                "ObservationId", {}, "ViewId", {}, ...
                "PassId", {}, "SourceRowPixels", {}, ...
                "SourceColumnPixels", {}, "RayOriginWorld", {}, ...
                "RayVectorWorld", {}, "Confidence", {}, ...
                "NavigationWeight", {}, "RadiometricValue", {}, ...
                "VisibilityState", {}, "Consistent", {}, ...
                "ConflictReason", {}, "OccurrenceCount", {}, ...
                "RecordIds", {}, "PairIds", {});
        end

        function tracks = emptyTracks()
            tracks = struct("TrackId", {}, "ModeId", {}, ...
                "CompetingMode", {}, "ObservationIndices", {}, ...
                "ObservationKeys", {}, "ObservationIds", {}, ...
                "ViewIds", {}, "PassIds", {}, ...
                "RecordIds", {}, "PairIds", {}, "ViewCount", {}, ...
                "IndependentPassCount", {}, "PairRecordCount", {}, ...
                "State", {});
        end

        function track = emptyTrack()
            track = struct(TrackId="", ModeId="", CompetingMode=false, ...
                ObservationIndices=zeros(1, 0), ...
                ObservationKeys=strings(1, 0), ...
                ObservationIds=strings(1, 0), ViewIds=strings(1, 0), ...
                PassIds=strings(1, 0), RecordIds=strings(1, 0), ...
                PairIds=strings(1, 0), ViewCount=0, ...
                IndependentPassCount=0, PairRecordCount=0, State="");
        end
    end
end
