classdef ProjectionAlignmentSyntheticAcceptance
    %ProjectionAlignmentSyntheticAcceptance Run multi-image truth evidence.

    properties (Constant)
        Format = "ProjectionAlignmentSyntheticAcceptance"
        Version = 1
    end

    methods (Static)
        function report = run(options)
            %run Execute the deterministic multi-image acceptance matrix.
            if nargin < 1
                options = struct();
            end
            options = ProjectionAlignmentSyntheticAcceptance.validateOptions( ...
                options);
            scenarios = ProjectionAlignmentSyntheticAcceptance.scenarios(options);
            records = repmat( ...
                ProjectionAlignmentSyntheticAcceptance.emptyRecord(), ...
                1, numel(scenarios));
            timer = tic;
            for index = 1:numel(scenarios)
                records(index) = ...
                    ProjectionAlignmentSyntheticAcceptance.runScenario( ...
                    scenarios(index), options);
            end
            report = struct( ...
                Format=ProjectionAlignmentSyntheticAcceptance.Format, ...
                Version=ProjectionAlignmentSyntheticAcceptance.Version, ...
                Status=ProjectionAlignmentSyntheticAcceptance.status(records), ...
                ThresholdsEstablished=false, ...
                OrdinaryPipelineStages=["pairGraph" "matchLedger" ...
                "trackBuilder" "networkSolver"], ...
                ScenarioCount=numel(records), Runs=records, ...
                Coverage=ProjectionAlignmentSyntheticAcceptance.coverage(records), ...
                RuntimeSeconds=toc(timer), ...
                Repeatability=struct(Status="not-checked", Exact=false, ...
                FirstRunRuntimeSeconds=NaN, SecondRunRuntimeSeconds=NaN));
        end

        function report = runRepeatable(options)
            %runRepeatable Execute twice and report exact deterministic agreement.
            if nargin < 1
                options = struct();
            end
            first = ProjectionAlignmentSyntheticAcceptance.run(options);
            second = ProjectionAlignmentSyntheticAcceptance.run(options);
            firstComparable = first;
            secondComparable = second;
            firstComparable.RuntimeSeconds = 0;
            secondComparable.RuntimeSeconds = 0;
            firstComparable.Repeatability = struct();
            secondComparable.Repeatability = struct();
            for index = 1:numel(firstComparable.Runs)
                firstComparable.Runs(index).RuntimeSeconds = 0;
                secondComparable.Runs(index).RuntimeSeconds = 0;
            end
            exact = isequaln(firstComparable, secondComparable);
            repeatabilityStatus = "mismatch";
            if exact
                repeatabilityStatus = "verified";
            end
            report = first;
            report.Repeatability = struct(Status=repeatabilityStatus, ...
                Exact=exact, FirstRunRuntimeSeconds=first.RuntimeSeconds, ...
                SecondRunRuntimeSeconds=second.RuntimeSeconds);
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "Options must be a scalar struct.");
            end
            defaults = struct(ScenarioNames=strings(1, 0), ...
                FeatureCount=12, ImageSize=[24 24], ...
                ComputeLeaveOnePairOut=false);
            names = fieldnames(options);
            unknown = setdiff(string(names), string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "Unknown option: %s.", unknown(1));
            end
            for index = 1:numel(names)
                defaults.(names{index}) = options.(names{index});
            end
            defaults.ScenarioNames = reshape(string( ...
                defaults.ScenarioNames), 1, []);
            if any(ismissing(defaults.ScenarioNames)) || ...
                    any(strlength(defaults.ScenarioNames) == 0)
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "ScenarioNames must contain nonempty strings.");
            end
            ProjectionAlignmentSyntheticAcceptance.validatePositiveInteger( ...
                defaults.FeatureCount, "FeatureCount", 6);
            if ~isnumeric(defaults.ImageSize) || ...
                    ~isequal(size(defaults.ImageSize), [1 2]) || ...
                    any(~isfinite(defaults.ImageSize)) || ...
                    any(fix(defaults.ImageSize) ~= defaults.ImageSize) || ...
                    any(defaults.ImageSize < 12)
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "ImageSize must be a 1x2 integer array with values at least 12.");
            end
            if ~(islogical(defaults.ComputeLeaveOnePairOut) && ...
                    isscalar(defaults.ComputeLeaveOnePairOut))
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "ComputeLeaveOnePairOut must be a logical scalar.");
            end
            options = defaults;
        end

        function validatePositiveInteger(value, name, minimum)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    fix(value) ~= value || value < minimum
                error("ProjectionAlignmentSyntheticAcceptance:invalidOptions", ...
                    "%s must be an integer greater than or equal to %d.", ...
                    name, minimum);
            end
        end

        function scenarios = scenarios(options)
            definitions = [ ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "two-view-balanced", 2, "balanced", "singlePass", false, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "three-view-all-pairs", 3, "allPlausible", "singlePass", false, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "four-view-quality-multipass", 4, "quality", "multiplePasses", false, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "six-view-balanced-multipass", 6, "balanced", "multiplePasses", false, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "four-view-fast-graph", 4, "fast", "singlePass", false, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "four-view-corrupted-edge", 4, "allPlausible", "multiplePasses", true, false), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "six-view-evidence-exclusions", 6, "quality", "multiplePasses", false, true), ...
                ProjectionAlignmentSyntheticAcceptance.scenario( ...
                "six-view-uncertainty", 6, "allPlausible", "multiplePasses", false, false)];
            if isempty(options.ScenarioNames)
                scenarios = definitions;
                return
            end
            available = string({definitions.Name});
            unknown = setdiff(options.ScenarioNames, available);
            if ~isempty(unknown)
                error("ProjectionAlignmentSyntheticAcceptance:unknownScenario", ...
                    "Unknown synthetic acceptance scenario: %s.", unknown(1));
            end
            scenarios = definitions(ismember(available, options.ScenarioNames));
        end

        function value = scenario(name, viewCount, graphVariant, ...
                configuration, corruptEdge, excludeEvidence)
            value = struct(Name=name, ViewCount=viewCount, ...
                GraphVariant=graphVariant, Configuration=configuration, ...
                CorruptEdge=corruptEdge, ExcludeEvidence=excludeEvidence);
        end

        function record = runScenario(scenario, options)
            timer = tic;
            try
                [scene, truth] = ...
                    ProjectionAlignmentSyntheticAcceptance.makeScene( ...
                    scenario, options);
                schedule = ProjectionAlignmentSyntheticAcceptance.schedule( ...
                    scene, scenario);
                [matched, evidenceClasses, corruptedPairId] = ...
                    ProjectionAlignmentSyntheticAcceptance.makeMatches( ...
                    scene, schedule, scenario, options);
                filtered = ProjectionAlignmentMatchFilter.filter( ...
                    matched, struct(FilterPipeline=struct(Stages="overlapMask")));
                solveOptions = ...
                    ProjectionAlignmentSyntheticAcceptance.solveOptions( ...
                    scenario, options);
                result = ProjectionAlignmentNetworkSolver.solve( ...
                    scene, filtered, solveOptions);
                record = ProjectionAlignmentSyntheticAcceptance.summarize( ...
                    scenario, schedule, result, truth, evidenceClasses, ...
                    corruptedPairId);
                record.RuntimeSeconds = toc(timer);
            catch exception
                record = ProjectionAlignmentSyntheticAcceptance.emptyRecord();
                record.Name = scenario.Name;
                record.ViewCount = scenario.ViewCount;
                record.GraphVariant = scenario.GraphVariant;
                record.Configuration = scenario.Configuration;
                record.Status = "failed";
                record.FailureIdentifier = string(exception.identifier);
                record.FailureMessage = string(exception.message);
                record.RuntimeSeconds = toc(timer);
            end
        end

        function [scene, truth] = makeScene(scenario, options)
            imageSize = options.ImageSize;
            imageData = reshape(1:prod(imageSize), imageSize);
            imageCells = repmat({imageData}, 1, scenario.ViewCount);
            paths = "synthetic-network-view-" + ...
                compose("%02d", 1:scenario.ViewCount) + ".tif";
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                imageCells, paths, struct(RowStride=1, ColumnStride=1, ...
                GSD=0.5, PlatformStepMeters=0.75));
            injected = ...
                ProjectionAlignmentSyntheticAcceptance.injectedOffsets( ...
                scenario.ViewCount, scenario.Configuration);
            for index = 1:scenario.ViewCount
                scene.layers(index).LayerId = ...
                    "synthetic-network-layer-" + compose("%02d", index);
                scene.layers(index).ViewId = ...
                    "synthetic-network-view-" + compose("%02d", index);
                scene.layers(index).ViewVectorAngularOffsetsDegrees = ...
                    injected(index, :).';
                if scenario.Configuration == "multiplePasses"
                    if index <= ceil(scenario.ViewCount / 2)
                        scene.layers(index).PassId = "pass-a";
                    else
                        scene.layers(index).PassId = "pass-b";
                    end
                else
                    scene.layers(index).PassId = "pass-a";
                end
            end
            scene = ProjectionViewMetadata.ensureScene(scene);
            truth = struct(TruthOffsetsDegrees=zeros(scenario.ViewCount, 3), ...
                InjectedOffsetsDegrees=injected, ...
                GeometryRole="reported-input-with-held-out-zero-OPK-truth", ...
                TruthEnteredSolver=false);
        end

        function offsets = injectedOffsets(viewCount, configuration)
            phase = (0:(viewCount - 1)).';
            offsets = [0.18 * sin(2 * pi * phase / max(3, viewCount)), ...
                0.14 * cos(2 * pi * phase / max(3, viewCount)), ...
                0.10 * sin(pi / 4 + 2 * pi * phase / max(3, viewCount))];
            offsets = offsets - mean(offsets, 1);
            if configuration == "multiplePasses"
                split = ceil(viewCount / 2);
                offsets(1:split, :) = offsets(1:split, :) + ...
                    [0.05 -0.03 0.02];
                offsets((split + 1):end, :) = ...
                    offsets((split + 1):end, :) + [-0.04 0.025 -0.015];
            end
        end

        function schedule = schedule(scene, scenario)
            scheduling = struct(QualitySpeed=scenario.GraphVariant);
            if scenario.GraphVariant == "allPlausible"
                scheduling = struct(AllPlausiblePairs=true);
            end
            schedule = ProjectionAlignmentScheduler.build(scene, ...
                struct(Options=struct(Scheduling=scheduling)));
        end

        function [result, classes, corruptedPairId] = makeMatches( ...
                scene, schedule, scenario, options)
            [rows, columns] = ...
                ProjectionAlignmentSyntheticAcceptance.featureLocations( ...
                options.ImageSize, options.FeatureCount);
            classes = repmat("visibleTerrain", numel(rows), 1);
            if scenario.ExcludeEvidence
                classes(1) = "occludedTerrain";
                classes(2) = "textureCoverageFailure";
                classes(3) = "masked";
                classes(4) = "invalidGeometry";
            end
            accepted = classes == "visibleTerrain";
            acceptedRows = rows(accepted);
            acceptedColumns = columns(accepted);
            corruptedPairId = "";
            if scenario.CorruptEdge
                corruptedPairId = schedule.Pairs(end).PairId;
            end
            matches = struct([]);
            for pairIndex = 1:numel(schedule.Pairs)
                pair = schedule.Pairs(pairIndex);
                referenceRows = acceptedRows;
                referenceColumns = acceptedColumns;
                if pair.PairId == corruptedPairId && ...
                        numel(referenceRows) >= 2
                    referenceRows([1 2]) = referenceRows([2 1]);
                    referenceColumns([1 2]) = referenceColumns([2 1]);
                end
                value = ProjectionAlignmentSyntheticAcceptance.pairMatch( ...
                    scene, pair, acceptedRows, acceptedColumns, ...
                    referenceRows, referenceColumns, options.ImageSize, ...
                    pairIndex);
                if isempty(matches)
                    matches = value;
                else
                    matches(end + 1) = value; %#ok<AGROW>
                end
            end
            result = struct(Matches=matches, Diagnostics=struct(), ...
                Schedule=schedule);
        end

        function [rows, columns] = featureLocations(imageSize, count)
            side = ceil(sqrt(count));
            rowGrid = round(linspace(3, imageSize(1) - 2, side));
            columnGrid = round(linspace(3, imageSize(2) - 2, side));
            [columns, rows] = meshgrid(columnGrid, rowGrid);
            rows = rows(1:count).';
            columns = columns(1:count).';
        end

        function value = pairMatch(scene, scheduledPair, movingRows, ...
                movingColumns, referenceRows, referenceColumns, imageSize, ...
                pairIndex)
            pair = scheduledPair.Pair;
            layerIds = string({scene.layers(pair).LayerId});
            count = numel(movingRows);
            metric = 0.05 + 0.001 * pairIndex + ...
                1e-5 * (1:count).';
            value = struct(Pair=pair, PairLayerIds=layerIds, ...
                MovingLayerId=layerIds(1), ReferenceLayerId=layerIds(2), ...
                PairDirection="movingToReference", Detector="syntheticOracle", ...
                Matcher="syntheticOracle", ...
                MovingFeatureLocations=[movingColumns movingRows], ...
                ReferenceFeatureLocations=[referenceColumns referenceRows], ...
                MovingPlaneCoordinates=zeros(count, 2), ...
                ReferencePlaneCoordinates=zeros(count, 2), ...
                MovingSourceRows=movingRows, ...
                MovingSourceColumns=movingColumns, ...
                ReferenceSourceRows=referenceRows, ...
                ReferenceSourceColumns=referenceColumns, ...
                IndexPairs=[(1:count).' (1:count).'], ...
                MatchMetric=metric, Scores=ones(count, 1), ...
                FeatureCounts=[count count], Count=count, ...
                OverlapMask=true(imageSize));
        end

        function options = solveOptions(scenario, acceptanceOptions)
            options = struct( ...
                Bounds=struct(OmegaDegrees=0.75, PhiDegrees=0.75, ...
                KappaDegrees=0.75), ...
                Regularization=struct(OverallWeight=1e-6, ...
                RobustLoss="huber"), ...
                Network=struct(Configuration=scenario.Configuration, ...
                ComputeLeaveOnePairOut= ...
                acceptanceOptions.ComputeLeaveOnePairOut));
        end

        function record = summarize(scenario, schedule, result, truth, ...
                evidenceClasses, corruptedPairId)
            solved = reshape( ...
                [result.SolvedCorrections.ViewVectorAngularOffsetsDegrees], ...
                3, []).';
            errors = solved - truth.TruthOffsetsDegrees;
            covariance = result.Diagnostics.Network.ViewCovariance;
            standardDeviation = reshape( ...
                [covariance.StandardDeviationDegrees], 3, []).';
            normalized = abs(errors) ./ standardDeviation;
            normalized(~isfinite(normalized)) = NaN;
            uncertainty = struct( ...
                Available=all(isfinite(standardDeviation), "all"), ...
                StandardDeviationDegrees=standardDeviation, ...
                NormalizedAbsoluteError=normalized, ...
                OneSigmaCoverage=mean(normalized(:) <= 1, "omitnan"), ...
                TwoSigmaCoverage=mean(normalized(:) <= 2, "omitnan"), ...
                ThreeSigmaCoverage=mean(normalized(:) <= 3, "omitnan"), ...
                CalibratedThresholdEstablished=false);
            pairGraph = schedule.Diagnostics.PairGraph;
            graph = struct(SelectedPairCount=schedule.PairCount, ...
                CandidatePairCount=numel(schedule.Graph.Candidates), ...
                TreePairCount=numel(pairGraph.TreePairIds), ...
                ChordPairCount=numel(pairGraph.ChordPairIds), ...
                ComponentCount=pairGraph.SelectedComponentCount, ...
                PairIds=string({schedule.Pairs.PairId}), ...
                Roles=string({schedule.Pairs.GraphRole}));
            evidence = struct(CandidateCount=numel(evidenceClasses), ...
                VisibleTerrainCount=nnz(evidenceClasses == "visibleTerrain"), ...
                OccludedTerrainCount=nnz(evidenceClasses == "occludedTerrain"), ...
                TextureCoverageFailureCount=nnz( ...
                evidenceClasses == "textureCoverageFailure"), ...
                MaskedCount=nnz(evidenceClasses == "masked"), ...
                InvalidGeometryCount=nnz(evidenceClasses == "invalidGeometry"), ...
                SolverRecordCount= ...
                result.Diagnostics.Network.Evidence.SelectedRecordCount);
            corruption = ...
                ProjectionAlignmentSyntheticAcceptance.corruptionSummary( ...
                result, corruptedPairId);
            residual = result.Diagnostics.Comparison.EpipolarCoplanarity;
            record = ProjectionAlignmentSyntheticAcceptance.emptyRecord();
            record.Name = scenario.Name;
            record.ViewCount = scenario.ViewCount;
            record.GraphVariant = scenario.GraphVariant;
            record.Configuration = scenario.Configuration;
            record.Status = "completed";
            record.Graph = graph;
            record.EvidenceClasses = evidence;
            record.Corruption = corruption;
            record.TruthRole = truth.GeometryRole;
            record.TruthEnteredSolver = truth.TruthEnteredSolver;
            record.InjectedOffsetsDegrees = truth.InjectedOffsetsDegrees;
            record.SolvedOffsetsDegrees = solved;
            record.RecoveryErrorDegrees = errors;
            record.RecoveryRmsDegrees = sqrt(mean(errors(:).^2));
            record.RecoveryMaximumDegrees = max(abs(errors), [], "all");
            record.ResidualRmsBefore = residual.RmsBefore;
            record.ResidualRmsAfter = residual.RmsAfter;
            record.Uncertainty = uncertainty;
            record.ConvergenceStatus = result.Convergence.Status;
            record.GaugeValid = result.Diagnostics.Network.Gauge.Valid;
        end

        function summary = corruptionSummary(result, pairId)
            summary = struct(Present=strlength(pairId) > 0, PairId=pairId, ...
                RetainedRecordCount=0, MedianWeight=NaN, ...
                OtherMedianWeight=NaN, DownweightedRecordCount=0);
            if strlength(pairId) == 0
                return
            end
            mapPairIds = string({result.Diagnostics.Network.RecordMap.PairId});
            weights = result.Diagnostics.Network.Robustification.Weights(:);
            count = min(numel(mapPairIds), numel(weights));
            mapPairIds = mapPairIds(1:count);
            weights = weights(1:count);
            corrupt = mapPairIds == pairId;
            summary.RetainedRecordCount = nnz(corrupt);
            if any(corrupt)
                summary.MedianWeight = median(weights(corrupt));
                summary.DownweightedRecordCount = nnz(weights(corrupt) < 0.999);
            end
            if any(~corrupt)
                summary.OtherMedianWeight = median(weights(~corrupt));
            end
        end

        function coverage = coverage(records)
            completed = records([records.Status] == "completed");
            coverage = struct( ...
                ViewCounts=unique([completed.ViewCount]), ...
                GraphVariants=unique(string({completed.GraphVariant}), "stable"), ...
                Configurations=unique(string({completed.Configuration}), "stable"), ...
                CorruptedEdge=any(arrayfun(@(record) ...
                record.Corruption.Present, completed)), ...
                Occlusion=any(arrayfun(@(record) ...
                record.EvidenceClasses.OccludedTerrainCount > 0, completed)), ...
                TextureCoverage=any(arrayfun(@(record) ...
                record.EvidenceClasses.TextureCoverageFailureCount > 0, ...
                completed)), ...
                Masks=any(arrayfun(@(record) ...
                record.EvidenceClasses.MaskedCount > 0, completed)), ...
                InvalidGeometry=any(arrayfun(@(record) ...
                record.EvidenceClasses.InvalidGeometryCount > 0, completed)), ...
                Uncertainty=any(arrayfun(@(record) ...
                record.Uncertainty.Available, completed)));
        end

        function value = status(records)
            states = string({records.Status});
            if all(states == "completed")
                value = "completed";
            elseif any(states == "completed")
                value = "partial";
            else
                value = "failed";
            end
        end

        function record = emptyRecord()
            record = struct(Name="", ViewCount=0, GraphVariant="", ...
                Configuration="", Status="not-run", FailureIdentifier="", ...
                FailureMessage="", Graph=struct(), EvidenceClasses=struct(), ...
                Corruption=struct(), TruthRole="", TruthEnteredSolver=false, ...
                InjectedOffsetsDegrees=zeros(0, 3), ...
                SolvedOffsetsDegrees=zeros(0, 3), ...
                RecoveryErrorDegrees=zeros(0, 3), ...
                RecoveryRmsDegrees=NaN, RecoveryMaximumDegrees=NaN, ...
                ResidualRmsBefore=NaN, ResidualRmsAfter=NaN, ...
                Uncertainty=struct(), ConvergenceStatus="not-run", ...
                GaugeValid=false, RuntimeSeconds=0);
        end
    end
end
