classdef ProjectionExampleSurfaceFusion < ProjectionSurfaceFusionAlgorithm
    %ProjectionExampleSurfaceFusion Minimal external-style per-mode centroid.

    methods
        function metadata = metadata(~)
            metadata = struct(AlgorithmId="example.mode-centroid", ...
                Name="Example per-mode centroid fusion", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct(FusedPoints=true, VoxelEvidence=false, ...
                CompetingModes=true, Covariance=false), ...
                RequiredProducts="ProjectionMultiRayPointSet", ...
                Deterministic=true, Precision="double", ...
                MemoryEstimate="linearInPointCount", ...
                CpuSupported=true, GpuSupported=false, ...
                ProductRole="exampleOnly");
        end

        function options = defaultOptions(~)
            options = struct();
        end

        function options = validateOptions(~, options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options) || ...
                    ~isempty(fieldnames(options))
                error("ProjectionExampleSurfaceFusion:invalidOptions", ...
                    "Example centroid fusion has no options.");
            end
        end
    end

    methods (Access = protected)
        function result = fuseImpl(~, request, ~, ~)
            [inputPoints, rejections] = ...
                ProjectionSurfaceFusionSupport.selectPoints(request);
            modeSummary = ProjectionSurfaceFusionSupport.modeSummary(inputPoints);
            fusedPoints = ProjectionSurfaceFusionResult.emptyPoints();
            for modeIndex = 1:numel(modeSummary.ModeIds)
                modeId = modeSummary.ModeIds(modeIndex);
                modeMask = ProjectionSurfaceFusionSupport. ...
                    modeLabels(inputPoints) == modeId;
                modePoints = inputPoints(modeMask);
                coordinates = horzcat(modePoints.PointWorld);
                contributors = string({modePoints.PointId});
                pointId = "example-centroid-" + extractBefore( ...
                    ProjectionGeometryFingerprint.hash(struct( ...
                    ModeId=modeId, Contributors=contributors)), 17);
                views = ProjectionExampleSurfaceFusion.unionField( ...
                    modePoints, "ContributingViewIds");
                passes = ProjectionExampleSurfaceFusion.unionField( ...
                    modePoints, "ContributingPassIds");
                fusedPoints(end + 1) = struct(PointId=pointId, ...
                    PointWorld=mean(coordinates, 2), ModeId=modeId, ...
                    CompetingMode=numel(modeSummary.ModeIds) > 1, ...
                    State="exampleModeCentroid", ...
                    ContributingPointIds=contributors, ...
                    ContributingViewIds=views, ContributingPassIds=passes, ...
                    IndependentViewCount=numel(views), ...
                    IndependentPassCount=numel(passes), ...
                    CovarianceWorldMetersSquared=nan(3), ...
                    CovarianceStatus="unavailable", ...
                    CovarianceReason="exampleDoesNotPropagateCovariance", ...
                    CovarianceFrame=request.PointSet.WorldFrame); %#ok<AGROW>
            end
            result = struct(FusedPoints=fusedPoints, ...
                SparseVoxelEvidence=struct(), CompetingModes=modeSummary, ...
                Uncertainty=struct(Policy="unavailableExampleOnly"), ...
                Contributors=ProjectionSurfaceFusionSupport. ...
                contributorSummary(inputPoints, fusedPoints), ...
                Rejections=rejections, ...
                Diagnostics=struct(ScientificDefault=false, ...
                Explanation="Minimal subclass example; not a production fusion method."), ...
                Memory=struct(Bytes= ...
                ProjectionSurfaceFusionSupport.bytes(fusedPoints)), ...
                Execution=struct(Device="cpu"));
        end
    end

    methods (Static, Access = private)
        function values = unionField(points, field)
            values = strings(1, 0);
            for index = 1:numel(points)
                values = unique([values reshape( ...
                    string(points(index).(field)), 1, [])], "stable");
            end
            values = sort(values);
        end
    end
end
