classdef ProjectionSurfaceFusionResult
    %ProjectionSurfaceFusionResult Normalize surface-fusion SDK output.

    properties (Constant)
        Format = "ProjectionSurfaceFusionResult"
        Version = 1
    end

    methods (Static)
        function result = validate(result, request, metadata)
            %validate Normalize one algorithm result against its request.
            if ~isstruct(result) || ~isscalar(result)
                error("ProjectionSurfaceFusionResult:invalidResult", ...
                    "Surface-fusion result must be a scalar struct.");
            end
            forbidden = ["Truth" "DisplayPyramid" "PreviewCoordinates" ...
                "Graphics" "RuntimeCache"];
            if any(isfield(result, forbidden))
                error("ProjectionSurfaceFusionResult:forbiddenData", ...
                    "Fusion results cannot contain truth or presentation/runtime state.");
            end
            defaults = struct(Format=ProjectionSurfaceFusionResult.Format, ...
                Version=ProjectionSurfaceFusionResult.Version, ...
                Status="succeeded", Stage="fusionDerived", ...
                ProductRole=metadata.ProductRole, ...
                WorldFrame=request.PointSet.WorldFrame, ...
                AlgorithmId=metadata.AlgorithmId, ...
                FusedPoints=ProjectionSurfaceFusionResult.emptyPoints(), ...
                SparseVoxelEvidence=struct(), ...
                CompetingModes=struct(), ...
                DerivedProducts=struct(Mesh=[], Grid=[]), ...
                Uncertainty=struct(), Contributors=struct(), ...
                Rejections=ProjectionSurfaceFusionResult.emptyRejections(), ...
                Diagnostics=struct(), Timing=struct(TotalSeconds=NaN), ...
                Memory=struct(Bytes=NaN), Precision=request.PrecisionPolicy, ...
                Execution=struct(), Provenance=struct());
            names = string(fieldnames(result));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionSurfaceFusionResult:invalidResult", ...
                    "Unexpected fusion-result field: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = result.(name);
            end
            defaults.Format = string(defaults.Format);
            defaults.Status = string(defaults.Status);
            defaults.Stage = string(defaults.Stage);
            defaults.ProductRole = string(defaults.ProductRole);
            defaults.WorldFrame = string(defaults.WorldFrame);
            defaults.AlgorithmId = string(defaults.AlgorithmId);
            identities = {defaults.Format defaults.Status defaults.Stage ...
                defaults.ProductRole defaults.WorldFrame defaults.AlgorithmId};
            invalidIdentity = cellfun(@(value) ~isscalar(value) || ...
                ismissing(value), identities);
            if any(invalidIdentity) || ...
                    defaults.Format ~= ProjectionSurfaceFusionResult.Format || ...
                    ~isequal(defaults.Version, ...
                    ProjectionSurfaceFusionResult.Version) || ...
                    ~ismember(defaults.Status, ...
                    ["succeeded" "failed" "cancelled"]) || ...
                    defaults.Stage ~= "fusionDerived" || ...
                    defaults.ProductRole ~= string(metadata.ProductRole) || ...
                    defaults.WorldFrame ~= request.PointSet.WorldFrame || ...
                    defaults.AlgorithmId ~= string(metadata.AlgorithmId)
                error("ProjectionSurfaceFusionResult:identityMismatch", ...
                    "Fusion result schema, identity, frame, stage, or role is invalid.");
            end
            defaults.FusedPoints = ProjectionSurfaceFusionResult. ...
                validatePoints(defaults.FusedPoints, defaults.WorldFrame);
            defaults.SparseVoxelEvidence = ProjectionSurfaceFusionResult. ...
                validateVoxelEvidence(defaults.SparseVoxelEvidence, request);
            scalarStructs = ["CompetingModes" "DerivedProducts" ...
                "Uncertainty" "Contributors" "Diagnostics" "Timing" ...
                "Memory" "Precision" "Execution" "Provenance"];
            for field = scalarStructs
                if ~isstruct(defaults.(field)) || ~isscalar(defaults.(field))
                    error("ProjectionSurfaceFusionResult:invalidResult", ...
                        "%s must be a scalar struct.", field);
                end
            end
            if ~isequal(defaults.Precision, request.PrecisionPolicy)
                error("ProjectionSurfaceFusionResult:precisionMismatch", ...
                    "Result precision must match the validated request policy.");
            end
            if ~isstruct(defaults.Rejections)
                error("ProjectionSurfaceFusionResult:invalidResult", ...
                    "Rejections must be a struct array.");
            end
            if isfield(defaults.Memory, "Bytes") && ...
                    (~isnumeric(defaults.Memory.Bytes) || ...
                    ~isscalar(defaults.Memory.Bytes) || ...
                    ~(isfinite(defaults.Memory.Bytes) || isnan(defaults.Memory.Bytes)) || ...
                    defaults.Memory.Bytes < 0)
                error("ProjectionSurfaceFusionResult:invalidResult", ...
                    "Memory.Bytes must be nonnegative or NaN.");
            end
            result = defaults;
        end

        function points = emptyPoints()
            %emptyPoints Return the normalized fused-point schema.
            points = struct("PointId", {}, "PointWorld", {}, "ModeId", {}, ...
                "CompetingMode", {}, "State", {}, ...
                "ContributingPointIds", {}, "ContributingViewIds", {}, ...
                "ContributingPassIds", {}, ...
                "IndependentViewCount", {}, "IndependentPassCount", {}, ...
                "CovarianceWorldMetersSquared", {}, "CovarianceStatus", {}, ...
                "CovarianceReason", {}, "CovarianceFrame", {});
        end

        function rejections = emptyRejections()
            %emptyRejections Return the normalized rejection schema.
            rejections = struct("PointId", {}, "Reason", {});
        end

        function metadata = metadata(result)
            %metadata Return compact JSON-safe fusion-result metadata.
            [request, algorithmMetadata] = ProjectionSurfaceFusionResult. ...
                persistenceContext(result);
            result = ProjectionSurfaceFusionResult.validate( ...
                result, request, algorithmMetadata);
            points = result.FusedPoints;
            pointSummaries = repmat(struct(PointId="", ModeId="", ...
                State="", IndependentViewCount=0, IndependentPassCount=0, ...
                CovarianceStatus=""), 1, numel(points));
            for index = 1:numel(points)
                point = points(index);
                pointSummaries(index) = struct(PointId=point.PointId, ...
                    ModeId=point.ModeId, State=point.State, ...
                    IndependentViewCount=point.IndependentViewCount, ...
                    IndependentPassCount=point.IndependentPassCount, ...
                    CovarianceStatus=point.CovarianceStatus);
            end
            scaleResults = ProjectionSurfaceFusionResult.scaleMetadata( ...
                result.SparseVoxelEvidence);
            metadata = struct(Format=result.Format, Version=result.Version, ...
                Status=result.Status, Stage=result.Stage, ...
                ProductRole=result.ProductRole, WorldFrame=result.WorldFrame, ...
                AlgorithmId=result.AlgorithmId, ...
                PointSummaries=pointSummaries, ...
                VoxelScaleSummaries=scaleResults, ...
                CompetingModes=result.CompetingModes, ...
                Uncertainty=result.Uncertainty, Contributors=result.Contributors, ...
                Rejections=result.Rejections, Diagnostics=result.Diagnostics, ...
                Timing=result.Timing, Memory=result.Memory, ...
                Precision=result.Precision, Execution=result.Execution, ...
                Provenance=result.Provenance);
        end

        function paths = write(result, matPath, metadataPath)
            %write Persist a complete MAT result and compact JSON metadata.
            [request, algorithmMetadata] = ProjectionSurfaceFusionResult. ...
                persistenceContext(result);
            result = ProjectionSurfaceFusionResult.validate( ...
                result, request, algorithmMetadata);
            matPath = ProjectionSurfaceFusionResult.filePath( ...
                matPath, ".mat", "matPath");
            metadataPath = ProjectionSurfaceFusionResult.filePath( ...
                metadataPath, ".json", "metadataPath");
            if matPath == metadataPath
                error("ProjectionSurfaceFusionResult:invalidPath", ...
                    "MAT and JSON paths must be distinct.");
            end
            fusionResult = result;
            save(matPath, "fusionResult", "-v7");
            metadata = ProjectionSurfaceFusionResult.metadata(result);
            fileId = fopen(metadataPath, "w");
            if fileId < 0
                error("ProjectionSurfaceFusionResult:writeFailed", ...
                    "Unable to open metadata path: %s.", metadataPath);
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(metadata, PrettyPrint=true));
            clear cleanup
            paths = struct(MatPath=matPath, MetadataPath=metadataPath);
        end
    end

    methods (Static, Access = private)
        function points = validatePoints(points, worldFrame)
            if ~isstruct(points)
                error("ProjectionSurfaceFusionResult:invalidPoints", ...
                    "FusedPoints must be a struct array.");
            end
            required = string(fieldnames( ...
                ProjectionSurfaceFusionResult.pointTemplate()));
            pointIds = strings(1, numel(points));
            for index = 1:numel(points)
                point = points(index);
                if any(~isfield(point, required))
                    error("ProjectionSurfaceFusionResult:invalidPoints", ...
                        "Fused points must retain identity, contributors, and uncertainty.");
                end
                pointId = string(point.PointId);
                scalarStrings = {pointId string(point.ModeId) ...
                    string(point.State) string(point.CovarianceStatus) ...
                    string(point.CovarianceReason) string(point.CovarianceFrame)};
                invalidString = cellfun(@(value) ~isscalar(value) || ...
                    ismissing(value), scalarStrings);
                pointIdsValue = reshape(string(point.ContributingPointIds), 1, []);
                viewIds = reshape(string(point.ContributingViewIds), 1, []);
                passIds = reshape(string(point.ContributingPassIds), 1, []);
                countValues = {point.IndependentViewCount ...
                    point.IndependentPassCount};
                countsValid = all(cellfun(@(value) isnumeric(value) && ...
                    isscalar(value) && isfinite(value) && value >= 0 && ...
                    fix(value) == value, countValues));
                covarianceInput = point.CovarianceWorldMetersSquared;
                covarianceShape = isnumeric(covarianceInput) && ...
                    isequal(size(covarianceInput), [3 3]);
                if covarianceShape
                    covariance = double(covarianceInput);
                else
                    covariance = zeros(0);
                end
                covarianceValid = ProjectionSurfaceFusionResult. ...
                    covarianceValid(covariance, string(point.CovarianceStatus));
                if any(invalidString) || strlength(pointId) == 0 || ...
                        strlength(string(point.ModeId)) == 0 || ...
                        strlength(string(point.State)) == 0 || ...
                        ~isnumeric(point.PointWorld) || ...
                        ~isequal(size(point.PointWorld), [3 1]) || ...
                        any(~isfinite(point.PointWorld)) || ...
                        ~islogical(point.CompetingMode) || ...
                        ~isscalar(point.CompetingMode) || ...
                        ~covarianceShape || ...
                        ~covarianceValid || ~countsValid || ...
                        point.IndependentViewCount ~= numel(unique(viewIds)) || ...
                        point.IndependentPassCount ~= numel(unique(passIds)) || ...
                        isempty(pointIdsValue) || any(ismissing(pointIdsValue)) || ...
                        any(strlength(pointIdsValue) == 0) || ...
                        any(ismissing(viewIds)) || any(strlength(viewIds) == 0) || ...
                        any(ismissing(passIds)) || any(strlength(passIds) == 0) || ...
                        numel(unique(pointIdsValue)) ~= numel(pointIdsValue) || ...
                        string(point.CovarianceFrame) ~= worldFrame
                    error("ProjectionSurfaceFusionResult:invalidPoints", ...
                        "Fused point geometry or covariance is malformed.");
                end
                pointIds(index) = pointId;
            end
            if numel(unique(pointIds)) ~= numel(pointIds)
                error("ProjectionSurfaceFusionResult:duplicatePointId", ...
                    "Fused PointId values must be unique.");
            end
        end

        function evidence = validateVoxelEvidence(evidence, request)
            if ~isstruct(evidence) || ~isscalar(evidence)
                error("ProjectionSurfaceFusionResult:invalidVoxelEvidence", ...
                    "Sparse voxel evidence must be a scalar struct.");
            end
            if isempty(fieldnames(evidence))
                return
            end
            required = ["Method" "ScaleSource" "ScaleResults"];
            if any(~isfield(evidence, required)) || ...
                    ~isstruct(evidence.ScaleResults)
                error("ProjectionSurfaceFusionResult:invalidVoxelEvidence", ...
                    "Sparse voxel evidence is malformed.");
            end
            roi = request.RoiWorld;
            for scaleResult = evidence.ScaleResults
                scaleRequired = ["VoxelScaleMeters" "GridSize" "Modes" ...
                    "AllocatedVoxelCount" "GridCellCount"];
                if any(~isfield(scaleResult, scaleRequired)) || ...
                        ~isstruct(scaleResult.Modes)
                    error("ProjectionSurfaceFusionResult:invalidVoxelEvidence", ...
                        "Every scale result requires grid and mode evidence.");
                end
                for mode = scaleResult.Modes
                    modeRequired = ["ModeId" "Indices" "CentersWorld" ...
                        "EvidenceWeights" "PointCounts" ...
                        "IndependentViewCounts" "IndependentPassCounts" ...
                        "ContributingPointIds" "ContributingViewIds" ...
                        "ContributingPassIds" "PeakMask"];
                    if any(~isfield(mode, modeRequired)) || ...
                            size(mode.Indices, 2) ~= 3 || ...
                            size(mode.CentersWorld, 1) ~= 3 || ...
                            size(mode.CentersWorld, 2) ~= size(mode.Indices, 1) || ...
                            numel(mode.EvidenceWeights) ~= size(mode.Indices, 1) || ...
                            any(mode.CentersWorld < roi(:, 1) - eps, "all") || ...
                            any(mode.CentersWorld > roi(:, 2) + eps, "all")
                        error("ProjectionSurfaceFusionResult:invalidVoxelEvidence", ...
                            "Mode voxel arrays are inconsistent or outside the ROI.");
                    end
                end
            end
        end

        function point = pointTemplate()
            point = struct(PointId="", PointWorld=nan(3, 1), ...
                ModeId="", CompetingMode=false, State="", ...
                ContributingPointIds=strings(1, 0), ...
                ContributingViewIds=strings(1, 0), ...
                ContributingPassIds=strings(1, 0), ...
                IndependentViewCount=0, IndependentPassCount=0, ...
                CovarianceWorldMetersSquared=nan(3), ...
                CovarianceStatus="unavailable", CovarianceReason="", ...
                CovarianceFrame="");
        end

        function [request, metadata] = persistenceContext(result)
            if ~isstruct(result) || ~isscalar(result) || ...
                    any(~isfield(result, ["WorldFrame" "ProductRole" ...
                    "AlgorithmId" "Precision" "Provenance"])) || ...
                    ~isstruct(result.Provenance) || ...
                    ~isscalar(result.Provenance) || ...
                    any(~isfield(result.Provenance, ["RoiWorld" ...
                    "VoxelScalesMeters" "VoxelScaleSource"]))
                error("ProjectionSurfaceFusionResult:invalidResult", ...
                    "Normalized provenance is required for persistence.");
            end
            request = struct(PointSet=struct(WorldFrame=result.WorldFrame), ...
                RoiWorld=result.Provenance.RoiWorld, ...
                VoxelScalesMeters=result.Provenance.VoxelScalesMeters, ...
                VoxelScaleSource=result.Provenance.VoxelScaleSource, ...
                PrecisionPolicy=result.Precision);
            metadata = struct(ProductRole=result.ProductRole, ...
                AlgorithmId=result.AlgorithmId);
        end

        function summaries = scaleMetadata(evidence)
            if isempty(fieldnames(evidence))
                summaries = struct("VoxelScaleMeters", {}, ...
                    "AllocatedVoxelCount", {}, "GridCellCount", {}, ...
                    "ModeIds", {});
                return
            end
            scales = evidence.ScaleResults;
            summaries = repmat(struct(VoxelScaleMeters=NaN, ...
                AllocatedVoxelCount=0, GridCellCount=0, ...
                ModeIds=strings(1, 0)), 1, numel(scales));
            for index = 1:numel(scales)
                summaries(index) = struct( ...
                    VoxelScaleMeters=scales(index).VoxelScaleMeters, ...
                    AllocatedVoxelCount=scales(index).AllocatedVoxelCount, ...
                    GridCellCount=scales(index).GridCellCount, ...
                    ModeIds=string({scales(index).Modes.ModeId}));
            end
        end

        function path = filePath(path, extension, name)
            path = string(path);
            if ~isscalar(path) || ismissing(path) || strlength(path) == 0 || ...
                    ~endsWith(lower(path), extension)
                error("ProjectionSurfaceFusionResult:invalidPath", ...
                    "%s must be a nonempty %s path.", name, extension);
            end
        end

        function tf = covarianceValid(covariance, status)
            if all(isnan(covariance), "all")
                tf = status == "unavailable";
                return
            end
            if any(~isfinite(covariance), "all")
                tf = false;
                return
            end
            scale = max(1, norm(covariance, "fro"));
            symmetric = norm(covariance - covariance.', "fro") <= ...
                1e-10 * scale;
            tf = symmetric && all(eig(0.5 * ...
                (covariance + covariance.')) >= -1e-10 * scale);
        end
    end
end
