classdef ProjectionDenseSgmTruthAudit
    %ProjectionDenseSgmTruthAudit Deterministic held-out audit of current SGM.

    properties (Constant)
        Format = "ProjectionDenseSgmTruthAudit"
        Version = 1
        GrossOutlierThresholdPixels = 1
        ConsistencyThresholdPixels = 1
    end

    methods (Static)
        function cases = defaultCases()
            %defaultCases Return the bounded public B0 scenario matrix.
            cases = [ ...
                ProjectionDenseSgmTruthAudit.makeCase("nominal", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("far-small-angle", ...
                "far", 240, 4, 2, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("wide-angle", ...
                "near", 100, 8, 8, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("relief-occlusion", ...
                "near", 100, 4, [2 8], "twoLevel", "centralStrip", ...
                "sameBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("cross-band", ...
                "near", 100, 4, 4, "constant", "none", ...
                "crossBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("combined-navigation", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "combinedNavigation", 1.5, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("rectification-error", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 2, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("repetitive-texture", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "repetitive", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("low-texture", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "low", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("large-disparity", ...
                "near", 100, 4, 12, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, false), ...
                ProjectionDenseSgmTruthAudit.makeCase("gpu-request", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, true)];
        end

        function report = run(cases, options)
            %run Execute the SGM audit without exposing truth to the matcher.
            if nargin < 1 || isempty(cases)
                cases = ProjectionDenseSgmTruthAudit.defaultCases();
            end
            if nargin < 2
                options = struct();
            end
            cases = ProjectionDenseSgmTruthAudit.validateCases(cases);
            options = ProjectionDenseSgmTruthAudit.validateRunOptions(options);
            records = repmat(ProjectionDenseSgmTruthAudit.emptyRecord(), ...
                1, numel(cases));
            timer = tic;
            for caseIndex = 1:numel(cases)
                records(caseIndex) = ...
                    ProjectionDenseSgmTruthAudit.runCase(cases(caseIndex));
            end
            failures = string({records.Status}) ~= "completed";
            report = struct(Format=ProjectionDenseSgmTruthAudit.Format, ...
                Version=ProjectionDenseSgmTruthAudit.Version, ...
                Status=ProjectionDenseSgmTruthAudit.reportStatus(failures), ...
                OperationalInputContainsTruth=false, ...
                HeldOutEvaluationTruthUsedOnlyAfterMatching=true, ...
                AutomaticBestMatcherSelected=false, ...
                ThresholdsEstablished=false, Cases=cases, Records=records, ...
                DimensionCoverage= ...
                ProjectionDenseSgmTruthAudit.dimensionCoverage(cases), ...
                Summary=struct(CaseCount=numel(cases), ...
                CompletedCount=nnz(~failures), FailureCount=nnz(failures)), ...
                RuntimeSeconds=toc(timer), Repeatability=struct( ...
                Status="not-checked", Exact=false, ...
                FirstRunRuntimeSeconds=NaN, SecondRunRuntimeSeconds=NaN), ...
                Artifacts=struct(ReportMatPath="", ReportJsonPath=""));
            if options.WriteArtifacts
                report.Artifacts = ProjectionDenseSgmTruthAudit. ...
                    writeArtifacts(report, options.OutputDirectory);
            end
        end

        function report = runRepeatable(cases, options)
            %runRepeatable Execute twice and compare nonvolatile evidence.
            if nargin < 1
                cases = [];
            end
            if nargin < 2
                options = struct();
            end
            options = ProjectionDenseSgmTruthAudit.validateRunOptions(options);
            writeArtifacts = options.WriteArtifacts;
            outputDirectory = options.OutputDirectory;
            options.WriteArtifacts = false;
            first = ProjectionDenseSgmTruthAudit.run(cases, options);
            second = ProjectionDenseSgmTruthAudit.run(cases, options);
            exact = isequaln( ...
                ProjectionDenseSgmTruthAudit.withoutVolatile(first), ...
                ProjectionDenseSgmTruthAudit.withoutVolatile(second));
            report = first;
            report.Repeatability = struct(Status= ...
                ProjectionDenseSgmTruthAudit.repeatabilityStatus(exact), ...
                Exact=exact, FirstRunRuntimeSeconds=first.RuntimeSeconds, ...
                SecondRunRuntimeSeconds=second.RuntimeSeconds);
            if writeArtifacts
                report.Artifacts = ProjectionDenseSgmTruthAudit. ...
                    writeArtifacts(report, outputDirectory);
            end
        end

        function artifacts = writeArtifacts(report, outputDirectory)
            %writeArtifacts Persist compact MAT and JSON audit evidence.
            ProjectionDenseSgmTruthAudit.validateReport(report);
            outputDirectory = string(outputDirectory);
            if ~isscalar(outputDirectory) || ismissing(outputDirectory) || ...
                    strlength(outputDirectory) == 0
                error("ProjectionDenseSgmTruthAudit:invalidOutput", ...
                    "OutputDirectory must be a nonempty string scalar.");
            end
            if ~isfolder(outputDirectory)
                mkdir(outputDirectory);
            end
            matPath = string(fullfile(outputDirectory, ...
                "sgm_truth_audit.mat"));
            jsonPath = string(fullfile(outputDirectory, ...
                "sgm_truth_audit.json"));
            save(matPath, "report", "-v7");
            ProjectionDenseSgmTruthAudit.writeJson(jsonPath, report);
            artifacts = struct(ReportMatPath=matPath, ...
                ReportJsonPath=jsonPath);
        end
    end

    methods (Static, Access = private)
        function record = runCase(caseDefinition)
            timer = tic;
            try
                fixture = ProjectionDenseSgmTruthAudit.buildFixture( ...
                    caseDefinition);
                denseOptions = struct(DisparityRange=[0 16], ...
                    UniquenessThreshold=caseDefinition.UniquenessThreshold, ...
                    MaximumSurfacePoints=20000, ...
                    UseGPU=caseDefinition.UseGPU);
                dense = ProjectionDenseSurfaceExtractor.extract( ...
                    fixture.Scene, fixture.PairWorking, ...
                    fixture.PairMatch, denseOptions);
                metrics = ProjectionDenseSgmTruthAudit.metrics( ...
                    dense, fixture, caseDefinition);
                record = struct(CaseId=caseDefinition.Id, ...
                    Status="completed", FailureIdentifier="", ...
                    FailureMessage="", Metrics=metrics, ...
                    Execution=struct(RequestedGpu=caseDefinition.UseGPU, ...
                    Actual=dense.Diagnostics.Execution, ...
                    GpuInfo=dense.Diagnostics.GpuInfo), ...
                    RuntimeSeconds=toc(timer), ...
                    MemoryBytes=ProjectionDenseSgmTruthAudit.bytesOf(dense));
            catch exception
                record = ProjectionDenseSgmTruthAudit.emptyRecord();
                record.CaseId = caseDefinition.Id;
                record.Status = "failed";
                record.FailureIdentifier = string(exception.identifier);
                record.FailureMessage = string(exception.message);
                record.RuntimeSeconds = toc(timer);
            end
        end

        function metrics = metrics(dense, fixture, caseDefinition)
            estimated = double(dense.Disparity);
            truth = fixture.TruthDisparity;
            validTruth = fixture.TruthStates == "valid" & isfinite(truth);
            validEstimate = validTruth & isfinite(estimated);
            errors = estimated(validEstimate) - truth(validEstimate);
            absoluteErrors = abs(errors);
            candidateCount = nnz(validTruth);
            estimateCount = nnz(validEstimate);
            occluded = fixture.TruthStates == "occluded";
            falseOcclusionValues = nnz(occluded & isfinite(estimated));
            [consistencyCount, consistencyFraction, consistencyP95] = ...
                ProjectionDenseSgmTruthAudit.consistency( ...
                dense, fixture, validEstimate);
            [heightCount, heightRms, heightP95] = ...
                ProjectionDenseSgmTruthAudit.heightMetrics( ...
                dense.Surface, fixture);
            metrics = struct( ...
                CandidateTruthCount=candidateCount, ...
                ValidEstimateCount=estimateCount, ...
                Completeness=ProjectionDenseSgmTruthAudit.ratio( ...
                estimateCount, candidateCount), ...
                GrossOutlierThresholdPixels= ...
                ProjectionDenseSgmTruthAudit.GrossOutlierThresholdPixels, ...
                GrossOutlierRate=ProjectionDenseSgmTruthAudit.ratio( ...
                nnz(absoluteErrors > ...
                ProjectionDenseSgmTruthAudit.GrossOutlierThresholdPixels), ...
                estimateCount), ...
                SubpixelMedianAbsoluteErrorPixels= ...
                ProjectionDenseSgmTruthAudit.medianOrNaN(absoluteErrors), ...
                SubpixelP95AbsoluteErrorPixels= ...
                ProjectionDenseSgmTruthAudit.percentileOrNaN( ...
                absoluteErrors, 95), ...
                SubpixelMaximumAbsoluteErrorPixels= ...
                ProjectionDenseSgmTruthAudit.maxOrNaN(absoluteErrors), ...
                HeightSampleCount=heightCount, ...
                HeightRmsErrorMeters=heightRms, ...
                HeightP95AbsoluteErrorMeters=heightP95, ...
                ConsistencySampleCount=consistencyCount, ...
                LeftRightConsistencyFraction=consistencyFraction, ...
                LeftRightConsistencyP95Pixels=consistencyP95, ...
                OccludedTruthCount=nnz(occluded), ...
                OcclusionFalseValidRate= ...
                ProjectionDenseSgmTruthAudit.ratio( ...
                falseOcclusionValues, nnz(occluded)), ...
                SgmRuntimeSeconds=dense.Diagnostics.TotalSeconds, ...
                ResultMemoryBytes=ProjectionDenseSgmTruthAudit.bytesOf(dense), ...
                IntersectionAngleDegrees= ...
                ProjectionDenseSgmTruthAudit.intersectionAngle( ...
                caseDefinition), ...
                ReliefMeters=max(fixture.TruthHeight, [], "all") - ...
                min(fixture.TruthHeight, [], "all"), ...
                DisparityTruthRangePixels=[min(truth(validTruth)) ...
                max(truth(validTruth))]);
        end

        function [count, fraction, p95] = consistency( ...
                dense, fixture, validForward)
            reverse = disparitySGM(fixture.ReferenceImageUint8, ...
                fixture.MovingImageUint8, DisparityRange=[-16 0], ...
                UniquenessThreshold=fixture.Case.UniquenessThreshold);
            [columns, rows] = meshgrid(1:size(reverse, 2), 1:size(reverse, 1));
            referenceColumns = columns - double(dense.Disparity);
            backward = interp2(double(reverse), referenceColumns, rows, ...
                "linear", NaN);
            values = abs(double(dense.Disparity) + backward);
            usable = validForward & isfinite(values);
            values = values(usable);
            count = numel(values);
            fraction = ProjectionDenseSgmTruthAudit.ratio( ...
                nnz(values <= ...
                ProjectionDenseSgmTruthAudit.ConsistencyThresholdPixels), ...
                count);
            p95 = ProjectionDenseSgmTruthAudit.percentileOrNaN(values, 95);
        end

        function [count, rmsError, p95Error] = heightMetrics(surface, fixture)
            truthHeight = fixture.TruthHeight( ...
                surface.RowIndices, surface.ColumnIndices);
            truthValid = fixture.TruthStates( ...
                surface.RowIndices, surface.ColumnIndices) == "valid";
            valid = surface.ValidMask & truthValid;
            errors = surface.HeightMeters(valid) - truthHeight(valid);
            count = numel(errors);
            rmsError = ProjectionDenseSgmTruthAudit.rmsOrNaN(errors);
            p95Error = ProjectionDenseSgmTruthAudit.percentileOrNaN( ...
                abs(errors), 95);
        end

        function fixture = buildFixture(caseDefinition)
            imageSize = [72 128];
            center = ([imageSize(2), imageSize(1)] + 1) / 2;
            [movingImage, referenceImage, truthDisparity, truthStates] = ...
                ProjectionDenseSgmTruthAudit.images(caseDefinition, imageSize);
            cameraHeight = caseDefinition.CameraHeightMeters;
            baseline = caseDefinition.BaselineMeters;
            focalLength = cameraHeight;
            origins = [-baseline / 2 baseline / 2];
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                {movingImage, referenceImage}, ...
                [caseDefinition.Id + "-moving.tif" ...
                caseDefinition.Id + "-reference.tif"], ...
                struct(RowStride=4, ColumnStride=4, ...
                DisplayTextureMaxPixels=Inf));
            plane = PlanarProjection.definePlaneFromBasis( ...
                zeros(3, 1), [1; 0; 0], [0; 1; 0]);
            for layerIndex = 1:2
                layer = scene.layers(layerIndex);
                origin = [origins(layerIndex); 0; cameraHeight];
                bias = 0;
                if layerIndex == 2
                    bias = caseDefinition.GeometryColumnBiasPixels;
                end
                layer.BaseProjectionPlane = plane;
                layer.CurrentProjectionPlane = plane;
                layer.SourceGeometry.ImageSize = imageSize;
                layer.SourceGeometry.SampleRayFcn = @(rows, columns) ...
                    ProjectionDenseSgmTruthAudit.pinholeRays( ...
                    origin, rows, columns, center, focalLength, bias);
                scene.layers(layerIndex) = layer;
            end
            scene.layers = ProjectionLayerIdentity.ensureLayers(scene.layers);
            [columnGrid, rowGrid] = meshgrid(1:imageSize(2), 1:imageSize(1));
            planeX = columnGrid - center(1);
            planeY = rowGrid - center(2);
            movingColumns = center(1) + ...
                (planeX - origins(1)) * focalLength / cameraHeight;
            referenceColumns = center(1) + ...
                (planeX - origins(2)) * focalLength / cameraHeight;
            sourceRows = center(2) + planeY * focalLength / cameraHeight;
            movingMask = movingColumns >= 1 & movingColumns <= imageSize(2);
            referenceMask = referenceColumns >= 1 & ...
                referenceColumns <= imageSize(2);
            ids = string([scene.layers.LayerId]);
            movingLayer = ProjectionDenseSgmTruthAudit.layerImage( ...
                1, ids(1), movingImage, movingMask, planeX, planeY, ...
                sourceRows, movingColumns);
            referenceLayer = ProjectionDenseSgmTruthAudit.layerImage( ...
                2, ids(2), referenceImage, referenceMask, planeX, planeY, ...
                sourceRows, referenceColumns);
            pairWorking = struct(Pair=[1 2], PairLayerIds=ids, ...
                MovingLayerId=ids(1), ReferenceLayerId=ids(2), ...
                PairDirection="movingToReference", OutputSize=imageSize, ...
                NumericalMode="fullSourceInverseWarp", ...
                ProjectionPlane=plane, OutputGrid=struct(), ...
                PixelToPlane=struct(X=planeX, Y=planeY, ...
                Coordinates=[planeX(:).'; planeY(:).']), ...
                LayerImages=[movingLayer referenceLayer], ...
                LayerMasks=cat(3, movingMask, referenceMask), ...
                OverlapMask=struct(Mask=movingMask & referenceMask), ...
                GridKey="sgm-truth-audit", RenderPlanSummary=struct());
            [pairMatch, truthHeight] = ...
                ProjectionDenseSgmTruthAudit.sparseMatches( ...
                ids, truthDisparity, cameraHeight, baseline, center, origins);
            fixture = struct(Scene=scene, PairWorking=pairWorking, ...
                PairMatch=pairMatch, TruthDisparity=truthDisparity, ...
                TruthHeight=truthHeight, TruthStates=truthStates, ...
                MovingImageUint8=im2uint8(mat2gray(movingImage)), ...
                ReferenceImageUint8=im2uint8(mat2gray(referenceImage)), ...
                Case=caseDefinition);
        end

        function [moving, reference, disparity, states] = ...
                images(caseDefinition, imageSize)
            stream = RandStream("mt19937ar", Seed=73);
            switch caseDefinition.TextureClass
                case "random"
                    moving = imgaussfilt(rand(stream, imageSize), 0.7);
                case "repetitive"
                    columns = 1:imageSize(2);
                    stripe = 0.5 + 0.45 * cos(2 * pi * columns / 8);
                    moving = repmat(stripe, imageSize(1), 1);
                case "low"
                    moving = 0.5 * ones(imageSize);
                otherwise
                    error("ProjectionDenseSgmTruthAudit:invalidCase", ...
                        "Unsupported texture class.");
            end
            if caseDefinition.ReliefClass == "twoLevel"
                rowDisparity = repmat(caseDefinition.DisparityPixels(1), ...
                    imageSize(1), 1);
                rowDisparity((floor(imageSize(1) / 2) + 1):end) = ...
                    caseDefinition.DisparityPixels(2);
            else
                rowDisparity = repmat(caseDefinition.DisparityPixels(1), ...
                    imageSize(1), 1);
            end
            disparity = repmat(rowDisparity, 1, imageSize(2));
            reference = zeros(imageSize);
            vertical = caseDefinition.RectificationErrorPixels;
            for row = 1:imageSize(1)
                sourceRow = row + vertical;
                shift = rowDisparity(row);
                if sourceRow >= 1 && sourceRow <= imageSize(1)
                    reference(row, 1:(end - shift)) = ...
                        moving(sourceRow, (1 + shift):end);
                end
            end
            states = repmat("valid", imageSize);
            columns = repmat(1:imageSize(2), imageSize(1), 1);
            states(columns - disparity < 1) = "outsideOverlap";
            if caseDefinition.OcclusionClass == "centralStrip"
                occluded = columns >= 54 & columns <= 74;
                states(occluded) = "occluded";
                for row = 1:imageSize(1)
                    shift = rowDisparity(row);
                    referenceColumns = (54:74) - shift;
                    referenceColumns = referenceColumns( ...
                        referenceColumns >= 1 & ...
                        referenceColumns <= imageSize(2));
                    reference(row, referenceColumns) = 0;
                end
            end
            if caseDefinition.RadiometricPair == "crossBand"
                reference = 1 - reference;
            end
            moving = min(max(moving, 0), 1);
            reference = min(max(reference, 0), 1);
        end

        function layer = layerImage(index, id, image, mask, x, y, ...
                rows, columns)
            layer = struct(LayerIndex=index, LayerId=id, AnalysisBand=1, ...
                Image=image, ValidMask=mask, ...
                PlaneCoordinates=[x(:).'; y(:).'], SourceRows=rows, ...
                SourceColumns=columns, SourceObservationMask=mask, ...
                MeshSummary=struct());
        end

        function [pairMatch, truthHeight] = sparseMatches( ...
                ids, disparity, cameraHeight, baseline, center, origins)
            truthHeight = cameraHeight .* disparity ./ ...
                (disparity + baseline);
            movingX = [30; 44; 58; 72; 90; 108];
            movingY = [12; 22; 32; 42; 52; 62];
            indices = sub2ind(size(disparity), movingY, movingX);
            sparseDisparity = disparity(indices);
            referenceX = movingX - sparseDisparity;
            heights = truthHeight(indices);
            worldX = (movingX - center(1)) .* ...
                (cameraHeight - heights) / cameraHeight + origins(1);
            worldY = (movingY - center(2)) .* ...
                (cameraHeight - heights) / cameraHeight;
            movingColumns = center(1) + ...
                (worldX - origins(1)) .* cameraHeight ./ ...
                (cameraHeight - heights);
            referenceColumns = center(1) + ...
                (worldX - origins(2)) .* cameraHeight ./ ...
                (cameraHeight - heights);
            sourceRows = center(2) + worldY .* cameraHeight ./ ...
                (cameraHeight - heights);
            pairMatch = struct(Pair=[1 2], PairLayerIds=ids, ...
                Count=numel(movingX), MovingSourceRows=sourceRows, ...
                MovingSourceColumns=movingColumns, ...
                ReferenceSourceRows=sourceRows, ...
                ReferenceSourceColumns=referenceColumns, ...
                MovingFeatureLocations=[movingX movingY], ...
                ReferenceFeatureLocations=[referenceX movingY]);
        end

        function [origins, vectors] = pinholeRays( ...
                origin, rows, columns, center, focalLength, columnBias)
            count = numel(rows);
            origins = repmat(origin, 1, count);
            vectors = [ ...
                (double(columns(:)).' + columnBias - center(1)) / focalLength; ...
                (double(rows(:)).' - center(2)) / focalLength; ...
                -ones(1, count)];
        end

        function angle = intersectionAngle(caseDefinition)
            disparity = median(caseDefinition.DisparityPixels);
            height = caseDefinition.CameraHeightMeters * disparity / ...
                (disparity + caseDefinition.BaselineMeters);
            range = caseDefinition.CameraHeightMeters - height;
            angle = rad2deg(2 * atan2( ...
                caseDefinition.BaselineMeters / 2, range));
        end

        function coverage = dimensionCoverage(cases)
            executionRequests = "cpu";
            if any([cases.UseGPU])
                executionRequests(end + 1) = "gpu-requested";
            end
            coverage = struct( ...
                RangeClasses=unique(string({cases.RangeClass}), "stable"), ...
                IntersectionAngleDegrees=arrayfun( ...
                @ProjectionDenseSgmTruthAudit.intersectionAngle, cases), ...
                ReliefClasses=unique(string({cases.ReliefClass}), "stable"), ...
                OcclusionClasses=unique(string({cases.OcclusionClass}), "stable"), ...
                RadiometricPairs=unique(string({cases.RadiometricPair}), "stable"), ...
                NavigationErrorClasses=unique( ...
                string({cases.NavigationErrorClass}), "stable"), ...
                RectificationErrorsPixels=unique( ...
                [cases.RectificationErrorPixels], "stable"), ...
                TextureClasses=unique(string({cases.TextureClass}), "stable"), ...
                DisparityRangesPixels=reshape([cases.DisparityPixels], [], 1), ...
                ExecutionRequests=executionRequests, ...
                CpuIncluded=any(~[cases.UseGPU]), ...
                GpuRequestIncluded=any([cases.UseGPU]));
        end

        function cases = validateCases(cases)
            required = string(fieldnames( ...
                ProjectionDenseSgmTruthAudit.makeCase("template", ...
                "near", 100, 4, 4, "constant", "none", ...
                "sameBand", "pointingOnly", 0, "random", 0, false)));
            if ~isstruct(cases) || isempty(cases) || ...
                    any(~isfield(cases, required))
                error("ProjectionDenseSgmTruthAudit:invalidCase", ...
                    "Audit cases must use the documented scenario schema.");
            end
            ids = string({cases.Id});
            if any(ismissing(ids)) || any(strlength(ids) == 0) || ...
                    numel(unique(ids)) ~= numel(ids)
                error("ProjectionDenseSgmTruthAudit:invalidCase", ...
                    "Audit case IDs must be distinct nonempty strings.");
            end
            for index = 1:numel(cases)
                caseDefinition = cases(index);
                numericFields = [caseDefinition.CameraHeightMeters ...
                    caseDefinition.BaselineMeters ...
                    caseDefinition.DisparityPixels ...
                    caseDefinition.GeometryColumnBiasPixels ...
                    caseDefinition.RectificationErrorPixels ...
                    caseDefinition.UniquenessThreshold];
                if any(~isfinite(numericFields)) || ...
                        caseDefinition.CameraHeightMeters <= 0 || ...
                        caseDefinition.BaselineMeters <= 0 || ...
                        any(caseDefinition.DisparityPixels <= 0) || ...
                        any(fix(caseDefinition.DisparityPixels) ~= ...
                        caseDefinition.DisparityPixels) || ...
                        any(caseDefinition.DisparityPixels > 15) || ...
                        ~islogical(caseDefinition.UseGPU) || ...
                        ~isscalar(caseDefinition.UseGPU)
                    error("ProjectionDenseSgmTruthAudit:invalidCase", ...
                        "Audit case numeric or execution values are invalid.");
                end
            end
        end

        function options = validateRunOptions(options)
            if nargin < 1 || isempty(options)
                options = struct();
            end
            defaults = struct(WriteArtifacts=false, OutputDirectory="");
            if ~isstruct(options) || ~isscalar(options) || ...
                    any(~ismember(string(fieldnames(options)), ...
                    string(fieldnames(defaults))))
                error("ProjectionDenseSgmTruthAudit:invalidOptions", ...
                    "Run options must contain only documented fields.");
            end
            names = fieldnames(options);
            for index = 1:numel(names)
                defaults.(names{index}) = options.(names{index});
            end
            if ~islogical(defaults.WriteArtifacts) || ...
                    ~isscalar(defaults.WriteArtifacts)
                error("ProjectionDenseSgmTruthAudit:invalidOptions", ...
                    "WriteArtifacts must be a logical scalar.");
            end
            defaults.OutputDirectory = string(defaults.OutputDirectory);
            if defaults.WriteArtifacts && ...
                    (~isscalar(defaults.OutputDirectory) || ...
                    ismissing(defaults.OutputDirectory) || ...
                    strlength(defaults.OutputDirectory) == 0)
                error("ProjectionDenseSgmTruthAudit:invalidOptions", ...
                    "OutputDirectory is required when writing artifacts.");
            end
            options = defaults;
        end

        function caseDefinition = makeCase(id, rangeClass, cameraHeight, ...
                baseline, disparity, relief, occlusion, radiometry, ...
                navigation, geometryBias, texture, rectification, useGpu)
            caseDefinition = struct(Id=id, RangeClass=rangeClass, ...
                CameraHeightMeters=cameraHeight, BaselineMeters=baseline, ...
                DisparityPixels=reshape(disparity, 1, []), ...
                ReliefClass=relief, OcclusionClass=occlusion, ...
                RadiometricPair=radiometry, ...
                NavigationErrorClass=navigation, ...
                GeometryColumnBiasPixels=geometryBias, ...
                RectificationErrorPixels=rectification, ...
                TextureClass=texture, UniquenessThreshold=10, ...
                UseGPU=logical(useGpu));
        end

        function status = reportStatus(failures)
            if ~any(failures)
                status = "complete";
            elseif all(failures)
                status = "failed";
            else
                status = "partial";
            end
        end

        function status = repeatabilityStatus(exact)
            status = "mismatch";
            if exact
                status = "verified";
            end
        end

        function report = withoutVolatile(report)
            report.RuntimeSeconds = 0;
            report.Repeatability = struct(Status="not-checked", ...
                Exact=false, FirstRunRuntimeSeconds=NaN, ...
                SecondRunRuntimeSeconds=NaN);
            report.Artifacts = struct(ReportMatPath="", ReportJsonPath="");
            for index = 1:numel(report.Records)
                report.Records(index).RuntimeSeconds = 0;
                report.Records(index).MemoryBytes = 0;
                report.Records(index).Metrics.SgmRuntimeSeconds = 0;
                report.Records(index).Metrics.ResultMemoryBytes = 0;
            end
        end

        function record = emptyRecord()
            record = struct(CaseId="", Status="not-run", ...
                FailureIdentifier="", FailureMessage="", Metrics=struct(), ...
                Execution=struct(RequestedGpu=false, Actual="not-run", ...
                GpuInfo=struct()), RuntimeSeconds=0, MemoryBytes=0);
        end

        function validateReport(report)
            if ~isstruct(report) || ~isscalar(report) || ...
                    ~isfield(report, "Format") || ...
                    string(report.Format) ~= ProjectionDenseSgmTruthAudit.Format
                error("ProjectionDenseSgmTruthAudit:invalidReport", ...
                    "Report must come from the SGM truth audit.");
            end
        end

        function value = ratio(numerator, denominator)
            if denominator == 0
                value = NaN;
            else
                value = double(numerator) / double(denominator);
            end
        end

        function value = medianOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = median(values);
            end
        end

        function value = percentileOrNaN(values, percentile)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = prctile(values, percentile);
            end
        end

        function value = maxOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = max(values);
            end
        end

        function value = rmsOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = sqrt(mean(values.^2));
            end
        end

        function bytes = bytesOf(value)
            measuredValue = value; %#ok<NASGU>
            info = whos("measuredValue");
            bytes = double(info.bytes);
        end

        function writeJson(path, value)
            fileId = fopen(path, "w");
            if fileId < 0
                error("ProjectionDenseSgmTruthAudit:outputOpenFailed", ...
                    "Unable to open the audit JSON output.");
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(value, ...
                PrettyPrint=true, ConvertInfAndNaN=true));
            clear cleanup
        end
    end
end
