classdef ProjectionDensePairScheduler
    %ProjectionDensePairScheduler Build an independent dense-pair schedule.

    properties (Constant)
        Format = "ProjectionDensePairSchedule"
        Version = 1
    end

    methods (Static)
        function schedule = build(scene, evidence, options)
            %build Score, explain, and select dense reconstruction pairs.
            if nargin < 3
                options = struct();
            end
            scene = ProjectionViewMetadata.ensureScene(scene);
            options = ProjectionDensePairScheduler.validateOptions(options);
            candidates = ProjectionDensePairScheduler.validateEvidence( ...
                scene, evidence);
            candidates = ProjectionDensePairScheduler.scoreCandidates( ...
                candidates, options);
            [validationViewId, validationReason] = ...
                ProjectionDensePairScheduler.validationView( ...
                scene, candidates, options);
            candidates = ProjectionDensePairScheduler.classifyCandidates( ...
                candidates, validationViewId, options);
            selectedMask = string({candidates.Decision}) == "selected";
            selectable = find(selectedMask);
            if ~options.AllPlausiblePairs && isfinite(options.MaximumPairs) && ...
                    numel(selectable) > options.MaximumPairs
                keep = selectable(1:options.MaximumPairs);
                remove = setdiff(selectable, keep, "stable");
                for index = remove
                    candidates(index).Decision = "rejected";
                    candidates(index).SelectionReason = "pairBudget";
                end
                selectedMask = string({candidates.Decision}) == "selected";
            end
            schedule = struct(Format=ProjectionDensePairScheduler.Format, ...
                Version=ProjectionDensePairScheduler.Version, ...
                SparseScheduleConsumed=false, ...
                AllPlausiblePairs=options.AllPlausiblePairs, ...
                MaximumPairs=options.MaximumPairs, ...
                ValidationViewId=validationViewId, ...
                ValidationViewReason=validationReason, ...
                ValidationViewReserved=strlength(validationViewId) > 0, ...
                Candidates=candidates, Selected=candidates(selectedMask), ...
                ValidationCandidates=candidates( ...
                string({candidates.Decision}) == "validation"), ...
                SelectedPairCount=nnz(selectedMask), ...
                PredictedCost=sum([candidates(selectedMask).PredictedCost]), ...
                PredictedMemoryBytes=sum( ...
                [candidates(selectedMask).PredictedMemoryBytes]), ...
                Diagnostics=ProjectionDensePairScheduler.diagnostics( ...
                candidates, scene, validationViewId));
        end

        function options = validateOptions(options)
            %validateOptions Normalize dense scheduling policy.
            if nargin < 1 || isempty(options)
                options = struct();
            end
            defaults = struct(MaximumPairs=3, AllPlausiblePairs=false, ...
                ForceIncludePairIds=strings(1, 0), ...
                ForceExcludePairIds=strings(1, 0), ...
                ReserveValidationView=true, ValidationViewId="", ...
                MinimumOverlap=0.1, MinimumConditioning=0.05, ...
                MinimumTexture=0.05, MinimumRadiometricCompatibility=0.05, ...
                MinimumVisibility=0.1, Weights=struct(Overlap=0.25, ...
                Conditioning=0.2, Texture=0.2, Radiometric=0.15, ...
                Visibility=0.2));
            if ~isstruct(options) || ~isscalar(options) || ...
                    any(~ismember(string(fieldnames(options)), ...
                    string(fieldnames(defaults))))
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "Dense scheduler options contain unsupported fields.");
            end
            names = fieldnames(options);
            for index = 1:numel(names)
                defaults.(names{index}) = options.(names{index});
            end
            if ~(isnumeric(defaults.MaximumPairs) && ...
                    isscalar(defaults.MaximumPairs) && ...
                    (isinf(defaults.MaximumPairs) || ...
                    (isfinite(defaults.MaximumPairs) && ...
                    defaults.MaximumPairs >= 1 && ...
                    fix(defaults.MaximumPairs) == defaults.MaximumPairs)))
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "MaximumPairs must be a positive integer or Inf.");
            end
            logicalFields = ["AllPlausiblePairs" "ReserveValidationView"];
            for field = logicalFields
                if ~islogical(defaults.(field)) || ~isscalar(defaults.(field))
                    error("ProjectionDensePairScheduler:invalidOptions", ...
                        "%s must be a logical scalar.", field);
                end
            end
            defaults.ForceIncludePairIds = reshape(string( ...
                defaults.ForceIncludePairIds), 1, []);
            defaults.ForceExcludePairIds = reshape(string( ...
                defaults.ForceExcludePairIds), 1, []);
            if any(ismember(defaults.ForceIncludePairIds, ...
                    defaults.ForceExcludePairIds))
                error("ProjectionDensePairScheduler:conflictingOverride", ...
                    "A pair cannot be both forced included and excluded.");
            end
            defaults.ValidationViewId = string(defaults.ValidationViewId);
            if ~isscalar(defaults.ValidationViewId) || ...
                    ismissing(defaults.ValidationViewId)
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "ValidationViewId must be a string scalar.");
            end
            thresholdFields = ["MinimumOverlap" "MinimumConditioning" ...
                "MinimumTexture" "MinimumRadiometricCompatibility" ...
                "MinimumVisibility"];
            for field = thresholdFields
                defaults.(field) = ProjectionDensePairScheduler.unitScalar( ...
                    defaults.(field), field);
            end
            requiredWeights = ["Overlap" "Conditioning" "Texture" ...
                "Radiometric" "Visibility"];
            if ~isstruct(defaults.Weights) || ~isscalar(defaults.Weights) || ...
                    any(~isfield(defaults.Weights, requiredWeights)) || ...
                    numel(fieldnames(defaults.Weights)) ~= numel(requiredWeights)
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "Weights must contain the five documented components.");
            end
            weightValues = zeros(1, numel(requiredWeights));
            for index = 1:numel(requiredWeights)
                weightValues(index) = ProjectionDensePairScheduler. ...
                    unitScalar(defaults.Weights.(requiredWeights(index)), ...
                    requiredWeights(index));
            end
            if sum(weightValues) <= 0
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "At least one scheduling weight must be positive.");
            end
            defaults.WeightValues = weightValues / sum(weightValues);
            options = defaults;
        end
    end

    methods (Static, Access = private)
        function candidates = validateEvidence(scene, evidence)
            required = ["Pair" "OverlapFraction" "ConditioningScore" ...
                "TextureScore" "RadiometricCompatibility" ...
                "VisibilityScore" "PredictedCost" ...
                "PredictedMemoryBytes"];
            if ~isstruct(evidence) || isempty(evidence) || ...
                    any(~isfield(evidence, required))
                error("ProjectionDensePairScheduler:invalidEvidence", ...
                    "Dense pair evidence is incomplete.");
            end
            viewIds = string({scene.layers.ViewId});
            candidates = repmat(ProjectionDensePairScheduler.emptyCandidate(), ...
                1, numel(evidence));
            for index = 1:numel(evidence)
                pair = double(evidence(index).Pair(:).');
                if numel(pair) ~= 2 || any(fix(pair) ~= pair) || ...
                        any(pair < 1) || any(pair > numel(scene.layers)) || ...
                        pair(1) == pair(2)
                    error("ProjectionDensePairScheduler:invalidEvidence", ...
                        "Every candidate Pair must select two scene views.");
                end
                identity = ProjectionViewMetadata.pairIdentity( ...
                    viewIds(pair(1)), viewIds(pair(2)));
                metrics = [evidence(index).OverlapFraction ...
                    evidence(index).ConditioningScore ...
                    evidence(index).TextureScore ...
                    evidence(index).RadiometricCompatibility ...
                    evidence(index).VisibilityScore];
                if any(~isfinite(metrics)) || any(metrics < 0 | metrics > 1) || ...
                        ~isscalar(evidence(index).PredictedCost) || ...
                        ~isfinite(evidence(index).PredictedCost) || ...
                        evidence(index).PredictedCost < 0 || ...
                        ~isscalar(evidence(index).PredictedMemoryBytes) || ...
                        ~isfinite(evidence(index).PredictedMemoryBytes) || ...
                        evidence(index).PredictedMemoryBytes < 0
                    error("ProjectionDensePairScheduler:invalidEvidence", ...
                        "Candidate metrics must be finite and bounded.");
                end
                candidates(index) = struct(PairId=identity.PairId, Pair=pair, ...
                    ViewIds=viewIds(pair), OverlapFraction=metrics(1), ...
                    ConditioningScore=metrics(2), TextureScore=metrics(3), ...
                    RadiometricCompatibility=metrics(4), ...
                    VisibilityScore=metrics(5), ...
                    PredictedCost=double(evidence(index).PredictedCost), ...
                    PredictedMemoryBytes=double( ...
                    evidence(index).PredictedMemoryBytes), ...
                    SelectionScore=NaN, Decision="pending", ...
                    SelectionReason="notEvaluated", Forced=false);
            end
            ids = string({candidates.PairId});
            if numel(unique(ids)) ~= numel(ids)
                error("ProjectionDensePairScheduler:duplicatePair", ...
                    "Dense candidate pairs must be unique by stable identity.");
            end
        end

        function candidates = scoreCandidates(candidates, options)
            weights = options.WeightValues;
            for index = 1:numel(candidates)
                values = [candidates(index).OverlapFraction ...
                    candidates(index).ConditioningScore ...
                    candidates(index).TextureScore ...
                    candidates(index).RadiometricCompatibility ...
                    candidates(index).VisibilityScore];
                candidates(index).SelectionScore = sum(weights .* values);
            end
            scores = [candidates.SelectionScore].';
            ids = string({candidates.PairId}).';
            tableValue = table(-scores, ids, (1:numel(candidates)).', ...
                VariableNames=["NegativeScore" "PairId" "Index"]);
            tableValue = sortrows(tableValue, ["NegativeScore" "PairId"]);
            candidates = candidates(tableValue.Index);
        end

        function [viewId, reason] = validationView(scene, candidates, options)
            viewId = "";
            reason = "notRequested";
            if ~options.ReserveValidationView
                return
            end
            viewIds = string({scene.layers.ViewId});
            if numel(viewIds) < 4
                reason = "fewerThanFourViews";
                return
            end
            if strlength(options.ValidationViewId) > 0
                if ~ismember(options.ValidationViewId, viewIds)
                    error("ProjectionDensePairScheduler:unknownValidationView", ...
                        "ValidationViewId is not present in the scene.");
                end
                viewId = options.ValidationViewId;
                reason = "operatorSelected";
                return
            end
            forcedIds = options.ForceIncludePairIds;
            available = true(size(viewIds));
            for index = 1:numel(candidates)
                if ismember(candidates(index).PairId, forcedIds)
                    available(ismember(viewIds, candidates(index).ViewIds)) = false;
                end
            end
            selectable = find(available, 1, "last");
            if isempty(selectable)
                reason = "forcedIncludesUseEveryView";
                return
            end
            viewId = viewIds(selectable);
            reason = "stableHeldOutView";
        end

        function candidates = classifyCandidates(candidates, validationView, options)
            for index = 1:numel(candidates)
                candidate = candidates(index);
                if ismember(candidate.PairId, options.ForceExcludePairIds)
                    candidate.Decision = "rejected";
                    candidate.SelectionReason = "operatorExcluded";
                    candidate.Forced = true;
                elseif ismember(candidate.PairId, options.ForceIncludePairIds)
                    candidate.Decision = "selected";
                    candidate.SelectionReason = "operatorIncluded";
                    candidate.Forced = true;
                elseif strlength(validationView) > 0 && ...
                        ismember(validationView, candidate.ViewIds)
                    candidate.Decision = "validation";
                    candidate.SelectionReason = "reservedValidationView";
                else
                    [candidate.Decision, candidate.SelectionReason] = ...
                        ProjectionDensePairScheduler.thresholdDecision( ...
                        candidate, options);
                end
                candidates(index) = candidate;
            end
        end

        function [decision, reason] = thresholdDecision(candidate, options)
            decision = "selected";
            reason = "qualityRank";
            checks = [candidate.OverlapFraction >= options.MinimumOverlap ...
                candidate.ConditioningScore >= options.MinimumConditioning ...
                candidate.TextureScore >= options.MinimumTexture ...
                candidate.RadiometricCompatibility >= ...
                options.MinimumRadiometricCompatibility ...
                candidate.VisibilityScore >= options.MinimumVisibility];
            reasons = ["insufficientOverlap" "weakConditioning" ...
                "insufficientTexture" "radiometricMismatch" ...
                "insufficientVisibility"];
            failed = find(~checks, 1, "first");
            if ~isempty(failed)
                decision = "rejected";
                reason = reasons(failed);
            end
        end

        function diagnostics = diagnostics(candidates, scene, validationView)
            decisions = string({candidates.Decision});
            selected = candidates(decisions == "selected");
            selectedViews = strings(1, 0);
            if ~isempty(selected)
                selectedViews = unique([selected.ViewIds], "stable");
            end
            sceneViews = string({scene.layers.ViewId});
            reconstructionViews = setdiff(sceneViews, validationView, "stable");
            diagnostics = struct(CandidateCount=numel(candidates), ...
                SelectedCount=nnz(decisions == "selected"), ...
                RejectedCount=nnz(decisions == "rejected"), ...
                ValidationCandidateCount=nnz(decisions == "validation"), ...
                ReconstructionViewIds=reconstructionViews, ...
                SelectedViewIds=selectedViews, ...
                UncoveredReconstructionViewIds=setdiff( ...
                reconstructionViews, selectedViews, "stable"), ...
                EveryDecisionExplained=all(strlength( ...
                string({candidates.SelectionReason})) > 0));
        end

        function candidate = emptyCandidate()
            candidate = struct(PairId="", Pair=zeros(1, 2), ...
                ViewIds=strings(1, 2), OverlapFraction=0, ...
                ConditioningScore=0, TextureScore=0, ...
                RadiometricCompatibility=0, VisibilityScore=0, ...
                PredictedCost=0, PredictedMemoryBytes=0, ...
                SelectionScore=NaN, Decision="pending", ...
                SelectionReason="notEvaluated", Forced=false);
        end

        function value = unitScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value < 0 || value > 1
                error("ProjectionDensePairScheduler:invalidOptions", ...
                    "%s must be a finite scalar in [0,1].", name);
            end
            value = double(value);
        end
    end
end
