classdef ProjectionAlignmentSolverPreparation
    %ProjectionAlignmentSolverPreparation Refine and bound solver evidence.

    methods (Static)
        function preparation = prepare(scene, matchResult, options, runtimeControl)
            %prepare Apply native refinement and spatial evidence selection.
            if nargin < 4
                runtimeControl = struct();
            end
            monitor = [];
            if isfield(runtimeControl, "ProgressMonitor")
                monitor = runtimeControl.ProgressMonitor;
                monitor.setStage("refiningSourceObservations", struct( ...
                    CoarseObservationCount=sum([matchResult.Matches.Count])));
            end
            refinement = ProjectionAlignmentSourceRefiner.refine( ...
                scene, matchResult, options, monitor);
            refinedFiltered = ProjectionAlignmentMatchFilter.filter( ...
                refinement.MatchResult, options, scene);
            selection = ProjectionAlignmentEvidenceSelector.select( ...
                refinedFiltered, options);
            if ~isempty(monitor)
                monitor.setStage("solveEvidenceSelected", struct( ...
                    RefinedObservationCount=refinement.Diagnostics.RefinedCount, ...
                    SelectedObservationCount= ...
                    selection.Diagnostics.SelectedRecordCount));
            end
            preparation = struct(MatchResult=selection.MatchResult, ...
                SourceRefinement=refinement.Diagnostics, ...
                SourceRefinementPairs=refinement.PairDiagnostics, ...
                RefinedFilterDiagnostics=refinedFiltered.Diagnostics, ...
                EvidenceSelection=selection.Diagnostics, ...
                CompleteMatchLedger=selection.MatchResult.MatchLedger);
        end

        function result = attachDiagnostics(result, preparation, matchResult)
            %attachDiagnostics Preserve complete evidence and bounded work.
            result.Diagnostics.SourceRefinement = ...
                preparation.SourceRefinement;
            result.Diagnostics.SourceRefinementPairs = ...
                preparation.SourceRefinementPairs;
            result.Diagnostics.EvidenceSelection = ...
                preparation.EvidenceSelection;
            result.Diagnostics.RefinedFiltering = ...
                preparation.RefinedFilterDiagnostics;
            result.Diagnostics.CompleteMatchLedger = ...
                preparation.CompleteMatchLedger;
            work = result.Diagnostics.WorkAccounting;
            work.CoarseMatchCount = sum([matchResult.Matches.Count]);
            work.RefinedObservationCount = ...
                preparation.SourceRefinement.RefinedCount;
            work.SourcePatchReadCount = ...
                preparation.SourceRefinement.SourceReadCount;
            work.SourcePatchPixelsRead = ...
                preparation.SourceRefinement.SourcePixelsRead;
            work.SourcePatchBytesRead = ...
                preparation.SourceRefinement.SourceBytesRead;
            work.SelectedObservationCount = ...
                preparation.EvidenceSelection.SelectedRecordCount;
            work.SpatialRedundancyCount = ...
                preparation.EvidenceSelection.SpatialRedundancyCount;
            result.Diagnostics.WorkAccounting = work;
        end
    end
end
