classdef ProjectionDenseSurfaceSyntheticNavigation
    %ProjectionDenseSurfaceSyntheticNavigation Build correlated reported geometry.

    properties (Constant)
        Format = "ProjectionDenseSurfaceSyntheticNavigation"
        Version = 1
        PresetNames = ["Tactical Grade IMU" "Navigation Grade IMU"]
        ModeNames = ["pointing-only" "combined-navigation-error"]
    end

    methods (Static)
        function bundle = create(config, truth, imageReference)
            %create Simulate both grades and build image-free geometry variants.
            config = ProjectionDenseSurfaceSyntheticConfig.validate(config);
            ProjectionDenseSurfaceSyntheticNavigation.validateTruth(truth);
            imageReference = ...
                ProjectionDenseSurfaceSyntheticNavigation.validateImageReference( ...
                imageReference, truth);
            presetFields = ["tactical_grade_imu" "navigation_grade_imu"];
            presets = repmat( ...
                ProjectionDenseSurfaceSyntheticNavigation.emptyPreset(), 1, 2);
            for presetIndex = 1:2
                presetConfig = config.navigation.presets.(presetFields(presetIndex));
                errorState = ...
                    ProjectionDenseSurfaceSyntheticNavigation.simulateErrorState( ...
                    config, truth, presetConfig);
                constants = ...
                    ProjectionDenseSurfaceSyntheticNavigation.constantPointingByView( ...
                    truth, errorState);
                pointingGeometries = ...
                    ProjectionDenseSurfaceSyntheticNavigation.sourceGeometries( ...
                    truth, errorState, "pointing-only", constants, ...
                    ProjectionDenseSurfaceSyntheticNavigation.PresetNames(presetIndex));
                combinedGeometries = ...
                    ProjectionDenseSurfaceSyntheticNavigation.sourceGeometries( ...
                    truth, errorState, "combined-navigation-error", ...
                    zeros(3, numel(truth.Views)), ...
                    ProjectionDenseSurfaceSyntheticNavigation.PresetNames(presetIndex));
                variants = [struct(Mode="pointing-only", ...
                    ConstantOpkDegrees=constants, ...
                    SourceGeometries={pointingGeometries}), ...
                    struct(Mode="combined-navigation-error", ...
                    ConstantOpkDegrees=zeros(3, numel(truth.Views)), ...
                    SourceGeometries={combinedGeometries})];
                presets(presetIndex) = struct( ...
                    Name=ProjectionDenseSurfaceSyntheticNavigation. ...
                    PresetNames(presetIndex), ErrorState=errorState, ...
                    Statistics=errorState.Statistics, Variants=variants);
            end
            bundle = struct( ...
                Format=ProjectionDenseSurfaceSyntheticNavigation.Format, ...
                Version=ProjectionDenseSurfaceSyntheticNavigation.Version, ...
                AidingMode=config.navigation.aiding_mode, ...
                BiasDrawScope=config.navigation.bias_draw_scope, ...
                ImageReference=imageReference, ImagesDuplicated=false, ...
                Presets=presets);
        end

        function bundle = createFromResult(config, generationResult)
            %createFromResult Build variants while retaining only image references.
            if ~isstruct(generationResult) || ~isscalar(generationResult) || ...
                    ~isfield(generationResult, "Format") || ...
                    string(generationResult.Format) ~= ...
                    ProjectionDenseSurfaceSyntheticGenerator.Format || ...
                    ~isfield(generationResult, "Truth") || ...
                    ~isfield(generationResult, "Summary") || ...
                    ~isfield(generationResult, "Artifacts")
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidRun", ...
                    "Generation result must come from the synthetic generator.");
            end
            reference = struct( ...
                ConfigurationFingerprint= ...
                generationResult.Summary.ConfigurationFingerprint, ...
                ImagePaths=generationResult.Artifacts.ImagePaths, ...
                ImageSize=generationResult.Summary.ImageSize, ...
                ImageClass=generationResult.Summary.ImageClass);
            bundle = ProjectionDenseSurfaceSyntheticNavigation.create( ...
                config, generationResult.Truth, reference);
        end

        function error = sampleErrorState(errorState, times)
            %sampleErrorState Interpolate correlated navigation errors in time.
            ProjectionDenseSurfaceSyntheticNavigation.validateErrorState(errorState);
            times = ProjectionDenseSurfaceSyntheticNavigation.validateTimes( ...
                times, errorState.TimesSeconds);
            error = struct(TimeSeconds=times, ...
                PositionErrorMeters=interp1(errorState.TimesSeconds, ...
                errorState.PositionErrorMeters.', times, "pchip").', ...
                VelocityErrorMetersPerSecond=interp1(errorState.TimesSeconds, ...
                errorState.VelocityErrorMetersPerSecond.', times, "pchip").', ...
                AttitudeErrorDegrees=interp1(errorState.TimesSeconds, ...
                errorState.AttitudeErrorDegrees.', times, "pchip").');
        end

        function artifacts = writeArtifacts(bundle, outputDirectory)
            %writeArtifacts Persist compact variants and a JSON statistics summary.
            ProjectionDenseSurfaceSyntheticNavigation.validateBundle(bundle);
            outputDirectory = string(outputDirectory);
            if ~isscalar(outputDirectory) || strlength(outputDirectory) == 0
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidOutput", ...
                    "Output directory must be a nonempty scalar path.");
            end
            if ~isfolder(outputDirectory)
                mkdir(outputDirectory);
            end
            matPath = string(fullfile(outputDirectory, ...
                "navigation_variants.mat"));
            save(matPath, "bundle", "-v7");
            presetSummaries = repmat(struct(Name="", Statistics=struct(), ...
                Modes=strings(1, 2), PointingConstantRmsDegrees=0), 1, ...
                numel(bundle.Presets));
            for presetIndex = 1:numel(bundle.Presets)
                preset = bundle.Presets(presetIndex);
                constants = preset.Variants(1).ConstantOpkDegrees;
                presetSummaries(presetIndex) = struct(Name=preset.Name, ...
                    Statistics=preset.Statistics, ...
                    Modes=[preset.Variants.Mode], ...
                    PointingConstantRmsDegrees= ...
                    sqrt(mean(sum(constants.^2, 1))));
            end
            summary = struct(Format=ProjectionDenseSurfaceSyntheticNavigation.Format, ...
                Version=ProjectionDenseSurfaceSyntheticNavigation.Version, ...
                AidingMode=bundle.AidingMode, ...
                BiasDrawScope=bundle.BiasDrawScope, ...
                ImageSetFingerprint= ...
                bundle.ImageReference.ConfigurationFingerprint, ...
                ImagesDuplicated=bundle.ImagesDuplicated, Presets=presetSummaries);
            jsonPath = string(fullfile(outputDirectory, ...
                "navigation_summary.json"));
            ProjectionDenseSurfaceSyntheticNavigation.writeJson(jsonPath, summary);
            artifacts = struct(VariantsMatPath=matPath, SummaryJsonPath=jsonPath);
        end
    end

    methods (Static, Access = private)
        function errorState = simulateErrorState(config, truth, preset)
            gnss = config.navigation.gnss;
            samplesPerAidingInterval = 10;
            step = 1 / (gnss.update_rate_hz * samplesPerAidingInterval);
            acquisitionSpan = (truth.ImageSize(2) - 1) / ...
                truth.LineRateLinesPerSecond;
            startTime = min([truth.Views.CenterTimeSeconds]) - ...
                0.5 * acquisitionSpan;
            endTime = max([truth.Views.CenterTimeSeconds]) + ...
                0.5 * acquisitionSpan;
            startTime = floor(startTime / step) * step;
            endTime = ceil(endTime / step) * step;
            times = startTime:step:endTime;
            sampleCount = numel(times);
            aidingIndices = 1:samplesPerAidingInterval:sampleCount;
            aidingCount = numel(aidingIndices);

            stream = RandStream("mt19937ar", ...
                Seed=config.fixture.random_seed + 701);
            biasCorrelation = max(gnss.correlation_time_seconds, ...
                truth.Trajectory.CorrelationTimeSeconds);
            biasCoefficient = exp(-step / biasCorrelation);
            gyroSigma = preset.gyro_bias_sigma_degrees_per_hour;
            accelerometerSigma = preset.accelerometer_bias_sigma_mg;
            gyroBiasDraw = gyroSigma * randn(stream, 3, 1);
            accelerometerBiasDraw = accelerometerSigma * randn(stream, 3, 1);
            gyroBiasProcess = ...
                ProjectionDenseSurfaceSyntheticNavigation.correlatedNoise( ...
                stream, 3, sampleCount, biasCoefficient, gyroSigma);
            accelerometerBiasProcess = ...
                ProjectionDenseSurfaceSyntheticNavigation.correlatedNoise( ...
                stream, 3, sampleCount, biasCoefficient, accelerometerSigma);
            gyroRandomWalk = randn(stream, 3, sampleCount);
            velocityRandomWalk = randn(stream, 3, sampleCount);

            aidingInterval = 1 / gnss.update_rate_hz;
            gnssCoefficient = exp(-aidingInterval / gnss.correlation_time_seconds);
            positionSigma = [gnss.horizontal_position_sigma_meters; ...
                gnss.horizontal_position_sigma_meters; ...
                gnss.vertical_position_sigma_meters];
            velocitySigma = gnss.velocity_sigma_meters_per_second * ones(3, 1);
            gnssPosition = ...
                ProjectionDenseSurfaceSyntheticNavigation.correlatedNoise( ...
                stream, 3, aidingCount, gnssCoefficient, positionSigma);
            gnssVelocity = ...
                ProjectionDenseSurfaceSyntheticNavigation.correlatedNoise( ...
                stream, 3, aidingCount, gnssCoefficient, velocitySigma);

            positionError = zeros(3, sampleCount);
            velocityError = zeros(3, sampleCount);
            attitudeError = zeros(3, sampleCount);
            positionError(:, 1) = gnssPosition(:, 1);
            velocityError(:, 1) = gnssVelocity(:, 1);
            aidingPointer = 2;
            gravityMetersPerSecondSquared = 9.80665;
            angleRandomWalkStep = ...
                preset.gyro_angle_random_walk_degrees_per_sqrt_hour * ...
                sqrt(step / 3600);
            velocityRandomWalkStep = ...
                preset. ...
                accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour * ...
                sqrt(step / 3600);
            for sampleIndex = 2:sampleCount
                gyroRate = (gyroBiasDraw + gyroBiasProcess(:, sampleIndex)) / 3600;
                acceleration = (accelerometerBiasDraw + ...
                    accelerometerBiasProcess(:, sampleIndex)) * ...
                    gravityMetersPerSecondSquared * 1e-3;
                attitudeError(:, sampleIndex) = ...
                    attitudeError(:, sampleIndex - 1) + gyroRate * step + ...
                    angleRandomWalkStep * gyroRandomWalk(:, sampleIndex);
                velocityError(:, sampleIndex) = ...
                    velocityError(:, sampleIndex - 1) + acceleration * step + ...
                    velocityRandomWalkStep * velocityRandomWalk(:, sampleIndex);
                positionError(:, sampleIndex) = ...
                    positionError(:, sampleIndex - 1) + ...
                    velocityError(:, sampleIndex - 1) * step + ...
                    0.5 * acceleration * step^2;
                if aidingPointer <= aidingCount && ...
                        sampleIndex == aidingIndices(aidingPointer)
                    positionError(:, sampleIndex) = gnssPosition(:, aidingPointer);
                    velocityError(:, sampleIndex) = gnssVelocity(:, aidingPointer);
                    aidingPointer = aidingPointer + 1;
                end
            end
            statistics = ...
                ProjectionDenseSurfaceSyntheticNavigation.errorStatistics( ...
                times, positionError, velocityError, attitudeError, ...
                aidingIndices);
            errorState = struct(Format="ProjectionDenseSurfaceNavigationErrorState", ...
                Version=1, TimesSeconds=times, ...
                PositionErrorMeters=positionError, ...
                VelocityErrorMetersPerSecond=velocityError, ...
                AttitudeErrorDegrees=attitudeError, ...
                GyroBiasDrawDegreesPerHour=gyroBiasDraw, ...
                AccelerometerBiasDrawMg=accelerometerBiasDraw, ...
                AidingIndices=aidingIndices, AidingMode=config.navigation.aiding_mode, ...
                BiasDrawScope=config.navigation.bias_draw_scope, ...
                Statistics=statistics);
        end

        function noise = correlatedNoise( ...
                stream, componentCount, sampleCount, coefficient, sigma)
            sigma = double(sigma);
            if isscalar(sigma)
                sigma = sigma * ones(componentCount, 1);
            end
            standard = zeros(componentCount, sampleCount);
            standard(:, 1) = randn(stream, componentCount, 1);
            innovationScale = sqrt(max(0, 1 - coefficient^2));
            for sampleIndex = 2:sampleCount
                standard(:, sampleIndex) = coefficient * ...
                    standard(:, sampleIndex - 1) + ...
                    innovationScale * randn(stream, componentCount, 1);
            end
            noise = standard .* sigma;
        end

        function statistics = errorStatistics( ...
                times, position, velocity, attitude, aidingIndices)
            unaidedMask = true(1, numel(times));
            unaidedMask(aidingIndices) = false;
            velocitySteps = diff(velocity, 1, 2);
            unaidedStepMask = unaidedMask(2:end);
            statistics = struct( ...
                PositionRmsMeters= ...
                sqrt(mean(sum(position.^2, 1))), ...
                VelocityRmsMetersPerSecond= ...
                sqrt(mean(sum(velocity.^2, 1))), ...
                AttitudeRmsDegrees= ...
                sqrt(mean(sum(attitude.^2, 1))), ...
                MaximumAttitudeDegrees=max(vecnorm(attitude, 2, 1)), ...
                UnaidedVelocityStepRmsMetersPerSecond= ...
                sqrt(mean(sum(velocitySteps(:, unaidedStepMask).^2, 1))), ...
                DurationSeconds=times(end) - times(1), ...
                AidingUpdateCount=numel(aidingIndices));
        end

        function constants = constantPointingByView(truth, errorState)
            acquisitionSpan = (truth.ImageSize(2) - 1) / ...
                truth.LineRateLinesPerSecond;
            constants = zeros(3, numel(truth.Views));
            for viewIndex = 1:numel(truth.Views)
                sampleTimes = truth.Views(viewIndex).CenterTimeSeconds + ...
                    linspace(-0.5 * acquisitionSpan, 0.5 * acquisitionSpan, 9);
                error = ...
                    ProjectionDenseSurfaceSyntheticNavigation.sampleErrorState( ...
                    errorState, sampleTimes);
                constants(:, viewIndex) = mean(error.AttitudeErrorDegrees, 2);
            end
        end

        function geometries = sourceGeometries( ...
                truth, errorState, mode, constants, presetName)
            times = errorState.TimesSeconds;
            truthState = ProjectionDenseSurfaceSyntheticTruth.sampleTrajectory( ...
                truth, times);
            if mode == "combined-navigation-error"
                model = struct(TimesSeconds=times, ...
                    Position=truthState.Position + errorState.PositionErrorMeters, ...
                    Velocity=truthState.Velocity + ...
                    errorState.VelocityErrorMetersPerSecond, ...
                    AttitudeDegrees=truthState.AttitudeDegrees + ...
                    errorState.AttitudeErrorDegrees, ImageSize=truth.ImageSize, ...
                    LineRateLinesPerSecond=truth.LineRateLinesPerSecond, ...
                    CrossTrackFovDegrees=truth.CrossTrackFovDegrees);
            else
                model = struct(TimesSeconds=times, Position=truthState.Position, ...
                    Velocity=truthState.Velocity, ...
                    AttitudeDegrees=truthState.AttitudeDegrees, ...
                    ImageSize=truth.ImageSize, ...
                    LineRateLinesPerSecond=truth.LineRateLinesPerSecond, ...
                    CrossTrackFovDegrees=truth.CrossTrackFovDegrees);
            end
            geometries = cell(1, numel(truth.Views));
            for viewIndex = 1:numel(truth.Views)
                view = truth.Views(viewIndex);
                viewModel = struct(CenterTimeSeconds=view.CenterTimeSeconds, ...
                    RollDegrees=view.RollDegrees, ...
                    PitchStartDegrees=view.PitchStartDegrees, ...
                    PitchEndDegrees=view.PitchEndDegrees, ...
                    ConstantOpkDegrees=zeros(3, 1), OpkAxes=eye(3));
                viewModel.OpkAxes = ...
                    ProjectionDenseSurfaceSyntheticNavigation.opkAxes( ...
                    model, viewModel);
                viewModel.ConstantOpkDegrees = constants(:, viewIndex);
                geometries{viewIndex} = ...
                    ProjectionDenseSurfaceSyntheticNavigation.sourceGeometry( ...
                    model, viewModel, presetName, mode, viewIndex);
            end
        end

        function geometry = sourceGeometry( ...
                model, view, presetName, mode, viewIndex)
            centerRow = 0.5 * (model.ImageSize(1) + 1);
            centerColumn = 0.5 * (model.ImageSize(2) + 1);
            [centerOrigin, centerRay] = ...
                ProjectionDenseSurfaceSyntheticNavigation.sampleReportedPairs( ...
                model, view, centerRow, centerColumn);
            centerState = ...
                ProjectionDenseSurfaceSyntheticNavigation.reportedState( ...
                model, view.CenterTimeSeconds);
            platformDirection = centerState.Velocity(:, 1);
            platformDirection = platformDirection / norm(platformDirection);
            rowAxis = view.OpkAxes(:, 1);
            terrainScale = -centerOrigin(3) / centerRay(3);
            nominalSceneCenter = centerOrigin + terrainScale * centerRay;
            geometry = struct(ImageSize=model.ImageSize, ...
                CoordinateFrame="reported-synthetic-navigation", ...
                PresetName=presetName, AcceptanceMode=mode, ...
                TruthIncluded=false, ImageCenter=[centerRow centerColumn], ...
                IFOVDegrees=model.CrossTrackFovDegrees / (model.ImageSize(1) - 1), ...
                G0=centerOrigin, ReferenceOrigin=centerOrigin, ...
                OpticalAxis=centerRay, PlatformDirection=platformDirection, ...
                RowAxis=rowAxis, ImageXAxis=platformDirection, ...
                ImageYAxis=rowAxis, NominalSceneCenter=nominalSceneCenter, ...
                Metadata=struct(ViewIndex=viewIndex, PresetName=presetName, ...
                AcceptanceMode=mode, TruthIncluded=false));
            geometry.SampleFcn = @(rowIndices, columnIndices) ...
                ProjectionDenseSurfaceSyntheticNavigation.sampleReportedGrid( ...
                model, view, rowIndices, columnIndices);
            geometry.SampleRayFcn = @(rowPositions, columnPositions) ...
                ProjectionDenseSurfaceSyntheticNavigation.sampleReportedPairs( ...
                model, view, rowPositions, columnPositions);
        end

        function [origins, vectors] = sampleReportedGrid( ...
                model, view, rowIndices, columnIndices)
            rowIndices = ProjectionDenseSurfaceSyntheticNavigation.validateIndices( ...
                rowIndices, model.ImageSize(1), "rowIndices", true);
            columnIndices = ...
                ProjectionDenseSurfaceSyntheticNavigation.validateIndices( ...
                columnIndices, model.ImageSize(2), "columnIndices", true);
            centerColumn = 0.5 * (model.ImageSize(2) + 1);
            times = view.CenterTimeSeconds + ...
                (columnIndices - centerColumn) / model.LineRateLinesPerSecond;
            state = ProjectionDenseSurfaceSyntheticNavigation.reportedState( ...
                model, times);
            origins = state.Position;
            [xBody, yBody, zBody] = ...
                ProjectionDenseSurfaceSyntheticNavigation.bodyRayGrid( ...
                model, view, rowIndices, columnIndices);
            vectors = ProjectionDenseSurfaceSyntheticNavigation.rotateBodyGrid( ...
                xBody, yBody, zBody, state.AttitudeDegrees);
            vectors = ProjectionDenseSurfaceSyntheticNavigation.applyOpkGrid( ...
                vectors, view.OpkAxes, view.ConstantOpkDegrees);
        end

        function [origins, vectors] = sampleReportedPairs( ...
                model, view, rows, columns)
            rows = ProjectionDenseSurfaceSyntheticNavigation.validateIndices( ...
                rows, model.ImageSize(1), "rowPositions", false);
            columns = ProjectionDenseSurfaceSyntheticNavigation.validateIndices( ...
                columns, model.ImageSize(2), "columnPositions", false);
            if isscalar(rows)
                rows = repmat(rows, size(columns));
            elseif isscalar(columns)
                columns = repmat(columns, size(rows));
            elseif numel(rows) ~= numel(columns)
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidObservations", ...
                    "Row and column observation counts must match or be scalar.");
            end
            centerColumn = 0.5 * (model.ImageSize(2) + 1);
            times = view.CenterTimeSeconds + ...
                (columns - centerColumn) / model.LineRateLinesPerSecond;
            state = ProjectionDenseSurfaceSyntheticNavigation.reportedState( ...
                model, times);
            origins = state.Position;
            centerRow = 0.5 * (model.ImageSize(1) + 1);
            rowIfov = model.CrossTrackFovDegrees / (model.ImageSize(1) - 1);
            roll = deg2rad(view.RollDegrees + (rows - centerRow) * rowIfov);
            fraction = (columns - 1) / (model.ImageSize(2) - 1);
            pitch = deg2rad(view.PitchStartDegrees + fraction * ...
                (view.PitchEndDegrees - view.PitchStartDegrees));
            xBody = sin(pitch);
            yBody = -sin(roll) .* cos(pitch);
            zBody = cos(roll) .* cos(pitch);
            vectors = ProjectionDenseSurfaceSyntheticNavigation.rotateBodyPairs( ...
                xBody, yBody, zBody, state.AttitudeDegrees);
            vectors = ProjectionDenseSurfaceSyntheticNavigation.applyOpkPairs( ...
                vectors, view.OpkAxes, view.ConstantOpkDegrees);
        end

        function axes = opkAxes(model, view)
            centerRow = 0.5 * (model.ImageSize(1) + 1);
            centerColumn = 0.5 * (model.ImageSize(2) + 1);
            [~, ray] = ...
                ProjectionDenseSurfaceSyntheticNavigation.sampleReportedPairs( ...
                model, view, centerRow, centerColumn);
            state = ProjectionDenseSurfaceSyntheticNavigation.reportedState( ...
                model, view.CenterTimeSeconds);
            platform = state.Velocity(:, 1);
            platform = platform / norm(platform);
            rowAxis = cross(platform, ray);
            rowAxis = rowAxis / norm(rowAxis);
            axes = [rowAxis platform ray];
        end

        function state = reportedState(model, times)
            state = struct(Position=interp1(model.TimesSeconds, ...
                model.Position.', times, "pchip").', ...
                Velocity=interp1(model.TimesSeconds, ...
                model.Velocity.', times, "pchip").', ...
                AttitudeDegrees=interp1(model.TimesSeconds, ...
                model.AttitudeDegrees.', times, "pchip").');
        end

        function [xBody, yBody, zBody] = bodyRayGrid( ...
                model, view, rows, columns)
            centerRow = 0.5 * (model.ImageSize(1) + 1);
            rowIfov = model.CrossTrackFovDegrees / (model.ImageSize(1) - 1);
            roll = deg2rad(view.RollDegrees + (rows(:) - centerRow) * rowIfov);
            fraction = (columns - 1) / (model.ImageSize(2) - 1);
            pitch = deg2rad(view.PitchStartDegrees + fraction * ...
                (view.PitchEndDegrees - view.PitchStartDegrees));
            xBody = repmat(sin(pitch), numel(rows), 1);
            yBody = -sin(roll) * cos(pitch);
            zBody = cos(roll) * cos(pitch);
        end

        function vectors = rotateBodyGrid(xBody, yBody, zBody, attitude)
            transform = ...
                ProjectionDenseSurfaceSyntheticNavigation.rotationCoefficients( ...
                attitude);
            worldX = xBody .* transform.R11 + yBody .* transform.R12 + ...
                zBody .* transform.R13;
            worldY = xBody .* transform.R21 + yBody .* transform.R22 + ...
                zBody .* transform.R23;
            worldZ = xBody .* transform.R31 + yBody .* transform.R32 + ...
                zBody .* transform.R33;
            vectors = permute(cat(3, worldX, worldY, worldZ), [3 1 2]);
            vectors = vectors ./ sqrt(sum(vectors.^2, 1));
        end

        function vectors = rotateBodyPairs(xBody, yBody, zBody, attitude)
            transform = ...
                ProjectionDenseSurfaceSyntheticNavigation.rotationCoefficients( ...
                attitude);
            vectors = [xBody .* transform.R11 + yBody .* transform.R12 + ...
                zBody .* transform.R13; ...
                xBody .* transform.R21 + yBody .* transform.R22 + ...
                zBody .* transform.R23; ...
                xBody .* transform.R31 + yBody .* transform.R32 + ...
                zBody .* transform.R33];
            vectors = vectors ./ vecnorm(vectors, 2, 1);
        end

        function vectors = applyOpkGrid(vectors, axes, opkDegrees)
            if all(abs(opkDegrees) <= eps)
                return
            end
            originalSize = size(vectors);
            vectors = reshape( ...
                ProjectionDenseSurfaceSyntheticNavigation.opkRotation( ...
                axes, opkDegrees) * reshape(vectors, 3, []), originalSize);
            vectors = vectors ./ sqrt(sum(vectors.^2, 1));
        end

        function vectors = applyOpkPairs(vectors, axes, opkDegrees)
            if all(abs(opkDegrees) <= eps)
                return
            end
            vectors = ProjectionDenseSurfaceSyntheticNavigation.opkRotation( ...
                axes, opkDegrees) * vectors;
            vectors = vectors ./ vecnorm(vectors, 2, 1);
        end

        function rotation = opkRotation(axes, opkDegrees)
            omega = ProjectionDenseSurfaceSyntheticNavigation.rotationAboutAxis( ...
                axes(:, 1), deg2rad(opkDegrees(1)));
            phi = ProjectionDenseSurfaceSyntheticNavigation.rotationAboutAxis( ...
                axes(:, 2), deg2rad(opkDegrees(2)));
            kappa = ProjectionDenseSurfaceSyntheticNavigation.rotationAboutAxis( ...
                axes(:, 3), deg2rad(opkDegrees(3)));
            rotation = kappa * phi * omega;
        end

        function rotation = rotationAboutAxis(axis, angle)
            axis = axis / norm(axis);
            skew = [0 -axis(3) axis(2); axis(3) 0 -axis(1); ...
                -axis(2) axis(1) 0];
            rotation = cos(angle) * eye(3) + (1 - cos(angle)) * ...
                (axis * axis.') + sin(angle) * skew;
        end

        function transform = rotationCoefficients(attitude)
            roll = deg2rad(attitude(1, :));
            pitch = deg2rad(attitude(2, :));
            yaw = deg2rad(attitude(3, :));
            sr = sin(roll);
            cr = cos(roll);
            sp = sin(pitch);
            cp = cos(pitch);
            sy = sin(yaw);
            cy = cos(yaw);
            transform = struct(R11=cy .* cp, ...
                R12=cy .* sp .* sr - sy .* cr, ...
                R13=cy .* sp .* cr + sy .* sr, R21=sy .* cp, ...
                R22=sy .* sp .* sr + cy .* cr, ...
                R23=sy .* sp .* cr - cy .* sr, R31=sp, ...
                R32=-cp .* sr, R33=-cp .* cr);
        end

        function values = validateIndices(values, maximum, name, integerOnly)
            if ~isnumeric(values) || isempty(values) || ~isvector(values) || ...
                    any(~isfinite(values)) || any(values < 1) || ...
                    any(values > maximum) || ...
                    (integerOnly && any(fix(values) ~= values))
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidObservations", ...
                    "%s must contain finite in-bounds image positions.", name);
            end
            values = double(values(:).');
        end

        function writeJson(path, value)
            fileId = fopen(path, "w");
            if fileId < 0
                error("ProjectionDenseSurfaceSyntheticNavigation:outputOpenFailed", ...
                    "Could not open navigation JSON output for writing.");
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(value, PrettyPrint=true));
            clear cleanup
        end

        function reference = validateImageReference(reference, truth)
            required = ["ConfigurationFingerprint" "ImagePaths" ...
                "ImageSize" "ImageClass"];
            if isstruct(reference) && isfield(reference, "ImageSize")
                reference.ImageSize = reshape(double(reference.ImageSize), 1, []);
            end
            if ~isstruct(reference) || ~isscalar(reference) || ...
                    ~all(isfield(reference, required)) || ...
                    isfield(reference, "Images") || isfield(reference, "Image") || ...
                    ~isequal(reference.ImageSize, double(truth.ImageSize))
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidImageReference", ...
                    "Image reference must identify the shared truth image set without payloads.");
            end
            reference.ConfigurationFingerprint = ...
                string(reference.ConfigurationFingerprint);
            reference.ImagePaths = string(reference.ImagePaths);
            reference.ImageClass = string(reference.ImageClass);
        end

        function validateTruth(truth)
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    ~isfield(truth, "Format") || ...
                    string(truth.Format) ~= ProjectionDenseSurfaceSyntheticTruth.Format
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidTruth", ...
                    "Truth must come from the synthetic truth model.");
            end
        end

        function validateErrorState(errorState)
            required = ["Format" "TimesSeconds" "PositionErrorMeters" ...
                "VelocityErrorMetersPerSecond" "AttitudeErrorDegrees"];
            if ~isstruct(errorState) || ~isscalar(errorState) || ...
                    ~all(isfield(errorState, required)) || ...
                    string(errorState.Format) ~= ...
                    "ProjectionDenseSurfaceNavigationErrorState"
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidErrorState", ...
                    "Error state must come from the navigation simulator.");
            end
        end

        function validateBundle(bundle)
            required = ["Format" "ImageReference" "ImagesDuplicated" "Presets"];
            if ~isstruct(bundle) || ~isscalar(bundle) || ...
                    ~all(isfield(bundle, required)) || ...
                    string(bundle.Format) ~= ...
                    ProjectionDenseSurfaceSyntheticNavigation.Format || ...
                    bundle.ImagesDuplicated || isfield(bundle, "Images")
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidBundle", ...
                    "Navigation bundle must contain compact image-free variants.");
            end
        end

        function times = validateTimes(times, timeline)
            if ~isnumeric(times) || isempty(times) || ~isvector(times) || ...
                    any(~isfinite(times)) || any(times < timeline(1)) || ...
                    any(times > timeline(end))
                error("ProjectionDenseSurfaceSyntheticNavigation:invalidTimes", ...
                    "Sample times must lie within the navigation timeline.");
            end
            times = double(times(:).');
        end

        function preset = emptyPreset()
            preset = struct(Name="", ErrorState=struct(), Statistics=struct(), ...
                Variants=struct([]));
        end
    end
end
