classdef ProjectionAnalysisSourceCache < handle
    %ProjectionAnalysisSourceCache Immutable radiometric source-level cache.
    %
    % This cache is alignment-only. It reads one native source band, builds
    % antialiased power-of-two levels with normalized validity reduction,
    % and samples those levels without using display imagery or display LOD.

    properties (Constant)
        Format = "ProjectionAnalysisSourceCache"
        Version = 1
        ReductionVersion = "normalized-box-v1"
    end

    properties (SetAccess = private)
        Options
    end

    properties (Access = private)
        Entries
        Totals
    end

    methods
        function cache = ProjectionAnalysisSourceCache(options)
            if nargin < 1
                options = struct();
            end
            cache.Options = ProjectionAnalysisSourceCache.validateOptions(options);
            cache.Entries = containers.Map( ...
                "KeyType", "char", "ValueType", "any");
            cache.Totals = ProjectionAnalysisSourceCache.emptyTotals();
        end

        function [outputImage, validMask, diagnostics] = sample( ...
                cache, layer, provider, bandIndex, mapping, interpolation, ...
                invalidFillValue)
            %sample Sample an analysis-selected source level.
            provider = ProjectionBackendSourceProvider.validate(provider);
            ProjectionAnalysisSourceCache.validateMapping(mapping);
            bandIndex = ProjectionAnalysisSourceCache.validateBand( ...
                bandIndex, provider.BandCount);

            planningTimer = tic;
            footprint = ProjectionAnalysisSourceCache.sourceFootprint(mapping);
            downsample = ProjectionAnalysisSourceCache.chooseDownsample( ...
                footprint.Percentile90, cache.Options.OversamplingFactor, ...
                cache.Options.MaximumDownsample);
            region = ProjectionAnalysisSourceCache.planRegion( ...
                mapping, provider.ImageSize, downsample, ...
                cache.Options.RegionAlignmentPixels);
            identity = ProjectionAnalysisSourceCache.identity( ...
                layer, provider, bandIndex, region, downsample, cache.Options);
            key = char(ProjectionGeometryFingerprint.hash(identity));
            planningSeconds = toc(planningTimer);

            lookupTimer = tic;
            cacheHit = isKey(cache.Entries, key);
            lookupSeconds = toc(lookupTimer);
            if cacheHit
                entry = cache.Entries(key);
                cache.Totals.CacheHits = cache.Totals.CacheHits + 1;
                readSeconds = 0;
                pyramidSeconds = 0;
                validitySeconds = 0;
                sourceReadCount = 0;
                sourcePixelsRead = 0;
                sourceBytesRead = 0;
            else
                [entry, work] = ProjectionAnalysisSourceCache.buildEntry( ...
                    provider, bandIndex, region, downsample, cache.Options);
                cache.Entries(key) = entry;
                cache.Totals.CacheMisses = cache.Totals.CacheMisses + 1;
                cache.Totals.SourceReadCount = ...
                    cache.Totals.SourceReadCount + work.SourceReadCount;
                cache.Totals.PyramidBuildCount = ...
                    cache.Totals.PyramidBuildCount + (downsample > 1);
                cache.Totals.SourcePixelsRead = ...
                    cache.Totals.SourcePixelsRead + work.SourcePixelsRead;
                cache.Totals.SourceBytesRead = ...
                    cache.Totals.SourceBytesRead + work.SourceBytesRead;
                readSeconds = work.SourceReadSeconds;
                pyramidSeconds = work.PyramidSeconds;
                validitySeconds = work.ValiditySeconds;
                sourceReadCount = work.SourceReadCount;
                sourcePixelsRead = work.SourcePixelsRead;
                sourceBytesRead = work.SourceBytesRead;
            end

            resampleTimer = tic;
            levelMapping = ProjectionAnalysisSourceCache.levelMapping( ...
                mapping, entry);
            [outputImage, validMask] = ...
                ProjectionFullSourceInverseWarp.sampleImage( ...
                entry.Image, levelMapping, interpolation, invalidFillValue);
            validitySamples = interp2(double(entry.ValidMask), ...
                levelMapping.ColumnCoordinates, ...
                levelMapping.RowCoordinates, "linear", 0);
            validMask = validMask & validitySamples >= ...
                cache.Options.MinimumValidityWeight;
            outputImage(~validMask) = invalidFillValue;
            resampleSeconds = toc(resampleTimer);

            cache.Totals.PlanningSeconds = ...
                cache.Totals.PlanningSeconds + planningSeconds;
            cache.Totals.CacheLookupSeconds = ...
                cache.Totals.CacheLookupSeconds + lookupSeconds;
            cache.Totals.SourceReadSeconds = ...
                cache.Totals.SourceReadSeconds + readSeconds;
            cache.Totals.PyramidSeconds = ...
                cache.Totals.PyramidSeconds + pyramidSeconds;
            cache.Totals.ValiditySeconds = ...
                cache.Totals.ValiditySeconds + validitySeconds;
            cache.Totals.ResampleSeconds = ...
                cache.Totals.ResampleSeconds + resampleSeconds;

            diagnostics = struct( ...
                Format=cache.Format, Version=cache.Version, ...
                CacheIdentity=string(key), CacheHit=cacheHit, ...
                SourceKind=provider.Kind, BandIndex=bandIndex, ...
                RadiometricOption=cache.Options.RadiometricOption, ...
                NodataPolicy=cache.Options.NodataPolicy, ...
                ReductionVersion=cache.ReductionVersion, ...
                SelectedDownsample=downsample, ...
                SourcePixelsPerWorkingPixel=footprint.Median, ...
                SourceFootprintPercentile90=footprint.Percentile90, ...
                OversamplingFactor=cache.Options.OversamplingFactor, ...
                Region=region, SourcePixelsRead=sourcePixelsRead, ...
                SourceBytesRead=sourceBytesRead, ...
                SourceReadCount=sourceReadCount, ...
                LevelSize=size(entry.Image, [1 2]), ...
                PlanningSeconds=planningSeconds, ...
                CacheLookupSeconds=lookupSeconds, ...
                SourceReadSeconds=readSeconds, ...
                PyramidSeconds=pyramidSeconds, ...
                ValiditySeconds=validitySeconds, ...
                ResampleSeconds=resampleSeconds);
        end

        function totals = diagnostics(cache)
            %diagnostics Return cumulative bounded-work accounting.
            totals = cache.Totals;
            totals.Format = cache.Format;
            totals.Version = cache.Version;
            totals.EntryCount = cache.Entries.Count;
            totals.ReductionVersion = cache.ReductionVersion;
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionAnalysisSourceCache:invalidOptions", ...
                    "Analysis-pyramid options must be a scalar struct.");
            end
            defaults = struct(OversamplingFactor=1.25, ...
                MaximumDownsample=1024, RegionAlignmentPixels=64, ...
                MaximumMaterializationPixels=4000000, ...
                MinimumValidityWeight=1 - 1e-5, ...
                NodataPolicy="finiteSourceSamples", ...
                RadiometricOption="nativeSourceBand");
            names = fieldnames(options);
            for index = 1:numel(names)
                if ~isfield(defaults, names{index})
                    error("ProjectionAnalysisSourceCache:invalidOptions", ...
                        "Unknown analysis-pyramid option %s.", names{index});
                end
                defaults.(names{index}) = options.(names{index});
            end
            positive = [defaults.OversamplingFactor ...
                defaults.MaximumDownsample defaults.RegionAlignmentPixels ...
                defaults.MaximumMaterializationPixels];
            if any(~isfinite(positive)) || any(positive <= 0) || ...
                    fix(defaults.MaximumDownsample) ~= ...
                    defaults.MaximumDownsample || ...
                    fix(defaults.RegionAlignmentPixels) ~= ...
                    defaults.RegionAlignmentPixels || ...
                    fix(defaults.MaximumMaterializationPixels) ~= ...
                    defaults.MaximumMaterializationPixels
                error("ProjectionAnalysisSourceCache:invalidOptions", ...
                    "Oversampling and cache bounds must be positive finite values.");
            end
            if ~isnumeric(defaults.MinimumValidityWeight) || ...
                    ~isscalar(defaults.MinimumValidityWeight) || ...
                    defaults.MinimumValidityWeight <= 0 || ...
                    defaults.MinimumValidityWeight > 1
                error("ProjectionAnalysisSourceCache:invalidOptions", ...
                    "MinimumValidityWeight must be in (0, 1].");
            end
            defaults.NodataPolicy = string(defaults.NodataPolicy);
            defaults.RadiometricOption = string(defaults.RadiometricOption);
            if defaults.NodataPolicy ~= "finiteSourceSamples" || ...
                    defaults.RadiometricOption ~= "nativeSourceBand"
                error("ProjectionAnalysisSourceCache:invalidOptions", ...
                    "Only finite source samples and native source-band radiometry are supported.");
            end
            options = defaults;
        end

        function validateMapping(mapping)
            required = ["OutputSize" "ImageSize" "RowCoordinates" ...
                "ColumnCoordinates" "ValidMask" "CoordinateTolerance"];
            if ~isstruct(mapping) || ~isscalar(mapping) || ...
                    any(~isfield(mapping, required)) || ...
                    ~isequal(size(mapping.RowCoordinates), mapping.OutputSize) || ...
                    ~isequal(size(mapping.ColumnCoordinates), mapping.OutputSize) || ...
                    ~isequal(size(mapping.ValidMask), mapping.OutputSize)
                error("ProjectionAnalysisSourceCache:invalidMapping", ...
                    "A full-source coordinate map is required.");
            end
        end

        function bandIndex = validateBand(bandIndex, bandCount)
            if ~isnumeric(bandIndex) || ~isscalar(bandIndex) || ...
                    ~isfinite(bandIndex) || bandIndex < 1 || ...
                    fix(bandIndex) ~= bandIndex || bandIndex > bandCount
                error("ProjectionAnalysisSourceCache:invalidBand", ...
                    "BandIndex must select a source band.");
            end
            bandIndex = double(bandIndex);
        end

        function footprint = sourceFootprint(mapping)
            rows = mapping.RowCoordinates;
            columns = mapping.ColumnCoordinates;
            [rowDx, rowDy] = gradient(rows);
            [columnDx, columnDy] = gradient(columns);
            horizontal = hypot(rowDx, columnDx);
            vertical = hypot(rowDy, columnDy);
            values = max(horizontal, vertical);
            values = values(mapping.ValidMask & isfinite(values) & values > 0);
            if isempty(values)
                values = 1;
            end
            values = sort(double(values(:)));
            percentileIndex = max(1, ceil(0.90 * numel(values)));
            footprint = struct(Median=median(values), ...
                Percentile90=values(percentileIndex), ...
                Minimum=values(1), Maximum=values(end));
        end

        function downsample = chooseDownsample( ...
                sourceFootprint, oversampling, maximumDownsample)
            demand = max(1, sourceFootprint / oversampling);
            exponent = max(0, floor(log2(demand)));
            maximumExponent = floor(log2(maximumDownsample));
            downsample = 2 ^ min(exponent, maximumExponent);
        end

        function region = planRegion(mapping, imageSize, downsample, alignment)
            validRows = mapping.RowCoordinates(mapping.ValidMask);
            validColumns = mapping.ColumnCoordinates(mapping.ValidMask);
            if isempty(validRows)
                rowRange = [1 1];
                columnRange = [1 1];
            else
                halo = max(2, 2 * downsample);
                rowRange = [floor(min(validRows)) - halo, ...
                    ceil(max(validRows)) + halo];
                columnRange = [floor(min(validColumns)) - halo, ...
                    ceil(max(validColumns)) + halo];
                block = max(alignment, downsample);
                rowRange = [floor((rowRange(1) - 1) / block) * block + 1, ...
                    ceil(rowRange(2) / block) * block];
                columnRange = [ ...
                    floor((columnRange(1) - 1) / block) * block + 1, ...
                    ceil(columnRange(2) / block) * block];
                rowRange = min(max(rowRange, 1), imageSize(1));
                columnRange = min(max(columnRange, 1), imageSize(2));
            end
            region = struct(RowRange=double(rowRange), ...
                ColumnRange=double(columnRange), ...
                PixelCount=double(diff(rowRange) + 1) * ...
                double(diff(columnRange) + 1));
        end

        function identity = identity( ...
                layer, provider, bandIndex, region, downsample, options)
            sourceRevision = ProjectionGeometryFingerprint.sourceRevisionStatus( ...
                layer.SourceGeometry);
            geometryToken = sourceRevision.Token;
            if strlength(geometryToken) == 0
                geometryToken = ProjectionGeometryFingerprint.layer(layer);
            end
            identity = struct(Format="ProjectionAnalysisSourceLevelKey", ...
                Version=1, LayerId=string(layer.LayerId), ...
                GeometryRevision=geometryToken, SourceKind=provider.Kind, ...
                SourcePath=provider.Path, ImageSize=double(provider.ImageSize), ...
                ImageClass=provider.SourceClass, ...
                MemoryGeneration=ProjectionAnalysisSourceCache.memoryGeneration(layer), ...
                BandIndex=bandIndex, NodataPolicy=options.NodataPolicy, ...
                LevelDownsample=downsample, ...
                ReductionVersion=ProjectionAnalysisSourceCache.ReductionVersion, ...
                Region=region, RadiometricOption=options.RadiometricOption);
        end

        function generation = memoryGeneration(layer)
            generation = "unspecified";
            for name = ["ImageGeneration" "SourceGeneration" ...
                    "SourceRevision" "Revision"]
                if isfield(layer, name)
                    generation = string(layer.(name));
                    return
                end
            end
        end

        function [entry, work] = buildEntry( ...
                provider, bandIndex, region, downsample, options)
            if downsample > 1 && ...
                    region.PixelCount > options.MaximumMaterializationPixels
                [entry, work] = ...
                    ProjectionAnalysisSourceCache.buildTiledEntry( ...
                    provider, bandIndex, region, downsample, options);
                return
            end
            readTimer = tic;
            rows = region.RowRange(1):region.RowRange(2);
            columns = region.ColumnRange(1):region.ColumnRange(2);
            if provider.Kind == "memory"
                sourceBand = provider.Image(rows, columns, bandIndex);
            else
                sourceImage = imread(provider.Path, ...
                    PixelRegion={region.RowRange, region.ColumnRange});
                sourceBand = sourceImage(:, :, bandIndex);
            end
            sourceReadSeconds = toc(readTimer);
            sourcePixelsRead = numel(sourceBand);
            sourceBytesRead = sourcePixelsRead * ...
                ProjectionAnalysisSourceCache.bytesPerElement(class(sourceBand));

            validityTimer = tic;
            sourceBand = double(sourceBand);
            sourceValid = isfinite(sourceBand);
            sourceBand(~sourceValid) = 0;
            validitySeconds = toc(validityTimer);

            pyramidTimer = tic;
            if downsample > 1
                targetSize = max(1, round(size(sourceBand, [1 2]) / downsample));
                weights = imresize(double(sourceValid), targetSize, "box", ...
                    Antialiasing=true);
                weighted = imresize(sourceBand .* double(sourceValid), ...
                    targetSize, "box", Antialiasing=true);
                levelImage = zeros(targetSize);
                positive = weights > eps;
                levelImage(positive) = weighted(positive) ./ weights(positive);
                levelValid = weights >= options.MinimumValidityWeight;
            else
                weights = double(sourceValid);
                levelImage = sourceBand;
                levelValid = sourceValid;
            end
            levelImage(~levelValid) = 0;
            pyramidSeconds = toc(pyramidTimer);
            entry = struct(Image=levelImage, ValidMask=logical(levelValid), ...
                ValidityWeights=weights, Region=region, ...
                Downsample=downsample, SourceRegionSize=size(sourceBand, [1 2]), ...
                LevelSize=size(levelImage, [1 2]));
            work = struct(SourceReadSeconds=sourceReadSeconds, ...
                PyramidSeconds=pyramidSeconds, ...
                ValiditySeconds=validitySeconds, ...
                SourceReadCount=1, ...
                SourcePixelsRead=sourcePixelsRead, ...
                SourceBytesRead=sourceBytesRead);
        end

        function [entry, work] = buildTiledEntry( ...
                provider, bandIndex, region, downsample, options)
            sourceSize = [diff(region.RowRange) + 1 ...
                diff(region.ColumnRange) + 1];
            levelSize = ceil(sourceSize / downsample);
            levelImage = zeros(levelSize);
            levelValid = false(levelSize);
            weights = zeros(levelSize);
            outputTileSide = max(1, floor( ...
                sqrt(options.MaximumMaterializationPixels) / downsample));
            work = struct(SourceReadSeconds=0, PyramidSeconds=0, ...
                ValiditySeconds=0, SourceReadCount=0, ...
                SourcePixelsRead=0, SourceBytesRead=0);
            for outputRowStart = 1:outputTileSide:levelSize(1)
                outputRowEnd = min(levelSize(1), ...
                    outputRowStart + outputTileSide - 1);
                sourceRowRange = [ ...
                    region.RowRange(1) + ...
                    (outputRowStart - 1) * downsample, ...
                    min(region.RowRange(2), region.RowRange(1) - 1 + ...
                    outputRowEnd * downsample)];
                for outputColumnStart = 1:outputTileSide:levelSize(2)
                    outputColumnEnd = min(levelSize(2), ...
                        outputColumnStart + outputTileSide - 1);
                    sourceColumnRange = [ ...
                        region.ColumnRange(1) + ...
                        (outputColumnStart - 1) * downsample, ...
                        min(region.ColumnRange(2), ...
                        region.ColumnRange(1) - 1 + ...
                        outputColumnEnd * downsample)];
                    readTimer = tic;
                    nativeTile = ProjectionAnalysisSourceCache.readSource( ...
                        provider, bandIndex, sourceRowRange, sourceColumnRange);
                    work.SourceReadSeconds = work.SourceReadSeconds + ...
                        toc(readTimer);
                    work.SourceReadCount = work.SourceReadCount + 1;
                    work.SourcePixelsRead = work.SourcePixelsRead + ...
                        numel(nativeTile);
                    work.SourceBytesRead = work.SourceBytesRead + ...
                        numel(nativeTile) * ...
                        ProjectionAnalysisSourceCache.bytesPerElement( ...
                        class(nativeTile));
                    validityTimer = tic;
                    sourceTile = double(nativeTile);
                    sourceValid = isfinite(sourceTile);
                    sourceTile(~sourceValid) = 0;
                    work.ValiditySeconds = work.ValiditySeconds + ...
                        toc(validityTimer);
                    targetSize = [outputRowEnd - outputRowStart + 1 ...
                        outputColumnEnd - outputColumnStart + 1];
                    pyramidTimer = tic;
                    tileWeights = imresize(double(sourceValid), ...
                        targetSize, "box", Antialiasing=true);
                    weighted = imresize(sourceTile .* double(sourceValid), ...
                        targetSize, "box", Antialiasing=true);
                    tileImage = zeros(targetSize);
                    positive = tileWeights > eps;
                    tileImage(positive) = ...
                        weighted(positive) ./ tileWeights(positive);
                    tileValid = tileWeights >= options.MinimumValidityWeight;
                    tileImage(~tileValid) = 0;
                    work.PyramidSeconds = work.PyramidSeconds + ...
                        toc(pyramidTimer);
                    outputRows = outputRowStart:outputRowEnd;
                    outputColumns = outputColumnStart:outputColumnEnd;
                    levelImage(outputRows, outputColumns) = tileImage;
                    levelValid(outputRows, outputColumns) = tileValid;
                    weights(outputRows, outputColumns) = tileWeights;
                end
            end
            entry = struct(Image=levelImage, ValidMask=levelValid, ...
                ValidityWeights=weights, Region=region, ...
                Downsample=downsample, SourceRegionSize=sourceSize, ...
                LevelSize=levelSize);
        end

        function nativeImage = readSource( ...
                provider, bandIndex, rowRange, columnRange)
            if provider.Kind == "memory"
                nativeImage = provider.Image( ...
                    rowRange(1):rowRange(2), ...
                    columnRange(1):columnRange(2), bandIndex);
            else
                sourceImage = imread(provider.Path, ...
                    PixelRegion={rowRange, columnRange});
                nativeImage = sourceImage(:, :, bandIndex);
            end
        end

        function mapping = levelMapping(fullMapping, entry)
            mapping = fullMapping;
            regionalRows = fullMapping.RowCoordinates - ...
                entry.Region.RowRange(1) + 1;
            regionalColumns = fullMapping.ColumnCoordinates - ...
                entry.Region.ColumnRange(1) + 1;
            rowScale = entry.LevelSize(1) / entry.SourceRegionSize(1);
            columnScale = entry.LevelSize(2) / entry.SourceRegionSize(2);
            mapping.RowCoordinates = (regionalRows - 0.5) * rowScale + 0.5;
            mapping.ColumnCoordinates = ...
                (regionalColumns - 0.5) * columnScale + 0.5;
            mapping.ImageSize = entry.LevelSize;
            mapping.ValidMask = fullMapping.ValidMask;
        end

        function count = bytesPerElement(className)
            switch className
                case {"logical", "uint8", "int8"}
                    count = 1;
                case {"uint16", "int16"}
                    count = 2;
                case {"uint32", "int32", "single"}
                    count = 4;
                otherwise
                    count = 8;
            end
        end

        function totals = emptyTotals()
            totals = struct(CacheHits=0, CacheMisses=0, ...
                SourceReadCount=0, PyramidBuildCount=0, ...
                SourcePixelsRead=0, SourceBytesRead=0, ...
                PlanningSeconds=0, CacheLookupSeconds=0, ...
                SourceReadSeconds=0, PyramidSeconds=0, ...
                ValiditySeconds=0, ResampleSeconds=0);
        end
    end
end
