classdef ProjectionDenseSurfaceSyntheticConfig
    %ProjectionDenseSurfaceSyntheticConfig Load and validate synthetic-fixture configuration.

    properties (Constant)
        SchemaVersion = 1
    end

    methods (Static)
        function [config, context] = load(filePath)
            %load Read a JSON configuration and resolve its runtime paths.
            filePath = ProjectionDenseSurfaceSyntheticConfig.scalarText( ...
                filePath, "filePath");
            if ~isfile(filePath)
                error("ProjectionDenseSurfaceSyntheticConfig:fileNotFound", ...
                    "Synthetic fixture configuration does not exist: %s", filePath);
            end

            try
                config = jsondecode(fileread(filePath));
            catch exception
                error("ProjectionDenseSurfaceSyntheticConfig:invalidJson", ...
                    "Synthetic fixture configuration is not valid JSON: %s", ...
                    exception.message);
            end
            config = ProjectionDenseSurfaceSyntheticConfig.validate(config);

            configPath = string(filePath);
            configDirectory = string(fileparts(configPath));
            projectRoot = string(fileparts(configDirectory));
            sourceImagePath = ProjectionDenseSurfaceSyntheticConfig.resolvePath( ...
                projectRoot, config.fixture.source_image_path);
            if ~isfile(sourceImagePath)
                error("ProjectionDenseSurfaceSyntheticConfig:sourceImageNotFound", ...
                    "Configured source image does not exist relative to the project root.");
            end
            outputDirectory = ProjectionDenseSurfaceSyntheticConfig.resolvePath( ...
                projectRoot, config.output.directory);
            context = struct(ConfigPath=configPath, ProjectRoot=projectRoot, ...
                SourceImagePath=sourceImagePath, OutputDirectory=outputDirectory);
        end

        function config = validate(config)
            %validate Enforce the complete committed schema and semantic contract.
            template = ProjectionDenseSurfaceSyntheticConfig.loadTemplate();
            ProjectionDenseSurfaceSyntheticConfig.validateStructure( ...
                config, template, "configuration");

            config.schema_version = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                config.schema_version, "schema_version");
            if config.schema_version ~= ...
                    ProjectionDenseSurfaceSyntheticConfig.SchemaVersion
                error("ProjectionDenseSurfaceSyntheticConfig:unsupportedVersion", ...
                    "schema_version must be %d.", ...
                    ProjectionDenseSurfaceSyntheticConfig.SchemaVersion);
            end

            config = ProjectionDenseSurfaceSyntheticConfig.validateFixture(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateImage(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateFrames(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validatePlatform(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateGimbal(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validatePlanner(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateSampling(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateTerrain(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateTurbulence(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateNavigation(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateAcceptance(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateOutput(config);
            config = ProjectionDenseSurfaceSyntheticConfig.validateFuture(config);
        end
    end

    methods (Static, Access = private)
        function template = loadTemplate()
            sourceDirectory = string(fileparts(mfilename("fullpath")));
            templatePath = fullfile(fileparts(sourceDirectory), "config", ...
                "dense_surface_synthetic.template.json");
            template = jsondecode(fileread(templatePath));
        end

        function validateStructure(value, template, path)
            if ~isstruct(template)
                if isempty(value)
                    error("ProjectionDenseSurfaceSyntheticConfig:missingValue", ...
                        "%s must not be null or empty.", path);
                end
                return
            end
            if ~isstruct(value) || ~isscalar(value)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidStructure", ...
                    "%s must be a JSON object.", path);
            end
            expected = sort(string(fieldnames(template)));
            actual = sort(string(fieldnames(value)));
            if ~isequal(expected, actual)
                error("ProjectionDenseSurfaceSyntheticConfig:schemaMismatch", ...
                    "%s fields must match the committed template exactly.", path);
            end
            names = fieldnames(template);
            for fieldIndex = 1:numel(names)
                name = names{fieldIndex};
                ProjectionDenseSurfaceSyntheticConfig.validateStructure( ...
                    value.(name), template.(name), path + "." + name);
            end
        end

        function config = validateFixture(config)
            fixture = config.fixture;
            fixture.source_image_path = ...
                ProjectionDenseSurfaceSyntheticConfig.scalarText( ...
                fixture.source_image_path, "fixture.source_image_path");
            fixture.reserved_source_image_paths = ...
                ProjectionDenseSurfaceSyntheticConfig.textVector( ...
                fixture.reserved_source_image_paths, ...
                "fixture.reserved_source_image_paths");
            fixture.random_seed = ...
                ProjectionDenseSurfaceSyntheticConfig.nonnegativeInteger( ...
                fixture.random_seed, "fixture.random_seed");
            config.fixture = fixture;
        end

        function config = validateImage(config)
            image = config.image;
            image.rows = ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                image.rows, "image.rows", 2);
            image.columns = ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                image.columns, "image.columns", 2);
            image.view_count = ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                image.view_count, "image.view_count", 2);
            image.instantaneous_line_axis = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                image.instantaneous_line_axis, "image.instantaneous_line_axis", ...
                "rows");
            image.scan_axis = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                image.scan_axis, "image.scan_axis", "columns");
            image.scan_rate_lines_per_second = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                image.scan_rate_lines_per_second, ...
                "image.scan_rate_lines_per_second");
            image.cross_track_fov_degrees = ...
                ProjectionDenseSurfaceSyntheticConfig.openRangeScalar( ...
                image.cross_track_fov_degrees, "image.cross_track_fov_degrees", ...
                0, 90);
            image.focal_length_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                image.focal_length_meters, "image.focal_length_meters");
            image.source_band_sequence = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveIntegerVector( ...
                image.source_band_sequence, "image.source_band_sequence");
            if numel(image.source_band_sequence) ~= image.view_count
                error("ProjectionDenseSurfaceSyntheticConfig:invalidBandSequence", ...
                    "image.source_band_sequence must contain one band per view.");
            end
            config.image = image;
        end

        function config = validateFrames(config)
            frame = config.world_frame;
            frame.x_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.x_axis_definition, "world_frame.x_axis_definition", ...
                "nominal-flight-forward");
            frame.y_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.y_axis_definition, "world_frame.y_axis_definition", ...
                "right-of-flight");
            frame.z_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.z_axis_definition, "world_frame.z_axis_definition", "up");
            frame.platform_x_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.platform_x_axis_definition, ...
                "world_frame.platform_x_axis_definition", "nose-forward");
            frame.platform_y_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.platform_y_axis_definition, ...
                "world_frame.platform_y_axis_definition", "right-wing");
            frame.platform_z_axis_definition = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                frame.platform_z_axis_definition, ...
                "world_frame.platform_z_axis_definition", "down");
            config.world_frame = frame;
        end

        function config = validatePlatform(config)
            platform = config.platform;
            platform.height_above_ground_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                platform.height_above_ground_meters, ...
                "platform.height_above_ground_meters");
            platform.forward_velocity_meters_per_second = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                platform.forward_velocity_meters_per_second, ...
                "platform.forward_velocity_meters_per_second");
            platform.nominal_off_nadir_degrees = ...
                ProjectionDenseSurfaceSyntheticConfig.openRangeScalar( ...
                platform.nominal_off_nadir_degrees, ...
                "platform.nominal_off_nadir_degrees", 0, 89);
            platform.target_side = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                platform.target_side, "platform.target_side", ["left" "right"]);
            config.platform = platform;
        end

        function config = validateGimbal(config)
            gimbal = config.gimbal;
            gimbal.zero_boresight_axis = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                gimbal.zero_boresight_axis, "gimbal.zero_boresight_axis", ...
                "platform-positive-z");
            gimbal.rotation_order = ...
                ProjectionDenseSurfaceSyntheticConfig.textVector( ...
                gimbal.rotation_order, "gimbal.rotation_order");
            if ~isequal(gimbal.rotation_order, ["roll" "pitch"])
                error("ProjectionDenseSurfaceSyntheticConfig:invalidGimbal", ...
                    "gimbal.rotation_order must be roll followed by pitch.");
            end
            gimbal.roll_axis = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                gimbal.roll_axis, "gimbal.roll_axis", "platform-positive-x");
            gimbal.pitch_axis = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                gimbal.pitch_axis, "gimbal.pitch_axis", ...
                "roll-gimbal-positive-y");
            gimbal.positive_rotation_convention = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                gimbal.positive_rotation_convention, ...
                "gimbal.positive_rotation_convention", "right-hand");
            gimbal.pitch_field_of_regard_degrees = ...
                ProjectionDenseSurfaceSyntheticConfig.increasingPair( ...
                gimbal.pitch_field_of_regard_degrees, ...
                "gimbal.pitch_field_of_regard_degrees");
            if any(gimbal.pitch_field_of_regard_degrees <= -89) || ...
                    any(gimbal.pitch_field_of_regard_degrees >= 89)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidGimbal", ...
                    "The pitch field of regard must remain between -89 and 89 degrees.");
            end
            gimbal.maximum_initial_forward_pitch_degrees = ...
                ProjectionDenseSurfaceSyntheticConfig.nonnegativeScalar( ...
                gimbal.maximum_initial_forward_pitch_degrees, ...
                "gimbal.maximum_initial_forward_pitch_degrees");
            if gimbal.maximum_initial_forward_pitch_degrees > ...
                    gimbal.pitch_field_of_regard_degrees(2)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidGimbal", ...
                    "Maximum initial forward pitch must not exceed the upper pitch limit.");
            end
            gimbal.ideal_encoder_and_mounting = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                gimbal.ideal_encoder_and_mounting, ...
                "gimbal.ideal_encoder_and_mounting");
            if ~gimbal.ideal_encoder_and_mounting
                error("ProjectionDenseSurfaceSyntheticConfig:invalidGimbal", ...
                    "The first fixture requires ideal gimbal encoders and mounting.");
            end
            config.gimbal = gimbal;
        end

        function config = validatePlanner(config)
            planner = config.collection_planner;
            planner.desired_scene_center_separation_degrees = ...
                ProjectionDenseSurfaceSyntheticConfig.openRangeScalar( ...
                planner.desired_scene_center_separation_degrees, ...
                "collection_planner.desired_scene_center_separation_degrees", ...
                0, 90);
            planner.allow_separation_expansion = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                planner.allow_separation_expansion, ...
                "collection_planner.allow_separation_expansion");
            planner.constant_inter_image_gap = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                planner.constant_inter_image_gap, ...
                "collection_planner.constant_inter_image_gap");
            planner.retrace_time_seconds = ...
                ProjectionDenseSurfaceSyntheticConfig.nonnegativeScalar( ...
                planner.retrace_time_seconds, ...
                "collection_planner.retrace_time_seconds");
            planner.minimum_slant_range_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                planner.minimum_slant_range_meters, ...
                "collection_planner.minimum_slant_range_meters");
            planner.maximum_slant_range_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                planner.maximum_slant_range_meters, ...
                "collection_planner.maximum_slant_range_meters");
            if planner.minimum_slant_range_meters >= ...
                    planner.maximum_slant_range_meters
                error("ProjectionDenseSurfaceSyntheticConfig:invalidRangeEnvelope", ...
                    "The minimum slant range must be less than the maximum.");
            end
            planner.stop_for_user_on_infeasible_geometry = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                planner.stop_for_user_on_infeasible_geometry, ...
                "collection_planner.stop_for_user_on_infeasible_geometry");
            if ~planner.constant_inter_image_gap
                error("ProjectionDenseSurfaceSyntheticConfig:invalidSchedule", ...
                    "The approved fixture requires a constant inter-image gap.");
            end
            config.collection_planner = planner;
        end

        function config = validateSampling(config)
            sampling = config.sampling;
            sampling.maximum_oversampling_per_axis = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                sampling.maximum_oversampling_per_axis, ...
                "sampling.maximum_oversampling_per_axis");
            sampling.derive_range = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                sampling.derive_range, "sampling.derive_range");
            sampling.minimum_reflection_tiles_rows = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                sampling.minimum_reflection_tiles_rows, ...
                "sampling.minimum_reflection_tiles_rows");
            sampling.minimum_reflection_tiles_columns = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                sampling.minimum_reflection_tiles_columns, ...
                "sampling.minimum_reflection_tiles_columns");
            sampling.maximum_reflection_tiles_rows = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                sampling.maximum_reflection_tiles_rows, ...
                "sampling.maximum_reflection_tiles_rows");
            sampling.maximum_reflection_tiles_columns = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                sampling.maximum_reflection_tiles_columns, ...
                "sampling.maximum_reflection_tiles_columns");
            sampling.prefer_odd_tile_counts = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                sampling.prefer_odd_tile_counts, ...
                "sampling.prefer_odd_tile_counts");
            sampling.logical_reflection_addressing = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                sampling.logical_reflection_addressing, ...
                "sampling.logical_reflection_addressing");
            if sampling.minimum_reflection_tiles_rows > ...
                    sampling.maximum_reflection_tiles_rows || ...
                    sampling.minimum_reflection_tiles_columns > ...
                    sampling.maximum_reflection_tiles_columns
                error("ProjectionDenseSurfaceSyntheticConfig:invalidTileLimits", ...
                    "Minimum reflected-tile counts must not exceed their maxima.");
            end
            if ~sampling.derive_range || ~sampling.logical_reflection_addressing
                error("ProjectionDenseSurfaceSyntheticConfig:invalidSampling", ...
                    "The approved fixture requires derived range and logical reflection.");
            end
            config.sampling = sampling;
        end

        function config = validateTerrain(config)
            terrain = config.terrain;
            terrain.model = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                terrain.model, "terrain.model", ...
                "asymmetric-windowed-radial-sinc-composite");
            terrain.minimum_height_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.finiteScalar( ...
                terrain.minimum_height_meters, "terrain.minimum_height_meters");
            terrain.maximum_height_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.finiteScalar( ...
                terrain.maximum_height_meters, "terrain.maximum_height_meters");
            if terrain.minimum_height_meters >= terrain.maximum_height_meters
                error("ProjectionDenseSurfaceSyntheticConfig:invalidTerrain", ...
                    "terrain.minimum_height_meters must be less than the maximum.");
            end
            terrain.characteristic_lengths_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveVector( ...
                terrain.characteristic_lengths_meters, ...
                "terrain.characteristic_lengths_meters");
            terrain.asymmetry_weights = ...
                ProjectionDenseSurfaceSyntheticConfig.finiteVector( ...
                terrain.asymmetry_weights, "terrain.asymmetry_weights");
            if numel(terrain.characteristic_lengths_meters) ~= ...
                    numel(terrain.asymmetry_weights)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidTerrain", ...
                    "Terrain length and asymmetry vectors must have equal length.");
            end
            terrain.require_occlusion = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                terrain.require_occlusion, "terrain.require_occlusion");
            config.terrain = terrain;
        end

        function config = validateTurbulence(config)
            turbulence = config.truth_turbulence;
            turbulence.model = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                turbulence.model, "truth_turbulence.model", ...
                "deterministic-gauss-markov");
            turbulence.position_rms_meters_per_axis = ...
                ProjectionDenseSurfaceSyntheticConfig.nonnegativeScalar( ...
                turbulence.position_rms_meters_per_axis, ...
                "truth_turbulence.position_rms_meters_per_axis");
            turbulence.attitude_rms_degrees_per_axis = ...
                ProjectionDenseSurfaceSyntheticConfig.nonnegativeScalar( ...
                turbulence.attitude_rms_degrees_per_axis, ...
                "truth_turbulence.attitude_rms_degrees_per_axis");
            turbulence.correlation_time_seconds = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                turbulence.correlation_time_seconds, ...
                "truth_turbulence.correlation_time_seconds");
            config.truth_turbulence = turbulence;
        end

        function config = validateNavigation(config)
            navigation = config.navigation;
            navigation.aiding_mode = ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                navigation.aiding_mode, "navigation.aiding_mode", ...
                "nominal-non-rtk-gnss");
            navigation.bias_draw_scope = ...
                ProjectionDenseSurfaceSyntheticConfig.enumText( ...
                navigation.bias_draw_scope, "navigation.bias_draw_scope", ...
                "one-sortie");
            gnss = navigation.gnss;
            gnss.class = ProjectionDenseSurfaceSyntheticConfig.scalarText( ...
                gnss.class, "navigation.gnss.class");
            gnss.update_rate_hz = ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                gnss.update_rate_hz, "navigation.gnss.update_rate_hz");
            gnss.horizontal_position_sigma_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                gnss.horizontal_position_sigma_meters, ...
                "navigation.gnss.horizontal_position_sigma_meters");
            gnss.vertical_position_sigma_meters = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                gnss.vertical_position_sigma_meters, ...
                "navigation.gnss.vertical_position_sigma_meters");
            gnss.velocity_sigma_meters_per_second = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                gnss.velocity_sigma_meters_per_second, ...
                "navigation.gnss.velocity_sigma_meters_per_second");
            gnss.correlation_time_seconds = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                gnss.correlation_time_seconds, ...
                "navigation.gnss.correlation_time_seconds");
            navigation.gnss = gnss;
            navigation.presets.tactical_grade_imu = ...
                ProjectionDenseSurfaceSyntheticConfig.validateImuPreset( ...
                navigation.presets.tactical_grade_imu, ...
                "navigation.presets.tactical_grade_imu");
            navigation.presets.navigation_grade_imu = ...
                ProjectionDenseSurfaceSyntheticConfig.validateImuPreset( ...
                navigation.presets.navigation_grade_imu, ...
                "navigation.presets.navigation_grade_imu");
            config.navigation = navigation;
        end

        function preset = validateImuPreset(preset, path)
            preset.gyro_bias_sigma_degrees_per_hour = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                preset.gyro_bias_sigma_degrees_per_hour, ...
                path + ".gyro_bias_sigma_degrees_per_hour");
            preset.gyro_angle_random_walk_degrees_per_sqrt_hour = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                preset.gyro_angle_random_walk_degrees_per_sqrt_hour, ...
                path + ".gyro_angle_random_walk_degrees_per_sqrt_hour");
            preset.accelerometer_bias_sigma_mg = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                preset.accelerometer_bias_sigma_mg, ...
                path + ".accelerometer_bias_sigma_mg");
            preset.accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour = ...
                ProjectionDenseSurfaceSyntheticConfig.positiveScalar( ...
                preset.accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour, ...
                path + ".accelerometer_velocity_random_walk_meters_per_second_per_sqrt_hour");
        end

        function config = validateAcceptance(config)
            acceptance = config.acceptance;
            acceptance.modes = ProjectionDenseSurfaceSyntheticConfig.textVector( ...
                acceptance.modes, "acceptance.modes");
            requiredModes = ["pointing-only" "combined-navigation-error"];
            if ~isequal(sort(acceptance.modes), sort(requiredModes))
                error("ProjectionDenseSurfaceSyntheticConfig:invalidAcceptance", ...
                    "acceptance.modes must contain the two approved variants.");
            end
            acceptance.establish_thresholds_after_first_full_scale_baseline = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                acceptance.establish_thresholds_after_first_full_scale_baseline, ...
                "acceptance.establish_thresholds_after_first_full_scale_baseline");
            acceptance.record_metrics = ...
                ProjectionDenseSurfaceSyntheticConfig.textVector( ...
                acceptance.record_metrics, "acceptance.record_metrics");
            config.acceptance = acceptance;
        end

        function config = validateOutput(config)
            output = config.output;
            output.directory = ProjectionDenseSurfaceSyntheticConfig.scalarText( ...
                output.directory, "output.directory");
            output.default_image_format = lower( ...
                ProjectionDenseSurfaceSyntheticConfig.scalarText( ...
                output.default_image_format, "output.default_image_format"));
            output.supported_image_formats = lower( ...
                ProjectionDenseSurfaceSyntheticConfig.textVector( ...
                output.supported_image_formats, "output.supported_image_formats"));
            if ~all(ismember(output.supported_image_formats, ["tiff" "png"])) || ...
                    ~ismember(output.default_image_format, ...
                    output.supported_image_formats)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidOutput", ...
                    "Output formats must be TIFF/PNG and include the default.");
            end
            output.preserve_source_integer_class = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                output.preserve_source_integer_class, ...
                "output.preserve_source_integer_class");
            output.write_compact_mat_truth = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                output.write_compact_mat_truth, "output.write_compact_mat_truth");
            output.write_json_run_summary = ...
                ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                output.write_json_run_summary, "output.write_json_run_summary");
            config.output = output;
        end

        function config = validateFuture(config)
            future = config.future;
            names = fieldnames(future);
            for fieldIndex = 1:numel(names)
                name = names{fieldIndex};
                future.(name) = ...
                    ProjectionDenseSurfaceSyntheticConfig.logicalScalar( ...
                    future.(name), "future." + name);
            end
            config.future = future;
        end

        function value = resolvePath(baseDirectory, value)
            value = string(value);
            isAbsolute = startsWith(value, string(filesep)) || ...
                ~isempty(regexp(char(value), "^[A-Za-z]:[\\\\/]", "once"));
            if ~isAbsolute
                value = string(fullfile(baseDirectory, value));
            end
        end

        function value = enumText(value, name, allowed)
            value = ProjectionDenseSurfaceSyntheticConfig.scalarText(value, name);
            if ~ismember(value, string(allowed))
                error("ProjectionDenseSurfaceSyntheticConfig:invalidValue", ...
                    "%s has an unsupported value.", name);
            end
        end

        function value = scalarText(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || strlength(value) == 0
                error("ProjectionDenseSurfaceSyntheticConfig:invalidText", ...
                    "%s must be a nonempty scalar string.", name);
            end
        end

        function value = textVector(value, name)
            value = string(value(:).');
            if isempty(value) || any(ismissing(value)) || any(strlength(value) == 0)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidText", ...
                    "%s must be a nonempty string vector.", name);
            end
        end

        function value = finiteScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidNumber", ...
                    "%s must be a finite numeric scalar.", name);
            end
            value = double(value);
        end

        function value = positiveScalar(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.finiteScalar(value, name);
            if value <= 0
                error("ProjectionDenseSurfaceSyntheticConfig:invalidNumber", ...
                    "%s must be positive.", name);
            end
        end

        function value = nonnegativeScalar(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.finiteScalar(value, name);
            if value < 0
                error("ProjectionDenseSurfaceSyntheticConfig:invalidNumber", ...
                    "%s must be nonnegative.", name);
            end
        end

        function value = openRangeScalar(value, name, minimum, maximum)
            value = ProjectionDenseSurfaceSyntheticConfig.finiteScalar(value, name);
            if value <= minimum || value >= maximum
                error("ProjectionDenseSurfaceSyntheticConfig:invalidNumber", ...
                    "%s must be greater than %g and less than %g.", ...
                    name, minimum, maximum);
            end
        end

        function value = positiveInteger(value, name, minimum)
            if nargin < 3
                minimum = 1;
            end
            value = ProjectionDenseSurfaceSyntheticConfig.finiteScalar(value, name);
            if value < minimum || fix(value) ~= value
                error("ProjectionDenseSurfaceSyntheticConfig:invalidInteger", ...
                    "%s must be an integer greater than or equal to %d.", ...
                    name, minimum);
            end
        end

        function value = nonnegativeInteger(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.positiveInteger( ...
                value, name, 0);
        end

        function value = finiteVector(value, name)
            if ~isnumeric(value) || isempty(value) || ~isvector(value) || ...
                    any(~isfinite(value))
                error("ProjectionDenseSurfaceSyntheticConfig:invalidVector", ...
                    "%s must be a nonempty finite numeric vector.", name);
            end
            value = double(value(:).');
        end

        function value = positiveVector(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.finiteVector(value, name);
            if any(value <= 0)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidVector", ...
                    "%s values must be positive.", name);
            end
        end

        function value = positiveIntegerVector(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.positiveVector(value, name);
            if any(fix(value) ~= value)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidVector", ...
                    "%s values must be positive integers.", name);
            end
        end

        function value = increasingPair(value, name)
            value = ProjectionDenseSurfaceSyntheticConfig.finiteVector(value, name);
            if numel(value) ~= 2 || value(1) >= value(2)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidVector", ...
                    "%s must be a strictly increasing two-element vector.", name);
            end
        end

        function value = logicalScalar(value, name)
            if ~islogical(value) || ~isscalar(value)
                error("ProjectionDenseSurfaceSyntheticConfig:invalidLogical", ...
                    "%s must be a logical scalar.", name);
            end
        end
    end
end
