classdef ProjectionDenseSearchPredictor
    %ProjectionDenseSearchPredictor Build regional sparse-seeded search priors.

    properties (Constant)
        Format = "ProjectionDenseSearchPrediction"
        Version = 1
    end

    methods (Static)
        function prediction = build(request, sparseEvidence, options)
            %build Predict bounded regional search geometry from sparse tracks.
            if nargin < 3
                options = struct();
            end
            request = ProjectionDenseMatchRequest.validate(request);
            options = ProjectionDenseSearchPredictor.validateOptions(options);
            evidence = ProjectionDenseSearchPredictor.validateEvidence( ...
                sparseEvidence, size(request.AnalysisImages{1}));
            imageSize = size(request.AnalysisImages{1});
            rowEdges = ProjectionDenseSearchPredictor.edges( ...
                imageSize(1), options.RegionSize(1));
            columnEdges = ProjectionDenseSearchPredictor.edges( ...
                imageSize(2), options.RegionSize(2));
            globalPrior = ProjectionDenseSearchPredictor.globalPrior( ...
                evidence, options);
            regionCount = (numel(rowEdges) - 1) * (numel(columnEdges) - 1);
            regions = repmat(ProjectionDenseSearchPredictor.emptyRegion(), ...
                1, regionCount);
            regionIndex = 0;
            for rowIndex = 1:(numel(rowEdges) - 1)
                for columnIndex = 1:(numel(columnEdges) - 1)
                    regionIndex = regionIndex + 1;
                    bounds = [columnEdges(columnIndex) ...
                        columnEdges(columnIndex + 1) ...
                        rowEdges(rowIndex) rowEdges(rowIndex + 1)];
                    selected = ProjectionDenseSearchPredictor.seedsInRegion( ...
                        evidence.MovingPoints, bounds);
                    regions(regionIndex) = ...
                        ProjectionDenseSearchPredictor.region( ...
                        bounds, evidence, selected, globalPrior, options);
                end
            end
            prediction = struct( ...
                Format=ProjectionDenseSearchPredictor.Format, ...
                Version=ProjectionDenseSearchPredictor.Version, ...
                PairId=request.PairId, ViewIds=request.ViewIds, ...
                ImageSize=imageSize, RegionSize=options.RegionSize, ...
                GridSize=[numel(rowEdges) - 1 numel(columnEdges) - 1], ...
                SeedCount=size(evidence.MovingPoints, 1), ...
                Regions=regions, GlobalPrior=globalPrior, ...
                AllowsUnseededSearch=options.AllowUnseededSearch, ...
                ForcesSurface=false, TruthUsed=false, ...
                CoordinateConvention=struct( ...
                Points="[column row] working pixels", ...
                Disparity="moving minus reference working pixels", ...
                FullSourceMappingsOwnedByRequest=true));
        end

        function request = attach(request, sparseEvidence, options)
            %attach Return a validated request carrying the prediction.
            if nargin < 3
                options = struct();
            end
            request = ProjectionDenseMatchRequest.validate(request);
            request.SearchPrediction = ProjectionDenseSearchPredictor.build( ...
                request, sparseEvidence, options);
            request = ProjectionDenseMatchRequest.validate(request);
        end

        function options = validateOptions(options)
            %validateOptions Normalize regional search policy.
            if nargin < 1 || isempty(options)
                options = struct();
            end
            defaults = struct(RegionSize=[32 32], MinimumSeedsPerRegion=2, ...
                SeedPaddingPixels=2, UnseededPaddingPixels=12, ...
                AllowUnseededSearch=true, MinimumUncertaintyPixels=0.5);
            if ~isstruct(options) || ~isscalar(options) || ...
                    any(~ismember(string(fieldnames(options)), ...
                    string(fieldnames(defaults))))
                error("ProjectionDenseSearchPredictor:invalidOptions", ...
                    "Search-prediction options contain unsupported fields.");
            end
            names = fieldnames(options);
            for index = 1:numel(names)
                defaults.(names{index}) = options.(names{index});
            end
            defaults.RegionSize = ProjectionDenseSearchPredictor. ...
                positiveIntegerPair(defaults.RegionSize, "RegionSize");
            defaults.MinimumSeedsPerRegion = ProjectionDenseSearchPredictor. ...
                positiveInteger(defaults.MinimumSeedsPerRegion, ...
                "MinimumSeedsPerRegion");
            scalarNames = ["SeedPaddingPixels" "UnseededPaddingPixels" ...
                "MinimumUncertaintyPixels"];
            for name = scalarNames
                defaults.(name) = ProjectionDenseSearchPredictor. ...
                    nonnegativeScalar(defaults.(name), name);
            end
            if ~islogical(defaults.AllowUnseededSearch) || ...
                    ~isscalar(defaults.AllowUnseededSearch)
                error("ProjectionDenseSearchPredictor:invalidOptions", ...
                    "AllowUnseededSearch must be a logical scalar.");
            end
            options = defaults;
        end
    end

    methods (Static, Access = private)
        function evidence = validateEvidence(evidence, imageSize)
            if ~isstruct(evidence) || ~isscalar(evidence)
                error("ProjectionDenseSearchPredictor:invalidEvidence", ...
                    "Sparse evidence must be a scalar struct.");
            end
            if isfield(evidence, "MovingFeatureLocations")
                evidence.MovingPoints = evidence.MovingFeatureLocations;
            end
            if isfield(evidence, "ReferenceFeatureLocations")
                evidence.ReferencePoints = evidence.ReferenceFeatureLocations;
            end
            required = ["MovingPoints" "ReferencePoints"];
            if any(~isfield(evidence, required))
                error("ProjectionDenseSearchPredictor:invalidEvidence", ...
                    "Sparse evidence requires moving and reference points.");
            end
            moving = double(evidence.MovingPoints);
            reference = double(evidence.ReferencePoints);
            if ~ismatrix(moving) || size(moving, 2) ~= 2 || ...
                    ~isequal(size(moving), size(reference)) || ...
                    any(~isfinite(moving), "all") || ...
                    any(~isfinite(reference), "all") || ...
                    any(moving(:, 1) < 1 | moving(:, 1) > imageSize(2)) || ...
                    any(moving(:, 2) < 1 | moving(:, 2) > imageSize(1))
                error("ProjectionDenseSearchPredictor:invalidEvidence", ...
                    "Sparse working points must be finite matching Nx2 arrays.");
            end
            count = size(moving, 1);
            trackIds = "seed-" + compose("%06d", (1:count).');
            if isfield(evidence, "TrackIds")
                trackIds = string(evidence.TrackIds(:));
            end
            if numel(trackIds) ~= count || any(ismissing(trackIds)) || ...
                    any(strlength(trackIds) == 0) || ...
                    numel(unique(trackIds)) ~= count
                error("ProjectionDenseSearchPredictor:invalidEvidence", ...
                    "TrackIds must uniquely identify every sparse seed.");
            end
            depth = nan(count, 1);
            if isfield(evidence, "DepthMeters")
                depth = double(evidence.DepthMeters(:));
            end
            uncertainty = zeros(count, 1);
            if isfield(evidence, "UncertaintyPixels")
                uncertainty = double(evidence.UncertaintyPixels(:));
            end
            if numel(depth) ~= count || numel(uncertainty) ~= count || ...
                    any(isinf(depth)) || ...
                    any(~isfinite(uncertainty)) || any(uncertainty < 0)
                error("ProjectionDenseSearchPredictor:invalidEvidence", ...
                    "Depth and uncertainty must provide one valid value per seed.");
            end
            evidence = struct(MovingPoints=moving, ...
                ReferencePoints=reference, TrackIds=trackIds, ...
                DepthMeters=depth, UncertaintyPixels=uncertainty);
        end

        function edges = edges(maximum, regionSize)
            edges = [1 (1 + regionSize):regionSize:maximum maximum + 1];
            edges = unique(edges, "stable");
        end

        function selected = seedsInRegion(points, bounds)
            selected = points(:, 1) >= bounds(1) & ...
                points(:, 1) < bounds(2) & points(:, 2) >= bounds(3) & ...
                points(:, 2) < bounds(4);
        end

        function prior = globalPrior(evidence, options)
            if isempty(evidence.MovingPoints)
                prior = struct(State="noSupport", ...
                    DisparityVectorPixels=[NaN NaN], ...
                    EpipolarDirection=[NaN NaN], ...
                    HorizontalSearchRangePixels=[NaN NaN], ...
                    VerticalSearchRangePixels=[NaN NaN], ...
                    DepthRangeMeters=[NaN NaN], ...
                    UncertaintyPixels=NaN, ...
                    SupportingTrackIds=strings(0, 1));
                return
            end
            selected = true(size(evidence.MovingPoints, 1), 1);
            prior = ProjectionDenseSearchPredictor.seededPrior( ...
                evidence, selected, options.UnseededPaddingPixels, options);
            prior.State = "globalSeeded";
            prior.SupportingTrackIds = strings(0, 1);
        end

        function region = region( ...
                bounds, evidence, selected, globalPrior, options)
            seedCount = nnz(selected);
            region = ProjectionDenseSearchPredictor.emptyRegion();
            region.Bounds = bounds;
            region.Center = [mean(bounds(1:2)) mean(bounds(3:4))];
            region.SeedCount = seedCount;
            if seedCount >= options.MinimumSeedsPerRegion
                prior = ProjectionDenseSearchPredictor.seededPrior( ...
                    evidence, selected, options.SeedPaddingPixels, options);
                region = ProjectionDenseSearchPredictor.assignPrior( ...
                    region, prior, "seeded");
            elseif options.AllowUnseededSearch && ...
                    ~isempty(evidence.MovingPoints)
                region = ProjectionDenseSearchPredictor.assignPrior( ...
                    region, globalPrior, "unseeded");
                region.SupportingTrackIds = strings(0, 1);
                region.UncertaintyPixels = max( ...
                    region.UncertaintyPixels, options.UnseededPaddingPixels);
            else
                region.State = "noSupport";
            end
        end

        function prior = seededPrior(evidence, selected, padding, options)
            disparities = evidence.MovingPoints(selected, :) - ...
                evidence.ReferencePoints(selected, :);
            center = median(disparities, 1);
            residual = vecnorm(disparities - center, 2, 2);
            uncertainty = max([options.MinimumUncertaintyPixels; ...
                evidence.UncertaintyPixels(selected); residual]);
            horizontal = [min(disparities(:, 1)) - padding - uncertainty ...
                max(disparities(:, 1)) + padding + uncertainty];
            vertical = [min(disparities(:, 2)) - padding - uncertainty ...
                max(disparities(:, 2)) + padding + uncertainty];
            direction = center;
            if norm(direction) > eps
                direction = direction / norm(direction);
            else
                direction = [1 0];
            end
            depth = evidence.DepthMeters(selected);
            finiteDepth = depth(isfinite(depth));
            depthRange = [NaN NaN];
            if ~isempty(finiteDepth)
                depthRange = [min(finiteDepth) max(finiteDepth)];
            end
            prior = struct(State="seeded", ...
                DisparityVectorPixels=center, ...
                EpipolarDirection=direction, ...
                HorizontalSearchRangePixels=horizontal, ...
                VerticalSearchRangePixels=vertical, ...
                DepthRangeMeters=depthRange, UncertaintyPixels=uncertainty, ...
                SupportingTrackIds=evidence.TrackIds(selected));
        end

        function region = assignPrior(region, prior, state)
            fields = ["DisparityVectorPixels" "EpipolarDirection" ...
                "HorizontalSearchRangePixels" "VerticalSearchRangePixels" ...
                "DepthRangeMeters" "UncertaintyPixels" ...
                "SupportingTrackIds"];
            region.State = state;
            for field = fields
                region.(field) = prior.(field);
            end
        end

        function region = emptyRegion()
            region = struct(Bounds=zeros(1, 4), Center=zeros(1, 2), ...
                State="noSupport", SeedCount=0, ...
                DisparityVectorPixels=[NaN NaN], ...
                EpipolarDirection=[NaN NaN], ...
                HorizontalSearchRangePixels=[NaN NaN], ...
                VerticalSearchRangePixels=[NaN NaN], ...
                DepthRangeMeters=[NaN NaN], UncertaintyPixels=NaN, ...
                SupportingTrackIds=strings(0, 1));
        end

        function value = positiveIntegerPair(value, name)
            if ~isnumeric(value) || ~isvector(value) || ...
                    ~ismember(numel(value), [1 2]) || ...
                    any(~isfinite(value)) || any(value < 1) || ...
                    any(fix(value) ~= value)
                error("ProjectionDenseSearchPredictor:invalidOptions", ...
                    "%s must contain one or two positive integers.", name);
            end
            value = double(value(:).');
            if isscalar(value)
                value = [value value];
            end
        end

        function value = positiveInteger(value, name)
            value = ProjectionDenseSearchPredictor.positiveIntegerPair( ...
                value, name);
            if numel(unique(value)) ~= 1
                error("ProjectionDenseSearchPredictor:invalidOptions", ...
                    "%s must be a positive integer scalar.", name);
            end
            value = value(1);
        end

        function value = nonnegativeScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value < 0
                error("ProjectionDenseSearchPredictor:invalidOptions", ...
                    "%s must be a finite nonnegative scalar.", name);
            end
            value = double(value);
        end
    end
end
