classdef ProjectionAlignmentSourceRefiner
    %ProjectionAlignmentSourceRefiner Refine coarse matches in native pixels.

    properties (Constant)
        Format = "ProjectionAlignmentSourceRefinement"
        Version = 1
    end

    methods (Static)
        function result = refine(scene, matchResult, options, monitor)
            %refine Return continuous native observations and uncertainty.
            if nargin < 4
                monitor = [];
            end
            scene = ProjectionLayerIdentity.ensureScene(scene);
            options = ProjectionAlignmentOptions.validate(options);
            refined = matchResult;
            for pairIndex = 1:numel(refined.Matches)
                refined.Matches(pairIndex).RefinementStatus = strings(0, 1);
                refined.Matches(pairIndex).RefinementQuality = zeros(0, 1);
                refined.Matches(pairIndex).RefinementPeakMargin = zeros(0, 1);
                refined.Matches(pairIndex).SourceUncertaintyPixels = zeros(0, 2);
                refined.Matches(pairIndex).RefinementAcceptedMask = false(0, 1);
            end
            pairDiagnostics = repmat( ...
                ProjectionAlignmentSourceRefiner.emptyPairDiagnostics(), ...
                1, numel(matchResult.Matches));
            for pairIndex = 1:numel(matchResult.Matches)
                pair = matchResult.Matches(pairIndex);
                [pair, pairDiagnostics(pairIndex)] = ...
                    ProjectionAlignmentSourceRefiner.refinePair( ...
                    scene, pair, options.SourceRefinement, monitor, pairIndex);
                refined.Matches(pairIndex) = pair;
            end
            refined.MatchLedger = ProjectionAlignmentMatchLedger.combine(refined);
            result = struct(Format=ProjectionAlignmentSourceRefiner.Format, ...
                Version=ProjectionAlignmentSourceRefiner.Version, ...
                MatchResult=refined, PairDiagnostics=pairDiagnostics, ...
                Diagnostics=ProjectionAlignmentSourceRefiner. ...
                combineDiagnostics(pairDiagnostics));
        end
    end

    methods (Static, Access = private)
        function [pair, diagnostics] = refinePair( ...
                scene, pair, options, monitor, pairIndex)
            diagnostics = ProjectionAlignmentSourceRefiner.emptyPairDiagnostics();
            diagnostics.Pair = pair.Pair;
            diagnostics.InputCount = pair.Count;
            diagnostics.Enabled = options.Enabled;
            pair.RefinementStatus = repmat("notAvailable", pair.Count, 1);
            pair.RefinementQuality = nan(pair.Count, 1);
            pair.RefinementPeakMargin = nan(pair.Count, 1);
            pair.SourceUncertaintyPixels = nan(pair.Count, 2);
            if ~options.Enabled || pair.Count == 0 || ...
                    ~ProjectionAlignmentSourceRefiner.isEligible(pair)
                if ~options.Enabled
                    pair.RefinementStatus(:) = "disabled";
                end
                diagnostics.NotAvailableCount = pair.Count;
                pair.RefinementAcceptedMask = false(pair.Count, 1);
                return
            end

            movingProvider = ProjectionBackendSourceProvider.fromLayer( ...
                scene.layers(pair.Pair(1)));
            referenceProvider = ProjectionBackendSourceProvider.fromLayer( ...
                scene.layers(pair.Pair(2)));
            bands = ProjectionAlignmentSourceRefiner.analysisBands(pair);
            uncertaintyFloor = max(options.UncertaintyFloorPixels, ...
                0.25 * max(pair.SourcePixelsPerWorkingPixel));
            originalReferenceRows = pair.ReferenceSourceRows;
            originalReferenceColumns = pair.ReferenceSourceColumns;
            accepted = false(pair.Count, 1);
            refinementTimer = tic;
            for observationIndex = 1:pair.Count
                if ~isempty(monitor) && mod(observationIndex - 1, 16) == 0
                    if monitor.cancellationRequested()
                        error("ProjectionAlignmentOpkSolver:cancelled", ...
                            "Alignment cancelled during source refinement.");
                    end
                    monitor.report(struct(PairIndex=pairIndex, ...
                        PairObservationIndex=observationIndex, ...
                        PairObservationCount=pair.Count, ...
                        SourceReadCount=diagnostics.SourceReadCount, ...
                        SourcePixelsRead=diagnostics.SourcePixelsRead), false);
                end
                movingJacobian = pair.MovingSourceJacobians( ...
                    observationIndex, :);
                referenceJacobian = pair.ReferenceSourceJacobians( ...
                    observationIndex, :);
                if any(~isfinite([movingJacobian referenceJacobian]))
                    pair.RefinementStatus(observationIndex) = "invalidGeometry";
                    continue
                end
                movingWindowRadius = ...
                    ProjectionAlignmentSourceRefiner.sourceWindowRadius( ...
                    movingJacobian, options.PatchRadiusPixels);
                referenceWindowRadius = ...
                    ProjectionAlignmentSourceRefiner.sourceWindowRadius( ...
                    referenceJacobian, options.PatchRadiusPixels + ...
                    options.SearchRadiusPixels);
                [movingWindow, movingInfo] = ...
                    ProjectionAlignmentSourceRefiner.readWindow( ...
                    movingProvider, bands(1), ...
                    pair.MovingSourceRows(observationIndex), ...
                    pair.MovingSourceColumns(observationIndex), ...
                    movingWindowRadius);
                [referenceWindow, referenceInfo] = ...
                    ProjectionAlignmentSourceRefiner.readWindow( ...
                    referenceProvider, bands(2), ...
                    pair.ReferenceSourceRows(observationIndex), ...
                    pair.ReferenceSourceColumns(observationIndex), ...
                    referenceWindowRadius);
                diagnostics.SourceReadCount = diagnostics.SourceReadCount + ...
                    movingInfo.ReadCount + referenceInfo.ReadCount;
                diagnostics.SourcePixelsRead = diagnostics.SourcePixelsRead + ...
                    movingInfo.PixelCount + referenceInfo.PixelCount;
                diagnostics.SourceBytesRead = diagnostics.SourceBytesRead + ...
                    movingInfo.ByteCount + referenceInfo.ByteCount;
                diagnostics.SourceReadSeconds = diagnostics.SourceReadSeconds + ...
                    movingInfo.ReadSeconds + referenceInfo.ReadSeconds;
                if ~movingInfo.Valid || ~referenceInfo.Valid
                    pair.RefinementStatus(observationIndex) = "borderRejected";
                    continue
                end
                movingPatch = ...
                    ProjectionAlignmentSourceRefiner.sampleAffinePatch( ...
                    movingWindow, movingInfo, ...
                    pair.MovingSourceRows(observationIndex), ...
                    pair.MovingSourceColumns(observationIndex), ...
                    options.PatchRadiusPixels, movingJacobian);
                if ~ProjectionAlignmentSourceRefiner.hasTexture( ...
                        movingPatch, options.MinimumTextureStandardDeviation)
                    pair.RefinementStatus(observationIndex) = "weakTexture";
                    continue
                end
                [scores, referenceTextureValid] = ...
                    ProjectionAlignmentSourceRefiner.correlationSurface( ...
                    movingPatch, referenceWindow, referenceInfo, ...
                    pair.ReferenceSourceRows(observationIndex), ...
                    pair.ReferenceSourceColumns(observationIndex), ...
                    referenceJacobian, options);
                if ~referenceTextureValid || ~any(isfinite(scores), "all")
                    pair.RefinementStatus(observationIndex) = "weakTexture";
                    continue
                end
                [peak, linearIndex] = max(scores, [], "all", "linear");
                sortedScores = sort(scores(isfinite(scores)), "descend");
                if numel(sortedScores) > 1
                    peakMargin = sortedScores(1) - sortedScores(2);
                else
                    peakMargin = Inf;
                end
                pair.RefinementQuality(observationIndex) = peak;
                pair.RefinementPeakMargin(observationIndex) = peakMargin;
                if peak < options.MinimumCorrelation
                    pair.RefinementStatus(observationIndex) = "weakCorrelation";
                    continue
                end
                if peakMargin < options.MinimumPeakMargin
                    pair.RefinementStatus(observationIndex) = "ambiguousPeak";
                    continue
                end
                [peakRow, peakColumn] = ind2sub(size(scores), linearIndex);
                searchRadius = options.SearchRadiusPixels;
                rowOffset = peakRow - searchRadius - 1;
                columnOffset = peakColumn - searchRadius - 1;
                [subpixelRow, subpixelColumn, curvature] = ...
                    ProjectionAlignmentSourceRefiner.subpixelOffset( ...
                    scores, peakRow, peakColumn, options.EnableSubpixel);
                workingOffset = [columnOffset + subpixelColumn; ...
                    rowOffset + subpixelRow];
                pair.ReferenceSourceRows(observationIndex) = ...
                    pair.ReferenceSourceRows(observationIndex) + ...
                    referenceJacobian(1:2) * workingOffset;
                pair.ReferenceSourceColumns(observationIndex) = ...
                    pair.ReferenceSourceColumns(observationIndex) + ...
                    referenceJacobian(3:4) * workingOffset;
                uncertainty = max(uncertaintyFloor, ...
                    max(pair.SourcePixelsPerWorkingPixel) * ...
                    0.1 / sqrt(max(curvature, eps)));
                pair.SourceUncertaintyPixels(observationIndex, :) = ...
                    [uncertainty uncertainty];
                pair.RefinementStatus(observationIndex) = "refined";
                accepted(observationIndex) = true;
            end

            if any(accepted)
                commonPlane = scene.layers(pair.Pair(2)).CurrentProjectionPlane;
                movingProjection = ProjectionAlignmentObservationProjector.project( ...
                    scene, pair.Pair(1), pair.MovingSourceRows, ...
                    pair.MovingSourceColumns, commonPlane);
                referenceProjection = ...
                    ProjectionAlignmentObservationProjector.project( ...
                    scene, pair.Pair(2), pair.ReferenceSourceRows, ...
                    pair.ReferenceSourceColumns, commonPlane);
                validGeometry = movingProjection.ValidMask & ...
                    referenceProjection.ValidMask;
                rejectedGeometry = accepted & ~validGeometry;
                pair.ReferenceSourceRows(rejectedGeometry) = ...
                    originalReferenceRows(rejectedGeometry);
                pair.ReferenceSourceColumns(rejectedGeometry) = ...
                    originalReferenceColumns(rejectedGeometry);
                pair.RefinementStatus(rejectedGeometry) = "invalidGeometry";
                pair.SourceUncertaintyPixels(rejectedGeometry, :) = NaN;
                accepted(rejectedGeometry) = false;
                pair.MovingPlaneCoordinates(accepted, :) = ...
                    movingProjection.PlaneCoordinates(accepted, :);
                pair.ReferencePlaneCoordinates(accepted, :) = ...
                    referenceProjection.PlaneCoordinates(accepted, :);
            end
            pair.RefinementAcceptedMask = accepted;
            pair = ProjectionAlignmentSourceRefiner.updateLedger(pair);
            diagnostics.RefinedCount = nnz(accepted);
            diagnostics.NotAvailableCount = nnz( ...
                pair.RefinementStatus == "notAvailable");
            diagnostics.BorderRejectedCount = nnz( ...
                pair.RefinementStatus == "borderRejected");
            diagnostics.WeakTextureCount = nnz( ...
                pair.RefinementStatus == "weakTexture");
            diagnostics.WeakCorrelationCount = nnz( ...
                pair.RefinementStatus == "weakCorrelation");
            diagnostics.AmbiguousCount = nnz( ...
                pair.RefinementStatus == "ambiguousPeak");
            diagnostics.InvalidGeometryCount = nnz( ...
                pair.RefinementStatus == "invalidGeometry");
            diagnostics.UncertaintyFloorPixels = uncertaintyFloor;
            diagnostics.RefinementSeconds = toc(refinementTimer);
        end

        function tf = isEligible(pair)
            required = ["MovingSourceRows" "MovingSourceColumns" ...
                "ReferenceSourceRows" "ReferenceSourceColumns" ...
                "MovingPlaneCoordinates" "ReferencePlaneCoordinates" ...
                "SourcePixelsPerWorkingPixel" "MovingSourceJacobians" ...
                "ReferenceSourceJacobians"];
            tf = all(isfield(pair, required)) && ...
                numel(pair.SourcePixelsPerWorkingPixel) == 2 && ...
                all(isfinite(pair.SourcePixelsPerWorkingPixel)) && ...
                all(pair.SourcePixelsPerWorkingPixel > 0) && ...
                size(pair.MovingSourceJacobians, 1) == pair.Count && ...
                size(pair.ReferenceSourceJacobians, 1) == pair.Count && ...
                size(pair.MovingSourceJacobians, 2) == 4 && ...
                size(pair.ReferenceSourceJacobians, 2) == 4;
        end

        function bands = analysisBands(pair)
            bands = [1 1];
            if isfield(pair, "AnalysisBands") && numel(pair.AnalysisBands) == 2
                bands = double(pair.AnalysisBands(:).');
            end
        end

        function pair = updateLedger(pair)
            pair = ProjectionAlignmentMatchLedger.ensurePair(pair);
            if isfield(pair, "MatchRecordIndices") && ...
                    numel(pair.MatchRecordIndices) == pair.Count
                rawIndices = pair.MatchRecordIndices(:);
            else
                rawIndices = (1:pair.Count).';
            end
            for observationIndex = 1:pair.Count
                recordIndex = rawIndices(observationIndex);
                record = pair.MatchLedger(recordIndex);
                record.MovingPlaneMeters = ...
                    pair.MovingPlaneCoordinates(observationIndex, :);
                record.ReferencePlaneMeters = ...
                    pair.ReferencePlaneCoordinates(observationIndex, :);
                record.MovingSourceRowPixels = ...
                    pair.MovingSourceRows(observationIndex);
                record.MovingSourceColumnPixels = ...
                    pair.MovingSourceColumns(observationIndex);
                record.ReferenceSourceRowPixels = ...
                    pair.ReferenceSourceRows(observationIndex);
                record.ReferenceSourceColumnPixels = ...
                    pair.ReferenceSourceColumns(observationIndex);
                record.Residuals.NativeDisplacementPixels = hypot( ...
                    record.ReferenceSourceColumnPixels - ...
                    record.MovingSourceColumnPixels, ...
                    record.ReferenceSourceRowPixels - ...
                    record.MovingSourceRowPixels);
                pair.MatchLedger(recordIndex) = record;
            end
        end

        function [window, info] = readWindow( ...
                provider, bandIndex, row, column, radius)
            info = struct(Valid=false, RowStart=0, ColumnStart=0, ...
                ReadCount=0, PixelCount=0, ByteCount=0, ReadSeconds=0);
            window = zeros(0, 0);
            if ~isfinite(row) || ~isfinite(column) || ...
                    row - radius < 1 || column - radius < 1 || ...
                    row + radius > provider.ImageSize(1) || ...
                    column + radius > provider.ImageSize(2) || ...
                    bandIndex > provider.BandCount
                return
            end
            rowRange = [floor(row - radius) ceil(row + radius)];
            columnRange = [floor(column - radius) ceil(column + radius)];
            timer = tic;
            if provider.Kind == "memory"
                nativeWindow = provider.Image( ...
                    rowRange(1):rowRange(2), ...
                    columnRange(1):columnRange(2), bandIndex);
            else
                nativeImage = imread(provider.Path, ...
                    PixelRegion={rowRange, columnRange});
                nativeWindow = nativeImage(:, :, bandIndex);
            end
            info.ReadSeconds = toc(timer);
            info.Valid = true;
            info.RowStart = rowRange(1);
            info.ColumnStart = columnRange(1);
            info.ReadCount = 1;
            info.PixelCount = numel(nativeWindow);
            info.ByteCount = info.PixelCount * ...
                ProjectionAlignmentSourceRefiner.bytesPerElement( ...
                class(nativeWindow));
            window = double(nativeWindow);
        end

        function patch = sampleAffinePatch( ...
                window, info, row, column, radius, jacobian)
            offsets = -radius:radius;
            [xGrid, yGrid] = meshgrid(offsets, offsets);
            rowGrid = row + jacobian(1) * xGrid + jacobian(2) * yGrid;
            columnGrid = column + ...
                jacobian(3) * xGrid + jacobian(4) * yGrid;
            patch = interp2(window, ...
                columnGrid - info.ColumnStart + 1, ...
                rowGrid - info.RowStart + 1, "linear", NaN);
        end

        function [scores, textureValid] = correlationSurface( ...
                movingPatch, referenceWindow, referenceInfo, row, column, ...
                referenceJacobian, options)
            searchRadius = options.SearchRadiusPixels;
            referenceSearch = ...
                ProjectionAlignmentSourceRefiner.sampleAffinePatch( ...
                referenceWindow, referenceInfo, row, column, ...
                options.PatchRadiusPixels + searchRadius, referenceJacobian);
            textureValid = ProjectionAlignmentSourceRefiner.hasTexture( ...
                referenceSearch, options.MinimumTextureStandardDeviation);
            scoreSize = 2 * searchRadius + 1;
            scores = nan(scoreSize);
            if ~textureValid
                return
            end
            correlation = normxcorr2(movingPatch, referenceSearch);
            first = size(movingPatch, 1);
            last = first + scoreSize - 1;
            scores = correlation(first:last, first:last);
        end

        function radius = sourceWindowRadius(jacobian, workingRadius)
            rowExtent = workingRadius * ...
                (abs(jacobian(1)) + abs(jacobian(2)));
            columnExtent = workingRadius * ...
                (abs(jacobian(3)) + abs(jacobian(4)));
            radius = ceil(max(rowExtent, columnExtent)) + 2;
        end

        function tf = hasTexture(patch, minimumStandardDeviation)
            values = patch(isfinite(patch));
            if numel(values) ~= numel(patch) || isempty(values)
                tf = false;
                return
            end
            valueRange = max(values) - min(values);
            tf = valueRange > 0 && ...
                std(values, 1) / valueRange >= minimumStandardDeviation;
        end

        function [rowOffset, columnOffset, curvature] = ...
                subpixelOffset(scores, row, column, enabled)
            rowOffset = 0;
            columnOffset = 0;
            rowCurvature = 0;
            columnCurvature = 0;
            if enabled && row > 1 && row < size(scores, 1) && ...
                    column > 1 && column < size(scores, 2)
                [rowOffset, rowCurvature] = ...
                    ProjectionAlignmentSourceRefiner.parabolicPeak( ...
                    scores(row - 1, column), scores(row, column), ...
                    scores(row + 1, column));
                [columnOffset, columnCurvature] = ...
                    ProjectionAlignmentSourceRefiner.parabolicPeak( ...
                    scores(row, column - 1), scores(row, column), ...
                    scores(row, column + 1));
            end
            curvature = max(eps, mean([rowCurvature columnCurvature]));
        end

        function [offset, curvature] = parabolicPeak(left, center, right)
            denominator = left - 2 * center + right;
            curvature = max(0, -denominator);
            if all(isfinite([left center right])) && abs(denominator) > eps
                offset = 0.5 * (left - right) / denominator;
                offset = min(max(offset, -0.5), 0.5);
            else
                offset = 0;
            end
        end

        function diagnostics = emptyPairDiagnostics()
            diagnostics = struct(Pair=[0 0], Enabled=false, InputCount=0, ...
                RefinedCount=0, NotAvailableCount=0, BorderRejectedCount=0, ...
                WeakTextureCount=0, WeakCorrelationCount=0, ...
                AmbiguousCount=0, InvalidGeometryCount=0, ...
                UncertaintyFloorPixels=NaN, SourceReadCount=0, ...
                SourcePixelsRead=0, SourceBytesRead=0, ...
                SourceReadSeconds=0, RefinementSeconds=0);
        end

        function diagnostics = combineDiagnostics(pairs)
            diagnostics = struct( ...
                InputCount=sum([pairs.InputCount]), ...
                RefinedCount=sum([pairs.RefinedCount]), ...
                NotAvailableCount=sum([pairs.NotAvailableCount]), ...
                BorderRejectedCount=sum([pairs.BorderRejectedCount]), ...
                WeakTextureCount=sum([pairs.WeakTextureCount]), ...
                WeakCorrelationCount=sum([pairs.WeakCorrelationCount]), ...
                AmbiguousCount=sum([pairs.AmbiguousCount]), ...
                InvalidGeometryCount=sum([pairs.InvalidGeometryCount]), ...
                SourceReadCount=sum([pairs.SourceReadCount]), ...
                SourcePixelsRead=sum([pairs.SourcePixelsRead]), ...
                SourceBytesRead=sum([pairs.SourceBytesRead]), ...
                SourceReadSeconds=sum([pairs.SourceReadSeconds]), ...
                RefinementSeconds=sum([pairs.RefinementSeconds]));
        end

        function count = bytesPerElement(className)
            switch className
                case {"logical", "uint8", "int8"}
                    count = 1;
                case {"uint16", "int16"}
                    count = 2;
                case {"uint32", "int32", "single"}
                    count = 4;
                otherwise
                    count = 8;
            end
        end
    end
end
