classdef ProjectionSurfaceRegistrationSupport
    %ProjectionSurfaceRegistrationSupport Robust DEM translation utilities.

    methods (Static)
        function solution = solve(request, options, ignoreMasks, runtimeControl)
            %solve Estimate imagery-to-DEM translation in scene-local ENU.
            points = request.PointSet.Points([request.PointSet.Points.Valid]);
            pointIds = string({points.PointId});
            coordinatesWorld = horzcat(points.PointWorld);
            insideRoi = all(coordinatesWorld >= request.RoiWorld(:, 1) & ...
                coordinatesWorld <= request.RoiWorld(:, 2), 1);
            excludedIds = string({request.PointExclusions.PointId});
            excluded = ismember(pointIds, excludedIds) & ~ignoreMasks;
            covarianceValid = arrayfun(@(point) ...
                ProjectionSurfaceRegistrationSupport.validCovariance( ...
                point.CovarianceWorldMetersSquared), points);
            conditions = double([points.ConditionNumber]);
            conditioningValid = isfinite(conditions) & conditions > 0 & ...
                conditions <= request.MaximumConditionNumber;
            candidate = insideRoi & ~excluded & covarianceValid & ...
                conditioningValid;
            rejections = ProjectionSurfaceRegistrationSupport.baseRejections( ...
                pointIds, insideRoi, excluded, covarianceValid, ...
                conditioningValid, request.PointExclusions);
            surface = ProjectionDemGrid.localSurface(request.Dem, ignoreMasks);
            interpolants = ProjectionSurfaceRegistrationSupport. ...
                interpolants(surface);
            coordinatesEnu = ProjectionDemGrid.worldToEnu( ...
                request.Dem, coordinatesWorld);
            rotation = request.Dem.Transforms.EnuToProjectWorldRotation;
            covarianceEnu = zeros(3, 3, numel(points));
            for index = 1:numel(points)
                covarianceEnu(:, :, index) = rotation.' * ...
                    double(points(index).CovarianceWorldMetersSquared) * rotation;
            end
            translation = reshape(double(options.InitialTranslationEnuMeters), 3, 1);
            converged = false;
            initialEvaluation = ProjectionSurfaceRegistrationSupport.evaluate( ...
                translation, coordinatesEnu, covarianceEnu, conditions, ...
                candidate, interpolants, request, options);
            normalMatrix = zeros(3);
            delta = nan(3, 1);
            for iteration = 1:request.MaximumIterations
                ProjectionSurfaceRegistrationSupport.throwIfCancelled( ...
                    runtimeControl);
                evaluation = ProjectionSurfaceRegistrationSupport.evaluate( ...
                    translation, coordinatesEnu, covarianceEnu, conditions, ...
                    candidate, interpolants, request, options);
                if nnz(evaluation.Usable) < request.MinimumSupport
                    break
                end
                [normalMatrix, gradient] = ...
                    ProjectionSurfaceRegistrationSupport.normalEquation(evaluation);
                if rank(normalMatrix, options.RankTolerance) < 3
                    break
                end
                delta = -normalMatrix \ gradient;
                deltaNorm = norm(delta);
                if deltaNorm > options.MaximumStepMeters
                    delta = delta * options.MaximumStepMeters / deltaNorm;
                end
                translation = translation + delta;
                ProjectionSurfaceRegistrationSupport.notifyProgress( ...
                    runtimeControl, 0.1 + 0.75 * ...
                    iteration / request.MaximumIterations, "iterating");
                if norm(delta) <= request.ConvergenceToleranceMeters
                    converged = true;
                    break
                end
            end
            evaluation = ProjectionSurfaceRegistrationSupport.evaluate( ...
                translation, coordinatesEnu, covarianceEnu, conditions, ...
                candidate, interpolants, request, options);
            if nnz(evaluation.Usable) >= request.MinimumSupport
                [normalMatrix, ~] = ...
                    ProjectionSurfaceRegistrationSupport.normalEquation(evaluation);
            end
            rejections = ProjectionSurfaceRegistrationSupport. ...
                appendSamplingRejections(rejections, pointIds, candidate, ...
                evaluation.Usable);
            [covariance, covarianceStatus, covarianceReason] = ...
                ProjectionSurfaceRegistrationSupport.covariance( ...
                normalMatrix, evaluation, request.Dem.Accuracy, options);
            matrixRank = rank(normalMatrix, options.RankTolerance);
            conditionNumber = Inf;
            if matrixRank == 3
                conditionNumber = cond(normalMatrix);
            end
            solution = struct(TranslationEnuMeters=translation, ...
                CovarianceEnuMetersSquared=covariance, ...
                CovarianceStatus=covarianceStatus, ...
                CovarianceReason=covarianceReason, Converged=converged, ...
                IterationCount=iteration, LastStepMeters=delta, ...
                NormalMatrix=normalMatrix, NormalMatrixRank=matrixRank, ...
                ConditionNumber=conditionNumber, ...
                InitialEvaluation=initialEvaluation, ...
                FinalEvaluation=evaluation, PointIds=pointIds, ...
                Points=points, OriginalPointsWorld=coordinatesWorld, ...
                OriginalPointsEnu=coordinatesEnu, CandidateMask=candidate, ...
                Rejections=rejections, IgnoreMasks=logical(ignoreMasks));
        end

        function data = correctionData(request, transform, covariance, ...
                algorithmId, conditionNumber, support, failure)
            %correctionData Create one proposed portable CorrectionSet value.
            passIds = ProjectionSurfaceRegistrationSupport.unionPointField( ...
                request.PointSet.Points, "ContributingPassIds");
            views = ProjectionSurfaceRegistrationSupport.correctionViews( ...
                request.PointSet);
            passes = repmat(struct(PassId="", ...
                CommonAttitudeRadians=zeros(1, 3), ...
                TranslationMeters=zeros(1, 3), ...
                TranslationAvailable=true), 1, numel(passIds));
            for index = 1:numel(passIds)
                passes(index).PassId = passIds(index);
                passes(index).TranslationMeters = ...
                    transform.TranslationWorldMeters.';
            end
            blocks = [struct(Name="DEM global position translation", ...
                Type="globalPositionTranslation", Scope="network", ...
                TargetId=request.PointSet.GenerationId, ...
                Values=transform.TranslationWorldMeters.', Units="meters", ...
                Frame=request.PointSet.WorldFrame, ...
                Semantics="imageryToDemPreviewOnlyNotApplied") ...
                struct(Name="DEM translation covariance", ...
                Type="globalPositionTranslationCovariance", Scope="network", ...
                TargetId=request.PointSet.GenerationId, ...
                Values=covariance.TranslationWorldMetersSquared, ...
                Units="metersSquared", Frame=request.PointSet.WorldFrame, ...
                Semantics="posteriorWithSharedDemAccuracyFloor")];
            identity = struct(SourcePointSetGenerationId= ...
                request.PointSet.GenerationId, AlgorithmId=algorithmId, ...
                Translation=transform.TranslationWorldMeters, ...
                RequestSeed=request.Seed);
            generationId = "dem-registration-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(identity), 17);
            data = struct(Format=ProjectionCorrectionSet.FormatName, ...
                Version=ProjectionCorrectionSet.SchemaVersion, ...
                GenerationId=generationId, ParentGenerationId="", ...
                Lifecycle="proposed", Views=views, Passes=passes, ...
                Blocks=blocks, Geometry=struct( ...
                FingerprintAlgorithm=ProjectionGeometryFingerprint.Algorithm, ...
                CanonicalizationVersion= ...
                ProjectionGeometryFingerprint.CanonicalizationVersion, ...
                SourcePointSetGenerationId=request.PointSet.GenerationId, ...
                ScopeViewIds=ProjectionSurfaceRegistrationSupport. ...
                unionPointField(request.PointSet.Points, ...
                "ContributingViewIds")), ...
                Covariance=struct(Available=false, ...
                AttitudeRadiansSquared=zeros(0), ...
                ConditionNumber=conditionNumber, ...
                Reason="translationCovarianceStoredAsTypedBlock"), ...
                Provenance=struct(Source="demRegistration", ...
                AlgorithmId=algorithmId, DemDatum=request.Dem.DatumAssumption, ...
                AutoApplied=false), Diagnostics=struct(AutoApply=false, ...
                RequiresExplicitB8Apply=true, Support=support), ...
                Failure=failure);
            correction = ProjectionCorrectionSet.create(data);
            data = correction.toStruct();
        end

        function summary = residualSummary(values)
            %residualSummary Summarize finite signed surface-normal residuals.
            values = double(values(isfinite(values)));
            if isempty(values)
                summary = struct(Count=0, MeanMeters=NaN, ...
                    MedianMeters=NaN, RmsMeters=NaN, MadMeters=NaN, ...
                    P95AbsoluteMeters=NaN, MaximumAbsoluteMeters=NaN);
                return
            end
            absolute = sort(abs(values));
            p95Index = max(1, ceil(0.95 * numel(absolute)));
            summary = struct(Count=numel(values), MeanMeters=mean(values), ...
                MedianMeters=median(values), ...
                RmsMeters=sqrt(mean(values .^ 2)), ...
                MadMeters=median(abs(values - median(values))), ...
                P95AbsoluteMeters=absolute(p95Index), ...
                MaximumAbsoluteMeters=max(absolute));
        end

        function bytes = bytes(value)
            if isempty(value)
                bytes = 0;
                return
            end
            info = whos("value");
            bytes = double(info.bytes);
        end
    end

    methods (Static, Access = private)
        function tf = validCovariance(value)
            tf = isnumeric(value) && isequal(size(value), [3 3]) && ...
                all(isfinite(value), "all");
            if tf
                value = double(value);
                tolerance = 1e-10 * max(1, norm(value, "fro"));
                tf = norm(value - value.', "fro") <= tolerance && ...
                    min(eig(0.5 * (value + value.'))) >= -tolerance;
            end
        end

        function interpolants = interpolants(surface)
            up = surface.UpMeters;
            [slopeEast, slopeNorth] = gradient(up, ...
                surface.EastAxisMeters, surface.NorthAxisMeters);
            axes = {surface.NorthAxisMeters, surface.EastAxisMeters};
            interpolants = struct( ...
                Height=griddedInterpolant(axes, up, "linear", "none"), ...
                SlopeEast=griddedInterpolant( ...
                axes, slopeEast, "linear", "none"), ...
                SlopeNorth=griddedInterpolant( ...
                axes, slopeNorth, "linear", "none"));
        end

        function evaluation = evaluate(translation, coordinates, covariances, ...
                conditions, candidate, interpolants, request, options)
            registered = coordinates + translation;
            east = registered(1, :);
            north = registered(2, :);
            heights = interpolants.Height(north, east);
            slopeEast = interpolants.SlopeEast(north, east);
            slopeNorth = interpolants.SlopeNorth(north, east);
            usable = candidate & isfinite(heights) & ...
                isfinite(slopeEast) & isfinite(slopeNorth);
            normals = nan(3, numel(candidate));
            normals(:, usable) = [-slopeEast(usable); -slopeNorth(usable); ...
                ones(1, nnz(usable))];
            normals(:, usable) = normals(:, usable) ./ ...
                vecnorm(normals(:, usable), 2, 1);
            residuals = nan(1, numel(candidate));
            residuals(usable) = normals(3, usable) .* ...
                (registered(3, usable) - heights(usable));
            baseWeights = zeros(1, numel(candidate));
            horizontalSigma = request.Dem.Accuracy.HorizontalSigmaMeters;
            verticalSigma = request.Dem.Accuracy.VerticalSigmaMeters;
            for index = find(usable)
                normal = normals(:, index);
                pointVariance = normal.' * covariances(:, :, index) * normal;
                demVariance = horizontalSigma ^ 2 * ...
                    (normal(1) ^ 2 + normal(2) ^ 2) + ...
                    verticalSigma ^ 2 * normal(3) ^ 2;
                slopeMagnitude = hypot(slopeEast(index), slopeNorth(index));
                slopeWeight = 1 / (1 + ...
                    (slopeMagnitude / request.SlopeWeightScale) ^ 2);
                conditioningWeight = 1 / ...
                    (1 + log10(max(1, conditions(index))));
                baseWeights(index) = slopeWeight * conditioningWeight / ...
                    max(options.MinimumVarianceMetersSquared, ...
                    pointVariance + demVariance);
            end
            huberScale = request.HuberScaleMeters;
            if isempty(huberScale)
                finiteResiduals = residuals(usable);
                robustScale = 1.4826 * median(abs( ...
                    finiteResiduals - median(finiteResiduals)));
                huberScale = max(options.MinimumHuberScaleMeters, robustScale);
            end
            robustWeights = zeros(1, numel(candidate));
            robustWeights(usable) = min(1, huberScale ./ ...
                max(abs(residuals(usable)), eps));
            weights = baseWeights .* robustWeights;
            evaluation = struct(RegisteredPointsEnu=registered, ...
                HeightsMeters=heights, SlopeEast=slopeEast, ...
                SlopeNorth=slopeNorth, Normals=normals, ...
                ResidualsMeters=residuals, Usable=usable, ...
                BaseWeights=baseWeights, RobustWeights=robustWeights, ...
                Weights=weights, HuberScaleMeters=huberScale, ...
                RobustDownweightedCount=nnz(usable & robustWeights < 1));
        end

        function [normalMatrix, gradient] = normalEquation(evaluation)
            usable = evaluation.Usable & evaluation.Weights > 0;
            jacobian = evaluation.Normals(:, usable);
            weights = evaluation.Weights(usable);
            residuals = evaluation.ResidualsMeters(usable);
            normalMatrix = (jacobian .* weights) * jacobian.';
            gradient = jacobian * (weights .* residuals).';
        end

        function [covariance, status, reason] = covariance( ...
                normalMatrix, evaluation, accuracy, options)
            covariance = diag([accuracy.HorizontalSigmaMeters ^ 2 ...
                accuracy.HorizontalSigmaMeters ^ 2 ...
                accuracy.VerticalSigmaMeters ^ 2]);
            status = "sharedDemAccuracyFloorOnly";
            reason = "normalMatrixNotFullRank";
            if rank(normalMatrix, options.RankTolerance) == 3
                residuals = evaluation.ResidualsMeters(evaluation.Usable);
                robustVariance = max(options.CovarianceScaleFloor, ...
                    mean(residuals .^ 2));
                covariance = covariance + robustVariance * pinv(normalMatrix);
                covariance = 0.5 * (covariance + covariance.');
                status = "posteriorWithSharedDemAccuracyFloor";
                reason = "conditionalNormalEquationPlusCorrelatedDemFloor";
            end
        end

        function rejections = baseRejections(pointIds, insideRoi, excluded, ...
                covarianceValid, conditioningValid, exclusions)
            rejections = ProjectionSurfaceRegistrationResult.emptyRejections();
            for index = 1:numel(pointIds)
                reason = "";
                if ~insideRoi(index)
                    reason = "outsideRoi";
                elseif excluded(index)
                    match = string({exclusions.PointId}) == pointIds(index);
                    reason = "pointMask:" + string(exclusions(match).Reason);
                elseif ~covarianceValid(index)
                    reason = "invalidPointCovariance";
                elseif ~conditioningValid(index)
                    reason = "weakPointConditioning";
                end
                if strlength(reason) > 0
                    rejections(end + 1) = struct( ...
                        PointId=pointIds(index), Reason=reason); %#ok<AGROW>
                end
            end
        end

        function rejections = appendSamplingRejections( ...
                rejections, pointIds, candidate, usable)
            missing = candidate & ~usable;
            for index = find(missing)
                rejections(end + 1) = struct( ...
                    PointId=pointIds(index), ...
                    Reason="outsideDemOrVoidOrExcludedCell"); %#ok<AGROW>
            end
        end

        function values = unionPointField(points, field)
            values = strings(1, 0);
            for index = 1:numel(points)
                values = [values reshape(string( ...
                    points(index).(field)), 1, [])]; %#ok<AGROW>
            end
            values = sort(unique(values));
        end

        function views = correctionViews(pointSet)
            viewIds = ProjectionSurfaceRegistrationSupport.unionPointField( ...
                pointSet.Points, "ContributingViewIds");
            template = struct(ViewId="", PassId="", LayerId="", ...
                ParentAttitudeRadians=zeros(1, 3), ...
                EffectiveAttitudeRadians=zeros(1, 3), ...
                CommonAttitudeRadians=zeros(1, 3), ...
                DifferentialAttitudeRadians=zeros(1, 3), ...
                ParentRotationMatrix=eye(3), ...
                IncrementRotationMatrix=eye(3), ...
                EffectiveRotationMatrix=eye(3), ...
                IncrementRotationVectorRadians=zeros(1, 3), ...
                ParentProjectionOffsetMeters=zeros(1, 2), ...
                EffectiveProjectionOffsetMeters=zeros(1, 2), ...
                BaseGeometryFingerprint="", ...
                ParentGeometryFingerprint="", ...
                CorrectedGeometryFingerprint="");
            views = repmat(template, 1, numel(viewIds));
            rays = [pointSet.Points.RayDiagnostics];
            for index = 1:numel(viewIds)
                viewId = viewIds(index);
                matching = string({rays.ViewId}) == viewId;
                passIds = unique(string({rays(matching).PassId}));
                if numel(passIds) ~= 1
                    error("ProjectionSurfaceRegistrationSupport:ambiguousPass", ...
                        "Each registration view must map to exactly one pass.");
                end
                fingerprint = "point-set-geometry-" + extractBefore( ...
                    ProjectionGeometryFingerprint.hash(struct( ...
                    GenerationId=pointSet.GenerationId, ViewId=viewId)), 17);
                views(index).ViewId = viewId;
                views(index).PassId = passIds;
                views(index).LayerId = viewId;
                views(index).BaseGeometryFingerprint = fingerprint;
                views(index).ParentGeometryFingerprint = fingerprint;
                views(index).CorrectedGeometryFingerprint = fingerprint;
            end
        end

        function throwIfCancelled(runtimeControl)
            if ~isempty(runtimeControl.CancellationFcn) && ...
                    logical(runtimeControl.CancellationFcn())
                error("ProjectionSurfaceRegistrationAlgorithm:cancelled", ...
                    "Surface registration was cancelled cooperatively.");
            end
        end

        function notifyProgress(runtimeControl, fraction, stage)
            if ~isempty(runtimeControl.ProgressFcn)
                runtimeControl.ProgressFcn(struct( ...
                    Fraction=double(fraction), Stage=string(stage)));
            end
        end
    end
end
