classdef ProjectionAlignmentObliqueTerrainHarness
    %ProjectionAlignmentObliqueTerrainHarness Build oblique pushbroom stereo data.

    properties (Constant)
        Format = "ProjectionAlignmentObliqueTerrainScene"
        Version = 1
    end

    methods (Static)
        function [scene, truth] = createSceneFromRgbTiff(imagePath, options)
            %createSceneFromRgbTiff Use TIFF red/blue bands as terrain textures.
            if nargin < 2
                options = struct();
            end
            imagePath = string(imagePath);
            if ~isscalar(imagePath) || ~isfile(imagePath)
                error("ProjectionAlignmentObliqueTerrainHarness:fileNotFound", ...
                    "RGB TIFF input does not exist: %s", imagePath);
            end
            rgbImage = imread(imagePath);
            [scene, truth] = ...
                ProjectionAlignmentObliqueTerrainHarness.createScene( ...
                rgbImage, options, imagePath);
        end

        function [scene, truth] = createScene(rgbImage, options, sourcePath)
            %createScene Drape rectified red/blue bands and render sensor views.
            if nargin < 2
                options = struct();
            end
            if nargin < 3
                sourcePath = "in-memory-rgb";
            end
            sourcePath = string(sourcePath);
            if ~isscalar(sourcePath) || strlength(sourcePath) == 0
                error("ProjectionAlignmentObliqueTerrainHarness:invalidSourcePath", ...
                    "Source path must be a nonempty scalar string.");
            end
            ProjectionAlignmentObliqueTerrainHarness.validateRgbImage(rgbImage);
            options = ProjectionAlignmentObliqueTerrainHarness.mergeOptions(options);
            plane = PlanarProjection.definePlaneFromBasis( ...
                zeros(3, 1), [1; 0; 0], [0; 1; 0]);

            textures = {rgbImage(:, :, 1), rgbImage(:, :, 3)};
            bandNames = ["red", "blue"];
            sensorImages = cell(1, 2);
            trajectories = repmat( ...
                ProjectionAlignmentObliqueTerrainHarness.emptyTrajectory(), 1, 2);
            truthViews = repmat( ...
                ProjectionAlignmentObliqueTerrainHarness.emptyTruthView(), 1, 2);
            sourceGeometries = cell(1, 2);
            for sensorIndex = 1:2
                trajectory = ...
                    ProjectionAlignmentObliqueTerrainHarness.createTrajectory( ...
                    options, options.AzimuthDegrees(sensorIndex));
                geometry = ...
                    ProjectionAlignmentObliqueTerrainHarness.createSourceGeometry( ...
                    options, trajectory, sensorIndex);
                [sensorImage, viewTruth] = ...
                    ProjectionAlignmentObliqueTerrainHarness.renderSensorImage( ...
                    textures{sensorIndex}, geometry, options);
                trajectories(sensorIndex) = trajectory;
                truthViews(sensorIndex) = viewTruth;
                sourceGeometries{sensorIndex} = geometry;
                sensorImages{sensorIndex} = sensorImage;
            end

            imagePaths = sourcePath + ["#red-oblique", "#blue-oblique"];
            harnessOptions = struct(RowStride=options.MeshStride, ...
                ColumnStride=options.MeshStride, ...
                GSD=sourceGeometries{1}.GSD, ...
                PlatformStepMeters=sourceGeometries{1}.PlatformStepMeters, ...
                NominalRange=options.RangeMeters, ...
                DisplayTextureMaxPixels=Inf);
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                sensorImages, imagePaths, harnessOptions);
            for sensorIndex = 1:2
                layer = scene.layers(sensorIndex);
                layer.Name = "Oblique terrain " + bandNames(sensorIndex);
                layer.SourceGeometry = sourceGeometries{sensorIndex};
                layer.BaseProjectionPlane = plane;
                layer.CurrentProjectionPlane = plane;
                layer.MeshSampling = ProjectionViewerHarness.createMeshSampling( ...
                    options.SensorImageSize, options.MeshStride, ...
                    options.MeshStride);
                layer.ImageMetadata.SourceBand = bandNames(sensorIndex);
                layer.ImageMetadata.RectifiedSourcePath = sourcePath;
                layer.ImageMetadata.SimulationFormat = ...
                    ProjectionAlignmentObliqueTerrainHarness.Format;
                scene.layers(sensorIndex) = layer;
            end
            scene.layers = ProjectionLayerIdentity.ensureLayers(scene.layers);
            for sensorIndex = 1:2
                truthViews(sensorIndex).LayerId = ...
                    string(scene.layers(sensorIndex).LayerId);
            end

            sensorCenters = reshape([trajectories.Center], 3, []);
            frameOrigin = mean(sensorCenters, 2);
            frameDirection = -frameOrigin / norm(frameOrigin);
            scene.frameCamera = PlanarProjection.defineFrameCamera( ...
                frameOrigin, frameDirection, 1, plane);
            scene.renderOrigin = plane.P0;
            scene.preview.MeshSampling = scene.layers(1).MeshSampling;
            scene.preview.LayerMeshSampling = [scene.layers.MeshSampling];
            scene.Simulation = ...
                ProjectionAlignmentObliqueTerrainHarness.sceneSummary( ...
                rgbImage, sourcePath, options, trajectories);

            [demX, demY, demZ] = ...
                ProjectionAlignmentObliqueTerrainHarness.demGrid(options);
            truth = struct( ...
                Format=ProjectionAlignmentObliqueTerrainHarness.Format + "Truth", ...
                Version=ProjectionAlignmentObliqueTerrainHarness.Version, ...
                TargetPlane=plane, TextureExtentMeters=options.TargetExtentMeters, ...
                DemX=single(demX), DemY=single(demY), DemZ=single(demZ), ...
                SensorViews=truthViews, Trajectories=trajectories, ...
                SourcePath=sourcePath, SourceImageSize=size(rgbImage));
        end

        function comparison = addTruthDiagnostics(comparison, truth)
            %addTruthDiagnostics Attach ground-coordinate match error metrics.
            if ~isstruct(comparison) || ~isfield(comparison, "Runs") || ...
                    ~isfield(comparison, "Summary")
                error("ProjectionAlignmentObliqueTerrainHarness:invalidComparison", ...
                    "Comparison must come from ProjectionAlignmentWorkingImageComparison.");
            end
            ProjectionAlignmentObliqueTerrainHarness.validateTruth(truth);
            for modeIndex = 1:numel(comparison.Runs)
                run = comparison.Runs(modeIndex);
                diagnostics = struct( ...
                    Raw=ProjectionAlignmentObliqueTerrainHarness.matchTruthMetrics( ...
                    run.MatchResult, truth), ...
                    Filtered= ...
                    ProjectionAlignmentObliqueTerrainHarness.matchTruthMetrics( ...
                    run.FilteredMatchResult, truth));
                comparison.Summary.Modes(modeIndex).TerrainTruth = diagnostics;
            end
        end

        function metrics = truthMetrics(matchResult, truth)
            %truthMetrics Compare matched source observations with terrain truth.
            ProjectionAlignmentObliqueTerrainHarness.validateTruth(truth);
            metrics = ProjectionAlignmentObliqueTerrainHarness.matchTruthMetrics( ...
                matchResult, truth);
        end

        function artifacts = writeSimulationArtifacts(outputDirectory, scene, truth)
            %writeSimulationArtifacts Write DEM and rendered sensor review PNGs.
            ProjectionAlignmentObliqueTerrainHarness.validateTruth(truth);
            outputDirectory = string(outputDirectory);
            if ~isscalar(outputDirectory) || strlength(outputDirectory) == 0
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOutput", ...
                    "Output directory must be a nonempty scalar path.");
            end
            if ~isfolder(outputDirectory)
                mkdir(outputDirectory);
            end

            demPath = fullfile(outputDirectory, "synthetic_dem.png");
            demImage = ProjectionAlignmentObliqueTerrainHarness.scaleSignedImage( ...
                truth.DemZ, max(abs(truth.DemZ), [], "all"));
            imwrite(demImage, demPath);
            sensorPaths = strings(1, numel(scene.layers));
            for sensorIndex = 1:numel(scene.layers)
                sensorPath = fullfile(outputDirectory, sprintf( ...
                    "sensor_view_%d_%s.png", sensorIndex, ...
                    scene.layers(sensorIndex).ImageMetadata.SourceBand));
                imwrite(scene.layers(sensorIndex).Image, sensorPath);
                sensorPaths(sensorIndex) = string(sensorPath);
            end
            artifacts = struct(DemPath=string(demPath), ...
                SensorViewPaths=sensorPaths);
        end
    end

    methods (Static, Access = private)
        function options = mergeOptions(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "Simulation options must be a scalar struct.");
            end
            defaults = struct(SensorImageSize=[1024 1024], ...
                RangeMeters=10000, OffNadirDegrees=65, ...
                AzimuthDegrees=[-1.5 1.5], CrossTrackFovDegrees=12, ...
                AlongTrackSpanMeters=3000, ...
                TargetExtentMeters=[-4000 4000 -4000 4000], ...
                DemAmplitudeMeters=50, DemWavelengthMeters=1500, ...
                DemEnvelopeSigmaMeters=5000, DemGridSize=257, ...
                MeshStride=16, RayIntersectionIterations=30, ...
                RenderChunkRows=64);
            names = fieldnames(defaults);
            for k = 1:numel(names)
                if isfield(options, names{k})
                    defaults.(names{k}) = options.(names{k});
                end
            end

            defaults.SensorImageSize = ...
                ProjectionAlignmentObliqueTerrainHarness.validateIntegerVector( ...
                defaults.SensorImageSize, 2, "SensorImageSize", 2);
            defaults.RangeMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                defaults.RangeMeters, "RangeMeters");
            defaults.OffNadirDegrees = ...
                ProjectionAlignmentObliqueTerrainHarness.validateScalarRange( ...
                defaults.OffNadirDegrees, "OffNadirDegrees", 0, 89);
            defaults.AzimuthDegrees = ...
                ProjectionAlignmentObliqueTerrainHarness.validateFiniteVector( ...
                defaults.AzimuthDegrees, 2, "AzimuthDegrees");
            defaults.CrossTrackFovDegrees = ...
                ProjectionAlignmentObliqueTerrainHarness.validateScalarRange( ...
                defaults.CrossTrackFovDegrees, ...
                "CrossTrackFovDegrees", 0, 30);
            defaults.AlongTrackSpanMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                defaults.AlongTrackSpanMeters, "AlongTrackSpanMeters");
            defaults.TargetExtentMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validateExtent( ...
                defaults.TargetExtentMeters);
            defaults.DemAmplitudeMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                defaults.DemAmplitudeMeters, "DemAmplitudeMeters");
            defaults.DemWavelengthMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                defaults.DemWavelengthMeters, "DemWavelengthMeters");
            defaults.DemEnvelopeSigmaMeters = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                defaults.DemEnvelopeSigmaMeters, "DemEnvelopeSigmaMeters");
            defaults.DemGridSize = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveInteger( ...
                defaults.DemGridSize, "DemGridSize", 3);
            defaults.MeshStride = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveInteger( ...
                defaults.MeshStride, "MeshStride", 1);
            defaults.RayIntersectionIterations = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveInteger( ...
                defaults.RayIntersectionIterations, ...
                "RayIntersectionIterations", 10);
            defaults.RenderChunkRows = ...
                ProjectionAlignmentObliqueTerrainHarness.validatePositiveInteger( ...
                defaults.RenderChunkRows, "RenderChunkRows", 1);
            options = defaults;
        end

        function trajectory = createTrajectory(options, azimuthDegrees)
            azimuthRadians = deg2rad(azimuthDegrees);
            offNadirRadians = deg2rad(options.OffNadirDegrees);
            radial = [cos(azimuthRadians); sin(azimuthRadians); 0];
            alongTrack = [-sin(azimuthRadians); cos(azimuthRadians); 0];
            center = options.RangeMeters * ( ...
                sin(offNadirRadians) * radial + ...
                cos(offNadirRadians) * [0; 0; 1]);
            opticalAxis = -center / norm(center);
            rowAxis = cross(alongTrack, opticalAxis);
            rowAxis = rowAxis / norm(rowAxis);
            trajectory = struct(AzimuthDegrees=azimuthDegrees, ...
                ElevationDegrees=90 - options.OffNadirDegrees, ...
                OffNadirDegrees=options.OffNadirDegrees, ...
                RangeMeters=options.RangeMeters, Center=center, ...
                AlongTrackDirection=alongTrack, RadialDirection=radial, ...
                OpticalAxis=opticalAxis, RowAxis=rowAxis, ...
                Start=center - 0.5 * options.AlongTrackSpanMeters * alongTrack, ...
                End=center + 0.5 * options.AlongTrackSpanMeters * alongTrack);
        end

        function geometry = createSourceGeometry(options, trajectory, sensorIndex)
            imageSize = options.SensorImageSize;
            crossTrackIfov = deg2rad(options.CrossTrackFovDegrees) / ...
                max(imageSize(1) - 1, 1);
            platformStep = options.AlongTrackSpanMeters / ...
                max(imageSize(2) - 1, 1);
            geometryData = struct(ImageSize=imageSize, ...
                CenterRow=0.5 * (imageSize(1) + 1), ...
                CenterColumn=0.5 * (imageSize(2) + 1), ...
                CrossTrackIfovRadians=crossTrackIfov, ...
                PlatformStepMeters=platformStep, ...
                ReferenceOrigin=trajectory.Center, ...
                OpticalAxis=trajectory.OpticalAxis, ...
                AlongTrackDirection=trajectory.AlongTrackDirection, ...
                RowAxis=trajectory.RowAxis);
            [origins, rowVectors] = ...
                ProjectionAlignmentObliqueTerrainHarness.geometryPosts( ...
                geometryData, 1:imageSize(1), 1:imageSize(2));
            geometry = struct(ImageSize=imageSize, ...
                CoordinateFrame="synthetic-oblique-terrain", ...
                GSD=options.RangeMeters * crossTrackIfov / ...
                cosd(options.OffNadirDegrees), ...
                NominalRange=options.RangeMeters, ...
                PlatformStepMeters=platformStep, ...
                IFOVRadians=crossTrackIfov, ...
                IFOVDegrees=rad2deg(crossTrackIfov), ...
                ImageCenter=[geometryData.CenterRow geometryData.CenterColumn], ...
                G0=trajectory.Center, ReferenceOrigin=trajectory.Center, ...
                OpticalAxis=trajectory.OpticalAxis, ...
                RowAxis=trajectory.RowAxis, ...
                PlatformDirection=trajectory.AlongTrackDirection, ...
                ImageXAxis=trajectory.AlongTrackDirection, ...
                ImageYAxis=trajectory.RowAxis, Origins=origins, ...
                CameraRays=rowVectors, RowPostIndices=1:imageSize(1), ...
                ColumnPostIndices=1:imageSize(2), ...
                Metadata=struct( ...
                Description="Synthetic oblique pushbroom terrain view", ...
                SensorIndex=sensorIndex, AzimuthDegrees=trajectory.AzimuthDegrees, ...
                ElevationDegrees=trajectory.ElevationDegrees, ...
                OffNadirDegrees=trajectory.OffNadirDegrees, ...
                CPUReferencePath=true));
            geometry.GeometryRevisionToken = ...
                ProjectionGeometryFingerprint.deriveSourceRevision(geometryData);
            geometry.SampleFcn = @(rowIndices, columnIndices) ...
                ProjectionAlignmentObliqueTerrainHarness.sampleGeometry( ...
                geometryData, rowIndices, columnIndices);
            geometry.SampleRayFcn = @(rowPositions, columnPositions) ...
                ProjectionAlignmentObliqueTerrainHarness.sampleRays( ...
                geometryData, rowPositions, columnPositions);
        end

        function [sensorImage, truthView] = renderSensorImage( ...
                texture, geometry, options)
            imageSize = options.SensorImageSize;
            sensorValues = nan(imageSize);
            validMask = false(imageSize);
            groundX = nan(imageSize, "single");
            groundY = nan(imageSize, "single");
            groundZ = nan(imageSize, "single");
            columns = 1:imageSize(2);
            for rowStart = 1:options.RenderChunkRows:imageSize(1)
                rowEnd = min(rowStart + options.RenderChunkRows - 1, ...
                    imageSize(1));
                [rowGrid, columnGrid] = ndgrid(rowStart:rowEnd, columns);
                [origins, vectors] = geometry.SampleRayFcn( ...
                    rowGrid(:), columnGrid(:));
                [groundPoints, valid] = ...
                    ProjectionAlignmentObliqueTerrainHarness.intersectTerrain( ...
                    origins, vectors, options);
                [textureRows, textureColumns] = ...
                    ProjectionAlignmentObliqueTerrainHarness.textureCoordinates( ...
                    groundPoints(1, :), groundPoints(2, :), ...
                    size(texture), options.TargetExtentMeters);
                values = interp2(double(texture), textureColumns, ...
                    textureRows, "linear", NaN);
                valid = valid & isfinite(values);
                values(~valid) = 0;
                chunkSize = [rowEnd - rowStart + 1, imageSize(2)];
                sensorValues(rowStart:rowEnd, :) = reshape(values, chunkSize);
                validMask(rowStart:rowEnd, :) = reshape(valid, chunkSize);
                groundX(rowStart:rowEnd, :) = reshape( ...
                    single(groundPoints(1, :)), chunkSize);
                groundY(rowStart:rowEnd, :) = reshape( ...
                    single(groundPoints(2, :)), chunkSize);
                groundZ(rowStart:rowEnd, :) = reshape( ...
                    single(groundPoints(3, :)), chunkSize);
            end
            sensorImage = ...
                ProjectionAlignmentObliqueTerrainHarness.castImage( ...
                sensorValues, class(texture));
            truthView = struct(LayerId="", ValidMask=validMask, ...
                GroundX=groundX, GroundY=groundY, GroundZ=groundZ, ...
                ValidFraction=nnz(validMask) / numel(validMask));
        end

        function [origins, vectors] = sampleGeometry( ...
                geometryData, rowIndices, columnIndices)
            rowIndices = ...
                ProjectionAlignmentObliqueTerrainHarness.validateSampleIndices( ...
                rowIndices, geometryData.ImageSize(1), "rowIndices", true);
            columnIndices = ...
                ProjectionAlignmentObliqueTerrainHarness.validateSampleIndices( ...
                columnIndices, geometryData.ImageSize(2), ...
                "columnIndices", true);
            [origins, rowVectors] = ...
                ProjectionAlignmentObliqueTerrainHarness.geometryPosts( ...
                geometryData, rowIndices, columnIndices);
            vectors = repmat(reshape(rowVectors, 3, numel(rowIndices), 1), ...
                1, 1, numel(columnIndices));
        end

        function [origins, vectors] = sampleRays( ...
                geometryData, rowPositions, columnPositions)
            rowPositions = ...
                ProjectionAlignmentObliqueTerrainHarness.validateSampleIndices( ...
                rowPositions, geometryData.ImageSize(1), ...
                "rowPositions", false);
            columnPositions = ...
                ProjectionAlignmentObliqueTerrainHarness.validateSampleIndices( ...
                columnPositions, geometryData.ImageSize(2), ...
                "columnPositions", false);
            if numel(rowPositions) ~= numel(columnPositions)
                error("ProjectionAlignmentObliqueTerrainHarness:sampleSizeMismatch", ...
                    "Row and column observation positions must have equal length.");
            end
            [origins, vectors] = ...
                ProjectionAlignmentObliqueTerrainHarness.geometryPosts( ...
                geometryData, rowPositions, columnPositions);
        end

        function [origins, rowVectors] = geometryPosts( ...
                geometryData, rows, columns)
            columnOffsets = (double(columns(:).') - ...
                geometryData.CenterColumn) * geometryData.PlatformStepMeters;
            origins = geometryData.ReferenceOrigin + ...
                geometryData.AlongTrackDirection * columnOffsets;
            rowAngles = (double(rows(:).') - geometryData.CenterRow) * ...
                geometryData.CrossTrackIfovRadians;
            rowVectors = ...
                ProjectionAlignmentObliqueTerrainHarness.rotateAboutAxis( ...
                geometryData.OpticalAxis, ...
                geometryData.AlongTrackDirection, rowAngles);
        end

        function vectors = rotateAboutAxis(vector, axis, angles)
            axis = axis / norm(axis);
            vector = vector / norm(vector);
            crossTerm = cross(axis, vector);
            dotTerm = dot(axis, vector);
            vectors = vector * cos(angles) + crossTerm * sin(angles) + ...
                axis * (dotTerm * (1 - cos(angles)));
            vectors = vectors ./ sqrt(sum(vectors.^2, 1));
        end

        function [points, valid] = intersectTerrain(origins, vectors, options)
            amplitude = options.DemAmplitudeMeters;
            margin = max(10, 0.1 * amplitude);
            vertical = vectors(3, :);
            lower = (amplitude + margin - origins(3, :)) ./ vertical;
            upper = (-amplitude - margin - origins(3, :)) ./ vertical;
            valid = isfinite(lower) & isfinite(upper) & vertical < 0 & ...
                lower > 0 & upper > lower;
            for iteration = 1:options.RayIntersectionIterations
                midpoint = 0.5 * (lower + upper);
                x = origins(1, :) + vectors(1, :) .* midpoint;
                y = origins(2, :) + vectors(2, :) .* midpoint;
                z = origins(3, :) + vectors(3, :) .* midpoint;
                residual = z - ...
                    ProjectionAlignmentObliqueTerrainHarness.terrainHeight( ...
                    x, y, options);
                above = residual > 0;
                lower(above) = midpoint(above);
                upper(~above) = midpoint(~above);
            end
            ranges = 0.5 * (lower + upper);
            points = origins + vectors .* ranges;
            valid = valid & all(isfinite(points), 1);
            points(:, ~valid) = NaN;
        end

        function height = terrainHeight(x, y, options)
            radiusSquared = x.^2 + y.^2;
            envelope = exp(-radiusSquared / ...
                (2 * options.DemEnvelopeSigmaMeters^2));
            height = options.DemAmplitudeMeters * ...
                cos(2 * pi * x / options.DemWavelengthMeters) .* ...
                cos(2 * pi * y / options.DemWavelengthMeters) .* envelope;
        end

        function [textureRows, textureColumns] = textureCoordinates( ...
                x, y, textureSize, extent)
            textureColumns = 1 + (x - extent(1)) / ...
                (extent(2) - extent(1)) * (textureSize(2) - 1);
            textureRows = 1 + (extent(4) - y) / ...
                (extent(4) - extent(3)) * (textureSize(1) - 1);
        end

        function image = castImage(values, imageClass)
            switch imageClass
                case "uint8"
                    image = uint8(min(max(round(values), 0), 255));
                case "uint16"
                    image = uint16(min(max(round(values), 0), 65535));
                case "single"
                    image = single(values);
                otherwise
                    image = cast(values, imageClass);
            end
        end

        function [demX, demY, demZ] = demGrid(options)
            x = linspace(options.TargetExtentMeters(1), ...
                options.TargetExtentMeters(2), options.DemGridSize);
            y = linspace(options.TargetExtentMeters(3), ...
                options.TargetExtentMeters(4), options.DemGridSize);
            [demX, demY] = meshgrid(x, y);
            demZ = ProjectionAlignmentObliqueTerrainHarness.terrainHeight( ...
                demX, demY, options);
        end

        function summary = sceneSummary(rgbImage, sourcePath, options, trajectories)
            summary = struct( ...
                Format=ProjectionAlignmentObliqueTerrainHarness.Format, ...
                Version=ProjectionAlignmentObliqueTerrainHarness.Version, ...
                SourcePath=string(sourcePath), SourceImageSize=size(rgbImage), ...
                SourceBands=["red" "blue"], ...
                SensorImageSize=options.SensorImageSize, ...
                RangeMeters=options.RangeMeters, ...
                OffNadirDegrees=options.OffNadirDegrees, ...
                AzimuthDegrees=options.AzimuthDegrees, ...
                ElevationDegrees=[trajectories.ElevationDegrees], ...
                AzimuthSeparationDegrees=abs(diff(options.AzimuthDegrees)), ...
                AlongTrackSpanMeters=options.AlongTrackSpanMeters, ...
                CrossTrackFovDegrees=options.CrossTrackFovDegrees, ...
                TargetExtentMeters=options.TargetExtentMeters, ...
                DemAmplitudeMeters=options.DemAmplitudeMeters, ...
                DemWavelengthMeters=options.DemWavelengthMeters, ...
                DemEnvelopeSigmaMeters=options.DemEnvelopeSigmaMeters, ...
                DemIsBackendInput=false, Trajectories=trajectories);
        end

        function metrics = matchTruthMetrics(matchResult, truth)
            if ~isstruct(matchResult) || ~isfield(matchResult, "Matches")
                metrics = struct([]);
                return
            end
            metrics = repmat(struct(PairLayerIds=strings(1, 2), Count=0, ...
                ValidTruthCount=0, MedianSeparationMeters=NaN, ...
                P95SeparationMeters=NaN, MaxSeparationMeters=NaN, ...
                FractionWithin10Meters=NaN), 1, numel(matchResult.Matches));
            for pairIndex = 1:numel(matchResult.Matches)
                pairMatch = matchResult.Matches(pairIndex);
                movingTruth = ...
                    ProjectionAlignmentObliqueTerrainHarness.truthViewById( ...
                    truth, pairMatch.MovingLayerId);
                referenceTruth = ...
                    ProjectionAlignmentObliqueTerrainHarness.truthViewById( ...
                    truth, pairMatch.ReferenceLayerId);
                movingPoints = ...
                    ProjectionAlignmentObliqueTerrainHarness.sampleTruthPoints( ...
                    movingTruth, pairMatch.MovingSourceRows, ...
                    pairMatch.MovingSourceColumns);
                referencePoints = ...
                    ProjectionAlignmentObliqueTerrainHarness.sampleTruthPoints( ...
                    referenceTruth, pairMatch.ReferenceSourceRows, ...
                    pairMatch.ReferenceSourceColumns);
                separations = sqrt(sum((movingPoints - referencePoints).^2, 2));
                separations = separations(isfinite(separations));
                metric = metrics(pairIndex);
                metric.PairLayerIds = pairMatch.PairLayerIds;
                metric.Count = pairMatch.Count;
                metric.ValidTruthCount = numel(separations);
                if ~isempty(separations)
                    metric.MedianSeparationMeters = median(separations);
                    metric.P95SeparationMeters = prctile(separations, 95);
                    metric.MaxSeparationMeters = max(separations);
                    metric.FractionWithin10Meters = mean(separations <= 10);
                end
                metrics(pairIndex) = metric;
            end
        end

        function view = truthViewById(truth, layerId)
            matches = string({truth.SensorViews.LayerId}) == string(layerId);
            if nnz(matches) ~= 1
                error("ProjectionAlignmentObliqueTerrainHarness:unknownLayerId", ...
                    "Truth data has no unique view for layer ID %s.", layerId);
            end
            view = truth.SensorViews(find(matches, 1, "first"));
        end

        function points = sampleTruthPoints(view, rows, columns)
            points = nan(numel(rows), 3);
            maps = {view.GroundX, view.GroundY, view.GroundZ};
            for componentIndex = 1:3
                points(:, componentIndex) = interp2(double(maps{componentIndex}), ...
                    double(columns(:)), double(rows(:)), "linear", NaN);
            end
        end

        function image = scaleSignedImage(values, limit)
            if ~isfinite(limit) || limit <= 0
                image = zeros(size(values), "uint8");
                return
            end
            normalized = 0.5 + 0.5 * double(values) / double(limit);
            image = uint8(round(255 * min(max(normalized, 0), 1)));
        end

        function validateRgbImage(image)
            if ~isnumeric(image) || ndims(image) ~= 3 || size(image, 3) < 3 || ...
                    isempty(image) || any(~isfinite(double(image)), "all")
                error("ProjectionAlignmentObliqueTerrainHarness:invalidRgbImage", ...
                    "Input must be a finite, nonempty numeric image with at least three bands.");
            end
        end

        function indices = validateSampleIndices(indices, maximum, name, integerOnly)
            if ~isnumeric(indices) || ~isvector(indices) || isempty(indices) || ...
                    any(~isfinite(indices)) || any(indices < 1) || ...
                    any(indices > maximum) || ...
                    (integerOnly && any(fix(indices) ~= indices))
                error("ProjectionAlignmentObliqueTerrainHarness:invalidSampleIndices", ...
                    "%s must lie within the sensor image.", name);
            end
            indices = double(indices(:).');
        end

        function value = validatePositiveScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value <= 0
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "%s must be a positive finite scalar.", name);
            end
            value = double(value);
        end

        function value = validatePositiveInteger(value, name, minimum)
            value = ProjectionAlignmentObliqueTerrainHarness.validatePositiveScalar( ...
                value, name);
            if fix(value) ~= value || value < minimum
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "%s must be an integer of at least %d.", name, minimum);
            end
        end

        function values = validateIntegerVector(values, count, name, minimum)
            values = ProjectionAlignmentObliqueTerrainHarness.validateFiniteVector( ...
                values, count, name);
            if any(fix(values) ~= values) || any(values < minimum)
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "%s values must be integers of at least %d.", name, minimum);
            end
        end

        function values = validateFiniteVector(values, count, name)
            if ~isnumeric(values) || numel(values) ~= count || ...
                    any(~isfinite(values))
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "%s must be a finite %d-vector.", name, count);
            end
            values = double(values(:).');
        end

        function value = validateScalarRange(value, name, lower, upper)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value <= lower || value >= upper
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "%s must lie strictly between %g and %g.", ...
                    name, lower, upper);
            end
            value = double(value);
        end

        function extent = validateExtent(extent)
            extent = ProjectionAlignmentObliqueTerrainHarness.validateFiniteVector( ...
                extent, 4, "TargetExtentMeters");
            if extent(2) <= extent(1) || extent(4) <= extent(3)
                error("ProjectionAlignmentObliqueTerrainHarness:invalidOptions", ...
                    "TargetExtentMeters must contain increasing X and Y bounds.");
            end
        end

        function validateTruth(truth)
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    ~isfield(truth, "Format") || ...
                    string(truth.Format) ~= ...
                    ProjectionAlignmentObliqueTerrainHarness.Format + "Truth" || ...
                    ~isfield(truth, "SensorViews")
                error("ProjectionAlignmentObliqueTerrainHarness:invalidTruth", ...
                    "Truth data must come from the oblique terrain harness.");
            end
        end

        function trajectory = emptyTrajectory()
            trajectory = struct(AzimuthDegrees=0, ElevationDegrees=0, ...
                OffNadirDegrees=0, RangeMeters=0, Center=zeros(3, 1), ...
                AlongTrackDirection=zeros(3, 1), ...
                RadialDirection=zeros(3, 1), OpticalAxis=zeros(3, 1), ...
                RowAxis=zeros(3, 1), Start=zeros(3, 1), End=zeros(3, 1));
        end

        function view = emptyTruthView()
            view = struct(LayerId="", ValidMask=false(0), ...
                GroundX=single.empty(0), GroundY=single.empty(0), ...
                GroundZ=single.empty(0), ValidFraction=0);
        end
    end
end
