classdef ProjectionAlignmentOptions
    %ProjectionAlignmentOptions Validate alignment engine option structs.

    properties (Constant)
        Format = "ProjectionAlignmentOptions"
        Version = 1
    end

    methods (Static)
        function options = defaults()
            %defaults Return normalized default alignment options.
            options = ProjectionAlignmentOptions.validate(struct());
        end

        function options = validate(options)
            %validate Normalize and validate alignment options.
            if nargin < 1 || isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionAlignmentOptions:invalidOptions", ...
                    "Alignment options must be a scalar struct.");
            end

            options.Format = ProjectionAlignmentOptions.Format;
            options.Version = ProjectionAlignmentOptions.Version;
            options.Detector = ProjectionAlignmentOptions.validateDetector( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Detector", struct()));
            options.Matcher = ProjectionAlignmentOptions.validateMatcher( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Matcher", struct()));
            options.FilterPipeline = ProjectionAlignmentOptions.validateFilterPipeline( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "FilterPipeline", struct()));
            options.LossMode = ProjectionAlignmentOptions.validateChoice( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "LossMode", ...
                "projectionPlane2D"), ["projectionPlane2D", "rayToRay3D", ...
                "epipolarCoplanarity"], ...
                "LossMode");
            options.Scheduling = ProjectionAlignmentOptions.validateScheduling( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Scheduling", struct()));
            options.Network = ProjectionAlignmentOptions.validateNetwork( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "Network", struct()));
            options.SourceRefinement = ...
                ProjectionAlignmentOptions.validateSourceRefinement( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "SourceRefinement", struct()));
            options.EvidenceSelection = ...
                ProjectionAlignmentOptions.validateEvidenceSelection( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "EvidenceSelection", struct()));
            options.MovableParameters = ProjectionAlignmentOptions.validateMovableParameters( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "MovableParameters", struct()));
            options.Bounds = ProjectionAlignmentOptions.validateBounds( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Bounds", struct()));
            options.Regularization = ProjectionAlignmentOptions.validateRegularization( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "Regularization", struct()));
            options.PointingPriors = ...
                ProjectionAlignmentOptions.validatePointingPriors( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "PointingPriors", struct()));
            options.SafeSolvePolicy = ...
                ProjectionAlignmentOptions.validateSafeSolvePolicy( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, ...
                "SafeSolvePolicy", struct()));
            options.Diagnostics = ProjectionAlignmentOptions.validateDiagnostics( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Diagnostics", struct()));
            options.Execution = ProjectionAlignmentOptions.validateExecution( ...
                ProjectionAlignmentOptions.fieldOrDefault(options, "Execution", struct()));
        end

        function jsonOptions = toJsonStruct(options)
            %toJsonStruct Return the JSON-compatible subset of options.
            jsonOptions = ProjectionAlignmentOptions.validate(options);
            if ~isempty(jsonOptions.FilterPipeline.RadialFilterFcn)
                error("ProjectionAlignmentOptions:nonSerializableFilter", ...
                    "FilterPipeline.RadialFilterFcn must be empty before JSON serialization.");
            end
        end

        function jsonText = encode(options)
            %encode Convert alignment options to pretty JSON text.
            jsonText = jsonencode(ProjectionAlignmentOptions.toJsonStruct(options), ...
                PrettyPrint=true);
        end

        function options = decode(jsonText)
            %decode Decode alignment options JSON.
            options = ProjectionAlignmentOptions.validate(jsondecode(jsonText));
        end

        function write(filePath, options)
            %write Save alignment options as JSON.
            ProjectionAlignmentOptions.writeTextFile(filePath, ...
                ProjectionAlignmentOptions.encode(options));
        end

        function options = read(filePath)
            %read Load alignment options from JSON.
            filePath = ProjectionAlignmentOptions.validateFilePath(filePath);
            options = ProjectionAlignmentOptions.decode(fileread(filePath));
        end
    end

    methods (Static, Access = private)
        function detector = validateDetector(detector)
            defaults = struct();
            defaults.Method = "auto";
            defaults.MaxFeatures = 384;
            defaults.MetricThreshold = [];
            defaults.AnalysisBand = 1;
            defaults.AnalysisScale = 1;
            defaults.MaskSupportRadiusPixels = [];
            detector = ProjectionAlignmentOptions.mergeStruct(defaults, detector, ...
                "Detector");
            detector.Method = ProjectionAlignmentOptions.validateChoice( ...
                detector.Method, ["auto", "sift", "surf", "orb", "brisk", ...
                "kaze"], "Detector.Method");
            detector.MaxFeatures = ProjectionAlignmentOptions.validatePositiveInteger( ...
                detector.MaxFeatures, "Detector.MaxFeatures");
            detector.MetricThreshold = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                detector.MetricThreshold, "Detector.MetricThreshold");
            detector.AnalysisBand = ProjectionAlignmentOptions.validatePositiveInteger( ...
                detector.AnalysisBand, "Detector.AnalysisBand");
            detector.AnalysisScale = ProjectionAlignmentOptions.validatePositiveScalar( ...
                detector.AnalysisScale, "Detector.AnalysisScale");
            if detector.AnalysisScale > 1
                error("ProjectionAlignmentOptions:invalidDetector", ...
                    "Detector.AnalysisScale must be in the range (0, 1].");
            end
            detector.MaskSupportRadiusPixels = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                detector.MaskSupportRadiusPixels, ...
                "Detector.MaskSupportRadiusPixels");
        end

        function matcher = validateMatcher(matcher)
            defaults = struct();
            defaults.Method = "exhaustive";
            defaults.MatchThreshold = [];
            defaults.MaxRatio = 0.8;
            defaults.Unique = true;
            matcher = ProjectionAlignmentOptions.mergeStruct(defaults, matcher, ...
                "Matcher");
            matcher.Method = ProjectionAlignmentOptions.validateChoice( ...
                matcher.Method, ["nearestNeighborRatio", "exhaustive"], ...
                "Matcher.Method");
            matcher.MatchThreshold = ...
                ProjectionAlignmentOptions.validateOptionalPercentage( ...
                matcher.MatchThreshold, "Matcher.MatchThreshold");
            matcher.MaxRatio = ProjectionAlignmentOptions.validateFraction( ...
                matcher.MaxRatio, "Matcher.MaxRatio");
            matcher.Unique = ProjectionAlignmentOptions.validateLogicalScalar( ...
                matcher.Unique, "Matcher.Unique");
        end

        function pipeline = validateFilterPipeline(pipeline)
            defaults = struct();
            defaults.Stages = ["overlapMask", "descriptorScore", "ratio", ...
                "geometricOutlier", "epipolarCoplanarity", ...
                "nativeDisplacement", "radial"];
            defaults.UseOverlapMask = true;
            defaults.MinMatchScore = [];
            defaults.MaxDescriptorRatio = [];
            defaults.GeometricMethod = "none";
            defaults.GeometricMaxDistancePixels = 3;
            defaults.CoplanarityMethod = "none";
            defaults.CoplanarityMadScale = 8;
            defaults.CoplanarityMinResidual = 1e-4;
            defaults.CoplanarityMaxResidual = [];
            defaults.NativeDisplacementMethod = "none";
            defaults.NativeMaxDisplacementPixels = [];
            defaults.NativeMadScale = 8;
            defaults.NativeMinResidualPixels = 5;
            defaults.RadialFilterFcn = [];
            defaults.RadialFilterName = "";
            pipeline = ProjectionAlignmentOptions.mergeStruct(defaults, pipeline, ...
                "FilterPipeline");
            pipeline.Stages = ProjectionAlignmentOptions.validateStringChoices( ...
                pipeline.Stages, ["overlapMask", "descriptorScore", "ratio", ...
                "geometricOutlier", "epipolarCoplanarity", ...
                "nativeDisplacement", "radial"], ...
                "FilterPipeline.Stages");
            pipeline.UseOverlapMask = ProjectionAlignmentOptions.validateLogicalScalar( ...
                pipeline.UseOverlapMask, "FilterPipeline.UseOverlapMask");
            pipeline.MinMatchScore = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                pipeline.MinMatchScore, "FilterPipeline.MinMatchScore");
            pipeline.MaxDescriptorRatio = ...
                ProjectionAlignmentOptions.validateOptionalFraction( ...
                pipeline.MaxDescriptorRatio, ...
                "FilterPipeline.MaxDescriptorRatio");
            pipeline.GeometricMethod = ProjectionAlignmentOptions.validateChoice( ...
                pipeline.GeometricMethod, ["none", "similarity", "affine"], ...
                "FilterPipeline.GeometricMethod");
            pipeline.GeometricMaxDistancePixels = ...
                ProjectionAlignmentOptions.validatePositiveScalar( ...
                pipeline.GeometricMaxDistancePixels, ...
                "FilterPipeline.GeometricMaxDistancePixels");
            pipeline.CoplanarityMethod = ProjectionAlignmentOptions.validateChoice( ...
                pipeline.CoplanarityMethod, ["none", "robustMad"], ...
                "FilterPipeline.CoplanarityMethod");
            pipeline.CoplanarityMadScale = ...
                ProjectionAlignmentOptions.validatePositiveScalar( ...
                pipeline.CoplanarityMadScale, ...
                "FilterPipeline.CoplanarityMadScale");
            pipeline.CoplanarityMinResidual = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                pipeline.CoplanarityMinResidual, ...
                "FilterPipeline.CoplanarityMinResidual");
            pipeline.CoplanarityMaxResidual = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                pipeline.CoplanarityMaxResidual, ...
                "FilterPipeline.CoplanarityMaxResidual");
            pipeline.NativeDisplacementMethod = ...
                ProjectionAlignmentOptions.validateChoice( ...
                pipeline.NativeDisplacementMethod, ["none", "mad"], ...
                "FilterPipeline.NativeDisplacementMethod");
            pipeline.NativeMaxDisplacementPixels = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                pipeline.NativeMaxDisplacementPixels, ...
                "FilterPipeline.NativeMaxDisplacementPixels");
            pipeline.NativeMadScale = ProjectionAlignmentOptions.validatePositiveScalar( ...
                pipeline.NativeMadScale, "FilterPipeline.NativeMadScale");
            pipeline.NativeMinResidualPixels = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                pipeline.NativeMinResidualPixels, ...
                "FilterPipeline.NativeMinResidualPixels");
            pipeline.RadialFilterFcn = ProjectionAlignmentOptions.validateFilterFcn( ...
                pipeline.RadialFilterFcn);
            pipeline.RadialFilterName = ...
                ProjectionAlignmentOptions.validateOptionalScalarString( ...
                pipeline.RadialFilterName, "FilterPipeline.RadialFilterName");
        end

        function scheduling = validateScheduling(scheduling)
            defaults = struct();
            defaults.Strategy = "qualityGraph";
            defaults.ReferenceLayerIndex = [];
            defaults.PairSelection = "visible";
            defaults.IncludeHiddenLayers = false;
            defaults.QualitySpeed = "balanced";
            defaults.MaxPairs = [];
            defaults.AllPlausiblePairs = false;
            defaults.ForcedIncludePairIds = strings(1, 0);
            defaults.ForcedExcludePairIds = strings(1, 0);
            scheduling = ProjectionAlignmentOptions.mergeStruct(defaults, scheduling, ...
                "Scheduling");
            scheduling.Strategy = ProjectionAlignmentOptions.validateChoice( ...
                scheduling.Strategy, ["centerOut", "centerStar", ...
                "adjacentChain", "hybrid", "twoImage", "qualityGraph"], ...
                "Scheduling.Strategy");
            scheduling.ReferenceLayerIndex = ...
                ProjectionAlignmentOptions.validateOptionalPositiveInteger( ...
                scheduling.ReferenceLayerIndex, "Scheduling.ReferenceLayerIndex");
            scheduling.PairSelection = ProjectionAlignmentOptions.validateChoice( ...
                scheduling.PairSelection, ["visible", "selected", "all"], ...
                "Scheduling.PairSelection");
            scheduling.IncludeHiddenLayers = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                scheduling.IncludeHiddenLayers, "Scheduling.IncludeHiddenLayers");
            scheduling.QualitySpeed = ProjectionAlignmentOptions.validateChoice( ...
                scheduling.QualitySpeed, ["fast", "balanced", "quality"], ...
                "Scheduling.QualitySpeed");
            scheduling.MaxPairs = ...
                ProjectionAlignmentOptions.validateOptionalPositiveInteger( ...
                scheduling.MaxPairs, "Scheduling.MaxPairs");
            scheduling.AllPlausiblePairs = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                scheduling.AllPlausiblePairs, ...
                "Scheduling.AllPlausiblePairs");
            scheduling.ForcedIncludePairIds = ...
                ProjectionAlignmentOptions.validateStringVector( ...
                scheduling.ForcedIncludePairIds, ...
                "Scheduling.ForcedIncludePairIds");
            scheduling.ForcedExcludePairIds = ...
                ProjectionAlignmentOptions.validateStringVector( ...
                scheduling.ForcedExcludePairIds, ...
                "Scheduling.ForcedExcludePairIds");
            if any(ismember(scheduling.ForcedIncludePairIds, ...
                    scheduling.ForcedExcludePairIds))
                error("ProjectionAlignmentOptions:invalidScheduling", ...
                    "A pair cannot be both forcibly included and excluded.");
            end
        end

        function network = validateNetwork(network)
            legacyFieldProvided = isstruct(network) && ...
                isfield(network, "ComputeLeaveOnePairOut");
            policyFieldProvided = isstruct(network) && ...
                isfield(network, "LeaveOnePairOutPolicy");
            defaults = struct(Enabled=false, ...
                GaugePolicy="balancedPriors", FixedReferenceViewId="", ...
                UseUniqueTrackEvidence=true, RobustScaleMode="auto", ...
                RobustScaleBounds=[1e-6 0.05], ...
                Configuration="multiplePasses", ...
                PassCommonSigmaDegrees=[1 1 1], ...
                DifferentialSigmaDegrees=[1 1 1], ...
                ComputeLeaveOnePairOut=false, ...
                LeaveOnePairOutPolicy="deferred", ...
                MaximumLeaveOnePairOutChildren=3, ...
                LeaveOnePairOutTimeBudgetSeconds=15, ...
                EvidenceMode="compiled", ...
                JacobianMethod="semiAnalytic");
            network = ProjectionAlignmentOptions.mergeStruct( ...
                defaults, network, "Network");
            network.Enabled = ProjectionAlignmentOptions.validateLogicalScalar( ...
                network.Enabled, "Network.Enabled");
            network.GaugePolicy = ProjectionAlignmentOptions.validateChoice( ...
                network.GaugePolicy, ["balancedPriors", "fixedReference"], ...
                "Network.GaugePolicy");
            network.FixedReferenceViewId = ...
                ProjectionAlignmentOptions.validateOptionalScalarString( ...
                network.FixedReferenceViewId, "Network.FixedReferenceViewId");
            network.UseUniqueTrackEvidence = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                network.UseUniqueTrackEvidence, ...
                "Network.UseUniqueTrackEvidence");
            network.RobustScaleMode = ProjectionAlignmentOptions.validateChoice( ...
                network.RobustScaleMode, ["auto", "fixed"], ...
                "Network.RobustScaleMode");
            network.RobustScaleBounds = ProjectionAlignmentOptions.validateRange( ...
                network.RobustScaleBounds, "Network.RobustScaleBounds");
            network.Configuration = ProjectionAlignmentOptions.validateChoice( ...
                network.Configuration, ["singlePass", "multiplePasses", ...
                "independentViewsCustomPriors"], "Network.Configuration");
            network.PassCommonSigmaDegrees = ...
                ProjectionAlignmentOptions.validatePositiveVector( ...
                network.PassCommonSigmaDegrees, 3, ...
                "Network.PassCommonSigmaDegrees");
            network.DifferentialSigmaDegrees = ...
                ProjectionAlignmentOptions.validatePositiveVector( ...
                network.DifferentialSigmaDegrees, 3, ...
                "Network.DifferentialSigmaDegrees");
            network.ComputeLeaveOnePairOut = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                network.ComputeLeaveOnePairOut, ...
                "Network.ComputeLeaveOnePairOut");
            network.LeaveOnePairOutPolicy = ...
                ProjectionAlignmentOptions.validateChoice( ...
                network.LeaveOnePairOutPolicy, ...
                ["notRequested", "deferred", "bounded", "exhaustive"], ...
                "Network.LeaveOnePairOutPolicy");
            if legacyFieldProvided && ~policyFieldProvided
                if network.ComputeLeaveOnePairOut
                    network.LeaveOnePairOutPolicy = "exhaustive";
                else
                    network.LeaveOnePairOutPolicy = "notRequested";
                end
            end
            network.ComputeLeaveOnePairOut = ismember( ...
                network.LeaveOnePairOutPolicy, ["bounded", "exhaustive"]);
            network.MaximumLeaveOnePairOutChildren = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                network.MaximumLeaveOnePairOutChildren, ...
                "Network.MaximumLeaveOnePairOutChildren");
            network.LeaveOnePairOutTimeBudgetSeconds = ...
                ProjectionAlignmentOptions.validatePositiveScalar( ...
                network.LeaveOnePairOutTimeBudgetSeconds, ...
                "Network.LeaveOnePairOutTimeBudgetSeconds");
            network.EvidenceMode = ProjectionAlignmentOptions.validateChoice( ...
                network.EvidenceMode, ["compiled", "reference"], ...
                "Network.EvidenceMode");
            network.JacobianMethod = ProjectionAlignmentOptions.validateChoice( ...
                network.JacobianMethod, ["semiAnalytic", "finiteDifference"], ...
                "Network.JacobianMethod");
            if network.GaugePolicy == "fixedReference" && ...
                    strlength(network.FixedReferenceViewId) == 0
                error("ProjectionAlignmentOptions:invalidNetwork", ...
                    "Fixed-reference gauge requires FixedReferenceViewId.");
            end
        end

        function refinement = validateSourceRefinement(refinement)
            defaults = struct(Enabled=true, PatchRadiusPixels=5, ...
                SearchRadiusPixels=2, MinimumCorrelation=0.65, ...
                MinimumPeakMargin=0.02, MinimumTextureStandardDeviation=0.01, ...
                EnableSubpixel=true, UncertaintyFloorPixels=0.20);
            refinement = ProjectionAlignmentOptions.mergeStruct( ...
                defaults, refinement, "SourceRefinement");
            refinement.Enabled = ProjectionAlignmentOptions.validateLogicalScalar( ...
                refinement.Enabled, "SourceRefinement.Enabled");
            refinement.PatchRadiusPixels = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                refinement.PatchRadiusPixels, ...
                "SourceRefinement.PatchRadiusPixels");
            refinement.SearchRadiusPixels = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                refinement.SearchRadiusPixels, ...
                "SourceRefinement.SearchRadiusPixels");
            refinement.MinimumCorrelation = ...
                ProjectionAlignmentOptions.validateFraction( ...
                refinement.MinimumCorrelation, ...
                "SourceRefinement.MinimumCorrelation");
            refinement.MinimumPeakMargin = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                refinement.MinimumPeakMargin, ...
                "SourceRefinement.MinimumPeakMargin");
            refinement.MinimumTextureStandardDeviation = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                refinement.MinimumTextureStandardDeviation, ...
                "SourceRefinement.MinimumTextureStandardDeviation");
            refinement.EnableSubpixel = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                refinement.EnableSubpixel, ...
                "SourceRefinement.EnableSubpixel");
            refinement.UncertaintyFloorPixels = ...
                ProjectionAlignmentOptions.validatePositiveScalar( ...
                refinement.UncertaintyFloorPixels, ...
                "SourceRefinement.UncertaintyFloorPixels");
        end

        function selection = validateEvidenceSelection(selection)
            defaults = struct(Enabled=true, MaximumPerPair=64, ...
                SpatialGridSize=[8 8], MinimumCoverageFraction=0.50, ...
                InformationWeight=0.25);
            selection = ProjectionAlignmentOptions.mergeStruct( ...
                defaults, selection, "EvidenceSelection");
            selection.Enabled = ProjectionAlignmentOptions.validateLogicalScalar( ...
                selection.Enabled, "EvidenceSelection.Enabled");
            selection.MaximumPerPair = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                selection.MaximumPerPair, ...
                "EvidenceSelection.MaximumPerPair");
            selection.SpatialGridSize = ...
                ProjectionAlignmentOptions.validatePositiveVector( ...
                selection.SpatialGridSize, 2, ...
                "EvidenceSelection.SpatialGridSize");
            if any(fix(selection.SpatialGridSize) ~= selection.SpatialGridSize)
                error("ProjectionAlignmentOptions:invalidEvidenceSelection", ...
                    "EvidenceSelection.SpatialGridSize must contain integers.");
            end
            selection.MinimumCoverageFraction = ...
                ProjectionAlignmentOptions.validateFraction( ...
                selection.MinimumCoverageFraction, ...
                "EvidenceSelection.MinimumCoverageFraction");
            selection.InformationWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                selection.InformationWeight, ...
                "EvidenceSelection.InformationWeight");
        end

        function movable = validateMovableParameters(movable)
            defaults = struct();
            defaults.Parameters = ["omega", "phi", "kappa"];
            defaults.AllowReferenceMotion = true;
            defaults.IncludeProjectionOffsets = false;
            defaults.IncludeSharedScale = false;
            movable = ProjectionAlignmentOptions.mergeStruct(defaults, movable, ...
                "MovableParameters");
            movable.Parameters = ProjectionAlignmentOptions.validateStringChoices( ...
                movable.Parameters, ["omega", "phi", "kappa", ...
                "projectionOffsetX", "projectionOffsetY", "sharedScale"], ...
                "MovableParameters.Parameters");
            movable.AllowReferenceMotion = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                movable.AllowReferenceMotion, ...
                "MovableParameters.AllowReferenceMotion");
            movable.IncludeProjectionOffsets = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                movable.IncludeProjectionOffsets, ...
                "MovableParameters.IncludeProjectionOffsets");
            movable.IncludeSharedScale = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                movable.IncludeSharedScale, ...
                "MovableParameters.IncludeSharedScale");
            if movable.IncludeProjectionOffsets
                movable.Parameters = unique([movable.Parameters, ...
                    "projectionOffsetX", "projectionOffsetY"], "stable");
            elseif any(ismember(movable.Parameters, ...
                    ["projectionOffsetX", "projectionOffsetY"]))
                movable.IncludeProjectionOffsets = true;
            end
            if movable.IncludeSharedScale
                movable.Parameters = unique([movable.Parameters, ...
                    "sharedScale"], "stable");
            elseif ismember("sharedScale", movable.Parameters)
                movable.IncludeSharedScale = true;
            end
        end

        function bounds = validateBounds(bounds)
            defaults = struct();
            defaults.FieldOfViewFraction = 0.25;
            defaults.OmegaDegrees = [];
            defaults.PhiDegrees = [];
            defaults.KappaDegrees = [];
            defaults.ProjectionOffsetMeters = [];
            defaults.SharedScale = [0.95 1.05];
            bounds = ProjectionAlignmentOptions.mergeStruct(defaults, bounds, "Bounds");
            bounds.FieldOfViewFraction = ProjectionAlignmentOptions.validateFraction( ...
                bounds.FieldOfViewFraction, "Bounds.FieldOfViewFraction");
            bounds.OmegaDegrees = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                bounds.OmegaDegrees, "Bounds.OmegaDegrees");
            bounds.PhiDegrees = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                bounds.PhiDegrees, "Bounds.PhiDegrees");
            bounds.KappaDegrees = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeScalar( ...
                bounds.KappaDegrees, "Bounds.KappaDegrees");
            bounds.ProjectionOffsetMeters = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeVector( ...
                bounds.ProjectionOffsetMeters, 2, ...
                "Bounds.ProjectionOffsetMeters");
            bounds.SharedScale = ProjectionAlignmentOptions.validateRange( ...
                bounds.SharedScale, "Bounds.SharedScale");
        end

        function regularization = validateRegularization(regularization)
            defaults = struct();
            defaults.OverallWeight = 1e-3;
            defaults.OmegaWeight = 1;
            defaults.PhiWeight = 1;
            defaults.KappaWeight = 1;
            defaults.ProjectionOffsetWeight = 1;
            defaults.SharedScaleWeight = 1;
            defaults.RobustLoss = "huber";
            defaults.RobustScale = 1;
            regularization = ProjectionAlignmentOptions.mergeStruct(defaults, ...
                regularization, "Regularization");
            regularization.OverallWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.OverallWeight, "Regularization.OverallWeight");
            regularization.OmegaWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.OmegaWeight, "Regularization.OmegaWeight");
            regularization.PhiWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.PhiWeight, "Regularization.PhiWeight");
            regularization.KappaWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.KappaWeight, "Regularization.KappaWeight");
            regularization.ProjectionOffsetWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.ProjectionOffsetWeight, ...
                "Regularization.ProjectionOffsetWeight");
            regularization.SharedScaleWeight = ...
                ProjectionAlignmentOptions.validateNonnegativeScalar( ...
                regularization.SharedScaleWeight, ...
                "Regularization.SharedScaleWeight");
            regularization.RobustLoss = ProjectionAlignmentOptions.validateChoice( ...
                regularization.RobustLoss, ...
                ["none", "huber", "bisquare", "cauchy"], ...
                "Regularization.RobustLoss");
            regularization.RobustScale = ProjectionAlignmentOptions.validatePositiveScalar( ...
                regularization.RobustScale, "Regularization.RobustScale");
        end

        function priors = validatePointingPriors(priors)
            defaults = struct();
            defaults.DefaultSigmaDegrees = [1 1 1];
            defaults.LayerIds = strings(1, 0);
            defaults.SigmaDegrees = zeros(0, 3);
            priors = ProjectionAlignmentOptions.mergeStruct(defaults, priors, ...
                "PointingPriors");
            priors.DefaultSigmaDegrees = ...
                ProjectionAlignmentOptions.validatePositiveVector( ...
                priors.DefaultSigmaDegrees, 3, ...
                "PointingPriors.DefaultSigmaDegrees");
            priors.LayerIds = reshape(string(priors.LayerIds), 1, []);
            if any(strlength(priors.LayerIds) == 0) || ...
                    numel(unique(priors.LayerIds)) ~= numel(priors.LayerIds)
                error("ProjectionAlignmentOptions:invalidPointingPriors", ...
                    "PointingPriors.LayerIds must contain unique nonempty IDs.");
            end
            sigma = priors.SigmaDegrees;
            if isempty(sigma)
                sigma = zeros(0, 3);
            end
            if ~isnumeric(sigma) || size(sigma, 2) ~= 3 || ...
                    any(~isfinite(sigma), "all") || any(sigma <= 0, "all") || ...
                    size(sigma, 1) ~= numel(priors.LayerIds)
                error("ProjectionAlignmentOptions:invalidPointingPriors", ...
                    "PointingPriors.SigmaDegrees must be a positive finite N-by-3 array matching LayerIds.");
            end
            priors.SigmaDegrees = double(sigma);
        end

        function diagnostics = validateDiagnostics(diagnostics)
            defaults = struct();
            defaults.StoreMatches = true;
            defaults.StoreInliers = true;
            defaults.StoreResiduals = true;
            defaults.StoreTiming = true;
            defaults.StoreWorkingImages = false;
            defaults.Verbose = false;
            diagnostics = ProjectionAlignmentOptions.mergeStruct(defaults, ...
                diagnostics, "Diagnostics");
            diagnostics.StoreMatches = ProjectionAlignmentOptions.validateLogicalScalar( ...
                diagnostics.StoreMatches, "Diagnostics.StoreMatches");
            diagnostics.StoreInliers = ProjectionAlignmentOptions.validateLogicalScalar( ...
                diagnostics.StoreInliers, "Diagnostics.StoreInliers");
            diagnostics.StoreResiduals = ProjectionAlignmentOptions.validateLogicalScalar( ...
                diagnostics.StoreResiduals, "Diagnostics.StoreResiduals");
            diagnostics.StoreTiming = ProjectionAlignmentOptions.validateLogicalScalar( ...
                diagnostics.StoreTiming, "Diagnostics.StoreTiming");
            diagnostics.StoreWorkingImages = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                diagnostics.StoreWorkingImages, "Diagnostics.StoreWorkingImages");
            verboseValue = ProjectionAlignmentOptions.fieldOrDefault( ...
                diagnostics, "Verbose", false);
            if isfield(diagnostics, "Verose") && ~isfield(diagnostics, "Verbose")
                verboseValue = diagnostics.Verose;
            end
            diagnostics.Verbose = ProjectionAlignmentOptions.validateLogicalScalar( ...
                verboseValue, "Diagnostics.Verbose");
            if isfield(diagnostics, "Verose")
                diagnostics = rmfield(diagnostics, "Verose");
            end
        end

        function policy = validateSafeSolvePolicy(policy)
            if isstruct(policy) && isscalar(policy) && ...
                    isfield(policy, "MinResidualImprovementFraction")
                if ~isfield(policy, "PreferredResidualImprovementFraction")
                    policy.PreferredResidualImprovementFraction = ...
                        policy.MinResidualImprovementFraction;
                end
                policy = rmfield(policy, "MinResidualImprovementFraction");
            end
            defaults = struct();
            defaults.Enabled = true;
            defaults.MinSolverObservationsPerPair = 3;
            defaults.MinPreferredObservationsPerPair = 10;
            defaults.FailOnBoundHit = true;
            defaults.PreferredResidualImprovementFraction = 0.10;
            defaults.MaximumResidualDegradationFraction = 0.01;
            defaults.MaximumConditionNumber = [];
            defaults.MaximumAttitudeStandardDeviationDegrees = [];
            policy = ProjectionAlignmentOptions.mergeStruct(defaults, policy, ...
                "SafeSolvePolicy");
            policy.Enabled = ProjectionAlignmentOptions.validateLogicalScalar( ...
                policy.Enabled, "SafeSolvePolicy.Enabled");
            policy.MinSolverObservationsPerPair = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                policy.MinSolverObservationsPerPair, ...
                "SafeSolvePolicy.MinSolverObservationsPerPair");
            policy.MinPreferredObservationsPerPair = ...
                ProjectionAlignmentOptions.validatePositiveInteger( ...
                policy.MinPreferredObservationsPerPair, ...
                "SafeSolvePolicy.MinPreferredObservationsPerPair");
            if policy.MinPreferredObservationsPerPair < ...
                    policy.MinSolverObservationsPerPair
                error("ProjectionAlignmentOptions:invalidInteger", ...
                    "SafeSolvePolicy.MinPreferredObservationsPerPair must be greater than or equal to MinSolverObservationsPerPair.");
            end
            policy.FailOnBoundHit = ...
                ProjectionAlignmentOptions.validateLogicalScalar( ...
                policy.FailOnBoundHit, "SafeSolvePolicy.FailOnBoundHit");
            policy.PreferredResidualImprovementFraction = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeFraction( ...
                policy.PreferredResidualImprovementFraction, ...
                "SafeSolvePolicy.PreferredResidualImprovementFraction");
            policy.MaximumResidualDegradationFraction = ...
                ProjectionAlignmentOptions.validateOptionalNonnegativeFraction( ...
                policy.MaximumResidualDegradationFraction, ...
                "SafeSolvePolicy.MaximumResidualDegradationFraction");
            policy.MaximumConditionNumber = ...
                ProjectionAlignmentOptions.validateOptionalPositiveScalar( ...
                policy.MaximumConditionNumber, ...
                "SafeSolvePolicy.MaximumConditionNumber");
            policy.MaximumAttitudeStandardDeviationDegrees = ...
                ProjectionAlignmentOptions.validateOptionalPositiveScalar( ...
                policy.MaximumAttitudeStandardDeviationDegrees, ...
                "SafeSolvePolicy.MaximumAttitudeStandardDeviationDegrees");
        end

        function execution = validateExecution(execution)
            defaults = struct();
            defaults.Mode = "serial";
            defaults.UseGPU = false;
            execution = ProjectionAlignmentOptions.mergeStruct(defaults, execution, ...
                "Execution");
            execution.Mode = ProjectionAlignmentOptions.validateChoice( ...
                execution.Mode, ["serial", "threads"], "Execution.Mode");
            execution.UseGPU = ProjectionAlignmentOptions.validateLogicalScalar( ...
                execution.UseGPU, "Execution.UseGPU");
        end

        function value = validateChoice(value, allowed, name)
            value = ProjectionAlignmentOptions.validateScalarString(value, name);
            matches = lower(value) == lower(allowed);
            if ~any(matches)
                error("ProjectionAlignmentOptions:invalidChoice", ...
                    "%s must be one of: %s.", name, strjoin(allowed, ", "));
            end
            value = allowed(find(matches, 1, "first"));
        end

        function values = validateStringChoices(values, allowed, name)
            values = string(values);
            values = reshape(values, 1, []);
            if isempty(values) || any(strlength(values) == 0)
                error("ProjectionAlignmentOptions:invalidChoice", ...
                    "%s must contain nonempty string values.", name);
            end
            for k = 1:numel(values)
                values(k) = ProjectionAlignmentOptions.validateChoice( ...
                    values(k), allowed, name);
            end
        end

        function value = validateScalarString(value, name)
            if ~(ischar(value) || isstring(value)) || ~isscalar(string(value)) || ...
                    strlength(string(value)) == 0
                error("ProjectionAlignmentOptions:invalidString", ...
                    "%s must be a nonempty scalar string.", name);
            end
            value = string(value);
        end

        function value = validateOptionalScalarString(value, name)
            if isempty(value)
                value = "";
                return
            end
            if ~(ischar(value) || isstring(value)) || ~isscalar(string(value))
                error("ProjectionAlignmentOptions:invalidString", ...
                    "%s must be a scalar string.", name);
            end
            value = string(value);
        end

        function value = validatePositiveScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be a positive finite scalar.", name);
            end
            value = double(value);
        end

        function value = validateNonnegativeScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be a nonnegative finite scalar.", name);
            end
            value = double(value);
        end

        function value = validateOptionalNonnegativeScalar(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validateNonnegativeScalar(value, name);
        end

        function value = validateOptionalPositiveScalar(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validatePositiveScalar(value, name);
        end

        function value = validateOptionalNonnegativeVector(value, count, name)
            if isempty(value)
                value = [];
                return
            end
            if ~isnumeric(value) || ~(isscalar(value) || numel(value) == count) || ...
                    any(~isfinite(value), "all") || any(value < 0, "all")
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be a nonnegative finite scalar or %d-vector.", ...
                    name, count);
            end
            value = double(value(:).');
            if isscalar(value)
                value = repmat(value, 1, count);
            end
        end

        function value = validatePositiveVector(value, count, name)
            if ~isnumeric(value) || numel(value) ~= count || ...
                    any(~isfinite(value), "all") || any(value <= 0, "all")
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be a positive finite %d-vector.", name, count);
            end
            value = double(value(:).');
        end

        function value = validateFraction(value, name)
            value = ProjectionAlignmentOptions.validatePositiveScalar(value, name);
            if value > 1
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be in the range (0, 1].", name);
            end
        end

        function value = validateOptionalFraction(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validateFraction(value, name);
        end

        function value = validateOptionalPercentage(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validatePositiveScalar(value, name);
            if value > 100
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be in the range (0, 100].", name);
            end
        end

        function value = validateOptionalNonnegativeFraction(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validateNonnegativeScalar(value, name);
            if value > 1
                error("ProjectionAlignmentOptions:invalidScalar", ...
                    "%s must be in the range [0, 1].", name);
            end
        end

        function value = validatePositiveInteger(value, name)
            value = ProjectionAlignmentOptions.validatePositiveScalar(value, name);
            if fix(value) ~= value
                error("ProjectionAlignmentOptions:invalidInteger", ...
                    "%s must be a positive integer.", name);
            end
        end

        function value = validateOptionalPositiveInteger(value, name)
            if isempty(value)
                value = [];
                return
            end
            value = ProjectionAlignmentOptions.validatePositiveInteger(value, name);
        end

        function values = validateStringVector(values, name)
            if isempty(values)
                values = strings(1, 0);
                return
            end
            if ~(isstring(values) || iscellstr(values) || ischar(values)) || ...
                    ~isvector(values)
                error("ProjectionAlignmentOptions:invalidString", ...
                    "%s must be a string vector.", name);
            end
            values = reshape(string(values), 1, []);
            if any(ismissing(values)) || any(strlength(strip(values)) == 0) || ...
                    any(values ~= strip(values)) || numel(unique(values)) ~= numel(values)
                error("ProjectionAlignmentOptions:invalidString", ...
                    "%s values must be unique, trimmed, and nonempty.", name);
            end
        end

        function value = validateLogicalScalar(value, name)
            if ~(islogical(value) || isnumeric(value)) || ~isscalar(value)
                error("ProjectionAlignmentOptions:invalidLogical", ...
                    "%s must be a scalar logical value.", name);
            end
            value = logical(value);
        end

        function value = validateRange(value, name)
            if ~isnumeric(value) || numel(value) ~= 2 || any(~isfinite(value), "all")
                error("ProjectionAlignmentOptions:invalidRange", ...
                    "%s must be a finite numeric two-element range.", name);
            end
            value = double(value(:).');
            if value(1) <= 0 || value(2) <= value(1)
                error("ProjectionAlignmentOptions:invalidRange", ...
                    "%s must be positive and strictly increasing.", name);
            end
        end

        function value = validateFilterFcn(value)
            if isempty(value)
                value = [];
                return
            end
            if ~isa(value, "function_handle")
                error("ProjectionAlignmentOptions:invalidFilterFcn", ...
                    "FilterPipeline.RadialFilterFcn must be empty or a function handle.");
            end
        end

        function output = mergeStruct(defaults, overrides, name)
            if isempty(overrides)
                output = defaults;
                return
            end
            if ~isstruct(overrides) || ~isscalar(overrides)
                error("ProjectionAlignmentOptions:invalidOptions", ...
                    "%s must be a scalar struct.", name);
            end

            output = defaults;
            names = fieldnames(overrides);
            for k = 1:numel(names)
                output.(names{k}) = overrides.(names{k});
            end
        end

        function value = fieldOrDefault(value, fieldName, defaultValue)
            if isfield(value, fieldName)
                value = value.(fieldName);
            else
                value = defaultValue;
            end
        end

        function filePath = validateFilePath(filePath)
            if ~(ischar(filePath) || (isstring(filePath) && isscalar(filePath))) || ...
                    strlength(string(filePath)) == 0
                error("ProjectionAlignmentOptions:invalidPath", ...
                    "File path must be a nonempty character vector or scalar string.");
            end
            filePath = char(filePath);
        end

        function writeTextFile(filePath, text)
            filePath = ProjectionAlignmentOptions.validateFilePath(filePath);
            fid = fopen(filePath, "w");
            if fid < 0
                error("ProjectionAlignmentOptions:fileOpenFailed", ...
                    "Unable to open alignment options file for writing: %s", filePath);
            end
            cleaner = onCleanup(@() fclose(fid));
            fprintf(fid, "%s\n", text);
            clear cleaner
        end
    end
end
