classdef ProjectionCorrectionOpkAdapter
    %ProjectionCorrectionOpkAdapter Bridge legacy degree OPK solver results.

    methods (Static)
        function correctionSet = fromAlignmentResult(scene, result, options)
            %fromAlignmentResult Build an immutable radian correction generation.
            if nargin < 3
                options = struct();
            end
            scene = ProjectionViewMetadata.ensureScene(scene);
            result = ProjectionAlignmentResult.validate(result);
            options = ProjectionCorrectionOpkAdapter.options(options);
            if isempty(result.SolvedCorrections)
                error("ProjectionCorrectionOpkAdapter:missingCorrections", ...
                    "Alignment result does not contain solved corrections.");
            end
            starting = result.Diagnostics.StartingCorrections;
            parentFingerprints = ProjectionGeometryFingerprint.scene(scene);
            correctedScene = scene;
            decomposition = ProjectionCorrectionOpkAdapter.decomposition(result);

            views = repmat(ProjectionCorrectionOpkAdapter.emptyView(), ...
                1, numel(result.SolvedCorrections));
            blocks = repmat(ProjectionCorrectionOpkAdapter.emptyBlock(), ...
                1, 3 * numel(result.SolvedCorrections));
            for index = 1:numel(result.SolvedCorrections)
                solved = result.SolvedCorrections(index);
                layerIndex = ProjectionCorrectionOpkAdapter.layerIndex( ...
                    scene, solved);
                layer = scene.layers(layerIndex);
                parent = ProjectionCorrectionOpkAdapter.correctionForLayer( ...
                    starting, layer.LayerId);
                ProjectionCorrectionOpkAdapter.assertParentState(layer, parent);
                solvedLayer = layer;
                solvedLayer.ViewVectorAngularOffsetsDegrees = ...
                    solved.ViewVectorAngularOffsetsDegrees(:);
                solvedLayer.ProjectionOffsetMeters = ...
                    solved.ProjectionOffsetMeters(:);
                [parentRotation, parentRadians] = ...
                    ProjectionMeshBuilder.viewVectorRotation( ...
                    layer, layer.CurrentProjectionPlane);
                [effectiveRotation, effectiveRadians] = ...
                    ProjectionMeshBuilder.viewVectorRotation( ...
                    solvedLayer, layer.CurrentProjectionPlane);
                solvedLayer.ViewVectorAngularOffsetsDegrees = ...
                    rad2deg(effectiveRadians(:));
                correctedScene.layers(layerIndex) = solvedLayer;
                incrementRotation = effectiveRotation * parentRotation.';
                [commonRadians, differentialRadians] = ...
                    ProjectionCorrectionOpkAdapter.decompositionForLayer( ...
                    decomposition, layer.LayerId);
                parentFingerprint = parentFingerprints( ...
                    string({parentFingerprints.ViewId}) == string(layer.ViewId));
                correctedFingerprint = struct(ViewId=string(layer.ViewId), ...
                    PassId=string(layer.PassId), ...
                    LayerId=string(layer.LayerId), ...
                    Fingerprint=ProjectionGeometryFingerprint.layer(solvedLayer));
                baseFingerprint = parentFingerprint.Fingerprint;
                if isfield(options.BaseGeometryFingerprints, char(layer.ViewId))
                    baseFingerprint = string( ...
                        options.BaseGeometryFingerprints.(char(layer.ViewId)));
                end
                views(index) = struct(ViewId=string(layer.ViewId), ...
                    PassId=string(layer.PassId), LayerId=string(layer.LayerId), ...
                    ParentAttitudeRadians=parentRadians, ...
                    EffectiveAttitudeRadians=effectiveRadians, ...
                    CommonAttitudeRadians=commonRadians, ...
                    DifferentialAttitudeRadians=differentialRadians, ...
                    ParentRotationMatrix=parentRotation, ...
                    IncrementRotationMatrix=incrementRotation, ...
                    EffectiveRotationMatrix=effectiveRotation, ...
                    IncrementRotationVectorRadians= ...
                    ProjectionCorrectionOpkAdapter.rotationVector( ...
                    incrementRotation), ...
                    ParentProjectionOffsetMeters=double( ...
                    parent.ProjectionOffsetMeters(:).'), ...
                    EffectiveProjectionOffsetMeters=double( ...
                    solved.ProjectionOffsetMeters(:).'), ...
                    BaseGeometryFingerprint=baseFingerprint, ...
                    ParentGeometryFingerprint=parentFingerprint.Fingerprint, ...
                    CorrectedGeometryFingerprint= ...
                    correctedFingerprint.Fingerprint);
                blockOffset = 3 * (index - 1);
                blocks(blockOffset + 1) = struct( ...
                    Name="effectiveAttitude", Type="attitudeOPK", ...
                    Scope="view", TargetId=string(layer.ViewId), ...
                    Values=effectiveRadians, Units="radians", ...
                    Frame="worldViewVector", Semantics="effectiveFromBase");
                blocks(blockOffset + 2) = struct( ...
                    Name="incrementRotation", Type="rotationMatrix", ...
                    Scope="view", TargetId=string(layer.ViewId), ...
                    Values=incrementRotation, Units="dimensionless", ...
                    Frame="worldViewVector", ...
                    Semantics="incrementFromParent");
                blocks(blockOffset + 3) = struct( ...
                    Name="projectionPlaneOffset", ...
                    Type="translation2D", Scope="view", ...
                    TargetId=string(layer.ViewId), ...
                    Values=double(solved.ProjectionOffsetMeters(:).'), ...
                    Units="meters", Frame="projectionPlaneBasis", ...
                    Semantics="effectiveFromBase");
            end
            correctedFingerprints = ...
                ProjectionGeometryFingerprint.scene(correctedScene);

            passIds = unique(string({views.PassId}), "stable");
            passes = repmat(struct(PassId="", ...
                CommonAttitudeRadians=zeros(1, 3), ...
                TranslationMeters=zeros(1, 3), ...
                TranslationAvailable=false), 1, numel(passIds));
            for index = 1:numel(passIds)
                passViews = views(string({views.PassId}) == passIds(index));
                passes(index).PassId = passIds(index);
                values = reshape([passViews.CommonAttitudeRadians], 3, []);
                passes(index).CommonAttitudeRadians = ...
                    reshape(mean(values, 2), 1, 3);
            end

            [covariance, provenance, diagnostics, failure] = ...
                ProjectionCorrectionOpkAdapter.supportingData(result, options);
            data = struct(Format=ProjectionCorrectionSet.FormatName, ...
                Version=ProjectionCorrectionSet.SchemaVersion, ...
                GenerationId=options.GenerationId, ...
                ParentGenerationId=options.ParentGenerationId, ...
                Lifecycle=options.Lifecycle, CreatedAt=options.CreatedAt, ...
                Convention=ProjectionCorrectionSet.opkConvention(), ...
                Views=views, Passes=passes, Blocks=blocks, ...
                Geometry=struct( ...
                FingerprintAlgorithm=ProjectionGeometryFingerprint.Algorithm, ...
                CanonicalizationVersion= ...
                ProjectionGeometryFingerprint.CanonicalizationVersion, ...
                Parent=parentFingerprints, Corrected=correctedFingerprints), ...
                Covariance=covariance, Provenance=provenance, ...
                Diagnostics=diagnostics, Failure=failure);
            correctionSet = ProjectionCorrectionSet.create(data);
        end

        function corrections = toLegacySolvedCorrections(correctionSet)
            %toLegacySolvedCorrections Restore validated degree-based records.
            correctionSet = ProjectionCorrectionSet.create(correctionSet);
            expected = ProjectionCorrectionSet.opkConvention();
            if correctionSet.Convention.ConventionId ~= expected.ConventionId
                error("ProjectionCorrectionOpkAdapter:incompatibleConvention", ...
                    "CorrectionSet does not use the legacy view-vector convention.");
            end
            corrections = repmat(struct(LayerIndex=0, LayerId="", ...
                ViewVectorAngularOffsetsDegrees=zeros(1, 3), ...
                ProjectionOffsetMeters=zeros(1, 2), SharedScale=1), ...
                1, numel(correctionSet.Views));
            for index = 1:numel(correctionSet.Views)
                view = correctionSet.Views(index);
                corrections(index).LayerId = view.LayerId;
                corrections(index).ViewVectorAngularOffsetsDegrees = ...
                    rad2deg(view.EffectiveAttitudeRadians);
                corrections(index).ProjectionOffsetMeters = ...
                    view.EffectiveProjectionOffsetMeters;
            end
        end
    end

    methods (Static, Access = private)
        function options = options(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionCorrectionOpkAdapter:invalidOptions", ...
                    "Correction adapter options must be a scalar struct.");
            end
            defaults = struct(GenerationId="", ParentGenerationId="", ...
                Lifecycle="proposed", CreatedAt="", ...
                SolverId="ProjectionAlignmentOpkSolver", ...
                BaseGeometryFingerprints=struct());
            names = fieldnames(options);
            for index = 1:numel(names)
                if ~isfield(defaults, names{index})
                    error("ProjectionCorrectionOpkAdapter:invalidOptions", ...
                        "Unknown correction adapter option %s.", names{index});
                end
                defaults.(names{index}) = options.(names{index});
            end
            if strlength(string(defaults.GenerationId)) == 0
                [~, token] = fileparts(tempname);
                defaults.GenerationId = "correction-" + string(token);
            end
            if strlength(string(defaults.CreatedAt)) == 0
                value = datetime("now", TimeZone="UTC", ...
                    Format="yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
                defaults.CreatedAt = string(value);
            end
            if ~isstruct(defaults.BaseGeometryFingerprints) || ...
                    ~isscalar(defaults.BaseGeometryFingerprints)
                error("ProjectionCorrectionOpkAdapter:invalidOptions", ...
                    "BaseGeometryFingerprints must be a scalar struct.");
            end
            options = defaults;
        end

        function index = layerIndex(scene, correction)
            if isfield(correction, "LayerId") && ...
                    strlength(string(correction.LayerId)) > 0
                index = ProjectionLayerIdentity.indexForId( ...
                    scene, correction.LayerId);
            else
                index = correction.LayerIndex;
            end
        end

        function correction = correctionForLayer(corrections, layerId)
            ids = string({corrections.LayerId});
            index = find(ids == string(layerId), 1, "first");
            if isempty(index)
                error("ProjectionCorrectionOpkAdapter:missingParent", ...
                    "Starting correction is missing for LayerId %s.", layerId);
            end
            correction = corrections(index);
        end

        function assertParentState(layer, parent)
            angles = double(layer.ViewVectorAngularOffsetsDegrees(:).');
            offsets = double(layer.ProjectionOffsetMeters(:).');
            if ~isequaln(angles, ...
                    double(parent.ViewVectorAngularOffsetsDegrees(:).')) || ...
                    ~isequaln(offsets, ...
                    double(parent.ProjectionOffsetMeters(:).'))
                error("ProjectionCorrectionOpkAdapter:staleAlignmentResult", ...
                    "Alignment result parent corrections do not match the scene.");
            end
        end

        function decomposition = decomposition(result)
            decomposition = struct(LayerIds=strings(1, 0), ...
                CommonDeltaDegrees=zeros(1, 3), ...
                DifferentialDeltaDegrees=zeros(0, 3));
            if isfield(result.Diagnostics, "AttitudeModel")
                model = result.Diagnostics.AttitudeModel;
                if isfield(model, "LayerIds")
                    decomposition.LayerIds = string(model.LayerIds);
                end
                if isfield(model, "CommonDeltaDegrees")
                    decomposition.CommonDeltaDegrees = ...
                        double(model.CommonDeltaDegrees);
                end
                if isfield(model, "DifferentialDeltaDegrees")
                    decomposition.DifferentialDeltaDegrees = ...
                        double(model.DifferentialDeltaDegrees);
                end
            end
        end

        function [common, differential] = decompositionForLayer(model, layerId)
            common = deg2rad(reshape(model.CommonDeltaDegrees, 1, 3));
            differential = zeros(1, 3);
            index = find(model.LayerIds == string(layerId), 1, "first");
            if ~isempty(index) && size(model.DifferentialDeltaDegrees, 1) >= index
                differential = deg2rad( ...
                    model.DifferentialDeltaDegrees(index, :));
            end
        end

        function vector = rotationVector(rotation)
            cosine = min(max((trace(rotation) - 1) / 2, -1), 1);
            angle = acos(cosine);
            if angle < 1e-12
                vector = zeros(1, 3);
                return
            end
            if abs(sin(angle)) < 1e-8
                [vectors, values] = eig(rotation);
                [~, index] = min(abs(diag(values) - 1));
                axis = real(vectors(:, index));
                axis = axis / norm(axis);
            else
                axis = [rotation(3, 2) - rotation(2, 3); ...
                    rotation(1, 3) - rotation(3, 1); ...
                    rotation(2, 1) - rotation(1, 2)] / (2 * sin(angle));
            end
            vector = (angle * axis).';
        end

        function [covariance, provenance, diagnostics, failure] = ...
                supportingData(result, options)
            conditionNumber = [];
            observability = struct();
            if isfield(result.Diagnostics, "Observability")
                observability = result.Diagnostics.Observability;
                if isfield(observability, "Solution") && ...
                        isfield(observability.Solution, "ConditionNumber") && ...
                        isfinite(observability.Solution.ConditionNumber)
                    conditionNumber = ...
                        double(observability.Solution.ConditionNumber);
                end
            end
            covariance = struct(Available=false, ...
                AttitudeRadiansSquared=zeros(0, 0), ...
                ConditionNumber=conditionNumber, ...
                Reason="legacySolverDidNotProduceCovariance");
            if isfield(observability, "Solution") && ...
                    isfield(observability.Solution, "ParameterCovariance")
                parameterCovariance = ...
                    observability.Solution.ParameterCovariance;
                attitudeCount = 3 * numel(result.SolvedCorrections);
                if isnumeric(parameterCovariance) && ...
                        size(parameterCovariance, 1) >= attitudeCount && ...
                        size(parameterCovariance, 2) >= attitudeCount
                    attitudeDegreesSquared = parameterCovariance( ...
                        1:attitudeCount, 1:attitudeCount);
                    covariance = struct(Available=true, ...
                        AttitudeRadiansSquared=attitudeDegreesSquared * ...
                        (pi / 180)^2, ConditionNumber=conditionNumber, ...
                        Reason="available");
                end
            end
            network = ProjectionCorrectionOpkAdapter.field( ...
                result.Diagnostics, "Network", struct());
            trackProvenance = struct(Available=false);
            gaugeProvenance = ProjectionCorrectionOpkAdapter.field( ...
                result.Diagnostics, "AttitudeModel", struct());
            if ~isempty(fieldnames(network))
                trackProvenance = struct(Available=true, ...
                    Evidence=ProjectionCorrectionOpkAdapter.field( ...
                    network, "Evidence", struct()));
                gaugeProvenance = ProjectionCorrectionOpkAdapter.field( ...
                    network, "Gauge", gaugeProvenance);
            end
            provenance = struct(Solver=struct(Id=string(options.SolverId), ...
                ResultFormat=string(result.Format), ...
                ResultVersion=double(result.Version)), ...
                AlignmentResultHash=ProjectionGeometryFingerprint.hash( ...
                struct(Status=result.Status, Request=result.RequestSummary, ...
                Corrections=result.SolvedCorrections, ...
                Convergence=result.Convergence)), ...
                MatchLedger=struct(RecordCount=numel(result.MatchLedger)), ...
                Track=trackProvenance, Gauge=gaugeProvenance, ...
                Precision=struct(Geometry="double", Solver="double", ...
                Covariance=ProjectionCorrectionOpkAdapter. ...
                covarianceStatus(covariance), Radiometry="notApplicable"), ...
                Configuration=result.RequestSummary);
            diagnostics = struct(Convergence=result.Convergence, ...
                Residuals=result.Residuals, Warnings=result.Warnings, ...
                Observability=observability, ...
                Bounds=ProjectionCorrectionOpkAdapter.field( ...
                result.Diagnostics, "BoundsDegrees", []), ...
                PriorContribution=ProjectionCorrectionOpkAdapter.field( ...
                provenance.Gauge, "PriorPrecision", []), Network=network);
            valid = result.Status == "solved" && result.Convergence.Success;
            if valid
                code = "none";
                explanation = "none";
            else
                code = "alignmentResultInvalid";
                explanation = string(result.Convergence.Message);
                if strlength(explanation) == 0
                    explanation = "Alignment result is not a valid solution.";
                end
            end
            failure = struct(Valid=valid, Code=code, Explanation=explanation);
        end

        function value = field(source, name, defaultValue)
            if isstruct(source) && isfield(source, name)
                value = source.(name);
            else
                value = defaultValue;
            end
        end

        function status = covarianceStatus(covariance)
            status = "unavailable";
            if covariance.Available
                status = "weightedNormalMatrixPseudoinverse";
            end
        end

        function view = emptyView()
            view = struct(ViewId="", PassId="", LayerId="", ...
                ParentAttitudeRadians=zeros(1, 3), ...
                EffectiveAttitudeRadians=zeros(1, 3), ...
                CommonAttitudeRadians=zeros(1, 3), ...
                DifferentialAttitudeRadians=zeros(1, 3), ...
                ParentRotationMatrix=eye(3), ...
                IncrementRotationMatrix=eye(3), ...
                EffectiveRotationMatrix=eye(3), ...
                IncrementRotationVectorRadians=zeros(1, 3), ...
                ParentProjectionOffsetMeters=zeros(1, 2), ...
                EffectiveProjectionOffsetMeters=zeros(1, 2), ...
                BaseGeometryFingerprint="", ...
                ParentGeometryFingerprint="", ...
                CorrectedGeometryFingerprint="");
        end

        function block = emptyBlock()
            block = struct(Name="", Type="", Scope="", TargetId="", ...
                Values=[], Units="", Frame="", Semantics="");
        end
    end
end
