classdef ProjectionDenseSurfaceSyntheticPlanner
    %ProjectionDenseSurfaceSyntheticPlanner Plan a feasible synthetic collection.

    properties (Constant)
        Format = "ProjectionDenseSurfaceSyntheticPlan"
        Version = 1
    end

    methods (Static)
        function report = planFile(configPath)
            %planFile Load private configuration and plan without image allocation.
            [config, context] = ProjectionDenseSurfaceSyntheticConfig.load(configPath);
            imageInfo = imfinfo(context.SourceImagePath);
            sourceImageSize = [imageInfo.Height imageInfo.Width imageInfo.SamplesPerPixel];
            report = ProjectionDenseSurfaceSyntheticPlanner.plan( ...
                config, sourceImageSize);
        end

        function report = plan(config, sourceImageSize)
            %plan Solve geometry, sampling, scan, and constant-gap feasibility.
            config = ProjectionDenseSurfaceSyntheticConfig.validate(config);
            sourceImageSize = ...
                ProjectionDenseSurfaceSyntheticPlanner.validateSourceImageSize( ...
                sourceImageSize);
            if max(config.image.source_band_sequence) > sourceImageSize(3)
                error("ProjectionDenseSurfaceSyntheticPlanner:missingSourceBand", ...
                    "The source image does not contain every configured source band.");
            end

            height = config.platform.height_above_ground_meters;
            velocity = config.platform.forward_velocity_meters_per_second;
            rollDegrees = ProjectionDenseSurfaceSyntheticPlanner.nominalRoll(config);
            referenceOrigin = [0; 0; height];
            referenceRay = ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                rollDegrees, 0);
            referencePoint = ...
                ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                referenceOrigin, referenceRay, 0);
            targetPoint = referencePoint;
            slantRange = norm(referencePoint - referenceOrigin);
            groundStandoff = norm(referencePoint(1:2) - referenceOrigin(1:2));

            acquisitionDuration = config.image.columns / ...
                config.image.scan_rate_lines_per_second;
            sampleSpanSeconds = (config.image.columns - 1) / ...
                config.image.scan_rate_lines_per_second;
            minimumCenterInterval = acquisitionDuration + ...
                config.collection_planner.retrace_time_seconds;
            desiredSpacing = ProjectionDenseSurfaceSyntheticPlanner.solveSpacing( ...
                config, targetPoint, height);
            scheduleSpacing = max(desiredSpacing, velocity * minimumCenterInterval);
            separationExpanded = scheduleSpacing > desiredSpacing * (1 + 1e-12);
            centerInterval = scheduleSpacing / velocity;
            interImageGap = centerInterval - acquisitionDuration - ...
                config.collection_planner.retrace_time_seconds;
            centerOffsets = ((1:config.image.view_count) - ...
                0.5 * (config.image.view_count + 1)) * scheduleSpacing;
            centerTimes = centerOffsets / velocity;
            achievedSeparations = ...
                ProjectionDenseSurfaceSyntheticPlanner.sceneCenterSeparations( ...
                centerOffsets, targetPoint, height);

            rowIfovDegrees = config.image.cross_track_fov_degrees / ...
                (config.image.rows - 1);
            views = repmat(ProjectionDenseSurfaceSyntheticPlanner.emptyView(), ...
                1, config.image.view_count);
            allBounds = zeros(config.image.view_count, 4);
            allRowGsd = zeros(1, config.image.view_count);
            allColumnGsd = zeros(1, config.image.view_count);
            for viewIndex = 1:config.image.view_count
                centerOrigin = [centerOffsets(viewIndex); 0; height];
                centerPitch = ProjectionDenseSurfaceSyntheticPlanner.pitchForTarget( ...
                    centerOrigin, targetPoint, rollDegrees);
                rowGsd = ProjectionDenseSurfaceSyntheticPlanner.crossTrackGsd( ...
                    centerOrigin, rollDegrees, centerPitch, rowIfovDegrees);
                [pitchStart, pitchEnd, pitchRate, platformAdvance, ...
                    gimbalAdvance, columnGsd] = ...
                    ProjectionDenseSurfaceSyntheticPlanner.solveScan( ...
                    centerOrigin, rollDegrees, centerPitch, rowGsd, ...
                    sampleSpanSeconds, config);
                bounds = ProjectionDenseSurfaceSyntheticPlanner.viewBounds( ...
                    centerOrigin, rollDegrees, pitchStart, pitchEnd, ...
                    config, sampleSpanSeconds);
                pitchLimits = config.gimbal.pitch_field_of_regard_degrees;
                pitchMargins = [min(pitchStart, pitchEnd) - pitchLimits(1), ...
                    pitchLimits(2) - max(pitchStart, pitchEnd)];
                centerSlantRange = norm(targetPoint - centerOrigin);
                views(viewIndex) = struct(Index=viewIndex, ...
                    CenterTimeSeconds=centerTimes(viewIndex), ...
                    PlatformCenter=reshape(centerOrigin, 1, 3), ...
                    SceneCenter=reshape(targetPoint, 1, 3), ...
                    SlantRangeMeters=centerSlantRange, ...
                    RollDegrees=rollDegrees, PitchStartDegrees=pitchStart, ...
                    PitchCenterDegrees=centerPitch, PitchEndDegrees=pitchEnd, ...
                    PitchRateDegreesPerSecond=pitchRate, ...
                    PitchFieldOfRegardMarginDegrees=min(pitchMargins), ...
                    ProjectedGsdMeters=[rowGsd columnGsd], ...
                    PlatformAdvanceMetersPerColumn=platformAdvance, ...
                    GimbalAdvanceMetersPerColumn=gimbalAdvance, ...
                    TerrainBoundsMeters=bounds, ...
                    TextureCoordinateBounds=[]);
                allBounds(viewIndex, :) = bounds;
                allRowGsd(viewIndex) = rowGsd;
                allColumnGsd(viewIndex) = columnGsd;
            end

            textureSpacing = [min(allRowGsd) min(allColumnGsd)];
            oversampling = [allRowGsd(:) / textureSpacing(1), ...
                allColumnGsd(:) / textureSpacing(2)];
            unionBounds = [min(allBounds(:, 1)) max(allBounds(:, 2)) ...
                min(allBounds(:, 3)) max(allBounds(:, 4))];
            tileCounts = ProjectionDenseSurfaceSyntheticPlanner.tileCounts( ...
                unionBounds, targetPoint, sourceImageSize, textureSpacing, config);
            for viewIndex = 1:numel(views)
                views(viewIndex).TextureCoordinateBounds = ...
                    ProjectionDenseSurfaceSyntheticPlanner.textureBounds( ...
                    views(viewIndex).TerrainBoundsMeters, targetPoint, ...
                    sourceImageSize, textureSpacing);
            end

            checks = ProjectionDenseSurfaceSyntheticPlanner.feasibilityChecks( ...
                config, slantRange, views, achievedSeparations, interImageGap, ...
                separationExpanded, oversampling, tileCounts, unionBounds);
            passed = [checks.Passed];
            if all(passed)
                status = "feasible";
                firstViolation = "";
                explanation = "All configured collection constraints are satisfied.";
            else
                status = "infeasible";
                firstViolation = string(checks(find(~passed, 1)).Name);
                explanation = string(checks(find(~passed, 1)).Explanation);
            end

            minimumPitchMargin = min([views.PitchFieldOfRegardMarginDegrees]);
            nearestCandidate = struct( ...
                PlatformCenterSpacingMeters=scheduleSpacing, ...
                InterImageGapSeconds=interImageGap, ...
                MinimumPitchMarginDegrees=minimumPitchMargin, ...
                RequiredReflectionTileCount=tileCounts, ...
                MaximumOversamplingPerAxis=max(oversampling, [], 1));
            report = struct(Format=ProjectionDenseSurfaceSyntheticPlanner.Format, ...
                Version=ProjectionDenseSurfaceSyntheticPlanner.Version, ...
                Status=status, Feasible=all(passed), ...
                FirstViolation=firstViolation, Explanation=explanation, ...
                NearestCandidate=nearestCandidate, ...
                Frame=struct(WorldAxes="forward-right-up", ...
                PlatformAxes="forward-right-down", ...
                BodyToWorld=ProjectionDenseSurfaceSyntheticPlanner.bodyToWorldMatrix()), ...
                DerivedSlantRangeMeters=slantRange, ...
                GroundStandoffMeters=groundStandoff, ...
                TargetPoint=reshape(targetPoint, 1, 3), ...
                RowIfovDegrees=rowIfovDegrees, ...
                AcquisitionDurationSeconds=acquisitionDuration, ...
                SampleSpanSeconds=sampleSpanSeconds, ...
                RetraceTimeSeconds=config.collection_planner.retrace_time_seconds, ...
                InterImageGapSeconds=interImageGap, ...
                CenterIntervalSeconds=centerInterval, ...
                PlatformCenterSpacingMeters=scheduleSpacing, ...
                SeparationExpanded=separationExpanded, ...
                AchievedSceneCenterSeparationsDegrees=achievedSeparations, ...
                TextureSampleSpacingMeters=textureSpacing, ...
                RequiredReflectionTileCount=tileCounts, ...
                ProjectedTerrainBoundsMeters=unionBounds, ...
                OversamplingRatioPerView=oversampling, Views=views, Checks=checks);
        end

        function transform = bodyToWorldMatrix()
            %bodyToWorldMatrix Map forward-right-down body vectors to world axes.
            transform = diag([1 1 -1]);
        end

        function rotation = gimbalRotation(rollDegrees, pitchDegrees)
            %gimbalRotation Compose active roll then pitch rotations in body axes.
            rollDegrees = ProjectionDenseSurfaceSyntheticPlanner.finiteScalar( ...
                rollDegrees, "rollDegrees");
            pitchDegrees = ProjectionDenseSurfaceSyntheticPlanner.finiteScalar( ...
                pitchDegrees, "pitchDegrees");
            roll = deg2rad(rollDegrees);
            pitch = deg2rad(pitchDegrees);
            rollRotation = [1 0 0; 0 cos(roll) -sin(roll); ...
                0 sin(roll) cos(roll)];
            pitchRotation = [cos(pitch) 0 sin(pitch); 0 1 0; ...
                -sin(pitch) 0 cos(pitch)];
            rotation = rollRotation * pitchRotation;
        end

        function ray = boresightRay(rollDegrees, pitchDegrees)
            %boresightRay Return the world-frame zero-detector view direction.
            ray = ProjectionDenseSurfaceSyntheticPlanner.bodyToWorldMatrix() * ...
                ProjectionDenseSurfaceSyntheticPlanner.gimbalRotation( ...
                rollDegrees, pitchDegrees) * [0; 0; 1];
            ray = ray / norm(ray);
        end
    end

    methods (Static, Access = private)
        function sizeValue = validateSourceImageSize(sizeValue)
            if ~isnumeric(sizeValue) || ~isvector(sizeValue) || ...
                    numel(sizeValue) < 2 || numel(sizeValue) > 3 || ...
                    any(~isfinite(sizeValue)) || any(sizeValue < 1) || ...
                    any(fix(sizeValue) ~= sizeValue)
                error("ProjectionDenseSurfaceSyntheticPlanner:invalidSourceImageSize", ...
                    "sourceImageSize must contain two or three positive integers.");
            end
            sizeValue = double(sizeValue(:).');
            if numel(sizeValue) == 2
                sizeValue(3) = 1;
            end
        end

        function rollDegrees = nominalRoll(config)
            sideSign = 1;
            if config.platform.target_side == "left"
                sideSign = -1;
            end
            rollDegrees = -sideSign * config.platform.nominal_off_nadir_degrees;
        end

        function spacing = solveSpacing(config, targetPoint, height)
            desired = config.collection_planner.desired_scene_center_separation_degrees;
            viewCount = config.image.view_count;
            lower = 0;
            upper = max(norm(targetPoint - [0; 0; height]) * deg2rad(desired), 1);
            while min(ProjectionDenseSurfaceSyntheticPlanner.sceneCenterSeparations( ...
                    ((1:viewCount) - 0.5 * (viewCount + 1)) * upper, ...
                    targetPoint, height)) < desired
                upper = 2 * upper;
                if upper > 1e9
                    error("ProjectionDenseSurfaceSyntheticPlanner:spacingSolveFailed", ...
                        "Could not bracket the requested scene-center separation.");
                end
            end
            for iteration = 1:80
                midpoint = 0.5 * (lower + upper);
                offsets = ((1:viewCount) - 0.5 * (viewCount + 1)) * midpoint;
                achieved = ...
                    ProjectionDenseSurfaceSyntheticPlanner.sceneCenterSeparations( ...
                    offsets, targetPoint, height);
                if min(achieved) < desired
                    lower = midpoint;
                else
                    upper = midpoint;
                end
            end
            spacing = upper;
        end

        function angles = sceneCenterSeparations(offsets, targetPoint, height)
            origins = [offsets; zeros(1, numel(offsets)); ...
                height * ones(1, numel(offsets))];
            vectors = targetPoint - origins;
            vectors = vectors ./ vecnorm(vectors, 2, 1);
            cosines = sum(vectors(:, 1:end-1) .* vectors(:, 2:end), 1);
            angles = real(acosd(max(-1, min(1, cosines))));
        end

        function pitchDegrees = pitchForTarget(origin, target, rollDegrees)
            pitchLimits = [-89 89];
            objective = @(pitch) ...
                ProjectionDenseSurfaceSyntheticPlanner.targetAlongTrackError( ...
                origin, target, rollDegrees, pitch);
            lowValue = objective(pitchLimits(1));
            highValue = objective(pitchLimits(2));
            if sign(lowValue) == sign(highValue)
                error("ProjectionDenseSurfaceSyntheticPlanner:pitchSolveFailed", ...
                    "Could not bracket the scene-center pitch solution.");
            end
            low = pitchLimits(1);
            high = pitchLimits(2);
            for iteration = 1:80
                midpoint = 0.5 * (low + high);
                value = objective(midpoint);
                if sign(value) == sign(lowValue)
                    low = midpoint;
                    lowValue = value;
                else
                    high = midpoint;
                end
            end
            pitchDegrees = 0.5 * (low + high);
        end

        function errorValue = targetAlongTrackError(origin, target, roll, pitch)
            ray = ProjectionDenseSurfaceSyntheticPlanner.boresightRay(roll, pitch);
            point = ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                origin, ray, target(3));
            errorValue = point(1) - target(1);
        end

        function gsd = crossTrackGsd(origin, roll, pitch, rowIfovDegrees)
            pointA = ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                origin, ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                roll - 0.5 * rowIfovDegrees, pitch), 0);
            pointB = ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                origin, ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                roll + 0.5 * rowIfovDegrees, pitch), 0);
            gsd = norm(pointB(1:2) - pointA(1:2));
        end

        function [pitchStart, pitchEnd, pitchRate, platformAdvance, ...
                gimbalAdvance, columnGsd] = solveScan( ...
                centerOrigin, roll, pitchCenter, targetGsd, sampleSpan, config)
            velocity = config.platform.forward_velocity_meters_per_second;
            totalTargetAdvance = (config.image.columns - 1) * targetGsd;
            originStart = centerOrigin + [-0.5 * velocity * sampleSpan; 0; 0];
            originEnd = centerOrigin + [0.5 * velocity * sampleSpan; 0; 0];
            objective = @(pitchDelta) ...
                ProjectionDenseSurfaceSyntheticPlanner.scanAdvance( ...
                originStart, originEnd, roll, pitchCenter, pitchDelta) - ...
                totalTargetAdvance;
            pitchDeltaLimit = 2 * (89 - abs(pitchCenter)) * (1 - 1e-8);
            lower = -pitchDeltaLimit;
            upper = pitchDeltaLimit;
            lowerValue = objective(lower);
            upperValue = objective(upper);
            if ~isfinite(lowerValue) || ~isfinite(upperValue) || ...
                    sign(lowerValue) == sign(upperValue)
                error("ProjectionDenseSurfaceSyntheticPlanner:scanSolveFailed", ...
                    "Could not bracket the pitch-scan solution.");
            end
            for iteration = 1:100
                midpoint = 0.5 * (lower + upper);
                value = objective(midpoint);
                if sign(value) == sign(lowerValue)
                    lower = midpoint;
                    lowerValue = value;
                else
                    upper = midpoint;
                end
            end
            pitchDelta = 0.5 * (lower + upper);
            pitchStart = pitchCenter - 0.5 * pitchDelta;
            pitchEnd = pitchCenter + 0.5 * pitchDelta;
            pitchRate = pitchDelta / sampleSpan;
            platformAdvance = velocity / config.image.scan_rate_lines_per_second;
            columnGsd = ProjectionDenseSurfaceSyntheticPlanner.scanAdvance( ...
                originStart, originEnd, roll, pitchCenter, pitchDelta) / ...
                (config.image.columns - 1);
            gimbalAdvance = columnGsd - platformAdvance;
        end

        function advance = scanAdvance(originStart, originEnd, roll, center, delta)
            pointStart = ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                originStart, ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                roll, center - 0.5 * delta), 0);
            pointEnd = ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                originEnd, ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                roll, center + 0.5 * delta), 0);
            advance = pointEnd(1) - pointStart(1);
        end

        function bounds = viewBounds(centerOrigin, roll, pitchStart, pitchEnd, ...
                config, sampleSpan)
            velocity = config.platform.forward_velocity_meters_per_second;
            origins = [centerOrigin + [-0.5 * velocity * sampleSpan; 0; 0], ...
                centerOrigin + [0.5 * velocity * sampleSpan; 0; 0]];
            pitches = [pitchStart pitchEnd];
            halfFov = 0.5 * config.image.cross_track_fov_degrees;
            rowRolls = roll + [-halfFov halfFov];
            heights = [config.terrain.minimum_height_meters ...
                config.terrain.maximum_height_meters];
            points = zeros(3, 8);
            pointIndex = 0;
            for columnIndex = 1:2
                for rowIndex = 1:2
                    for heightIndex = 1:2
                        pointIndex = pointIndex + 1;
                        ray = ProjectionDenseSurfaceSyntheticPlanner.boresightRay( ...
                            rowRolls(rowIndex), pitches(columnIndex));
                        points(:, pointIndex) = ...
                            ProjectionDenseSurfaceSyntheticPlanner.intersectHorizontalPlane( ...
                            origins(:, columnIndex), ray, heights(heightIndex));
                    end
                end
            end
            bounds = [min(points(1, :)) max(points(1, :)) ...
                min(points(2, :)) max(points(2, :))];
        end

        function counts = tileCounts(bounds, target, sourceSize, spacing, config)
            relativeX = bounds(1:2) - target(1);
            relativeY = bounds(3:4) - target(2);
            rowSpan = (sourceSize(1) - 1) * spacing(1);
            columnSpan = (sourceSize(2) - 1) * spacing(2);
            rows = ProjectionDenseSurfaceSyntheticPlanner.axisTileCount( ...
                relativeY, rowSpan, ...
                config.sampling.minimum_reflection_tiles_rows, ...
                config.sampling.prefer_odd_tile_counts);
            columns = ProjectionDenseSurfaceSyntheticPlanner.axisTileCount( ...
                relativeX, columnSpan, ...
                config.sampling.minimum_reflection_tiles_columns, ...
                config.sampling.prefer_odd_tile_counts);
            counts = [rows columns];
        end

        function count = axisTileCount(extent, tileSpan, minimum, preferOdd)
            if preferOdd
                count = 2 * ceil(max(abs(extent)) / tileSpan - 0.5) + 1;
                count = max(count, minimum);
                if mod(count, 2) == 0
                    count = count + 1;
                end
            else
                count = max(ceil((extent(2) - extent(1)) / tileSpan), minimum);
            end
        end

        function bounds = textureBounds(terrainBounds, target, sourceSize, spacing)
            center = 0.5 * ([sourceSize(1) sourceSize(2)] + 1);
            rowBounds = center(1) + (terrainBounds(3:4) - target(2)) / spacing(1);
            columnBounds = center(2) + (terrainBounds(1:2) - target(1)) / spacing(2);
            bounds = [rowBounds columnBounds];
        end

        function checks = feasibilityChecks(config, slantRange, views, ...
                separations, gap, expanded, oversampling, tileCounts, bounds)
            planner = config.collection_planner;
            rangePassed = slantRange >= planner.minimum_slant_range_meters && ...
                all([views.SlantRangeMeters] <= planner.maximum_slant_range_meters);
            samplingPassed = all(oversampling <= ...
                config.sampling.maximum_oversampling_per_axis, "all");
            scanPassed = all(isfinite([views.PitchRateDegreesPerSecond]));
            separationPassed = min(separations) + 1e-10 >= ...
                planner.desired_scene_center_separation_degrees && gap >= -1e-10 && ...
                (~expanded || planner.allow_separation_expansion);
            pitchValues = [[views.PitchStartDegrees] ...
                [views.PitchCenterDegrees] [views.PitchEndDegrees]];
            pitchLimits = config.gimbal.pitch_field_of_regard_degrees;
            pitchPassed = all(pitchValues >= pitchLimits(1) - 1e-10) && ...
                all(pitchValues <= pitchLimits(2) + 1e-10) && ...
                max([views(1).PitchStartDegrees views(1).PitchCenterDegrees ...
                views(1).PitchEndDegrees]) <= ...
                config.gimbal.maximum_initial_forward_pitch_degrees + 1e-10;
            footprintPassed = all(isfinite(bounds)) && bounds(1) < bounds(2) && ...
                bounds(3) < bounds(4);
            tilesPassed = tileCounts(1) <= ...
                config.sampling.maximum_reflection_tiles_rows && ...
                tileCounts(2) <= config.sampling.maximum_reflection_tiles_columns;
            checks = [ ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "rangeEnvelope", rangePassed, ...
                "Derived and collection-center slant ranges must remain in the configured envelope."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "perAxisSampling", samplingPassed, ...
                "Projected per-axis oversampling exceeds the configured maximum."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "scanSolution", scanPassed, ...
                "The full-geometry pitch-scan solution is not finite."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "constantGapSchedule", separationPassed, ...
                "No permitted constant-gap schedule satisfies scene-center separation."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "pitchFieldOfRegard", pitchPassed, ...
                "A collection pitch or initial forward pitch exceeds its limit."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "footprintContainment", footprintPassed, ...
                "A projected terrain footprint is invalid or unbounded."), ...
                ProjectionDenseSurfaceSyntheticPlanner.check( ...
                "textureGridGrowth", tilesPassed, ...
                "Required reflected texture tiles exceed the configured growth limit.")];
        end

        function value = check(name, passed, explanation)
            value = struct(Name=name, Passed=logical(passed), ...
                Explanation=explanation);
        end

        function point = intersectHorizontalPlane(origin, ray, height)
            denominator = ray(3);
            scale = (height - origin(3)) / denominator;
            if ~isfinite(scale) || scale <= 0
                error("ProjectionDenseSurfaceSyntheticPlanner:invalidForwardRay", ...
                    "A collection view does not intersect the terrain plane forward.");
            end
            point = origin + scale * ray;
        end

        function value = finiteScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
                error("ProjectionDenseSurfaceSyntheticPlanner:invalidAngle", ...
                    "%s must be a finite numeric scalar.", name);
            end
            value = double(value);
        end

        function view = emptyView()
            view = struct(Index=0, CenterTimeSeconds=0, ...
                PlatformCenter=zeros(1, 3), SceneCenter=zeros(1, 3), ...
                SlantRangeMeters=0, RollDegrees=0, PitchStartDegrees=0, ...
                PitchCenterDegrees=0, PitchEndDegrees=0, ...
                PitchRateDegreesPerSecond=0, ...
                PitchFieldOfRegardMarginDegrees=0, ...
                ProjectedGsdMeters=zeros(1, 2), ...
                PlatformAdvanceMetersPerColumn=0, ...
                GimbalAdvanceMetersPerColumn=0, ...
                TerrainBoundsMeters=zeros(1, 4), ...
                TextureCoordinateBounds=zeros(1, 4));
        end
    end
end
