classdef ProjectionDenseObservationAssociator
    %ProjectionDenseObservationAssociator Form provenance-rich dense tracks.

    properties (Constant)
        Format = "ProjectionDenseObservationAssociation"
        Version = 1
        RequestFormat = "ProjectionDensePairObservationRecords"
        RequestVersion = 1
    end

    methods (Static)
        function options = defaults()
            %defaults Return deterministic association and quality gates.
            options = struct( ...
                MinimumPairAngleDegrees=0.1, ...
                MinimumTextureScore=0.05, ...
                MinimumNavigationWeight=0.05, ...
                MinimumRadiometricConsistency=0.05, ...
                SourceObservationTolerancePixels=0.25, ...
                RayOriginToleranceMeters=1e-6, ...
                RayDirectionToleranceDegrees=1e-5, ...
                ModeSeparationMeters=Inf);
        end

        function result = associate(request, options)
            %associate Reconcile dense pair observations into stable tracks.
            if nargin < 2
                options = struct();
            end
            options = ProjectionDenseObservationAssociator.validateOptions( ...
                options);
            request = ProjectionDenseObservationAssociator.validateRequest( ...
                request);
            records = ProjectionDenseObservationAssociator.normalizeRecords( ...
                request.Records);
            [observations, records] = ...
                ProjectionDenseObservationAssociator.collectObservations( ...
                records, options);
            records = ProjectionDenseObservationAssociator.precheckRecords( ...
                records, observations, options);
            [records, tracks] = ...
                ProjectionDenseObservationAssociator.associateTracks( ...
                records, observations, options);

            generationPayload = struct(WorldFrame=request.WorldFrame, ...
                Options=options, RecordIds=string({records.RecordId}), ...
                RecordStates=string({records.AssociationState}), ...
                RecordReasons=string({records.AssociationReason}), ...
                TrackIds=string({tracks.TrackId}));
            generationId = "dense-association-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(generationPayload), 17);
            result = struct( ...
                Format=ProjectionDenseObservationAssociator.Format, ...
                Version=ProjectionDenseObservationAssociator.Version, ...
                Status="complete", Stage="denseObservationAssociation", ...
                WorldFrame=request.WorldFrame, GenerationId=generationId, ...
                Options=options, RawPairwiseRecords=records, ...
                Observations=observations, Tracks=tracks, ...
                Diagnostics=ProjectionDenseObservationAssociator.diagnostics( ...
                records, observations, tracks));
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            defaults = ProjectionDenseObservationAssociator.defaults();
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "Association options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "Unknown association option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            bounded = ["MinimumTextureScore" ...
                "MinimumNavigationWeight" ...
                "MinimumRadiometricConsistency"];
            for name = bounded
                defaults.(name) = ...
                    ProjectionDenseObservationAssociator.boundedScalar( ...
                    defaults.(name), name);
            end
            positive = ["SourceObservationTolerancePixels" ...
                "RayOriginToleranceMeters" ...
                "RayDirectionToleranceDegrees"];
            for name = positive
                defaults.(name) = ...
                    ProjectionDenseObservationAssociator.positiveScalar( ...
                    defaults.(name), name, false);
            end
            defaults.MinimumPairAngleDegrees = ...
                ProjectionDenseObservationAssociator.boundedAngle( ...
                defaults.MinimumPairAngleDegrees, "MinimumPairAngleDegrees");
            defaults.ModeSeparationMeters = ...
                ProjectionDenseObservationAssociator.positiveScalar( ...
                defaults.ModeSeparationMeters, "ModeSeparationMeters", true);
            options = defaults;
        end

        function request = validateRequest(request)
            if ~isstruct(request) || ~isscalar(request)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Dense pair-observation request must be a scalar struct.");
            end
            allowed = ["Format" "Version" "WorldFrame" "Records"];
            unknown = setdiff(string(fieldnames(request)), allowed);
            if ~isempty(unknown)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Unexpected request field: %s.", unknown(1));
            end
            required = ["WorldFrame" "Records"];
            if any(~isfield(request, required))
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "WorldFrame and Records are required.");
            end
            if ~isfield(request, "Format")
                request.Format = ...
                    ProjectionDenseObservationAssociator.RequestFormat;
            end
            if ~isfield(request, "Version")
                request.Version = ...
                    ProjectionDenseObservationAssociator.RequestVersion;
            end
            request.Format = string(request.Format);
            if ~isscalar(request.Format) || ismissing(request.Format) || ...
                    request.Format ~= ...
                    ProjectionDenseObservationAssociator.RequestFormat || ...
                    ~isequal(request.Version, ...
                    ProjectionDenseObservationAssociator.RequestVersion)
                error("ProjectionDenseObservationAssociator:unsupportedSchema", ...
                    "Dense pair-observation Format and Version must be supported.");
            end
            request.WorldFrame = string(request.WorldFrame);
            if ~isscalar(request.WorldFrame) || ismissing(request.WorldFrame) || ...
                    strlength(request.WorldFrame) == 0
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "WorldFrame must be a nonempty string scalar.");
            end
            if ~isstruct(request.Records)
                error("ProjectionDenseObservationAssociator:invalidRequest", ...
                    "Records must be a struct array.");
            end
        end

        function records = normalizeRecords(inputRecords)
            records = repmat( ...
                ProjectionDenseObservationAssociator.emptyRecord(), ...
                1, numel(inputRecords));
            if isempty(inputRecords)
                return
            end
            allowed = string(fieldnames( ...
                ProjectionDenseObservationAssociator.emptyRecord()));
            inputFields = string(fieldnames(inputRecords));
            internal = ["NodeIndices" "PairRayParametersMeters" ...
                "PairRaySeparationMeters" "PairConditionNumber" ...
                "PairAngleDegrees" "PairForwardValid" "AssociationState" ...
                "AssociationReason" "ModeKey" "TrackId"];
            allowedInput = setdiff(allowed, internal);
            unknown = setdiff(inputFields, allowedInput);
            required = ["RecordId" "PairId" "ViewIds" "PassIds" ...
                "ObservationIds" "SourceObservationsPixels" ...
                "RayOriginsWorld" "RayVectorsWorld"];
            if ~isempty(unknown) || any(~isfield(inputRecords, required))
                error("ProjectionDenseObservationAssociator:invalidRecords", ...
                    "Records have missing required or unexpected fields.");
            end
            for index = 1:numel(inputRecords)
                record = ProjectionDenseObservationAssociator.emptyRecord();
                for field = inputFields.'
                    record.(field) = inputRecords(index).(field);
                end
                records(index) = ...
                    ProjectionDenseObservationAssociator.validateRecord(record);
            end
            keys = string({records.RecordId});
            if numel(unique(keys)) ~= numel(keys)
                error("ProjectionDenseObservationAssociator:duplicateRecordId", ...
                    "Every dense pair record requires a unique RecordId.");
            end
            [~, order] = sort(keys);
            records = records(order);
        end

        function record = validateRecord(record)
            record.RecordId = ProjectionDenseObservationAssociator. ...
                nonemptyString(record.RecordId, "RecordId");
            record.PairId = ProjectionDenseObservationAssociator. ...
                nonemptyString(record.PairId, "PairId");
            record.ViewIds = reshape(string(record.ViewIds), 1, []);
            record.PassIds = reshape(string(record.PassIds), 1, []);
            record.ObservationIds = reshape(string(record.ObservationIds), 1, []);
            identity = [record.ViewIds record.PassIds record.ObservationIds];
            if numel(record.ViewIds) ~= 2 || ...
                    numel(record.PassIds) ~= 2 || ...
                    numel(record.ObservationIds) ~= 2 || ...
                    any(ismissing(identity)) || any(strlength(identity) == 0) || ...
                    record.ViewIds(1) == record.ViewIds(2)
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "Each record requires two distinct views and stable pass/observation IDs.");
            end
            finiteArrays = ["SourceObservationsPixels" ...
                "RayOriginsWorld" "RayVectorsWorld"];
            expectedSizes = {[2 2], [3 2], [3 2]};
            for index = 1:numel(finiteArrays)
                field = finiteArrays(index);
                value = record.(field);
                if ~isnumeric(value) || ...
                        ~isequal(size(value), expectedSizes{index}) || ...
                        any(~isfinite(value), "all")
                    error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                        "%s has invalid size or nonfinite values.", field);
                end
                record.(field) = double(value);
            end
            if any(vecnorm(record.RayVectorsWorld, 2, 1) <= eps)
                error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                    "Ray vectors must be nonzero.");
            end
            record.MatchState = string(record.MatchState);
            supportedStates = ["valid" "noMatch" "occluded" ...
                "ambiguousRepetitive" "insufficientTexture" ...
                "outsideOverlap" "geometrySearchFailure" "masked" ...
                "algorithmFailure"];
            if ~isscalar(record.MatchState) || ...
                    ~ismember(record.MatchState, supportedStates)
                error("ProjectionDenseObservationAssociator:invalidState", ...
                    "MatchState is unsupported.");
            end
            record.VisibilityStates = reshape( ...
                string(record.VisibilityStates), 1, []);
            if numel(record.VisibilityStates) ~= 2 || ...
                    any(~ismember(record.VisibilityStates, ...
                    ["visible" "occluded" "unknown" "unobservable"]))
                error("ProjectionDenseObservationAssociator:invalidVisibility", ...
                    "VisibilityStates must contain two supported states.");
            end
            record.Score = ProjectionDenseObservationAssociator. ...
                finiteOrNanScalar(record.Score, "Score");
            bounded = ["Confidence" "TextureScore" ...
                "RadiometricConsistency"];
            for field = bounded
                record.(field) = ProjectionDenseObservationAssociator. ...
                    boundedScalar(record.(field), field);
            end
            if ~isnumeric(record.NavigationWeights) || ...
                    numel(record.NavigationWeights) ~= 2 || ...
                    any(~isfinite(record.NavigationWeights)) || ...
                    any(record.NavigationWeights < 0 | ...
                    record.NavigationWeights > 1)
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "NavigationWeights must contain two values in [0,1].");
            end
            record.NavigationWeights = ...
                reshape(double(record.NavigationWeights), 1, 2);
            if ~isnumeric(record.RadiometricValues) || ...
                    numel(record.RadiometricValues) ~= 2
                error("ProjectionDenseObservationAssociator:invalidRadiometry", ...
                    "RadiometricValues must contain two numeric values.");
            end
            record.RadiometricValues = ...
                reshape(double(record.RadiometricValues), 1, 2);
            record.ProvisionalPointWorld = ...
                ProjectionDenseObservationAssociator.optionalVector( ...
                record.ProvisionalPointWorld, 3, "ProvisionalPointWorld");
            covariance = record.PairwiseCovarianceWorldMetersSquared;
            if ~isempty(covariance) && (~isnumeric(covariance) || ...
                    ~isequal(size(covariance), [3 3]) || ...
                    any(~isfinite(covariance), "all"))
                error("ProjectionDenseObservationAssociator:invalidCovariance", ...
                    "Pairwise covariance must be empty or finite 3x3.");
            end
            record.PairwiseCovarianceWorldMetersSquared = double(covariance);
            record.ModeId = string(record.ModeId);
            if ~isscalar(record.ModeId) || ismissing(record.ModeId)
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "ModeId must be a string scalar, possibly empty.");
            end
            [point, ranges, separation, condition, angle, valid] = ...
                ProjectionDenseObservationAssociator.triangulate( ...
                record.RayOriginsWorld, record.RayVectorsWorld);
            if isempty(record.ProvisionalPointWorld)
                record.ProvisionalPointWorld = point;
            end
            record.PairRayParametersMeters = ranges;
            record.PairRaySeparationMeters = separation;
            record.PairConditionNumber = condition;
            record.PairAngleDegrees = angle;
            record.PairForwardValid = valid;
        end

        function [observations, records] = collectObservations(records, options)
            observations = ...
                ProjectionDenseObservationAssociator.emptyObservations();
            if isempty(records)
                return
            end
            candidateCount = 2 * numel(records);
            candidates = repmat( ...
                ProjectionDenseObservationAssociator.emptyCandidate(), ...
                1, candidateCount);
            cursor = 0;
            for recordIndex = 1:numel(records)
                for side = 1:2
                    cursor = cursor + 1;
                    candidates(cursor) = ...
                        ProjectionDenseObservationAssociator.candidate( ...
                        records(recordIndex), recordIndex, side);
                end
            end
            keys = string({candidates.NodeKey});
            uniqueKeys = sort(unique(keys));
            for key = uniqueKeys
                memberIndices = find(keys == key);
                members = candidates(memberIndices);
                observation = ...
                    ProjectionDenseObservationAssociator.observation( ...
                    members, options);
                observations(end + 1) = observation; %#ok<AGROW>
                observationIndex = numel(observations);
                for candidateIndex = memberIndices
                    records(candidates(candidateIndex).RecordIndex). ...
                        NodeIndices(candidates(candidateIndex).Side) = ...
                        observationIndex;
                end
            end
        end

        function candidate = candidate(record, recordIndex, side)
            candidate = ProjectionDenseObservationAssociator.emptyCandidate();
            candidate.NodeKey = record.ViewIds(side) + "|" + ...
                record.ObservationIds(side);
            candidate.RecordIndex = recordIndex;
            candidate.Side = side;
            candidate.RecordId = record.RecordId;
            candidate.PairId = record.PairId;
            candidate.ViewId = record.ViewIds(side);
            candidate.PassId = record.PassIds(side);
            candidate.ObservationId = record.ObservationIds(side);
            candidate.SourceObservationPixels = ...
                record.SourceObservationsPixels(side, :);
            candidate.RayOriginWorld = record.RayOriginsWorld(:, side);
            candidate.RayVectorWorld = record.RayVectorsWorld(:, side);
            candidate.Confidence = record.Confidence;
            candidate.NavigationWeight = record.NavigationWeights(side);
            candidate.RadiometricValue = record.RadiometricValues(side);
            candidate.VisibilityState = record.VisibilityStates(side);
        end

        function observation = observation(members, options)
            viewIds = unique(string({members.ViewId}));
            passIds = unique(string({members.PassId}));
            source = vertcat(members.SourceObservationPixels);
            origins = horzcat(members.RayOriginWorld);
            vectors = horzcat(members.RayVectorWorld);
            unitVectors = vectors ./ vecnorm(vectors, 2, 1);
            meanVector = mean(unitVectors, 2);
            meanVector = meanVector / norm(meanVector);
            angular = acosd(min(1, max(-1, meanVector.' * unitVectors)));
            visibility = unique(string({members.VisibilityState}), "stable");
            consistent = isscalar(viewIds) && isscalar(passIds) && ...
                max(vecnorm(source - mean(source, 1), 2, 2)) <= ...
                options.SourceObservationTolerancePixels && ...
                max(vecnorm(origins - mean(origins, 2), 2, 1)) <= ...
                options.RayOriginToleranceMeters && ...
                max(angular) <= options.RayDirectionToleranceDegrees && ...
                ~all(ismember(["visible" "occluded"], visibility));
            reason = "";
            if ~consistent
                reason = "observationIdentityConflict";
            end
            values = [members.RadiometricValue];
            finiteValues = values(isfinite(values));
            radiometricValue = NaN;
            if ~isempty(finiteValues)
                radiometricValue = median(finiteValues);
            end
            visibilityState = "unknown";
            if isscalar(visibility)
                visibilityState = visibility;
            elseif any(visibility == "occluded")
                visibilityState = "conflicting";
            elseif any(visibility == "visible")
                visibilityState = "visible";
            end
            observation = struct( ...
                ObservationKey=members(1).NodeKey, ...
                ObservationId=members(1).ObservationId, ...
                ViewId=members(1).ViewId, PassId=members(1).PassId, ...
                SourceRowPixels=mean(source(:, 1)), ...
                SourceColumnPixels=mean(source(:, 2)), ...
                RayOriginWorld=mean(origins, 2), ...
                RayVectorWorld=meanVector, ...
                Confidence=max([members.Confidence]), ...
                NavigationWeight=min([members.NavigationWeight]), ...
                RadiometricValue=radiometricValue, ...
                VisibilityState=visibilityState, ...
                Consistent=consistent, ConflictReason=reason, ...
                OccurrenceCount=numel(members), ...
                RecordIds=sort(unique(string({members.RecordId}))), ...
                PairIds=sort(unique(string({members.PairId}))));
        end

        function records = precheckRecords(records, observations, options)
            for index = 1:numel(records)
                record = records(index);
                reason = "";
                if record.MatchState ~= "valid"
                    reason = "matchState:" + record.MatchState;
                elseif any(~[observations(record.NodeIndices).Consistent])
                    reason = "observationIdentityConflict";
                elseif ~record.PairForwardValid
                    reason = "pairForwardInvalid";
                elseif record.PairAngleDegrees < options.MinimumPairAngleDegrees
                    reason = "nearlyParallel";
                elseif record.TextureScore < options.MinimumTextureScore
                    reason = "insufficientTexture";
                elseif min(record.NavigationWeights) < ...
                        options.MinimumNavigationWeight
                    reason = "weakNavigation";
                elseif record.RadiometricConsistency < ...
                        options.MinimumRadiometricConsistency
                    reason = "radiometricInconsistent";
                elseif any(record.VisibilityStates == "occluded")
                    reason = "visibilityConflict";
                end
                if strlength(reason) > 0
                    records(index).AssociationState = "rejected";
                    records(index).AssociationReason = reason;
                end
            end
        end

        function [records, tracks] = associateTracks(records, observations, options)
            tracks = ProjectionDenseObservationAssociator.emptyTracks();
            eligible = find(string({records.AssociationState}) == "candidate");
            if isempty(eligible)
                return
            end
            baseParent = 1:numel(observations);
            for eligibleIndex = 1:numel(eligible)
                edgeIndex = eligible(eligibleIndex);
                baseParent = ProjectionDenseObservationAssociator.join( ...
                    baseParent, records(edgeIndex).NodeIndices);
            end
            roots = unique(arrayfun(@(node) ...
                ProjectionDenseObservationAssociator.root(baseParent, node), ...
                1:numel(observations)));
            for root = roots
                componentNodes = find(arrayfun(@(node) ...
                    ProjectionDenseObservationAssociator.root( ...
                    baseParent, node) == root, 1:numel(observations)));
                edgeIndices = eligible(arrayfun(@(edgeIndex) ...
                    all(ismember(records(edgeIndex).NodeIndices, componentNodes)), ...
                    eligible));
                if isempty(edgeIndices)
                    continue
                end
                modeGroups = ProjectionDenseObservationAssociator.modeGroups( ...
                    records, edgeIndices, options.ModeSeparationMeters);
                competing = numel(modeGroups) > 1;
                for modeIndex = 1:numel(modeGroups)
                    modeEdges = modeGroups(modeIndex).EdgeIndices;
                    [records, modeTracks] = ...
                        ProjectionDenseObservationAssociator.reconcileMode( ...
                        records, observations, modeEdges, ...
                        modeGroups(modeIndex).ModeKey, competing);
                    tracks = [tracks modeTracks]; %#ok<AGROW>
                end
            end
            if ~isempty(tracks)
                [~, order] = sort(string({tracks.TrackId}));
                tracks = tracks(order);
            end
        end

        function groups = modeGroups(records, edgeIndices, separation)
            groups = struct("ModeKey", {}, "EdgeIndices", {});
            explicit = string({records(edgeIndices).ModeId});
            explicitIds = sort(unique(explicit(strlength(explicit) > 0)));
            for modeId = explicitIds
                groups(end + 1) = struct( ...
                    ModeKey="hint:" + modeId, ...
                    EdgeIndices=edgeIndices(explicit == modeId)); %#ok<AGROW>
            end
            autoEdges = edgeIndices(strlength(explicit) == 0);
            if isempty(autoEdges)
                return
            end
            if isinf(separation)
                groups(end + 1) = struct( ...
                    ModeKey="auto:1", EdgeIndices=autoEdges);
                return
            end
            points = horzcat(records(autoEdges).ProvisionalPointWorld).';
            keys = string({records(autoEdges).RecordId}).';
            orderTable = table(points(:, 1), points(:, 2), points(:, 3), ...
                keys, (1:numel(autoEdges)).', VariableNames= ...
                ["X" "Y" "Z" "RecordId" "LocalIndex"]);
            orderTable = sortrows(orderTable, ["X" "Y" "Z" "RecordId"]);
            centers = zeros(0, 3);
            members = cell(1, 0);
            for orderIndex = 1:height(orderTable)
                localIndex = orderTable.LocalIndex(orderIndex);
                point = points(localIndex, :);
                distances = vecnorm(centers - point, 2, 2);
                [distance, cluster] = min(distances);
                if isempty(cluster) || distance > separation
                    centers(end + 1, :) = point; %#ok<AGROW>
                    members{end + 1} = localIndex; %#ok<AGROW>
                else
                    members{cluster}(end + 1) = localIndex;
                    centers(cluster, :) = mean(points(members{cluster}, :), 1);
                end
            end
            for cluster = 1:numel(members)
                groups(end + 1) = struct( ...
                    ModeKey="auto:" + cluster, ...
                    EdgeIndices=autoEdges(members{cluster})); %#ok<AGROW>
            end
        end

        function [records, tracks] = reconcileMode( ...
                records, observations, edgeIndices, modeKey, competing)
            tracks = ProjectionDenseObservationAssociator.emptyTracks();
            edgeIndices = reshape(edgeIndices, [], 1);
            quality = reshape([records(edgeIndices).Confidence], [], 1) .* ...
                reshape([records(edgeIndices).TextureScore], [], 1) .* ...
                reshape([records(edgeIndices).RadiometricConsistency], [], 1) .* ...
                reshape(arrayfun(@(record) min(record.NavigationWeights), ...
                records(edgeIndices)), [], 1);
            pairIds = reshape(string({records(edgeIndices).PairId}), [], 1);
            recordIds = reshape(string({records(edgeIndices).RecordId}), [], 1);
            ordering = table(-quality, pairIds, recordIds, edgeIndices, ...
                VariableNames=["NegativeQuality" "PairId" "RecordId" "EdgeIndex"]);
            ordering = sortrows(ordering, ...
                ["NegativeQuality" "PairId" "RecordId"]);
            parent = 1:numel(observations);
            for orderIndex = 1:height(ordering)
                edgeIndex = ordering.EdgeIndex(orderIndex);
                nodes = records(edgeIndex).NodeIndices;
                firstRoot = ProjectionDenseObservationAssociator.root( ...
                    parent, nodes(1));
                secondRoot = ProjectionDenseObservationAssociator.root( ...
                    parent, nodes(2));
                if firstRoot ~= secondRoot
                    firstViews = ProjectionDenseObservationAssociator. ...
                        componentViews(parent, firstRoot, observations);
                    secondViews = ProjectionDenseObservationAssociator. ...
                        componentViews(parent, secondRoot, observations);
                    if any(ismember(firstViews, secondViews))
                        records(edgeIndex).AssociationState = "rejected";
                        records(edgeIndex).AssociationReason = ...
                            "duplicateViewConflict";
                        continue
                    end
                    parent = ProjectionDenseObservationAssociator.join( ...
                        parent, nodes);
                end
                records(edgeIndex).AssociationState = "accepted";
                records(edgeIndex).AssociationReason = "";
                records(edgeIndex).ModeKey = modeKey;
            end
            acceptedEdges = edgeIndices(string( ...
                {records(edgeIndices).AssociationState}) == "accepted");
            if isempty(acceptedEdges)
                return
            end
            acceptedParent = 1:numel(observations);
            for acceptedIndex = 1:numel(acceptedEdges)
                edgeIndex = acceptedEdges(acceptedIndex);
                acceptedParent = ProjectionDenseObservationAssociator.join( ...
                    acceptedParent, records(edgeIndex).NodeIndices);
            end
            nodesUsed = unique([records(acceptedEdges).NodeIndices]);
            acceptedRoots = unique(arrayfun(@(node) ...
                ProjectionDenseObservationAssociator.root( ...
                acceptedParent, node), nodesUsed));
            for acceptedRoot = acceptedRoots
                nodeIndices = nodesUsed(arrayfun(@(node) ...
                    ProjectionDenseObservationAssociator.root( ...
                    acceptedParent, node) == acceptedRoot, nodesUsed));
                modeRecordIndices = acceptedEdges(arrayfun(@(edgeIndex) ...
                    all(ismember(records(edgeIndex).NodeIndices, nodeIndices)), ...
                    acceptedEdges));
                viewIds = string({observations(nodeIndices).ViewId});
                [~, order] = sort(viewIds);
                nodeIndices = nodeIndices(order);
                observationKeys = string( ...
                    {observations(nodeIndices).ObservationKey});
                observationIds = string( ...
                    {observations(nodeIndices).ObservationId});
                recordIds = sort(string({records(modeRecordIndices).RecordId}));
                pairIds = sort(unique(string( ...
                    {records(modeRecordIndices).PairId})));
                trackPayload = struct(ModeKey=modeKey, ...
                    ObservationKeys=observationKeys, RecordIds=recordIds);
                trackId = "dense-track-" + extractBefore( ...
                    ProjectionGeometryFingerprint.hash(trackPayload), 17);
                for recordIndex = 1:numel(modeRecordIndices)
                    edgeIndex = modeRecordIndices(recordIndex);
                    records(edgeIndex).TrackId = trackId;
                end
                tracks(end + 1) = struct( ...
                    TrackId=trackId, ModeId=modeKey, ...
                    CompetingMode=competing, ...
                    ObservationIndices=nodeIndices, ...
                    ObservationKeys=observationKeys, ...
                    ObservationIds=observationIds, ...
                    ViewIds=string({observations(nodeIndices).ViewId}), ...
                    PassIds=string({observations(nodeIndices).PassId}), ...
                    RecordIds=recordIds, PairIds=pairIds, ...
                    ViewCount=numel(nodeIndices), ...
                    IndependentPassCount=numel(unique(string( ...
                    {observations(nodeIndices).PassId}))), ...
                    PairRecordCount=numel(modeRecordIndices), ...
                    State="associated"); %#ok<AGROW>
            end
        end

        function parent = join(parent, nodes)
            firstRoot = ProjectionDenseObservationAssociator.root( ...
                parent, nodes(1));
            secondRoot = ProjectionDenseObservationAssociator.root( ...
                parent, nodes(2));
            if firstRoot ~= secondRoot
                parent(parent == max(firstRoot, secondRoot)) = ...
                    min(firstRoot, secondRoot);
            end
        end

        function rootValue = root(parent, node)
            rootValue = node;
            while parent(rootValue) ~= rootValue
                rootValue = parent(rootValue);
            end
        end

        function viewIds = componentViews(parent, rootValue, observations)
            memberMask = arrayfun(@(node) ...
                ProjectionDenseObservationAssociator.root(parent, node) == ...
                rootValue, 1:numel(observations));
            viewIds = string({observations(memberMask).ViewId});
        end

        function value = diagnostics(records, observations, tracks)
            states = string({records.AssociationState});
            reasons = string({records.AssociationReason});
            value = struct(InputPairRecordCount=numel(records), ...
                ObservationCount=numel(observations), ...
                ConsistentObservationCount=nnz([observations.Consistent]), ...
                TrackCount=numel(tracks), ...
                AcceptedPairRecordCount=nnz(states == "accepted"), ...
                RejectedPairRecordCount=nnz(states == "rejected"), ...
                DuplicateViewConflictCount=nnz( ...
                reasons == "duplicateViewConflict"), ...
                CompetingModeTrackCount=nnz([tracks.CompetingMode]), ...
                TwoViewTrackCount=nnz([tracks.ViewCount] == 2));
        end

        function [point, ranges, separation, condition, angle, valid] = ...
                triangulate(origins, vectors)
            directions = vectors ./ vecnorm(vectors, 2, 1);
            matrix = [directions(:, 1) -directions(:, 2)];
            singularValues = svd(matrix, "econ");
            condition = singularValues(1) / max(singularValues(end), eps);
            ranges = matrix \ (origins(:, 2) - origins(:, 1));
            firstPoint = origins(:, 1) + directions(:, 1) * ranges(1);
            secondPoint = origins(:, 2) + directions(:, 2) * ranges(2);
            point = 0.5 * (firstPoint + secondPoint);
            separation = norm(firstPoint - secondPoint);
            angle = acosd(min(1, max(-1, abs(dot( ...
                directions(:, 1), directions(:, 2))))));
            valid = all(isfinite(point)) && all(ranges > 0) && ...
                singularValues(end) > 1e-10;
            if ~valid
                point(:) = NaN;
            end
        end

        function value = nonemptyString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || ...
                    strlength(strip(value)) == 0
                error("ProjectionDenseObservationAssociator:invalidIdentity", ...
                    "%s must be a nonempty string scalar.", name);
            end
            value = strip(value);
        end

        function value = boundedScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 0 || value > 1
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "%s must be a finite scalar in [0,1].", name);
            end
            value = double(value);
        end

        function value = finiteOrNanScalar(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~(isfinite(value) || isnan(value))
                error("ProjectionDenseObservationAssociator:invalidQuality", ...
                    "%s must be a finite scalar or NaN.", name);
            end
            value = double(value);
        end

        function value = positiveScalar(value, name, allowInf)
            if ~isnumeric(value) || ~isscalar(value) || isnan(value) || ...
                    value <= 0 || (~allowInf && ~isfinite(value))
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "%s must be a positive scalar%s.", name, ...
                    ProjectionDenseObservationAssociator.infSuffix(allowInf));
            end
            value = double(value);
        end

        function value = boundedAngle(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 0 || value >= 90
                error("ProjectionDenseObservationAssociator:invalidOptions", ...
                    "%s must be in [0,90) degrees.", name);
            end
            value = double(value);
        end

        function suffix = infSuffix(allowInf)
            suffix = "";
            if allowInf
                suffix = " or Inf";
            end
        end

        function value = optionalVector(value, count, name)
            if isempty(value)
                value = zeros(count, 0);
                return
            end
            if ~isnumeric(value) || numel(value) ~= count || ...
                    any(~isfinite(value))
                error("ProjectionDenseObservationAssociator:invalidGeometry", ...
                    "%s must be empty or a finite %d-vector.", name, count);
            end
            value = reshape(double(value), count, 1);
        end

        function record = emptyRecord()
            record = struct(RecordId="", PairId="", ...
                ViewIds=strings(1, 2), PassIds=strings(1, 2), ...
                ObservationIds=strings(1, 2), ...
                SourceObservationsPixels=nan(2), ...
                RayOriginsWorld=nan(3, 2), RayVectorsWorld=nan(3, 2), ...
                MatchState="valid", Score=NaN, Confidence=1, ...
                TextureScore=1, NavigationWeights=ones(1, 2), ...
                RadiometricValues=nan(1, 2), ...
                RadiometricConsistency=1, ...
                VisibilityStates=["visible" "visible"], ...
                ProvisionalPointWorld=zeros(3, 0), ...
                PairwiseCovarianceWorldMetersSquared=[], ModeId="", ...
                NodeIndices=zeros(1, 2), ...
                PairRayParametersMeters=nan(2, 1), ...
                PairRaySeparationMeters=Inf, PairConditionNumber=Inf, ...
                PairAngleDegrees=NaN, PairForwardValid=false, ...
                AssociationState="candidate", AssociationReason="", ...
                ModeKey="", TrackId="");
        end

        function candidate = emptyCandidate()
            candidate = struct(NodeKey="", RecordIndex=0, Side=0, ...
                RecordId="", PairId="", ViewId="", PassId="", ...
                ObservationId="", SourceObservationPixels=nan(1, 2), ...
                RayOriginWorld=nan(3, 1), RayVectorWorld=nan(3, 1), ...
                Confidence=0, NavigationWeight=0, RadiometricValue=NaN, ...
                VisibilityState="unknown");
        end

        function observations = emptyObservations()
            observations = struct("ObservationKey", {}, ...
                "ObservationId", {}, "ViewId", {}, ...
                "PassId", {}, "SourceRowPixels", {}, ...
                "SourceColumnPixels", {}, "RayOriginWorld", {}, ...
                "RayVectorWorld", {}, "Confidence", {}, ...
                "NavigationWeight", {}, "RadiometricValue", {}, ...
                "VisibilityState", {}, "Consistent", {}, ...
                "ConflictReason", {}, "OccurrenceCount", {}, ...
                "RecordIds", {}, "PairIds", {});
        end

        function tracks = emptyTracks()
            tracks = struct("TrackId", {}, "ModeId", {}, ...
                "CompetingMode", {}, "ObservationIndices", {}, ...
                "ObservationKeys", {}, "ObservationIds", {}, ...
                "ViewIds", {}, "PassIds", {}, ...
                "RecordIds", {}, "PairIds", {}, "ViewCount", {}, ...
                "IndependentPassCount", {}, "PairRecordCount", {}, ...
                "State", {});
        end
    end
end
