classdef ProjectionSurfaceProductCatalog
    %ProjectionSurfaceProductCatalog Serializable B6 surface-product catalog.

    properties (Constant)
        Format = "ProjectionSurfaceProductCatalog"
        Version = 1
    end

    methods (Static)
        function catalog = create(pointSet, fusionResults, optionalProducts)
            %create Adapt authoritative B5 and derived S6 results.
            if nargin < 2 || isempty(fusionResults)
                fusionResults = cell(1, 0);
            elseif isstruct(fusionResults) && isscalar(fusionResults)
                fusionResults = {fusionResults};
            end
            if nargin < 3
                optionalProducts = ProjectionSurfaceProductCatalog. ...
                    emptyProducts();
            end
            pointSet = ProjectionSurfaceProductCatalog.validatePointSet(pointSet);
            if ~iscell(fusionResults) || ~isvector(fusionResults)
                error("ProjectionSurfaceProductCatalog:invalidFusionResults", ...
                    "Fusion results must be a cell vector of normalized results.");
            end
            products = ProjectionSurfaceProductCatalog.emptyProducts();
            raw = ProjectionSurfaceProductCatalog.rawProduct(pointSet);
            if raw.Status == "available"
                products(end + 1) = raw;
            end
            robust = ProjectionSurfaceProductCatalog.robustProduct(pointSet);
            products(end + 1) = robust;
            products(end + 1) = ProjectionSurfaceProductCatalog. ...
                uncertaintyProduct(robust);
            for index = 1:numel(fusionResults)
                result = fusionResults{index};
                ProjectionSurfaceFusionResult.metadata(result);
                if string(result.WorldFrame) ~= string(pointSet.WorldFrame)
                    error("ProjectionSurfaceProductCatalog:frameMismatch", ...
                        "Every fusion result must use the point-set world frame.");
                end
                products = [products ProjectionSurfaceProductCatalog. ...
                    fusionProducts(pointSet, result)]; %#ok<AGROW>
            end
            if ~isempty(optionalProducts)
                products = [products reshape(optionalProducts, 1, [])];
            end
            products = ProjectionSurfaceProductCatalog.addPlaceholders(products);
            identities = struct(PointSetGenerationId=pointSet.GenerationId, ...
                ProductIds=string({products.ProductId}), ...
                ProductStages=string({products.Stage}));
            catalog = struct(Format=ProjectionSurfaceProductCatalog.Format, ...
                Version=ProjectionSurfaceProductCatalog.Version, ...
                WorldFrame=pointSet.WorldFrame, ...
                GenerationId="surface-catalog-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(identities), 17), ...
                SourcePointSetGenerationId=pointSet.GenerationId, ...
                ViewIds=ProjectionSurfaceProductCatalog.unionPointField( ...
                pointSet.Points, "ContributingViewIds"), ...
                PassIds=ProjectionSurfaceProductCatalog.unionPointField( ...
                pointSet.Points, "ContributingPassIds"), ...
                PairIds=ProjectionSurfaceProductCatalog.unionPointField( ...
                pointSet.Points, "ContributingPairIds"), ...
                Products=products, ...
                Diagnostics=struct(ProductCount=numel(products), ...
                AvailableProductCount=nnz(string({products.Status}) == ...
                "available"), FullElementCount=sum([products.FullElementCount]), ...
                EstimatedMemoryBytes=sum([products.EstimatedMemoryBytes]), ...
                GraphicsStateIncluded=false));
            catalog = ProjectionSurfaceProductCatalog.validate(catalog);
        end

        function catalog = validate(catalog)
            %validate Normalize one versioned graphics-free catalog.
            required = ["Format" "Version" "WorldFrame" "GenerationId" ...
                "SourcePointSetGenerationId" "ViewIds" "PassIds" ...
                "PairIds" "Products" "Diagnostics"];
            if ~isstruct(catalog) || ~isscalar(catalog) || ...
                    any(~isfield(catalog, required))
                error("ProjectionSurfaceProductCatalog:invalidCatalog", ...
                    "Surface catalog fields are incomplete.");
            end
            catalog.Format = string(catalog.Format);
            catalog.WorldFrame = string(catalog.WorldFrame);
            catalog.GenerationId = string(catalog.GenerationId);
            catalog.SourcePointSetGenerationId = ...
                string(catalog.SourcePointSetGenerationId);
            identities = {catalog.Format catalog.WorldFrame ...
                catalog.GenerationId catalog.SourcePointSetGenerationId};
            invalidIdentity = cellfun(@(value) ~isscalar(value) || ...
                ismissing(value) || strlength(value) == 0, identities);
            if any(invalidIdentity) || ...
                    catalog.Format ~= ProjectionSurfaceProductCatalog.Format || ...
                    ~isequal(catalog.Version, ProjectionSurfaceProductCatalog.Version)
                error("ProjectionSurfaceProductCatalog:unsupportedSchema", ...
                    "Surface catalog format, version, frame, and generation are required.");
            end
            catalog.ViewIds = ProjectionSurfaceProductCatalog.identities( ...
                catalog.ViewIds, "ViewIds");
            catalog.PassIds = ProjectionSurfaceProductCatalog.identities( ...
                catalog.PassIds, "PassIds");
            catalog.PairIds = ProjectionSurfaceProductCatalog.identities( ...
                catalog.PairIds, "PairIds");
            if ~isstruct(catalog.Products) || isempty(catalog.Products) || ...
                    ~isstruct(catalog.Diagnostics) || ...
                    ~isscalar(catalog.Diagnostics) || ...
                    ProjectionSurfaceProductCatalog.hasRuntimeValue(catalog)
                error("ProjectionSurfaceProductCatalog:invalidCatalog", ...
                    "Catalog products/diagnostics must be portable value structs.");
            end
            for index = 1:numel(catalog.Products)
                catalog.Products(index) = ProjectionSurfaceProductCatalog. ...
                    validateProduct(catalog.Products(index), catalog.WorldFrame);
            end
            productIds = string({catalog.Products.ProductId});
            if numel(unique(productIds)) ~= numel(productIds)
                error("ProjectionSurfaceProductCatalog:duplicateProductId", ...
                    "Surface ProductId values must be unique.");
            end
        end

        function product = meshProduct(productId, label, stage, role, ...
                vertices, faces, pointIds)
            %meshProduct Create one optional triangle-mesh catalog value.
            if nargin < 7 || isempty(pointIds)
                pointIds = "mesh-vertex-" + (1:size(vertices, 2));
            end
            points = ProjectionSurfaceProductCatalog.pointsFromCoordinates( ...
                vertices, pointIds, "mesh");
            mesh = struct(Vertices=double(vertices), Faces=double(faces), ...
                VertexPointIds=reshape(string(pointIds), 1, []));
            product = ProjectionSurfaceProductCatalog.product( ...
                productId, label, stage, "mesh", role, "available", ...
                points, mesh, struct(), "", struct(), struct());
        end

        function product = gridProduct(productId, label, stage, role, ...
                x, y, z, validMask)
            %gridProduct Create one optional gridded surface catalog value.
            if nargin < 8 || isempty(validMask)
                validMask = isfinite(z);
            end
            if ~isequal(size(x), size(y), size(z), size(validMask))
                error("ProjectionSurfaceProductCatalog:invalidGrid", ...
                    "Grid X, Y, Z, and ValidMask must have equal size.");
            end
            selected = logical(validMask) & isfinite(x) & isfinite(y) & isfinite(z);
            coordinates = [double(x(selected)).'; double(y(selected)).'; ...
                double(z(selected)).'];
            pointIds = "grid-point-" + (1:size(coordinates, 2));
            points = ProjectionSurfaceProductCatalog.pointsFromCoordinates( ...
                coordinates, pointIds, "grid");
            grid = struct(X=double(x), Y=double(y), Z=double(z), ...
                ValidMask=logical(validMask), PointIds=reshape(pointIds, 1, []));
            product = ProjectionSurfaceProductCatalog.product( ...
                productId, label, stage, "grid", role, "available", ...
                points, struct(), grid, "", struct(), struct());
        end

        function products = registrationProducts(pointSet, dem, result)
            %registrationProducts Adapt S7 DEM and preview values for B6.
            dem = ProjectionDemGrid.validate(dem);
            if ~isstruct(result) || ~isscalar(result) || ...
                    ~isfield(result, "Status") || ...
                    ~ismember(string(result.Status), ["succeeded" "ambiguous"])
                error("ProjectionSurfaceProductCatalog:invalidRegistration", ...
                    "Only successful or reviewable registration previews can display.");
            end
            sourceCatalog = ProjectionSurfaceProductCatalog.create(pointSet, {});
            robust = ProjectionSurfaceProductCatalog.find( ...
                sourceCatalog, "robust-multi-view");
            previewIds = reshape(string(result.Preview.PointIds), 1, []);
            pointIds = string({robust.Points.PointId});
            [found, locations] = ismember(pointIds, previewIds);
            if ~all(found) || ...
                    result.Preview.SourcePointSetGenerationId ~= pointSet.GenerationId
                error("ProjectionSurfaceProductCatalog:registrationMismatch", ...
                    "Registration preview must cover the complete source point set.");
            end
            registeredPoints = robust.Points;
            covariance = double(result.Covariance. ...
                TranslationWorldMetersSquared);
            for index = 1:numel(registeredPoints)
                location = locations(index);
                registeredPoints(index).PointWorld = ...
                    result.Preview.RegisteredPointsWorld(:, location);
                registeredPoints(index).DemDifferenceMeters = ...
                    result.Preview.DemDifferenceMeters(location);
                registeredPoints(index).FusionMethod = "demRegistrationPreview";
                registeredPoints(index).CovarianceWorldMetersSquared = ...
                    registeredPoints(index).CovarianceWorldMetersSquared + covariance;
                registeredPoints(index).UncertaintyMeters = ...
                    ProjectionSurfaceProductCatalog.uncertainty( ...
                    registeredPoints(index).CovarianceWorldMetersSquared);
            end
            provenance = struct(RegistrationAlgorithmId=result.AlgorithmId, ...
                RegistrationDirection=result.Transform.Direction, ...
                RegistrationFrame=result.Transform.Frame, ...
                AutoApplied=false, ...
                SourcePointSetGenerationId=pointSet.GenerationId);
            registered = ProjectionSurfaceProductCatalog.product( ...
                "registered", "DEM-registered preview", "registered", ...
                "pointCloud", "previewDerived", "available", ...
                registeredPoints, struct(), struct(), "", ...
                struct(RegistrationStatus=result.Status, ...
                AcceptedMask=result.Preview.AcceptedMask, ...
                CompleteImageryProductPreserved=true), provenance);
            difference = registered;
            difference.ProductId = "dem-difference";
            difference.Label = "Registered point-to-DEM difference";
            difference.Stage = "demDifference";
            difference.ProductRole = "diagnosticDerived";
            demProduct = ProjectionSurfaceProductCatalog.gridProduct( ...
                "dem", "Reference DEM (scene HAE)", "dem", ...
                "externalReference", dem.WorldX, dem.WorldY, dem.WorldZ, ...
                dem.ValidMask);
            demProduct.Diagnostics = struct(Accuracy=dem.Accuracy, ...
                DatumAssumption=dem.DatumAssumption, ...
                GeoidModel=dem.GeoidModel, ...
                RegistrationValidCellCount= ...
                dem.Diagnostics.RegistrationValidCellCount);
            demProduct.Provenance = struct(DatasetKind=dem.DatasetKind, ...
                WorldFrame=dem.WorldFrame, HeightReference="HAE");
            products = [demProduct registered difference];
        end

        function product = find(catalog, productId)
            %find Resolve a product by stable identity.
            catalog = ProjectionSurfaceProductCatalog.validate(catalog);
            productId = string(productId);
            match = string({catalog.Products.ProductId}) == productId;
            if nnz(match) ~= 1
                error("ProjectionSurfaceProductCatalog:unknownProduct", ...
                    "Surface product '%s' is not in the catalog.", productId);
            end
            product = catalog.Products(match);
        end

        function products = emptyProducts()
            %emptyProducts Return the normalized product schema.
            products = struct("ProductId", {}, "Label", {}, "Stage", {}, ...
                "Representation", {}, "ProductRole", {}, "Status", {}, ...
                "SourceProductId", {}, "Points", {}, "Mesh", {}, "Grid", {}, ...
                "Diagnostics", {}, "Provenance", {}, "FullElementCount", {}, ...
                "EstimatedMemoryBytes", {});
        end

        function points = emptyPoints()
            %emptyPoints Return the normalized display/scientific point schema.
            points = struct("PointId", {}, "PointWorld", {}, ...
                "SourceIntensity", {}, "IndependentViewCount", {}, ...
                "IndependentPassCount", {}, "ResidualMeters", {}, ...
                "UncertaintyMeters", {}, "ConditionNumber", {}, ...
                "FusionMethod", {}, "ViewIds", {}, "PassIds", {}, ...
                "PairIds", {}, "ObservationLinks", {}, ...
                "CovarianceWorldMetersSquared", {}, ...
                "DemDifferenceMeters", {}, "EvidenceWeight", {});
        end

        function links = emptyLinks()
            %emptyLinks Return the full-source observation-link schema.
            links = struct("ViewId", {}, "PassId", {}, ...
                "ObservationId", {}, "SourceColumnPixels", {}, ...
                "SourceRowPixels", {}, "Accepted", {});
        end
    end

    methods (Static, Access = private)
        function pointSet = validatePointSet(pointSet)
            if ~isstruct(pointSet) || ~isscalar(pointSet) || ...
                    ~isfield(pointSet, "Points") || isempty(pointSet.Points)
                error("ProjectionSurfaceProductCatalog:invalidPointSet", ...
                    "A nonempty B5 multi-ray point set is required.");
            end
            valid = [pointSet.Points.Valid];
            coordinates = horzcat(pointSet.Points(valid).PointWorld);
            if isempty(coordinates) || any(~isfinite(coordinates), "all")
                error("ProjectionSurfaceProductCatalog:invalidPointSet", ...
                    "At least one finite valid point is required.");
            end
            lower = min(coordinates, [], 2);
            upper = max(coordinates, [], 2);
            padding = max(1, 0.01 * max(upper - lower));
            roi = [lower - padding upper + padding];
            request = ProjectionSurfaceFusionRequest.validate(struct( ...
                PointSet=pointSet, RoiWorld=roi, VoxelScalesMeters=padding));
            pointSet = request.PointSet;
        end

        function product = rawProduct(pointSet)
            records = pointSet.RawPairwiseRecords;
            valid = arrayfun(@(record) ...
                isfield(record, "ProvisionalPointWorld") && ...
                isnumeric(record.ProvisionalPointWorld) && ...
                isequal(size(record.ProvisionalPointWorld), [3 1]) && ...
                all(isfinite(record.ProvisionalPointWorld)), records);
            records = records(valid);
            points = ProjectionSurfaceProductCatalog.emptyPoints();
            for index = 1:numel(records)
                record = records(index);
                links = ProjectionSurfaceProductCatalog.recordLinks(record);
                covariance = ProjectionSurfaceProductCatalog.field(record, ...
                    "PairwiseCovarianceWorldMetersSquared", nan(3));
                points(end + 1) = ProjectionSurfaceProductCatalog.point( ...
                    string(record.RecordId), double(record.ProvisionalPointWorld), ...
                    numel(unique(string(record.ViewIds))), ...
                    numel(unique(string(record.PassIds))), ...
                    ProjectionSurfaceProductCatalog.field(record, ...
                    "PairRaySeparationMeters", NaN), ...
                    ProjectionSurfaceProductCatalog.uncertainty(covariance), ...
                    ProjectionSurfaceProductCatalog.field(record, ...
                    "PairConditionNumber", NaN), "rawPairwise", ...
                    string(record.ViewIds), string(record.PassIds), ...
                    string(record.PairId), links, covariance, NaN); %#ok<AGROW>
                points(end).SourceIntensity = ProjectionSurfaceProductCatalog. ...
                    radiometricIntensity(record);
            end
            status = "available";
            if isempty(points)
                status = "unavailable";
            end
            product = ProjectionSurfaceProductCatalog.product( ...
                "raw-pairwise", "Raw pairwise points", "rawPairwise", ...
                "pointCloud", "provenance", status, points, struct(), ...
                struct(), "", struct(RecordCount=numel(records)), ...
                struct(SourcePointSetGenerationId=pointSet.GenerationId));
        end

        function product = robustProduct(pointSet)
            input = pointSet.Points([pointSet.Points.Valid]);
            points = ProjectionSurfaceProductCatalog.emptyPoints();
            for index = 1:numel(input)
                source = input(index);
                points(end + 1) = ProjectionSurfaceProductCatalog.point( ...
                    string(source.PointId), double(source.PointWorld), ...
                    source.IndependentViewCount, source.IndependentPassCount, ...
                    ProjectionSurfaceProductCatalog.field(source, ...
                    "RobustResidualRmsMeters", NaN), ...
                    ProjectionSurfaceProductCatalog.uncertainty( ...
                    source.CovarianceWorldMetersSquared), ...
                    ProjectionSurfaceProductCatalog.field(source, ...
                    "ConditionNumber", NaN), "robustMultiRay", ...
                    string(source.ContributingViewIds), ...
                    string(source.ContributingPassIds), ...
                    ProjectionSurfaceProductCatalog.field(source, ...
                    "ContributingPairIds", strings(1, 0)), ...
                    ProjectionSurfaceProductCatalog.rayLinks( ...
                    source.RayDiagnostics), ...
                    source.CovarianceWorldMetersSquared, NaN); %#ok<AGROW>
                points(end).SourceIntensity = ProjectionSurfaceProductCatalog. ...
                    contributingIntensity(pointSet, source);
            end
            product = ProjectionSurfaceProductCatalog.product( ...
                "robust-multi-view", "Robust multi-view points", ...
                "robustMultiView", "pointCloud", "authoritative", ...
                "available", points, struct(), struct(), "", ...
                struct(PointCount=numel(points)), ...
                struct(SourcePointSetGenerationId=pointSet.GenerationId));
        end

        function product = uncertaintyProduct(robust)
            product = ProjectionSurfaceProductCatalog.product( ...
                "uncertainty-filtered", "Uncertainty-filtered points", ...
                "uncertaintyFiltered", "pointCloud", "derived", ...
                "available", ProjectionSurfaceProductCatalog.emptyPoints(), ...
                struct(), struct(), robust.ProductId, ...
                struct(Filter="MaximumUncertaintyMeters"), ...
                struct(SourceProductId=robust.ProductId));
            product.FullElementCount = robust.FullElementCount;
            product.EstimatedMemoryBytes = 0;
        end

        function products = fusionProducts(pointSet, result)
            products = ProjectionSurfaceProductCatalog.emptyProducts();
            algorithmId = string(result.AlgorithmId);
            safeId = regexprep(algorithmId, "[^A-Za-z0-9_.-]", "-");
            points = ProjectionSurfaceProductCatalog.fusionPoints( ...
                pointSet, result.FusedPoints, algorithmId);
            if ~isempty(points)
                products(end + 1) = ProjectionSurfaceProductCatalog.product( ...
                    "fusion." + safeId, "Fused: " + algorithmId, ...
                    "fusionDerived", "pointCloud", result.ProductRole, ...
                    "available", points, struct(), struct(), "", ...
                    result.Diagnostics, result.Provenance);
            end
            evidence = result.SparseVoxelEvidence;
            if isempty(fieldnames(evidence))
                return
            end
            for scaleIndex = 1:numel(evidence.ScaleResults)
                scale = evidence.ScaleResults(scaleIndex);
                voxelPoints = ProjectionSurfaceProductCatalog.voxelPoints( ...
                    pointSet, scale, algorithmId);
                productId = "voxel." + safeId + ".scale-" + scaleIndex;
                products(end + 1) = ProjectionSurfaceProductCatalog.product( ...
                    productId, sprintf("%s voxels (%.6g m)", ...
                    algorithmId, scale.VoxelScaleMeters), ...
                    "voxelEvidence", "voxel", "diagnosticDerived", ...
                    "available", voxelPoints, struct(), struct(), "", ...
                    struct(VoxelScaleMeters=scale.VoxelScaleMeters, ...
                    AllocatedVoxelCount=scale.AllocatedVoxelCount, ...
                    GridCellCount=scale.GridCellCount), result.Provenance); %#ok<AGROW>
            end
        end

        function points = fusionPoints(pointSet, fusedPoints, algorithmId)
            points = ProjectionSurfaceProductCatalog.emptyPoints();
            for index = 1:numel(fusedPoints)
                fused = fusedPoints(index);
                contributors = ProjectionSurfaceProductCatalog. ...
                    contributorPoints(pointSet, fused.ContributingPointIds);
                points(end + 1) = ProjectionSurfaceProductCatalog.point( ...
                    string(fused.PointId), double(fused.PointWorld), ...
                    fused.IndependentViewCount, fused.IndependentPassCount, ...
                    ProjectionSurfaceProductCatalog.aggregateField( ...
                    contributors, "RobustResidualRmsMeters", "median"), ...
                    ProjectionSurfaceProductCatalog.uncertainty( ...
                    fused.CovarianceWorldMetersSquared), ...
                    ProjectionSurfaceProductCatalog.aggregateField( ...
                    contributors, "ConditionNumber", "maximum"), ...
                    algorithmId, string(fused.ContributingViewIds), ...
                    string(fused.ContributingPassIds), ...
                    ProjectionSurfaceProductCatalog.unionPointField( ...
                    contributors, "ContributingPairIds"), ...
                    ProjectionSurfaceProductCatalog.pointLinks(contributors), ...
                    fused.CovarianceWorldMetersSquared, NaN); %#ok<AGROW>
                points(end).SourceIntensity = ProjectionSurfaceProductCatalog. ...
                    contributingIntensity(pointSet, contributors);
            end
        end

        function points = voxelPoints(pointSet, scale, algorithmId)
            points = ProjectionSurfaceProductCatalog.emptyPoints();
            for modeIndex = 1:numel(scale.Modes)
                mode = scale.Modes(modeIndex);
                for index = 1:size(mode.CentersWorld, 2)
                    contributorIds = mode.ContributingPointIds{index};
                    contributors = ProjectionSurfaceProductCatalog. ...
                        contributorPoints(pointSet, contributorIds);
                    covariance = (scale.VoxelScaleMeters ^ 2 / 12) * eye(3);
                    pointId = "voxel-" + modeIndex + "-" + ...
                        strjoin(string(mode.Indices(index, :)), "-");
                    points(end + 1) = ProjectionSurfaceProductCatalog.point( ...
                        pointId, mode.CentersWorld(:, index), ...
                        mode.IndependentViewCounts(index), ...
                        mode.IndependentPassCounts(index), ...
                        ProjectionSurfaceProductCatalog.aggregateField( ...
                        contributors, "RobustResidualRmsMeters", "median"), ...
                        ProjectionSurfaceProductCatalog.uncertainty(covariance), ...
                        ProjectionSurfaceProductCatalog.aggregateField( ...
                        contributors, "ConditionNumber", "maximum"), ...
                        algorithmId + ":" + mode.ModeId, ...
                        mode.ContributingViewIds{index}, ...
                        mode.ContributingPassIds{index}, ...
                        ProjectionSurfaceProductCatalog.unionPointField( ...
                        contributors, "ContributingPairIds"), ...
                        ProjectionSurfaceProductCatalog.pointLinks(contributors), ...
                        covariance, double(mode.EvidenceWeights(index))); %#ok<AGROW>
                    points(end).SourceIntensity = ProjectionSurfaceProductCatalog. ...
                        contributingIntensity(pointSet, contributors);
                end
            end
        end

        function products = addPlaceholders(products)
            placeholders = [ ...
                ProjectionSurfaceProductCatalog.placeholder( ...
                "mesh", "Local mesh/TIN", "mesh", "mesh") ...
                ProjectionSurfaceProductCatalog.placeholder( ...
                "grid", "Gridded elevation", "grid", "grid") ...
                ProjectionSurfaceProductCatalog.placeholder( ...
                "dem", "Reference DEM", "dem", "grid") ...
                ProjectionSurfaceProductCatalog.placeholder( ...
                "registered", "DEM-registered surface", "registered", "pointCloud") ...
                ProjectionSurfaceProductCatalog.placeholder( ...
                "dem-difference", "DEM difference", "demDifference", "grid")];
            ids = string({products.ProductId});
            products = [products placeholders(~ismember( ...
                string({placeholders.ProductId}), ids))];
        end

        function product = placeholder(productId, label, stage, representation)
            product = ProjectionSurfaceProductCatalog.product( ...
                productId, label, stage, representation, "derived", ...
                "unavailable", ProjectionSurfaceProductCatalog.emptyPoints(), ...
                struct(), struct(), "", struct(Reason="notProvided"), struct());
        end

        function product = product(productId, label, stage, representation, ...
                role, status, points, mesh, grid, sourceProductId, diagnostics, provenance)
            product = struct(ProductId=string(productId), Label=string(label), ...
                Stage=string(stage), Representation=string(representation), ...
                ProductRole=string(role), Status=string(status), ...
                SourceProductId=string(sourceProductId), Points=points, ...
                Mesh=mesh, Grid=grid, Diagnostics=diagnostics, ...
                Provenance=provenance, FullElementCount=numel(points), ...
                EstimatedMemoryBytes=ProjectionSurfaceProductCatalog.bytes( ...
                struct(Points=points, Mesh=mesh, Grid=grid)));
        end

        function product = validateProduct(product, worldFrame)
            template = ProjectionSurfaceProductCatalog.placeholder( ...
                "template", "template", "rawPairwise", "pointCloud");
            required = string(fieldnames(template));
            if ~isstruct(product) || ~isscalar(product) || ...
                    any(~isfield(product, required))
                error("ProjectionSurfaceProductCatalog:invalidProduct", ...
                    "Every surface product requires the complete schema.");
            end
            stringsToCheck = ["ProductId" "Label" "Stage" ...
                "Representation" "ProductRole" "Status" "SourceProductId"];
            for field = stringsToCheck
                product.(field) = string(product.(field));
                if ~isscalar(product.(field)) || ismissing(product.(field))
                    error("ProjectionSurfaceProductCatalog:invalidProduct", ...
                        "%s must be a string scalar.", field);
                end
            end
            if strlength(product.ProductId) == 0 || ...
                    strlength(product.Label) == 0 || ...
                    ~ismember(product.Stage, ["rawPairwise" "robustMultiView" ...
                    "uncertaintyFiltered" "fusionDerived" "voxelEvidence" ...
                    "mesh" "grid" "dem" "registered" "demDifference"]) || ...
                    ~ismember(product.Representation, ...
                    ["pointCloud" "voxel" "mesh" "grid"]) || ...
                    ~ismember(product.Status, ["available" "unavailable"]) || ...
                    ~isstruct(product.Points) || ~isscalar(product.Diagnostics) || ...
                    ~isstruct(product.Diagnostics) || ~isscalar(product.Provenance) || ...
                    ~isstruct(product.Provenance)
                error("ProjectionSurfaceProductCatalog:invalidProduct", ...
                    "Surface product identity, state, or payload is malformed.");
            end
            product.Points = ProjectionSurfaceProductCatalog. ...
                validatePoints(product.Points, worldFrame);
            ProjectionSurfaceProductCatalog.validateRepresentation(product);
            if ~isnumeric(product.FullElementCount) || ...
                    ~isscalar(product.FullElementCount) || ...
                    product.FullElementCount < numel(product.Points) || ...
                    fix(product.FullElementCount) ~= product.FullElementCount || ...
                    ~isnumeric(product.EstimatedMemoryBytes) || ...
                    ~isscalar(product.EstimatedMemoryBytes) || ...
                    ~isfinite(product.EstimatedMemoryBytes) || ...
                    product.EstimatedMemoryBytes < 0
                error("ProjectionSurfaceProductCatalog:invalidProduct", ...
                    "Product counts and memory estimates must be bounded values.");
            end
            if product.Status == "available" && ...
                    isempty(product.Points) && strlength(product.SourceProductId) == 0
                error("ProjectionSurfaceProductCatalog:emptyProduct", ...
                    "Available products require points or a source product.");
            end
        end

        function points = validatePoints(points, worldFrame)
            required = string(fieldnames( ...
                ProjectionSurfaceProductCatalog.point("template", zeros(3, 1), ...
                0, 0, NaN, NaN, NaN, "template", strings(1, 0), ...
                strings(1, 0), strings(1, 0), ...
                ProjectionSurfaceProductCatalog.emptyLinks(), nan(3), NaN)));
            for index = 1:numel(points)
                if any(~isfield(points(index), required)) || ...
                        ~isnumeric(points(index).PointWorld) || ...
                        ~isequal(size(points(index).PointWorld), [3 1]) || ...
                        any(~isfinite(points(index).PointWorld)) || ...
                        ~isnumeric(points(index).CovarianceWorldMetersSquared) || ...
                        ~isequal(size( ...
                        points(index).CovarianceWorldMetersSquared), [3 3]) || ...
                        ~isstruct(points(index).ObservationLinks)
                    error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                        "Catalog points require finite world geometry and link values.");
                end
                points(index).PointId = string(points(index).PointId);
                points(index).FusionMethod = string(points(index).FusionMethod);
                if ~isscalar(points(index).PointId) || ...
                        strlength(points(index).PointId) == 0 || ...
                        ~isscalar(points(index).FusionMethod) || ...
                        strlength(points(index).FusionMethod) == 0
                    error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                        "Catalog point identity must be explicit.");
                end
                points(index).ViewIds = ProjectionSurfaceProductCatalog. ...
                    identityList(points(index).ViewIds);
                points(index).PassIds = ProjectionSurfaceProductCatalog. ...
                    identityList(points(index).PassIds);
                points(index).PairIds = ProjectionSurfaceProductCatalog. ...
                    identityList(points(index).PairIds);
                ProjectionSurfaceProductCatalog.validatePointScalars( ...
                    points(index));
                points(index).ObservationLinks = ...
                    ProjectionSurfaceProductCatalog.validateLinks( ...
                    points(index).ObservationLinks);
            end
            if numel(unique(string({points.PointId}))) ~= numel(points)
                error("ProjectionSurfaceProductCatalog:duplicatePointId", ...
                    "Point IDs must be unique within a product in frame %s.", ...
                    worldFrame);
            end
        end

        function validateRepresentation(product)
            if product.Status ~= "available" || ...
                    strlength(product.SourceProductId) > 0
                return
            end
            if product.Representation == "mesh"
                required = ["Vertices" "Faces" "VertexPointIds"];
                mesh = product.Mesh;
                if ~isstruct(mesh) || ~isscalar(mesh) || ...
                        any(~isfield(mesh, required)) || ...
                        ~isnumeric(mesh.Vertices) || ...
                        size(mesh.Vertices, 1) ~= 3 || ...
                        any(~isfinite(mesh.Vertices), "all") || ...
                        ~isnumeric(mesh.Faces) || size(mesh.Faces, 2) ~= 3 || ...
                        any(~isfinite(mesh.Faces), "all") || ...
                        any(mesh.Faces < 1, "all") || ...
                        any(fix(mesh.Faces) ~= mesh.Faces, "all") || ...
                        any(mesh.Faces > size(mesh.Vertices, 2), "all") || ...
                        numel(mesh.VertexPointIds) ~= size(mesh.Vertices, 2) || ...
                        numel(product.Points) ~= size(mesh.Vertices, 2) || ...
                        ~isequal(horzcat(product.Points.PointWorld), ...
                        double(mesh.Vertices)) || ...
                        ~isequal(string({product.Points.PointId}), ...
                        reshape(string(mesh.VertexPointIds), 1, []))
                    error("ProjectionSurfaceProductCatalog:invalidMesh", ...
                        "Available mesh products require consistent vertices and faces.");
                end
            elseif product.Representation == "grid"
                required = ["X" "Y" "Z" "ValidMask" "PointIds"];
                grid = product.Grid;
                if ~isstruct(grid) || ~isscalar(grid) || ...
                        any(~isfield(grid, required)) || ...
                        ~isnumeric(grid.X) || ~isnumeric(grid.Y) || ...
                        ~isnumeric(grid.Z) || ~islogical(grid.ValidMask) || ...
                        ~isequal(size(grid.X), size(grid.Y), size(grid.Z), ...
                        size(grid.ValidMask))
                    error("ProjectionSurfaceProductCatalog:invalidGrid", ...
                        "Available grid products require equally sized numeric arrays.");
                end
                selected = grid.ValidMask & isfinite(grid.X) & ...
                    isfinite(grid.Y) & isfinite(grid.Z);
                coordinates = [double(grid.X(selected)).'; ...
                    double(grid.Y(selected)).'; double(grid.Z(selected)).'];
                if numel(grid.PointIds) ~= nnz(selected) || ...
                        numel(product.Points) ~= nnz(selected) || ...
                        ~isequal(horzcat(product.Points.PointWorld), coordinates) || ...
                        ~isequal(string({product.Points.PointId}), ...
                        reshape(string(grid.PointIds), 1, []))
                    error("ProjectionSurfaceProductCatalog:invalidGrid", ...
                        "Grid points and identities must match valid cells.");
                end
            end
        end

        function validatePointScalars(point)
            scalars = ["SourceIntensity" "ResidualMeters" ...
                "UncertaintyMeters" "ConditionNumber" ...
                "DemDifferenceMeters" "EvidenceWeight"];
            for field = scalars
                value = point.(field);
                if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ...
                        ~(isfinite(value) || isnan(value))
                    error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                        "%s must be one finite scalar or NaN.", field);
                end
            end
            counts = [point.IndependentViewCount point.IndependentPassCount];
            if any(~isfinite(counts)) || any(counts < 0) || ...
                    any(fix(counts) ~= counts) || ...
                    (isfinite(point.UncertaintyMeters) && ...
                    point.UncertaintyMeters < 0) || ...
                    (isfinite(point.ConditionNumber) && ...
                    point.ConditionNumber < 0) || ...
                    (isfinite(point.EvidenceWeight) && point.EvidenceWeight < 0)
                error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                    "Point counts and nonnegative metrics are malformed.");
            end
            covariance = double(point.CovarianceWorldMetersSquared);
            finiteCovariance = all(isfinite(covariance), "all");
            missingCovariance = all(isnan(covariance), "all");
            tolerance = 1e-12 * max(1, norm(covariance, "fro"));
            positiveSemidefinite = finiteCovariance && ...
                norm(covariance - covariance.', "fro") <= tolerance && ...
                min(eig(0.5 * (covariance + covariance.'))) >= -tolerance;
            if ~(missingCovariance || positiveSemidefinite)
                error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                    "Point covariance must be all-NaN or symmetric PSD.");
            end
        end

        function links = validateLinks(links)
            required = ["ViewId" "PassId" "ObservationId" ...
                "SourceColumnPixels" "SourceRowPixels" "Accepted"];
            for index = 1:numel(links)
                if any(~isfield(links(index), required))
                    error("ProjectionSurfaceProductCatalog:invalidLink", ...
                        "Observation links require the complete schema.");
                end
                viewId = string(links(index).ViewId);
                passId = string(links(index).PassId);
                observationId = string(links(index).ObservationId);
                identities = [viewId passId observationId];
                pixels = [links(index).SourceColumnPixels ...
                    links(index).SourceRowPixels];
                if ~isscalar(viewId) || ~isscalar(passId) || ...
                        ~isscalar(observationId) || any(ismissing(identities)) || ...
                        any(strlength(identities) == 0) || ...
                        ~isnumeric(pixels) || any(~isfinite(pixels)) || ...
                        any(pixels <= 0) || ~isscalar(links(index).Accepted) || ...
                        ~(islogical(links(index).Accepted) || ...
                        (isnumeric(links(index).Accepted) && ...
                        ismember(links(index).Accepted, [0 1])))
                    error("ProjectionSurfaceProductCatalog:invalidLink", ...
                        "Observation links require identities, pixels, and state.");
                end
                links(index).ViewId = identities(1);
                links(index).PassId = identities(2);
                links(index).ObservationId = identities(3);
                links(index).SourceColumnPixels = double(pixels(1));
                links(index).SourceRowPixels = double(pixels(2));
                links(index).Accepted = logical(links(index).Accepted);
            end
        end

        function values = identityList(values)
            values = reshape(string(values), 1, []);
            if any(ismissing(values)) || any(strlength(values) == 0)
                error("ProjectionSurfaceProductCatalog:invalidPoint", ...
                    "Point view/pass/pair identities must be nonempty.");
            end
            values = unique(values, "stable");
        end

        function point = point(pointId, pointWorld, viewCount, passCount, ...
                residual, uncertainty, condition, fusionMethod, viewIds, ...
                passIds, pairIds, links, covariance, evidenceWeight)
            point = struct(PointId=string(pointId), ...
                PointWorld=double(pointWorld), SourceIntensity=NaN, ...
                IndependentViewCount=double(viewCount), ...
                IndependentPassCount=double(passCount), ...
                ResidualMeters=double(residual), ...
                UncertaintyMeters=double(uncertainty), ...
                ConditionNumber=double(condition), ...
                FusionMethod=string(fusionMethod), ...
                ViewIds=reshape(string(viewIds), 1, []), ...
                PassIds=reshape(string(passIds), 1, []), ...
                PairIds=reshape(string(pairIds), 1, []), ...
                ObservationLinks=links, ...
                CovarianceWorldMetersSquared=double(covariance), ...
                DemDifferenceMeters=NaN, ...
                EvidenceWeight=double(evidenceWeight));
        end

        function points = pointsFromCoordinates(coordinates, pointIds, method)
            if ~isnumeric(coordinates) || size(coordinates, 1) ~= 3 || ...
                    any(~isfinite(coordinates), "all") || ...
                    numel(pointIds) ~= size(coordinates, 2)
                error("ProjectionSurfaceProductCatalog:invalidCoordinates", ...
                    "Optional product coordinates must be finite 3xN values.");
            end
            points = ProjectionSurfaceProductCatalog.emptyPoints();
            for index = 1:size(coordinates, 2)
                points(end + 1) = ProjectionSurfaceProductCatalog.point( ...
                    string(pointIds(index)), coordinates(:, index), 0, 0, ...
                    NaN, NaN, NaN, method, strings(1, 0), ...
                    strings(1, 0), strings(1, 0), ...
                    ProjectionSurfaceProductCatalog.emptyLinks(), nan(3), NaN); %#ok<AGROW>
            end
        end

        function links = recordLinks(record)
            links = ProjectionSurfaceProductCatalog.emptyLinks();
            for side = 1:2
                source = record.SourceObservationsPixels(side, :);
                links(end + 1) = struct(ViewId=string(record.ViewIds(side)), ...
                    PassId=string(record.PassIds(side)), ...
                    ObservationId=string(record.ObservationIds(side)), ...
                    SourceColumnPixels=double(source(2)), ...
                    SourceRowPixels=double(source(1)), Accepted=true); %#ok<AGROW>
            end
        end

        function links = rayLinks(rays)
            links = ProjectionSurfaceProductCatalog.emptyLinks();
            for index = 1:numel(rays)
                links(end + 1) = struct(ViewId=string(rays(index).ViewId), ...
                    PassId=string(rays(index).PassId), ...
                    ObservationId=string(rays(index).ObservationId), ...
                    SourceColumnPixels=double(rays(index).SourceColumnPixels), ...
                    SourceRowPixels=double(rays(index).SourceRowPixels), ...
                    Accepted=logical(rays(index).Accepted)); %#ok<AGROW>
            end
        end

        function links = pointLinks(points)
            links = ProjectionSurfaceProductCatalog.emptyLinks();
            for index = 1:numel(points)
                links = [links ProjectionSurfaceProductCatalog. ...
                    rayLinks(points(index).RayDiagnostics)]; %#ok<AGROW>
            end
            if isempty(links)
                return
            end
            keys = string({links.ViewId}) + "|" + string({links.ObservationId});
            [~, selected] = unique(keys, "stable");
            links = links(selected);
        end

        function points = contributorPoints(pointSet, pointIds)
            pointIds = reshape(string(pointIds), 1, []);
            points = pointSet.Points(ismember( ...
                string({pointSet.Points.PointId}), pointIds));
        end

        function uncertainty = uncertainty(covariance)
            uncertainty = NaN;
            if isnumeric(covariance) && isequal(size(covariance), [3 3]) && ...
                    all(isfinite(covariance), "all")
                uncertainty = sqrt(max(0, trace(double(covariance))));
            end
        end

        function value = aggregateField(points, field, method)
            value = NaN;
            if isempty(points) || ~isfield(points, field)
                return
            end
            values = double([points.(field)]);
            values = values(isfinite(values));
            if isempty(values)
                return
            end
            if method == "maximum"
                value = max(values);
            else
                value = median(values);
            end
        end

        function value = contributingIntensity(pointSet, points)
            recordIds = ProjectionSurfaceProductCatalog.unionPointField( ...
                points, "ContributingRecordIds");
            records = pointSet.RawPairwiseRecords(ismember(string( ...
                {pointSet.RawPairwiseRecords.RecordId}), recordIds));
            value = ProjectionSurfaceProductCatalog.radiometricIntensity(records);
        end

        function value = radiometricIntensity(records)
            values = zeros(1, 0);
            for index = 1:numel(records)
                radiometry = ProjectionSurfaceProductCatalog.field( ...
                    records(index), "RadiometricValues", zeros(1, 0));
                values = [values reshape(double(radiometry), 1, [])]; %#ok<AGROW>
            end
            values = values(isfinite(values));
            value = NaN;
            if ~isempty(values)
                value = mean(values);
            end
        end

        function values = unionPointField(points, field)
            values = strings(1, 0);
            if isempty(points) || ~isfield(points, field)
                return
            end
            for index = 1:numel(points)
                values = [values reshape(string(points(index).(field)), 1, [])]; %#ok<AGROW>
            end
            values = sort(unique(values));
        end

        function value = field(source, name, defaultValue)
            if isfield(source, name)
                value = source.(name);
            else
                value = defaultValue;
            end
        end

        function values = identities(values, name)
            values = reshape(string(values), 1, []);
            if any(ismissing(values)) || any(strlength(values) == 0) || ...
                    numel(unique(values)) ~= numel(values)
                error("ProjectionSurfaceProductCatalog:invalidIdentity", ...
                    "%s must contain unique nonempty identities.", name);
            end
            values = sort(values);
        end

        function bytes = bytes(value)
            if isempty(value)
                bytes = 0;
                return
            end
            info = whos("value");
            bytes = double(info.bytes);
        end

        function tf = hasRuntimeValue(value)
            if isa(value, "function_handle") || ...
                    (isobject(value) && isa(value, "handle")) || isjava(value)
                tf = true;
            elseif isstruct(value)
                tf = false;
                names = fieldnames(value);
                for element = 1:numel(value)
                    for index = 1:numel(names)
                        if ProjectionSurfaceProductCatalog.hasRuntimeValue( ...
                                value(element).(names{index}))
                            tf = true;
                            return
                        end
                    end
                end
            elseif iscell(value)
                tf = false;
                for index = 1:numel(value)
                    if ProjectionSurfaceProductCatalog.hasRuntimeValue(value{index})
                        tf = true;
                        return
                    end
                end
            else
                tf = false;
            end
        end
    end
end
