classdef ProjectionDemGrid
    %ProjectionDemGrid Strict WGS84 DEM value normalized to scene ENU/HAE.

    properties (Constant)
        Format = "ProjectionDemGrid"
        Version = 1
    end

    methods (Static)
        function dem = create(input)
            %create Normalize one WGS84 latitude/longitude elevation grid.
            if ~isstruct(input) || ~isscalar(input)
                error("ProjectionDemGrid:invalidInput", ...
                    "DEM input must be a scalar struct.");
            end
            defaults = struct(LatitudeDegrees=[], LongitudeDegrees=[], ...
                HeightsMeters=[], DatasetKind="WGS84Grid", ...
                HeightReference="", GeoidModel="", NoDataValue=[], ...
                ValidityMask=[], ExclusionMask=[], CallerAccuracy=struct(), ...
                DatasetAccuracy=struct(), SceneFrame=struct());
            names = string(fieldnames(input));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDemGrid:invalidInput", ...
                    "Unexpected DEM input field: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = input.(name);
            end
            input = defaults;
            [latitude, longitude, heights] = ProjectionDemGrid.inputGrid( ...
                input.LatitudeDegrees, input.LongitudeDegrees, ...
                input.HeightsMeters);
            datasetKind = ProjectionDemGrid.enumValue(input.DatasetKind, ...
                ["WGS84Grid" "DTED2"], "DatasetKind");
            [heightReference, geoidModel, datumAssumption] = ...
                ProjectionDemGrid.datum(input.HeightReference, ...
                input.GeoidModel, datasetKind);
            noDataValue = ProjectionDemGrid.noDataValue(input.NoDataValue);
            baseValid = isfinite(latitude) & isfinite(longitude) & ...
                isfinite(heights);
            if ~isempty(noDataValue)
                baseValid = baseValid & heights ~= noDataValue;
            end
            validityMask = ProjectionDemGrid.mask( ...
                input.ValidityMask, size(heights), true);
            exclusionMask = ProjectionDemGrid.mask( ...
                input.ExclusionMask, size(heights), false);
            baseValid = baseValid & validityMask;
            valid = baseValid & ~exclusionMask;
            if nnz(baseValid) < 4 || nnz(valid) < 4
                error("ProjectionDemGrid:insufficientCoverage", ...
                    "DEM ingestion requires at least four valid cells.");
            end
            geoid = zeros(size(heights));
            hae = double(heights);
            if heightReference == "MSL"
                geoid(baseValid) = egm96geoid( ...
                    latitude(baseValid), longitude(baseValid));
                hae(baseValid) = heights(baseValid) + geoid(baseValid);
            end
            hae(~baseValid) = NaN;
            geoid(~baseValid) = NaN;
            frame = ProjectionDemGrid.sceneFrame( ...
                input.SceneFrame, latitude, longitude, hae, baseValid);
            [east, north, up, worldX, worldY, worldZ, transforms] = ...
                ProjectionDemGrid.transformGrid( ...
                latitude, longitude, hae, baseValid, frame);
            accuracy = ProjectionDemGrid.accuracy( ...
                input.CallerAccuracy, input.DatasetAccuracy, datasetKind);
            dem = struct(Format=ProjectionDemGrid.Format, ...
                Version=ProjectionDemGrid.Version, DatasetKind=datasetKind, ...
                WorldFrame=frame.WorldFrame, ...
                HeightReferenceInput=heightReference, ...
                HeightReferenceWorking="HAE", GeoidModel=geoidModel, ...
                DatumAssumption=datumAssumption, ...
                LatitudeDegrees=latitude, LongitudeDegrees=longitude, ...
                InputHeightsMeters=double(heights), ...
                HaeHeightsMeters=hae, GeoidUndulationMeters=geoid, ...
                NoDataValue=noDataValue, BaseValidMask=baseValid, ...
                ExclusionMask=exclusionMask, ValidMask=valid, ...
                Accuracy=accuracy, Transforms=transforms, ...
                EnuEastMeters=east, EnuNorthMeters=north, ...
                EnuUpMeters=up, WorldX=worldX, WorldY=worldY, ...
                WorldZ=worldZ, Diagnostics=struct( ...
                CellCount=numel(heights), BaseValidCellCount=nnz(baseValid), ...
                ExcludedCellCount=nnz(baseValid & exclusionMask), ...
                RegistrationValidCellCount=nnz(valid), ...
                BaseCoverageFraction=nnz(baseValid) / numel(heights), ...
                RegistrationCoverageFraction=nnz(valid) / numel(heights), ...
                RuntimeStateIncluded=false));
            dem = ProjectionDemGrid.validate(dem);
        end

        function dem = validate(dem)
            %validate Validate an already normalized portable DEM value.
            required = ["Format" "Version" "DatasetKind" "WorldFrame" ...
                "HeightReferenceInput" "HeightReferenceWorking" ...
                "GeoidModel" "DatumAssumption" "LatitudeDegrees" ...
                "LongitudeDegrees" "InputHeightsMeters" ...
                "HaeHeightsMeters" "GeoidUndulationMeters" "NoDataValue" ...
                "BaseValidMask" "ExclusionMask" "ValidMask" "Accuracy" ...
                "Transforms" "EnuEastMeters" "EnuNorthMeters" ...
                "EnuUpMeters" "WorldX" "WorldY" "WorldZ" "Diagnostics"];
            if ~isstruct(dem) || ~isscalar(dem) || ...
                    any(~isfield(dem, required))
                error("ProjectionDemGrid:unsupportedSchema", ...
                    "DEM schema format/version and fields are required.");
            end
            format = string(dem.Format);
            if ~isscalar(format) || format ~= ProjectionDemGrid.Format || ...
                    ~isequal(dem.Version, ProjectionDemGrid.Version)
                error("ProjectionDemGrid:unsupportedSchema", ...
                    "DEM schema format/version and fields are required.");
            end
            if ProjectionDemGrid.hasRuntimeValue(dem)
                error("ProjectionDemGrid:runtimeState", ...
                    "DEM values cannot contain runtime handles or callbacks.");
            end
            dem.DatasetKind = ProjectionDemGrid.enumValue(dem.DatasetKind, ...
                ["WGS84Grid" "DTED2"], "DatasetKind");
            dem.HeightReferenceInput = ProjectionDemGrid.enumValue( ...
                dem.HeightReferenceInput, ["HAE" "MSL"], ...
                "HeightReferenceInput");
            if string(dem.HeightReferenceWorking) ~= "HAE" || ...
                    ~isscalar(string(dem.WorldFrame)) || ...
                    strlength(string(dem.WorldFrame)) == 0
                error("ProjectionDemGrid:invalidDatum", ...
                    "Working DEM heights must be explicit HAE in a world frame.");
            end
            shape = size(dem.HaeHeightsMeters);
            arrays = ["LatitudeDegrees" "LongitudeDegrees" ...
                "InputHeightsMeters" "GeoidUndulationMeters" ...
                "EnuEastMeters" "EnuNorthMeters" "EnuUpMeters" ...
                "WorldX" "WorldY" "WorldZ"];
            for field = arrays
                value = dem.(field);
                if ~isnumeric(value) || ~isequal(size(value), shape) || ...
                        ~isreal(value)
                    error("ProjectionDemGrid:invalidGrid", ...
                        "%s must match the elevation-grid shape.", field);
                end
                dem.(field) = double(value);
            end
            masks = ["BaseValidMask" "ExclusionMask" "ValidMask"];
            for field = masks
                if ~islogical(dem.(field)) || ...
                        ~isequal(size(dem.(field)), shape)
                    error("ProjectionDemGrid:invalidGrid", ...
                        "DEM masks must be logical grid arrays.");
                end
            end
            expectedValid = dem.BaseValidMask & ~dem.ExclusionMask;
            finiteWorking = isfinite(dem.HaeHeightsMeters) & ...
                isfinite(dem.EnuEastMeters) & isfinite(dem.EnuNorthMeters) & ...
                isfinite(dem.EnuUpMeters) & isfinite(dem.WorldX) & ...
                isfinite(dem.WorldY) & isfinite(dem.WorldZ);
            if ~isequal(dem.ValidMask, expectedValid) || ...
                    any(~finiteWorking(dem.BaseValidMask)) || ...
                    any(isfinite(dem.HaeHeightsMeters(~dem.BaseValidMask)))
                error("ProjectionDemGrid:invalidGrid", ...
                    "DEM validity and finite normalized coordinates disagree.");
            end
            ProjectionDemGrid.validateAccuracy(dem.Accuracy);
            ProjectionDemGrid.validateTransforms(dem.Transforms, dem.WorldFrame);
            ProjectionDemGrid.localSurface(dem, false);
        end

        function surface = localSurface(dem, ignoreExclusions)
            %localSurface Return monotonic ENU axes and oriented surface grids.
            if nargin < 2
                ignoreExclusions = false;
            end
            eastAxis = median(dem.EnuEastMeters, 1, "omitnan");
            northAxis = median(dem.EnuNorthMeters, 2, "omitnan").';
            up = dem.EnuUpMeters;
            valid = dem.ValidMask;
            if ignoreExclusions
                valid = dem.BaseValidMask;
            end
            if all(diff(eastAxis) < 0)
                eastAxis = fliplr(eastAxis);
                up = fliplr(up);
                valid = fliplr(valid);
            end
            if all(diff(northAxis) < 0)
                northAxis = fliplr(northAxis);
                up = flipud(up);
                valid = flipud(valid);
            end
            if any(diff(eastAxis) <= 0) || any(diff(northAxis) <= 0)
                error("ProjectionDemGrid:nonmonotonicGrid", ...
                    "DEM rows/columns must define monotonic local ENU axes.");
            end
            up(~valid) = NaN;
            surface = struct(EastAxisMeters=eastAxis, ...
                NorthAxisMeters=northAxis, UpMeters=up, ValidMask=valid);
        end

        function enu = worldToEnu(dem, world)
            %worldToEnu Convert project-world 3xN coordinates to scene ENU.
            dem = ProjectionDemGrid.validate(dem);
            world = ProjectionDemGrid.coordinates(world, "world");
            enu = dem.Transforms.EnuToProjectWorldRotation.' * ...
                (world - dem.Transforms.ProjectWorldOriginMeters);
        end

        function world = enuToWorld(dem, enu)
            %enuToWorld Convert scene ENU 3xN coordinates to project world.
            dem = ProjectionDemGrid.validate(dem);
            enu = ProjectionDemGrid.coordinates(enu, "ENU");
            world = dem.Transforms.ProjectWorldOriginMeters + ...
                dem.Transforms.EnuToProjectWorldRotation * enu;
        end

        function geodetic = worldToGeodetic(dem, world)
            %worldToGeodetic Return [latitude;longitude;HAE] for world points.
            enu = ProjectionDemGrid.worldToEnu(dem, world);
            ecef = dem.Transforms.OriginEcefMeters + ...
                dem.Transforms.EcefToEnuRotation.' * enu;
            ellipsoid = wgs84Ellipsoid("meter");
            [latitude, longitude, hae] = ecef2geodetic( ...
                ellipsoid, ecef(1, :), ecef(2, :), ecef(3, :));
            geodetic = [latitude; longitude; hae];
        end

        function world = geodeticToWorld(dem, geodetic)
            %geodeticToWorld Convert [latitude;longitude;HAE] to project world.
            dem = ProjectionDemGrid.validate(dem);
            geodetic = ProjectionDemGrid.coordinates(geodetic, "geodetic");
            ellipsoid = wgs84Ellipsoid("meter");
            [x, y, z] = geodetic2ecef(ellipsoid, geodetic(1, :), ...
                geodetic(2, :), geodetic(3, :));
            ecef = [x; y; z];
            enu = dem.Transforms.EcefToEnuRotation * ...
                (ecef - dem.Transforms.OriginEcefMeters);
            world = ProjectionDemGrid.enuToWorld(dem, enu);
        end
    end

    methods (Static, Access = private)
        function [latitude, longitude, heights] = inputGrid( ...
                latitude, longitude, heights)
            if ~isnumeric(heights) || isempty(heights) || ~ismatrix(heights)
                error("ProjectionDemGrid:invalidGrid", ...
                    "HeightsMeters must be one nonempty numeric grid.");
            end
            if isvector(latitude) && isvector(longitude) && ...
                    numel(latitude) == size(heights, 1) && ...
                    numel(longitude) == size(heights, 2)
                [longitude, latitude] = meshgrid( ...
                    double(longitude), double(latitude));
            end
            if ~isnumeric(latitude) || ~isnumeric(longitude) || ...
                    ~isequal(size(latitude), size(longitude), size(heights)) || ...
                    any(latitude(isfinite(latitude)) < -90) || ...
                    any(latitude(isfinite(latitude)) > 90) || ...
                    any(longitude(isfinite(longitude)) < -180) || ...
                    any(longitude(isfinite(longitude)) > 180)
                error("ProjectionDemGrid:invalidGrid", ...
                    "Latitude, longitude, and heights must be compatible WGS84 grids.");
            end
            latitude = double(latitude);
            longitude = double(longitude);
            heights = double(heights);
        end

        function [reference, model, assumption] = datum( ...
                reference, model, datasetKind)
            reference = upper(string(reference));
            model = upper(string(model));
            assumption = "none";
            if strlength(reference) == 0
                if datasetKind ~= "DTED2"
                    error("ProjectionDemGrid:missingHeightReference", ...
                        "Non-DTED grids must declare HAE or MSL heights.");
                end
                reference = "MSL";
                model = "EGM96";
                assumption = "omittedDtedReferenceAssumedMslEgm96";
            end
            reference = ProjectionDemGrid.enumValue( ...
                reference, ["HAE" "MSL"], "HeightReference");
            if reference == "HAE"
                if strlength(model) == 0
                    model = "NONE";
                elseif model ~= "NONE"
                    error("ProjectionDemGrid:invalidDatum", ...
                        "HAE input must not declare an orthometric geoid model.");
                end
            else
                if strlength(model) == 0
                    model = "EGM96";
                    assumption = "mslGeoidOmittedAssumedEgm96";
                elseif model ~= "EGM96"
                    error("ProjectionDemGrid:unsupportedGeoid", ...
                        "Initial MSL ingestion supports explicit EGM96 only.");
                end
            end
        end

        function value = noDataValue(value)
            if isempty(value)
                value = [];
                return
            end
            if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ...
                    ~isfinite(value)
                error("ProjectionDemGrid:invalidNoData", ...
                    "NoDataValue must be empty or one finite numeric scalar.");
            end
            value = double(value);
        end

        function value = mask(value, shape, defaultValue)
            if isempty(value)
                value = repmat(logical(defaultValue), shape);
            elseif ~islogical(value) || ~isequal(size(value), shape)
                error("ProjectionDemGrid:invalidMask", ...
                    "DEM masks must be logical arrays matching HeightsMeters.");
            end
        end

        function frame = sceneFrame(value, latitude, longitude, hae, valid)
            defaults = struct(WorldFrame="sceneWorld", ...
                OriginGeodeticDegreesMeters=[median(latitude(valid)) ...
                median(longitude(valid)) median(hae(valid))], ...
                EnuToProjectWorldRotation=eye(3), ...
                ProjectWorldOriginMeters=zeros(3, 1));
            if isempty(value)
                value = struct();
            end
            if ~isstruct(value) || ~isscalar(value)
                error("ProjectionDemGrid:invalidFrame", ...
                    "SceneFrame must be a scalar struct.");
            end
            names = string(fieldnames(value));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDemGrid:invalidFrame", ...
                    "Unexpected SceneFrame field: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = value.(name);
            end
            frame = defaults;
            frame.WorldFrame = string(frame.WorldFrame);
            frame.OriginGeodeticDegreesMeters = reshape( ...
                double(frame.OriginGeodeticDegreesMeters), 1, []);
            frame.ProjectWorldOriginMeters = reshape( ...
                double(frame.ProjectWorldOriginMeters), 3, 1);
            rotation = double(frame.EnuToProjectWorldRotation);
            if ~isscalar(frame.WorldFrame) || strlength(frame.WorldFrame) == 0 || ...
                    numel(frame.OriginGeodeticDegreesMeters) ~= 3 || ...
                    any(~isfinite(frame.OriginGeodeticDegreesMeters)) || ...
                    ~isequal(size(rotation), [3 3]) || ...
                    any(~isfinite(rotation), "all") || ...
                    norm(rotation.' * rotation - eye(3), "fro") > 1e-10 || ...
                    abs(det(rotation) - 1) > 1e-10 || ...
                    any(~isfinite(frame.ProjectWorldOriginMeters))
                error("ProjectionDemGrid:invalidFrame", ...
                    "SceneFrame requires a proper ENU/world transform and HAE origin.");
            end
            frame.EnuToProjectWorldRotation = rotation;
        end

        function [east, north, up, worldX, worldY, worldZ, transforms] = ...
                transformGrid(latitude, longitude, hae, valid, frame)
            ellipsoid = wgs84Ellipsoid("meter");
            origin = frame.OriginGeodeticDegreesMeters;
            [originX, originY, originZ] = geodetic2ecef( ...
                ellipsoid, origin(1), origin(2), origin(3));
            originEcef = [originX; originY; originZ];
            latitudeRadians = deg2rad(origin(1));
            longitudeRadians = deg2rad(origin(2));
            rotation = [-sin(longitudeRadians) cos(longitudeRadians) 0; ...
                -sin(latitudeRadians) * cos(longitudeRadians) ...
                -sin(latitudeRadians) * sin(longitudeRadians) ...
                cos(latitudeRadians); ...
                cos(latitudeRadians) * cos(longitudeRadians) ...
                cos(latitudeRadians) * sin(longitudeRadians) ...
                sin(latitudeRadians)];
            east = nan(size(hae));
            north = nan(size(hae));
            up = nan(size(hae));
            [x, y, z] = geodetic2ecef(ellipsoid, latitude(valid), ...
                longitude(valid), hae(valid));
            enu = rotation * ([x.'; y.'; z.'] - originEcef);
            east(valid) = enu(1, :);
            north(valid) = enu(2, :);
            up(valid) = enu(3, :);
            world = frame.ProjectWorldOriginMeters + ...
                frame.EnuToProjectWorldRotation * enu;
            worldX = nan(size(hae));
            worldY = nan(size(hae));
            worldZ = nan(size(hae));
            worldX(valid) = world(1, :);
            worldY(valid) = world(2, :);
            worldZ(valid) = world(3, :);
            transforms = struct(GeodeticFrame="WGS84", ...
                HeightFrame="HAE", EcefFrame="WGS84-ECEF", ...
                EnuFrame="sceneLocalENU", WorldFrame=frame.WorldFrame, ...
                OriginGeodeticDegreesMeters=origin, ...
                OriginEcefMeters=originEcef, ...
                EcefToEnuRotation=rotation, ...
                EnuToProjectWorldRotation= ...
                frame.EnuToProjectWorldRotation, ...
                ProjectWorldOriginMeters=frame.ProjectWorldOriginMeters, ...
                Reversible=true);
        end

        function accuracy = accuracy(caller, dataset, datasetKind)
            caller = ProjectionDemGrid.accuracyInput(caller, "caller");
            dataset = ProjectionDemGrid.accuracyInput(dataset, "dataset");
            if caller.Available
                selected = caller;
            elseif dataset.Available
                selected = dataset;
            elseif datasetKind == "DTED2"
                selected = struct(Available=true, CE90Meters=23, ...
                    LE90Meters=18, Source="dted2Default");
            else
                selected = struct(Available=false, CE90Meters=NaN, ...
                    LE90Meters=NaN, Source="unavailable");
            end
            horizontalSigma = NaN;
            verticalSigma = NaN;
            if selected.Available
                horizontalSigma = selected.CE90Meters / sqrt(-2 * log(0.1));
                verticalSigma = selected.LE90Meters / 1.64485362695147;
            end
            accuracy = struct(Available=selected.Available, ...
                CE90Meters=selected.CE90Meters, ...
                LE90Meters=selected.LE90Meters, Source=selected.Source, ...
                HorizontalSigmaMeters=horizontalSigma, ...
                VerticalSigmaMeters=verticalSigma, ...
                DistributionAssumption= ...
                "zeroMeanGaussian; CE90 isotropic 2D Rayleigh; LE90 twoSidedNormal", ...
                CellCorrelationAssumption= ...
                "datasetAccuracySharedAcrossCellsNotIndependent");
        end

        function value = accuracyInput(value, source)
            if isempty(value) || (isstruct(value) && isscalar(value) && ...
                    isempty(fieldnames(value)))
                value = struct(Available=false, CE90Meters=NaN, ...
                    LE90Meters=NaN, Source=string(source));
                return
            end
            if ~isstruct(value) || ~isscalar(value) || ...
                    any(~isfield(value, ["CE90Meters" "LE90Meters"])) || ...
                    ~isnumeric(value.CE90Meters) || ...
                    ~isscalar(value.CE90Meters) || ...
                    ~isfinite(value.CE90Meters) || value.CE90Meters <= 0 || ...
                    ~isnumeric(value.LE90Meters) || ...
                    ~isscalar(value.LE90Meters) || ...
                    ~isfinite(value.LE90Meters) || value.LE90Meters <= 0
                error("ProjectionDemGrid:invalidAccuracy", ...
                    "%s accuracy requires positive CE90Meters and LE90Meters.", ...
                    source);
            end
            value = struct(Available=true, ...
                CE90Meters=double(value.CE90Meters), ...
                LE90Meters=double(value.LE90Meters), Source=string(source));
        end

        function validateAccuracy(value)
            required = ["Available" "CE90Meters" "LE90Meters" "Source" ...
                "HorizontalSigmaMeters" "VerticalSigmaMeters" ...
                "DistributionAssumption" "CellCorrelationAssumption"];
            if ~isstruct(value) || ~isscalar(value) || ...
                    any(~isfield(value, required)) || ...
                    ~islogical(value.Available) || ~isscalar(value.Available)
                error("ProjectionDemGrid:invalidAccuracy", ...
                    "Normalized DEM accuracy is malformed.");
            end
            if value.Available && (any(~isfinite([value.CE90Meters ...
                    value.LE90Meters value.HorizontalSigmaMeters ...
                    value.VerticalSigmaMeters])) || ...
                    any([value.CE90Meters value.LE90Meters ...
                    value.HorizontalSigmaMeters value.VerticalSigmaMeters] <= 0))
                error("ProjectionDemGrid:invalidAccuracy", ...
                    "Available DEM accuracy must contain positive metrics.");
            end
        end

        function validateTransforms(value, worldFrame)
            required = ["GeodeticFrame" "HeightFrame" "EcefFrame" ...
                "EnuFrame" "WorldFrame" "OriginGeodeticDegreesMeters" ...
                "OriginEcefMeters" "EcefToEnuRotation" ...
                "EnuToProjectWorldRotation" "ProjectWorldOriginMeters" ...
                "Reversible"];
            if ~isstruct(value) || ~isscalar(value) || ...
                    any(~isfield(value, required))
                error("ProjectionDemGrid:invalidFrame", ...
                    "Normalized DEM transforms must be reversible WGS84/ENU values.");
            end
            rotations = [value.EcefToEnuRotation; ...
                value.EnuToProjectWorldRotation];
            if string(value.WorldFrame) ~= string(worldFrame) || ...
                    string(value.GeodeticFrame) ~= "WGS84" || ...
                    string(value.HeightFrame) ~= "HAE" || ...
                    ~isequal(size(value.EcefToEnuRotation), [3 3]) || ...
                    ~isequal(size(value.EnuToProjectWorldRotation), [3 3]) || ...
                    any(~isfinite(rotations), "all") || ...
                    norm(value.EcefToEnuRotation * ...
                    value.EcefToEnuRotation.' - eye(3), "fro") > 1e-10 || ...
                    norm(value.EnuToProjectWorldRotation.' * ...
                    value.EnuToProjectWorldRotation - eye(3), "fro") > 1e-10 || ...
                    ~isequal(value.Reversible, true)
                error("ProjectionDemGrid:invalidFrame", ...
                    "Normalized DEM transforms must be reversible WGS84/ENU values.");
            end
        end

        function value = coordinates(value, name)
            if ~isnumeric(value) || size(value, 1) ~= 3 || ...
                    any(~isfinite(value), "all")
                error("ProjectionDemGrid:invalidCoordinates", ...
                    "%s coordinates must be finite double 3xN values.", name);
            end
            value = double(value);
        end

        function value = enumValue(value, choices, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || ~ismember(value, choices)
                error("ProjectionDemGrid:invalidInput", ...
                    "%s is unsupported.", name);
            end
        end

        function tf = hasRuntimeValue(value)
            if isa(value, "function_handle") || ...
                    (isobject(value) && isa(value, "handle")) || isjava(value)
                tf = true;
            elseif isstruct(value)
                tf = false;
                names = fieldnames(value);
                for element = 1:numel(value)
                    for index = 1:numel(names)
                        if ProjectionDemGrid.hasRuntimeValue( ...
                                value(element).(names{index}))
                            tf = true;
                            return
                        end
                    end
                end
            elseif iscell(value)
                tf = false;
                for index = 1:numel(value)
                    if ProjectionDemGrid.hasRuntimeValue(value{index})
                        tf = true;
                        return
                    end
                end
            else
                tf = false;
            end
        end
    end
end
