classdef ProjectionDenseSurfaceSyntheticTruth
    %ProjectionDenseSurfaceSyntheticTruth Compact terrain, motion, and ray truth.

    properties (Constant)
        Format = "ProjectionDenseSurfaceSyntheticTruth"
        Version = 1
        VisibilityStatuses = ["visibleTerrain" "terrainOcclusion" ...
            "textureCoverageFailure" "invalidGeometry"]
    end

    methods (Static)
        function truth = create(config, plan)
            %create Build compact on-demand truth without full per-pixel XYZ arrays.
            config = ProjectionDenseSurfaceSyntheticConfig.validate(config);
            ProjectionDenseSurfaceSyntheticTruth.validatePlan(plan);
            terrain = ProjectionDenseSurfaceSyntheticTerrain.create(config, plan);
            trajectory = ProjectionDenseSurfaceSyntheticTruth.createTrajectory( ...
                config, plan);
            views = repmat(ProjectionDenseSurfaceSyntheticTruth.emptyView(), ...
                1, config.image.view_count);
            for viewIndex = 1:config.image.view_count
                planView = plan.Views(viewIndex);
                views(viewIndex) = struct(Index=viewIndex, ...
                    SourceBand=config.image.source_band_sequence(viewIndex), ...
                    CenterTimeSeconds=planView.CenterTimeSeconds, ...
                    RollDegrees=planView.RollDegrees, ...
                    PitchStartDegrees=planView.PitchStartDegrees, ...
                    PitchCenterDegrees=planView.PitchCenterDegrees, ...
                    PitchEndDegrees=planView.PitchEndDegrees);
            end
            origins = reshape([plan.Views.PlatformCenter], 3, []);
            occlusionAudit = ...
                ProjectionDenseSurfaceSyntheticTerrain.auditOcclusion( ...
                terrain, origins);
            if config.terrain.require_occlusion && ~occlusionAudit.Passed
                error("ProjectionDenseSurfaceSyntheticTruth:requiredOcclusionMissing", ...
                    "Terrain design did not produce required view-dependent occlusion.");
            end
            truth = struct(Format=ProjectionDenseSurfaceSyntheticTruth.Format, ...
                Version=ProjectionDenseSurfaceSyntheticTruth.Version, ...
                ImageSize=[config.image.rows config.image.columns], ...
                LineRateLinesPerSecond=config.image.scan_rate_lines_per_second, ...
                CrossTrackFovDegrees=config.image.cross_track_fov_degrees, ...
                Terrain=terrain, Trajectory=trajectory, Views=views, ...
                VisibilityStatuses= ...
                ProjectionDenseSurfaceSyntheticTruth.VisibilityStatuses, ...
                OcclusionAudit=occlusionAudit, CompactOnDemand=true, ...
                ContainsPerPixelXyz=false);
        end

        function state = sampleTrajectory(truth, times)
            %sampleTrajectory Sample continuous truth position, velocity, and attitude.
            ProjectionDenseSurfaceSyntheticTruth.validateTruth(truth);
            times = ProjectionDenseSurfaceSyntheticTruth.validateTimes( ...
                times, truth.Trajectory.KnotTimesSeconds);
            trajectory = truth.Trajectory;
            positionPerturbation = interp1(trajectory.KnotTimesSeconds, ...
                trajectory.PositionPerturbationMeters.', times, "pchip").';
            attitude = interp1(trajectory.KnotTimesSeconds, ...
                trajectory.AttitudePerturbationDegrees.', times, "pchip").';
            nominalPosition = [trajectory.NominalVelocityMetersPerSecond * times; ...
                zeros(1, numel(times)); ...
                trajectory.HeightMeters * ones(1, numel(times))];
            position = nominalPosition + positionPerturbation;

            derivativeStep = max(1e-6, ...
                trajectory.CorrelationTimeSeconds * 1e-4);
            lowerTimes = max(times - derivativeStep, ...
                trajectory.KnotTimesSeconds(1));
            upperTimes = min(times + derivativeStep, ...
                trajectory.KnotTimesSeconds(end));
            lowerPosition = interp1(trajectory.KnotTimesSeconds, ...
                trajectory.PositionPerturbationMeters.', lowerTimes, "pchip").';
            upperPosition = interp1(trajectory.KnotTimesSeconds, ...
                trajectory.PositionPerturbationMeters.', upperTimes, "pchip").';
            velocityPerturbation = (upperPosition - lowerPosition) ./ ...
                (upperTimes - lowerTimes);
            velocity = velocityPerturbation + ...
                repmat([trajectory.NominalVelocityMetersPerSecond; 0; 0], ...
                1, numel(times));
            state = struct(TimeSeconds=times, Position=position, ...
                Velocity=velocity, AttitudeDegrees=attitude);
        end

        function [origins, vectors, times] = sampleRays( ...
                truth, viewIndex, rowPositions, columnPositions)
            %sampleRays Sample paired continuous image observations from truth.
            ProjectionDenseSurfaceSyntheticTruth.validateTruth(truth);
            viewIndex = ProjectionDenseSurfaceSyntheticTruth.validateViewIndex( ...
                viewIndex, numel(truth.Views));
            [rowPositions, columnPositions] = ...
                ProjectionDenseSurfaceSyntheticTruth.validateObservations( ...
                rowPositions, columnPositions, truth.ImageSize);
            view = truth.Views(viewIndex);
            centerColumn = 0.5 * (truth.ImageSize(2) + 1);
            times = view.CenterTimeSeconds + ...
                (columnPositions - centerColumn) / truth.LineRateLinesPerSecond;
            state = ProjectionDenseSurfaceSyntheticTruth.sampleTrajectory(truth, times);
            origins = state.Position;
            rowIfov = truth.CrossTrackFovDegrees / (truth.ImageSize(1) - 1);
            centerRow = 0.5 * (truth.ImageSize(1) + 1);
            detectorOffsets = (rowPositions - centerRow) * rowIfov;
            columnFractions = (columnPositions - 1) / (truth.ImageSize(2) - 1);
            pitchDegrees = view.PitchStartDegrees + columnFractions * ...
                (view.PitchEndDegrees - view.PitchStartDegrees);
            vectors = zeros(3, numel(times));
            bodyToWorld = ...
                ProjectionDenseSurfaceSyntheticPlanner.bodyToWorldMatrix();
            for sampleIndex = 1:numel(times)
                gimbal = ProjectionDenseSurfaceSyntheticPlanner.gimbalRotation( ...
                    view.RollDegrees + detectorOffsets(sampleIndex), ...
                    pitchDegrees(sampleIndex));
                turbulence = ...
                    ProjectionDenseSurfaceSyntheticTruth.attitudeRotation( ...
                    state.AttitudeDegrees(:, sampleIndex));
                vector = bodyToWorld * turbulence * gimbal * [0; 0; 1];
                vectors(:, sampleIndex) = vector / norm(vector);
            end
        end

        function [origins, vectors] = sampleGridRays( ...
                truth, viewIndex, rowIndices, columnIndices)
            %sampleGridRays Sample independent row/column posts for SampleFcn use.
            ProjectionDenseSurfaceSyntheticTruth.validateTruth(truth);
            viewIndex = ProjectionDenseSurfaceSyntheticTruth.validateViewIndex( ...
                viewIndex, numel(truth.Views));
            rowIndices = ProjectionDenseSurfaceSyntheticTruth.validateGridIndices( ...
                rowIndices, truth.ImageSize(1), "rowIndices");
            columnIndices = ProjectionDenseSurfaceSyntheticTruth.validateGridIndices( ...
                columnIndices, truth.ImageSize(2), "columnIndices");
            view = truth.Views(viewIndex);
            centerColumn = 0.5 * (truth.ImageSize(2) + 1);
            times = view.CenterTimeSeconds + ...
                (columnIndices - centerColumn) / truth.LineRateLinesPerSecond;
            state = ProjectionDenseSurfaceSyntheticTruth.sampleTrajectory(truth, times);
            origins = state.Position;

            centerRow = 0.5 * (truth.ImageSize(1) + 1);
            rowIfov = truth.CrossTrackFovDegrees / (truth.ImageSize(1) - 1);
            detectorRoll = deg2rad(view.RollDegrees + ...
                (rowIndices(:) - centerRow) * rowIfov);
            columnFraction = (columnIndices - 1) / (truth.ImageSize(2) - 1);
            gimbalPitch = deg2rad(view.PitchStartDegrees + columnFraction * ...
                (view.PitchEndDegrees - view.PitchStartDegrees));
            sinPitch = sin(gimbalPitch);
            cosPitch = cos(gimbalPitch);
            xBody = repmat(sinPitch, numel(rowIndices), 1);
            yBody = -sin(detectorRoll) * cosPitch;
            zBody = cos(detectorRoll) * cosPitch;
            transform = ProjectionDenseSurfaceSyntheticTruth. ...
                bodyToWorldCoefficients(state.AttitudeDegrees);
            worldX = xBody .* transform.R11 + yBody .* transform.R12 + ...
                zBody .* transform.R13;
            worldY = xBody .* transform.R21 + yBody .* transform.R22 + ...
                zBody .* transform.R23;
            worldZ = xBody .* transform.R31 + yBody .* transform.R32 + ...
                zBody .* transform.R33;
            vectors = reshape(cat(3, worldX, worldY, worldZ), ...
                numel(rowIndices), numel(columnIndices), 3);
            vectors = permute(vectors, [3 1 2]);
            vectors = vectors ./ sqrt(sum(vectors.^2, 1));
        end

        function [points, status, ranges] = intersectObservations( ...
                truth, viewIndex, rowPositions, columnPositions)
            %intersectObservations Sample truth rays and first terrain hits.
            [origins, vectors] = ProjectionDenseSurfaceSyntheticTruth.sampleRays( ...
                truth, viewIndex, rowPositions, columnPositions);
            [points, status, ranges] = ...
                ProjectionDenseSurfaceSyntheticTerrain.intersectRays( ...
                truth.Terrain, origins, vectors);
        end

        function metadata = sceneMetadata(truth)
            %sceneMetadata Return viewer-safe metadata with no truth payload.
            ProjectionDenseSurfaceSyntheticTruth.validateTruth(truth);
            metadata = struct(Format="ProjectionDenseSurfaceSyntheticScene", ...
                Version=1, ViewCount=numel(truth.Views), ...
                ImageSize=truth.ImageSize, SourceBands=[truth.Views.SourceBand], ...
                TruthIncluded=false, GeometryRole="reported-only");
        end
    end

    methods (Static, Access = private)
        function trajectory = createTrajectory(config, plan)
            sampleSpan = plan.SampleSpanSeconds;
            startTime = min([plan.Views.CenterTimeSeconds]) - 0.5 * sampleSpan;
            endTime = max([plan.Views.CenterTimeSeconds]) + 0.5 * sampleSpan;
            correlation = config.truth_turbulence.correlation_time_seconds;
            knotStep = correlation / 4;
            knotTimes = (floor(startTime / knotStep) - 1: ...
                ceil(endTime / knotStep) + 1) * knotStep;
            stream = RandStream("mt19937ar", Seed=config.fixture.random_seed);
            position = ProjectionDenseSurfaceSyntheticTruth.gaussMarkovKnots( ...
                stream, 3, numel(knotTimes), knotStep, correlation, ...
                config.truth_turbulence.position_rms_meters_per_axis);
            attitude = ProjectionDenseSurfaceSyntheticTruth.gaussMarkovKnots( ...
                stream, 3, numel(knotTimes), knotStep, correlation, ...
                config.truth_turbulence.attitude_rms_degrees_per_axis);
            trajectory = struct(Model=config.truth_turbulence.model, ...
                KnotTimesSeconds=knotTimes, ...
                PositionPerturbationMeters=position, ...
                AttitudePerturbationDegrees=attitude, ...
                NominalVelocityMetersPerSecond= ...
                config.platform.forward_velocity_meters_per_second, ...
                HeightMeters=config.platform.height_above_ground_meters, ...
                CorrelationTimeSeconds=correlation, ...
                SeedScope="fixture-local-stream");
        end

        function values = gaussMarkovKnots( ...
                stream, componentCount, knotCount, step, correlation, sigma)
            values = zeros(componentCount, knotCount);
            if sigma == 0
                return
            end
            coefficient = exp(-step / correlation);
            innovationSigma = sigma * sqrt(1 - coefficient^2);
            values(:, 1) = sigma * randn(stream, componentCount, 1);
            for knotIndex = 2:knotCount
                values(:, knotIndex) = coefficient * values(:, knotIndex - 1) + ...
                    innovationSigma * randn(stream, componentCount, 1);
            end
            values = values - mean(values, 2);
            actualRms = sqrt(mean(values.^2, 2));
            values = values .* (sigma ./ max(actualRms, eps));
        end

        function rotation = attitudeRotation(attitudeDegrees)
            roll = deg2rad(attitudeDegrees(1));
            pitch = deg2rad(attitudeDegrees(2));
            yaw = deg2rad(attitudeDegrees(3));
            rollRotation = [1 0 0; 0 cos(roll) -sin(roll); ...
                0 sin(roll) cos(roll)];
            pitchRotation = [cos(pitch) 0 sin(pitch); 0 1 0; ...
                -sin(pitch) 0 cos(pitch)];
            yawRotation = [cos(yaw) -sin(yaw) 0; ...
                sin(yaw) cos(yaw) 0; 0 0 1];
            rotation = yawRotation * pitchRotation * rollRotation;
        end

        function transform = bodyToWorldCoefficients(attitudeDegrees)
            roll = deg2rad(attitudeDegrees(1, :));
            pitch = deg2rad(attitudeDegrees(2, :));
            yaw = deg2rad(attitudeDegrees(3, :));
            sinRoll = sin(roll);
            cosRoll = cos(roll);
            sinPitch = sin(pitch);
            cosPitch = cos(pitch);
            sinYaw = sin(yaw);
            cosYaw = cos(yaw);
            transform = struct( ...
                R11=cosYaw .* cosPitch, ...
                R12=cosYaw .* sinPitch .* sinRoll - sinYaw .* cosRoll, ...
                R13=cosYaw .* sinPitch .* cosRoll + sinYaw .* sinRoll, ...
                R21=sinYaw .* cosPitch, ...
                R22=sinYaw .* sinPitch .* sinRoll + cosYaw .* cosRoll, ...
                R23=sinYaw .* sinPitch .* cosRoll - cosYaw .* sinRoll, ...
                R31=sinPitch, R32=-cosPitch .* sinRoll, ...
                R33=-cosPitch .* cosRoll);
        end

        function times = validateTimes(times, knotTimes)
            if ~isnumeric(times) || isempty(times) || ~isvector(times) || ...
                    any(~isfinite(times)) || any(times < knotTimes(1)) || ...
                    any(times > knotTimes(end))
                error("ProjectionDenseSurfaceSyntheticTruth:invalidTimes", ...
                    "Truth times must be finite and lie within the sortie timeline.");
            end
            times = double(times(:).');
        end

        function [rows, columns] = validateObservations(rows, columns, imageSize)
            rows = ProjectionDenseSurfaceSyntheticTruth.validatePositions( ...
                rows, imageSize(1), "rowPositions");
            columns = ProjectionDenseSurfaceSyntheticTruth.validatePositions( ...
                columns, imageSize(2), "columnPositions");
            if isscalar(rows)
                rows = repmat(rows, size(columns));
            elseif isscalar(columns)
                columns = repmat(columns, size(rows));
            elseif numel(rows) ~= numel(columns)
                error("ProjectionDenseSurfaceSyntheticTruth:invalidObservations", ...
                    "Row and column observation counts must match or be scalar.");
            end
        end

        function values = validatePositions(values, maximum, name)
            if ~isnumeric(values) || isempty(values) || ~isvector(values) || ...
                    any(~isfinite(values)) || any(values < 1) || ...
                    any(values > maximum)
                error("ProjectionDenseSurfaceSyntheticTruth:invalidObservations", ...
                    "%s must contain finite in-bounds image positions.", name);
            end
            values = double(values(:).');
        end

        function values = validateGridIndices(values, maximum, name)
            values = ProjectionDenseSurfaceSyntheticTruth.validatePositions( ...
                values, maximum, name);
            if any(fix(values) ~= values)
                error("ProjectionDenseSurfaceSyntheticTruth:invalidObservations", ...
                    "%s must contain integer image indices.", name);
            end
        end

        function index = validateViewIndex(index, viewCount)
            if ~isnumeric(index) || ~isscalar(index) || ~isfinite(index) || ...
                    fix(index) ~= index || index < 1 || index > viewCount
                error("ProjectionDenseSurfaceSyntheticTruth:invalidViewIndex", ...
                    "View index must select one truth collection.");
            end
            index = double(index);
        end

        function validatePlan(plan)
            if ~isstruct(plan) || ~isscalar(plan) || ...
                    ~isfield(plan, "Format") || ...
                    string(plan.Format) ~= ProjectionDenseSurfaceSyntheticPlanner.Format || ...
                    ~isfield(plan, "Feasible") || ~plan.Feasible || ...
                    ~isfield(plan, "Views")
                error("ProjectionDenseSurfaceSyntheticTruth:invalidPlan", ...
                    "Truth creation requires a feasible synthetic collection plan.");
            end
        end

        function validateTruth(truth)
            required = ["Format" "ImageSize" "LineRateLinesPerSecond" ...
                "CrossTrackFovDegrees" "Terrain" "Trajectory" "Views" ...
                "VisibilityStatuses" "CompactOnDemand" "ContainsPerPixelXyz"];
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    ~all(isfield(truth, required)) || ...
                    string(truth.Format) ~= ProjectionDenseSurfaceSyntheticTruth.Format
                error("ProjectionDenseSurfaceSyntheticTruth:invalidTruth", ...
                    "Truth must come from create.");
            end
        end

        function view = emptyView()
            view = struct(Index=0, SourceBand=0, CenterTimeSeconds=0, ...
                RollDegrees=0, PitchStartDegrees=0, PitchCenterDegrees=0, ...
                PitchEndDegrees=0);
        end
    end
end
