classdef ProjectionMultiRayReconstructor
    %ProjectionMultiRayReconstructor Robustly solve dense multi-view tracks.

    properties (Constant)
        Format = "ProjectionMultiRayPointSet"
        Version = 1
    end

    methods (Static)
        function options = defaults()
            %defaults Return deterministic robust multi-ray options.
            options = struct(HuberScaleMeters=0.25, ...
                MaximumResidualMeters=1, MaximumIterations=25, ...
                ConvergenceToleranceMeters=1e-9, ...
                MaximumConditionNumber=1e8, ...
                ResidualSigmaFloorMeters=0.01);
        end

        function result = reconstruct(association, options)
            %reconstruct Solve an authoritative point for every dense track.
            if nargin < 2
                options = struct();
            end
            association = ProjectionMultiRayReconstructor. ...
                validateAssociation(association);
            options = ProjectionMultiRayReconstructor.validateOptions(options);
            tracks = association.Tracks;
            points = repmat(ProjectionMultiRayReconstructor.emptyPoint(), ...
                1, numel(tracks));
            for index = 1:numel(tracks)
                points(index) = ProjectionMultiRayReconstructor.solveTrack( ...
                    association, tracks(index), options);
            end
            generationPayload = struct( ...
                AssociationGenerationId=association.GenerationId, ...
                Options=options, PointIds=string({points.PointId}), ...
                PointStates=string({points.State}), ...
                AcceptedViewCounts=[points.IndependentViewCount]);
            generationId = "multi-ray-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(generationPayload), 17);
            result = struct(Format=ProjectionMultiRayReconstructor.Format, ...
                Version=ProjectionMultiRayReconstructor.Version, ...
                Status="complete", Stage="robustMultiView", ...
                AuthoritativeProduct="provenanceRichPointSet", ...
                WorldFrame=association.WorldFrame, ...
                CovarianceUnits="metersSquared", ...
                GenerationId=generationId, ...
                AssociationGenerationId=association.GenerationId, ...
                Options=options, Points=points, ...
                RawPairwiseRecords=association.RawPairwiseRecords, ...
                AssociationTracks=association.Tracks, ...
                DerivedProducts=struct(Voxel=[], Mesh=[], Grid=[]), ...
                Provenance=struct( ...
                PairwiseStage="rawPairwise", ...
                AuthoritativeStage="robustMultiView", ...
                EvidenceWeightPolicy= ...
                "oneRayPerStableObservation;equalTotalWeightPerPass", ...
                PairwiseCovariancePolicy= ...
                "retainedAsPairProvenance;notRecountedAsIndependentEvidence"), ...
                Diagnostics=ProjectionMultiRayReconstructor.diagnostics(points));
        end

        function metadata = metadata(result)
            %metadata Return compact JSON-safe scientific-result metadata.
            result = ProjectionMultiRayReconstructor.validateResult(result);
            points = result.Points;
            summaries = repmat(struct(PointId="", TrackId="", ...
                State="", Valid=false, IndependentViewCount=0, ...
                IndependentPassCount=0, PairRecordCount=0, ...
                RobustResidualRmsMeters=NaN, ConditionNumber=Inf, ...
                CovarianceStatus="", CompetingMode=false), 1, numel(points));
            for index = 1:numel(points)
                point = points(index);
                summaries(index) = struct(PointId=point.PointId, ...
                    TrackId=point.TrackId, State=point.State, ...
                    Valid=point.Valid, ...
                    IndependentViewCount=point.IndependentViewCount, ...
                    IndependentPassCount=point.IndependentPassCount, ...
                    PairRecordCount=point.PairRecordCount, ...
                    RobustResidualRmsMeters=point.RobustResidualRmsMeters, ...
                    ConditionNumber=point.ConditionNumber, ...
                    CovarianceStatus=point.CovarianceStatus, ...
                    CompetingMode=point.CompetingMode);
            end
            metadata = struct(Format=result.Format, Version=result.Version, ...
                Status=result.Status, Stage=result.Stage, ...
                AuthoritativeProduct=result.AuthoritativeProduct, ...
                WorldFrame=result.WorldFrame, ...
                CovarianceUnits=result.CovarianceUnits, ...
                GenerationId=result.GenerationId, ...
                AssociationGenerationId=result.AssociationGenerationId, ...
                Diagnostics=result.Diagnostics, PointSummaries=summaries, ...
                Provenance=result.Provenance);
        end

        function paths = write(result, matPath, metadataPath)
            %write Persist full MAT data and compact JSON metadata.
            result = ProjectionMultiRayReconstructor.validateResult(result);
            matPath = ProjectionMultiRayReconstructor.filePath( ...
                matPath, ".mat", "matPath");
            metadataPath = ProjectionMultiRayReconstructor.filePath( ...
                metadataPath, ".json", "metadataPath");
            if matPath == metadataPath
                error("ProjectionMultiRayReconstructor:invalidPath", ...
                    "MAT and JSON paths must be distinct.");
            end
            pointSet = result;
            save(matPath, "pointSet", "-v7");
            metadata = ProjectionMultiRayReconstructor.metadata(result);
            fileId = fopen(metadataPath, "w");
            if fileId < 0
                error("ProjectionMultiRayReconstructor:writeFailed", ...
                    "Unable to open metadata path: %s.", metadataPath);
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(metadata, PrettyPrint=true));
            clear cleanup
            paths = struct(MatPath=matPath, MetadataPath=metadataPath);
        end
    end

    methods (Static, Access = private)
        function association = validateAssociation(association)
            if ~isstruct(association) || ~isscalar(association) || ...
                    any(~isfield(association, ["Format" "Version" ...
                    "WorldFrame" "GenerationId" "RawPairwiseRecords" ...
                    "Observations" "Tracks"]))
                error("ProjectionMultiRayReconstructor:invalidAssociation", ...
                    "A complete dense observation association is required.");
            end
            association.Format = string(association.Format);
            if ~isscalar(association.Format) || ...
                    ismissing(association.Format) || ...
                    association.Format ~= ...
                    ProjectionDenseObservationAssociator.Format || ...
                    ~isequal(association.Version, ...
                    ProjectionDenseObservationAssociator.Version)
                error("ProjectionMultiRayReconstructor:unsupportedAssociation", ...
                    "Dense observation association Format or Version is unsupported.");
            end
            if ~isstruct(association.RawPairwiseRecords) || ...
                    ~isstruct(association.Observations) || ...
                    ~isstruct(association.Tracks)
                error("ProjectionMultiRayReconstructor:invalidAssociation", ...
                    "Association records, observations, and tracks must be structs.");
            end
            association.WorldFrame = string(association.WorldFrame);
            association.GenerationId = string(association.GenerationId);
            if ~isscalar(association.WorldFrame) || ...
                    strlength(association.WorldFrame) == 0 || ...
                    ~isscalar(association.GenerationId) || ...
                    strlength(association.GenerationId) == 0
                error("ProjectionMultiRayReconstructor:invalidAssociation", ...
                    "Association frame and generation identity must be explicit.");
            end
            observationCount = numel(association.Observations);
            for track = association.Tracks
                if ~isfield(track, "ObservationIndices") || ...
                        numel(track.ObservationIndices) < 2 || ...
                        any(track.ObservationIndices < 1) || ...
                        any(track.ObservationIndices > observationCount) || ...
                        numel(unique(track.ObservationIndices)) ~= ...
                        numel(track.ObservationIndices)
                    error("ProjectionMultiRayReconstructor:invalidAssociation", ...
                        "Every track requires at least two unique valid observations.");
                end
            end
        end

        function options = validateOptions(options)
            defaults = ProjectionMultiRayReconstructor.defaults();
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionMultiRayReconstructor:invalidOptions", ...
                    "Multi-ray options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionMultiRayReconstructor:invalidOptions", ...
                    "Unknown multi-ray option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            positive = ["HuberScaleMeters" "MaximumResidualMeters" ...
                "ConvergenceToleranceMeters" "MaximumConditionNumber" ...
                "ResidualSigmaFloorMeters"];
            for name = positive
                value = defaults.(name);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value <= 0
                    error("ProjectionMultiRayReconstructor:invalidOptions", ...
                        "%s must be a finite positive scalar.", name);
                end
                defaults.(name) = double(value);
            end
            value = defaults.MaximumIterations;
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 1 || fix(value) ~= value
                error("ProjectionMultiRayReconstructor:invalidOptions", ...
                    "MaximumIterations must be a positive integer.");
            end
            defaults.MaximumIterations = double(value);
            options = defaults;
        end

        function pointRecord = solveTrack(association, track, options)
            observations = association.Observations(track.ObservationIndices);
            origins = horzcat(observations.RayOriginWorld);
            vectors = horzcat(observations.RayVectorWorld);
            directions = vectors ./ vecnorm(vectors, 2, 1);
            baseWeights = ProjectionMultiRayReconstructor.baseWeights(observations);
            [point, robustWeights] = ProjectionMultiRayReconstructor.irls( ...
                origins, directions, baseWeights, options);
            [residuals, parameters] = ...
                ProjectionMultiRayReconstructor.rayDiagnostics( ...
                point, origins, directions);
            accepted = residuals <= options.MaximumResidualMeters & ...
                parameters > 0 & isfinite(residuals) & isfinite(parameters);
            [point, accepted, residuals, parameters, condition, normal] = ...
                ProjectionMultiRayReconstructor.refineAccepted( ...
                origins, directions, baseWeights, accepted, options);
            valid = nnz(accepted) >= 2 && isfinite(condition) && ...
                condition <= options.MaximumConditionNumber && ...
                all(isfinite(point));
            state = "insufficientAcceptedRays";
            if nnz(accepted) >= 2 && condition > options.MaximumConditionNumber
                state = "weakGeometryRejected";
            elseif valid && nnz(accepted) == 2
                state = "twoViewRetained";
            elseif valid
                state = "multiViewSolved";
            end
            if ~valid
                point(:) = NaN;
            end
            rayRecords = ProjectionMultiRayReconstructor.rayRecords( ...
                observations, residuals, parameters, baseWeights, ...
                robustWeights, accepted);
            acceptedObservationKeys = string( ...
                {observations(accepted).ObservationKey});
            acceptedObservationIds = string( ...
                {observations(accepted).ObservationId});
            [contributingRecords, rejectedRecords] = ...
                ProjectionMultiRayReconstructor.partitionRecords( ...
                association.RawPairwiseRecords, track.RecordIds, ...
                acceptedObservationKeys);
            contributingPairIds = sort(unique(string( ...
                {contributingRecords.PairId})));
            rejectedPairIds = sort(unique(string({rejectedRecords.PairId})));
            acceptedPassIds = string({observations(accepted).PassId});
            acceptedViewIds = string({observations(accepted).ViewId});
            rejectedViewIds = string({observations(~accepted).ViewId});
            [radiometricConsistency, radiometricStatus] = ...
                ProjectionMultiRayReconstructor.radiometry( ...
                contributingRecords, observations(accepted));
            visibilityState = ProjectionMultiRayReconstructor.visibility( ...
                observations(accepted));
            [covariance, covarianceStatus, covarianceReason, axes] = ...
                ProjectionMultiRayReconstructor.covariance( ...
                normal, residuals(accepted), baseWeights(accepted), ...
                valid, options);
            angleRange = ProjectionMultiRayReconstructor.angleRange( ...
                directions(:, accepted));
            rmsResidual = NaN;
            if any(accepted)
                rmsResidual = sqrt(mean(residuals(accepted) .^ 2));
            end
            initialPoint = ProjectionMultiRayReconstructor. ...
                pairwiseInitialPoint(contributingRecords);
            pointPayload = struct(TrackId=track.TrackId, ...
                ModeId=track.ModeId, ObservationKeys=track.ObservationKeys);
            pointId = "point-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(pointPayload), 17);
            pointRecord = struct(PointId=pointId, TrackId=track.TrackId, ...
                ModeId=track.ModeId, CompetingMode=track.CompetingMode, ...
                Stage="robustMultiView", State=state, Valid=valid, ...
                PointWorld=point, ...
                PairwiseInitialOracleWorld=initialPoint, ...
                PairwiseInitialOracleLabel="pairwisePointMedianNotAuthoritative", ...
                ObservationKeys=string({observations.ObservationKey}), ...
                ObservationIds=string({observations.ObservationId}), ...
                ContributingObservationKeys=acceptedObservationKeys, ...
                ContributingObservationIds=acceptedObservationIds, ...
                ContributingViewIds=acceptedViewIds, ...
                RejectedViewIds=rejectedViewIds, ...
                ContributingPassIds=sort(unique(acceptedPassIds)), ...
                ContributingRecordIds=sort(string( ...
                {contributingRecords.RecordId})), ...
                RejectedRecordIds=sort(string({rejectedRecords.RecordId})), ...
                ContributingPairIds=contributingPairIds, ...
                RejectedPairIds=rejectedPairIds, ...
                IndependentViewCount=numel(unique(acceptedViewIds)), ...
                IndependentPassCount=numel(unique(acceptedPassIds)), ...
                PairRecordCount=track.PairRecordCount, ...
                RayDiagnostics=rayRecords, ...
                RobustResidualRmsMeters=rmsResidual, ...
                ConditionNumber=condition, ...
                IntersectionAngleRangeDegrees=angleRange, ...
                RadiometricConsistency=radiometricConsistency, ...
                RadiometricStatus=radiometricStatus, ...
                VisibilityState=visibilityState, ...
                CovarianceWorldMetersSquared=covariance, ...
                CovarianceStatus=covarianceStatus, ...
                CovarianceReason=covarianceReason, ...
                CovarianceFrame=association.WorldFrame, ...
                PrincipalAxisSigmasMeters=axes);
        end

        function weights = baseWeights(observations)
            confidence = max([observations.Confidence], eps);
            navigation = max([observations.NavigationWeight], eps);
            weights = confidence .* navigation;
            passIds = string({observations.PassId});
            for passId = unique(passIds, "stable")
                mask = passIds == passId;
                weights(mask) = weights(mask) / nnz(mask);
            end
            weights = weights / mean(weights);
        end

        function [point, robustWeights] = irls( ...
                origins, directions, baseWeights, options)
            robustWeights = ones(size(baseWeights));
            previous = nan(3, 1);
            for iteration = 1:options.MaximumIterations
                weights = baseWeights .* robustWeights;
                [point, ~, ~] = ProjectionMultiRayReconstructor. ...
                    weightedSolve(origins, directions, weights);
                residuals = ProjectionMultiRayReconstructor. ...
                    rayDiagnostics(point, origins, directions);
                robustWeights = min(1, options.HuberScaleMeters ./ ...
                    max(residuals, eps));
                if all(isfinite(previous)) && ...
                        norm(point - previous) <= ...
                        options.ConvergenceToleranceMeters
                    break
                end
                previous = point;
            end
        end

        function [point, accepted, residuals, parameters, condition, normal] = ...
                refineAccepted(origins, directions, baseWeights, accepted, options)
            point = nan(3, 1);
            condition = Inf;
            normal = nan(3);
            for iteration = 1:3
                if nnz(accepted) < 2
                    break
                end
                [point, condition, normal] = ...
                    ProjectionMultiRayReconstructor.weightedSolve( ...
                    origins(:, accepted), directions(:, accepted), ...
                    baseWeights(accepted));
                [residuals, parameters] = ...
                    ProjectionMultiRayReconstructor.rayDiagnostics( ...
                    point, origins, directions);
                updated = accepted & ...
                    residuals <= options.MaximumResidualMeters & ...
                    parameters > 0;
                if isequal(updated, accepted)
                    break
                end
                accepted = updated;
            end
            [residuals, parameters] = ...
                ProjectionMultiRayReconstructor.rayDiagnostics( ...
                point, origins, directions);
        end

        function [point, condition, normal] = weightedSolve( ...
                origins, directions, weights)
            normal = zeros(3);
            right = zeros(3, 1);
            identity = eye(3);
            for index = 1:size(origins, 2)
                projector = identity - ...
                    directions(:, index) * directions(:, index).';
                normal = normal + weights(index) * projector;
                right = right + weights(index) * projector * origins(:, index);
            end
            singularValues = svd(normal);
            condition = singularValues(1) / max(singularValues(end), eps);
            point = normal \ right;
            if singularValues(end) <= 1e-12 || any(~isfinite(point))
                point(:) = NaN;
            end
        end

        function [residuals, parameters] = rayDiagnostics( ...
                point, origins, directions)
            delta = point - origins;
            parameters = sum(delta .* directions, 1);
            closest = origins + directions .* parameters;
            residuals = vecnorm(point - closest, 2, 1);
        end

        function records = rayRecords(observations, residuals, parameters, ...
                baseWeights, robustWeights, accepted)
            records = repmat(struct(ObservationKey="", ...
                ObservationId="", ViewId="", PassId="", ...
                SourceRowPixels=NaN, SourceColumnPixels=NaN, ...
                RayOriginWorld=nan(3, 1), RayVectorWorld=nan(3, 1), ...
                RayParameterMeters=NaN, ForwardValid=false, ...
                ResidualMeters=Inf, BaseEvidenceWeight=0, RobustWeight=0, ...
                Accepted=false, RejectionReason="", ...
                VisibilityState="unknown"), 1, numel(observations));
            for index = 1:numel(observations)
                reason = "";
                if ~accepted(index) && parameters(index) <= 0
                    reason = "behindRay";
                elseif ~accepted(index)
                    reason = "robustResidual";
                end
                records(index) = struct( ...
                    ObservationKey=observations(index).ObservationKey, ...
                    ObservationId=observations(index).ObservationId, ...
                    ViewId=observations(index).ViewId, ...
                    PassId=observations(index).PassId, ...
                    SourceRowPixels=observations(index).SourceRowPixels, ...
                    SourceColumnPixels=observations(index).SourceColumnPixels, ...
                    RayOriginWorld=observations(index).RayOriginWorld, ...
                    RayVectorWorld=observations(index).RayVectorWorld, ...
                    RayParameterMeters=parameters(index), ...
                    ForwardValid=parameters(index) > 0, ...
                    ResidualMeters=residuals(index), ...
                    BaseEvidenceWeight=baseWeights(index), ...
                    RobustWeight=robustWeights(index), ...
                    Accepted=accepted(index), RejectionReason=reason, ...
                    VisibilityState=observations(index).VisibilityState);
            end
        end

        function [contributing, rejected] = partitionRecords( ...
                records, trackRecordIds, acceptedObservationKeys)
            mask = ismember(string({records.RecordId}), trackRecordIds);
            trackRecords = records(mask);
            acceptedMask = arrayfun(@(record) all(ismember( ...
                record.ViewIds + "|" + record.ObservationIds, ...
                acceptedObservationKeys)), trackRecords);
            contributing = trackRecords(acceptedMask);
            rejected = trackRecords(~acceptedMask);
        end

        function [consistency, status] = radiometry(records, observations)
            consistency = NaN;
            status = "unavailable";
            if ~isempty(records)
                pairIds = string({records.PairId});
                [~, uniqueIndices] = unique(pairIds, "stable");
                values = [records(uniqueIndices).RadiometricConsistency];
                if ~isempty(values)
                    consistency = mean(values);
                    status = "pairConsistency";
                    return
                end
            end
            values = [observations.RadiometricValue];
            values = values(isfinite(values));
            if numel(values) >= 2
                scale = max(abs(median(values)), eps);
                consistency = exp(-median(abs(values - median(values))) / scale);
                status = "observationRobustSpread";
            end
        end

        function state = visibility(observations)
            if isempty(observations)
                state = "unavailable";
                return
            end
            values = string({observations.VisibilityState});
            if all(values == "visible")
                state = "consistentVisible";
            elseif any(values == "occluded" | values == "conflicting")
                state = "inconsistent";
            else
                state = "partiallyUnobserved";
            end
        end

        function [covariance, status, reason, axes] = covariance( ...
                normal, residuals, weights, valid, options)
            covariance = nan(3);
            axes = nan(3, 1);
            status = "unavailable";
            reason = "insufficientAcceptedRays";
            if ~valid || any(~isfinite(normal), "all")
                return
            end
            sigma = options.ResidualSigmaFloorMeters;
            if ~isempty(residuals)
                sigma = max(sigma, sqrt(sum(weights .* residuals .^ 2) / ...
                    max(sum(weights), eps)));
            end
            covariance = sigma ^ 2 * pinv(0.5 * (normal + normal.'));
            covariance = 0.5 * (covariance + covariance.');
            status = "assumed";
            reason = "independentRayResidualFloorModel";
            axes = sqrt(max(sort(eig(covariance), "descend"), 0));
        end

        function range = angleRange(directions)
            range = [NaN NaN];
            if size(directions, 2) < 2
                return
            end
            angles = zeros(1, nchoosek(size(directions, 2), 2));
            cursor = 0;
            for first = 1:(size(directions, 2) - 1)
                for second = (first + 1):size(directions, 2)
                    cursor = cursor + 1;
                    angles(cursor) = acosd(min(1, max(-1, abs(dot( ...
                        directions(:, first), directions(:, second))))));
                end
            end
            range = [min(angles) max(angles)];
        end

        function point = pairwiseInitialPoint(records)
            point = nan(3, 1);
            if isempty(records)
                return
            end
            pairIds = string({records.PairId});
            [~, uniqueIndices] = unique(pairIds, "stable");
            values = horzcat(records(uniqueIndices).ProvisionalPointWorld);
            if ~isempty(values) && all(isfinite(values), "all")
                point = median(values, 2);
            end
        end

        function value = diagnostics(points)
            states = string({points.State});
            value = struct(PointCount=numel(points), ...
                ValidPointCount=nnz([points.Valid]), ...
                MultiViewPointCount=nnz(states == "multiViewSolved"), ...
                TwoViewRetainedCount=nnz(states == "twoViewRetained"), ...
                RejectedPointCount=nnz(~[points.Valid]), ...
                CompetingModePointCount=nnz([points.CompetingMode]), ...
                RejectedRayCount=sum(arrayfun(@(point) ...
                nnz(~[point.RayDiagnostics.Accepted]), points)));
        end

        function result = validateResult(result)
            required = ["Format" "Version" "Status" "Stage" ...
                "AuthoritativeProduct" "WorldFrame" "CovarianceUnits" ...
                "GenerationId" "AssociationGenerationId" "Points" ...
                "Diagnostics" "Provenance"];
            if ~isstruct(result) || ~isscalar(result) || ...
                    any(~isfield(result, required)) || ...
                    ~isscalar(string(result.Format)) || ...
                    ismissing(string(result.Format)) || ...
                    string(result.Format) ~= ...
                    ProjectionMultiRayReconstructor.Format || ...
                    ~isequal(result.Version, ...
                    ProjectionMultiRayReconstructor.Version) || ...
                    string(result.Stage) ~= "robustMultiView" || ...
                    ~isstruct(result.Points)
                error("ProjectionMultiRayReconstructor:invalidResult", ...
                    "A supported robust multi-view point set is required.");
            end
        end

        function path = filePath(path, extension, name)
            path = string(path);
            if ~isscalar(path) || ismissing(path) || strlength(path) == 0 || ...
                    ~endsWith(lower(path), extension)
                error("ProjectionMultiRayReconstructor:invalidPath", ...
                    "%s must be a nonempty %s path.", name, extension);
            end
        end

        function point = emptyPoint()
            point = struct(PointId="", TrackId="", ModeId="", ...
                CompetingMode=false, Stage="robustMultiView", State="", ...
                Valid=false, PointWorld=nan(3, 1), ...
                PairwiseInitialOracleWorld=nan(3, 1), ...
                PairwiseInitialOracleLabel="pairwisePointMedianNotAuthoritative", ...
                ObservationKeys=strings(1, 0), ...
                ObservationIds=strings(1, 0), ...
                ContributingObservationKeys=strings(1, 0), ...
                ContributingObservationIds=strings(1, 0), ...
                ContributingViewIds=strings(1, 0), ...
                RejectedViewIds=strings(1, 0), ...
                ContributingPassIds=strings(1, 0), ...
                ContributingRecordIds=strings(1, 0), ...
                RejectedRecordIds=strings(1, 0), ...
                ContributingPairIds=strings(1, 0), ...
                RejectedPairIds=strings(1, 0), ...
                IndependentViewCount=0, IndependentPassCount=0, ...
                PairRecordCount=0, RayDiagnostics=repmat(struct( ...
                ObservationKey="", ObservationId="", ...
                ViewId="", PassId="", ...
                SourceRowPixels=NaN, SourceColumnPixels=NaN, ...
                RayOriginWorld=nan(3, 1), RayVectorWorld=nan(3, 1), ...
                RayParameterMeters=NaN, ForwardValid=false, ...
                ResidualMeters=Inf, BaseEvidenceWeight=0, RobustWeight=0, ...
                Accepted=false, RejectionReason="", ...
                VisibilityState="unknown"), 1, 0), ...
                RobustResidualRmsMeters=NaN, ConditionNumber=Inf, ...
                IntersectionAngleRangeDegrees=[NaN NaN], ...
                RadiometricConsistency=NaN, RadiometricStatus="unavailable", ...
                VisibilityState="unavailable", ...
                CovarianceWorldMetersSquared=nan(3), ...
                CovarianceStatus="unavailable", ...
                CovarianceReason="notRun", CovarianceFrame="", ...
                PrincipalAxisSigmasMeters=nan(3, 1));
        end
    end
end
