classdef ProjectionGaussianSplatFusion < ProjectionSurfaceFusionAlgorithm
    %ProjectionGaussianSplatFusion Sparse uncertainty-weighted Gaussian votes.

    methods
        function metadata = metadata(~)
            metadata = struct(AlgorithmId="sightline.fusion.gaussian-splat", ...
                Name="Sparse uncertainty-weighted Gaussian splats", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct(FusedPoints=true, VoxelEvidence=true, ...
                CompetingModes=true, Covariance=true), ...
                RequiredProducts="ProjectionMultiRayPointSet", ...
                Deterministic=true, Precision="double", ...
                MemoryEstimate="sparseKernelSupportVoxels", ...
                CpuSupported=true, GpuSupported=false, ...
                ProductRole="diagnosticDerived");
        end

        function options = defaultOptions(~)
            options = struct(MaximumGridCells=2000000, ...
                MaximumContributions=5000000, ...
                KernelSigmaFloorVoxels=0.5, TruncationSigma=3, ...
                MinimumKernelWeight=1e-6);
        end

        function options = validateOptions(algorithm, options)
            defaults = algorithm.defaultOptions();
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionGaussianSplatFusion:invalidOptions", ...
                    "Gaussian-splat options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionGaussianSplatFusion:invalidOptions", ...
                    "Unexpected option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            integerFields = ["MaximumGridCells" "MaximumContributions"];
            for field = integerFields
                value = defaults.(field);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value < 1 || fix(value) ~= value
                    error("ProjectionGaussianSplatFusion:invalidOptions", ...
                        "%s must be a positive integer.", field);
                end
                defaults.(field) = double(value);
            end
            positiveFields = ["KernelSigmaFloorVoxels" "TruncationSigma" ...
                "MinimumKernelWeight"];
            for field = positiveFields
                value = defaults.(field);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value <= 0
                    error("ProjectionGaussianSplatFusion:invalidOptions", ...
                        "%s must be a finite positive scalar.", field);
                end
                defaults.(field) = double(value);
            end
            if defaults.MinimumKernelWeight >= 1
                error("ProjectionGaussianSplatFusion:invalidOptions", ...
                    "MinimumKernelWeight must be less than one.");
            end
            options = defaults;
        end
    end

    methods (Access = protected)
        function result = fuseImpl(~, request, options, runtimeControl)
            [inputPoints, rejections] = ...
                ProjectionSurfaceFusionSupport.selectPoints(request);
            evidence = ProjectionSurfaceFusionSupport.gaussianEvidence( ...
                inputPoints, request, options, runtimeControl);
            fusedPoints = ProjectionSurfaceFusionSupport.pointsFromEvidence( ...
                evidence, inputPoints, request);
            result = struct(FusedPoints=fusedPoints, ...
                SparseVoxelEvidence=evidence, ...
                CompetingModes=ProjectionSurfaceFusionSupport. ...
                modeSummary(inputPoints), ...
                Uncertainty=struct( ...
                Policy="inputCovariancePlusVoxelSigmaFloor", ...
                InputCovarianceCount=nnz(arrayfun(@(point) all(isfinite( ...
                point.CovarianceWorldMetersSquared), "all"), inputPoints))), ...
                Contributors=ProjectionSurfaceFusionSupport. ...
                contributorSummary(inputPoints, fusedPoints), ...
                Rejections=rejections, ...
                Diagnostics=struct(EvidenceKind="normalizedGaussianPointSplat", ...
                AuxiliaryPoseObjective=false, ...
                PairMultiplicityUsed=false), ...
                Memory=struct(Bytes= ...
                ProjectionSurfaceFusionSupport.bytes(evidence)), ...
                Execution=struct(Device="cpu"));
        end
    end
end
