classdef ProjectionTimeVaryingOpkResearch
    %ProjectionTimeVaryingOpkResearch A7 tangent-spline observability study.

    properties (Constant)
        Format = "ProjectionTimeVaryingOpkResearchResult"
        Version = 1
        NominalPostSpacingPixels = 128
    end

    methods (Static)
        function result = analyze(request, options)
            %analyze Fit a research-only pass/view tangent-space spline model.
            if nargin < 2
                options = struct();
            end
            request = ProjectionTimeVaryingOpkResearch.validateRequest(request);
            options = ProjectionTimeVaryingOpkResearch.validateOptions(options);
            timer = tic;
            spacing = options.PostSpacingPixels;
            history = struct("PostSpacingPixels", {}, ...
                "ParameterCount", {}, "ObservationCount", {}, ...
                "DataRank", {}, "RequiredDataRank", {}, ...
                "DataConditionNumber", {}, ...
                "MinimumControlSupport", {}, "SupportSufficient", {}, ...
                "RankSufficient", {}, "ConditionSufficient", {});
            while true
                system = ProjectionTimeVaryingOpkResearch.system( ...
                    request, spacing, options);
                assessment = ProjectionTimeVaryingOpkResearch.assess( ...
                    system, options);
                history(end + 1) = assessment; %#ok<AGROW>
                if options.Mode == "perColumnAnalysis" || ...
                        (assessment.SupportSufficient && ...
                        assessment.RankSufficient && ...
                        assessment.ConditionSufficient) || ...
                        spacing >= options.MaximumPostSpacingPixels
                    break
                end
                spacing = min(options.MaximumPostSpacingPixels, 2 * spacing);
            end
            solution = ProjectionTimeVaryingOpkResearch.solve(system, options);
            views = ProjectionTimeVaryingOpkResearch.viewResults( ...
                request, system, solution);
            passes = ProjectionTimeVaryingOpkResearch.passResults( ...
                system, solution);
            predicted = system.Design * solution.Parameters;
            residual = system.Observations - predicted;
            locallyObservable = assessment.SupportSufficient && ...
                assessment.RankSufficient && assessment.ConditionSufficient;
            if options.Mode == "perColumnAnalysis"
                status = "analysisUpperBound";
            elseif locallyObservable
                status = "locallyObservableResearch";
            else
                status = "insufficientLocalObservability";
            end
            result = struct(Format= ...
                ProjectionTimeVaryingOpkResearch.Format, ...
                Version=ProjectionTimeVaryingOpkResearch.Version, ...
                Status=status, Stage="timeVaryingOpkResearch", ...
                SourceGenerationId=request.SourceGenerationId, ...
                Model=struct(Parameterization="localRotationVector", ...
                Composition="leftComposeExpMapWithNominalRotation", ...
                Basis="openUniformCubicBSpline", Degree=3, ...
                NominalPostSpacingPixels= ...
                ProjectionTimeVaryingOpkResearch.NominalPostSpacingPixels, ...
                SelectedPostSpacingPixels=spacing, ...
                Smoothness="secondDifference", ...
                PassCommonComponent=true, PerImageComponent=true, ...
                PerColumnAnalysisOnly=options.Mode == "perColumnAnalysis"), ...
                Passes=passes, Views=views, ...
                Observability=struct(LocallyObservable=locallyObservable, ...
                History=history, Final=assessment, ...
                PriorAugmentedRank=solution.AugmentedRank, ...
                PriorDominated=~locallyObservable, ...
                Coarsened=spacing > options.PostSpacingPixels), ...
                Residuals=ProjectionTimeVaryingOpkResearch. ...
                residualSummary(residual), ...
                Covariance=struct(Available=solution.CovarianceAvailable, ...
                ParameterRadiansSquared=solution.Covariance, ...
                Status=solution.CovarianceStatus, ...
                Reason=solution.CovarianceReason), ...
                Decision="retainResearchOnly", ...
                DecisionReason= ...
                "Physical dense-network local observability and stability are not yet demonstrated.", ...
                ApplicationSupported=false, AutoApplied=false, ...
                Precision="double", Timing=struct(TotalSeconds=toc(timer)), ...
                Provenance=struct(Method="weightedLinearizedTangentSpline", ...
                TruthUsedOperationally=false, Deterministic=true, ...
                EvidenceKinds=unique(string({request.Views.EvidenceKind})), ...
                Options=options));
            result = ProjectionTimeVaryingOpkResearch.validateResult(result);
        end

        function [basis, definition] = basis(imageWidthPixels, columns, spacing)
            %basis Evaluate an open-uniform cubic B-spline over source columns.
            imageWidthPixels = ProjectionTimeVaryingOpkResearch. ...
                positiveInteger(imageWidthPixels, "ImageWidthPixels");
            spacing = ProjectionTimeVaryingOpkResearch.positiveInteger( ...
                spacing, "PostSpacingPixels");
            if ~isnumeric(columns) || isempty(columns) || ~isvector(columns) || ...
                    any(~isfinite(columns)) || any(columns < 1) || ...
                    any(columns > imageWidthPixels)
                error("ProjectionTimeVaryingOpkResearch:invalidColumns", ...
                    "Source columns must be finite and within the image width.");
            end
            columns = reshape(double(columns), 1, []);
            segmentCount = max(1, ceil((imageWidthPixels - 1) / spacing));
            controlCount = segmentCount + 3;
            knots = [zeros(1, 4) 1:(segmentCount - 1) ...
                segmentCount * ones(1, 4)];
            parameter = (columns - 1) / max(imageWidthPixels - 1, 1) * ...
                segmentCount;
            degreeZero = zeros(numel(columns), controlCount + 3);
            for index = 1:(controlCount + 3)
                degreeZero(:, index) = parameter >= knots(index) & ...
                    parameter < knots(index + 1);
            end
            degreeZero(parameter == segmentCount, controlCount) = 1;
            current = degreeZero;
            for degree = 1:3
                next = zeros(size(current));
                for index = 1:(controlCount + 3 - degree)
                    leftDenominator = knots(index + degree) - knots(index);
                    rightDenominator = ...
                        knots(index + degree + 1) - knots(index + 1);
                    if leftDenominator > 0
                        next(:, index) = next(:, index) + ...
                            ((parameter - knots(index)) / leftDenominator).' .* ...
                            current(:, index);
                    end
                    if rightDenominator > 0
                        next(:, index) = next(:, index) + ...
                            ((knots(index + degree + 1) - parameter) / ...
                            rightDenominator).' .* current(:, index + 1);
                    end
                end
                current = next;
            end
            basis = current(:, 1:controlCount);
            basis(parameter == segmentCount, :) = 0;
            basis(parameter == segmentCount, controlCount) = 1;
            definition = struct(Degree=3, Knots=knots, ...
                SegmentCount=segmentCount, ControlCount=controlCount, ...
                ImageWidthPixels=imageWidthPixels, ...
                PostSpacingPixels=spacing, ...
                ControlAbscissaPixels=linspace(1, imageWidthPixels, controlCount));
        end

        function rotations = compose(nominalRotation, rotationVectors)
            %compose Left-compose tangent rotation vectors with nominal attitude.
            if ~isnumeric(nominalRotation) || ...
                    ~isequal(size(nominalRotation), [3 3]) || ...
                    any(~isfinite(nominalRotation), "all") || ...
                    norm(nominalRotation.' * nominalRotation - eye(3), ...
                    "fro") > 1e-9 || abs(det(nominalRotation) - 1) > 1e-9
                error("ProjectionTimeVaryingOpkResearch:invalidRotation", ...
                    "Nominal attitude must be a proper 3-by-3 rotation.");
            end
            if ~isnumeric(rotationVectors) || ...
                    size(rotationVectors, 1) ~= 3 || ...
                    any(~isfinite(rotationVectors), "all")
                error("ProjectionTimeVaryingOpkResearch:invalidRotationVector", ...
                    "Rotation vectors must be a finite 3-by-N array.");
            end
            nominalRotation = double(nominalRotation);
            rotationVectors = double(rotationVectors);
            rotations = zeros(3, 3, size(rotationVectors, 2));
            for index = 1:size(rotationVectors, 2)
                vector = rotationVectors(:, index);
                angle = norm(vector);
                skew = [0 -vector(3) vector(2); vector(3) 0 -vector(1); ...
                    -vector(2) vector(1) 0];
                if angle < 1e-10
                    increment = eye(3) + skew + 0.5 * skew * skew;
                else
                    increment = eye(3) + sin(angle) / angle * skew + ...
                        (1 - cos(angle)) / angle ^ 2 * (skew * skew);
                end
                rotations(:, :, index) = increment * nominalRotation;
            end
        end

        function correctionSet = toCorrectionSet( ...
                scene, result, parentGenerationId)
            %toCorrectionSet Package research blocks without enabling Apply.
            scene = ProjectionViewMetadata.ensureScene(scene);
            result = ProjectionTimeVaryingOpkResearch.validateResult(result);
            parentGenerationId = ProjectionTimeVaryingOpkResearch. ...
                requiredString(parentGenerationId, "ParentGenerationId");
            views = ProjectionTimeVaryingOpkResearch.correctionViews( ...
                scene, result.Views);
            blocks = ProjectionTimeVaryingOpkResearch.correctionBlocks(result);
            fingerprints = ProjectionGeometryFingerprint.scene(scene);
            identity = struct(SourceGenerationId=result.SourceGenerationId, ...
                ParentGenerationId=parentGenerationId, ...
                Fingerprints=fingerprints, Model=result.Model);
            generationId = "time-varying-opk-research-" + extractBefore( ...
                ProjectionGeometryFingerprint.hash(identity), 17);
            data = struct(Format=ProjectionCorrectionSet.FormatName, ...
                Version=ProjectionCorrectionSet.SchemaVersion, ...
                GenerationId=generationId, ...
                ParentGenerationId=parentGenerationId, ...
                Lifecycle="proposed", Views=views, Passes=result.Passes, ...
                Blocks=blocks, Geometry=struct(Parent=fingerprints, ...
                Corrected=fingerprints, ScopeViewIds=string({views.ViewId}), ...
                ApplicationModel="researchOnlyNotApplied"), ...
                Covariance=struct(Available=false, ...
                AttitudeRadiansSquared=zeros(0), ...
                ConditionNumber=result.Observability.Final.DataConditionNumber, ...
                Reason="researchSplineCovarianceNotMappedToSceneGeometry"), ...
                Provenance=struct(Source="timeVaryingOpkResearch", ...
                SourceGenerationId=result.SourceGenerationId, ...
                Precision="double", AutoApplied=false), ...
                Diagnostics=struct(ResearchOnly=true, ...
                ApplicationSupported=false, AutoApply=false, ...
                Decision=result.Decision, ...
                Observability=result.Observability), ...
                Failure=struct(Valid=true, Code="none", ...
                Explanation="Valid research result; application is gated."));
            correctionSet = ProjectionCorrectionSet.create(data);
        end
    end

    methods (Static, Access = private)
        function request = validateRequest(request)
            if ~isstruct(request) || ~isscalar(request) || ...
                    any(~isfield(request, ["SourceGenerationId" "Views"])) || ...
                    isfield(request, "Truth") || isfield(request, "Expected") || ...
                    ProjectionTimeVaryingOpkResearch.hasRuntimeValue(request)
                error("ProjectionTimeVaryingOpkResearch:invalidRequest", ...
                    "Research request must be portable and truth-free.");
            end
            request.SourceGenerationId = ...
                ProjectionTimeVaryingOpkResearch.requiredString( ...
                request.SourceGenerationId, "SourceGenerationId");
            if ~isstruct(request.Views) || numel(request.Views) < 2
                error("ProjectionTimeVaryingOpkResearch:invalidViews", ...
                    "At least two view observation records are required.");
            end
            required = ["ViewId" "PassId" "ImageWidthPixels" ...
                "SourceColumnsPixels" "RotationJacobians" "Residuals" ...
                "Weights" "EvidenceKind"];
            viewIds = strings(1, numel(request.Views));
            for index = 1:numel(request.Views)
                view = request.Views(index);
                if any(~isfield(view, required))
                    error("ProjectionTimeVaryingOpkResearch:invalidViews", ...
                        "View observation schema is incomplete.");
                end
                view.ViewId = ProjectionTimeVaryingOpkResearch. ...
                    requiredString(view.ViewId, "ViewId");
                view.PassId = ProjectionTimeVaryingOpkResearch. ...
                    requiredString(view.PassId, "PassId");
                view.ImageWidthPixels = ProjectionTimeVaryingOpkResearch. ...
                    positiveInteger(view.ImageWidthPixels, "ImageWidthPixels");
                columns = reshape(double(view.SourceColumnsPixels), [], 1);
                residuals = reshape(double(view.Residuals), [], 1);
                weights = reshape(double(view.Weights), [], 1);
                count = numel(columns);
                if count < 3 || ~isnumeric(view.SourceColumnsPixels) || ...
                        any(~isfinite(columns)) || any(columns < 1) || ...
                        any(columns > view.ImageWidthPixels) || ...
                        ~isnumeric(view.RotationJacobians) || ...
                        ~isequal(size(view.RotationJacobians), [count 3]) || ...
                        any(~isfinite(view.RotationJacobians), "all") || ...
                        numel(residuals) ~= count || any(~isfinite(residuals)) || ...
                        numel(weights) ~= count || any(~isfinite(weights)) || ...
                        any(weights <= 0)
                    error("ProjectionTimeVaryingOpkResearch:invalidObservations", ...
                        "Columns, Jacobians, residuals, and weights are inconsistent.");
                end
                evidence = string(view.EvidenceKind);
                if ~isscalar(evidence) || ...
                        ~ismember(evidence, ["sparse" "dense" "mixed"])
                    error("ProjectionTimeVaryingOpkResearch:invalidEvidence", ...
                        "EvidenceKind must be sparse, dense, or mixed.");
                end
                view.SourceColumnsPixels = columns;
                view.RotationJacobians = double(view.RotationJacobians);
                view.Residuals = residuals;
                view.Weights = weights;
                view.EvidenceKind = evidence;
                request.Views(index) = view;
                viewIds(index) = view.ViewId;
            end
            if numel(unique(viewIds)) ~= numel(viewIds)
                error("ProjectionTimeVaryingOpkResearch:duplicateView", ...
                    "ViewId values must be unique.");
            end
        end

        function options = validateOptions(options)
            defaults = struct(PostSpacingPixels= ...
                ProjectionTimeVaryingOpkResearch.NominalPostSpacingPixels, ...
                MaximumPostSpacingPixels=2048, ...
                MinimumObservationsPerControl=12, ...
                MaximumDataConditionNumber=1e10, ...
                MaximumParameterCount=2000, ...
                SmoothnessWeight=1e-3, GaugeWeight=1e3, Mode="spline");
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionTimeVaryingOpkResearch:invalidOptions", ...
                    "Options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionTimeVaryingOpkResearch:invalidOptions", ...
                    "Unexpected option %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            defaults.PostSpacingPixels = ...
                ProjectionTimeVaryingOpkResearch.positiveInteger( ...
                defaults.PostSpacingPixels, "PostSpacingPixels");
            defaults.MaximumPostSpacingPixels = ...
                ProjectionTimeVaryingOpkResearch.positiveInteger( ...
                defaults.MaximumPostSpacingPixels, ...
                "MaximumPostSpacingPixels");
            defaults.MinimumObservationsPerControl = ...
                ProjectionTimeVaryingOpkResearch.positiveInteger( ...
                defaults.MinimumObservationsPerControl, ...
                "MinimumObservationsPerControl");
            defaults.MaximumParameterCount = ...
                ProjectionTimeVaryingOpkResearch.positiveInteger( ...
                defaults.MaximumParameterCount, "MaximumParameterCount");
            scalars = ["MaximumDataConditionNumber" "SmoothnessWeight" ...
                "GaugeWeight"];
            for name = scalars
                value = defaults.(name);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value <= 0
                    error("ProjectionTimeVaryingOpkResearch:invalidOptions", ...
                        "%s must be positive and finite.", name);
                end
                defaults.(name) = double(value);
            end
            defaults.Mode = string(defaults.Mode);
            if ~isscalar(defaults.Mode) || ...
                    ~ismember(defaults.Mode, ["spline" "perColumnAnalysis"])
                error("ProjectionTimeVaryingOpkResearch:invalidOptions", ...
                    "Mode must be spline or perColumnAnalysis.");
            end
            if defaults.Mode == "perColumnAnalysis"
                defaults.PostSpacingPixels = 1;
                defaults.MaximumPostSpacingPixels = 1;
            elseif defaults.MaximumPostSpacingPixels < ...
                    defaults.PostSpacingPixels
                error("ProjectionTimeVaryingOpkResearch:invalidOptions", ...
                    "Maximum post spacing cannot be smaller than initial spacing.");
            end
            options = defaults;
        end

        function system = system(request, spacing, options)
            passIds = unique(string({request.Views.PassId}), "stable");
            passOffsets = containers.Map(cellstr(passIds), ...
                num2cell(1 + 3 * (0:numel(passIds)-1)));
            cursor = 3 * numel(passIds) + 1;
            layouts = repmat(struct(ViewId="", PassId="", Offset=0, ...
                ControlCount=0, Basis=zeros(0), Definition=struct(), ...
                ObservationIndices=[]), 1, numel(request.Views));
            observationCount = sum(arrayfun( ...
                @(view) numel(view.Residuals), request.Views));
            for index = 1:numel(request.Views)
                view = request.Views(index);
                [basis, definition] = ProjectionTimeVaryingOpkResearch. ...
                    basis(view.ImageWidthPixels, ...
                    view.SourceColumnsPixels, spacing);
                layouts(index) = struct(ViewId=view.ViewId, ...
                    PassId=view.PassId, Offset=cursor, ...
                    ControlCount=definition.ControlCount, Basis=basis, ...
                    Definition=definition, ObservationIndices=[]);
                cursor = cursor + 3 * definition.ControlCount;
            end
            parameterCount = cursor - 1;
            if parameterCount > options.MaximumParameterCount
                error("ProjectionTimeVaryingOpkResearch:resourceLimit", ...
                    "The requested model has %d parameters; the bounded " + ...
                    "research limit is %d.", parameterCount, ...
                    options.MaximumParameterCount);
            end
            design = zeros(observationCount, parameterCount);
            observations = zeros(observationCount, 1);
            weights = zeros(observationCount, 1);
            row = 0;
            for index = 1:numel(request.Views)
                view = request.Views(index);
                count = numel(view.Residuals);
                rows = row + (1:count);
                layouts(index).ObservationIndices = rows;
                passOffset = passOffsets(char(view.PassId));
                design(rows, passOffset:(passOffset + 2)) = ...
                    view.RotationJacobians;
                for control = 1:layouts(index).ControlCount
                    columns = layouts(index).Offset + 3 * (control - 1) + (0:2);
                    design(rows, columns) = ...
                        view.RotationJacobians .* ...
                        layouts(index).Basis(:, control);
                end
                observations(rows) = view.Residuals;
                weights(rows) = view.Weights;
                row = row + count;
            end
            prior = ProjectionTimeVaryingOpkResearch.prior( ...
                layouts, passIds, parameterCount, options);
            controlSupport = zeros(1, 0);
            for layout = layouts
                controlSupport = [controlSupport ...
                    sum(layout.Basis > 1e-8, 1)]; %#ok<AGROW>
            end
            system = struct(Design=design, Observations=observations, ...
                Weights=weights, Prior=prior, Layouts=layouts, ...
                PassIds=passIds, PassOffsets=passOffsets, ...
                ParameterCount=parameterCount, ...
                ControlSupport=controlSupport, PostSpacingPixels=spacing);
        end

        function prior = prior(layouts, passIds, count, options)
            rows = cell(1, 0);
            for layout = layouts
                if layout.ControlCount >= 3
                    difference = diff(eye(layout.ControlCount), 2, 1);
                    for component = 1:3
                        block = zeros(size(difference, 1), count);
                        columns = layout.Offset + component - 1 + ...
                            3 * (0:(layout.ControlCount - 1));
                        block(:, columns) = ...
                            sqrt(options.SmoothnessWeight) * difference;
                        rows{end + 1} = block; %#ok<AGROW>
                    end
                end
            end
            for passId = passIds
                selected = layouts(string({layouts.PassId}) == passId);
                for component = 1:3
                    block = zeros(1, count);
                    for layout = selected
                        columns = layout.Offset + component - 1 + ...
                            3 * (0:(layout.ControlCount - 1));
                        block(columns) = sqrt(options.GaugeWeight) / ...
                            (numel(selected) * layout.ControlCount);
                    end
                    rows{end + 1} = block; %#ok<AGROW>
                end
            end
            if isempty(rows)
                prior = zeros(0, count);
            else
                prior = vertcat(rows{:});
            end
        end

        function assessment = assess(system, options)
            weighted = sqrt(system.Weights) .* system.Design;
            singularValues = svd(weighted, "econ");
            tolerance = max(size(weighted)) * eps(max(singularValues));
            dataRank = nnz(singularValues > tolerance);
            requiredRank = system.ParameterCount - 3 * numel(system.PassIds);
            conditionNumber = Inf;
            if dataRank >= requiredRank && requiredRank > 0
                conditionNumber = singularValues(1) / ...
                    singularValues(requiredRank);
            end
            minimumSupport = min(system.ControlSupport);
            assessment = struct(PostSpacingPixels= ...
                system.PostSpacingPixels, ...
                ParameterCount=system.ParameterCount, ...
                ObservationCount=size(system.Design, 1), DataRank=dataRank, ...
                RequiredDataRank=requiredRank, ...
                DataConditionNumber=conditionNumber, ...
                MinimumControlSupport=minimumSupport, ...
                SupportSufficient=minimumSupport >= ...
                options.MinimumObservationsPerControl, ...
                RankSufficient=dataRank >= requiredRank, ...
                ConditionSufficient=conditionNumber <= ...
                options.MaximumDataConditionNumber);
        end

        function solution = solve(system, ~)
            weightedDesign = sqrt(system.Weights) .* system.Design;
            weightedObservations = sqrt(system.Weights) .* system.Observations;
            augmented = [weightedDesign; system.Prior];
            rightHandSide = [weightedObservations; ...
                zeros(size(system.Prior, 1), 1)];
            parameters = augmented \ rightHandSide;
            normal = augmented.' * augmented;
            augmentedRank = rank(augmented);
            covarianceAvailable = augmentedRank == system.ParameterCount;
            if covarianceAvailable
                covariance = pinv(normal);
                covarianceStatus = "researchLinearized";
                covarianceReason = "weightedSplineNormalMatrix";
            else
                covariance = zeros(0);
                covarianceStatus = "unavailable";
                covarianceReason = "rankDeficientResearchSystem";
            end
            solution = struct(Parameters=parameters, ...
                AugmentedRank=augmentedRank, Covariance=covariance, ...
                CovarianceAvailable=covarianceAvailable, ...
                CovarianceStatus=covarianceStatus, ...
                CovarianceReason=covarianceReason);
        end

        function views = viewResults(request, system, solution)
            template = struct(ViewId="", PassId="", EvidenceKind="", ...
                ImageWidthPixels=0, PostSpacingPixels=0, ...
                ControlAbscissaPixels=zeros(1, 0), ...
                DifferentialControlRotationVectorsRadians=zeros(0, 3), ...
                SourceColumnsPixels=zeros(1, 0), ...
                EffectiveRotationVectorsAtObservationsRadians=zeros(0, 3), ...
                LocalSupportCounts=zeros(1, 0));
            views = repmat(template, 1, numel(request.Views));
            for index = 1:numel(request.Views)
                view = request.Views(index);
                layout = system.Layouts(index);
                coefficients = reshape(solution.Parameters( ...
                    layout.Offset:(layout.Offset + ...
                    3 * layout.ControlCount - 1)), 3, []).';
                passOffset = system.PassOffsets(char(view.PassId));
                common = solution.Parameters(passOffset:(passOffset + 2)).';
                effective = common + layout.Basis * coefficients;
                views(index) = struct(ViewId=view.ViewId, ...
                    PassId=view.PassId, EvidenceKind=view.EvidenceKind, ...
                    ImageWidthPixels=view.ImageWidthPixels, ...
                    PostSpacingPixels=system.PostSpacingPixels, ...
                    ControlAbscissaPixels= ...
                    layout.Definition.ControlAbscissaPixels, ...
                    DifferentialControlRotationVectorsRadians=coefficients, ...
                    SourceColumnsPixels=reshape( ...
                    view.SourceColumnsPixels, 1, []), ...
                    EffectiveRotationVectorsAtObservationsRadians=effective, ...
                    LocalSupportCounts=sum(layout.Basis > 1e-8, 1));
            end
        end

        function passes = passResults(system, solution)
            passes = repmat(struct(PassId="", ...
                CommonAttitudeRadians=zeros(1, 3), ...
                TranslationMeters=zeros(1, 3), ...
                TranslationAvailable=false), 1, numel(system.PassIds));
            for index = 1:numel(system.PassIds)
                passId = system.PassIds(index);
                offset = system.PassOffsets(char(passId));
                passes(index).PassId = passId;
                passes(index).CommonAttitudeRadians = ...
                    solution.Parameters(offset:(offset + 2)).';
            end
        end

        function result = validateResult(result)
            required = ["Format" "Version" "Status" "Stage" ...
                "SourceGenerationId" "Model" "Passes" "Views" ...
                "Observability" "Residuals" "Covariance" "Decision" ...
                "DecisionReason" "ApplicationSupported" "AutoApplied" ...
                "Precision" "Timing" "Provenance"];
            if ~isstruct(result) || ~isscalar(result) || ...
                    any(~isfield(result, required)) || ...
                    string(result.Format) ~= ...
                    ProjectionTimeVaryingOpkResearch.Format || ...
                    ~isequal(result.Version, ...
                    ProjectionTimeVaryingOpkResearch.Version) || ...
                    string(result.Stage) ~= "timeVaryingOpkResearch" || ...
                    ~ismember(string(result.Status), [ ...
                    "locallyObservableResearch" ...
                    "insufficientLocalObservability" ...
                    "analysisUpperBound"]) || ...
                    ~isstruct(result.Views) || isempty(result.Views) || ...
                    ~isstruct(result.Passes) || isempty(result.Passes) || ...
                    ~isequal(result.ApplicationSupported, false) || ...
                    ~isequal(result.AutoApplied, false) || ...
                    string(result.Precision) ~= "double" || ...
                    string(result.Decision) ~= "retainResearchOnly" || ...
                    ProjectionTimeVaryingOpkResearch.hasRuntimeValue(result)
                error("ProjectionTimeVaryingOpkResearch:invalidResult", ...
                    "Time-varying OPK research result is invalid.");
            end
        end

        function views = correctionViews(scene, resultViews)
            template = struct(ViewId="", PassId="", LayerId="", ...
                ParentAttitudeRadians=zeros(1, 3), ...
                EffectiveAttitudeRadians=zeros(1, 3), ...
                CommonAttitudeRadians=zeros(1, 3), ...
                DifferentialAttitudeRadians=zeros(1, 3), ...
                ParentRotationMatrix=eye(3), ...
                IncrementRotationMatrix=eye(3), ...
                EffectiveRotationMatrix=eye(3), ...
                IncrementRotationVectorRadians=zeros(1, 3), ...
                ParentProjectionOffsetMeters=zeros(1, 2), ...
                EffectiveProjectionOffsetMeters=zeros(1, 2), ...
                BaseGeometryFingerprint="", ...
                ParentGeometryFingerprint="", ...
                CorrectedGeometryFingerprint="");
            views = repmat(template, 1, numel(resultViews));
            for index = 1:numel(resultViews)
                resultView = resultViews(index);
                layerIndex = ProjectionViewMetadata.indexForId( ...
                    scene, resultView.ViewId);
                layer = scene.layers(layerIndex);
                if string(layer.PassId) ~= string(resultView.PassId)
                    error("ProjectionTimeVaryingOpkResearch:passMismatch", ...
                        "Research result pass does not match the scene.");
                end
                [rotation, radians] = ProjectionMeshBuilder. ...
                    viewVectorRotation(layer, layer.CurrentProjectionPlane);
                fingerprint = ProjectionGeometryFingerprint.layer(layer);
                views(index) = struct(ViewId=string(layer.ViewId), ...
                    PassId=string(layer.PassId), ...
                    LayerId=string(layer.LayerId), ...
                    ParentAttitudeRadians=reshape(radians, 1, 3), ...
                    EffectiveAttitudeRadians=reshape(radians, 1, 3), ...
                    CommonAttitudeRadians=zeros(1, 3), ...
                    DifferentialAttitudeRadians=zeros(1, 3), ...
                    ParentRotationMatrix=rotation, ...
                    IncrementRotationMatrix=eye(3), ...
                    EffectiveRotationMatrix=rotation, ...
                    IncrementRotationVectorRadians=zeros(1, 3), ...
                    ParentProjectionOffsetMeters=reshape(double( ...
                    layer.ProjectionOffsetMeters), 1, 2), ...
                    EffectiveProjectionOffsetMeters=reshape(double( ...
                    layer.ProjectionOffsetMeters), 1, 2), ...
                    BaseGeometryFingerprint=fingerprint, ...
                    ParentGeometryFingerprint=fingerprint, ...
                    CorrectedGeometryFingerprint=fingerprint);
            end
        end

        function blocks = correctionBlocks(result)
            template = struct(Name="", Type="", Scope="", TargetId="", ...
                Values=[], Units="", Frame="", Semantics="");
            blocks = repmat(template, 1, ...
                numel(result.Passes) + numel(result.Views));
            cursor = 0;
            for pass = result.Passes
                cursor = cursor + 1;
                blocks(cursor) = struct(Name="pass common tangent rotation", ...
                    Type="passCommonRotationVector", Scope="pass", ...
                    TargetId=pass.PassId, ...
                    Values=pass.CommonAttitudeRadians, Units="radians", ...
                    Frame="localAttitudeTangent", ...
                    Semantics="leftComposeWithNominalRotation");
            end
            for view = result.Views
                cursor = cursor + 1;
                blocks(cursor) = struct(Name="time-varying OPK spline", ...
                    Type="timeVaryingRotationSpline", Scope="view", ...
                    TargetId=view.ViewId, ...
                    Values=view.DifferentialControlRotationVectorsRadians, ...
                    Units="radians", Frame="localAttitudeTangent", ...
                    Semantics="openUniformCubicByFullSourceColumnResearchOnly");
            end
        end

        function summary = residualSummary(values)
            values = double(values(:));
            absolute = sort(abs(values));
            summary = struct(Count=numel(values), ...
                Rms=sqrt(mean(values .^ 2)), Median=median(values), ...
                P95Absolute=absolute(max(1, ceil(0.95 * numel(absolute)))), ...
                MaximumAbsolute=max(absolute));
        end

        function value = positiveInteger(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 1 || fix(value) ~= value
                error("ProjectionTimeVaryingOpkResearch:invalidInteger", ...
                    "%s must be a positive integer.", name);
            end
            value = double(value);
        end

        function value = requiredString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || ...
                    strlength(value) == 0 || value ~= strip(value)
                error("ProjectionTimeVaryingOpkResearch:invalidString", ...
                    "%s must be a nonempty trimmed string.", name);
            end
        end

        function tf = hasRuntimeValue(value)
            if isa(value, "function_handle") || isa(value, "handle")
                tf = true;
            elseif isstruct(value)
                tf = false;
                names = fieldnames(value);
                for element = 1:numel(value)
                    for index = 1:numel(names)
                        if ProjectionTimeVaryingOpkResearch.hasRuntimeValue( ...
                                value(element).(names{index}))
                            tf = true;
                            return
                        end
                    end
                end
            elseif iscell(value)
                tf = any(cellfun(@ProjectionTimeVaryingOpkResearch. ...
                    hasRuntimeValue, value));
            else
                tf = false;
            end
        end
    end
end
