classdef ProjectionDenseSurfaceSyntheticAcceptance
    %ProjectionDenseSurfaceSyntheticAcceptance Run truth-aware alignment evidence.

    properties (Constant)
        Format = "ProjectionDenseSurfaceSyntheticAcceptance"
        Version = 1
    end

    methods (Static)
        function report = runRepeatable(bundle, truth, options)
            %runRepeatable Execute twice and record deterministic agreement.
            if nargin < 3
                options = struct();
            end
            ProjectionDenseSurfaceSyntheticAcceptance.validateBundle(bundle);
            ProjectionDenseSurfaceSyntheticAcceptance.validateTruth(truth);
            options = ProjectionDenseSurfaceSyntheticAcceptance.mergeOptions( ...
                options, bundle);
            images = ProjectionDenseSurfaceSyntheticAcceptance.loadOrUseImages( ...
                bundle, options.Images);
            writeArtifacts = options.WriteArtifacts;
            outputDirectory = options.OutputDirectory;
            options.Images = images;
            options.WriteArtifacts = false;
            first = ProjectionDenseSurfaceSyntheticAcceptance.run( ...
                bundle, truth, options);
            second = ProjectionDenseSurfaceSyntheticAcceptance.run( ...
                bundle, truth, options);
            report = first;
            report.Repeatability = ...
                ProjectionDenseSurfaceSyntheticAcceptance. ...
                repeatabilityMetrics(first, second);
            if writeArtifacts
                report.Artifacts = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.writeArtifacts( ...
                    report, outputDirectory);
            end
        end

        function scene = buildScene(bundle, presetIndex, mode, images)
            %buildScene Create an in-memory viewer scene from reported geometry.
            ProjectionDenseSurfaceSyntheticAcceptance.validateBundle(bundle);
            presetIndex = ...
                ProjectionDenseSurfaceSyntheticAcceptance.validatePresetIndex( ...
                presetIndex, numel(bundle.Presets));
            mode = ProjectionDenseSurfaceSyntheticAcceptance.validateMode(mode);
            variant = ...
                ProjectionDenseSurfaceSyntheticAcceptance.variantForMode( ...
                bundle.Presets(presetIndex), mode);
            if nargin < 4 || isempty(images)
                images = ProjectionDenseSurfaceSyntheticAcceptance.loadImages( ...
                    bundle.ImageReference.ImagePaths);
            else
                images = ProjectionDenseSurfaceSyntheticAcceptance.validateImages( ...
                    images, bundle.ImageReference.ImageSize);
            end
            imagePaths = bundle.ImageReference.ImagePaths;
            if isempty(imagePaths) || all(strlength(imagePaths) == 0)
                imagePaths = "synthetic-view-" + compose("%03d", 1:numel(images));
            end
            geometryArray = [variant.SourceGeometries{:}];
            planeOrigin = mean(reshape( ...
                [geometryArray.NominalSceneCenter], 3, []), 2);
            planeOrigin(3) = 0;
            plane = PlanarProjection.definePlaneFromBasis( ...
                planeOrigin, [1; 0; 0], [0; 1; 0]);
            imageSize = bundle.ImageReference.ImageSize;
            rowStride = max(1, ceil(imageSize(1) / 128));
            columnStride = max(1, ceil(imageSize(2) / 128));
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                images, imagePaths, struct(RowStride=rowStride, ...
                ColumnStride=columnStride, DisplayTextureMaxPixels=1e6));
            for layerIndex = 1:numel(scene.layers)
                layer = scene.layers(layerIndex);
                layer.Name = sprintf("Synthetic view %d (%s, %s)", ...
                    layerIndex, bundle.Presets(presetIndex).Name, mode);
                layer.SourceGeometry = variant.SourceGeometries{layerIndex};
                layer.BaseProjectionPlane = plane;
                layer.CurrentProjectionPlane = plane;
                layer.ViewVectorAngularOffsetsDegrees = zeros(3, 1);
                layer.ImageMetadata.SyntheticAcceptance = struct( ...
                    PresetName=bundle.Presets(presetIndex).Name, ...
                    Mode=mode, TruthIncluded=false);
                scene.layers(layerIndex) = layer;
            end
            scene.layers = ProjectionLayerIdentity.ensureLayers(scene.layers);
            origins = reshape([scene.layers.SourceGeometry], 1, []);
            centers = reshape([origins.NominalSceneCenter], 3, []);
            viewOrigins = reshape([origins.G0], 3, []);
            frameOrigin = mean(viewOrigins, 2);
            frameDirection = mean(centers, 2) - frameOrigin;
            frameDirection = frameDirection / norm(frameDirection);
            scene.frameCamera = PlanarProjection.defineFrameCamera( ...
                frameOrigin, frameDirection, 1, plane);
            scene.renderOrigin = plane.P0;
            scene.SyntheticAcceptance = struct( ...
                Format=ProjectionDenseSurfaceSyntheticAcceptance.Format, ...
                PresetName=bundle.Presets(presetIndex).Name, Mode=mode, ...
                TruthIncluded=false, GeometryRole="reported-only", ...
                ImageSetFingerprint= ...
                bundle.ImageReference.ConfigurationFingerprint);
        end

        function report = run(bundle, truth, options)
            %run Execute alignment and dense extraction with truth diagnostics.
            if nargin < 3
                options = struct();
            end
            ProjectionDenseSurfaceSyntheticAcceptance.validateBundle(bundle);
            ProjectionDenseSurfaceSyntheticAcceptance.validateTruth(truth);
            options = ProjectionDenseSurfaceSyntheticAcceptance.mergeOptions( ...
                options, bundle);
            images = ProjectionDenseSurfaceSyntheticAcceptance.loadOrUseImages( ...
                bundle, options.Images);
            pair = ProjectionDenseSurfaceSyntheticAcceptance.selectPair( ...
                truth, options.PairIndices);
            runCount = numel(options.PresetIndices) * numel(options.Modes);
            records = repmat( ...
                ProjectionDenseSurfaceSyntheticAcceptance.emptyRecord(), 1, runCount);
            reportTimer = tic;
            recordIndex = 0;
            for presetIndex = options.PresetIndices
                for mode = options.Modes
                    recordIndex = recordIndex + 1;
                    scene = ProjectionDenseSurfaceSyntheticAcceptance.buildScene( ...
                        bundle, presetIndex, mode, images);
                    injected = bundle.Presets(presetIndex).Variants(1). ...
                        ConstantOpkDegrees(:, pair);
                    records(recordIndex) = ...
                        ProjectionDenseSurfaceSyntheticAcceptance.runVariant( ...
                        scene, truth, bundle.Presets(presetIndex).Name, mode, ...
                        pair, injected, options);
                end
            end
            imageInfo = whos("images");
            report = struct( ...
                Format=ProjectionDenseSurfaceSyntheticAcceptance.Format, ...
                Version=ProjectionDenseSurfaceSyntheticAcceptance.Version, ...
                Status=ProjectionDenseSurfaceSyntheticAcceptance.reportStatus(records), ...
                ConfigurationFingerprint= ...
                bundle.ImageReference.ConfigurationFingerprint, ...
                PairIndices=pair, PresetNames=[bundle.Presets.Name], ...
                Modes=options.Modes, Runs=records, ...
                GenerationMetrics=options.GenerationMetrics, ...
                RuntimeSeconds=toc(reportTimer), ...
                LoadedImageContainerBytes=imageInfo.bytes, ...
                Repeatability=struct(Status="not-checked", Exact=false, ...
                FirstRunRuntimeSeconds=NaN, SecondRunRuntimeSeconds=NaN), ...
                ThresholdsEstablished=false);
            if options.WriteArtifacts
                report.Artifacts = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.writeArtifacts( ...
                    report, options.OutputDirectory);
            else
                report.Artifacts = struct(ReportMatPath="", ReportJsonPath="");
            end
        end

        function artifacts = writeArtifacts(report, outputDirectory)
            %writeArtifacts Persist compact acceptance evidence.
            outputDirectory = string(outputDirectory);
            if ~isscalar(outputDirectory) || strlength(outputDirectory) == 0
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOutput", ...
                    "Output directory must be a nonempty scalar path.");
            end
            if ~isfolder(outputDirectory)
                mkdir(outputDirectory);
            end
            matPath = string(fullfile(outputDirectory, ...
                "acceptance_evidence.mat"));
            jsonPath = string(fullfile(outputDirectory, ...
                "acceptance_evidence.json"));
            save(matPath, "report", "-v7");
            ProjectionDenseSurfaceSyntheticAcceptance.writeJson(jsonPath, report);
            artifacts = struct(ReportMatPath=matPath, ReportJsonPath=jsonPath);
        end
    end

    methods (Static, Access = private)
        function metrics = repeatabilityMetrics(first, second)
            firstRecords = ...
                ProjectionDenseSurfaceSyntheticAcceptance. ...
                recordsWithoutRuntime(first.Runs);
            secondRecords = ...
                ProjectionDenseSurfaceSyntheticAcceptance. ...
                recordsWithoutRuntime(second.Runs);
            exact = first.ConfigurationFingerprint == ...
                second.ConfigurationFingerprint && ...
                isequal(first.PairIndices, second.PairIndices) && ...
                isequaln(firstRecords, secondRecords);
            if exact
                status = "verified";
            else
                status = "mismatch";
            end
            metrics = struct(Status=status, Exact=exact, ...
                FirstRunRuntimeSeconds=first.RuntimeSeconds, ...
                SecondRunRuntimeSeconds=second.RuntimeSeconds);
        end

        function records = recordsWithoutRuntime(records)
            for recordIndex = 1:numel(records)
                records(recordIndex).RuntimeSeconds = 0;
                records(recordIndex).DenseSurface.RuntimeSeconds = 0;
            end
        end

        function record = runVariant(scene, truth, presetName, mode, ...
                pair, injected, options)
            timer = tic;
            try
                alignmentOptions = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.alignmentOptions( ...
                    options);
                request = ProjectionAlignmentRequest.validate(struct(Scene=scene, ...
                    LayerIndices=pair, ReferenceLayerIndex=pair(2), ...
                    AnalysisBands=[1 1], Options=alignmentOptions));
                working = ProjectionAlignmentWorkingImageRenderer.render( ...
                    scene, request, struct(OutputSize=options.WorkingOutputSize));
                matched = ProjectionAlignmentFeatureMatcher.match( ...
                    working, alignmentOptions);
                filtered = ProjectionAlignmentMatchFilter.filter( ...
                    matched, alignmentOptions, scene);
                solve = ProjectionAlignmentOpkSolver.solve( ...
                    scene, filtered, alignmentOptions);
                solve = ProjectionAlignmentSafeSolvePolicy.apply( ...
                    solve, filtered, alignmentOptions);
                applied = ProjectionAlignmentSafeSolvePolicy.isActionable(solve);
                if applied
                    alignedScene = ...
                        ProjectionAlignmentOpkSolver.applyCorrections(scene, solve);
                else
                    alignedScene = scene;
                end
                pairMatch = filtered.Matches(1);
                denseMetrics = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.runDense( ...
                    alignedScene, request, pairMatch, truth, pair, options);
                truthMetrics = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.sparseTruthMetrics( ...
                    truth, pair, pairMatch);
                recovered = ...
                    ProjectionDenseSurfaceSyntheticAcceptance.recoveredCorrections( ...
                    solve, pair);
                injectedDifferential = injected(:, 1) - injected(:, 2);
                recoveredDifferential = recovered(:, 1) - recovered(:, 2);
                stageCounts = struct(Raw=matched.Matches(1).Count, ...
                    Filtered=pairMatch.Count, ...
                    SolverUsed=sum([solve.SolverObservations.Count]));
                record = struct(PresetName=presetName, Mode=mode, Pair=pair, ...
                    Status="completed", FailureIdentifier="", ...
                    FailureMessage="", StageCounts=stageCounts, ...
                    SpatialCoverageFraction= ...
                    ProjectionDenseSurfaceSyntheticAcceptance.spatialCoverage( ...
                    pairMatch, working.OutputSize), ...
                    AlignmentApplied=applied, SolveStatus=solve.Status, ...
                    Warnings=solve.Warnings, ...
                    InjectedConstantOpkDegrees=injected, ...
                    RecoveredCorrectionDegrees=recovered, ...
                    AbsoluteLayerRecoveryErrorDegrees=recovered + injected, ...
                    InjectedDifferentialOpkDegrees=injectedDifferential, ...
                    RecoveredDifferentialCorrectionDegrees= ...
                    recoveredDifferential, ...
                    DifferentialRecoveryErrorDegrees= ...
                    recoveredDifferential + injectedDifferential, ...
                    TruthCorrespondence=truthMetrics, ...
                    ForwardRay=struct(RmsBefore= ...
                    solve.Diagnostics.Comparison.ForwardRay3D.RmsBefore, ...
                    RmsAfter=solve.Diagnostics.Comparison.ForwardRay3D.RmsAfter), ...
                    ResidualColumnStructure= ...
                    ProjectionDenseSurfaceSyntheticAcceptance.residualColumnMetrics( ...
                    pairMatch, solve.Diagnostics.Comparison.ForwardRay3D.ResidualsAfter), ...
                    DenseSurface=denseMetrics, RuntimeSeconds=toc(timer));
            catch exception
                record = ProjectionDenseSurfaceSyntheticAcceptance.emptyRecord();
                record.PresetName = presetName;
                record.Mode = mode;
                record.Pair = pair;
                record.Status = "failed";
                record.FailureIdentifier = string(exception.identifier);
                record.FailureMessage = string(exception.message);
                record.RuntimeSeconds = toc(timer);
            end
        end

        function metrics = runDense( ...
                scene, request, pairMatch, truth, pair, options)
            if ~options.RunDense || exist("disparitySGM", "file") ~= 2 || ...
                    pairMatch.Count < 3
                metrics = struct(Status="not-run", ValidCount=0, ...
                    MutuallyVisibleCount=0, OcclusionExcludedCount=0, ...
                    HeightRmsMeters=NaN, HeightMedianMeters=NaN, ...
                    HeightP95Meters=NaN, RaySeparationP95Meters=NaN, ...
                    RuntimeSeconds=0);
                return
            end
            timer = tic;
            request.Scene = scene;
            request = ProjectionAlignmentRequest.validate(request);
            working = ProjectionAlignmentWorkingImageRenderer.render( ...
                scene, request, struct(OutputSize=options.WorkingOutputSize));
            dense = ProjectionDenseSurfaceExtractor.extract( ...
                scene, working.PairWorkingImages(1), pairMatch, ...
                options.DenseOptions);
            surface = dense.Surface;
            valid = surface.ValidMask;
            movingRows = surface.MovingSourceRows(valid);
            movingColumns = surface.MovingSourceColumns(valid);
            referenceRows = surface.ReferenceSourceRows(valid);
            referenceColumns = surface.ReferenceSourceColumns(valid);
            [movingTruth, movingStatus] = ...
                ProjectionDenseSurfaceSyntheticTruth.intersectObservations( ...
                truth, pair(1), movingRows, movingColumns);
            [referenceOrigins, ~] = ...
                ProjectionDenseSurfaceSyntheticTruth.sampleRays( ...
                truth, pair(2), referenceRows, referenceColumns);
            referenceVisibility = ...
                ProjectionDenseSurfaceSyntheticTerrain.classifyVisibility( ...
                truth.Terrain, referenceOrigins, movingTruth, 0.1);
            mutual = movingStatus == "visibleTerrain" & ...
                referenceVisibility == "visibleTerrain";
            reconstructedHeight = surface.HeightMeters(valid);
            heightError = reconstructedHeight(mutual) - movingTruth(3, mutual).';
            raySeparation = surface.RaySeparationMeters(valid);
            metrics = struct(Status=dense.Status, ValidCount=nnz(valid), ...
                MutuallyVisibleCount=nnz(mutual), ...
                OcclusionExcludedCount=nnz(~mutual), ...
                HeightRmsMeters=ProjectionDenseSurfaceSyntheticAcceptance.rmsOrNaN( ...
                heightError), ...
                HeightMedianMeters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.medianOrNaN(heightError), ...
                HeightP95Meters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.percentileOrNaN( ...
                abs(heightError), 95), ...
                RaySeparationP95Meters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.percentileOrNaN( ...
                raySeparation, 95), RuntimeSeconds=toc(timer));
        end

        function metrics = sparseTruthMetrics(truth, pair, pairMatch)
            [movingPoints, movingStatus] = ...
                ProjectionDenseSurfaceSyntheticTruth.intersectObservations( ...
                truth, pair(1), pairMatch.MovingSourceRows, ...
                pairMatch.MovingSourceColumns);
            [referencePoints, referenceStatus] = ...
                ProjectionDenseSurfaceSyntheticTruth.intersectObservations( ...
                truth, pair(2), pairMatch.ReferenceSourceRows, ...
                pairMatch.ReferenceSourceColumns);
            [movingOrigins, ~] = ...
                ProjectionDenseSurfaceSyntheticTruth.sampleRays( ...
                truth, pair(1), pairMatch.MovingSourceRows, ...
                pairMatch.MovingSourceColumns);
            [referenceOrigins, ~] = ...
                ProjectionDenseSurfaceSyntheticTruth.sampleRays( ...
                truth, pair(2), pairMatch.ReferenceSourceRows, ...
                pairMatch.ReferenceSourceColumns);
            movingFromReference = ...
                ProjectionDenseSurfaceSyntheticTerrain.classifyVisibility( ...
                truth.Terrain, referenceOrigins, movingPoints, 0.1);
            referenceFromMoving = ...
                ProjectionDenseSurfaceSyntheticTerrain.classifyVisibility( ...
                truth.Terrain, movingOrigins, referencePoints, 0.1);
            mutual = movingStatus == "visibleTerrain" & ...
                referenceStatus == "visibleTerrain" & ...
                movingFromReference == "visibleTerrain" & ...
                referenceFromMoving == "visibleTerrain";
            separations = vecnorm(movingPoints - referencePoints, 2, 1);
            validSeparations = separations(mutual);
            metrics = struct(Count=pairMatch.Count, ...
                MutuallyVisibleCount=nnz(mutual), ...
                OcclusionExcludedCount=nnz(~mutual), ...
                MedianSeparationMeters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.medianOrNaN( ...
                validSeparations), ...
                P95SeparationMeters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.percentileOrNaN( ...
                validSeparations, 95), ...
                MaximumSeparationMeters= ...
                ProjectionDenseSurfaceSyntheticAcceptance.maxOrNaN( ...
                validSeparations));
        end

        function corrections = recoveredCorrections(solve, pair)
            corrections = zeros(3, numel(pair));
            for pairIndex = 1:numel(pair)
                match = find([solve.SolvedCorrections.LayerIndex] == ...
                    pair(pairIndex), 1, "first");
                if ~isempty(match)
                    corrections(:, pairIndex) = reshape( ...
                        solve.SolvedCorrections(match). ...
                        ViewVectorAngularOffsetsDegrees, 3, 1);
                end
            end
        end

        function metrics = residualColumnMetrics(pairMatch, residuals)
            columns = 0.5 * (double(pairMatch.MovingSourceColumns(:)) + ...
                double(pairMatch.ReferenceSourceColumns(:)));
            residuals = double(residuals(:));
            count = min(numel(columns), numel(residuals));
            columns = columns(1:count);
            residuals = residuals(1:count);
            if count < 2 || std(columns) <= eps || any(~isfinite(residuals))
                metrics = struct(Count=count, SlopePerColumn=NaN, ...
                    Correlation=NaN);
                return
            end
            coefficients = polyfit(columns, residuals, 1);
            correlation = corrcoef(columns, residuals);
            metrics = struct(Count=count, ...
                SlopePerColumn=coefficients(1), ...
                Correlation=correlation(1, 2));
        end

        function fraction = spatialCoverage(pairMatch, outputSize)
            points = double(pairMatch.MovingFeatureLocations);
            if size(points, 1) < 2
                fraction = 0;
                return
            end
            extent = max(points, [], 1) - min(points, [], 1);
            fraction = prod(extent ./ max(fliplr(outputSize) - 1, 1));
            fraction = min(max(fraction, 0), 1);
        end

        function options = alignmentOptions(options)
            if ~isempty(options.AlignmentOptions)
                options = ProjectionAlignmentOptions.validate( ...
                    options.AlignmentOptions);
                return
            end
            options = ProjectionAlignmentOptions.validate(struct( ...
                Detector=struct(Method=options.DetectorMethod, ...
                MaxFeatures=options.MaximumFeatures, MaskSupportRadiusPixels=0), ...
                Matcher=struct(MaxRatio=0.95), LossMode=options.LossMode, ...
                MovableParameters=struct(AllowReferenceMotion=false), ...
                FilterPipeline=struct(Stages="geometricOutlier", ...
                GeometricMethod="similarity", ...
                NativeDisplacementMethod="none", CoplanarityMethod="none")));
        end

        function options = mergeOptions(options, bundle)
            if nargin < 1 || isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "Acceptance options must be a scalar struct.");
            end
            defaults = struct(PresetIndices=1:numel(bundle.Presets), ...
                Modes=ProjectionDenseSurfaceSyntheticNavigation.ModeNames, ...
                PairIndices=[], WorkingOutputSize=[512 512], ...
                DetectorMethod="kaze", MaximumFeatures=2000, ...
                LossMode="projectionPlane2D", RunDense=true, ...
                DenseOptions=struct(UniquenessThreshold=10, ...
                MaximumSurfacePoints=100000), AlignmentOptions=[], ...
                Images={cell(1, 0)}, WriteArtifacts=false, OutputDirectory="", ...
                GenerationMetrics=struct());
            names = fieldnames(options);
            if any(~ismember(string(names), string(fieldnames(defaults))))
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "Acceptance options contain an unsupported field.");
            end
            for fieldIndex = 1:numel(names)
                defaults.(names{fieldIndex}) = options.(names{fieldIndex});
            end
            defaults.PresetIndices = unique(double(defaults.PresetIndices(:).'), ...
                "stable");
            if isempty(defaults.PresetIndices) || ...
                    any(fix(defaults.PresetIndices) ~= defaults.PresetIndices) || ...
                    any(defaults.PresetIndices < 1) || ...
                    any(defaults.PresetIndices > numel(bundle.Presets))
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "PresetIndices must select available presets.");
            end
            defaults.Modes = string(defaults.Modes(:).');
            if isempty(defaults.Modes) || any(~ismember(defaults.Modes, ...
                    ProjectionDenseSurfaceSyntheticNavigation.ModeNames))
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "Modes must select approved acceptance modes.");
            end
            if ~isempty(defaults.PairIndices)
                defaults.PairIndices = double(defaults.PairIndices(:).');
                if numel(defaults.PairIndices) ~= 2 || ...
                        any(fix(defaults.PairIndices) ~= defaults.PairIndices) || ...
                        any(defaults.PairIndices < 1) || ...
                        any(defaults.PairIndices > numel(bundle.ImageReference.ImagePaths)) || ...
                        defaults.PairIndices(1) == defaults.PairIndices(2)
                    error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                        "PairIndices must select two distinct image views.");
                end
            end
            defaults.WorkingOutputSize = ...
                ProjectionDenseSurfaceSyntheticAcceptance.outputSize( ...
                defaults.WorkingOutputSize);
            defaults.DetectorMethod = lower(string(defaults.DetectorMethod));
            defaults.MaximumFeatures = ...
                ProjectionDenseSurfaceSyntheticAcceptance.positiveInteger( ...
                defaults.MaximumFeatures, "MaximumFeatures");
            defaults.LossMode = string(defaults.LossMode);
            if ~islogical(defaults.RunDense) || ~isscalar(defaults.RunDense) || ...
                    ~islogical(defaults.WriteArtifacts) || ...
                    ~isscalar(defaults.WriteArtifacts)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "RunDense and WriteArtifacts must be logical scalars.");
            end
            defaults.OutputDirectory = string(defaults.OutputDirectory);
            if defaults.WriteArtifacts && ...
                    (~isscalar(defaults.OutputDirectory) || ...
                    strlength(defaults.OutputDirectory) == 0)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "OutputDirectory is required when writing artifacts.");
            end
            options = defaults;
        end

        function pair = selectPair(truth, requested)
            if ~isempty(requested)
                pair = requested;
                return
            end
            bands = [truth.Views.SourceBand];
            bestDistance = Inf;
            pair = [];
            for firstIndex = 1:(numel(bands) - 1)
                for secondIndex = (firstIndex + 1):numel(bands)
                    distance = secondIndex - firstIndex;
                    if bands(firstIndex) == bands(secondIndex) && ...
                            distance < bestDistance
                        pair = [firstIndex secondIndex];
                        bestDistance = distance;
                    end
                end
            end
            if isempty(pair)
                firstIndex = max(1, floor(numel(bands) / 2));
                pair = [firstIndex min(firstIndex + 1, numel(bands))];
            end
        end

        function images = loadOrUseImages(bundle, images)
            if isempty(images)
                images = ProjectionDenseSurfaceSyntheticAcceptance.loadImages( ...
                    bundle.ImageReference.ImagePaths);
            else
                images = ProjectionDenseSurfaceSyntheticAcceptance.validateImages( ...
                    images, bundle.ImageReference.ImageSize);
            end
        end

        function images = loadImages(paths)
            paths = string(paths);
            if isempty(paths) || any(strlength(paths) == 0) || any(~isfile(paths))
                error("ProjectionDenseSurfaceSyntheticAcceptance:missingImages", ...
                    "Every shared truth image path must exist.");
            end
            images = cell(1, numel(paths));
            for imageIndex = 1:numel(paths)
                images{imageIndex} = imread(paths(imageIndex));
            end
        end

        function images = validateImages(images, imageSize)
            if ~iscell(images) || isempty(images)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidImages", ...
                    "Images must be a nonempty cell array.");
            end
            for imageIndex = 1:numel(images)
                image = images{imageIndex};
                if ~(isnumeric(image) || islogical(image)) || ...
                        ~isequal([size(image, 1) size(image, 2)], imageSize) || ...
                        size(image, 3) ~= 1
                    error("ProjectionDenseSurfaceSyntheticAcceptance:invalidImages", ...
                        "Every acceptance image must be a matching single-band image.");
                end
            end
            images = reshape(images, 1, []);
        end

        function variant = variantForMode(preset, mode)
            matches = string([preset.Variants.Mode]) == mode;
            if nnz(matches) ~= 1
                error("ProjectionDenseSurfaceSyntheticAcceptance:missingVariant", ...
                    "Preset does not contain the requested mode.");
            end
            variant = preset.Variants(find(matches, 1, "first"));
        end

        function status = reportStatus(records)
            if all(string({records.Status}) == "completed")
                status = "complete";
            elseif any(string({records.Status}) == "completed")
                status = "partial";
            else
                status = "failed";
            end
        end

        function value = medianOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = median(values);
            end
        end

        function value = percentileOrNaN(values, percentile)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = prctile(values, percentile);
            end
        end

        function value = rmsOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = sqrt(mean(values.^2));
            end
        end

        function value = maxOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = max(values);
            end
        end

        function writeJson(path, value)
            fileId = fopen(path, "w");
            if fileId < 0
                error("ProjectionDenseSurfaceSyntheticAcceptance:outputOpenFailed", ...
                    "Could not open acceptance JSON output for writing.");
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", jsonencode(value, ...
                PrettyPrint=true, ConvertInfAndNaN=true));
            clear cleanup
        end

        function validateBundle(bundle)
            if ~isstruct(bundle) || ~isscalar(bundle) || ...
                    ~isfield(bundle, "Format") || ...
                    string(bundle.Format) ~= ...
                    ProjectionDenseSurfaceSyntheticNavigation.Format || ...
                    ~isfield(bundle, "ImagesDuplicated") || bundle.ImagesDuplicated || ...
                    isfield(bundle, "Images")
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidBundle", ...
                    "Acceptance requires image-free navigation variants.");
            end
        end

        function validateTruth(truth)
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    ~isfield(truth, "Format") || ...
                    string(truth.Format) ~= ProjectionDenseSurfaceSyntheticTruth.Format
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidTruth", ...
                    "Acceptance truth must come from the synthetic truth model.");
            end
        end

        function index = validatePresetIndex(index, count)
            if ~isnumeric(index) || ~isscalar(index) || ~isfinite(index) || ...
                    fix(index) ~= index || index < 1 || index > count
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidPreset", ...
                    "Preset index must select one navigation preset.");
            end
            index = double(index);
        end

        function mode = validateMode(mode)
            mode = string(mode);
            if ~isscalar(mode) || ~ismember(mode, ...
                    ProjectionDenseSurfaceSyntheticNavigation.ModeNames)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidMode", ...
                    "Mode must select an approved acceptance mode.");
            end
        end

        function sizeValue = outputSize(sizeValue)
            if ~isnumeric(sizeValue) || ~isvector(sizeValue) || ...
                    ~ismember(numel(sizeValue), [1 2]) || ...
                    any(~isfinite(sizeValue)) || any(sizeValue < 32) || ...
                    any(fix(sizeValue) ~= sizeValue)
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "WorkingOutputSize must contain one or two integers of at least 32.");
            end
            sizeValue = double(sizeValue(:).');
            if isscalar(sizeValue)
                sizeValue = [sizeValue sizeValue];
            end
        end

        function value = positiveInteger(value, name)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 1 || fix(value) ~= value
                error("ProjectionDenseSurfaceSyntheticAcceptance:invalidOptions", ...
                    "%s must be a positive integer.", name);
            end
            value = double(value);
        end

        function record = emptyRecord()
            record = struct(PresetName="", Mode="", Pair=zeros(1, 2), ...
                Status="not-run", FailureIdentifier="", FailureMessage="", ...
                StageCounts=struct(Raw=0, Filtered=0, SolverUsed=0), ...
                SpatialCoverageFraction=0, AlignmentApplied=false, ...
                SolveStatus="not-run", Warnings=strings(1, 0), ...
                InjectedConstantOpkDegrees=zeros(3, 2), ...
                RecoveredCorrectionDegrees=zeros(3, 2), ...
                AbsoluteLayerRecoveryErrorDegrees=zeros(3, 2), ...
                InjectedDifferentialOpkDegrees=zeros(3, 1), ...
                RecoveredDifferentialCorrectionDegrees=zeros(3, 1), ...
                DifferentialRecoveryErrorDegrees=zeros(3, 1), ...
                TruthCorrespondence=struct(Count=0, MutuallyVisibleCount=0, ...
                OcclusionExcludedCount=0, MedianSeparationMeters=NaN, ...
                P95SeparationMeters=NaN, MaximumSeparationMeters=NaN), ...
                ForwardRay=struct(RmsBefore=NaN, RmsAfter=NaN), ...
                ResidualColumnStructure=struct(Count=0, ...
                SlopePerColumn=NaN, Correlation=NaN), ...
                DenseSurface=struct(Status="not-run", ValidCount=0, ...
                MutuallyVisibleCount=0, OcclusionExcludedCount=0, ...
                HeightRmsMeters=NaN, HeightMedianMeters=NaN, ...
                HeightP95Meters=NaN, RaySeparationP95Meters=NaN, ...
                RuntimeSeconds=0), RuntimeSeconds=0);
        end
    end
end
