classdef ProjectionDemCorrectionAdapter
    %ProjectionDemCorrectionAdapter Bind S7 proposals to live scene geometry.

    methods (Static)
        function correctionSet = bind(scene, registration, options)
            %bind Create a scene-compatible proposed B8 position correction.
            if nargin < 3
                options = struct();
            end
            scene = ProjectionViewMetadata.ensureScene(scene);
            options = ProjectionDemCorrectionAdapter.validateOptions(options);
            source = ProjectionDemCorrectionAdapter.sourceCorrection( ...
                registration);
            [translation, sourceFrame, scopeViewIds] = ...
                ProjectionDemCorrectionAdapter.sourcePlan(source, options);
            ProjectionDemCorrectionAdapter.validateScope( ...
                scene, source, scopeViewIds);
            sceneFrame = ProjectionDemCorrectionAdapter.sceneFrame( ...
                scene, scopeViewIds, options.SceneWorldFrame);
            if sourceFrame ~= sceneFrame
                error("ProjectionDemCorrectionAdapter:frameMismatch", ...
                    "DEM correction frame %s does not match scene frame %s.", ...
                    sourceFrame, sceneFrame);
            end
            parentFingerprints = ProjectionGeometryFingerprint.scene(scene);
            correctedScene = ProjectionDemCorrectionAdapter.translateScene( ...
                scene, scopeViewIds, translation);
            correctedFingerprints = ...
                ProjectionGeometryFingerprint.scene(correctedScene);
            views = ProjectionDemCorrectionAdapter.views( ...
                scene, correctedScene, scopeViewIds);
            passes = ProjectionDemCorrectionAdapter.passes( ...
                views, translation);
            blocks = source.Blocks;
            blockTypes = string({blocks.Type});
            translationIndex = find( ...
                blockTypes == "globalPositionTranslation", 1, "first");
            blocks(translationIndex).Semantics = ...
                "imageryToDemExplicitPositionCorrection";
            identity = struct(SourceGenerationId=source.GenerationId, ...
                ParentGenerationId=options.ParentGenerationId, ...
                ParentFingerprints=parentFingerprints, ...
                TranslationMeters=translation, SceneWorldFrame=sceneFrame);
            generationId = options.GenerationId;
            if strlength(generationId) == 0
                generationId = "dem-position-" + extractBefore( ...
                    ProjectionGeometryFingerprint.hash(identity), 17);
            end
            data = source.toStruct();
            data.GenerationId = generationId;
            data.ParentGenerationId = options.ParentGenerationId;
            data.Lifecycle = "proposed";
            data.Views = views;
            data.Passes = passes;
            data.Blocks = blocks;
            data.Geometry = struct( ...
                FingerprintAlgorithm=ProjectionGeometryFingerprint.Algorithm, ...
                CanonicalizationVersion= ...
                ProjectionGeometryFingerprint.CanonicalizationVersion, ...
                SceneWorldFrame=sceneFrame, ScopeViewIds=scopeViewIds, ...
                SourcePointSetGenerationId=blocks(translationIndex).TargetId, ...
                SourceRegistrationGenerationId=source.GenerationId, ...
                Parent=parentFingerprints, Corrected=correctedFingerprints, ...
                InvalidationManifest= ...
                ProjectionDemCorrectionAdapter.invalidationManifest());
            data.Provenance.Source = "demRegistrationExplicitPositionApply";
            data.Provenance.SourceRegistrationGenerationId = ...
                source.GenerationId;
            data.Provenance.SceneBindingFingerprint = ...
                ProjectionGeometryFingerprint.hash(identity);
            data.Provenance.AutoApplied = false;
            data.Diagnostics.AutoApply = false;
            data.Diagnostics.RequiresExplicitB8Apply = false;
            data.Diagnostics.ExplicitPositionApplyPrepared = true;
            data.Diagnostics.AllowAmbiguous = options.AllowAmbiguous;
            data.Diagnostics.RegistrationStatus = ...
                ProjectionDemCorrectionAdapter.registrationStatus(source);
            data.Diagnostics.InvalidationManifest = ...
                ProjectionDemCorrectionAdapter.invalidationManifest();
            correctionSet = ProjectionCorrectionSet.create(data);
            ProjectionDemCorrectionAdapter.applicationPlan(correctionSet);
        end

        function plan = applicationPlan(correctionSet)
            %applicationPlan Validate and return a typed B8 translation plan.
            correctionSet = ProjectionCorrectionSet.create(correctionSet);
            blockTypes = string({correctionSet.Blocks.Type});
            indices = find(blockTypes == "globalPositionTranslation");
            if isempty(indices)
                plan = struct(Available=false, ...
                    TranslationWorldMeters=zeros(3, 1), ...
                    SceneWorldFrame="", ScopeViewIds=strings(1, 0), ...
                    SourcePointSetGenerationId="");
                return
            end
            if numel(indices) ~= 1 || ...
                    any(~ismember(blockTypes, [ ...
                    "globalPositionTranslation" ...
                    "globalPositionTranslationCovariance"]))
                error("ProjectionDemCorrectionAdapter:unsupportedBlocks", ...
                    "B8 supports one global translation and optional covariance only.");
            end
            block = correctionSet.Blocks(indices);
            requiredGeometry = ["SceneWorldFrame" "ScopeViewIds" ...
                "SourcePointSetGenerationId" "InvalidationManifest"];
            if any(~isfield(correctionSet.Geometry, requiredGeometry)) || ...
                    ~isfield(correctionSet.Diagnostics, ...
                    "ExplicitPositionApplyPrepared") || ...
                    ~isequal(correctionSet.Diagnostics. ...
                    ExplicitPositionApplyPrepared, true) || ...
                    ~isfield(correctionSet.Diagnostics, "AutoApply") || ...
                    correctionSet.Diagnostics.AutoApply
                error("ProjectionDemCorrectionAdapter:unboundProposal", ...
                    "DEM translation must be explicitly bound to live scene geometry.");
            end
            sceneFrame = string(correctionSet.Geometry.SceneWorldFrame);
            scopeViewIds = reshape(string( ...
                correctionSet.Geometry.ScopeViewIds), 1, []);
            sourceGeneration = string( ...
                correctionSet.Geometry.SourcePointSetGenerationId);
            if ~isscalar(sceneFrame) || strlength(sceneFrame) == 0 || ...
                    isempty(scopeViewIds) || ...
                    numel(unique(scopeViewIds)) ~= numel(scopeViewIds) || ...
                    ~isequal(sort(scopeViewIds), ...
                    sort(string({correctionSet.Views.ViewId}))) || ...
                    string(block.Scope) ~= "network" || ...
                    string(block.Units) ~= "meters" || ...
                    string(block.Frame) ~= sceneFrame || ...
                    string(block.Semantics) ~= ...
                    "imageryToDemExplicitPositionCorrection" || ...
                    string(block.TargetId) ~= sourceGeneration || ...
                    ~isnumeric(block.Values) || numel(block.Values) ~= 3 || ...
                    any(~isfinite(block.Values))
                error("ProjectionDemCorrectionAdapter:invalidTranslationBlock", ...
                    "Bound DEM translation frame, scope, units, or values are invalid.");
            end
            for view = correctionSet.Views
                if norm(view.IncrementRotationMatrix - eye(3), "fro") > 1e-12 || ...
                        norm(view.ParentRotationMatrix - ...
                        view.EffectiveRotationMatrix, "fro") > 1e-12 || ...
                        ~isequal(view.ParentProjectionOffsetMeters, ...
                        view.EffectiveProjectionOffsetMeters)
                    error("ProjectionDemCorrectionAdapter:positionOnly", ...
                        "B8 cannot combine position and attitude/plane corrections.");
                end
            end
            plan = struct(Available=true, ...
                TranslationWorldMeters=reshape(double(block.Values), 3, 1), ...
                SceneWorldFrame=sceneFrame, ScopeViewIds=scopeViewIds, ...
                SourcePointSetGenerationId=sourceGeneration);
        end

        function effects = effects(correctionSet, transition)
            %effects Return portable invalidation/recompute evidence.
            plan = ProjectionDemCorrectionAdapter.applicationPlan(correctionSet);
            if ~plan.Available
                effects = struct(Kind="none", Transition=string(transition), ...
                    GeometryChanged=false, InvalidatedProducts=strings(1, 0), ...
                    RequiredRecomputation=strings(1, 0), ...
                    RecomputeRequired=false, ScopeViewIds=strings(1, 0), ...
                    SourcePointSetGenerationId="");
                return
            end
            manifest = ProjectionDemCorrectionAdapter.invalidationManifest();
            effects = struct(Kind="demPositionCorrection", ...
                Transition=string(transition), GeometryChanged=true, ...
                InvalidatedProducts=manifest.InvalidatedProducts, ...
                RequiredRecomputation=manifest.RequiredRecomputation, ...
                RecomputeRequired=true, ScopeViewIds=plan.ScopeViewIds, ...
                SourcePointSetGenerationId= ...
                plan.SourcePointSetGenerationId);
        end

        function manifest = invalidationManifest()
            %invalidationManifest Define geometry-dependent B8 invalidation.
            manifest = struct(InvalidatedProducts=[ ...
                "rawMatches" "filteredMatches" "alignmentSolve" ...
                "denseObservations" "multiRayPoints" "fusionProducts" ...
                "surfaceProducts" "demRegistration"], ...
                RequiredRecomputation=["alignmentMatch" ...
                "alignmentFilter" "alignmentSolve" "denseReconstruction" ...
                "surfaceFusion" "demRegistration"], ...
                RecomputeRequired=true, RegisteredPreviewReusable=false, ...
                DemEvidenceReusableAsIndependentValidation=false);
        end
    end

    methods (Static, Access = private)
        function options = validateOptions(options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionDemCorrectionAdapter:invalidOptions", ...
                    "B8 binding options must be a scalar struct.");
            end
            defaults = struct(ParentGenerationId="", ...
                SceneWorldFrame="", AllowAmbiguous=false, GenerationId="");
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionDemCorrectionAdapter:invalidOptions", ...
                    "Unexpected B8 binding option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            defaults.ParentGenerationId = ...
                ProjectionDemCorrectionAdapter.requiredString( ...
                defaults.ParentGenerationId, "ParentGenerationId");
            defaults.SceneWorldFrame = ...
                ProjectionDemCorrectionAdapter.optionalString( ...
                defaults.SceneWorldFrame, "SceneWorldFrame");
            defaults.GenerationId = ...
                ProjectionDemCorrectionAdapter.optionalString( ...
                defaults.GenerationId, "GenerationId");
            if ~islogical(defaults.AllowAmbiguous) || ...
                    ~isscalar(defaults.AllowAmbiguous)
                error("ProjectionDemCorrectionAdapter:invalidOptions", ...
                    "AllowAmbiguous must be a logical scalar.");
            end
            options = defaults;
        end

        function correction = sourceCorrection(registration)
            if isstruct(registration) && isscalar(registration) && ...
                    isfield(registration, "CorrectionSetData")
                if ~isfield(registration, "Format") || ...
                        string(registration.Format) ~= ...
                        ProjectionSurfaceRegistrationResult.Format || ...
                        ~isfield(registration, "Status")
                    error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                        "Registration result identity is invalid.");
                end
                correction = ProjectionCorrectionSet.create( ...
                    registration.CorrectionSetData);
                if ProjectionDemCorrectionAdapter.registrationStatus( ...
                        correction) ~= string(registration.Status)
                    error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                        "Registration result and correction status disagree.");
                end
            else
                correction = ProjectionCorrectionSet.create(registration);
            end
            if correction.Lifecycle ~= "proposed" || ...
                    ~correction.Failure.Valid || ...
                    ~isfield(correction.Provenance, "Source") || ...
                    string(correction.Provenance.Source) ~= "demRegistration" || ...
                    ~isfield(correction.Diagnostics, ...
                    "RequiresExplicitB8Apply") || ...
                    ~isequal(correction.Diagnostics. ...
                    RequiresExplicitB8Apply, true) || ...
                    ~isfield(correction.Diagnostics, "AutoApply") || ...
                    correction.Diagnostics.AutoApply
                error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                    "B8 requires a valid preview-only S7 DEM proposal.");
            end
        end

        function [translation, frame, scopeViewIds] = ...
                sourcePlan(correction, options)
            status = ProjectionDemCorrectionAdapter.registrationStatus( ...
                correction);
            if status == "ambiguous" && ~options.AllowAmbiguous
                error("ProjectionDemCorrectionAdapter:ambiguousRegistration", ...
                    "Ambiguous DEM registration requires explicit override.");
            end
            if ~ismember(status, ["succeeded" "ambiguous"])
                error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                    "Only successful or explicitly accepted ambiguous registration applies.");
            end
            types = string({correction.Blocks.Type});
            translationIndex = find(types == "globalPositionTranslation");
            if numel(translationIndex) ~= 1 || ...
                    any(~ismember(types, ["globalPositionTranslation" ...
                    "globalPositionTranslationCovariance"]))
                error("ProjectionDemCorrectionAdapter:unsupportedBlocks", ...
                    "S7 proposal must contain only global translation and covariance.");
            end
            block = correction.Blocks(translationIndex);
            if string(block.Scope) ~= "network" || ...
                    string(block.Units) ~= "meters" || ...
                    ~isnumeric(block.Values) || numel(block.Values) ~= 3 || ...
                    any(~isfinite(block.Values))
                error("ProjectionDemCorrectionAdapter:invalidTranslationBlock", ...
                    "S7 global translation scope, units, or values are invalid.");
            end
            translation = reshape(double(block.Values), 3, 1);
            frame = ProjectionDemCorrectionAdapter.requiredString( ...
                block.Frame, "translation frame");
            if ~isfield(correction.Geometry, "ScopeViewIds")
                error("ProjectionDemCorrectionAdapter:invalidScope", ...
                    "S7 proposal must declare its complete view scope.");
            end
            scopeViewIds = reshape(string( ...
                correction.Geometry.ScopeViewIds), 1, []);
            if isempty(scopeViewIds) || ...
                    numel(unique(scopeViewIds)) ~= numel(scopeViewIds) || ...
                    ~isequal(sort(scopeViewIds), ...
                    sort(string({correction.Views.ViewId})))
                error("ProjectionDemCorrectionAdapter:invalidScope", ...
                    "S7 correction view records and declared scope disagree.");
            end
        end

        function frame = sceneFrame(scene, scopeViewIds, configuredFrame)
            frames = strings(1, 0);
            for viewId = scopeViewIds
                index = ProjectionViewMetadata.indexForId(scene, viewId);
                source = scene.layers(index).SourceGeometry;
                if isfield(source, "CoordinateFrame") && ...
                        strlength(string(source.CoordinateFrame)) > 0
                    frames(end + 1) = string(source.CoordinateFrame); %#ok<AGROW>
                end
            end
            frames = unique(frames);
            if strlength(configuredFrame) > 0
                frame = configuredFrame;
                if ~isempty(frames) && any(frames ~= frame)
                    error("ProjectionDemCorrectionAdapter:frameMismatch", ...
                        "Scoped source geometry does not use SceneWorldFrame %s.", ...
                        frame);
                end
            elseif isscalar(frames)
                frame = frames;
            else
                error("ProjectionDemCorrectionAdapter:missingSceneFrame", ...
                    "SceneWorldFrame is required when scoped source frames are absent or mixed.");
            end
        end

        function validateScope(scene, correction, scopeViewIds)
            for viewId = scopeViewIds
                record = correction.Views( ...
                    string({correction.Views.ViewId}) == viewId);
                try
                    index = ProjectionViewMetadata.indexForId(scene, viewId);
                catch exception
                    error("ProjectionDemCorrectionAdapter:missingView", ...
                        "%s", exception.message);
                end
                if numel(record) ~= 1 || ...
                        record.PassId ~= string(scene.layers(index).PassId)
                    error("ProjectionDemCorrectionAdapter:passMismatch", ...
                        "View %s does not match the DEM proposal pass scope.", ...
                        viewId);
                end
            end
        end

        function scene = translateScene(scene, scopeViewIds, translation)
            for viewId = scopeViewIds
                index = ProjectionViewMetadata.indexForId(scene, viewId);
                scene.layers(index).SourceGeometry = ...
                    ProjectionSourceGeometry.translateOrigins( ...
                    scene.layers(index).SourceGeometry, translation);
            end
        end

        function views = views(scene, correctedScene, scopeViewIds)
            template = struct(ViewId="", PassId="", LayerId="", ...
                ParentAttitudeRadians=zeros(1, 3), ...
                EffectiveAttitudeRadians=zeros(1, 3), ...
                CommonAttitudeRadians=zeros(1, 3), ...
                DifferentialAttitudeRadians=zeros(1, 3), ...
                ParentRotationMatrix=eye(3), ...
                IncrementRotationMatrix=eye(3), ...
                EffectiveRotationMatrix=eye(3), ...
                IncrementRotationVectorRadians=zeros(1, 3), ...
                ParentProjectionOffsetMeters=zeros(1, 2), ...
                EffectiveProjectionOffsetMeters=zeros(1, 2), ...
                BaseGeometryFingerprint="", ...
                ParentGeometryFingerprint="", ...
                CorrectedGeometryFingerprint="");
            views = repmat(template, 1, numel(scopeViewIds));
            for index = 1:numel(scopeViewIds)
                viewId = scopeViewIds(index);
                layerIndex = ProjectionViewMetadata.indexForId(scene, viewId);
                layer = scene.layers(layerIndex);
                correctedLayer = correctedScene.layers(layerIndex);
                [rotation, radians] = ProjectionMeshBuilder. ...
                    viewVectorRotation(layer, layer.CurrentProjectionPlane);
                views(index) = struct(ViewId=viewId, ...
                    PassId=string(layer.PassId), ...
                    LayerId=string(layer.LayerId), ...
                    ParentAttitudeRadians=reshape(radians, 1, 3), ...
                    EffectiveAttitudeRadians=reshape(radians, 1, 3), ...
                    CommonAttitudeRadians=zeros(1, 3), ...
                    DifferentialAttitudeRadians=zeros(1, 3), ...
                    ParentRotationMatrix=rotation, ...
                    IncrementRotationMatrix=eye(3), ...
                    EffectiveRotationMatrix=rotation, ...
                    IncrementRotationVectorRadians=zeros(1, 3), ...
                    ParentProjectionOffsetMeters=reshape(double( ...
                    layer.ProjectionOffsetMeters), 1, 2), ...
                    EffectiveProjectionOffsetMeters=reshape(double( ...
                    layer.ProjectionOffsetMeters), 1, 2), ...
                    BaseGeometryFingerprint= ...
                    ProjectionGeometryFingerprint.layer(layer), ...
                    ParentGeometryFingerprint= ...
                    ProjectionGeometryFingerprint.layer(layer), ...
                    CorrectedGeometryFingerprint= ...
                    ProjectionGeometryFingerprint.layer(correctedLayer));
            end
        end

        function passes = passes(views, translation)
            passIds = unique(string({views.PassId}), "stable");
            passes = repmat(struct(PassId="", ...
                CommonAttitudeRadians=zeros(1, 3), ...
                TranslationMeters=zeros(1, 3), ...
                TranslationAvailable=true), 1, numel(passIds));
            for index = 1:numel(passIds)
                passes(index).PassId = passIds(index);
                passes(index).TranslationMeters = translation.';
            end
        end

        function status = registrationStatus(correction)
            if ~isfield(correction.Diagnostics, "RegistrationStatus")
                error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                    "S7 correction must record RegistrationStatus.");
            end
            status = string(correction.Diagnostics.RegistrationStatus);
            if ~isscalar(status)
                error("ProjectionDemCorrectionAdapter:invalidRegistration", ...
                    "RegistrationStatus must be scalar.");
            end
        end

        function value = requiredString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || ...
                    strlength(value) == 0 || value ~= strip(value)
                error("ProjectionDemCorrectionAdapter:invalidString", ...
                    "%s must be a nonempty trimmed string.", name);
            end
        end

        function value = optionalString(value, name)
            value = string(value);
            if ~isscalar(value) || ismissing(value) || value ~= strip(value)
                error("ProjectionDemCorrectionAdapter:invalidString", ...
                    "%s must be a trimmed string.", name);
            end
        end
    end
end
