classdef ProjectionSurfaceFusionTruthAudit
    %ProjectionSurfaceFusionTruthAudit Bounded held-out fusion comparison.

    properties (Constant)
        Format = "ProjectionSurfaceFusionTruthAudit"
        Version = 1
    end

    methods (Static)
        function report = run(request, truth, options)
            %run Compare authoritative points and diagnostic voxel modes.
            if nargin < 3
                options = struct();
            end
            request = ProjectionSurfaceFusionRequest.validate(request);
            truth = ProjectionSurfaceFusionTruthAudit.validateTruth( ...
                truth, request);
            options = ProjectionSurfaceFusionTruthAudit.validateOptions( ...
                options, request.BaseVoxelScaleMeters);

            directResult = ProjectionRobustMultiRayFusion().fuse(request);
            hardResult = ProjectionHardVoxelFusion().fuse(request);
            gaussianResult = ProjectionGaussianSplatFusion().fuse(request);
            directPrediction = ProjectionSurfaceFusionTruthAudit. ...
                resultPrediction(directResult);
            direct = ProjectionSurfaceFusionTruthAudit.algorithmSummary( ...
                directResult, directPrediction, truth, ...
                options.CompletenessToleranceMeters);
            hard = ProjectionSurfaceFusionTruthAudit.voxelSummary( ...
                hardResult, truth, options.CompletenessToleranceMeters);
            gaussian = ProjectionSurfaceFusionTruthAudit.voxelSummary( ...
                gaussianResult, truth, options.CompletenessToleranceMeters);
            invariance = ProjectionSurfaceFusionTruthAudit. ...
                pairMultiplicityAudit(request, hardResult, gaussianResult);
            decision = ProjectionSurfaceFusionTruthAudit.decision( ...
                direct, hard, gaussian, invariance, options);
            payload = struct(Direct=direct, HardVoxel=hard, ...
                GaussianSplat=gaussian, PairMultiplicity=invariance, ...
                Decision=decision);
            report = struct(Format=ProjectionSurfaceFusionTruthAudit.Format, ...
                Version=ProjectionSurfaceFusionTruthAudit.Version, ...
                WorldFrame=request.PointSet.WorldFrame, ...
                RoiWorld=request.RoiWorld, ...
                VoxelScalesMeters=request.VoxelScalesMeters, ...
                VoxelScaleSource=request.VoxelScaleSource, ...
                CompletenessToleranceMeters= ...
                options.CompletenessToleranceMeters, ...
                TruthSummary=ProjectionSurfaceFusionTruthAudit. ...
                truthSummary(truth), Direct=direct, HardVoxel=hard, ...
                GaussianSplat=gaussian, PairMultiplicity=invariance, ...
                Decision=decision, ...
                AuditFingerprint=ProjectionGeometryFingerprint.hash(payload));
        end
    end

    methods (Static, Access = private)
        function truth = validateTruth(truth, request)
            required = ["WorldFrame" "PointsWorld" "ModeIds" "SurfaceTypes"];
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    any(~isfield(truth, required))
                error("ProjectionSurfaceFusionTruthAudit:invalidTruth", ...
                    "Truth requires frame, 3xN points, modes, and surface types.");
            end
            truth.WorldFrame = string(truth.WorldFrame);
            truth.ModeIds = reshape(string(truth.ModeIds), 1, []);
            truth.SurfaceTypes = reshape(string(truth.SurfaceTypes), 1, []);
            count = size(truth.PointsWorld, 2);
            if ~isscalar(truth.WorldFrame) || ismissing(truth.WorldFrame) || ...
                    truth.WorldFrame ~= request.PointSet.WorldFrame || ...
                    ~isnumeric(truth.PointsWorld) || ...
                    size(truth.PointsWorld, 1) ~= 3 || count == 0 || ...
                    any(~isfinite(truth.PointsWorld), "all") || ...
                    numel(truth.ModeIds) ~= count || ...
                    numel(truth.SurfaceTypes) ~= count || ...
                    any(ismissing(truth.ModeIds)) || ...
                    any(strlength(truth.ModeIds) == 0) || ...
                    any(ismissing(truth.SurfaceTypes)) || ...
                    any(strlength(truth.SurfaceTypes) == 0) || ...
                    any(truth.PointsWorld < request.RoiWorld(:, 1), "all") || ...
                    any(truth.PointsWorld > request.RoiWorld(:, 2), "all")
                error("ProjectionSurfaceFusionTruthAudit:invalidTruth", ...
                    "Truth must be finite, inside the ROI, and match the world frame.");
            end
            truth.PointsWorld = double(truth.PointsWorld);
        end

        function options = validateOptions(options, baseScale)
            defaults = struct(CompletenessToleranceMeters=baseScale, ...
                AccuracyImprovementFraction=0.05, ...
                CompletenessImprovementFraction=0.05);
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionSurfaceFusionTruthAudit:invalidOptions", ...
                    "Audit options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionSurfaceFusionTruthAudit:invalidOptions", ...
                    "Unexpected audit option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            fields = string(fieldnames(defaults));
            for field = fields.'
                value = defaults.(field);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value <= 0
                    error("ProjectionSurfaceFusionTruthAudit:invalidOptions", ...
                        "%s must be a finite positive scalar.", field);
                end
                defaults.(field) = double(value);
            end
            options = defaults;
        end

        function summary = algorithmSummary(result, prediction, truth, tolerance)
            summary = struct(AlgorithmId=result.AlgorithmId, ...
                ProductRole=result.ProductRole, ...
                Metrics=ProjectionSurfaceFusionTruthAudit.metrics( ...
                prediction, truth, tolerance), ...
                RuntimeSeconds=result.Timing.TotalSeconds, ...
                MemoryBytes=result.Memory.Bytes, ...
                Precision=result.Precision, Execution=result.Execution, ...
                Provenance=result.Provenance);
        end

        function summary = voxelSummary(result, truth, tolerance)
            scaleResults = result.SparseVoxelEvidence.ScaleResults;
            scales = repmat(struct(VoxelScaleMeters=NaN, Metrics=struct(), ...
                AllocatedVoxelCount=0, GridCellCount=0, MemoryBytes=0), ...
                1, numel(scaleResults));
            for index = 1:numel(scaleResults)
                scaleResult = scaleResults(index);
                prediction = ProjectionSurfaceFusionTruthAudit. ...
                    scalePrediction(scaleResult);
                scales(index) = struct( ...
                    VoxelScaleMeters=scaleResult.VoxelScaleMeters, ...
                    Metrics=ProjectionSurfaceFusionTruthAudit.metrics( ...
                    prediction, truth, tolerance), ...
                    AllocatedVoxelCount=scaleResult.AllocatedVoxelCount, ...
                    GridCellCount=scaleResult.GridCellCount, ...
                    MemoryBytes=ProjectionSurfaceFusionSupport.bytes(scaleResult));
            end
            accuracy = arrayfun(@(scale) ...
                scale.Metrics.AccuracyRmseMeters, scales);
            completeness = arrayfun(@(scale) ...
                scale.Metrics.CompletenessFraction, scales);
            [bestAccuracy, bestIndex] = min(accuracy);
            summary = struct(AlgorithmId=result.AlgorithmId, ...
                ProductRole=result.ProductRole, ScaleResults=scales, ...
                BestScaleMeters=scales(bestIndex).VoxelScaleMeters, ...
                BestAccuracyRmseMeters=bestAccuracy, ...
                BestCompletenessFraction=max(completeness), ...
                ScaleSensitivityAccuracyRangeMeters=range(accuracy), ...
                RuntimeSeconds=result.Timing.TotalSeconds, ...
                MemoryBytes=result.Memory.Bytes, ...
                Precision=result.Precision, Execution=result.Execution, ...
                Provenance=result.Provenance);
        end

        function prediction = resultPrediction(result)
            count = numel(result.FusedPoints);
            points = zeros(3, count);
            modes = strings(1, count);
            sigma = nan(1, count);
            for index = 1:count
                point = result.FusedPoints(index);
                points(:, index) = point.PointWorld;
                modes(index) = string(point.ModeId);
                covariance = double(point.CovarianceWorldMetersSquared);
                if all(isfinite(covariance), "all")
                    sigma(index) = sqrt(max(0, trace(covariance)));
                end
            end
            prediction = struct(PointsWorld=points, ModeIds=modes, ...
                RadialSigmaMeters=sigma);
        end

        function prediction = scalePrediction(scaleResult)
            count = sum(arrayfun(@(mode) nnz(mode.PeakMask), ...
                scaleResult.Modes));
            points = zeros(3, count);
            modes = strings(1, count);
            cursor = 0;
            for mode = scaleResult.Modes
                peakIndices = find(mode.PeakMask);
                next = cursor + numel(peakIndices);
                points(:, cursor + 1:next) = mode.CentersWorld(:, peakIndices);
                modes(cursor + 1:next) = mode.ModeId;
                cursor = next;
            end
            radialSigma = repmat(scaleResult.VoxelScaleMeters / 2, 1, count);
            prediction = struct(PointsWorld=points, ModeIds=modes, ...
                RadialSigmaMeters=radialSigma);
        end

        function metrics = metrics(prediction, truth, tolerance)
            predictionErrors = ProjectionSurfaceFusionTruthAudit. ...
                nearestErrors(prediction.PointsWorld, prediction.ModeIds, ...
                truth.PointsWorld, truth.ModeIds);
            truthErrors = ProjectionSurfaceFusionTruthAudit.nearestErrors( ...
                truth.PointsWorld, truth.ModeIds, prediction.PointsWorld, ...
                prediction.ModeIds);
            verticalErrors = ProjectionSurfaceFusionTruthAudit. ...
                nearestVerticalErrors(prediction, truth);
            sigma = prediction.RadialSigmaMeters;
            validCalibration = isfinite(predictionErrors) & ...
                isfinite(sigma) & sigma > 0;
            normalized = predictionErrors(validCalibration) ./ ...
                sigma(validCalibration);
            predictedModes = unique(prediction.ModeIds);
            truthModes = unique(truth.ModeIds);
            metrics = struct( ...
                PredictionCount=size(prediction.PointsWorld, 2), ...
                AccuracyRmseMeters=ProjectionSurfaceFusionTruthAudit.rmse( ...
                predictionErrors), ...
                AccuracyMedianMeters=ProjectionSurfaceFusionTruthAudit. ...
                medianFinite(predictionErrors), ...
                CompletenessFraction=mean(truthErrors <= tolerance), ...
                CompletenessRmseMeters=ProjectionSurfaceFusionTruthAudit.rmse( ...
                truthErrors), ...
                VerticalRmseMeters=ProjectionSurfaceFusionTruthAudit.rmse( ...
                verticalErrors), ...
                ModeRecallFraction=mean(ismember(truthModes, predictedModes)), ...
                PreservedModeIds=intersect(truthModes, predictedModes, "stable"), ...
                UncertaintyCoverageOneSigma=ProjectionSurfaceFusionTruthAudit. ...
                meanOrNaN(normalized <= 1), ...
                NormalizedErrorMedian=ProjectionSurfaceFusionTruthAudit. ...
                medianFinite(normalized), ...
                SurfaceTypes=ProjectionSurfaceFusionTruthAudit. ...
                surfaceMetrics(truthErrors, truth.SurfaceTypes, tolerance));
        end

        function errors = nearestErrors(source, sourceModes, target, targetModes)
            errors = inf(1, size(source, 2));
            for index = 1:size(source, 2)
                eligible = targetModes == sourceModes(index);
                delta = target(:, eligible) - source(:, index);
                if ~isempty(delta)
                    errors(index) = min(vecnorm(delta, 2, 1));
                end
            end
        end

        function errors = nearestVerticalErrors(prediction, truth)
            errors = inf(1, size(prediction.PointsWorld, 2));
            for index = 1:numel(errors)
                eligible = truth.ModeIds == prediction.ModeIds(index);
                delta = abs(truth.PointsWorld(3, eligible) - ...
                    prediction.PointsWorld(3, index));
                if ~isempty(delta)
                    errors(index) = min(delta);
                end
            end
        end

        function values = surfaceMetrics(errors, surfaceTypes, tolerance)
            types = sort(unique(surfaceTypes));
            values = repmat(struct(SurfaceType="", TruthPointCount=0, ...
                CompletenessFraction=0, CompletenessRmseMeters=Inf), ...
                1, numel(types));
            for index = 1:numel(types)
                selected = errors(surfaceTypes == types(index));
                values(index) = struct(SurfaceType=types(index), ...
                    TruthPointCount=numel(selected), ...
                    CompletenessFraction=mean(selected <= tolerance), ...
                    CompletenessRmseMeters= ...
                    ProjectionSurfaceFusionTruthAudit.rmse(selected));
            end
        end

        function summary = truthSummary(truth)
            modes = sort(unique(truth.ModeIds));
            types = sort(unique(truth.SurfaceTypes));
            summary = struct(PointCount=size(truth.PointsWorld, 2), ...
                ModeIds=modes, ModeCount=numel(modes), ...
                SurfaceTypes=types, SurfaceTypeCount=numel(types), ...
                RawTruthRetained=false);
        end

        function audit = pairMultiplicityAudit(request, hard, gaussian)
            duplicateRequest = request;
            for index = 1:numel(duplicateRequest.PointSet.Points)
                duplicateRequest.PointSet.Points(index).PairRecordCount = ...
                    duplicateRequest.PointSet.Points(index).PairRecordCount + 1000;
            end
            duplicateHard = ProjectionHardVoxelFusion().fuse(duplicateRequest);
            duplicateGaussian = ProjectionGaussianSplatFusion().fuse( ...
                duplicateRequest);
            hardInvariant = isequaln(hard.SparseVoxelEvidence, ...
                duplicateHard.SparseVoxelEvidence);
            gaussianInvariant = isequaln(gaussian.SparseVoxelEvidence, ...
                duplicateGaussian.SparseVoxelEvidence);
            audit = struct(HardVoxelInvariant=hardInvariant, ...
                GaussianSplatInvariant=gaussianInvariant, ...
                IndependentEvidencePolicy= ...
                "uniquePointTracksAndPasses;pairMultiplicityIgnored", ...
                Passed=hardInvariant && gaussianInvariant);
        end

        function decision = decision(direct, hard, gaussian, invariance, options)
            directAccuracy = direct.Metrics.AccuracyRmseMeters;
            bestVoxelAccuracy = min(hard.BestAccuracyRmseMeters, ...
                gaussian.BestAccuracyRmseMeters);
            bestVoxelCompleteness = max(hard.BestCompletenessFraction, ...
                gaussian.BestCompletenessFraction);
            accuracyImproved = bestVoxelAccuracy <= directAccuracy * ...
                (1 - options.AccuracyImprovementFraction);
            completenessImproved = bestVoxelCompleteness >= ...
                direct.Metrics.CompletenessFraction + ...
                options.CompletenessImprovementFraction;
            modesPreserved = all(arrayfun(@(scale) ...
                scale.Metrics.ModeRecallFraction == 1, ...
                [hard.ScaleResults gaussian.ScaleResults]));
            promote = invariance.Passed && modesPreserved && ...
                (accuracyImproved || completenessImproved);
            if promote
                outcome = "retainDiagnosticCandidate";
                rationale = ...
                    "Voxel evidence added held-out value and remains diagnostic pending broader validation.";
            else
                outcome = "abandonAuthoritativePromotion";
                rationale = ...
                    "Voxel evidence did not add enough held-out value; retain only diagnostic/research outputs.";
            end
            decision = struct(Outcome=outcome, PromoteVoxelAsAuthoritative=promote, ...
                AuthoritativeAlgorithmId=direct.AlgorithmId, ...
                VoxelProductRole="diagnosticDerived", ...
                PairMultiplicityInvariant=invariance.Passed, ...
                CompetingModesPreserved=modesPreserved, ...
                AccuracyImproved=accuracyImproved, ...
                CompletenessImproved=completenessImproved, ...
                Rationale=rationale);
        end

        function value = rmse(errors)
            finite = errors(isfinite(errors));
            if isempty(finite)
                value = Inf;
            else
                value = sqrt(mean(finite .^ 2));
            end
        end

        function value = medianFinite(values)
            finite = values(isfinite(values));
            if isempty(finite)
                value = NaN;
            else
                value = median(finite);
            end
        end

        function value = meanOrNaN(values)
            if isempty(values)
                value = NaN;
            else
                value = mean(values);
            end
        end
    end
end
