classdef ProjectionHardVoxelFusion < ProjectionSurfaceFusionAlgorithm
    %ProjectionHardVoxelFusion Sparse hard point-vote occupancy adapter.

    methods
        function metadata = metadata(~)
            metadata = struct(AlgorithmId="sightline.fusion.hard-voxel", ...
                Name="Sparse hard voxel occupancy", ...
                SemanticVersion="1.0.0", ...
                Capabilities=struct(FusedPoints=true, VoxelEvidence=true, ...
                CompetingModes=true, Covariance=true), ...
                RequiredProducts="ProjectionMultiRayPointSet", ...
                Deterministic=true, Precision="double", ...
                MemoryEstimate="sparseAllocatedVoxels", ...
                CpuSupported=true, GpuSupported=false, ...
                ProductRole="diagnosticDerived");
        end

        function options = defaultOptions(~)
            options = struct(MaximumGridCells=2000000);
        end

        function options = validateOptions(algorithm, options)
            options = ProjectionHardVoxelFusion.validate( ...
                algorithm.defaultOptions(), options);
        end
    end

    methods (Access = protected)
        function result = fuseImpl(~, request, options, runtimeControl)
            [inputPoints, rejections] = ...
                ProjectionSurfaceFusionSupport.selectPoints(request);
            evidence = ProjectionSurfaceFusionSupport.hardEvidence( ...
                inputPoints, request, options, runtimeControl);
            fusedPoints = ProjectionSurfaceFusionSupport.pointsFromEvidence( ...
                evidence, inputPoints, request);
            result = struct(FusedPoints=fusedPoints, ...
                SparseVoxelEvidence=evidence, ...
                CompetingModes=ProjectionSurfaceFusionSupport. ...
                modeSummary(inputPoints), ...
                Uncertainty=struct(Policy="voxelQuantizationAssumption", ...
                InputCovarianceCount=nnz(arrayfun(@(point) all(isfinite( ...
                point.CovarianceWorldMetersSquared), "all"), inputPoints))), ...
                Contributors=ProjectionSurfaceFusionSupport. ...
                contributorSummary(inputPoints, fusedPoints), ...
                Rejections=rejections, ...
                Diagnostics=struct(EvidenceKind="pointVoteOccupancy", ...
                AuxiliaryPoseObjective=false, ...
                PairMultiplicityUsed=false), ...
                Memory=struct(Bytes= ...
                ProjectionSurfaceFusionSupport.bytes(evidence)), ...
                Execution=struct(Device="cpu"));
        end
    end

    methods (Static, Access = private)
        function options = validate(defaults, options)
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionHardVoxelFusion:invalidOptions", ...
                    "Hard-voxel options must be a scalar struct.");
            end
            names = string(fieldnames(options));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionHardVoxelFusion:invalidOptions", ...
                    "Unexpected option: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = options.(name);
            end
            value = defaults.MaximumGridCells;
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                    value < 1 || fix(value) ~= value
                error("ProjectionHardVoxelFusion:invalidOptions", ...
                    "MaximumGridCells must be a positive integer.");
            end
            defaults.MaximumGridCells = double(value);
            options = defaults;
        end
    end
end
