classdef ProjectionSurfaceRegistrationResult
    %ProjectionSurfaceRegistrationResult Strict S7 proposed-correction result.

    properties (Constant)
        Format = "ProjectionSurfaceRegistrationResult"
        Version = 1
    end

    methods (Static)
        function result = validate(result, request, metadata)
            %validate Normalize one algorithm result against its request.
            if ~isstruct(result) || ~isscalar(result)
                error("ProjectionSurfaceRegistrationResult:invalidResult", ...
                    "Registration result must be a scalar struct.");
            end
            forbidden = ["Truth" "ExpectedTranslation" "Graphics" ...
                "RuntimeCache" "AppliedScene"];
            if any(isfield(result, forbidden))
                error("ProjectionSurfaceRegistrationResult:forbiddenData", ...
                    "Truth, graphics, applied scenes, and runtime state are forbidden.");
            end
            defaults = struct(Format= ...
                ProjectionSurfaceRegistrationResult.Format, ...
                Version=ProjectionSurfaceRegistrationResult.Version, ...
                Status="succeeded", Stage="demRegistration", ...
                WorldFrame=request.PointSet.WorldFrame, ...
                AlgorithmId=string(metadata.AlgorithmId), ...
                Transform=struct(), Covariance=struct(), Support=struct(), ...
                Rejections=ProjectionSurfaceRegistrationResult. ...
                emptyRejections(), Residuals=struct(), Sensitivity=struct(), ...
                Datum=struct(), Ambiguity=struct(), Preview=struct(), ...
                CorrectionSetData=struct(), Diagnostics=struct(), ...
                Timing=struct(TotalSeconds=NaN), Memory=struct(Bytes=NaN), ...
                Precision=request.PrecisionPolicy, Execution=struct(), ...
                Provenance=struct(), Failure=struct(Valid=true, Code="none", ...
                Explanation="none"));
            names = string(fieldnames(result));
            unknown = setdiff(names, string(fieldnames(defaults)));
            if ~isempty(unknown)
                error("ProjectionSurfaceRegistrationResult:invalidResult", ...
                    "Unexpected registration-result field: %s.", unknown(1));
            end
            for name = names.'
                defaults.(name) = result.(name);
            end
            result = defaults;
            result.Format = string(result.Format);
            result.Status = string(result.Status);
            result.Stage = string(result.Stage);
            result.WorldFrame = string(result.WorldFrame);
            result.AlgorithmId = string(result.AlgorithmId);
            identities = {result.Format result.Status result.Stage ...
                result.WorldFrame result.AlgorithmId};
            invalidIdentity = cellfun(@(value) ~isscalar(value) || ...
                ismissing(value), identities);
            if any(invalidIdentity) || ...
                    result.Format ~= ProjectionSurfaceRegistrationResult.Format || ...
                    ~isequal(result.Version, ...
                    ProjectionSurfaceRegistrationResult.Version) || ...
                    ~ismember(result.Status, ["succeeded" "ambiguous" ...
                    "degenerate" "failed" "cancelled"]) || ...
                    result.Stage ~= "demRegistration" || ...
                    result.WorldFrame ~= string(request.PointSet.WorldFrame) || ...
                    result.AlgorithmId ~= string(metadata.AlgorithmId)
                error("ProjectionSurfaceRegistrationResult:identityMismatch", ...
                    "Result schema, status, stage, frame, or algorithm is invalid.");
            end
            scalarStructs = ["Transform" "Covariance" "Support" ...
                "Residuals" "Sensitivity" "Datum" "Ambiguity" "Preview" ...
                "CorrectionSetData" "Diagnostics" "Timing" "Memory" ...
                "Precision" "Execution" "Provenance" "Failure"];
            for field = scalarStructs
                if ~isstruct(result.(field)) || ~isscalar(result.(field))
                    error("ProjectionSurfaceRegistrationResult:invalidResult", ...
                        "%s must be a scalar struct.", field);
                end
            end
            if ~isstruct(result.Rejections)
                error("ProjectionSurfaceRegistrationResult:invalidResult", ...
                    "Rejections must be a struct array.");
            end
            ProjectionSurfaceRegistrationResult.validateTransform( ...
                result.Transform, request);
            ProjectionSurfaceRegistrationResult.validateCovariance( ...
                result.Covariance);
            ProjectionSurfaceRegistrationResult.validateSupport(result.Support);
            ProjectionSurfaceRegistrationResult.validatePreview( ...
                result.Preview, request);
            ProjectionSurfaceRegistrationResult.validateFailure( ...
                result.Failure, result.Status);
            ProjectionSurfaceRegistrationResult.validateCorrection( ...
                result.CorrectionSetData, request, result.Transform, ...
                result.Failure, result.Status);
            if ~isequal(result.Precision, request.PrecisionPolicy) || ...
                    ~isfield(result.Provenance, "AutoApplied") || ...
                    result.Provenance.AutoApplied || ...
                    (isfield(result.Preview, "AppliedToSourceGeometry") && ...
                    result.Preview.AppliedToSourceGeometry)
                error("ProjectionSurfaceRegistrationResult:autoApplyForbidden", ...
                    "Registration results must remain proposed preview-only values.");
            end
            if isfield(result.Memory, "Bytes") && ...
                    (~isnumeric(result.Memory.Bytes) || ...
                    ~isscalar(result.Memory.Bytes) || ...
                    ~(isfinite(result.Memory.Bytes) || isnan(result.Memory.Bytes)) || ...
                    result.Memory.Bytes < 0)
                error("ProjectionSurfaceRegistrationResult:invalidResult", ...
                    "Memory.Bytes must be nonnegative or NaN.");
            end
        end

        function rejections = emptyRejections()
            rejections = struct("PointId", {}, "Reason", {});
        end

        function metadata = metadata(result)
            %metadata Return compact JSON-safe registration evidence.
            correction = ProjectionCorrectionSet.create( ...
                result.CorrectionSetData);
            metadata = struct(Format=result.Format, Version=result.Version, ...
                Status=result.Status, Stage=result.Stage, ...
                WorldFrame=result.WorldFrame, AlgorithmId=result.AlgorithmId, ...
                Transform=result.Transform, Covariance=result.Covariance, ...
                Support=result.Support, Residuals=result.Residuals, ...
                Sensitivity=result.Sensitivity, Datum=result.Datum, ...
                Ambiguity=result.Ambiguity, ...
                CorrectionGenerationId=correction.GenerationId, ...
                CorrectionLifecycle=correction.Lifecycle, ...
                Diagnostics=result.Diagnostics, Timing=result.Timing, ...
                Memory=result.Memory, Precision=result.Precision, ...
                Execution=result.Execution, Provenance=result.Provenance, ...
                Failure=result.Failure, PreviewPointCount= ...
                numel(result.Preview.PointIds), ...
                CompleteImageryProductPreserved= ...
                result.Preview.CompleteImageryProductPreserved, ...
                AppliedToSourceGeometry=false);
        end

        function paths = write(result, matPath, metadataPath)
            %write Persist full MAT result and compact JSON evidence.
            matPath = string(matPath);
            metadataPath = string(metadataPath);
            if ~endsWith(lower(matPath), ".mat") || ...
                    ~endsWith(lower(metadataPath), ".json")
                error("ProjectionSurfaceRegistrationResult:invalidPath", ...
                    "Registration persistence requires .mat and .json paths.");
            end
            registrationResult = result;
            save(matPath, "registrationResult", "-v7.3");
            text = jsonencode(ProjectionSurfaceRegistrationResult. ...
                metadata(result), PrettyPrint=true);
            fileId = fopen(metadataPath, "w");
            if fileId < 0
                error("ProjectionSurfaceRegistrationResult:fileOpenFailed", ...
                    "Unable to open metadata path: %s", metadataPath);
            end
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", text);
            clear cleanup
            paths = struct(MatPath=matPath, MetadataPath=metadataPath);
        end
    end

    methods (Static, Access = private)
        function validateTransform(value, request)
            required = ["Kind" "Direction" "Frame" ...
                "TranslationEnuMeters" "TranslationWorldMeters" ...
                "RotationMatrix"];
            if any(~isfield(value, required)) || ...
                    string(value.Kind) ~= "globalTranslation" || ...
                    string(value.Direction) ~= "imageryToDem" || ...
                    string(value.Frame) ~= "sceneLocalENU" || ...
                    ~isequal(size(value.TranslationEnuMeters), [3 1]) || ...
                    ~isequal(size(value.TranslationWorldMeters), [3 1]) || ...
                    any(~isfinite(value.TranslationEnuMeters)) || ...
                    any(~isfinite(value.TranslationWorldMeters)) || ...
                    ~isequal(double(value.RotationMatrix), eye(3))
                error("ProjectionSurfaceRegistrationResult:invalidTransform", ...
                    "Only finite imagery-to-DEM global ENU translation is supported.");
            end
            expectedWorld = request.Dem.Transforms. ...
                EnuToProjectWorldRotation * value.TranslationEnuMeters;
            if norm(expectedWorld - value.TranslationWorldMeters) > 1e-9
                error("ProjectionSurfaceRegistrationResult:invalidTransform", ...
                    "ENU and project-world translations disagree.");
            end
        end

        function validateCovariance(value)
            required = ["TranslationEnuMetersSquared" ...
                "TranslationWorldMetersSquared" "Status" "Reason" ...
                "SharedDemAccuracyIncluded"];
            if any(~isfield(value, required)) || ...
                    ~ProjectionSurfaceRegistrationResult.psd( ...
                    value.TranslationEnuMetersSquared) || ...
                    ~ProjectionSurfaceRegistrationResult.psd( ...
                    value.TranslationWorldMetersSquared) || ...
                    ~isequal(value.SharedDemAccuracyIncluded, true)
                error("ProjectionSurfaceRegistrationResult:invalidCovariance", ...
                    "Translation covariance must be symmetric PSD with a DEM floor.");
            end
        end

        function validateSupport(value)
            required = ["InputPointCount" "CandidatePointCount" ...
                "AcceptedPointCount" "RejectedPointCount" ...
                "CoverageFraction" "IndependentViewCount" ...
                "IndependentPassCount"];
            if any(~isfield(value, required)) || ...
                    any(~isfinite([value.InputPointCount ...
                    value.CandidatePointCount value.AcceptedPointCount ...
                    value.RejectedPointCount value.CoverageFraction ...
                    value.IndependentViewCount value.IndependentPassCount])) || ...
                    value.AcceptedPointCount + value.RejectedPointCount ~= ...
                    value.InputPointCount || value.CoverageFraction < 0 || ...
                    value.CoverageFraction > 1
                error("ProjectionSurfaceRegistrationResult:invalidSupport", ...
                    "Registration support counts/coverage are inconsistent.");
            end
        end

        function validatePreview(value, request)
            required = ["SourcePointSetGenerationId" "PointIds" ...
                "OriginalPointsWorld" "RegisteredPointsWorld" ...
                "DemDifferenceMeters" "AcceptedMask" ...
                "CompleteImageryProductPreserved" ...
                "AppliedToSourceGeometry"];
            if any(~isfield(value, required))
                error("ProjectionSurfaceRegistrationResult:invalidPreview", ...
                    "Preview requires the complete portable schema.");
            end
            count = numel(value.PointIds);
            if string(value.SourcePointSetGenerationId) ~= ...
                    string(request.PointSet.GenerationId) || ...
                    ~isequal(size(value.OriginalPointsWorld), [3 count]) || ...
                    ~isequal(size(value.RegisteredPointsWorld), [3 count]) || ...
                    numel(value.DemDifferenceMeters) ~= count || ...
                    ~islogical(value.AcceptedMask) || ...
                    numel(value.AcceptedMask) ~= count || ...
                    any(~isfinite(value.OriginalPointsWorld), "all") || ...
                    any(~isfinite(value.RegisteredPointsWorld), "all") || ...
                    ~isequal(value.CompleteImageryProductPreserved, true) || ...
                    ~isequal(value.AppliedToSourceGeometry, false)
                error("ProjectionSurfaceRegistrationResult:invalidPreview", ...
                    "Preview must preserve the complete imagery-only product.");
            end
        end

        function validateCorrection(value, request, transform, failure, status)
            correction = ProjectionCorrectionSet.create(value);
            blockTypes = string({correction.Blocks.Type});
            translationBlocks = correction.Blocks( ...
                blockTypes == "globalPositionTranslation");
            if correction.Lifecycle ~= "proposed" || ...
                    numel(translationBlocks) ~= 1 || ...
                    ~isequal(translationBlocks.Values, ...
                    transform.TranslationWorldMeters.') || ...
                    string(translationBlocks.Frame) ~= request.PointSet.WorldFrame || ...
                    ~isfield(correction.Diagnostics, "AutoApply") || ...
                    correction.Diagnostics.AutoApply || ...
                    ~isfield(correction.Diagnostics, "RegistrationStatus") || ...
                    string(correction.Diagnostics.RegistrationStatus) ~= status || ...
                    correction.Failure.Valid ~= failure.Valid || ...
                    correction.Failure.Code ~= string(failure.Code)
                error("ProjectionSurfaceRegistrationResult:invalidCorrection", ...
                    "Result must contain one proposed non-auto-applied translation block.");
            end
        end

        function validateFailure(value, status)
            if any(~isfield(value, ["Valid" "Code" "Explanation"])) || ...
                    ~islogical(value.Valid) || ~isscalar(value.Valid) || ...
                    ~isscalar(string(value.Code)) || ...
                    strlength(string(value.Code)) == 0 || ...
                    ~isscalar(string(value.Explanation)) || ...
                    strlength(string(value.Explanation)) == 0 || ...
                    (ismember(status, ["succeeded" "ambiguous"]) && ~value.Valid) || ...
                    (ismember(status, ["degenerate" "failed" "cancelled"]) && value.Valid)
                error("ProjectionSurfaceRegistrationResult:invalidFailure", ...
                    "Failure classification disagrees with result status.");
            end
        end

        function tf = psd(value)
            tf = isnumeric(value) && isequal(size(value), [3 3]) && ...
                all(isfinite(value), "all");
            if tf
                value = double(value);
                tolerance = 1e-10 * max(1, norm(value, "fro"));
                tf = norm(value - value.', "fro") <= tolerance && ...
                    min(eig(0.5 * (value + value.'))) >= -tolerance;
            end
        end
    end
end
