classdef ProjectionPrecisionInventory
    %ProjectionPrecisionInventory Describe current numerical type boundaries.

    properties (Constant)
        Format = "ProjectionPrecisionInventory"
        Version = 1
    end

    methods (Static)
        function report = inspect()
            %inspect Return the executable P0 precision inventory.
            entries = [ ...
                ProjectionPrecisionInventory.entry( ...
                "sourceRadiometry", "authoritativeRadiometry", ...
                "caller numeric/logical", "preserve caller type", ...
                "Source imagery remains the backend radiometric authority."), ...
                ProjectionPrecisionInventory.entry( ...
                "sourceOriginsAndRays", "authoritativeGeometry", ...
                "double", "double", ...
                "ProjectionSourceGeometry validates origins and rays as double."), ...
                ProjectionPrecisionInventory.entry( ...
                "planesAndFrameCameras", "authoritativeGeometry", ...
                "double", "double", ...
                "PlanarProjection definitions and transforms use double."), ...
                ProjectionPrecisionInventory.entry( ...
                "renderOriginAndWorldMesh", "authoritativeGeometry", ...
                "double", "double", ...
                "World intersections and render-origin subtraction use double."), ...
                ProjectionPrecisionInventory.entry( ...
                "viewerRelativeVertices", "derivedDisplay", ...
                "double", "single candidate after double local shift", ...
                "A discardable display cast is allowed only after P1 evidence."), ...
                ProjectionPrecisionInventory.entry( ...
                "displayTexturesAndTiles", "derivedDisplayRadiometry", ...
                "natural or normalized single", ...
                "natural or normalized single", ...
                "Preview textures are display-only and never backend input."), ...
                ProjectionPrecisionInventory.entry( ...
                "backendOutputGridAndMapping", "authoritativeBackend", ...
                "double", "double", ...
                "Output axes, bounds, coordinates, and inverse maps stay double."), ...
                ProjectionPrecisionInventory.entry( ...
                "backendTileRadiometry", "derivedBackendRadiometry", ...
                "configured double or single", ...
                "configured double or single", ...
                "WorkingPrecision changes tile products, not geometry metadata."), ...
                ProjectionPrecisionInventory.entry( ...
                "alignmentObservationsAndRays", "authoritativeAlignment", ...
                "double", "double", ...
                "Full-source observations, origins, and vectors are promoted to double."), ...
                ProjectionPrecisionInventory.entry( ...
                "solverJacobianAndState", "authoritativeSolver", ...
                "double", "double", ...
                "OPK parameters, residuals, Jacobians, and factorization remain double."), ...
                ProjectionPrecisionInventory.entry( ...
                "correctionsAndCovariance", "authoritativeCovariance", ...
                "double", "double", ...
                "CorrectionSet radians and radians-squared covariance are double."), ...
                ProjectionPrecisionInventory.entry( ...
                "denseRectifiedAndDisparity", "derivedDenseIntermediate", ...
                "single", "single candidate", ...
                "SGM intensity and disparity are single intermediates."), ...
                ProjectionPrecisionInventory.entry( ...
                "denseRaysAndSurfacePoints", "authoritativeSurface", ...
                "double", "double", ...
                "Dense observations are resampled and triangulated in double."), ...
                ProjectionPrecisionInventory.entry( ...
                "syntheticGeometryAndTruth", "authoritativeTruth", ...
                "double", "double", ...
                "Truth geometry and comparison metrics remain a double oracle."), ...
                ProjectionPrecisionInventory.entry( ...
                "gpuDenseIntermediates", "runtimeAcceleration", ...
                "optional single gpuArray", "study required", ...
                "GPU execution is optional; results are gathered before double geometry."), ...
                ProjectionPrecisionInventory.entry( ...
                "voxelAndFusionIntermediates", "futureDerivedFusion", ...
                "not implemented", "P2 evidence required", ...
                "No precision selection is made before the fusion contract exists.")];
            report = struct(Format=ProjectionPrecisionInventory.Format, ...
                Version=ProjectionPrecisionInventory.Version, ...
                Status="complete", Entries=entries, EntryCount=numel(entries), ...
                Roles=unique(string({entries.Role}), "stable"), ...
                AuthoritativeReference="double", ...
                P0Complete=true, P2PolicySelected=false);
        end

        function probes = probeCurrentTypes()
            %probeCurrentTypes Sample representative public runtime values.
            imageData = uint16(reshape(1:144, 12, 12));
            scene = ProjectionViewerHarness.createSceneFromImages( ...
                {imageData}, "precision-inventory.tif", ...
                struct(RowStride=1, ColumnStride=1));
            layer = scene.layers(1);
            plane = layer.CurrentProjectionPlane;
            mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                layer, plane, scene.renderOrigin);
            [outputGrid, ~] = ProjectionBackendOutputGrid.plan( ...
                scene, [], struct(OutputSize=[12 12]));
            pyramid = ProjectionPreviewPyramid.build(imageData, ...
                struct(UseFileSource=false));
            [origins, vectors] = layer.SourceGeometry.SampleFcn([1 12], [1 12]);
            probes = struct( ...
                SourceImage=string(class(layer.Image)), ...
                SourceOrigins=string(class(origins)), ...
                SourceVectors=string(class(vectors)), ...
                PlaneOrigin=string(class(plane.P0)), ...
                RenderOrigin=string(class(scene.renderOrigin)), ...
                MeshWorldPoints=string(class(mesh.WorldPoints)), ...
                MeshRenderPoints=string(class(mesh.RenderPoints)), ...
                BackendGridOrigin=string(class(outputGrid.Origin)), ...
                BackendGridBounds=string(class(outputGrid.Bounds.X)), ...
                PreviewLevelImage=string(class(pyramid.Levels(1).Image)));
        end
    end

    methods (Static, Access = private)
        function value = entry(name, role, currentType, requiredType, evidence)
            value = struct(Name=name, Role=role, CurrentType=currentType, ...
                RequiredOrCandidateType=requiredType, Evidence=evidence);
        end
    end
end
