classdef ProjectionSurfaceRegistrationTruthAudit
    %ProjectionSurfaceRegistrationTruthAudit Held-out recovery/calibration audit.

    methods (Static)
        function report = run(request, truth, trialCount)
            %run Compare operational registration against held-out translation.
            if nargin < 3
                trialCount = 25;
            end
            request = ProjectionSurfaceRegistrationRequest.validate(request);
            truth = ProjectionSurfaceRegistrationTruthAudit.validateTruth(truth);
            if ~isnumeric(trialCount) || ~isscalar(trialCount) || ...
                    ~isfinite(trialCount) || trialCount < 5 || ...
                    fix(trialCount) ~= trialCount
                error("ProjectionSurfaceRegistrationTruthAudit:invalidTrials", ...
                    "Trial count must be an integer of at least five.");
            end
            baseline = ProjectionSurfaceRegistrationService.run(request);
            baselineError = baseline.Transform.TranslationEnuMeters - ...
                truth.TranslationEnuMeters;
            state = rng;
            cleanup = onCleanup(@() rng(state));
            rng(truth.Seed, "twister");
            errors = nan(3, trialCount);
            mahalanobisSquared = nan(1, trialCount);
            statuses = strings(1, trialCount);
            for trial = 1:trialCount
                trialRequest = ProjectionSurfaceRegistrationTruthAudit. ...
                    perturb(request, trial);
                result = ProjectionSurfaceRegistrationService.run(trialRequest);
                errorVector = result.Transform.TranslationEnuMeters - ...
                    truth.TranslationEnuMeters;
                errors(:, trial) = errorVector;
                mahalanobisSquared(trial) = errorVector.' * ...
                    pinv(result.Covariance.TranslationEnuMetersSquared) * ...
                    errorVector;
                statuses(trial) = result.Status;
            end
            clear cleanup
            threshold90 = 6.25138863117033;
            report = struct(Format= ...
                "ProjectionSurfaceRegistrationTruthAudit", Version=1, ...
                TrialCount=trialCount, BaselineStatus=baseline.Status, ...
                BaselineTranslationEnuMeters= ...
                baseline.Transform.TranslationEnuMeters, ...
                BaselineErrorMeters=baselineError, ...
                BaselineErrorNormMeters=norm(baselineError), ...
                BaselineResiduals=baseline.Residuals, ...
                BaselineSupport=baseline.Support, ...
                BaselineSensitivity=baseline.Sensitivity, ...
                BaselineRejectionReasons= ...
                string({baseline.Rejections.Reason}), ...
                ImageryOnlyProductPreserved=isequal( ...
                baseline.Preview.OriginalPointsWorld, ...
                horzcat(request.PointSet.Points.PointWorld)), ...
                AutoApplied=baseline.Diagnostics.AutoApplied, ...
                MonteCarlo=struct(MeanErrorMeters=mean(errors, 2), ...
                RmseMeters=sqrt(mean(errors .^ 2, 2)), ...
                EmpiricalCovarianceMetersSquared=cov(errors.'), ...
                Coverage90Fraction=mean(mahalanobisSquared <= threshold90), ...
                ChiSquare3Threshold90=threshold90, ...
                AllReviewable=all(ismember(statuses, ...
                ["succeeded" "ambiguous"]))), ...
                OperationalTruthSeparated=true, ...
                AuditFingerprint=ProjectionGeometryFingerprint.hash(struct( ...
                BaselineError=baselineError, TrialCount=trialCount, ...
                Coverage=mean(mahalanobisSquared <= threshold90))));
        end
    end

    methods (Static, Access = private)
        function truth = validateTruth(truth)
            if ~isstruct(truth) || ~isscalar(truth) || ...
                    any(~isfield(truth, ["TranslationEnuMeters" "Seed"])) || ...
                    ~isnumeric(truth.TranslationEnuMeters) || ...
                    numel(truth.TranslationEnuMeters) ~= 3 || ...
                    any(~isfinite(truth.TranslationEnuMeters)) || ...
                    ~isnumeric(truth.Seed) || ~isscalar(truth.Seed) || ...
                    ~isfinite(truth.Seed) || truth.Seed < 0 || ...
                    fix(truth.Seed) ~= truth.Seed
                error("ProjectionSurfaceRegistrationTruthAudit:invalidTruth", ...
                    "Held-out truth requires finite ENU translation and seed.");
            end
            truth.TranslationEnuMeters = reshape( ...
                double(truth.TranslationEnuMeters), 3, 1);
            truth.Seed = double(truth.Seed);
        end

        function request = perturb(request, trial)
            horizontal = request.Dem.Accuracy.HorizontalSigmaMeters;
            vertical = request.Dem.Accuracy.VerticalSigmaMeters;
            sharedDemError = [horizontal; horizontal; vertical] .* randn(3, 1);
            for index = 1:numel(request.PointSet.Points)
                point = request.PointSet.Points(index);
                covariance = point.CovarianceWorldMetersSquared;
                pointNoise = chol(covariance + 1e-14 * eye(3), "lower") * ...
                    randn(3, 1);
                request.PointSet.Points(index).PointWorld = ...
                    point.PointWorld + pointNoise - sharedDemError;
            end
            request.PointSet.GenerationId = "dem-audit-trial-" + trial;
            request.EvaluateMaskSensitivity = false;
        end
    end
end
