classdef ProjectionAlignmentCoplanarity
    %ProjectionAlignmentCoplanarity Normalized epipolar ray diagnostics.

    methods (Static)
        function result = evaluate(scene, pairMatch, options)
            %evaluate Sample current moving/reference rays for one match pair.
            if nargin < 3
                options = struct();
            end
            scene = ProjectionLayerIdentity.ensureScene(scene);
            ProjectionAlignmentCoplanarity.validatePairMatch(pairMatch);
            pair = ProjectionAlignmentLayerResolver.pairIndices(scene, pairMatch);
            [movingOrigins, movingVectors, movingValid, movingStatus, ...
                movingMethod] = ProjectionAlignmentCoplanarity.sampleLayerRays( ...
                scene, pair(1), pairMatch.MovingSourceRows, ...
                pairMatch.MovingSourceColumns);
            [referenceOrigins, referenceVectors, referenceValid, ...
                referenceStatus, referenceMethod] = ...
                ProjectionAlignmentCoplanarity.sampleLayerRays( ...
                scene, pair(2), pairMatch.ReferenceSourceRows, ...
                pairMatch.ReferenceSourceColumns);
            result = ProjectionAlignmentCoplanarity.evaluateRays( ...
                movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors, options);
            samplingValid = movingValid & referenceValid;
            result.ValidMask = result.ValidMask & samplingValid;
            result.Residuals(~result.ValidMask) = NaN;
            result.AbsoluteResiduals(~result.ValidMask) = NaN;
            invalidMoving = ~movingValid;
            invalidReference = movingValid & ~referenceValid;
            result.Status(invalidMoving) = "moving:" + movingStatus(invalidMoving);
            result.Status(invalidReference) = ...
                "reference:" + referenceStatus(invalidReference);
            result.Pair = pair;
            result.PairLayerIds = ProjectionLayerIdentity.idsForIndices( ...
                scene, pair);
            result.PairDirection = "movingToReference";
            result.MovingSampler = movingMethod;
            result.ReferenceSampler = referenceMethod;
        end

        function result = evaluateRays(movingOrigins, movingVectors, ...
                referenceOrigins, referenceVectors, options)
            %evaluateRays Return signed angular/Sampson coplanarity residuals.
            if nargin < 5
                options = struct();
            end
            [movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors, options] = ...
                ProjectionAlignmentCoplanarity.validateRayInputs( ...
                movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors, options);
            count = size(movingOrigins, 2);
            residuals = nan(count, 1);
            status = repmat("nonfiniteRay", count, 1);
            movingNorms = sqrt(sum(movingVectors.^2, 1));
            referenceNorms = sqrt(sum(referenceVectors.^2, 1));
            finiteMask = all(isfinite(movingOrigins), 1) & ...
                all(isfinite(referenceOrigins), 1) & ...
                all(isfinite(movingVectors), 1) & ...
                all(isfinite(referenceVectors), 1);
            directionMask = movingNorms > options.MinimumDirectionNorm & ...
                referenceNorms > options.MinimumDirectionNorm;
            status(finiteMask & ~directionMask) = "zeroDirection";

            movingUnit = movingVectors ./ movingNorms;
            referenceUnit = referenceVectors ./ referenceNorms;
            baseline = referenceOrigins - movingOrigins;
            baselineNorms = sqrt(sum(baseline.^2, 1));
            baselineMask = baselineNorms > options.MinimumBaselineMeters;
            status(finiteMask & directionMask & ~baselineMask) = ...
                "negligibleBaseline";
            baselineUnit = baseline ./ baselineNorms;
            rayCross = cross(movingUnit, referenceUnit, 1);
            rayCrossNorms = sqrt(sum(rayCross.^2, 1));
            parallelMask = rayCrossNorms > options.MinimumRayCrossNorm;
            status(finiteMask & directionMask & baselineMask & ~parallelMask) = ...
                "nearlyParallelRays";
            numerator = sum(baselineUnit .* rayCross, 1);
            movingDerivative = cross(referenceUnit, baselineUnit, 1);
            referenceDerivative = cross(baselineUnit, movingUnit, 1);
            denominator = sqrt(sum(movingDerivative.^2, 1) + ...
                sum(referenceDerivative.^2, 1));
            denominatorMask = denominator > ...
                options.MinimumSampsonDenominator;
            status(finiteMask & directionMask & baselineMask & parallelMask & ...
                ~denominatorMask) = "degenerateNormalization";
            valid = (finiteMask & directionMask & baselineMask & ...
                parallelMask & denominatorMask).';
            residuals(valid) = (numerator(valid.') ./ denominator(valid.')).';
            status(valid) = "valid";

            result = struct(Residuals=residuals, ...
                AbsoluteResiduals=abs(residuals), ValidMask=valid, ...
                Status=status, Unit="normalizedAngular", ...
                Normalization="baselineUnitSampsonRayDirections", ...
                BaselineMeters=baselineNorms(:), Numerator=numerator(:), ...
                SampsonDenominator=denominator(:), ...
                RayCrossNorm=rayCrossNorms(:), ...
                Options=options);
        end
    end

    methods (Static, Access = private)
        function [origins, vectors, valid, status, method] = ...
                sampleLayerRays(scene, layerIndex, rows, columns)
            layer = scene.layers(layerIndex);
            rows = double(rows(:));
            columns = double(columns(:));
            count = numel(rows);
            if numel(columns) ~= count
                error("ProjectionAlignmentCoplanarity:sizeMismatch", ...
                    "Observation row and column counts must match.");
            end
            origins = nan(3, count);
            vectors = nan(3, count);
            valid = false(count, 1);
            status = repmat("outsideSource", count, 1);
            imageSize = double(layer.SourceGeometry.ImageSize(:).');
            candidateMask = isfinite(rows) & isfinite(columns) & ...
                rows >= 1 & rows <= imageSize(1) & ...
                columns >= 1 & columns <= imageSize(2);
            sourceGeometry = layer.SourceGeometry;
            if isfield(sourceGeometry, "SampleRayFcn") && ...
                    isa(sourceGeometry.SampleRayFcn, "function_handle")
                method = "exactSampledRay";
                [origins, vectors, valid, status] = ...
                    ProjectionAlignmentCoplanarity.sampleExactRays( ...
                    layer, rows, columns, candidateMask, origins, vectors, ...
                    valid, status);
            else
                method = "sampledMeshInterpolation";
                [origins, vectors, valid, status] = ...
                    ProjectionAlignmentCoplanarity.sampleMeshRays( ...
                    scene, layerIndex, rows, columns, candidateMask, ...
                    origins, vectors, valid, status);
            end
        end

        function [origins, vectors, valid, status] = sampleExactRays( ...
                layer, rows, columns, candidateMask, origins, vectors, ...
                valid, status)
            indices = reshape(find(candidateMask), 1, []);
            if isempty(indices)
                return
            end
            rotation = ProjectionMeshBuilder.viewVectorRotationMatrix( ...
                layer, layer.CurrentProjectionPlane);
            try
                [candidateOrigins, candidateVectors] = ...
                    layer.SourceGeometry.SampleRayFcn( ...
                    rows(indices), columns(indices));
                ProjectionAlignmentCoplanarity.validateSampleBatch( ...
                    candidateOrigins, candidateVectors, numel(indices));
                origins(:, indices) = double(candidateOrigins);
                vectors(:, indices) = rotation * double(candidateVectors);
                valid(indices) = true;
                status(indices) = "valid";
                return
            catch
                % Custom observation samplers may only support scalars.
            end
            for index = indices
                try
                    [origin, vector] = layer.SourceGeometry.SampleRayFcn( ...
                        rows(index), columns(index));
                    ProjectionAlignmentCoplanarity.validateSampleBatch( ...
                        origin, vector, 1);
                    origins(:, index) = double(origin);
                    vectors(:, index) = rotation * double(vector);
                    valid(index) = true;
                    status(index) = "valid";
                catch
                    status(index) = "samplingFailure";
                end
            end
        end

        function [origins, vectors, valid, status] = sampleMeshRays( ...
                scene, layerIndex, rows, columns, candidateMask, origins, ...
                vectors, valid, status)
            if ~any(candidateMask)
                return
            end
            try
                mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                    scene.layers(layerIndex), ...
                    scene.layers(layerIndex).CurrentProjectionPlane, ...
                    scene.renderOrigin);
                for component = 1:3
                    origins(component, candidateMask) = interp1( ...
                        mesh.ColumnIndices, mesh.SampledOrigins(component, :), ...
                        columns(candidateMask), "linear", NaN);
                    vectorGrid = squeeze( ...
                        mesh.SampledVectors(component, :, :));
                    vectors(component, candidateMask) = interp2( ...
                        mesh.ColumnIndices, mesh.RowIndices, vectorGrid, ...
                        columns(candidateMask), rows(candidateMask), ...
                        "linear", NaN);
                end
                finiteMask = candidateMask & all(isfinite(origins), 1).' & ...
                    all(isfinite(vectors), 1).';
                valid(finiteMask) = true;
                status(finiteMask) = "valid";
                status(candidateMask & ~finiteMask) = "outsideSampledMesh";
            catch
                status(candidateMask) = "meshSamplingFailure";
            end
        end

        function validateSampleBatch(origins, vectors, count)
            if ~isnumeric(origins) || ~isequal(size(origins), [3 count]) || ...
                    any(~isfinite(origins), "all") || ~isnumeric(vectors) || ...
                    ~isequal(size(vectors), [3 count]) || ...
                    any(~isfinite(vectors), "all")
                error("ProjectionAlignmentCoplanarity:invalidSample", ...
                    "SampleRayFcn must return finite 3xN origins and vectors.");
            end
        end

        function validatePairMatch(pairMatch)
            required = ["MovingSourceRows", "MovingSourceColumns", ...
                "ReferenceSourceRows", "ReferenceSourceColumns", "Count"];
            if ~isstruct(pairMatch) || ~isscalar(pairMatch) || ...
                    any(~isfield(pairMatch, required)) || ...
                    any([numel(pairMatch.MovingSourceRows), ...
                    numel(pairMatch.MovingSourceColumns), ...
                    numel(pairMatch.ReferenceSourceRows), ...
                    numel(pairMatch.ReferenceSourceColumns)] ~= pairMatch.Count)
                error("ProjectionAlignmentCoplanarity:invalidMatchPair", ...
                    "Match pair source observations must have Count entries.");
            end
        end

        function [movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors, options] = validateRayInputs( ...
                movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors, options)
            arrays = {movingOrigins, movingVectors, referenceOrigins, ...
                referenceVectors};
            count = size(movingOrigins, 2);
            if any(cellfun(@(value) ~isnumeric(value) || ...
                    ~ismatrix(value) || size(value, 1) ~= 3 || ...
                    size(value, 2) ~= count, arrays))
                error("ProjectionAlignmentCoplanarity:invalidRays", ...
                    "All ray arrays must be equal-size numeric 3xN matrices.");
            end
            movingOrigins = double(movingOrigins);
            movingVectors = double(movingVectors);
            referenceOrigins = double(referenceOrigins);
            referenceVectors = double(referenceVectors);
            if isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error("ProjectionAlignmentCoplanarity:invalidOptions", ...
                    "Options must be a scalar struct.");
            end
            defaults = struct(MinimumBaselineMeters=1e-6, ...
                MinimumDirectionNorm=1e-12, ...
                MinimumRayCrossNorm=1e-8, ...
                MinimumSampsonDenominator=1e-8);
            names = fieldnames(options);
            for k = 1:numel(names)
                defaults.(names{k}) = options.(names{k});
            end
            names = fieldnames(defaults);
            for k = 1:numel(names)
                value = defaults.(names{k});
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value <= 0
                    error("ProjectionAlignmentCoplanarity:invalidOptions", ...
                        "%s must be a positive finite scalar.", names{k});
                end
                defaults.(names{k}) = double(value);
            end
            options = defaults;
        end
    end
end
