function records = exportCppGeometryGoldenFixture(outputPath)
%exportCppGeometryGoldenFixture Write the public native geometry oracle CSV.

arguments
    outputPath (1, 1) string
end

horizontalPlane = struct(P0=[0; 0; 0], VN=[0; 0; 1], ...
    basis=[1 0; 0 1; 0 0]);
shiftedPlane = horizontalPlane;
shiftedPlane.P0 = [100; -50; 3];
obliquePlane = struct(P0=[1000; -2000; 300], ...
    VN=[0.51961524227066325; -0.69282032302755092; 0.5], ...
    basis=[0.8 -0.3; 0.6 0.4; 0 sqrt(3) / 2]);
obliqueTarget = obliquePlane.P0 + obliquePlane.basis * [2; -3];
obliqueOrigin = obliqueTarget - 5 * obliquePlane.VN;

records = [ ...
    makeRecord("horizontal_normal", horizontalPlane, [1; 2; 10], ...
    [0; 0; -1], 10, [1; 2; 0], [1; 2], true, "ok") ...
    makeRecord("horizontal_oblique", shiftedPlane, [1; 2; 11], ...
    [0.6; 0; -0.8], 10, [7; 2; 3], [-93; 52], true, "ok") ...
    makeRecord("large_oblique", obliquePlane, obliqueOrigin, ...
    obliquePlane.VN, 5, obliqueTarget, [2; -3], true, "ok") ...
    makeRecord("parallel", horizontalPlane, [0; 0; 1], ...
    [1; 0; 0], NaN, nan(3, 1), nan(2, 1), false, "parallel") ...
    makeRecord("behind", horizontalPlane, [0; 0; -1], ...
    [0; 0; -1], NaN, nan(3, 1), nan(2, 1), false, "behind")];

fileId = fopen(outputPath, "w");
if fileId < 0
    error("exportCppGeometryGoldenFixture:openFailed", ...
        "Cannot open %s for writing.", outputPath);
end
cleanup = onCleanup(@() fclose(fileId));
header = strjoin([ ...
    "case_id,p0_x,p0_y,p0_z,normal_x,normal_y,normal_z," ...
    "basis_x_x,basis_x_y,basis_x_z,basis_y_x,basis_y_y,basis_y_z," ...
    "origin_x,origin_y,origin_z,direction_x,direction_y,direction_z," ...
    "expected_range,expected_world_x,expected_world_y,expected_world_z," ...
    "expected_plane_x,expected_plane_y,valid,status"], "");
fprintf(fileId, "%s\n", header);
for index = 1:numel(records)
    record = records(index);
    values = [record.Plane.P0; record.Plane.VN; ...
        record.Plane.basis(:, 1); record.Plane.basis(:, 2); ...
        record.Origin; record.Direction; record.ExpectedRange; ...
        record.ExpectedWorld; record.ExpectedPlane].';
    valueText = compose("%.17g", values);
    valueText(isnan(values)) = "nan";
    fprintf(fileId, "%s,%s,%d,%s\n", record.CaseId, ...
        strjoin(valueText, ","), record.Valid, record.Status);
end
clear cleanup
end

function record = makeRecord(caseId, plane, origin, direction, ...
        expectedRange, expectedWorld, expectedPlane, valid, status)
record = struct(CaseId=caseId, Plane=plane, Origin=origin, ...
    Direction=direction, ExpectedRange=expectedRange, ...
    ExpectedWorld=expectedWorld, ExpectedPlane=expectedPlane, ...
    Valid=valid, Status=status);
end
