function groups = projectionTestGroups(groupName)
%projectionTestGroups Return the authoritative logical test-suite manifest.

arguments
    groupName (1, 1) string = ""
end

groups = [ ...
    struct(Name="coreGeometryState", ...
    Description="Core geometry, identity, state, and non-UI controllers", ...
    Files=[ ...
    "PlanarProjectionTest.m" ...
    "ProjectionLayerIdentityTest.m" ...
    "ProjectionLayerManagerTest.m" ...
    "ProjectionMeshBuilderTest.m" ...
    "ProjectionMotionSequenceTest.m" ...
    "ProjectionPairControllerTest.m" ...
    "ProjectionPairViewpointTest.m" ...
    "ProjectionPreviewPyramidTest.m" ...
    "ProjectionPreviewTileGeometryTest.m" ...
    "ProjectionPrecisionInventoryTest.m" ...
    "ProjectionCppGoldenFixtureTest.m" ...
    "ProjectionReadbackRendererTest.m" ...
    "ProjectionSoloPairVisibilityTest.m" ...
    "ProjectionSourceGeometryTest.m" ...
    "ProjectionStereoCursorModelTest.m" ...
    "ProjectionStereoEyeControllerTest.m" ...
    "ProjectionTestGroupingTest.m" ...
    "ProjectionViewMetadataTest.m" ...
    "ProjectionViewerLruCacheTest.m" ...
    "ProjectionViewerPerformanceMonitorTest.m" ...
    "ProjectionViewerStateSceneTest.m" ...
    "ProjectionViewerStateTest.m" ...
    "ProjectionViewportGridTest.m"]), ...
    struct(Name="alignment", ...
    Description="Sparse alignment, global network solve, and correction SDK", ...
    Files=[ ...
    "ProjectionAlignmentCoplanarityTest.m" ...
    "ProjectionAlignmentFeatureMatcherTest.m" ...
    "ProjectionAlignmentGeometricModelTest.m" ...
    "ProjectionAlignmentLayerResolverTest.m" ...
    "ProjectionAlignmentMatchFilterTest.m" ...
    "ProjectionAlignmentMatchLedgerTest.m" ...
    "ProjectionAlignmentModelTest.m" ...
    "ProjectionAlignmentNetworkSolverTest.m" ...
    "ProjectionAlignmentObliqueTerrainHarnessTest.m" ...
    "ProjectionAlignmentObservationProjectorTest.m" ...
    "ProjectionAlignmentOpkSolverTest.m" ...
    "ProjectionAlignmentReliabilityValidationTest.m" ...
    "ProjectionAlignmentSafeSolvePolicyTest.m" ...
    "ProjectionAlignmentSchedulerTest.m" ...
    "ProjectionAlignmentSessionTest.m" ...
    "ProjectionAlignmentSyntheticAcceptanceTest.m" ...
    "ProjectionAlignmentSyntheticHarnessTest.m" ...
    "ProjectionAlignmentTimeVaryingOpkResearchTest.m" ...
    "ProjectionAlignmentTrackBuilderTest.m" ...
    "ProjectionAlignmentWorkingGridTest.m" ...
    "ProjectionAlignmentWorkingImageComparisonTest.m" ...
    "ProjectionAlignmentWorkingImageRendererTest.m" ...
    "ProjectionCorrectionSetTest.m" ...
    "ProjectionCorrectionStoreTest.m" ...
    "ProjectionDemCorrectionApplicationTest.m"]), ...
    struct(Name="backendSurface", ...
    Description="Backend rendering, dense surface, and synthetic truth", ...
    Files=[ ...
    "ProjectionBackendAlignmentIntegrationTest.m" ...
    "ProjectionBackendCustomGpuKernelPlanTest.m" ...
    "ProjectionBackendGpuSupportTest.m" ...
    "ProjectionBackendJobTest.m" ...
    "ProjectionBackendOutputGridTest.m" ...
    "ProjectionBackendProcessorOutputTest.m" ...
    "ProjectionBackendProcessorValidationTest.m" ...
    "ProjectionBackendRadiometryTest.m" ...
    "ProjectionBackendRenderPlanTest.m" ...
    "ProjectionBackendSourceProviderTest.m" ...
    "ProjectionBackendTiledRendererTest.m" ...
    "ProjectionDenseSurfaceExtractorTest.m" ...
    "ProjectionDenseMatcherSdkTest.m" ...
    "ProjectionDenseMultiRayReconstructionTest.m" ...
    "ProjectionDenseSearchPlanningTest.m" ...
    "ProjectionDenseSgmTruthAuditTest.m" ...
    "ProjectionDenseTemplateMatcherTest.m" ...
    "ProjectionCoordinateFrameTest.m" ...
    "ProjectionDemGridTest.m" ...
    "ProjectionDenseSurfaceSyntheticAcceptanceTest.m" ...
    "ProjectionDenseSurfaceSyntheticGeneratorTest.m" ...
    "ProjectionDenseSurfaceSyntheticNavigationTest.m" ...
    "ProjectionDenseSurfaceSyntheticPlannerTest.m" ...
    "ProjectionDenseSurfaceSyntheticTruthTest.m" ...
    "ProjectionFullSourceInverseWarpTest.m" ...
    "ProjectionPairwisePointCovarianceTest.m" ...
    "ProjectionProceduralAnaglyphTest.m" ...
    "ProjectionRasterPreviewRendererTest.m" ...
    "ProjectionReflectedTextureTest.m" ...
    "ProjectionSurfaceFusionSdkTest.m" ...
    "ProjectionSurfaceFusionTruthAuditTest.m" ...
    "ProjectionSurfaceRegistrationSdkTest.m" ...
    "ProjectionSurfaceRegistrationTruthAuditTest.m" ...
    "ProjectionSurfaceRunTest.m" ...
    "ProjectionSurfaceWorkbenchModelTest.m" ...
    "ProjectionSurfaceWorkbenchRunnerTest.m"]), ...
    struct(Name="viewerAlignmentUi", ...
    Description="Viewer alignment, active-pair, and general app interaction", ...
    Files=[ ...
    "ProjectionViewerActivePairWorkflowTest.m" ...
    "ProjectionViewerAlignmentWorkflowTest.m" ...
    "ProjectionViewerDemCorrectionWorkflowTest.m" ...
    "ProjectionViewerAppInteractionTest.m"]), ...
    struct(Name="viewerPresentationWorkflows", ...
    Description="Viewer motion, framing, harness, and stereo workflows", ...
    Files=[ ...
    "ProjectionMotionPlaybackTest.m" ...
    "ProjectionViewerHarnessTest.m" ...
    "ProjectionViewerMotionPlaybackWorkflowTest.m" ...
    "ProjectionViewerMotionWorkflowTest.m" ...
    "ProjectionViewerRealDataFramingTest.m" ...
    "ProjectionSurfaceWorkbenchWorkflowTest.m" ...
    "ProjectionSurfaceRegistrationWorkflowTest.m" ...
    "ProjectionViewerStereoCursorWorkflowTest.m" ...
    "ProjectionViewerStereoEyeWorkflowTest.m"]), ...
    struct(Name="viewerPerformancePrecision", ...
    Description="Viewer performance evidence and long-range precision", ...
    Files=[ ...
    "ProjectionViewerPerformanceTest.m" ...
    "ProjectionViewerPrecisionValidationTest.m"])];

if strlength(groupName) == 0
    return
end

match = string({groups.Name}) == groupName;
if ~any(match)
    error("projectionTestGroups:unknownGroup", ...
        "Unknown test group '%s'. Available groups are: %s.", ...
        groupName, strjoin(string({groups.Name}), ", "));
end
groups = groups(match);
end
