function [summary, artifacts] = ...
        alignment_reliability_validation(imagePath, options)
%ALIGNMENT_RELIABILITY_VALIDATION Run the Pack 8 synthetic validation matrix.
%
% Uses the red and blue bands of a test RGB TIFF as independent sensor images
% over the deterministic oblique DEM. The report combines image-driven
% detector/filter/loss sweeps with named contract regressions. No display or
% alignment working product is used as backend radiometry.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
if nargin < 1 || isempty(imagePath)
    imagePath = fullfile(projectRoot, "test_data", "10.tif");
end
if nargin < 2 || isempty(options)
    options = struct();
end
options = mergeOptions(options, projectRoot);
imagePath = string(imagePath);
if ~isscalar(imagePath) || ~isfile(imagePath)
    error("alignment_reliability_validation:fileNotFound", ...
        "Validation RGB TIFF does not exist: %s", imagePath);
end

totalTimer = tic;
[truthScene, truth] = ...
    ProjectionAlignmentObliqueTerrainHarness.createSceneFromRgbTiff( ...
    imagePath, options.SimulationOptions);
biasedScene = applyBias(truthScene, options.BiasDegrees);
baseOptions = validationAlignmentOptions(options);
request = ProjectionAlignmentRequest.validate(struct(Scene=biasedScene, ...
    LayerIndices=[2 1], ReferenceLayerIndex=1, AnalysisBands=[1 1], ...
    Options=baseOptions));
working = ProjectionAlignmentWorkingImageRenderer.render( ...
    biasedScene, request, options.RenderOptions);

[detectorRecords, matchResults, filteredResults] = detectorMatrix( ...
    biasedScene, working, truth, baseOptions, options.Detectors);
filteredCounts = [detectorRecords.FilteredCount];
[~, bestIndex] = max(filteredCounts);
bestMatches = matchResults{bestIndex};
bestFiltered = filteredResults{bestIndex};
bestDetector = detectorRecords(bestIndex).Detector;

tinyScene = applyBias(biasedScene, options.TinyPerturbationDegrees, 2);
tinyRequest = request;
tinyRequest.Scene = tinyScene;
tinyWorking = ProjectionAlignmentWorkingImageRenderer.render( ...
    tinyScene, tinyRequest, options.RenderOptions);
tinyOptions = baseOptions;
tinyOptions.Detector.Method = bestDetector;
tinyMatches = ProjectionAlignmentFeatureMatcher.match( ...
    tinyWorking, tinyOptions);
tinyFiltered = ProjectionAlignmentMatchFilter.filter( ...
    tinyMatches, tinyOptions, tinyScene);
repeatability = struct( ...
    Detector=bestDetector, ...
    GridKeysEqual=isequal(working.GridKeys, tinyWorking.GridKeys), ...
    BaselineRawCount=matchCount(bestMatches), ...
    PerturbedRawCount=matchCount(tinyMatches), ...
    BaselineFilteredCount=matchCount(bestFiltered), ...
    PerturbedFilteredCount=matchCount(tinyFiltered), ...
    RawRetentionFraction=matchCount(tinyMatches) / ...
        max(matchCount(bestMatches), 1), ...
    FilteredRetentionFraction=matchCount(tinyFiltered) / ...
        max(matchCount(bestFiltered), 1), ...
    PerturbationDegrees=options.TinyPerturbationDegrees);

lossRecords = lossMatrix(biasedScene, bestFiltered, baseOptions);
curation = curationDiagnostics(bestFiltered);
anchor = anchorDiagnostics(biasedScene, bestFiltered, baseOptions);
regressions = regressionMatrix(options.RunRegressionTests, projectRoot);
summary = struct( ...
    Format="ProjectionAlignmentReliabilityValidation", Version=1, ...
    CreatedAt=string(datetime("now", TimeZone="UTC", ...
        Format="yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    SourcePath=imagePath, MATLABVersion=string(version), ...
    Computer=string(computer), Simulation=truthScene.Simulation, ...
    BiasDegrees=options.BiasDegrees, ...
    WorkingImageMode="fullSourceInverseWarp", ...
    WorkingGridKeys=working.GridKeys, ...
    Detectors=detectorRecords, SelectedDetector=bestDetector, ...
    Repeatability=repeatability, Losses=lossRecords, ...
    Curation=curation, CommonAnchor=anchor, ...
    ContractRegressions=regressions, ...
    BackendRadiometryContract="fullSourceInverseWarp", ...
    TotalSeconds=toc(totalTimer));

artifacts = writeArtifacts(summary, options.OutputDirectory);
printSummary(summary, artifacts);
end

function options = mergeOptions(options, projectRoot)
if ~isstruct(options) || ~isscalar(options)
    error("alignment_reliability_validation:invalidOptions", ...
        "Options must be a scalar struct.");
end
defaults = struct( ...
    OutputDirectory=fullfile(projectRoot, "artifacts", ...
        "alignment_reliability_validation"), ...
    SimulationOptions=struct(SensorImageSize=[1024 1024], DemGridSize=257, ...
        MeshStride=16, RenderChunkRows=64), ...
    RenderOptions=struct(OutputSize=[768 768]), ...
    BiasDegrees=[0.006 -0.003 0.001; -0.004 0.002 -0.001], ...
    TinyPerturbationDegrees=[0.01 0 0], ...
    Detectors="all", RunRegressionTests=true, MaxFeatures=2000, ...
    MaxRatio=0.9);
names = fieldnames(defaults);
for k = 1:numel(names)
    if isfield(options, names{k})
        defaults.(names{k}) = options.(names{k});
    end
end
defaults.OutputDirectory = string(defaults.OutputDirectory);
defaults.BiasDegrees = double(defaults.BiasDegrees);
defaults.TinyPerturbationDegrees = reshape( ...
    double(defaults.TinyPerturbationDegrees), 1, []);
defaults.Detectors = string(defaults.Detectors);
defaults.RunRegressionTests = logical(defaults.RunRegressionTests);
if ~isscalar(defaults.OutputDirectory) || ...
        strlength(defaults.OutputDirectory) == 0 || ...
        ~isequal(size(defaults.BiasDegrees), [2 3]) || ...
        any(~isfinite(defaults.BiasDegrees), "all") || ...
        numel(defaults.TinyPerturbationDegrees) ~= 3 || ...
        any(~isfinite(defaults.TinyPerturbationDegrees)) || ...
        ~isscalar(defaults.RunRegressionTests) || ...
        ~isnumeric(defaults.MaxFeatures) || ~isscalar(defaults.MaxFeatures) || ...
        defaults.MaxFeatures < 1 || fix(defaults.MaxFeatures) ~= ...
        defaults.MaxFeatures || ~isnumeric(defaults.MaxRatio) || ...
        ~isscalar(defaults.MaxRatio) || ~isfinite(defaults.MaxRatio) || ...
        defaults.MaxRatio <= 0 || defaults.MaxRatio > 1
    error("alignment_reliability_validation:invalidOptions", ...
        "Output, bias, detector, feature, ratio, or regression option is invalid.");
end
options = defaults;
end

function options = validationAlignmentOptions(configuration)
options = ProjectionAlignmentOptions.validate(struct( ...
    Detector=struct(Method="auto", MaxFeatures=configuration.MaxFeatures), ...
    Matcher=struct(Method="exhaustive", MaxRatio=configuration.MaxRatio), ...
    FilterPipeline=struct(GeometricMethod="similarity", ...
        GeometricMaxDistancePixels=4, CoplanarityMethod="none", ...
        NativeDisplacementMethod="none"), ...
    MovableParameters=struct(AllowReferenceMotion=true), ...
    Regularization=struct(OverallWeight=1e-3, RobustLoss="huber")));
end

function scene = applyBias(scene, biasDegrees, layerIndex)
if nargin < 3
    for k = 1:numel(scene.layers)
        scene.layers(k).ViewVectorAngularOffsetsDegrees = ...
            reshape(double(biasDegrees(k, :)), 3, 1);
    end
    return
end
offsets = layerOffsets(scene.layers(layerIndex));
scene.layers(layerIndex).ViewVectorAngularOffsetsDegrees = ...
    offsets + reshape(double(biasDegrees), 3, 1);
end

function offsets = layerOffsets(layer)
offsets = zeros(3, 1);
if isfield(layer, "ViewVectorAngularOffsetsDegrees")
    offsets = reshape(double(layer.ViewVectorAngularOffsetsDegrees), 3, 1);
end
end

function [records, matches, filtered] = detectorMatrix( ...
        scene, working, truth, baseOptions, requestedDetectors)
capabilities = ProjectionAlignmentFeatureMatcher.capabilities();
available = capabilities.AvailableDetectors;
if isscalar(requestedDetectors) && requestedDetectors == "all"
    detectors = available;
else
    detectors = reshape(requestedDetectors, 1, []);
    unavailable = setdiff(detectors, ["auto" available]);
    if ~isempty(unavailable)
        error("alignment_reliability_validation:unavailableDetector", ...
            "Requested detector is unavailable: %s", unavailable(1));
    end
end
records = repmat(emptyDetectorRecord(), 1, numel(detectors));
matches = cell(1, numel(detectors));
filtered = cell(1, numel(detectors));
for k = 1:numel(detectors)
    timer = tic;
    detectorOptions = baseOptions;
    detectorOptions.Detector.Method = detectors(k);
    first = ProjectionAlignmentFeatureMatcher.match(working, detectorOptions);
    repeated = ProjectionAlignmentFeatureMatcher.match(working, detectorOptions);
    kept = ProjectionAlignmentMatchFilter.filter( ...
        first, detectorOptions, scene);
    terrain = ProjectionAlignmentObliqueTerrainHarness.truthMetrics(kept, truth);
    record = emptyDetectorRecord();
    record.Detector = detectors(k);
    record.ExactRepeat = exactMatchRecords(first, repeated);
    record.RawCount = matchCount(first);
    record.FilteredCount = matchCount(kept);
    record.RejectedCount = record.RawCount - record.FilteredCount;
    record.TerrainMedianMeters = terrain.MedianSeparationMeters;
    record.TerrainP95Meters = terrain.P95SeparationMeters;
    record.TotalSeconds = toc(timer);
    record.MatcherMethod = detectorOptions.Matcher.Method;
    records(k) = record;
    matches{k} = first;
    filtered{k} = kept;
end
end

function record = emptyDetectorRecord()
record = struct(Detector="", ExactRepeat=false, RawCount=0, ...
    FilteredCount=0, RejectedCount=0, TerrainMedianMeters=NaN, ...
    TerrainP95Meters=NaN, TotalSeconds=NaN, MatcherMethod="");
end

function tf = exactMatchRecords(first, second)
tf = isequal(first.Matches.IndexPairs, second.Matches.IndexPairs) && ...
    isequal(first.Matches.MatchMetric, second.Matches.MatchMetric) && ...
    isequal(first.Matches.MovingSourceRows, ...
    second.Matches.MovingSourceRows) && ...
    isequal(first.Matches.ReferenceSourceColumns, ...
    second.Matches.ReferenceSourceColumns);
end

function records = lossMatrix(scene, filtered, baseOptions)
variants = [ ...
    struct(Name="planeEqual", Loss="projectionPlane2D", ...
        AllowReferenceMotion=true, UnequalPriors=false), ...
    struct(Name="rayEqual", Loss="rayToRay3D", ...
        AllowReferenceMotion=true, UnequalPriors=false), ...
    struct(Name="coplanarityEqual", Loss="epipolarCoplanarity", ...
        AllowReferenceMotion=true, UnequalPriors=false), ...
    struct(Name="planeUnequal", Loss="projectionPlane2D", ...
        AllowReferenceMotion=true, UnequalPriors=true), ...
    struct(Name="planeFixedReference", Loss="projectionPlane2D", ...
        AllowReferenceMotion=false, UnequalPriors=false)];
records = repmat(emptyLossRecord(), 1, numel(variants));
for k = 1:numel(variants)
    record = emptyLossRecord();
    record.Name = variants(k).Name;
    record.LossMode = variants(k).Loss;
    record.AllowReferenceMotion = variants(k).AllowReferenceMotion;
    record.UnequalPriors = variants(k).UnequalPriors;
    record.RawCount = matchCount(filtered);
    if record.RawCount < 3
        record.Status = "skipped";
        record.FailureReason = "Fewer than three filtered observations.";
        records(k) = record;
        continue
    end
    solveOptions = baseOptions;
    solveOptions.LossMode = variants(k).Loss;
    solveOptions.MovableParameters.AllowReferenceMotion = ...
        variants(k).AllowReferenceMotion;
    if variants(k).UnequalPriors
        ids = ProjectionLayerIdentity.idsForIndices(scene, [2 1]);
        solveOptions.PointingPriors.LayerIds = ids;
        solveOptions.PointingPriors.SigmaDegrees = ...
            [2 2 2; 0.5 0.5 0.5];
    end
    try
        timer = tic;
        result = ProjectionAlignmentOpkSolver.solve( ...
            scene, filtered, solveOptions);
        result = ProjectionAlignmentSafeSolvePolicy.apply( ...
            result, filtered, solveOptions);
        record.TotalSeconds = toc(timer);
        record.Status = result.Status;
        record.Actionable = ...
            ProjectionAlignmentSafeSolvePolicy.isActionable(result);
        record.SafetyStatus = result.Diagnostics.SafeSolvePolicy.Status;
        record.AnyBoundHit = result.Diagnostics.AnyBoundHit;
        record.PlaneRmsBefore = ...
            result.Diagnostics.Comparison.ProjectionPlane2D.RmsBefore;
        record.PlaneRmsAfter = ...
            result.Diagnostics.Comparison.ProjectionPlane2D.RmsAfter;
        record.RayRmsBefore = ...
            result.Diagnostics.Comparison.ForwardRay3D.RmsBefore;
        record.RayRmsAfter = ...
            result.Diagnostics.Comparison.ForwardRay3D.RmsAfter;
        record.CoplanarityRmsBefore = ...
            result.Diagnostics.Comparison.EpipolarCoplanarity.RmsBefore;
        record.CoplanarityRmsAfter = ...
            result.Diagnostics.Comparison.EpipolarCoplanarity.RmsAfter;
        record.CommonDeltaDegrees = ...
            result.Diagnostics.AttitudeModel.CommonDeltaDegrees;
        record.LayerDeltaDegrees = ...
            result.Diagnostics.AttitudeModel.LayerDeltaDegrees;
        record.ObservedRank = result.Diagnostics.Observability.Solution.Rank;
        record.ModeCount = ...
            numel(result.Diagnostics.Observability.Solution.Modes);
        record.WeakModeCount = ...
            numel(result.Diagnostics.Observability.Solution.WeakModes);
        if ~record.Actionable
            record.FailureReason = strjoin( ...
                result.Diagnostics.SafeSolvePolicy.Reasons, "; ");
        end
    catch ME
        record.Status = "error";
        record.FailureReason = string(ME.message);
    end
    records(k) = record;
end
end

function record = emptyLossRecord()
record = struct(Name="", LossMode="", AllowReferenceMotion=true, ...
    UnequalPriors=false, RawCount=0, Status="", Actionable=false, ...
    SafetyStatus="", AnyBoundHit=false, PlaneRmsBefore=NaN, ...
    PlaneRmsAfter=NaN, RayRmsBefore=NaN, RayRmsAfter=NaN, ...
    CoplanarityRmsBefore=NaN, CoplanarityRmsAfter=NaN, ...
    CommonDeltaDegrees=nan(1, 3), LayerDeltaDegrees=nan(2, 3), ...
    ObservedRank=NaN, ModeCount=NaN, WeakModeCount=NaN, ...
    TotalSeconds=NaN, FailureReason="");
end

function diagnostics = curationDiagnostics(filtered)
count = matchCount(filtered);
roiCount = 0;
if count > 0
    pair = filtered.Matches(1);
    points = [pair.MovingPlaneCoordinates; pair.ReferencePlaneCoordinates];
    finitePoints = points(all(isfinite(points), 2), :);
    if ~isempty(finitePoints)
        lower = prctile(finitePoints, 25, 1);
        upper = prctile(finitePoints, 75, 1);
        movingInside = all(pair.MovingPlaneCoordinates >= lower & ...
            pair.MovingPlaneCoordinates <= upper, 2);
        referenceInside = all(pair.ReferencePlaneCoordinates >= lower & ...
            pair.ReferencePlaneCoordinates <= upper, 2);
        roiCount = nnz(movingInside & referenceInside);
    end
end
diagnostics = struct(FilteredCount=count, CentralRoiCount=roiCount, ...
    ManualDisableCount=min(count, 1), ...
    ReSolveCount=max(count - 1, 0), ...
    HardMinimumSatisfiedAfterDisable=max(count - 1, 0) >= 3);
end

function diagnostics = anchorDiagnostics(scene, filtered, options)
diagnostics = struct(Status="skipped", MatchIndex=NaN, ...
    Success=false, TargetErrorMeters=NaN, ...
    CommonDeltaDegrees=nan(1, 2), DifferentialPreserved=false, ...
    KappaPreserved=false, BoundScenarioRejected=false, ...
    ForwardRayRmsBefore=NaN, ForwardRayRmsAfter=NaN, FailureReason="");
if matchCount(filtered) < 3
    diagnostics.FailureReason = "Fewer than three filtered observations.";
    return
end
pairMatch = filtered.Matches(1);
matchIndices = (1:pairMatch.Count).';
if isfield(pairMatch, "MatchRecordIndices") && ...
        numel(pairMatch.MatchRecordIndices) == pairMatch.Count
    matchIndices = pairMatch.MatchRecordIndices(:);
end
matchIndex = matchIndices(ceil(numel(matchIndices) / 2));
try
    state = ProjectionAlignmentCommonAnchor.prepare(scene, filtered, ...
        pairMatch.Pair, matchIndex, scene.layers(pairMatch.Pair(1)). ...
        CurrentProjectionPlane, options);
    requestedDelta = min([0.001 0.001], ...
        0.25 * state.CommonBoundsDegrees);
    target = state.StartingCentroid + ...
        (state.Jacobian * requestedDelta.').';
    result = ProjectionAlignmentCommonAnchor.refine(state, target);
    boundTarget = state.StartingCentroid + ...
        (state.Jacobian * (4 * state.CommonBoundsDegrees).').';
    boundResult = ProjectionAlignmentCommonAnchor.refine(state, boundTarget);
    startOpk = reshape( ...
        [state.StartingCorrections.ViewVectorAngularOffsetsDegrees], 3, []).';
    finalOpk = reshape( ...
        [result.Corrections.ViewVectorAngularOffsetsDegrees], 3, []).';
    diagnostics.Status = result.Status;
    diagnostics.MatchIndex = matchIndex;
    diagnostics.Success = result.Success;
    diagnostics.TargetErrorMeters = result.TargetErrorMeters;
    diagnostics.CommonDeltaDegrees = result.CommonDeltaDegrees;
    diagnostics.DifferentialPreserved = ...
        norm((finalOpk(1, :) - finalOpk(2, :)) - ...
        (startOpk(1, :) - startOpk(2, :))) <= 1e-10;
    diagnostics.KappaPreserved = ...
        all(abs(finalOpk(:, 3) - startOpk(:, 3)) <= 1e-12);
    diagnostics.BoundScenarioRejected = ...
        ~boundResult.Success && boundResult.AnyBoundHit;
    diagnostics.ForwardRayRmsBefore = result.ForwardRayRmsBefore;
    diagnostics.ForwardRayRmsAfter = result.ForwardRayRmsAfter;
    diagnostics.FailureReason = result.FailureReason;
catch ME
    diagnostics.Status = "error";
    diagnostics.FailureReason = string(ME.message);
end
end

function records = regressionMatrix(runTests, projectRoot)
definitions = regressionDefinitions(projectRoot);
records = repmat(emptyRegressionRecord(), 1, numel(definitions));
if ~runTests
    for k = 1:numel(definitions)
        records(k) = emptyRegressionRecord();
        records(k).Category = definitions(k).Category;
        records(k).TestName = definitions(k).TestName;
        records(k).Status = "notRun";
    end
    return
end
for k = 1:numel(definitions)
    definition = definitions(k);
    suite = matlab.unittest.TestSuite.fromFile( ...
        definition.File, Name=definition.TestName);
    result = run(suite);
    record = emptyRegressionRecord();
    record.Category = definition.Category;
    record.TestName = definition.TestName;
    record.Passed = all([result.Passed]);
    record.Failed = any([result.Failed]);
    record.Incomplete = any([result.Incomplete]);
    record.DurationSeconds = sum([result.Duration]);
    record.Status = "passed";
    if record.Failed
        record.Status = "failed";
    elseif record.Incomplete
        record.Status = "incomplete";
    end
    records(k) = record;
end
end

function definitions = regressionDefinitions(projectRoot)
definitions = [ ...
    definition("roi", fullfile(projectRoot, ...
    "tests/ProjectionViewerAlignmentWorkflowTest.m"), ...
    "ProjectionViewerAlignmentWorkflowTest/testClearingRoiRestoresPreRoiMatchesWithoutRematch"), ...
    definition("layerReorder", fullfile(projectRoot, ...
    "tests/ProjectionViewerAlignmentWorkflowTest.m"), ...
    "ProjectionViewerAlignmentWorkflowTest/testOverlayCoordinatesRemainFixedAcrossLayerReorder"), ...
    definition("manualCuration", fullfile(projectRoot, ...
    "tests/ProjectionViewerAlignmentWorkflowTest.m"), ...
    "ProjectionViewerAlignmentWorkflowTest/testOverlayClickDeleteAndUndoCuration"), ...
    definition("commonAnchor", fullfile(projectRoot, ...
    "tests/ProjectionViewerAlignmentWorkflowTest.m"), ...
    "ProjectionViewerAlignmentWorkflowTest/testShiftLeftDragAppliesAndUndoesCommonAnchor"), ...
    definition("multiImageSchedule", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testJointMultiImageSolverReportsPairwiseResiduals"), ...
    definition("pureDifferential", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testEqualPriorsSplitRelativeCorrection"), ...
    definition("sharedBiasWeakCommon", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testRegularizationKeepsPerfectInitialState"), ...
    definition("unequalPriors", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testUnequalPriorsMoveLessTrustedLayerFarther"), ...
    definition("fixedReference", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testReferenceMotionAndMovableAxesAreHonored"), ...
    definition("parallelRays", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentOpkSolverTest.m"), ...
    "ProjectionAlignmentOpkSolverTest/testRayToRayLossHandlesParallelRays"), ...
    definition("degenerateBaseline", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentCoplanarityTest.m"), ...
    "ProjectionAlignmentCoplanarityTest/testDegenerateGeometryIsFlagged"), ...
    definition("behindOrigin", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentObservationProjectorTest.m"), ...
    "ProjectionAlignmentObservationProjectorTest/testBehindSourceRayIsIndependentlyRejected"), ...
    definition("invalidEndpoint", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentObservationProjectorTest.m"), ...
    "ProjectionAlignmentObservationProjectorTest/testOneOutsideObservationDoesNotInvalidateNeighbors"), ...
    definition("obliqueRelief", fullfile(projectRoot, ...
    "tests/ProjectionAlignmentObliqueTerrainHarnessTest.m"), ...
    "ProjectionAlignmentObliqueTerrainHarnessTest/testTruthfulFiltersPreserveReliefRichCorrespondences"), ...
    definition("serializedBackend", fullfile(projectRoot, ...
    "tests/ProjectionBackendAlignmentIntegrationTest.m"), ...
    "ProjectionBackendAlignmentIntegrationTest/testSerializedBackendJobWritesAlignedStateAndDiagnostics")];
end

function value = definition(category, file, testName)
value = struct(Category=category, File=file, TestName=testName);
end

function record = emptyRegressionRecord()
record = struct(Category="", TestName="", Status="", Passed=false, ...
    Failed=false, Incomplete=false, DurationSeconds=NaN);
end

function count = matchCount(result)
count = 0;
if isstruct(result) && isfield(result, "Matches") && ~isempty(result.Matches)
    count = sum([result.Matches.Count]);
end
end

function artifacts = writeArtifacts(summary, outputDirectory)
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
jsonPath = fullfile(outputDirectory, "alignment_reliability_summary.json");
writeText(jsonPath, jsonencode(summary, PrettyPrint=true));
matPath = fullfile(outputDirectory, "alignment_reliability_summary.mat");
save(matPath, "summary");

detectors = summary.Detectors;
detectorTable = table(string({detectors.Detector}).', ...
    [detectors.ExactRepeat].', [detectors.RawCount].', ...
    [detectors.FilteredCount].', [detectors.RejectedCount].', ...
    [detectors.TerrainMedianMeters].', [detectors.TerrainP95Meters].', ...
    [detectors.TotalSeconds].', VariableNames=["Detector", "ExactRepeat", ...
    "RawCount", "FilteredCount", "RejectedCount", ...
    "TerrainMedianMeters", "TerrainP95Meters", "TotalSeconds"]);
detectorPath = fullfile(outputDirectory, "detector_matrix.csv");
writetable(detectorTable, detectorPath);

losses = summary.Losses;
lossTable = table(string({losses.Name}).', string({losses.LossMode}).', ...
    [losses.AllowReferenceMotion].', [losses.UnequalPriors].', ...
    string({losses.Status}).', [losses.Actionable].', ...
    [losses.AnyBoundHit].', [losses.PlaneRmsBefore].', ...
    [losses.PlaneRmsAfter].', [losses.RayRmsBefore].', ...
    [losses.RayRmsAfter].', [losses.CoplanarityRmsBefore].', ...
    [losses.CoplanarityRmsAfter].', [losses.ObservedRank].', ...
    [losses.ModeCount].', [losses.WeakModeCount].', ...
    [losses.TotalSeconds].', string({losses.FailureReason}).', ...
    VariableNames=["Name", "LossMode", "AllowReferenceMotion", ...
    "UnequalPriors", "Status", "Actionable", "AnyBoundHit", ...
    "PlaneRmsBefore", "PlaneRmsAfter", "RayRmsBefore", ...
    "RayRmsAfter", "CoplanarityRmsBefore", "CoplanarityRmsAfter", ...
    "ObservedRank", "ModeCount", "WeakModeCount", "TotalSeconds", ...
    "FailureReason"]);
lossPath = fullfile(outputDirectory, "loss_matrix.csv");
writetable(lossTable, lossPath);

regressions = summary.ContractRegressions;
regressionTable = table(string({regressions.Category}).', ...
    string({regressions.TestName}).', string({regressions.Status}).', ...
    [regressions.Passed].', [regressions.Failed].', ...
    [regressions.Incomplete].', [regressions.DurationSeconds].', ...
    VariableNames=["Category", "TestName", "Status", "Passed", ...
    "Failed", "Incomplete", "DurationSeconds"]);
regressionPath = fullfile(outputDirectory, "contract_regression_matrix.csv");
writetable(regressionTable, regressionPath);
artifacts = struct(OutputDirectory=string(outputDirectory), ...
    SummaryPath=string(jsonPath), MatPath=string(matPath), ...
    DetectorMatrixPath=string(detectorPath), ...
    LossMatrixPath=string(lossPath), ...
    RegressionMatrixPath=string(regressionPath));
end

function writeText(filePath, value)
fileId = fopen(filePath, "w");
if fileId < 0
    error("alignment_reliability_validation:fileWriteFailed", ...
        "Unable to open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanup
end

function printSummary(summary, artifacts)
fprintf("Alignment reliability validation: %s\n", artifacts.OutputDirectory);
fprintf("Selected detector: %s\n", summary.SelectedDetector);
for record = summary.Detectors
    fprintf("  %s raw=%d filtered=%d repeat=%d truth p95=%.3g m\n", ...
        record.Detector, record.RawCount, record.FilteredCount, ...
        record.ExactRepeat, record.TerrainP95Meters);
end
for record = summary.Losses
    fprintf("  %s status=%s safe=%s ray %.3g -> %.3g\n", ...
        record.Name, record.Status, record.SafetyStatus, ...
        record.RayRmsBefore, record.RayRmsAfter);
end
if ~isempty(summary.ContractRegressions)
    fprintf("Contract regressions: %d passed, %d failed, %d incomplete\n", ...
        nnz([summary.ContractRegressions.Passed]), ...
        nnz([summary.ContractRegressions.Failed]), ...
        nnz([summary.ContractRegressions.Incomplete]));
end
end
