classdef ProjectionAlignmentModelTest < matlab.unittest.TestCase
    %ProjectionAlignmentModelTest Tests for alignment request/result contracts.

    properties (Constant)
        Tol = 1e-10
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            srcFolder = fullfile(projectRoot, "src");
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(srcFolder));
        end
    end

    methods (Test)
        function testOptionsDefaultsCoverAlignmentPipeline(testCase)
            options = ProjectionAlignmentOptions.defaults();

            testCase.verifyEqual(options.Format, ProjectionAlignmentOptions.Format);
            testCase.verifyEqual(options.Detector.Method, "auto");
            testCase.verifyEqual(options.Matcher.Method, "nearestNeighborRatio");
            testCase.verifyEqual(options.FilterPipeline.Stages, ...
                ["overlapMask", "descriptorScore", "ratio", ...
                "geometricOutlier", "nativeDisplacement", "radial"]);
            testCase.verifyEqual(options.FilterPipeline.NativeDisplacementMethod, ...
                "none");
            testCase.verifyEqual(options.LossMode, "projectionPlane2D");
            testCase.verifyEqual(options.Scheduling.Strategy, "centerOut");
            testCase.verifyEqual(options.MovableParameters.Parameters, ...
                ["omega", "phi", "kappa"]);
            testCase.verifyTrue(options.MovableParameters.AllowReferenceMotion);
            testCase.verifyFalse(options.MovableParameters.IncludeProjectionOffsets);
            testCase.verifyFalse(options.MovableParameters.IncludeSharedScale);
            testCase.verifyEqual(options.Bounds.FieldOfViewFraction, 0.25, ...
                AbsTol=ProjectionAlignmentModelTest.Tol);
            testCase.verifyEqual(options.Bounds.SharedScale, [0.95 1.05], ...
                AbsTol=ProjectionAlignmentModelTest.Tol);
            testCase.verifyGreaterThan(options.Regularization.OverallWeight, 0);
            testCase.verifyGreaterThan( ...
                options.Regularization.SharedScaleWeight, 0);
            testCase.verifyTrue(options.Diagnostics.StoreTiming);
            testCase.verifyEqual(options.Execution.Mode, "serial");
            testCase.verifyFalse(options.Execution.UseGPU);
        end

        function testOptionsRejectUnsupportedDetector(testCase)
            options = struct(Detector=struct(Method="notAFeatureDetector"));

            testCase.verifyError( ...
                @() ProjectionAlignmentOptions.validate(options), ...
                "ProjectionAlignmentOptions:invalidChoice");
        end

        function testOptionsRejectProcessPoolExecution(testCase)
            options = struct(Execution=struct(Mode="processes"));

            testCase.verifyError( ...
                @() ProjectionAlignmentOptions.validate(options), ...
                "ProjectionAlignmentOptions:invalidChoice");
        end

        function testRequestDefaultsUseMiddleReferenceAndBandOne(testCase)
            request = ProjectionAlignmentRequest.validate( ...
                struct(LayerIndices=[1 2 3]));

            testCase.verifyEqual(request.Format, ProjectionAlignmentRequest.Format);
            testCase.verifyEqual(request.LayerIndices, [1 2 3]);
            testCase.verifyEqual(request.ReferenceLayerIndex, 2);
            testCase.verifyEqual(request.AnalysisBands, [1 1 1]);
            testCase.verifyEqual(request.Options.LossMode, "projectionPlane2D");
        end

        function testRequestRejectsAnalysisBandMismatch(testCase)
            request = struct(LayerIndices=[1 2 3], AnalysisBands=[1 2]);

            testCase.verifyError( ...
                @() ProjectionAlignmentRequest.validate(request), ...
                "ProjectionAlignmentRequest:analysisBandMismatch");
        end

        function testResultDefaultsContainRequiredFields(testCase)
            request = struct(LayerIndices=[1 2 3]);

            result = ProjectionAlignmentResult.empty(request);

            testCase.verifyEqual(result.Format, ProjectionAlignmentResult.Format);
            testCase.verifyEqual(result.Status, "notRun");
            testCase.verifyEqual(result.RequestSummary.LayerIndices, [1 2 3]);
            testCase.verifyTrue(isfield(result, "Matches"));
            testCase.verifyTrue(isfield(result, "Inliers"));
            testCase.verifyTrue(isfield(result, "Residuals"));
            testCase.verifyTrue(isfield(result, "SolvedCorrections"));
            testCase.verifyTrue(isfield(result, "Convergence"));
            testCase.verifyTrue(isfield(result, "Warnings"));
            testCase.verifyTrue(isfield(result, "Timing"));
        end

        function testRequestJsonRoundTripPreservesOptions(testCase)
            request = ProjectionAlignmentModelTest.makeRequest();

            jsonText = ProjectionAlignmentRequest.encode(request);
            decoded = ProjectionAlignmentRequest.decode(jsonText);

            testCase.verifyTrue(contains(jsonText, '"ProjectionAlignmentRequest"'));
            testCase.verifyEqual(decoded.LayerIndices, [1 2 3]);
            testCase.verifyEqual(decoded.ReferenceLayerIndex, 2);
            testCase.verifyEqual(decoded.AnalysisBands, [1 2 1]);
            testCase.verifyEqual(decoded.Options.Detector.Method, "surf");
            testCase.verifyEqual(decoded.Options.Scheduling.Strategy, "adjacentChain");
            testCase.verifyEqual(decoded.Options.MovableParameters.Parameters, ...
                ["omega", "kappa"]);
            testCase.verifyTrue(decoded.Options.Diagnostics.StoreWorkingImages);
        end

        function testResultJsonRoundTripPreservesDiagnostics(testCase)
            result = ProjectionAlignmentModelTest.makeSolvedResult();

            jsonText = ProjectionAlignmentResult.encode(result);
            decoded = ProjectionAlignmentResult.decode(jsonText);

            testCase.verifyTrue(contains(jsonText, '"ProjectionAlignmentResult"'));
            testCase.verifyEqual(decoded.Status, "solved");
            testCase.verifyEqual(decoded.Matches.Count, 2);
            testCase.verifyEqual(decoded.Inliers.Mask, [true false]);
            testCase.verifyEqual(decoded.Residuals.After, [0.5 0.7], ...
                AbsTol=ProjectionAlignmentModelTest.Tol);
            testCase.verifyEqual( ...
                decoded.SolvedCorrections.ViewVectorAngularOffsetsDegrees, ...
                [0.1 -0.2 0.03], AbsTol=ProjectionAlignmentModelTest.Tol);
            testCase.verifyTrue(decoded.Convergence.Success);
            testCase.verifyEqual(decoded.Warnings, "low match count");
            testCase.verifyEqual(decoded.Timing.TotalSeconds, 0.7, ...
                AbsTol=ProjectionAlignmentModelTest.Tol);
        end
    end

    methods (Static, Access = private)
        function request = makeRequest()
            options = struct();
            options.Detector = struct(Method="surf", MaxFeatures=100);
            options.Matcher = struct(MaxRatio=0.7);
            options.Scheduling = struct(Strategy="adjacentChain");
            options.MovableParameters = struct( ...
                Parameters=["omega", "kappa"], ...
                AllowReferenceMotion=false);
            options.Bounds = struct(OmegaDegrees=0.2);
            options.Diagnostics = struct(StoreWorkingImages=true);
            request = struct( ...
                LayerIndices=[1 2 3], ...
                ReferenceLayerIndex=2, ...
                AnalysisBands=[1 2 1], ...
                Options=options, ...
                Metadata=struct(Source="unit-test"));
        end

        function result = makeSolvedResult()
            result = struct();
            result.Status = "solved";
            result.RequestSummary = struct( ...
                LayerIndices=[1 2], ...
                ReferenceLayerIndex=1, ...
                AnalysisBands=[1 1], ...
                LossMode="projectionPlane2D", ...
                SchedulingStrategy="twoImage", ...
                MovableParameters=["omega", "phi", "kappa"]);
            result.Matches = struct( ...
                Pair=[1 2], ...
                MovingPoints=[10 11; 12 13], ...
                ReferencePoints=[10.5 11.5; 12.5 13.5], ...
                MovingProjectionPoints=[0 0; 1 1], ...
                ReferenceProjectionPoints=[0.1 0.2; 1.1 1.2], ...
                Scores=[0.9; 0.8], ...
                DescriptorIndices=[1 3; 2 4], ...
                Count=2);
            result.Inliers = struct( ...
                Pair=[1 2], ...
                Mask=[true false], ...
                Count=1, ...
                Method="geometric");
            result.Residuals = struct( ...
                LossMode="projectionPlane2D", ...
                Unit="pixels", ...
                Before=[2 3], ...
                After=[0.5 0.7], ...
                PerPair=struct(Pair=[1 2], Before=[2 3], ...
                After=[0.5 0.7], Count=2));
            result.SolvedCorrections = struct( ...
                LayerIndex=2, ...
                ViewVectorAngularOffsetsDegrees=[0.1 -0.2 0.03], ...
                ProjectionOffsetMeters=[0 0], ...
                SharedScale=1);
            result.Convergence = struct( ...
                Status="converged", ...
                Success=true, ...
                Iterations=4, ...
                ExitFlag=1, ...
                Objective=0.25, ...
                FirstOrderOptimality=1e-4, ...
                Message="done");
            result.Warnings = "low match count";
            result.Timing = struct( ...
                StartedAt="2026-07-03T12:00:00Z", ...
                FinishedAt="2026-07-03T12:00:01Z", ...
                TotalSeconds=0.7, ...
                StageSeconds=struct(Matching=0.2, Solver=0.5));
            result.Diagnostics = struct(MatchCount=2);
        end
    end
end
