classdef ProjectionFullSourceInverseWarpTest < matlab.unittest.TestCase
    %ProjectionFullSourceInverseWarpTest Full-source backend warp contracts.

    properties (Constant)
        Tol = 1e-9
    end

    methods (TestClassSetup)
        function addSourceToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "scripts")));
        end
    end

    methods (Test)
        function testIdentityNearestReturnsEverySingleBandPixel(testCase)
            imageData = reshape(1:30, 5, 6);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 1);
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[5 6]));

            readback = ProjectionReadbackRenderer.renderScene(scene, struct( ...
                OutputGrid=outputGrid, Interpolation="nearest"));

            testCase.verifyEqual(readback.Image, imageData);
            testCase.verifyTrue(all(readback.ValidMask, "all"));
            testCase.verifyEqual(readback.RenderPlan.NumericalMode, ...
                "fullSourceInverseWarp");
        end

        function testMappingAndRadiometryAreSeparateAndPrecise(testCase)
            imageData = ProjectionFullSourceInverseWarpTest.linearImage(5, 6);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 1);
            layer = scene.layers;
            mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                layer, layer.CurrentProjectionPlane, scene.renderOrigin);
            model = ProjectionFullSourceInverseWarp.prepare( ...
                mesh, layer.CurrentProjectionPlane, [5 6]);
            queryPlaneCoordinates = [1.25; -2.25];

            mapping = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                model, queryPlaneCoordinates, [1 1]);
            bilinear = ProjectionFullSourceInverseWarp.sampleImage( ...
                imageData, mapping, "bilinear", -1);
            nearest = ProjectionFullSourceInverseWarp.sampleImage( ...
                imageData, mapping, "nearest", -1);

            testCase.verifyEqual(mapping.RowCoordinates, 3.25, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual(mapping.ColumnCoordinates, 2.25, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual(bilinear, 34.75, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual(nearest, 32, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
        end

        function testProjectionTranslationShiftsSourceWithoutChangingGeometry(testCase)
            imageData = reshape(1:30, 5, 6);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 1);
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[5 6]));
            scene.layers.ProjectionOffsetMeters = [1; 0];

            shifted = ProjectionReadbackRenderer.renderScene(scene, struct( ...
                OutputGrid=outputGrid, Interpolation="nearest", ...
                InvalidFillValue=-999));

            expected = [zeros(5, 1), imageData(:, 1:end - 1)];
            testCase.verifyEqual(shifted.Image, expected);
            testCase.verifyFalse(any(shifted.ValidMask(:, 1)));
            testCase.verifyTrue(all(shifted.ValidMask(:, 2:end), "all"));
            testCase.verifyEqual( ...
                shifted.LayerReadbacks.Image(:, 1), ...
                -999 * ones(5, 1));
        end

        function testOpkChangesInverseCoordinatesOnFixedOutputGrid(testCase)
            imageData = ProjectionFullSourceInverseWarpTest.linearImage(9, 11);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 2);
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[9 11]));
            basePlan = ProjectionBackendRenderPlan.compile( ...
                scene, struct(OutputGrid=outputGrid));
            baseReadback = ProjectionReadbackRenderer.renderPlan(basePlan);
            queryPlaneCoordinates = PlanarProjection.worldToPlane( ...
                baseReadback.CameraGrid.QueryWorldPoints, ...
                scene.layers.CurrentProjectionPlane);
            baseMap = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                basePlan.Layers.InverseWarp, queryPlaneCoordinates, [9 11]);
            scene.layers.ViewVectorAngularOffsetsDegrees = [0.4; -0.3; 0.2];

            opkPlan = ProjectionBackendRenderPlan.compile( ...
                scene, struct(OutputGrid=outputGrid));
            opkMap = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                opkPlan.Layers.InverseWarp, queryPlaneCoordinates, [9 11]);
            commonMask = baseMap.ValidMask & opkMap.ValidMask;
            coordinateChange = max([ ...
                abs(opkMap.RowCoordinates(commonMask) - ...
                baseMap.RowCoordinates(commonMask)); ...
                abs(opkMap.ColumnCoordinates(commonMask) - ...
                baseMap.ColumnCoordinates(commonMask))]);

            testCase.verifyGreaterThan(nnz(commonMask), 0);
            testCase.verifyGreaterThan(coordinateChange, 1e-4);
            testCase.verifyEqual( ...
                opkPlan.Layers.Mesh.ViewVectorAngularOffsetsDegrees, ...
                [0.4; -0.3; 0.2], ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
        end

        function testObliquePlaneMapsMeshVerticesBackToTheirIndices(testCase)
            imageData = zeros(7, 8);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 2);
            layer = scene.layers;
            layer.CurrentProjectionPlane = ProjectionMeshBuilder.applyPlaneTipTilt( ...
                layer.BaseProjectionPlane, deg2rad(8), deg2rad(-6));
            mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                layer, layer.CurrentProjectionPlane, scene.renderOrigin);
            model = ProjectionFullSourceInverseWarp.prepare( ...
                mesh, layer.CurrentProjectionPlane, [7 8]);
            queryPlaneCoordinates = PlanarProjection.worldToPlane( ...
                reshape(mesh.WorldPoints, 3, []), layer.CurrentProjectionPlane);

            mapping = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                model, queryPlaneCoordinates, size(mesh.X));
            expectedRows = repmat(mesh.RowIndices(:), 1, ...
                numel(mesh.ColumnIndices));
            expectedColumns = repmat(mesh.ColumnIndices(:).', ...
                numel(mesh.RowIndices), 1);

            testCase.verifyEqual(mapping.RowCoordinates, expectedRows, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual(mapping.ColumnCoordinates, expectedColumns, ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyTrue(all(mapping.ValidMask, "all"));
        end

        function testInvalidCoordinatesUseFillAndMask(testCase)
            imageData = ProjectionFullSourceInverseWarpTest.linearImage(5, 6);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 1);
            mesh = ProjectionMeshBuilder.buildLayerMesh( ...
                scene.layers, scene.layers.CurrentProjectionPlane, ...
                scene.renderOrigin);
            model = ProjectionFullSourceInverseWarp.prepare( ...
                mesh, scene.layers.CurrentProjectionPlane, [5 6]);
            queryPlaneCoordinates = [1, 100; -2, 100];

            mapping = ProjectionFullSourceInverseWarp.mapCoordinates( ...
                model, queryPlaneCoordinates, [1 2]);
            [sampled, validMask] = ProjectionFullSourceInverseWarp.sampleImage( ...
                imageData, mapping, "bilinear", -999);

            testCase.verifyEqual(sampled(1), imageData(3, 2), ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual(sampled(2), -999);
            testCase.verifyEqual(validMask, [true false]);
        end

        function testRgbBandsShareOneSourceCoordinateWarp(testCase)
            base = ProjectionFullSourceInverseWarpTest.linearImage(5, 6);
            imageData = cat(3, base, base + 100, base + 200);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 2);
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[7 9]));

            readback = ProjectionReadbackRenderer.renderScene(scene, struct( ...
                OutputGrid=outputGrid, Interpolation="bilinear"));
            mask = readback.ValidMask;

            testCase.verifySize(readback.Image, [7 9 3]);
            testCase.verifyEqual( ...
                readback.Image(:, :, 2) - readback.Image(:, :, 1), ...
                100 * double(mask), ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
            testCase.verifyEqual( ...
                readback.Image(:, :, 3) - readback.Image(:, :, 1), ...
                200 * double(mask), ...
                AbsTol=ProjectionFullSourceInverseWarpTest.Tol);
        end

        function testArbitraryBandsAreAllSampledFromFullSource(testCase)
            base = ProjectionFullSourceInverseWarpTest.linearImage(6, 7);
            imageData = cat(3, base, base + 10, base + 20, base + 30);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                imageData, 3);
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[6 7]));

            readback = ProjectionReadbackRenderer.renderScene(scene, struct( ...
                OutputGrid=outputGrid, Interpolation="nearest"));

            testCase.verifySize(readback.Image, [6 7 4]);
            testCase.verifyEqual(readback.Image, imageData);
        end

        function testFullSourceIgnoresDisplayTextureAndQuantifiesSparseDifference(testCase)
            [columnGrid, rowGrid] = meshgrid(1:9, 1:9);
            checkerboard = mod(rowGrid + columnGrid, 2);
            scene = ProjectionFullSourceInverseWarpTest.makeAnalyticScene( ...
                checkerboard, 4);
            scene.layers.DisplayTexture = zeros(2, 2, 3, "single");
            outputGrid = ProjectionBackendOutputGrid.plan(scene, ...
                struct(OutputSize=[9 9]));
            baseOptions = struct(OutputGrid=outputGrid, ...
                Interpolation="nearest");

            fullSource = ProjectionReadbackRenderer.renderScene(scene, ...
                ProjectionFullSourceInverseWarpTest.withMode( ...
                baseOptions, "fullSourceInverseWarp"));
            sparse = ProjectionReadbackRenderer.renderScene(scene, ...
                ProjectionFullSourceInverseWarpTest.withMode( ...
                baseOptions, "sparseIntensityScatteredInterpolant"));
            comparison = ProjectionFullSourceInverseWarp.compareReadbacks( ...
                fullSource, sparse);

            testCase.verifyEqual(fullSource.Image, checkerboard);
            testCase.verifyEqual(sparse.Image, zeros(9, 9));
            testCase.verifyGreaterThan( ...
                comparison.Bands.MeanAbsoluteError, 0.4);
            testCase.verifyEqual(comparison.ValidMaskMismatchCount, 0);
            testCase.verifyEqual(fullSource.RenderPlan.NumericalMode, ...
                "fullSourceInverseWarp");
            testCase.verifyEqual(sparse.RenderPlan.NumericalMode, ...
                "sparseIntensityScatteredInterpolant");
        end

        function testCompatibilityEvaluationReportsBothModes(testCase)
            summary = backend_inverse_warp_evaluation(struct( ...
                ImageSize=[64 80], OutputSize=[40 50], MeshStride=8, ...
                PatternCycles=16, WriteArtifacts=false));

            testCase.verifyTrue(summary.CpuComplete);
            testCase.verifyEqual(summary.FullSourcePlan.NumericalMode, ...
                "fullSourceInverseWarp");
            testCase.verifyEqual(summary.SparseReferencePlan.NumericalMode, ...
                "sparseIntensityScatteredInterpolant");
            testCase.verifyGreaterThan( ...
                summary.Comparison.CommonValidPixelCount, 0);
            testCase.verifyGreaterThan( ...
                summary.Comparison.Bands.MeanAbsoluteError, 0);
        end
    end

    methods (Static, Access = private)
        function scene = makeAnalyticScene(imageData, stride)
            imageSize = [size(imageData, 1), size(imageData, 2)];
            rowIndices = 1:imageSize(1);
            columnIndices = 1:imageSize(2);
            origins = [columnIndices; zeros(1, imageSize(2)); ...
                10 * ones(1, imageSize(2))];
            viewVectors = zeros(3, imageSize(1), imageSize(2));
            for rowIndex = 1:imageSize(1)
                for columnIndex = 1:imageSize(2)
                    viewVectors(:, rowIndex, columnIndex) = ...
                        [0; -rowIndex; -10];
                end
            end
            sourceOptions = struct( ...
                ReferenceOrigin=[(imageSize(2) + 1) / 2; 0; 10], ...
                OpticalAxis=[0; 0; -1], PlatformDirection=[1; 0; 0], ...
                RowAxis=[0; -1; 0], ImageXAxis=[1; 0; 0], ...
                ImageYAxis=[0; -1; 0], GSD=1, ...
                PlatformStepMeters=1, NominalRange=10);
            sourceGeometry = ProjectionSourceGeometry.fromGrid( ...
                imageSize, rowIndices, columnIndices, origins, ...
                viewVectors, sourceOptions);
            plane = PlanarProjection.definePlaneFromBasis( ...
                [1; -1; 0], [1; 0; 0], [0; 1; 0]);
            frameCamera = PlanarProjection.defineFrameCamera( ...
                sourceOptions.ReferenceOrigin, sourceOptions.OpticalAxis, ...
                1, plane);
            layer = struct();
            layer.Name = "Analytic";
            layer.Image = imageData;
            layer.DisplayTexture = ...
                ProjectionViewerHarness.prepareDisplayTexture(imageData);
            layer.ImagePath = "analytic.tif";
            layer.ImageMetadata = struct(ImageSize=imageSize, ...
                BandCount=size(imageData, 3), Class=string(class(imageData)));
            layer.SourceGeometry = sourceGeometry;
            layer.BaseProjectionPlane = plane;
            layer.CurrentProjectionPlane = plane;
            layer.MeshSampling = ProjectionViewerHarness.createMeshSampling( ...
                imageSize, stride, stride);
            layer.ProjectionOffsetMeters = [0; 0];
            layer.ViewVectorAngularOffsetsDegrees = [0; 0; 0];
            layer.Alpha = 1;
            layer.BlendMode = "alpha";
            layer.Visible = true;
            scene = struct(frameCamera=frameCamera, renderOrigin=plane.P0, ...
                preview=struct(), renderOptions=struct(), layers=layer);
        end

        function imageData = linearImage(rowCount, columnCount)
            [columns, rows] = meshgrid(1:columnCount, 1:rowCount);
            imageData = 10 * rows + columns;
        end

        function options = withMode(options, mode)
            options.NumericalMode = mode;
        end
    end
end
